peac_dev/force-app/main/default/objects/Report_Subscription__c/Report_Subscription__c.object-meta.xml
<CustomObject>
    <label>Report Subscription</label>
    <nameField>
        <displayFormat>RS-{0000}</displayFormat>
        <label>Report Subscription Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Report Subscriptions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

peac_dev/force-app/main/default/objects/Report_Subscription__c/fields/Day__c.field-meta.xml
<CustomField>
    <fullName>Day__c</fullName>
    <label>Day</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
            </value>
            <value>
                <fullName>2</fullName>
            </value>
            <value>
                <fullName>3</fullName>
            </value>
            <value>
                <fullName>4</fullName>
            </value>
            <value>
                <fullName>5</fullName>
            </value>
            <value>
                <fullName>6</fullName>
            </value>
            <value>
                <fullName>7</fullName>
            </value>
            <value>
                <fullName>8</fullName>
            </value>
            <value>
                <fullName>9</fullName>
            </value>
            <value>
                <fullName>10</fullName>
            </value>
            <value>
                <fullName>11</fullName>
            </value>
            <value>
                <fullName>12</fullName>
            </value>
            <value>
                <fullName>13</fullName>
            </value>
            <value>
                <fullName>14</fullName>
            </value>
            <value>
                <fullName>15</fullName>
            </value>
            <value>
                <fullName>16</fullName>
            </value>
            <value>
                <fullName>17</fullName>
            </value>
            <value>
                <fullName>18</fullName>
            </value>
            <value>
                <fullName>19</fullName>
            </value>
            <value>
                <fullName>20</fullName>
            </value>
            <value>
                <fullName>21</fullName>
            </value>
            <value>
                <fullName>22</fullName>
            </value>
            <value>
                <fullName>23</fullName>
            </value>
            <value>
                <fullName>24</fullName>
            </value>
            <value>
                <fullName>25</fullName>
            </value>
            <value>
                <fullName>26</fullName>
            </value>
            <value>
                <fullName>27</fullName>
            </value>
            <value>
                <fullName>28</fullName>
            </value>
            <value>
                <fullName>29</fullName>
            </value>
            <value>
                <fullName>30</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

peac_dev/force-app/main/default/objects/Report_Subscription__c/fields/Report__c.field-meta.xml
<CustomField>
    <fullName>Report__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Report</label>
    <length>18</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

peac_dev/force-app/main/default/objects/Report_Subscription__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Report_Subscriptions</relationshipName>
    <type>Lookup</type>
</CustomField>

peac_dev/force-app/main/default/objects/Report_Subscription__c/fields/WeekDay__c.field-meta.xml
<CustomField>
    <fullName>WeekDay__c</fullName>
    <label>WeekDay</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Sunday</fullName>
            </value>
            <value>
                <fullName>Monday</fullName>
            </value>
            <value>
                <fullName>Tuesday</fullName>
            </value>
            <value>
                <fullName>Wednesday</fullName>
            </value>
            <value>
                <fullName>Thursday</fullName>
            </value>
            <value>
                <fullName>Friday</fullName>
            </value>
            <value>
                <fullName>Saturday</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

peac_dev/force-app/main/default/classes/SL_DPReportsSchedule.cls
public with sharing class SL_DPReportsSchedule implements Schedulable {
    public void execute(SchedulableContext ctx) {
        sendDPReportEmails();
    }

    public static void sendDPReportEmails(){
        List<Messaging.SingleEmailMessage> mailPouch = new List<Messaging.SingleEmailMessage>();
        List <OrgWideEmailAddress> noreply = new List <OrgWideEmailAddress> ([SELECT Id, Address, DisplayName from OrgWideEmailAddress WHERE address = 'noreply@peacsolutions.com']);
        List<EmailTemplate> templateToUse = [SELECT Id, Name, DeveloperName,  FolderName 
            FROM EmailTemplate WHERE Folder.Name = 'Email Notification' AND DeveloperName = 'Service_Passthrough_Notification'];
        Id templateId = null;
        if(templateToUse.size() > 0){
            templateId = templateToUse[0].Id;
            for(Report_Subscription__c subscription : [SELECT Id, Name, User__r.Email, User__r.ContactId, User__r.Contact.Email,
                Report__c, Frequency__c, WeekDay__c, Day__c 
                FROM Report_Subscription__c]){
                String toAddress = subscription.User__r.Email != null? subscription.User__r.Email: subscription.User__r.Contact.Email;
                if(toAddress != null
                    && (subscription.Frequency__c == 'Monthly' && subscription.Day__c == String.valueOf(Date.today().day()))
                    || (subscription.Frequency__c == 'Weekly' && subscription.WeekDay__c == Datetime.now().format('EEEE'))
                    || subscription.Frequency__c == 'Daily'){
                    Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();
                    mail.setTemplateId(templateId);
                    mail.setWhatId(subscription.Id);
                    mail.setTargetObjectId(subscription.User__r.ContactId);
                    mail.setToAddresses(new String[] {toAddress});
                    if(noreply.size() > 0){
                        mail.setOrgWideEmailAddressId(noreply[0].Id);
                    }
                    mail.saveAsActivity = false;
                    mailPouch.add(mail);
                }
            }
        }
        if(mailPouch.size() > 0 && !Test.isRunningTest()){
            Messaging.sendEmail(mailPouch);
        }
    }
}