peac_dev/force-app/main/default/objects/Report_Subscription__c/Report_Subscription__c.object-meta.xml
<CustomObject>
    <label>Report Subscription</label>
    <nameField>
        <displayFormat>RS-{0000}</displayFormat>
        <label>Report Subscription Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Report Subscriptions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

peac_dev/force-app/main/default/objects/Report_Subscription__c/fields/Report__c.field-meta.xml
<CustomField>
    <fullName>Report__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Report</label>
    <length>18</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

peac_dev/force-app/main/default/objects/Report_Subscription__c/fields/Url__c.field-meta.xml
<CustomField>
    <fullName>Url__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Url</label>
    <length>180</length>
    <type>Text</type>
</CustomField>

peac_dev/force-app/main/default/objects/Report_Subscription__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Report_Subscriptions</relationshipName>
    <type>Lookup</type>
</CustomField>

peac_dev/force-app/main/default/objects/Subscribable_Report__mdt/Subscribable_Report__mdt.object-meta.xml
<CustomObject>
    <label>Subscribable Report</label>
    <pluralLabel>Subscribable Reports</pluralLabel>
</CustomObject>

peac_dev/force-app/main/default/objects/Subscribable_Report__mdt/fields/Email_Template__c.field-meta.xml
<CustomField>
    <fullName>Email_Template__c</fullName>
    <label>Email Template</label>
    <length>118</length>
    <type>Text</type>
</CustomField>

peac_dev/force-app/main/default/objects/Subscribable_Report__mdt/fields/Report__c.field-meta.xml
<CustomField>
    <fullName>Report__c</fullName>
    <label>Report</label>
    <length>118</length>
    <type>Text</type>
</CustomField>

peac_dev/force-app/main/default/classes/SL_DPReportsScheduleTest.cls
@isTest
public with sharing class SL_DPReportsScheduleTest {
    @isTest
    static void schedule(){
        SL_SCTestData.createAccountAndContracts(1, 1);
        Subscribable_Report__mdt anyReport = [SELECT Id, Label, DeveloperName, Report__c, Email_Template__c
            FROM Subscribable_Report__mdt LIMIT 1];
        // Report theActualReport = [SELECT Id, Name, DeveloperName
        //     FROM Report WHERE DeveloperName = :anyReport.Report__c LIMIT 1];
        User dpUser = SL_SCTestData.createDPUser(SL_SCTestData.testAccounts[0].Id);
        insert new Report_Subscription__c(Report__c = 'fakeId', User__c = dpUser.Id, 
            Url__c = 'https://fake.url/report/', Frequency__c = 'Daily');
        Test.startTest();
        System.schedule('Test Insurance Follow-up', '0 0 3 * * ?' , new SL_DPReportsSchedule());
        Test.stopTest();
        System.assert(true);
    }
}