peac_dev/force-app/main/default/objects/Loan_Contract__c/Loan_Contract__c.object-meta.xml
<CustomObject>
    <label>Loan Contract</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Contract Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Loan Contracts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

peac_dev/force-app/main/default/objects/Loan_Contract__c/fields/Contract_Status__c.field-meta.xml
<CustomField>
    <fullName>Contract_Status__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Contract Status</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

peac_dev/force-app/main/default/objects/Loan_Contract__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Loan Contracts</relationshipLabel>
    <relationshipName>Loan_Contracts</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

peac_dev/force-app/main/default/classes/TC_GetContractNumberMapTest.cls
@isTest
public with sharing class TC_GetContractNumberMapTest {
    @TestSetup
    static void dataSetup(){

        Account acc = new Account (
            Name = 'test', 
            CCID__c = '9000000',
            RecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('End User Account').getRecordTypeId()
        );
        insert acc;

        Opportunity opp = new Opportunity(
            AccountId = acc.Id,
            CloseDate = date.today()+5,
            StageName = 'test',
            Name = 'test'
        );
        insert opp;

        Loan_Contract__c lc = new Loan_Contract__c(Opportunity__c = opp.Id, Contract_Status__c = 'Active', Name = 'TestRecordR222');
        insert lc;
    }

    @IsTest
    public static void GetContractNumberMapTest(){

            Opportunity opp = [SELECT Id, StageName,CCID__c FROM Opportunity];
            try{
                TC_GetContractNumberMap.getContractNumberMap(new set<Id>{opp.Id});
                }
                catch (DmlException e) {
                    System.debug(e.getMessage());
                    System.debug(e.getStackTraceString());
                }
                catch (Exception e) {
                    System.debug(e.getMessage());
                    System.debug(e.getStackTraceString());
                }
    }
}