peac_dev/force-app/main/default/objects/Dealer__c/Dealer__c.object-meta.xml
<CustomObject>
    <label>Dealer</label>
    <nameField>
        <displayFormat>B-{0000}</displayFormat>
        <label>Dealer Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Dealers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

peac_dev/force-app/main/default/objects/Dealer__c/fields/Dealer__c.field-meta.xml
<CustomField>
    <fullName>Dealer__c</fullName>
    <label>Account</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Dealer Account, Dealer_Account Development, Dealer_Account Penetration, Dealer_Close, Dealer_Discovery, Dealer_Proposal, Dealer_Qualification</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Dealer Opportunities</relationshipLabel>
    <relationshipName>Dealers</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

peac_dev/force-app/main/default/objects/Dealer__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipName>Brokers</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

peac_dev/force-app/main/default/objects/Dealer__c/fields/Primary_Dealer__c.field-meta.xml
<CustomField>
    <fullName>Primary_Dealer__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Indicates if the dealer is primary dealer.</description>
    <label>Primary Dealer</label>
    <type>Checkbox</type>
</CustomField>

peac_dev/force-app/main/default/objects/Gl_Code__c/Gl_Code__c.object-meta.xml
<CustomObject>
    <label>Gl Code</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Gl Code Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>GL Codes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

peac_dev/force-app/main/default/objects/Miscellaneous_Invoice_Item__c/Miscellaneous_Invoice_Item__c.object-meta.xml
<CustomObject>
    <label>Miscellaneous Invoice Item</label>
    <nameField>
        <displayFormat>MI-{0}</displayFormat>
        <label>Miscellaneous Invoice Item Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Miscellaneous Invoice Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

peac_dev/force-app/main/default/objects/Miscellaneous_Invoice_Item__c/fields/CB_Disp__c.field-meta.xml
<CustomField>
    <fullName>CB_Disp__c</fullName>
    <defaultValue>false</defaultValue>
    <label>CB/Disp</label>
    <type>Checkbox</type>
</CustomField>

peac_dev/force-app/main/default/objects/Miscellaneous_Invoice_Item__c/fields/Dealer__c.field-meta.xml
<CustomField>
    <fullName>Dealer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Dealer</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Miscellaneous Invoice Items</relationshipLabel>
    <relationshipName>Miscellaneous_Invoice_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

peac_dev/force-app/main/default/objects/Miscellaneous_Invoice_Item__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Misc Item Description</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

peac_dev/force-app/main/default/objects/Miscellaneous_Invoice_Item__c/fields/GL_Code__c.field-meta.xml
<CustomField>
    <fullName>GL_Code__c</fullName>
    <label>GL Code</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>0000 - NOT ON FILE</fullName>
            </value>
            <value>
                <fullName>0001 - Interim Rent</fullName>
            </value>
            <value>
                <fullName>0002 - Upfront Tax</fullName>
            </value>
            <value>
                <fullName>0003 - OneTime Documentation Fee</fullName>
            </value>
            <value>
                <fullName>0004 - Ending Deposit</fullName>
            </value>
            <value>
                <fullName>0005 - Security Deposit</fullName>
            </value>
            <value>
                <fullName>0006 - Rental on Disposed Accts</fullName>
            </value>
            <value>
                <fullName>0007 - 90-day same as cash disc.</fullName>
            </value>
            <value>
                <fullName>0008 - CLOSING FEE</fullName>
            </value>
            <value>
                <fullName>0009 - Returned Check Fee</fullName>
            </value>
            <value>
                <fullName>0010 - COLLECTION / REPO FEE</fullName>
            </value>
            <value>
                <fullName>0011 - Insurance Fee</fullName>
            </value>
            <value>
                <fullName>0012 - Legal Fee</fullName>
            </value>
            <value>
                <fullName>0013 - Loss Reserve</fullName>
            </value>
            <value>
                <fullName>0014 - Funding Difference</fullName>
            </value>
            <value>
                <fullName>0015 - Recovery</fullName>
            </value>
            <value>
                <fullName>0016 - Equipment Sale</fullName>
            </value>
            <value>
                <fullName>0017 - Service Contract</fullName>
            </value>
            <value>
                <fullName>0018 - Property Tax</fullName>
            </value>
            <value>
                <fullName>0019 - Fla Doc Stamp Tax</fullName>
            </value>
            <value>
                <fullName>0020 - Renewal Rentals</fullName>
            </value>
            <value>
                <fullName>0021 - Sec Deposit Refund</fullName>
            </value>
            <value>
                <fullName>0022 - Residual Due Vendor</fullName>
            </value>
            <value>
                <fullName>0023 - Insurance Misc</fullName>
            </value>
            <value>
                <fullName>0024 - Hasselblad</fullName>
            </value>
            <value>
                <fullName>0025 - Inventory Equipment Sale</fullName>
            </value>
            <value>
                <fullName>0026 - Payment after Disposition</fullName>
            </value>
            <value>
                <fullName>0027 - Damage/Return Fee</fullName>
            </value>
            <value>
                <fullName>0028 - End of Term Recovery</fullName>
            </value>
            <value>
                <fullName>0029 - Restructure Fee</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

peac_dev/force-app/main/default/objects/Miscellaneous_Invoice_Item__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <inlineHelpText>Opportunity related to this Misc Invoice Item.</inlineHelpText>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Misc Invoices</relationshipLabel>
    <relationshipName>Miscellaneous_Invoice_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

peac_dev/force-app/main/default/objects/Miscellaneous_Invoice_Item__c/fields/Pay_Code__c.field-meta.xml
<CustomField>
    <fullName>Pay_Code__c</fullName>
    <label>Pay Code</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>0</fullName>
                <label>Don&apos;t Pay Dealer</label>
            </value>
            <value>
                <fullName>1</fullName>
                <label>Pay Dealer</label>
            </value>
            <value>
                <fullName>2</fullName>
                <label>Service Dealer</label>
            </value>
            <value>
                <fullName>3</fullName>
                <label>Pay Customer</label>
            </value>
            <value>
                <fullName>4</fullName>
                <label>Service Multiple Dealers</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

peac_dev/force-app/main/default/objects/SL_Trigger_Settings__c/SL_Trigger_Settings__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>This controls the behavior of triggers written by Silverline.</description>
    <label>SL Trigger Settings</label>
</CustomObject>

peac_dev/force-app/main/default/objects/SL_Trigger_Settings__c/fields/KillList__c.field-meta.xml
<CustomField>
    <fullName>KillList__c</fullName>
    <description>Any object names added to this list will not have their triggers execute.</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Any object names added to this list will not have their triggers execute.</inlineHelpText>
    <label>KillList</label>
    <type>TextArea</type>
</CustomField>

peac_dev/force-app/main/default/classes/SL_MiscInvoiceItemTriggerHandlerTest.cls
@isTest
public with sharing class SL_MiscInvoiceItemTriggerHandlerTest {
    @isTest
    static void miscInvoiceItemActionsFormerPB() {
        Id dealerVendorId = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('Dealer_Vendor').getRecordTypeId();
        insert new SL_Trigger_Settings__c(Name = 'default', KillList__c = 'Account\nOpportunity');
        SL_SCTestData.createAccountAndContracts(2,1);
        SL_SCTestData.createOpportunitiesAndAssets(SL_SCTestData.testAccounts[0].Id, 1, 1);
        List<Account> accounts = SL_SCTestData.testAccounts;
        accounts[1].RecordTypeId = dealerVendorId;
        update accounts[1];
        Opportunity theOpp = SL_SCTestData.testOpportunities[0];
        theOpp.Documentation_Fee__c = 101;
        theOpp.Security_Deposit__c = 102;
        theOpp.First_Payment_Date__c = Date.today();
        update theOpp;
        Test.startTest();
        insert new Dealer__c(Opportunity__c = theOpp.Id, Primary_Dealer__c = true, Dealer__c = accounts[1].Id);
        List<Miscellaneous_Invoice_Item__c> miscInvoiceItems = new List<Miscellaneous_Invoice_Item__c>{
            new Miscellaneous_Invoice_Item__c(Opportunity__c = theOpp.Id,
                                                GL_Code__c = '0000 - NOT ON FILE'),
            new Miscellaneous_Invoice_Item__c(Opportunity__c = theOpp.Id,
                                                GL_Code__c = '0003 - OneTime Documentation Fee'),
            new Miscellaneous_Invoice_Item__c(Opportunity__c = theOpp.Id,
                                                GL_Code__c = '0005 - Security Deposit')
        };
        insert miscInvoiceItems;
        miscInvoiceItems[0].GL_Code__c = '0001 - Interim Rent';
        update miscInvoiceItems;
        Test.stopTest();
        List<Miscellaneous_Invoice_Item__c> miisAfter = [SELECT Id, GL_Code__c, Description__c, Amount__c, CB_Disp__c, Pay_Code__c, Dealer__c
            FROM Miscellaneous_Invoice_Item__c ORDER BY GL_Code__c];
        System.Assert.areEqual('Interim Rent', miisAfter[0].Description__c, 'description gets parsed from the GL Code');
        System.Assert.areEqual(101, miisAfter[1].Amount__c, 'for 0003 amount comes from opp.Documentation_Fee__c');
        System.Assert.areEqual(102, miisAfter[2].Amount__c, 'for 0005 amount comes from opp.Security_Deposit__c');
        System.Assert.areEqual(true, miisAfter[2].CB_Disp__c, 'when opp.First_Payment_Date__c is filled CB/Disp is True');
        System.Assert.areEqual('0', miisAfter[2].Pay_Code__c, 'when opp.First_Payment_Date__c is filled Pay Code is Dont pay dealer (exept for new requirement on Booking)');
        System.Assert.areEqual(accounts[1].Id, miisAfter[2].Dealer__c, 'Dealer field is the opp.primary_Dealer__r.Dealer__c');
    }
}