peac_dev/force-app/main/default/objects/Dealer__c/Dealer__c.object-meta.xml
<CustomObject>
    <label>Dealer</label>
    <nameField>
        <displayFormat>B-{0000}</displayFormat>
        <label>Dealer Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Dealers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

peac_dev/force-app/main/default/objects/Dealer__c/fields/Dealer__c.field-meta.xml
<CustomField>
    <fullName>Dealer__c</fullName>
    <label>Account</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Dealer Account, Dealer_Account Development, Dealer_Account Penetration, Dealer_Close, Dealer_Discovery, Dealer_Proposal, Dealer_Qualification</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Dealer Opportunities</relationshipLabel>
    <relationshipName>Dealers</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

peac_dev/force-app/main/default/classes/SL_UserTriggerHandlerTest.cls
@isTest
public with sharing class SL_UserTriggerHandlerTest {
  private static final String OEG_DEALER_PROFILE = 'OEG Dealer';
  private static final String USERNAME = 'Portal.SL.test.user@silverlinecrm.com';
  private static final Id DEALER_ACC = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('Dealer_Vendor').getRecordTypeId();
    
    @isTest()
    public static void scenario1() {
        User u = new User();
        Id expectedId = null;
        Test.startTest();
        SL_SCTestData.createAccountAndContracts(1, 1);
        List<User> externalUsers = [SELECT Id, name, ContactId, Contact.AccountId, Dealer__c FROM User WHERE ContactId != null];
        system.debug('externalUsers.size() ' + externalUsers.size() );
        if(externalUsers.size() > 0){
            u = externalUsers[0];
            expectedId = u.Contact.AccountId;
        }else{
            Account acc = SL_SCTestData.testAccounts[0];
            u = SL_SCTestData.testUser;
            Site.createExternalUser(u, acc.Id);
        }
        u.Dealer__c = 'nothing';
        // this will need review in fullCopy, also tests actually adding the role to the Partner executive
        System.runAs(SL_SCTestData.testUser){
        	update u;    
        }
        Test.stopTest();
        List<User> usersAfter = [SELECT Id, name, ContactId, Contact.AccountId, Dealer__c FROM User WHERE Id = :u.Id];
        // if(externalUsers.size() > 0 && usersAfter.size() > 0){
        //     System.assertEquals(expectedId, usersAfter[0].Dealer__c);
        // }
    }

    @isTest
    static void addingPermissionSetsSharingAndGroup(){
        Profile p = [SELECT Id FROM Profile WHERE Name = 'System Administrator'];
        User systemAdmin = SL_SCTestData.createTestUser(p.Id);
        SL_SCTestData.createAccountAndContracts(1,1);
        Account portalAccount = SL_SCTestData.testAccounts[0];
        portalAccount.Account_Dealer_Program__c = 'XBS;';
        
        Test.startTest();
        System.runAs(systemAdmin){
           User u = SL_SCTestData.createDPDataForUser(portalAccount);
            PermissionSet thePermission = [SELECT Id, Name FROM PermissionSet WHERE Name = 'Dealer_Delegated_Admin'];
            PermissionSetAssignment thePSA = new PermissionSetAssignment(AssigneeId = u.Id, PermissionSetId = thePermission.Id);
            insert thePSA;
            SL_SCTestData.createPortalContracts(1,portalAccount, u);
            update u;
        }
        Test.stopTest();
    }

    @isTest
    static void removingSharingAndUngroup(){
        Profile p = [SELECT Id FROM Profile WHERE Name = 'System Administrator'];
        User systemAdmin = SL_SCTestData.createTestUser(p.Id);
        SL_SCTestData.createAccountAndContracts(1,1);
        Account portalAccount = SL_SCTestData.testAccounts[0];
        portalAccount.Account_Dealer_Program__c = 'XBS;';
        
        Test.startTest();
        System.runAs(systemAdmin){
           User u = SL_SCTestData.createDPDataForUser(portalAccount);
            PermissionSet thePermission = [SELECT Id, Name FROM PermissionSet WHERE Name = 'Dealer_Delegated_Admin'];
            PermissionSetAssignment thePSA = new PermissionSetAssignment(AssigneeId = u.Id, PermissionSetId = thePermission.Id);
            insert thePSA;
            SL_SCTestData.createPortalContracts(1,portalAccount, u);
            u.IsActive = false;
            update u;
        }
        Test.stopTest();
    }
}