peac_dev/force-app/main/default/objects/Dealer__c/Dealer__c.object-meta.xml
<CustomObject>
    <label>Dealer</label>
    <nameField>
        <displayFormat>B-{0000}</displayFormat>
        <label>Dealer Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Dealers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

peac_dev/force-app/main/default/objects/Dealer__c/fields/Dealer__c.field-meta.xml
<CustomField>
    <fullName>Dealer__c</fullName>
    <label>Account</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Dealer Account, Dealer_Account Development, Dealer_Account Penetration, Dealer_Close, Dealer_Discovery, Dealer_Proposal, Dealer_Qualification</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Dealer Opportunities</relationshipLabel>
    <relationshipName>Dealers</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

peac_dev/force-app/main/default/objects/Gl_Code__c/Gl_Code__c.object-meta.xml
<CustomObject>
    <label>Gl Code</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Gl Code Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>GL Codes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

peac_dev/force-app/main/default/objects/Gl_Code__c/fields/GL_Name__c.field-meta.xml
<CustomField>
    <fullName>GL_Name__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>GL Name</label>
    <length>60</length>
    <type>Text</type>
</CustomField>

peac_dev/force-app/main/default/objects/Gl_Code__c/fields/Payment_Field_name__c.field-meta.xml
<CustomField>
    <fullName>Payment_Field_name__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Payment Field name</label>
    <length>50</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

peac_dev/force-app/main/default/objects/Gl_Code__c/fields/Payment_Field_Source__c.field-meta.xml
<CustomField>
    <fullName>Payment_Field_Source__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Payment Field Source</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

peac_dev/force-app/main/default/objects/Gl_Code__c/fields/Payment_Type__c.field-meta.xml
<CustomField>
    <fullName>Payment_Type__c</fullName>
    <label>Payment Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Both</fullName>
            </value>
            <value>
                <fullName>Lease</fullName>
            </value>
            <value>
                <fullName>Loan</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

peac_dev/force-app/main/default/objects/Gl_Code__c/fields/SL_Account__c.field-meta.xml
<CustomField>
    <fullName>SL_Account__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>SL Account</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

peac_dev/force-app/main/default/objects/Gl_Code__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Plus or Minus Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>+</fullName>
            </value>
            <value>
                <fullName>-</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

peac_dev/force-app/main/default/objects/Marlin_Configuration__c/Marlin_Configuration__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Marlin Configuration</label>
</CustomObject>

peac_dev/force-app/main/default/objects/Marlin_Configuration__c/fields/Enable_Auto_Move_to_Booking__c.field-meta.xml
<CustomField>
    <fullName>Enable_Auto_Move_to_Booking__c</fullName>
    <defaultValue>false</defaultValue>
    <description>If checked, deal will automatically move to booking once all payments move to Payment Confirmed status. If not checked, a user needs to move to Booking.</description>
    <inlineHelpText>If checked, deal will automatically move to booking once all payments move to Payment Confirmed status. If not checked, a user needs to move to Booking.</inlineHelpText>
    <label>Enable Auto Move to Booking</label>
    <type>Checkbox</type>
</CustomField>

peac_dev/force-app/main/default/objects/Payee__c/Payee__c.object-meta.xml
<CustomObject>
    <label>Payee</label>
    <nameField>
        <displayFormat>PAY-{000000}</displayFormat>
        <label>Payee Indentification</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payees</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

peac_dev/force-app/main/default/objects/Payee__c/fields/Address1__c.field-meta.xml
<CustomField>
    <fullName>Address1__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Address1</label>
    <length>60</length>
    <type>Text</type>
</CustomField>

peac_dev/force-app/main/default/objects/Payee__c/fields/City__c.field-meta.xml
<CustomField>
    <fullName>City__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>City</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

peac_dev/force-app/main/default/objects/Payee__c/fields/Dealer__c.field-meta.xml
<CustomField>
    <fullName>Dealer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Select a Dealer if one exists. After selection, pressing save will default the address information into the Payee entry.</inlineHelpText>
    <label>Dealer/Broker</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Dealer Account, Dealer_Account Development, Dealer_Account Penetration, Dealer_Close, Dealer_Discovery, Dealer_Proposal, Dealer_Qualification, Broker Account, End User Account</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Payees</relationshipLabel>
    <relationshipName>Payees</relationshipName>
    <type>Lookup</type>
</CustomField>

peac_dev/force-app/main/default/objects/Payee__c/fields/SL_Vendor_ID__c.field-meta.xml
<CustomField>
    <fullName>SL_Vendor_ID__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <externalId>true</externalId>
    <label>SL Vendor ID</label>
    <length>12</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

peac_dev/force-app/main/default/objects/Payee__c/fields/State__c.field-meta.xml
<CustomField>
    <fullName>State__c</fullName>
    <label>State</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>AB</fullName>
            </value>
            <value>
                <fullName>AK</fullName>
            </value>
            <value>
                <fullName>AL</fullName>
            </value>
            <value>
                <fullName>AR</fullName>
            </value>
            <value>
                <fullName>AUC</fullName>
            </value>
            <value>
                <fullName>AZ</fullName>
            </value>
            <value>
                <fullName>BC</fullName>
            </value>
            <value>
                <fullName>CA</fullName>
            </value>
            <value>
                <fullName>CO</fullName>
            </value>
            <value>
                <fullName>CT</fullName>
            </value>
            <value>
                <fullName>DC</fullName>
            </value>
            <value>
                <fullName>DE</fullName>
            </value>
            <value>
                <fullName>FL</fullName>
            </value>
            <value>
                <fullName>GA</fullName>
            </value>
            <value>
                <fullName>HI</fullName>
            </value>
            <value>
                <fullName>IA</fullName>
            </value>
            <value>
                <fullName>ID</fullName>
            </value>
            <value>
                <fullName>IL</fullName>
            </value>
            <value>
                <fullName>IN</fullName>
            </value>
            <value>
                <fullName>KS</fullName>
            </value>
            <value>
                <fullName>KY</fullName>
            </value>
            <value>
                <fullName>LA</fullName>
            </value>
            <value>
                <fullName>LB</fullName>
            </value>
            <value>
                <fullName>MA</fullName>
            </value>
            <value>
                <fullName>MB</fullName>
            </value>
            <value>
                <fullName>MD</fullName>
            </value>
            <value>
                <fullName>ME</fullName>
            </value>
            <value>
                <fullName>MI</fullName>
            </value>
            <value>
                <fullName>MN</fullName>
            </value>
            <value>
                <fullName>MO</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

peac_dev/force-app/main/default/objects/Payee__c/fields/Tax_ID_Nbr__c.field-meta.xml
<CustomField>
    <fullName>Tax_ID_Nbr__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Tax ID Nbr</label>
    <length>11</length>
    <type>Text</type>
</CustomField>

peac_dev/force-app/main/default/objects/Payee__c/fields/Tax_ID_type__c.field-meta.xml
<CustomField>
    <fullName>Tax_ID_type__c</fullName>
    <inlineHelpText>If 1099 checked, please select EIN (Employer Identification Number) or SSN (Social Security Number) type of entry for Tax ID Nbr.</inlineHelpText>
    <label>Tax ID type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>EIN</fullName>
            </value>
            <value>
                <fullName>SSN</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

peac_dev/force-app/main/default/objects/Payee__c/fields/TIN_Name__c.field-meta.xml
<CustomField>
    <fullName>TIN_Name__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>TIN Name</label>
    <length>60</length>
    <type>Text</type>
</CustomField>

peac_dev/force-app/main/default/objects/Payee__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <formula>if ( CONTAINS(RecordType.Name, &quot;Lease&quot;), &quot;Lease Payee&quot;, &quot;Loan Payee&quot;)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Type</label>
    <type>Text</type>
</CustomField>

peac_dev/force-app/main/default/objects/Payee__c/fields/X1099__c.field-meta.xml
<CustomField>
    <fullName>X1099__c</fullName>
    <defaultValue>false</defaultValue>
    <label>1099</label>
    <type>Checkbox</type>
</CustomField>

peac_dev/force-app/main/default/objects/Payee__c/fields/Zip__c.field-meta.xml
<CustomField>
    <fullName>Zip__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Zip</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

peac_dev/force-app/main/default/objects/Payment__c/Payment__c.object-meta.xml
<CustomObject>
    <description>Payments to a Payee related to an opportunity</description>
    <label>Payment</label>
    <nameField>
        <displayFormat>PYMT-{0}</displayFormat>
        <label>Payment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

peac_dev/force-app/main/default/objects/Payment__c/fields/Less_Points_Pool__c.field-meta.xml
<CustomField>
    <fullName>Less_Points_Pool__c</fullName>
    <label>Less Points Pool</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

peac_dev/force-app/main/default/objects/Payment__c/fields/Payee__c.field-meta.xml
<CustomField>
    <fullName>Payee__c</fullName>
    <inlineHelpText>Payee related to this payment</inlineHelpText>
    <label>Payee</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 AND 2 AND 3</booleanFilter>
        <errorMessage>Value does not exist or does not match filter criteria or the Payee in Inactive</errorMessage>
        <filterItems>
            <field>Payee__c.SL_Vendor_ID__c</field>
            <operation>notEqual</operation>
            <value></value>
        </filterItems>
        <filterItems>
            <field>Payee__c.Active__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <filterItems>
            <field>Payee__c.Payee_Name__c</field>
            <operation>notContain</operation>
            <value>Do Not</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Payee__c</referenceTo>
    <relationshipLabel>Payments</relationshipLabel>
    <relationshipName>Payments</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

peac_dev/force-app/main/default/objects/Payment__c/fields/Payment_Status__c.field-meta.xml
<CustomField>
    <fullName>Payment_Status__c</fullName>
    <label>Payment Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>Ready to Send</fullName>
            </value>
            <value>
                <fullName>Payment Sent</fullName>
            </value>
            <value>
                <fullName>Payment Confirmed</fullName>
                <label>Payment Acknowledged</label>
            </value>
            <value>
                <fullName>Payment Released</fullName>
            </value>
            <value>
                <fullName>Void/Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

peac_dev/force-app/main/default/objects/Payment__c/fields/Plus_Points__c.field-meta.xml
<CustomField>
    <fullName>Plus_Points__c</fullName>
    <label>Plus Points</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

peac_dev/force-app/main/default/objects/Payment__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <formula>RecordType.DeveloperName</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Type</label>
    <type>Text</type>
</CustomField>

peac_dev/force-app/main/default/classes/xct_SolomonPaymentTest.cls
@isTest
public class xct_SolomonPaymentTest {
    
    @isTest static void PaymentTest() {
        Marlin_Configuration__c config = Marlin_Configuration__c.getOrgDefaults ();
        config.Enable_Auto_Move_to_Booking__c = true;
        insert config;

        Gl_Code__c gl = new Gl_Code__c(GL_Name__c='Broker Fees Booking Clearing',Payment_Field_name__c='Points',Payment_Field_Source__c='Plus_Points__c',Payment_Type__c='Both',Type__c='+',SL_Account__c='133011');
        insert gl;
        
        Gl_Code__c gl2 = new Gl_Code__c(GL_Name__c='Accrued Broker Fee Program',Payment_Field_name__c='Points Pool',Payment_Field_Source__c='Less_Points_Pool__c',Payment_Type__c='Both',Type__c='-',SL_Account__c='232862');
        insert gl2;
            
        Account acc = new Account (Name = 'test', RecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Franchisee Account').getRecordTypeId(), Business_Address__c = 'test', Business_Phone__c = '1234567890');
        insert acc;
        
        Contact primary = new Contact (FirstName = 'test', LastName = 'test2', Email = 'test@test.com', AccountId = acc.Id);
        insert primary;
        
        Contact billing = new Contact (FirstName = 'test', LastName = 'test2', AccountId = acc.Id);
        insert billing;
        
        Account dealer = new Account (Name = 'dealer', RecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Dealer Account').getRecordTypeId() , Equipment_Type__c = 'A/V (General)');
        insert dealer;
        
        Id p = UserInfo.getProfileId();
        
        String uniqueUserName = 'dataadmin' + DateTime.now().getTime() + '@testorg.com';
        Test.startTest();
        User u = new User(Alias = 'dadmin', Email='dataadmin@testorg.com',EmailEncodingKey='UTF-8', LastName='Testing', LanguageLocaleKey='en_US',LocaleSidKey='en_US', ProfileId = p,TimeZoneSidKey='America/Los_Angeles',UserName=uniqueUserName);
        
        System.runAs(u) {
            
            Id rt2 = Schema.SObjectType.Opportunity.getRecordTypeInfosByName().get('Express Application').getRecordTypeId();
            Opportunity opp = new Opportunity (Name = 'checklistTest', StageName = 'Decision', CloseDate = Date.today () + 10, AccountId = acc.Id, Primary_Source__c = 'Direct Mail', RecordTypeId = rt2, Application_Status__c = 'Manually Approved', Application__c = 'test', Equipment_Cost__c = 5000, Equipment_Description__c = 'test', Payment_Amount__c = 5000, of_Payments__c = 12);
            
            insert opp;
            
            Payee__c payee = new Payee__c (Dealer__c = dealer.Id, Address1__c = 'test', City__c = 'test', State__c = 'MN', Zip__c = '11111', Email__c = 'test@test.com', 
                                            SL_Vendor_ID__c = 'test', X1099__c = true, Tax_ID_type__c = 'EIN', Tax_ID_Nbr__c = '6666666666',TIN_Name__c = 'TEST');
          	
            
            insert payee;

            //JAH(Tamarack - June 6, 2019): Removed Amount Financed since this causes error with Equip_Cost_Wo_Tax_grter_Sum_Amt_Finance validation rule
            //Payment__c payment = new Payment__c (Payment_Status__c = 'Ready to Send', Opportunity__c = opp.Id, Payee__c = payee.Id,Amount_Financed__c=10000);
            Payment__c payment = new Payment__c (Payment_Status__c = 'Ready to Send', Opportunity__c = opp.Id, Payee__c = payee.Id, Payment_Method__c = 'Check', 
                                                    Plus_Points__c = 1, Less_Points_Pool__c = 1);
			
            insert payment; 
            
            Payment__c[] paymentList = new Payment__c[]{};
            paymentList.add( payment);
            Solomon.SendPayments( paymentList);
            Test.stopTest();
            /*
            payment.Overnight__c = true;
            payment.Payment_Status__c = 'Ready to Send';
            
            update payment;
            
            Solomon.SendPayments( paymentList);
                        
            payee.Wire_Available__c = true;
            payee.Wire_ID__c = '000000000';
            payee.Wire_Account_Number__c = '0000000000';
            update payee;
            payment.Payment_Method__c = 'Wire';
            payment.Overnight__c = false;
            payment.Payment_Status__c = 'Ready to Send';
            
            update payment;
            
            Solomon.SendPayments( paymentList);

            payee.Wire_Available__c = false;
            payee.Wire_ID__c = '';
            payee.Wire_Account_Number__c = '';
            payee.ACH_Available__c = true;
            payee.ACH_Account_Type__c = 'Checking';
            payee.ACH_Bank_Transit__c = '000000000';
            payee.ACH_Account_Number__c = '0000000000';
            update payee;
            payment.Payment_Method__c = 'ACH';
            payment.Overnight__c = false;
            payment.Payment_Status__c = 'Ready to Send';
            
            update payment;
            
            Solomon.SendPayments( paymentList);           
            */
        }
    }
}