peac_dev/force-app/main/default/objects/Dealer__c/Dealer__c.object-meta.xml
<CustomObject>
    <label>Dealer</label>
    <nameField>
        <displayFormat>B-{0000}</displayFormat>
        <label>Dealer Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Dealers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

peac_dev/force-app/main/default/objects/Dealer__c/fields/Dealer__c.field-meta.xml
<CustomField>
    <fullName>Dealer__c</fullName>
    <label>Account</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Dealer Account, Dealer_Account Development, Dealer_Account Penetration, Dealer_Close, Dealer_Discovery, Dealer_Proposal, Dealer_Qualification</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Dealer Opportunities</relationshipLabel>
    <relationshipName>Dealers</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

peac_dev/force-app/main/default/objects/Payee__c/Payee__c.object-meta.xml
<CustomObject>
    <label>Payee</label>
    <nameField>
        <displayFormat>PAY-{000000}</displayFormat>
        <label>Payee Indentification</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payees</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

peac_dev/force-app/main/default/objects/Payee__c/fields/Dealer__c.field-meta.xml
<CustomField>
    <fullName>Dealer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Select a Dealer if one exists. After selection, pressing save will default the address information into the Payee entry.</inlineHelpText>
    <label>Dealer/Broker</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Dealer Account, Dealer_Account Development, Dealer_Account Penetration, Dealer_Close, Dealer_Discovery, Dealer_Proposal, Dealer_Qualification, Broker Account, End User Account</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Payees</relationshipLabel>
    <relationshipName>Payees</relationshipName>
    <type>Lookup</type>
</CustomField>

peac_dev/force-app/main/default/objects/Payee__c/fields/SL_Vendor_ID__c.field-meta.xml
<CustomField>
    <fullName>SL_Vendor_ID__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <externalId>true</externalId>
    <label>SL Vendor ID</label>
    <length>12</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

peac_dev/force-app/main/default/classes/SL_PayeeTriggerHandler.cls
public with sharing class SL_PayeeTriggerHandler extends SL_Trigger.baseHandler {


    public override void afterUpdate(Map<Id, SObject> oldMap, Map<Id, SObject> newMap){
        System.debug(' SL_PayeeTriggerHandler afterUpdate');
        for(SObject theObject :newMap.values()){
            Payee__c payee = (Payee__c)theObject;
            Payee__c oldPayee = (Payee__c)oldMap.get(payee.Id);

            if(payee.Dealer__c != null && (payee.SL_Vendor_ID__c != oldPayee.SL_Vendor_ID__c || payee.Dealer__c != oldPayee.Dealer__c) ){
                if(!Test.isRunningTest())TC_BWUpdateDealerCtrl.updateDealerFuture(payee.Dealer__c);
            }
        }


    }


    public override void afterInsert(Map<Id, SObject> newMap){
        System.debug(' SL_PayeeTriggerHandler afterInsert');

        for(SObject theObject :newMap.values()){
            Payee__c payee = (Payee__c)theObject;

            System.debug(' SL_PayeeTriggerHandler afterInsert payee SL_Vendor_ID__c' + payee.SL_Vendor_ID__c);

            if(payee.Dealer__c != null && payee.SL_Vendor_ID__c != null ){
                if(!Test.isRunningTest())TC_BWUpdateDealerCtrl.updateDealerFuture(payee.Dealer__c);
            }
        }

    }
}