peac_dev/force-app/main/default/objects/Dealer__c/Dealer__c.object-meta.xml
<CustomObject>
    <label>Dealer</label>
    <nameField>
        <displayFormat>B-{0000}</displayFormat>
        <label>Dealer Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Dealers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

peac_dev/force-app/main/default/objects/Dealer__c/fields/Dealer__c.field-meta.xml
<CustomField>
    <fullName>Dealer__c</fullName>
    <label>Account</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Dealer Account, Dealer_Account Development, Dealer_Account Penetration, Dealer_Close, Dealer_Discovery, Dealer_Proposal, Dealer_Qualification</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Dealer Opportunities</relationshipLabel>
    <relationshipName>Dealers</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

peac_dev/force-app/main/default/objects/Dealer__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipName>Brokers</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

peac_dev/force-app/main/default/objects/Marlin_Configuration__c/Marlin_Configuration__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Marlin Configuration</label>
</CustomObject>

peac_dev/force-app/main/default/objects/Marlin_Configuration__c/fields/Enable_Auto_Move_to_Booking__c.field-meta.xml
<CustomField>
    <fullName>Enable_Auto_Move_to_Booking__c</fullName>
    <defaultValue>false</defaultValue>
    <description>If checked, deal will automatically move to booking once all payments move to Payment Confirmed status. If not checked, a user needs to move to Booking.</description>
    <inlineHelpText>If checked, deal will automatically move to booking once all payments move to Payment Confirmed status. If not checked, a user needs to move to Booking.</inlineHelpText>
    <label>Enable Auto Move to Booking</label>
    <type>Checkbox</type>
</CustomField>

peac_dev/force-app/main/default/objects/Payee__c/Payee__c.object-meta.xml
<CustomObject>
    <label>Payee</label>
    <nameField>
        <displayFormat>PAY-{000000}</displayFormat>
        <label>Payee Indentification</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payees</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

peac_dev/force-app/main/default/objects/Payee__c/fields/Address1__c.field-meta.xml
<CustomField>
    <fullName>Address1__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Address1</label>
    <length>60</length>
    <type>Text</type>
</CustomField>

peac_dev/force-app/main/default/objects/Payee__c/fields/City__c.field-meta.xml
<CustomField>
    <fullName>City__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>City</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

peac_dev/force-app/main/default/objects/Payee__c/fields/Dealer__c.field-meta.xml
<CustomField>
    <fullName>Dealer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Select a Dealer if one exists. After selection, pressing save will default the address information into the Payee entry.</inlineHelpText>
    <label>Dealer/Broker</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Dealer Account, Dealer_Account Development, Dealer_Account Penetration, Dealer_Close, Dealer_Discovery, Dealer_Proposal, Dealer_Qualification, Broker Account, End User Account</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Payees</relationshipLabel>
    <relationshipName>Payees</relationshipName>
    <type>Lookup</type>
</CustomField>

peac_dev/force-app/main/default/objects/Payee__c/fields/SL_Vendor_ID__c.field-meta.xml
<CustomField>
    <fullName>SL_Vendor_ID__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <externalId>true</externalId>
    <label>SL Vendor ID</label>
    <length>12</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

peac_dev/force-app/main/default/objects/Payee__c/fields/State__c.field-meta.xml
<CustomField>
    <fullName>State__c</fullName>
    <label>State</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>AB</fullName>
            </value>
            <value>
                <fullName>AK</fullName>
            </value>
            <value>
                <fullName>AL</fullName>
            </value>
            <value>
                <fullName>AR</fullName>
            </value>
            <value>
                <fullName>AUC</fullName>
            </value>
            <value>
                <fullName>AZ</fullName>
            </value>
            <value>
                <fullName>BC</fullName>
            </value>
            <value>
                <fullName>CA</fullName>
            </value>
            <value>
                <fullName>CO</fullName>
            </value>
            <value>
                <fullName>CT</fullName>
            </value>
            <value>
                <fullName>DC</fullName>
            </value>
            <value>
                <fullName>DE</fullName>
            </value>
            <value>
                <fullName>FL</fullName>
            </value>
            <value>
                <fullName>GA</fullName>
            </value>
            <value>
                <fullName>HI</fullName>
            </value>
            <value>
                <fullName>IA</fullName>
            </value>
            <value>
                <fullName>ID</fullName>
            </value>
            <value>
                <fullName>IL</fullName>
            </value>
            <value>
                <fullName>IN</fullName>
            </value>
            <value>
                <fullName>KS</fullName>
            </value>
            <value>
                <fullName>KY</fullName>
            </value>
            <value>
                <fullName>LA</fullName>
            </value>
            <value>
                <fullName>LB</fullName>
            </value>
            <value>
                <fullName>MA</fullName>
            </value>
            <value>
                <fullName>MB</fullName>
            </value>
            <value>
                <fullName>MD</fullName>
            </value>
            <value>
                <fullName>ME</fullName>
            </value>
            <value>
                <fullName>MI</fullName>
            </value>
            <value>
                <fullName>MN</fullName>
            </value>
            <value>
                <fullName>MO</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

peac_dev/force-app/main/default/objects/Payee__c/fields/Zip__c.field-meta.xml
<CustomField>
    <fullName>Zip__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Zip</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

peac_dev/force-app/main/default/objects/Payment__c/Payment__c.object-meta.xml
<CustomObject>
    <description>Payments to a Payee related to an opportunity</description>
    <label>Payment</label>
    <nameField>
        <displayFormat>PYMT-{0}</displayFormat>
        <label>Payment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

peac_dev/force-app/main/default/objects/Payment__c/fields/Date_Sent_to_External_System__c.field-meta.xml
<CustomField>
    <fullName>Date_Sent_to_External_System__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Date Sent to External System</label>
    <type>DateTime</type>
</CustomField>

peac_dev/force-app/main/default/objects/Payment__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <inlineHelpText>Opportunity related to this payment</inlineHelpText>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Payments</relationshipLabel>
    <relationshipName>Payments</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

peac_dev/force-app/main/default/objects/Payment__c/fields/Payee__c.field-meta.xml
<CustomField>
    <fullName>Payee__c</fullName>
    <inlineHelpText>Payee related to this payment</inlineHelpText>
    <label>Payee</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 AND 2 AND 3</booleanFilter>
        <errorMessage>Value does not exist or does not match filter criteria or the Payee in Inactive</errorMessage>
        <filterItems>
            <field>Payee__c.SL_Vendor_ID__c</field>
            <operation>notEqual</operation>
            <value></value>
        </filterItems>
        <filterItems>
            <field>Payee__c.Active__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <filterItems>
            <field>Payee__c.Payee_Name__c</field>
            <operation>notContain</operation>
            <value>Do Not</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Payee__c</referenceTo>
    <relationshipLabel>Payments</relationshipLabel>
    <relationshipName>Payments</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

peac_dev/force-app/main/default/objects/Payment__c/fields/Payment_Status__c.field-meta.xml
<CustomField>
    <fullName>Payment_Status__c</fullName>
    <label>Payment Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>Ready to Send</fullName>
            </value>
            <value>
                <fullName>Payment Sent</fullName>
            </value>
            <value>
                <fullName>Payment Confirmed</fullName>
                <label>Payment Acknowledged</label>
            </value>
            <value>
                <fullName>Payment Released</fullName>
            </value>
            <value>
                <fullName>Void/Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

peac_dev/force-app/main/default/classes/TC_PaymentTriggerHelperTest.cls
@isTest public class TC_PaymentTriggerHelperTest {

    @TestSetup
    static void setup() {
        
        Marlin_Configuration__c config = Marlin_Configuration__c.getOrgDefaults ();
        config.Enable_Auto_Move_to_Booking__c = true;
        insert config;
        
        Account acc = new Account (Name = 'test', RecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Franchisee Account').getRecordTypeId(), Business_Address__c = 'test', Business_Phone__c = '1234567890');
        insert acc;
        
        Contact primary = new Contact (FirstName = 'test', LastName = 'test2', Email = 'test@test.com', AccountId = acc.Id);
        insert primary;
        
        Test.startTest();
        Contact billing = new Contact (FirstName = 'test', LastName = 'test2', AccountId = acc.Id);
        insert billing;
        
        Account dealer = new Account (Name = 'dealer', RecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Dealer Account').getRecordTypeId(), Equipment_Type__c = 'A/V (General)');
        insert dealer;
        Test.stopTest();
    }
    
    @isTest public static void updateOppStageTest () {
       
        Account acc = [SELECT Id FROM Account WHERE Name = 'test'];
        Account dealer = [SELECT Id FROM Account WHERE Name = 'dealer'];
        Profile p = [SELECT Id FROM Profile WHERE Name='System Administrator'][0];
        
        String uniqueUserName = 'dataadmin' + DateTime.now().getTime() + '@testorg.com';
        User u = new User(Alias = 'dadmin', Email='dataadmin@testorg.com',EmailEncodingKey='UTF-8', LastName='Testing', LanguageLocaleKey='en_US',LocaleSidKey='en_US', ProfileId = p.Id,TimeZoneSidKey='America/Los_Angeles',UserName=uniqueUserName);
        System.runAs(u) {
            
            RecordType rt2 = [select id,Name from RecordType where SobjectType='Opportunity' and Name LIKE '%Express%' Limit 1];
            Opportunity opp = new Opportunity (Name = 'checklistTest', StageName = 'Decision', CloseDate = Date.today () + 10, AccountId = acc.Id, Primary_Source__c = 'Direct Mail', RecordTypeId = rt2.Id, Application_Status__c = 'Manually Approved', Application__c = 'test', Equipment_Cost__c = 5000, Equipment_Description__c = 'test', Payment_Amount__c = 5000, of_Payments__c = 12);
            Test.startTest();
            insert opp;
            
            Payee__c payee = new Payee__c (Dealer__c = dealer.Id, Address1__c = 'test', City__c = 'test', State__c = 'MN', Zip__c = '11111', Email__c = 'test@test.com', SL_Vendor_ID__c = 'test');
            insert payee;
            
            Payment__c payment = new Payment__c (Payment_Status__c = 'Draft', Opportunity__c = opp.Id, Payee__c = payee.Id);
            
            insert payment; 
            Test.stopTest();
            payment.Payment_Status__c = 'Payment Confirmed';
            update payment;
            
            
        }
    }
    @IsTest public static void deleteAsCMS() {
        Account acc = [SELECT Id FROM Account WHERE Name = 'test'];
        Account dealer = [SELECT Id FROM Account WHERE Name = 'dealer'];
        Profile p = [SELECT Id FROM Profile WHERE Name = 'CMS' LIMIT 1];
        String error;

        String uniqueUserName = 'dataadmin' + DateTime.now().getTime() + '@testorg2.com';
        User u = new User(Alias = 'dadmin', Email = 'dataadmin@testorg.com', EmailEncodingKey = 'UTF-8', LastName = 'Testing', LanguageLocaleKey = 'en_US', LocaleSidKey = 'en_US', ProfileId = p.Id, TimeZoneSidKey = 'America/Los_Angeles', UserName = uniqueUserName);
        System.runAs(u) {

            RecordType rt2 = [select id,Name from RecordType where SobjectType = 'Opportunity' and Name LIKE '%Express%' Limit 1];
            Opportunity opp = new Opportunity (Name = 'checklistTest', StageName = 'Decision', CloseDate = Date.today () + 10, AccountId = acc.Id, Primary_Source__c = 'Direct Mail', RecordTypeId = rt2.Id, Application_Status__c = 'Manually Approved', Application__c = 'test', Equipment_Cost__c = 5000, Equipment_Description__c = 'test', Payment_Amount__c = 5000, of_Payments__c = 12);
            Test.startTest();
            insert opp;

            Payee__c payee = new Payee__c (Dealer__c = dealer.Id, Address1__c = 'test', City__c = 'test', State__c = 'MN', Zip__c = '11111', Email__c = 'test@test.com', SL_Vendor_ID__c = 'test');
            insert payee;

            Payment__c payment = new Payment__c (Payment_Status__c = 'Draft', Opportunity__c = opp.Id, Payee__c = payee.Id, Date_Sent_to_External_System__c = Datetime.now());

            insert payment;
            Test.stopTest();
            try{
                delete payment;
            }catch (Exception e){
                System.assertEquals(true,
                e.getMessage().contains('CMS should not be able to use the "Delete" function on the payment object after they have Sent to Solomon.'));
            }
        }
    }
}