peac_dev/force-app/main/default/objects/Dealer__c/Dealer__c.object-meta.xml
<CustomObject>
    <label>Dealer</label>
    <nameField>
        <displayFormat>B-{0000}</displayFormat>
        <label>Dealer Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Dealers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

peac_dev/force-app/main/default/objects/Dealer__c/fields/Dealer__c.field-meta.xml
<CustomField>
    <fullName>Dealer__c</fullName>
    <label>Account</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Dealer Account, Dealer_Account Development, Dealer_Account Penetration, Dealer_Close, Dealer_Discovery, Dealer_Proposal, Dealer_Qualification</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Dealer Opportunities</relationshipLabel>
    <relationshipName>Dealers</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

peac_dev/force-app/main/default/objects/Dealer__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipName>Brokers</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

peac_dev/force-app/main/default/objects/Dealer__c/fields/Primary_Dealer__c.field-meta.xml
<CustomField>
    <fullName>Primary_Dealer__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Indicates if the dealer is primary dealer.</description>
    <label>Primary Dealer</label>
    <type>Checkbox</type>
</CustomField>

peac_dev/force-app/main/default/objects/Program__c/Program__c.object-meta.xml
<CustomObject>
    <label>Program</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Programs</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Programs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

peac_dev/force-app/main/default/objects/Program__c/fields/Program_Code__c.field-meta.xml
<CustomField>
    <fullName>Program_Code__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Program Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

peac_dev/force-app/main/default/objects/Program__c/recordTypes/Programs.recordType-meta.xml
<RecordType>
    <fullName>Programs</fullName>
    <active>true</active>
    <description>Programs offered by a Dealer, Franchisor or Manufacturer that would affect the pricing of an application</description>
    <label>Programs</label>
</RecordType>

peac_dev/force-app/main/default/classes/PEAC_AssociateDealerProgramTest.cls
/************************************************************************************************************************
 @Description: This is the unit test class. Tigger the Program association on opportunity
 @Author: Rajesh Kumar(LTM)
 @Created Date: 07/01/2026
 @User Story: SAL-6998
 ************************************************************************************************************************/
@IsTest
public class PEAC_AssociateDealerProgramTest {
	// Utility: Create Program__c records
    private static Map<String, Program__c> createPrograms() {
        List<Program__c> programs = new List<Program__c>{
            new Program__c(Name='BOOTY', Program_Code__c='BOOTY'),
            new Program__c(Name='GOLD', Program_Code__c='GOLD'),
            new Program__c(Name='COPPER', Program_Code__c='COPPER')
        };
        insert programs;

        Map<String, Program__c> mapResult = new Map<String, Program__c>();
        for (Program__c p : programs) {
            mapResult.put(p.Program_Code__c, p);
        }
        return mapResult;
    }

    // Utility: Create a dealer account
    private static Account createDealer(String programs) {
        Id recordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('Dealer_Vendor').getRecordTypeId();
        Account acc = new Account(
            Name = 'Dealer Test',
            Type = 'D',
            Account_Dealer_Program__c = programs,
            recordTypeId = recordTypeId
        );
        insert acc;
        return acc;
    }

    @testsetup
    static void testInsertCreatesAccountPrograms() {
		PEAC_TestDataFactory.createBridgeWareSetting();
        List<Account> accounts = PEAC_TestDataFactory.createAccount(1);
        List<Opportunity> testOpportunities = PEAC_TestDataFactory.createOpportunities(accounts[0].Id, 1);
        Test.startTest();
        Map<String, Program__c> programMap = createPrograms();

        Account dealer = createDealer('BOOTY');
        Test.StopTest();

        
    }
    @isTest
    static void createPrimaryDealer()
    {
        List<Opportunity> oppList = [SELECT ID FROM OPPORTUNITY LIMIT 1];
        List<Account> accList = [SELECT ID FROM ACCOUNT WHERE Type = 'D'];
        
        Dealer__c dealer = new Dealer__c(Dealer__c = accList[0].Id,
                                Opportunity__c = oppList[0].Id,
                                Primary_Dealer__c = True);
       	Insert dealer;
    }
    
    

}