peac_dev/force-app/main/default/objects/Insurance__c/Insurance__c.object-meta.xml
<CustomObject>
    <label>Insurance</label>
    <nameField>
        <displayFormat>INS-{0000}</displayFormat>
        <label>Insurance Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Insurance</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

peac_dev/force-app/main/default/objects/Insurance__c/fields/Cancel_Date__c.field-meta.xml
<CustomField>
    <fullName>Cancel_Date__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Cancel Date</label>
    <type>Date</type>
</CustomField>

peac_dev/force-app/main/default/objects/Insurance__c/fields/Carrier__c.field-meta.xml
<CustomField>
    <fullName>Carrier__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Carrier Name</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

peac_dev/force-app/main/default/objects/Insurance__c/fields/Effective_Date__c.field-meta.xml
<CustomField>
    <fullName>Effective_Date__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Effective Date</label>
    <type>Date</type>
</CustomField>

peac_dev/force-app/main/default/objects/Insurance__c/fields/Expiration_Date__c.field-meta.xml
<CustomField>
    <fullName>Expiration_Date__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Expiration Date</label>
    <type>Date</type>
</CustomField>

peac_dev/force-app/main/default/objects/Insurance__c/fields/Insurance_Id__c.field-meta.xml
<CustomField>
    <fullName>Insurance_Id__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <externalId>true</externalId>
    <label>Insurance Id</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

peac_dev/force-app/main/default/objects/Insurance__c/fields/Integration_Status__c.field-meta.xml
<CustomField>
    <fullName>Integration_Status__c</fullName>
    <label>Integration Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Not Synced</fullName>
                <default>true</default>
                <label>Not Synced</label>
            </value>
            <value>
                <fullName>Error</fullName>
            </value>
            <value>
                <fullName>Re-sync</fullName>
            </value>
            <value>
                <fullName>Synced</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

peac_dev/force-app/main/default/classes/SL_InfoleaseInsuranceController.cls
public with sharing class SL_InfoleaseInsuranceController {
    public static void updateInsurance(Map <Id, Insurance__c> oldMap, Map <Id, Insurance__c> newMap){

        SL_InfoleaseUtils.isRecursive = true;

        List<Insurance__c> validInsuranceList = new List<Insurance__c>();
        Map<Insurance__c, Set<String>> insToFieldsMap = new Map<Insurance__c, Set<String>>();
        //to exclude Informatica user updates
        Id informaticaUserId = SL_InfoleaseUtils.getUserId('User Informatica');

        Set<String> fieldSet = new Set<String>{ 'Carrier__c',
                                                'Effective_Date__c',
                                                'Expiration_Date__c',
                                                'Cancel_Date__c',
                                                'Insurance_Id__c'
                                                };

        for(Insurance__c newInsurance : newMap.values()){

            if(newInsurance.Name == null || newInsurance.LastModifiedById == informaticaUserId){
                continue;
            }

            //check if updates were made to these specific fields
            Set<String> changedFieldSet = new Set<String>{'Insurance_Id__c'};
            for(String s : fieldSet){
                if(newInsurance.get(s) != oldMap.get(newInsurance.Id).get(s)){
                    changedFieldSet.add(s); //adding fields whose value changed
                }
            }

            if(changedFieldSet.size() > 1){
                insToFieldsMap.put(newInsurance, changedFieldSet);
            }
            if(newInsurance.Integration_Status__c == 'Re-sync' && oldMap.get(newInsurance.Id).Integration_Status__c != 'Re-sync'){
                validInsuranceList.add(newInsurance);
            }
        }
        
        if(validInsuranceList.size() > 0){
            SL_InfoleaseInsuranceHandler.updateAllFields(validInsuranceList);
        }else if(insToFieldsMap.size() > 0){
            SL_InfoleaseInsuranceHandler.updateSpecificFields(insToFieldsMap);
        }
    }
}