peac_dev/force-app/main/default/objects/Payee__c/Payee__c.object-meta.xml
<CustomObject>
    <label>Payee</label>
    <nameField>
        <displayFormat>PAY-{000000}</displayFormat>
        <label>Payee Indentification</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payees</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

peac_dev/force-app/main/default/objects/Payee__c/fields/ACH_Account_Number__c.field-meta.xml
<CustomField>
    <fullName>ACH_Account_Number__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>ACH Account #</label>
    <length>34</length>
    <type>Text</type>
</CustomField>

peac_dev/force-app/main/default/objects/Payee__c/fields/ACH_Account_Type__c.field-meta.xml
<CustomField>
    <fullName>ACH_Account_Type__c</fullName>
    <label>ACH Account Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Checking</fullName>
            </value>
            <value>
                <fullName>Savings</fullName>
            </value>
            <value>
                <fullName>Financial Institution GL</fullName>
            </value>
            <value>
                <fullName>Loan Account</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

peac_dev/force-app/main/default/objects/Payee__c/fields/ACH_Available__c.field-meta.xml
<CustomField>
    <fullName>ACH_Available__c</fullName>
    <defaultValue>false</defaultValue>
    <label>ACH Available</label>
    <type>Checkbox</type>
</CustomField>

peac_dev/force-app/main/default/objects/Payee__c/fields/ACH_Bank_Transit__c.field-meta.xml
<CustomField>
    <fullName>ACH_Bank_Transit__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>ACH/Bank Transit</label>
    <length>9</length>
    <type>Text</type>
</CustomField>

peac_dev/force-app/main/default/objects/Payee__c/fields/Address1__c.field-meta.xml
<CustomField>
    <fullName>Address1__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Address1</label>
    <length>60</length>
    <type>Text</type>
</CustomField>

peac_dev/force-app/main/default/objects/Payee__c/fields/Address2__c.field-meta.xml
<CustomField>
    <fullName>Address2__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Address2</label>
    <length>60</length>
    <type>Text</type>
</CustomField>

peac_dev/force-app/main/default/objects/Payee__c/fields/City__c.field-meta.xml
<CustomField>
    <fullName>City__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>City</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

peac_dev/force-app/main/default/objects/Payee__c/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <label>Country</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>USA</fullName>
                <default>true</default>
                <label>USA</label>
            </value>
            <value>
                <fullName>NZ</fullName>
            </value>
            <value>
                <fullName>CAN</fullName>
            </value>
            <value>
                <fullName>GER</fullName>
            </value>
            <value>
                <fullName>UK</fullName>
            </value>
            <value>
                <fullName>VEN</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

peac_dev/force-app/main/default/objects/Payee__c/fields/Default_Pay_Type__c.field-meta.xml
<CustomField>
    <fullName>Default_Pay_Type__c</fullName>
    <label>Default Pay Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Check</fullName>
                <default>true</default>
                <label>Check</label>
            </value>
            <value>
                <fullName>ACH</fullName>
            </value>
            <value>
                <fullName>Wire</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

peac_dev/force-app/main/default/objects/Payee__c/fields/EbankingExists__c.field-meta.xml
<CustomField>
    <fullName>EbankingExists__c</fullName>
    <defaultValue>false</defaultValue>
    <label>EbankingExists</label>
    <type>Checkbox</type>
</CustomField>

peac_dev/force-app/main/default/objects/Payee__c/fields/Payee_Name__c.field-meta.xml
<CustomField>
    <fullName>Payee_Name__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Payee Name</label>
    <length>60</length>
    <type>Text</type>
</CustomField>

peac_dev/force-app/main/default/objects/Payee__c/fields/Qualifier__c.field-meta.xml
<CustomField>
    <fullName>Qualifier__c</fullName>
    <label>Qualifier</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>FedWire</fullName>
            </value>
            <value>
                <fullName>SWIFT</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

peac_dev/force-app/main/default/objects/Payee__c/fields/SL_Vendor_ID__c.field-meta.xml
<CustomField>
    <fullName>SL_Vendor_ID__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <externalId>true</externalId>
    <label>SL Vendor ID</label>
    <length>12</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

peac_dev/force-app/main/default/objects/Payee__c/fields/State__c.field-meta.xml
<CustomField>
    <fullName>State__c</fullName>
    <label>State</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>AB</fullName>
            </value>
            <value>
                <fullName>AK</fullName>
            </value>
            <value>
                <fullName>AL</fullName>
            </value>
            <value>
                <fullName>AR</fullName>
            </value>
            <value>
                <fullName>AUC</fullName>
            </value>
            <value>
                <fullName>AZ</fullName>
            </value>
            <value>
                <fullName>BC</fullName>
            </value>
            <value>
                <fullName>CA</fullName>
            </value>
            <value>
                <fullName>CO</fullName>
            </value>
            <value>
                <fullName>CT</fullName>
            </value>
            <value>
                <fullName>DC</fullName>
            </value>
            <value>
                <fullName>DE</fullName>
            </value>
            <value>
                <fullName>FL</fullName>
            </value>
            <value>
                <fullName>GA</fullName>
            </value>
            <value>
                <fullName>HI</fullName>
            </value>
            <value>
                <fullName>IA</fullName>
            </value>
            <value>
                <fullName>ID</fullName>
            </value>
            <value>
                <fullName>IL</fullName>
            </value>
            <value>
                <fullName>IN</fullName>
            </value>
            <value>
                <fullName>KS</fullName>
            </value>
            <value>
                <fullName>KY</fullName>
            </value>
            <value>
                <fullName>LA</fullName>
            </value>
            <value>
                <fullName>LB</fullName>
            </value>
            <value>
                <fullName>MA</fullName>
            </value>
            <value>
                <fullName>MB</fullName>
            </value>
            <value>
                <fullName>MD</fullName>
            </value>
            <value>
                <fullName>ME</fullName>
            </value>
            <value>
                <fullName>MI</fullName>
            </value>
            <value>
                <fullName>MN</fullName>
            </value>
            <value>
                <fullName>MO</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

peac_dev/force-app/main/default/objects/Payee__c/fields/Wire_Account_Number__c.field-meta.xml
<CustomField>
    <fullName>Wire_Account_Number__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Wire Account #</label>
    <length>34</length>
    <type>Text</type>
</CustomField>

peac_dev/force-app/main/default/objects/Payee__c/fields/Wire_Available__c.field-meta.xml
<CustomField>
    <fullName>Wire_Available__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Wire Available</label>
    <type>Checkbox</type>
</CustomField>

peac_dev/force-app/main/default/objects/Payee__c/fields/Wire_ID__c.field-meta.xml
<CustomField>
    <fullName>Wire_ID__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Wire/Bank Transit</label>
    <length>9</length>
    <type>Text</type>
</CustomField>

peac_dev/force-app/main/default/objects/Payee__c/fields/Zip__c.field-meta.xml
<CustomField>
    <fullName>Zip__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Zip</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

peac_dev/force-app/main/default/classes/SolomonEBanking.cls
public with sharing class SolomonEBanking {
    // XDD
    public class DepositorSF {
        public String VendID{ get; set; }
        public string Crtd_Prog{ get; set; }
        public string LUpd_Prog{ get; set; }
        public string AcctType { get; set; }
        public string BankTransit { get; set; }
        public string BankAcct { get; set; }
        public string EM1Vendor { get; set; }
        public string EM2ToCcBc { get; set; }
        public string EM3ToCcBc { get; set; }
        public string EM4ToCcBc { get; set; }
        public string EM4Addr { get; set; }
        public string EM4Name { get; set; }
        public string FormatID { get; set; }
        public string VendAcct { get; set; }
        public string WBenBankQualifier { get; set; }
        public string WBenBankID { get; set; }
        public string WBeneAcct { get; set; }
        public string WBeneAcctType { get; set; }
        public string WBeneName { get; set; }
        public string WBeneAddr { get; set; }
        public string WBeneAddr2 { get; set; }
        public string WBeneCity { get; set; }
        public string WBeneState { get; set; }
        public string WBeneZipPostal { get; set; }
        public string WBeneISOCntry { get; set; }
        public string PNTaxPmt {get; set; }
        public string Record {get; set; }
        public string EntryClass {get; set; }
        public integer EntryClassCanChg {get; set; }
        public string SKFuture01 {get; set; }
        public integer SKFuture09 {get; set; }
    }
    public class TxnTypeDeps {
        public string VendID { get; set; }
        public string VendCust { get; set; }
        public string VendAcct { get; set; }
        public string eStatus { get; set; }
        public string Selected { get; set; }
    
    }
    public class TopWrapper {
        public DepositorSF myDepositor  { get; set; }
        public List <TxnTypeDeps> myTxnTypeDeps { get; set; }
    }
        
 
    public static void Depositor(Payee__c payee, string type){
                    
            System.debug('!!!!!!SendEbanking');
            
            DepositorSF myDepositor = new DepositorSF();
            
        myDepositor.VendID = payee.SL_Vendor_ID__c;
        myDepositor.Record = 'V';
        myDepositor.EM1Vendor = 'Y'; // N?
        if ( payee.Default_Pay_Type__c == 'Check' ) {
            myDepositor.EntryClass = 'SLCK'; 
        }
        else if ( payee.Default_Pay_Type__c == 'ACH' ) {
            myDepositor.EntryClass = 'ACCP'; 
        }
        else {
            myDepositor.EntryClass = 'MTS'; 
        }  
        myDepositor.EntryClassCanChg = 1;
          
        if ( payee.ACH_Account_Type__c == 'Checking' ) {
            myDepositor.AcctType  = 'C'; 
        }
        else if ( payee.ACH_Account_Type__c == 'Savings' ) {
            myDepositor.AcctType  = 'S'; 
        }
        else if ( payee.ACH_Account_Type__c == 'Loan Account' ) {
            myDepositor.AcctType  = 'L'; 
        }
        else {
            myDepositor.AcctType  = 'F'; 
        }    
        
        myDepositor.Crtd_Prog = 'SFPAY';
        myDepositor.LUpd_Prog = 'SFPAY';
        myDepositor.BankTransit  = payee.ACH_Bank_Transit__c;
        myDepositor.BankAcct  = payee.ACH_Account_Number__c;
        myDepositor.EM2ToCcBc  = 'B';
        myDepositor.EM3ToCcBc  = 'B';
        myDepositor.EM4ToCcBc  = 'B';
        // myDepositor.EM4Addr  = 'FakeAPPaymentNotifications@marlinleasing.com';
        myDepositor.EM4Addr  = 'APPaymentNotifications@marlinleasing.com';
        myDepositor.EM4Name  = 'Ap Payment Notification';
        myDepositor.FormatID  = 'US-WFARGO-PMSV9';
        myDepositor.VendAcct  = 'MAIN';
        if ( payee.Qualifier__c == 'SWIFT' ) {
            myDepositor.WBenBankQualifier  = 'IS';
        }
        else if ( payee.Qualifier__c == 'FedWire' ) {
            myDepositor.WBenBankQualifier  = 'FW';
        }
        else {
            myDepositor.WBenBankQualifier  = '';
        }
        myDepositor.WBenBankID  = payee.Wire_ID__c;
        myDepositor.WBeneAcct  = payee.Wire_Account_Number__c;
        myDepositor.WBeneAcctType = 'D';
        myDepositor.WBeneName  = payee.Payee_Name__c;
        myDepositor.WBeneAddr  = payee.Address1__c;
        myDepositor.WBeneAddr2  = payee.Address2__c;
        myDepositor.WBeneCity  = payee.City__c;
        myDepositor.WBeneState  = payee.State__c;
        myDepositor.WBeneZipPostal  = payee.Zip__c;
        myDepositor.WBeneISOCntry  = payee.Country__c;
        myDepositor.SKFuture01 = payee.Id;
        
        if ( payee.EbankingExists__c == true ) {
            myDepositor.SKFuture09 = 1;
        }
        else {
            myDepositor.SKFuture09 = 0;
        }

        TopWrapper t = new TopWrapper();
        t.myDepositor = myDepositor;
        
        t.myTxnTypeDeps = new List<TxnTypeDeps>();
        TxnTypeDeps thisTxnTypeDeps = new TxnTypeDeps();
        thisTxnTypeDeps.VendID = payee.SL_Vendor_ID__c;
        thisTxnTypeDeps.VendAcct = 'MAIN';
        thisTxnTypeDeps.VendCust = 'V';
        thisTxnTypeDeps.eStatus = ' ';
        thisTxnTypeDeps.Selected = '1';
        t.myTxnTypeDeps.Add(thisTxnTypeDeps);
        TxnTypeDeps thisTxnTypeDepsO = new TxnTypeDeps();
        thisTxnTypeDepsO.VendID = payee.SL_Vendor_ID__c;
        thisTxnTypeDepsO.VendAcct = 'MAIN';
        thisTxnTypeDepsO.VendCust = 'V';
        thisTxnTypeDepsO.eStatus = 'O';
        if ( payee.ACH_Available__c == true) {
            thisTxnTypeDepsO.Selected = '1';
        }
        else {
            thisTxnTypeDepsO.Selected = '0';
        }
        t.myTxnTypeDeps.Add(thisTxnTypeDepsO);
        TxnTypeDeps thisTxnTypeDepsM = new TxnTypeDeps();
        thisTxnTypeDepsM.VendID = payee.SL_Vendor_ID__c;
        thisTxnTypeDepsM.VendAcct = 'MAIN';
        thisTxnTypeDepsM.VendCust = 'V';
        thisTxnTypeDepsM.eStatus = 'M';
        if ( payee.Wire_Available__c == true) {
            thisTxnTypeDepsM.Selected = '1';
        }
        else {
            thisTxnTypeDepsM.Selected = '0';
        }
        t.myTxnTypeDeps.Add(thisTxnTypeDepsM);
        
        
        String s = JSON.serialize(t);
        
        System.debug(s);
        // send the data to the queue
           xctDataClass.makeCallout('SFEBANK', payee.Id, type, s);
        
    }

}