peac_dev/force-app/main/default/objects/Contract__c/Contract__c.object-meta.xml
<CustomObject>
    <description>Custom Object created so we can use Queue functionality</description>
    <label>Contract</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Contract Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Contracts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

peac_dev/force-app/main/default/objects/Contract__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipName>Custom_Contracts</relationshipName>
    <type>Lookup</type>
</CustomField>

peac_dev/force-app/main/default/objects/Contract__c/recordTypes/Lease.recordType-meta.xml
<RecordType>
    <fullName>Lease</fullName>
    <active>true</active>
    <label>Lease</label>
</RecordType>

peac_dev/force-app/main/default/objects/Contract__c/recordTypes/Loan.recordType-meta.xml
<RecordType>
    <fullName>Loan</fullName>
    <active>false</active>
    <label>Loan</label>
</RecordType>

peac_dev/force-app/main/default/objects/Gl_Code__c/Gl_Code__c.object-meta.xml
<CustomObject>
    <label>Gl Code</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Gl Code Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>GL Codes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

peac_dev/force-app/main/default/objects/Gl_Code__c/fields/Payment_Field_Source__c.field-meta.xml
<CustomField>
    <fullName>Payment_Field_Source__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Payment Field Source</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

peac_dev/force-app/main/default/objects/Gl_Code__c/fields/Payment_Type__c.field-meta.xml
<CustomField>
    <fullName>Payment_Type__c</fullName>
    <label>Payment Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Both</fullName>
            </value>
            <value>
                <fullName>Lease</fullName>
            </value>
            <value>
                <fullName>Loan</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

peac_dev/force-app/main/default/objects/Gl_Code__c/fields/SL_Account__c.field-meta.xml
<CustomField>
    <fullName>SL_Account__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>SL Account</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

peac_dev/force-app/main/default/objects/Gl_Code__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Plus or Minus Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>+</fullName>
            </value>
            <value>
                <fullName>-</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

peac_dev/force-app/main/default/objects/Payee__c/Payee__c.object-meta.xml
<CustomObject>
    <label>Payee</label>
    <nameField>
        <displayFormat>PAY-{000000}</displayFormat>
        <label>Payee Indentification</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payees</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

peac_dev/force-app/main/default/objects/Payee__c/fields/Payee_Name__c.field-meta.xml
<CustomField>
    <fullName>Payee_Name__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Payee Name</label>
    <length>60</length>
    <type>Text</type>
</CustomField>

peac_dev/force-app/main/default/objects/Payee__c/fields/SL_Vendor_ID__c.field-meta.xml
<CustomField>
    <fullName>SL_Vendor_ID__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <externalId>true</externalId>
    <label>SL Vendor ID</label>
    <length>12</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

peac_dev/force-app/main/default/objects/Payee__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <formula>if ( CONTAINS(RecordType.Name, &quot;Lease&quot;), &quot;Lease Payee&quot;, &quot;Loan Payee&quot;)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Type</label>
    <type>Text</type>
</CustomField>

peac_dev/force-app/main/default/objects/Payee__c/fields/X1099__c.field-meta.xml
<CustomField>
    <fullName>X1099__c</fullName>
    <defaultValue>false</defaultValue>
    <label>1099</label>
    <type>Checkbox</type>
</CustomField>

peac_dev/force-app/main/default/objects/Payee__c/recordTypes/Lease_Payment.recordType-meta.xml
<RecordType>
    <fullName>Lease_Payment</fullName>
    <active>true</active>
    <description>Payee for a Lease Payment</description>
    <label>Lease Payment</label>
</RecordType>

peac_dev/force-app/main/default/objects/Payee__c/recordTypes/Loan_Payment.recordType-meta.xml
<RecordType>
    <fullName>Loan_Payment</fullName>
    <active>true</active>
    <description>Payee for a Loan Payment</description>
    <label>Loan Payment</label>
</RecordType>

peac_dev/force-app/main/default/objects/Payment__c/Payment__c.object-meta.xml
<CustomObject>
    <description>Payments to a Payee related to an opportunity</description>
    <label>Payment</label>
    <nameField>
        <displayFormat>PYMT-{0}</displayFormat>
        <label>Payment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

peac_dev/force-app/main/default/objects/Payment__c/fields/Invoice_Number__c.field-meta.xml
<CustomField>
    <fullName>Invoice_Number__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Invoice Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

peac_dev/force-app/main/default/objects/Payment__c/fields/Less_Advance_Funding__c.field-meta.xml
<CustomField>
    <fullName>Less_Advance_Funding__c</fullName>
    <label>Less Advance Funding</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

peac_dev/force-app/main/default/objects/Payment__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <inlineHelpText>Opportunity related to this payment</inlineHelpText>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Payments</relationshipLabel>
    <relationshipName>Payments</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

peac_dev/force-app/main/default/objects/Payment__c/fields/Overnight__c.field-meta.xml
<CustomField>
    <fullName>Overnight__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Check this box for overnight requests. This is only available for Check Payment Method.</inlineHelpText>
    <label>Overnight</label>
    <type>Checkbox</type>
</CustomField>

peac_dev/force-app/main/default/objects/Payment__c/fields/Payee__c.field-meta.xml
<CustomField>
    <fullName>Payee__c</fullName>
    <inlineHelpText>Payee related to this payment</inlineHelpText>
    <label>Payee</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 AND 2 AND 3</booleanFilter>
        <errorMessage>Value does not exist or does not match filter criteria or the Payee in Inactive</errorMessage>
        <filterItems>
            <field>Payee__c.SL_Vendor_ID__c</field>
            <operation>notEqual</operation>
            <value></value>
        </filterItems>
        <filterItems>
            <field>Payee__c.Active__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <filterItems>
            <field>Payee__c.Payee_Name__c</field>
            <operation>notContain</operation>
            <value>Do Not</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Payee__c</referenceTo>
    <relationshipLabel>Payments</relationshipLabel>
    <relationshipName>Payments</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

peac_dev/force-app/main/default/objects/Payment__c/fields/Payee_Name__c.field-meta.xml
<CustomField>
    <fullName>Payee_Name__c</fullName>
    <formula>Payee__r.Payee_Name__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Payee Name</label>
    <type>Text</type>
</CustomField>

peac_dev/force-app/main/default/objects/Payment__c/fields/Payment_Method__c.field-meta.xml
<CustomField>
    <fullName>Payment_Method__c</fullName>
    <label>Payment Method</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Wire</fullName>
            </value>
            <value>
                <fullName>ACH</fullName>
            </value>
            <value>
                <fullName>Check</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

peac_dev/force-app/main/default/objects/Payment__c/fields/Payment_Status__c.field-meta.xml
<CustomField>
    <fullName>Payment_Status__c</fullName>
    <label>Payment Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>Ready to Send</fullName>
            </value>
            <value>
                <fullName>Payment Sent</fullName>
            </value>
            <value>
                <fullName>Payment Confirmed</fullName>
                <label>Payment Acknowledged</label>
            </value>
            <value>
                <fullName>Payment Released</fullName>
            </value>
            <value>
                <fullName>Void/Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

peac_dev/force-app/main/default/objects/Payment__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <formula>RecordType.DeveloperName</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Type</label>
    <type>Text</type>
</CustomField>

peac_dev/force-app/main/default/objects/Payment__c/recordTypes/Lease_Payment.recordType-meta.xml
<RecordType>
    <fullName>Lease_Payment</fullName>
    <active>true</active>
    <description>Payment for a Lease</description>
    <label>Lease Payment</label>
</RecordType>

peac_dev/force-app/main/default/objects/Payment__c/recordTypes/Loan_Payment.recordType-meta.xml
<RecordType>
    <fullName>Loan_Payment</fullName>
    <active>true</active>
    <description>Payment for a Loan</description>
    <label>Loan Payment</label>
</RecordType>

peac_dev/force-app/main/default/classes/Solomon.cls
public with sharing class Solomon {

    // Transaction
    public class AptranSF {   
        public String TranDesc{ get; set; }
        public String ExtRefNbr{ get; set; }                                               
        public decimal Qty{ get; set; }
        public String UnitDesc{ get; set; }
        public decimal CuryUnitPrice{ get; set; }
        public decimal CuryTranAmt{ get; set; }
        public decimal UnitPrice{ get; set; }
        public decimal TranAmt { get; set; }
        public String CpnyID{ get; set; }
        public String Sub{ get; set; }
        public String Acct{ get; set; }
        // public String TaxCalced{ get; set; }
        public String BoxNbr { get; set; }
        public string Crtd_Prog{ get; set; }
        public string LUpd_Prog{ get; set; }
        public String PC_Flag { get; set; }
        public String VendId{ get; set; }

    }
    // Document
    public class ApdocSF {
        public String CpnyID{ get; set; }
        public String CashAcct{ get; set;}
        public String DocType{ get; set; }
        public String VendId{ get; set; }
        public String User1{ get; set; }
        public String User2{ get; set; }
        public String User5{ get; set; }
        public string User6 { get; set; }
        public String S4Future01{ get; set; }
        public String PmtMethod { get; set; }
        public String Sub{ get; set; }
        public String notes{ get; set; }
        public string Crtd_Prog{ get; set; }
        public string InvcNbr{ get; set; }
        public string LUpd_Prog{ get; set; }
        public decimal CuryDocBal{ get; set; }
        public decimal DocBal{ get; set; }
        public decimal CuryOrigDocAmt{ get; set; }
        public decimal OrigDocAmt{ get; set; }
        public string Econfirm{ get; set; }
        public string Estatus{ get; set; }
    }
    // Batch
    public class BatchSF {
        public String CpnyID{ get; set; }
        public string Crtd_Prog{ get; set; }
        public string LUpd_Prog{ get; set; }
        public string User5 { get; set; }
        public string User6 { get; set; }
 //       public string BatNbr { get; set; }
 //       public decimal CtrlTot { get; set; }
 //       public decimal CuryCtrlTot { get; set; }
 //       public decimal CuryCrTot { get; set; }
 //       public decimal CrTot { get; set; }
 //       public decimal CuryDrTot { get; set; }
 //       public decimal DrTot { get; set; }
    }
    // Voucher for sending to Solomon
    public class VoucherSF {
        public BatchSF myBatch { get; set; }
        public ApdocSF myAPDoc{ get; set; }
        public List<AptranSF> myAPTran{ get; set; }
        public String batchNote { get; set; }
    }
    
     public static void SendPayments(Payment__c[] paymentList){
                
        // System.debug('!!!!!!SendPayments');
        //System.debug('Total Number of SOQL Queries allowed in this apex code context: ' +  Limits.getLimitQueries());
        //System.debug('SOQL Queries Consumed: ' +  Limits.getQueries());
        // Get GL Codes
        Gl_Code__c[] glCodes = Database.query('Select Id, Payment_Field_Source__c, SL_Account__c, Type__c, Payment_Type__c from Gl_Code__c');
       
        for(Payment__c payline: paymentList){
        
            System.debug(payline.Id);

            // Get local Payment fields used
            Id PaymentID = payline.Id;
            String queryString = 'SELECT id,Name,Payee__c,Opportunity__c,Type__c,Invoice_Number__c,Payment_Status__c,Payment_Method__c, Less_Advance_Funding__c, Overnight__c  FROM Payment__c where id = :PaymentID';
            Payment__c thisPayment = Database.query(queryString);
          
            if ( thisPayment.Payment_Status__c == 'Ready to Send' ) {
                
            
                // Get Payee vendor field
                Id payeeID = thisPayment.Payee__c;
                // queryString = 'SELECT id,SL_Vendor_ID__c,Payee_Name__c,X1099__c,Last_Sales_Email__c,Last_Sales_Name__c FROM Payee__c where id = :payeeID';
                queryString = 'SELECT id,SL_Vendor_ID__c,Payee_Name__c,X1099__c FROM Payee__c where id = :payeeID';
                Payee__c payee = Database.query(queryString);
                System.debug('Payee = ' + payee.SL_Vendor_ID__c);
                
                // Get Opportunity fields
                Id OpportunityID = thisPayment.Opportunity__c;
                // queryString = 'SELECT id,Application__c,Name,Contract__c,AccountId,Owner.Email,Owner.Name FROM Opportunity where id = :OpportunityID';
                queryString = 'SELECT id,Application__c,Name,Contract__c,AccountId,SL_Company__c,CaseCenter__c FROM Opportunity where id = :OpportunityID';
                Opportunity thisOpportunity  = Database.query(queryString);
                                   
                // Get Account fields
                Id AccountID = thisOpportunity.AccountId;
                queryString = 'SELECT id,Name FROM Account where id = :AccountID';
                Account thisAccount  = Database.query(queryString);
                
                // System.debug(thisPayee.Id);
                
                // System.debug(thisPayment.Type__c);

                VoucherSF voucher = new VoucherSF();
                BatchSF batch = new BatchSF();
                ApdocSF APDoc = new ApdocSF();
                //APDoc.CpnyID = thisOpportunity.SL_Company__c;
                APDoc.DocType = 'VO';
                APDoc.CpnyID = '1000';   //per request 1-07-2022 - Jira - SAL-462  ALex
                APDoc.VendId = payee.SL_Vendor_ID__c;
                String regExp = '[^a-zA-Z0-9\']';
                
                // Jira SAL-3034, Service Request #94910 - 8/20/2021

                if ( thisPayment.Type__c == 'Lease_Payment') {
                    APDoc.User1 = thisOpportunity.Application__c + ' ' + thisAccount.Name.replaceAll(regExp ,' ').left(15);
                }
                else {
                    APDoc.User1 = thisOpportunity.CaseCenter__c;
                }
                
                if (String.isBlank(thisPayment.Invoice_Number__c)) { APdoc.User2 = ''; } else { APdoc.User2 = thisPayment.Invoice_Number__c; }
                APDoc.InvcNbr = APDoc.User1;
                APdoc.S4Future01 = thisPayment.id;
                APdoc.User5 = thisPayment.Name;
                APDoc.CashAcct = '110300';
                APDoc.notes= '';
                APDoc.Sub = '0400000000';
                if ( APDoc.CpnyID == '1000') {
                    APDoc.Sub = '0000000000';
                }
                
                APDoc.PmtMethod = 'C';
                APDoc.Crtd_Prog = '03PAY';
                APDoc.LUpd_Prog = 'SFPAY';
                
                batch.User5 = 'OPEN';
                
                // System.debug( 'Payment_Method__c = ' + thisPayment.Payment_Method__c);
                
                if ( thisPayment.Payment_Method__c == 'ACH') {
                    APDoc.Econfirm = 'MAIN';
                    APDoc.Estatus = 'O';
                    batch.User6 = 'ACHCHECK';
                    APDoc.User6 = 'ACHCHECK';
                } else if ( thisPayment.Payment_Method__c == 'Wire') {
                    APDoc.Econfirm = 'MAIN';
                    APDoc.Estatus = 'M';
                    batch.User6 = 'WIRE';
                    APDoc.User6 = 'WIRE';
                }
                else {
                    APDoc.Econfirm = '';
                    APDoc.Estatus = '';
                    batch.User6 = 'ACHCHECK';
                    APDoc.User6 = 'ACHCHECK';
               }
               if ( thisPayment.Less_Advance_Funding__c != null) {
                    batch.User6 = 'FUND';
                    APDoc.User6 = 'FUND';
                    batch.User5 = 'CLOSE';
                }
                else if ( thisPayment.Overnight__c == true) {
                    batch.User6 = 'OVERNIGHT';
                    APDoc.User6 = 'OVERNIGHT';
                    // like wire now 9-11-2019 - batch.User5 = 'CLOSE';
                }
               
                voucher.myAPTran = GetAPTransactions(glCodes, PaymentID, thisPayment.Type__c);
                decimal apdocAmt = 0;
                for ( AptranSF APTran: voucher.myAPTran) {
                
                    //APTran.CpnyID = thisOpportunity.SL_Company__c;
                    APTran.CpnyID = '1000';  // per request 2-08-2022 - Jira - SAL-462  ALex
                
                    // APTran.x1099 = '7';
                    String description = payee.SL_Vendor_ID__c + ' ' + payee.Payee_Name__c;
                    APTran.TranDesc = description.left(30);
                     APTran.ExtRefNbr = APDoc.User1;
                    System.debug(APTran.ExtRefNbr);
                    if ( thisPayment.Type__c == 'Lease_Payment') {
                        // Lease
                        //APTran.Sub = '0400000000';  per request 1-07-2022 - Jira - SAL-462  ALex
                        //if ( APTran.CpnyID == '1000') {
                        APTran.Sub = '0000000000';     // moved inside lease so not to squash loan  01-11-22 alex hatcher debanking.  per request 1-07-2022 - Jira - SAL-462  ALex
                    	//}
                    }
                    else {
                        // Loan
                        APTran.Sub = '0000024000';   // changed from 0400024000  01-11-22 alex hatcher  debanking.
                        APDoc.InvcNbr = thisOpportunity.Contract__c;
                    }
                    

                    if ( APTran.Acct == '133011' && payee.X1099__c == true ) {
                        APTran.BoxNbr = '7';
                    }
                    APTran.Crtd_Prog = 'SFPAY';
                    APTran.LUpd_Prog = 'SFPAY';
                    APTran.PC_Flag = '';
                    APTran.VendId = APDoc.VendId;
                    apdocAmt = apdocAmt + APTran.CuryUnitPrice;
                }

                //SAL-869 Need to make sure data is rounded to two digits, in some cases SF saves
                //with additional precision.
                apdocAmt = apdocAmt.setScale(2, System.RoundingMode.HALF_UP);
                APDoc.CuryDocBal = apdocAmt;
                APDoc.DocBal = apdocAmt;
                APDoc.CuryOrigDocAmt = apdocAmt;
                APDoc.OrigDocAmt = apdocAmt;
               
                // batch.CpnyID = thisOpportunity.SL_Company__c;
                batch.CpnyID = '1000';  // per request 1-07-2022 - Jira - SAL-462  ALex
                batch.Crtd_Prog = 'SFPAY';
                batch.LUpd_Prog = 'SFPAY';
                
                voucher.batchNote = '';
                voucher.myApdoc = APDoc;
                voucher.myBatch = batch;
                
                String s = JSON.serialize(voucher);
                
                System.debug(s);
                // send the data to the queue
                xctDataClass.makeCallout('SFPAYMENT', thisPayment.Id, 'ADD', s);
                
                //if ( payee.Last_Sales_Email__c != thisOpportunity.Owner.Email) {
                //     payee.Last_Sales_Email__c = thisOpportunity.Owner.Email;
                //     payee.Last_Sales_Name__c = thisOpportunity.Owner.Name;
                //     update payee;
                //      System.debug('Email = ' + thisOpportunity.Owner.Email);
                //     System.debug('Name= ' + thisOpportunity.Owner.Name);
                //}
               
                
            }
       
        }
        //System.debug('Total Number of SOQL Queries allowed in this apex code context: ' +  Limits.getLimitQueries());
        //System.debug('SOQL Queries consumed: ' +  Limits.getQueries());
       
    }
   
    private static List<AptranSF> GetAPTransactions( Gl_Code__c[] theGLCodes, Id PaymentID, String ThisType) {
    
        List<AptranSF> APTrans;
        APTrans = new List<AptranSF>();
        
        DescribeSObjectResult describeResult = PaymentID.getSObjectType().getDescribe();    
        List<String> fieldNames = new List<String>( describeResult.fields.getMap().keySet() );

        String queryString = 'SELECT ' + String.join( fieldNames, ',' ) + ' FROM Payment__c where id = :PaymentID';
        System.debug(queryString);
        Payment__c thisPayment = Database.query(queryString);   
        
        // Loop through GL Codes and see which fields are set and not zero for creating a transaction line.
        for(Gl_Code__c c: theGLCodes){
        
            if ( c.Payment_Type__c == 'Both' || (c.Payment_Type__c == 'Lease' && ThisType == 'Lease_Payment') || (c.Payment_Type__c == 'Loan' && ThisType == 'Loan_Payment')) {
                 // default the transaction
                AptranSF APTran = new AptranSF();
                APTran.UnitDesc = '';
                APTran.Qty= 1.0;
                APTran.Acct = '232900';
                APTran.CuryUnitPrice = 0;
                
                try {
                    System.debug(c.Payment_Field_Source__c);
     
                    Object o = thisPayment.get(c.Payment_Field_Source__c);
                    
                    String s = String.valueOf(o);
                    System.debug(s + ' ' + c.Type__c + ' ' + c.SL_Account__c);
                    
                    Decimal result = Decimal.valueOf(s);
                    //SAL-869 Need to make sure data is rounded to two digits, in some cases SF saves
                    //with additional precision.
                    result = result.setScale(2, System.RoundingMode.HALF_UP);
                    if ( result >= 0 ) {
                        
                        if ( c.Type__c == '-') {
                            APTran.CuryUnitPrice = 0 - result;
                        }
                        else 
                        {
                            APTran.CuryUnitPrice = result;
                        }
                        APTran.CuryTranAmt = APTran.CuryUnitPrice;
                        APTran.TranAmt = APTran.CuryUnitPrice;
                        APTran.UnitPrice = APTran.CuryUnitPrice;
                        APTran.Acct = c.SL_Account__c;
                        APTrans.Add(APTran);
                    }

                } catch(exception e) {
                }
            }
        }
        return (APTrans);

    }

 }