peac_dev/force-app/main/default/objects/Contract__c/Contract__c.object-meta.xml
<CustomObject>
    <description>Custom Object created so we can use Queue functionality</description>
    <label>Contract</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Contract Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Contracts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

peac_dev/force-app/main/default/objects/Contract__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Disposed</fullName>
            </value>
            <value>
                <fullName>Disposed - Charged Off</fullName>
            </value>
            <value>
                <fullName>Renewal</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

peac_dev/force-app/main/default/objects/Contract_Asset__c/Contract_Asset__c.object-meta.xml
<CustomObject>
    <label>Contract Asset</label>
    <nameField>
        <displayFormat>CA-{0000}</displayFormat>
        <label>Contract Asset Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contract Assets</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

peac_dev/force-app/main/default/objects/Contract_Asset__c/fields/Contract__c.field-meta.xml
<CustomField>
    <fullName>Contract__c</fullName>
    <label>Contract</label>
    <referenceTo>Contract__c</referenceTo>
    <relationshipLabel>Contract Assets</relationshipLabel>
    <relationshipName>Contract_Assets</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

peac_dev/force-app/main/default/objects/Contract_Asset__c/fields/Notes__c.field-meta.xml
<CustomField>
    <fullName>Notes__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Notes</label>
    <type>TextArea</type>
</CustomField>

peac_dev/force-app/main/default/objects/Contract_Asset__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>DP-905</description>
    <formula>IF(ISBLANK(Asset_Disposed_Date__c), &quot;Active&quot;, &quot;Disposed&quot;)</formula>
    <label>Status</label>
    <type>Text</type>
</CustomField>

peac_dev/force-app/main/default/objects/Repurchase_Invoice__c/Repurchase_Invoice__c.object-meta.xml
<CustomObject>
    <label>Repurchase Invoice</label>
    <nameField>
        <displayFormat>DINV-{0000}</displayFormat>
        <label>Repurchase Invoice #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Repurchase Invoices</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

peac_dev/force-app/main/default/objects/Repurchase_Invoice__c/fields/Contract__c.field-meta.xml
<CustomField>
    <fullName>Contract__c</fullName>
    <label>Contract</label>
    <referenceTo>Contract__c</referenceTo>
    <relationshipLabel>Repurchase Invoices</relationshipLabel>
    <relationshipName>Repurchase_Invoices</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

peac_dev/force-app/main/default/objects/Repurchase_Invoice__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Invoice Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Open</fullName>
            </value>
            <value>
                <fullName>Paid</fullName>
            </value>
            <value>
                <fullName>Delinquent</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

peac_dev/force-app/main/default/classes/SL_Repurchase_InvoiceTriggerHandlerTest.cls
@IsTest
public with sharing class SL_Repurchase_InvoiceTriggerHandlerTest {
    @testSetup static void setup() {
        // Create necessary test data using SL_SCTestData methods
        SL_SCTestData.createAccountAndContracts(1, 1);
        SL_SCTestData.createInsurancesAndContractAssets(1, 2); // Creating 1 insurance with 2 contract assets  
        Contract__c Contract = [SELECT Id FROM Contract__c LIMIT 1];
        List<Contract_Asset__c> assets = [SELECT Id FROM Contract_Asset__c WHERE Contract__c=:Contract.Id];
        String invoiceAssetsJSON = '[{\"Id\":\"'+assets[0].Id+'\",\"UnitPrice\":\"10\"},{\"Id\":\"'+assets[1].Id+'\",\"UnitPrice\":\"15\"}]';    
        String result = '';
        String resultGenerated = '';
        result = SL_DealerRepurchaseController.generateInvoice(Contract.Id, invoiceAssetsJSON);
        resultGenerated = SL_DealerRepurchaseController.generateInvoiceDocument('', '', true, result ,invoiceAssetsJSON ); 

        Repurchase_Invoice__c invoice = [SELECT Id, Status__c FROM Repurchase_Invoice__c WHERE Contract__c=:Contract.Id LIMIT 1];
        invoice.Status__c = 'Open';
        update invoice;
    }

    @IsTest
    static void openToPaidTest(){
        Contract__c Contract = [SELECT Id FROM Contract__c LIMIT 1];
        Repurchase_Invoice__c invoice = [SELECT Id, Status__c FROM Repurchase_Invoice__c WHERE Contract__c=:Contract.Id LIMIT 1];

      
        Test.startTest();
        invoice.Status__c = 'Paid';
        update invoice;
        Test.stopTest();

        Integer paidTask = 0;
        List<Task> tasks = [SELECT Id , Notes__c FROM Task WHERE Contract__c = :Contract.Id ];
        for(Task t : tasks){
            if(t.Notes__c.contains('has been paid.')){
                paidTask += 1;
            }
        }
        Assert.isTrue(paidTask > 0);
    }
    
    @IsTest
    static void openToDelinquentTest(){
        Contract__c Contract = [SELECT Id FROM Contract__c LIMIT 1];
        Repurchase_Invoice__c invoice = [SELECT Id, Status__c FROM Repurchase_Invoice__c WHERE Contract__c=:Contract.Id LIMIT 1];

      
        Test.startTest();
        invoice.Status__c = 'Delinquent';
        update invoice;
        Test.stopTest();

        Integer delinquentTask = 0;
        List<Task> tasks = [SELECT Id , Notes__c FROM Task WHERE Contract__c = :Contract.Id ];
        for(Task t : tasks){
            if(t.Notes__c.contains('is now delinquent.')){
                delinquentTask += 1;
            }
        }
        Assert.isTrue(delinquentTask > 0);
    }
    
    @IsTest
    static void openToCancelled(){
        Contract__c Contract = [SELECT Id FROM Contract__c LIMIT 1];
        Repurchase_Invoice__c invoice = [SELECT Id, Status__c FROM Repurchase_Invoice__c WHERE Contract__c=:Contract.Id LIMIT 1];

      
        Test.startTest();
        invoice.Status__c = 'Cancelled';
        update invoice;
        Test.stopTest();

        Integer CancelledtTask = 0;
        List<Task> tasks = [SELECT Id , Notes__c FROM Task WHERE Contract__c = :Contract.Id ];
        for(Task t : tasks){
            if(t.Notes__c.contains('is now canceled.')){
                CancelledtTask += 1;
            }
        }
        Assert.isTrue(CancelledtTask > 0);
    }
}