peac_dev/force-app/main/default/objects/Contract__c/Contract__c.object-meta.xml
<CustomObject>
    <description>Custom Object created so we can use Queue functionality</description>
    <label>Contract</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Contract Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Contracts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

peac_dev/force-app/main/default/objects/Contract__c/fields/Collection_Group__c.field-meta.xml
<CustomField>
    <fullName>Collection_Group__c</fullName>
    <label>Collection Group</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>31 EOT</fullName>
            </value>
            <value>
                <fullName>31 First Payment Default</fullName>
            </value>
            <value>
                <fullName>31 High Balance</fullName>
            </value>
            <value>
                <fullName>31 Regular</fullName>
            </value>
            <value>
                <fullName>31 Syndication</fullName>
            </value>
            <value>
                <fullName>31 Varadero</fullName>
            </value>
            <value>
                <fullName>61</fullName>
            </value>
            <value>
                <fullName>61 EOT</fullName>
            </value>
            <value>
                <fullName>61 Syndication</fullName>
            </value>
            <value>
                <fullName>91</fullName>
            </value>
            <value>
                <fullName>91 Syndication</fullName>
            </value>
            <value>
                <fullName>91+ EOT</fullName>
            </value>
            <value>
                <fullName>Agency Closed</fullName>
            </value>
            <value>
                <fullName>Bankruptcy</fullName>
            </value>
            <value>
                <fullName>Bankruptcy Closed</fullName>
            </value>
            <value>
                <fullName>Dead Contracts</fullName>
            </value>
            <value>
                <fullName>Dialer Do Not Call</fullName>
            </value>
            <value>
                <fullName>Dialer First Payment Default</fullName>
            </value>
            <value>
                <fullName>Dialer Regular</fullName>
            </value>
            <value>
                <fullName>Dialer Special</fullName>
            </value>
            <value>
                <fullName>Dialer TCF</fullName>
            </value>
            <value>
                <fullName>Dialer Team Assigned</fullName>
            </value>
            <value>
                <fullName>External Agencies</fullName>
            </value>
            <value>
                <fullName>Litigation</fullName>
            </value>
            <value>
                <fullName>Multiples</fullName>
            </value>
            <value>
                <fullName>Pending Equipment Return</fullName>
            </value>
            <value>
                <fullName>Pending Repo</fullName>
            </value>
            <value>
                <fullName>Placed With Attorney</fullName>
            </value>
            <value>
                <fullName>Pre-Charge Off</fullName>
            </value>
            <value>
                <fullName>Recovery Agents</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

peac_dev/force-app/main/default/objects/Contract__c/fields/Contract_Balance_Remaining__c.field-meta.xml
<CustomField>
    <fullName>Contract_Balance_Remaining__c</fullName>
    <label>Contract Balance Remaining</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

peac_dev/force-app/main/default/objects/Contract__c/fields/Delinquency_Status_Code__c.field-meta.xml
<CustomField>
    <fullName>Delinquency_Status_Code__c</fullName>
    <label>Delinquency Status Code</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>00</fullName>
                <label>Not delinquent</label>
            </value>
            <value>
                <fullName>01</fullName>
                <label>Past due 01 - 30 days</label>
            </value>
            <value>
                <fullName>31</fullName>
                <label>Past due 31 - 60 days</label>
            </value>
            <value>
                <fullName>61</fullName>
                <label>Past due 61 - 90 days</label>
            </value>
            <value>
                <fullName>91</fullName>
                <label>Past due 91 - 120 days</label>
            </value>
            <value>
                <fullName>121</fullName>
                <label>Past due 121 - 150 days</label>
            </value>
            <value>
                <fullName>151</fullName>
                <label>Past due 151 - 180 days</label>
            </value>
            <value>
                <fullName>181</fullName>
                <label>Past due 181 days and more</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

peac_dev/force-app/main/default/objects/Contract_Criteria__c/Contract_Criteria__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>created for the Collection Group Assignment</description>
    <label>Contract Criteria</label>
</CustomObject>

peac_dev/force-app/main/default/objects/Contract_Criteria__c/fields/Maximum_Balance_CBR__c.field-meta.xml
<CustomField>
    <fullName>Maximum_Balance_CBR__c</fullName>
    <label>Maximum Balance CBR</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

peac_dev/force-app/main/default/objects/Contract_Criteria__c/fields/Maximum_CBR_XBS_ADR__c.field-meta.xml
<CustomField>
    <fullName>Maximum_CBR_XBS_ADR__c</fullName>
    <label>Maximum CBR (XBS, ADR)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

peac_dev/force-app/main/default/classes/SL_ManageBalanceCBRTest.cls
@isTest
public with sharing class SL_ManageBalanceCBRTest {
    
    @TestSetup static void setup() {
    UserRole adminRole = [SELECT Id, Name FROM UserRole WHERE Name = 'Collections Manager'];
            Profile p = [SELECT Id FROM Profile WHERE Name = 'Collections'];
            User u = new User(Alias = 'CBRTest', Email = 'CBRmarlinbusiness@silverlinecrm.com', EmailEncodingKey='UTF-8',
                    LastName = 'testing', FirstName = 'user', LanguageLocaleKey = 'en_US',
                    LocaleSidKey = 'en_US', ProfileId = p.Id, TimeZoneSidKey = 'America/Los_Angeles', IsActive=true,
                    Username = 'CBR.admin.test.user@silverlinecrm.com', Doc_Fee_Exception_Approver__c = true);
            insert u;   

            SL_SCTestData.createAccountAndContracts(1,1);
			Contract__c contract = [SELECT Id, Name, Contract_Balance_Remaining__c, Delinquency_Status_Code__c FROM Contract__c];
            contract.Delinquency_Status_Code__c = '01';
            contract.Contract_Balance_Remaining__c = 1300;
            update contract;
	}
    
    @isTest
    static void increaseMaximum() {
        User u = [SELECT Id, Alias, Username, Email, UserRoleId, ProfileId FROM User WHERE Alias='CBRTest' LIMIT 1];
		UserRole adminRole = [SELECT Id, Name FROM UserRole WHERE Name = 'Collections Manager'];
        u.UserRoleId=adminRole.Id;
        update u;
            Contract_Criteria__c criteriaSetting = [SELECT Id, Maximum_Balance_CBR__c, Maximum_CBR_XBS_ADR__c FROM Contract_Criteria__c LIMIT 1];
            System.debug('criteriaSetting  ' + criteriaSetting);
        String result2, result3;
        List<String> result1;
        System.runAs(u){
            Test.startTest();
            result1 = SL_ManageBalanceCBR.getMaxCBR();
            result2 = SL_ManageBalanceCBR.hubExecute('checkPermission', new List<String>());
            result3 = SL_ManageBalanceCBR.hubExecute('saveMaxCBR', new List<String>{'1500', '1500'});
            Test.stopTest();
        }
        
        Contract__c actual = [SELECT Collection_Group__c FROM Contract__c];
        System.assertEquals('1200.00', result1[0]);
        System.assertEquals('true', result2);
        System.assertEquals('Dialer Regular', actual.Collection_Group__c);
    }
    @isTest
    static void decreaseMaximum() {
        String result1, result2;
		UserRole nonAdminRole = [SELECT Id, Name FROM UserRole WHERE Name = 'Collections Staff'];
		User u = [SELECT Id, Alias, Username, Email, UserRoleId, ProfileId FROM User WHERE Alias='CBRTest' LIMIT 1];
        u.UserRoleId=nonAdminRole.Id;
        update u;

        Test.startTest();
        System.runAs(u){
            result1 = SL_ManageBalanceCBR.hubExecute('saveMaxCBR', new List<String>{'1100','1500'});
        }
        Test.stopTest();
        Contract__c actual = [SELECT Collection_Group__c FROM Contract__c];
        System.assertEquals('You don\'t have permission to change the Maximum Balance CBR, please contact your Administrator.', result1);
        System.assertEquals('Dialer Team Assigned', actual.Collection_Group__c);
    }
}