peac_dev/force-app/main/default/objects/Contract__c/Contract__c.object-meta.xml
<CustomObject>
    <description>Custom Object created so we can use Queue functionality</description>
    <label>Contract</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Contract Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Contracts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

peac_dev/force-app/main/default/objects/Contract_Misc_Billable__c/Contract_Misc_Billable__c.object-meta.xml
<CustomObject>
    <label>Contract Misc Billable</label>
    <nameField>
        <displayFormat>CMB-{0000}</displayFormat>
        <label>Contract Misc Billable Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contract Misc Billables</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

peac_dev/force-app/main/default/objects/Contract_Misc_Billable__c/fields/Contract__c.field-meta.xml
<CustomField>
    <fullName>Contract__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contract</label>
    <referenceTo>Contract__c</referenceTo>
    <relationshipLabel>Contract Misc Billables</relationshipLabel>
    <relationshipName>Contract_Misc_Billables</relationshipName>
    <type>Lookup</type>
</CustomField>

peac_dev/force-app/main/default/classes/SL_DeleteCMBillableTest.cls
@isTest
public with sharing class SL_DeleteCMBillableTest {
    @isTest
    static void deleteExternal() {
        SL_SCTestData.createAccountAndContracts(1, 1);
        Contract__c contract = [SELECT Id FROM Contract__c];
        Contract_Misc_Billable__c cmb = new Contract_Misc_Billable__c(Contract__c=contract.Id);
        insert cmb;
        String actual;
        Test.StartTest();
        actual = SL_DeleteCMBillable.deleteExternalFirst('deleteExternal', cmb.Id);
        
        PageReference pageRef = Page.SL_DeleteContractMiscBillable;
        pageRef.getParameters().put('id', String.valueOf(cmb.Id));
        Test.setCurrentPage(pageRef);
        ApexPages.StandardController sc = new ApexPages.StandardController(cmb);
        SL_DeleteCMBillable vfController = new SL_DeleteCMBillable(sc);
        vfController.goBackNotDeleted();
        vfController.goToContract();
        Test.stopTest();
        System.assert(true);
    }
    @isTest
    static void deleteInternal() {
        SL_SCTestData.createAccountAndContracts(1, 1);
        Contract__c contract = [SELECT Id FROM Contract__c];
        Contract_Misc_Billable__c cmb = new Contract_Misc_Billable__c(Contract__c=contract.Id);
        insert cmb;
        String actual;
        Test.StartTest();
        actual = SL_DeleteCMBillable.deleteExternalFirst('deleteInternal', cmb.Id);
        Test.stopTest();
        System.assert(actual.contains('{"isSuccess": true, "contractId": "'));
    }
}