peac_dev/force-app/main/default/objects/Contract__c/Contract__c.object-meta.xml
<CustomObject>
    <description>Custom Object created so we can use Queue functionality</description>
    <label>Contract</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Contract Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Contracts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

peac_dev/force-app/main/default/objects/Contract__c/fields/Infolease_Environment__c.field-meta.xml
<CustomField>
    <fullName>Infolease_Environment__c</fullName>
    <label>Infolease Environment</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>9</fullName>
            </value>
            <value>
                <fullName>10</fullName>
            </value>
            <value>
                <fullName>C</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

peac_dev/force-app/main/default/objects/Contract__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Disposed</fullName>
            </value>
            <value>
                <fullName>Disposed - Charged Off</fullName>
            </value>
            <value>
                <fullName>Renewal</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

peac_dev/force-app/main/default/objects/SL_BW_Integration_Status__e/SL_BW_Integration_Status__e.object-meta.xml
<CustomObject>
    <label>SL BW Integration Status</label>
    <pluralLabel>SL BW Integration Status</pluralLabel>
</CustomObject>

peac_dev/force-app/main/default/classes/SL_InfoleaseContractHandler.cls
public with sharing class SL_InfoleaseContractHandler {
    public static void updateContractInIL(List<Contract__c> validContractList){
        System.debug(validcontractlist);		       
        if (!System.isFuture() && !System.isBatch()){
            SL_InfoleaseContractBatchQueueable queueableJob = new SL_InfoleaseContractBatchQueueable(validContractList, null, true);
            System.enqueueJob(queueableJob);
            // String jobId = Database.executeBatch(new SL_InfoleaseContractQueueable(validContractList,null,true),1);
            /*for(Contract__c thisCon : validContractList){
                EventBus.publish( new SL_BW_Integration_Status__e(Message__c = 'Sync in progress. Do not close or refresh this page.', Status__c = 'In Progress', Record_Id__c = thisCon.Id ));
                updateContractFuture(thisCon.Id, null, thisCon.Infolease_Environment__c);
            }*/
        }
    }
    public static void updateSpecificFields(Map<Contract__c, Set<String>> conToFieldsMap) {
        if (!System.isFuture() && !System.isBatch()){
            SL_InfoleaseContractBatchQueueable queueableJob = new SL_InfoleaseContractBatchQueueable(null, conToFieldsMap, false);
            System.enqueueJob(queueableJob);
            //String jobId = Database.executeBatch(new SL_InfoleaseContractQueueable(null,conToFieldsMap,false),1);
            //Contract__c conRec = new List<Contract__c>(conToFieldsMap.keySet())[0];
            /*for(Contract__c conRec : conToFieldsMap.keySet()){
                Set<String> changedFieldSet = conToFieldsMap.get(conRec);
                EventBus.publish( new SL_BW_Integration_Status__e(Message__c = 'Sync in progress. Do not close or refresh this page.', Status__c = 'In Progress', Record_Id__c = conRec.Id ));
                updateContractFuture(conRec.Id, changedFieldSet,  conRec.Infolease_Environment__c);
            }*/
        }
    }
    
    //Now on QueueableClass
    @future(callout = true)
    public static void updateContractFuture(String contractId, Set<String> changedFieldSet, String ilEnvironment){
        SL_InfoleaseContractHelper contractAPI = new SL_InfoleaseContractHelper(contractId);
        SL_InfoleaseContractService service = new SL_InfoleaseContractService();

        service.recordId = contractAPI.recordId;

        if (contractAPI.validate()) {
            /*try{
                if(changedFieldSet == null){
                    SL_InfoleaseContractRequestWrapper request = contractAPI.createRequest();
                    String errorMessage = String.join(contractAPI.getErrorMessages(), ',');
                    if(String.isNotEmpty(errorMessage)){
                        publishError(errorMessage, contractId);
                    }else{
                        SL_InfoleaseIntegrationResponseWrapper response = service.updateContract(request, null, ilEnvironment);
                    }
                }else {
                    String requestString = contractAPI.mapSpecificFields(contractId, changedFieldSet);
                    String errorMessage = String.join(contractAPI.getErrorMessages(), ',');
                    if(String.isNotEmpty(errorMessage)){
                        publishError(errorMessage, contractId);
                    }else{
                        SL_InfoleaseIntegrationResponseWrapper response = service.updateContract(null, requestString, ilEnvironment);
                    }
                }
            } catch (Exception e) {
                SL_InfoleaseLoggingUtils.addLog(SL_InfoleaseConstants.contractUpdateJob , contractAPI.recordId, '', '', e.getMessage(), true);
                SL_InfoleaseLoggingUtils.flush();
                SL_InfoleaseUtils.updateRecordWithError(contractAPI.recordId);
            }*/
        }else{
            String errorMessage = String.join(contractAPI.getErrorMessages(), ',');
            publishError(errorMessage, contractId);
            return;
        }

    }

    private static void publishError(String errorMessage, Id contractId){
        EventBus.publish( new SL_BW_Integration_Status__e(Message__c = SL_InfoleaseConstants.errorOccurred+errorMessage+'\n'+SL_InfoleaseConstants.contactAdmin, Status__c = 'Error', Record_Id__c = contractId ));
        SL_InfoleaseLoggingUtils.addLog(SL_InfoleaseConstants.contractUpdateJob , contractId, '', '', errorMessage, true);
        SL_InfoleaseLoggingUtils.flush();
        SL_InfoleaseUtils.updateRecordWithError(contractId);
    }
}