peac_dev/force-app/main/default/objects/Contract__c/Contract__c.object-meta.xml
<CustomObject>
    <description>Custom Object created so we can use Queue functionality</description>
    <label>Contract</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Contract Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Contracts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

peac_dev/force-app/main/default/objects/Contract__c/fields/Commencement_Date__c.field-meta.xml
<CustomField>
    <fullName>Commencement_Date__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Commencement Date</label>
    <type>Date</type>
</CustomField>

peac_dev/force-app/main/default/objects/Contract__c/fields/Contract_Balance_Remaining__c.field-meta.xml
<CustomField>
    <fullName>Contract_Balance_Remaining__c</fullName>
    <label>Contract Balance Remaining</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

peac_dev/force-app/main/default/objects/Contract__c/fields/Customer__c.field-meta.xml
<CustomField>
    <fullName>Customer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Customer account</description>
    <label>Customer</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Customer_Contracts</relationshipName>
    <type>Lookup</type>
</CustomField>

peac_dev/force-app/main/default/objects/Contract__c/fields/Delinquency_Status_Code__c.field-meta.xml
<CustomField>
    <fullName>Delinquency_Status_Code__c</fullName>
    <label>Delinquency Status Code</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>00</fullName>
                <label>Not delinquent</label>
            </value>
            <value>
                <fullName>01</fullName>
                <label>Past due 01 - 30 days</label>
            </value>
            <value>
                <fullName>31</fullName>
                <label>Past due 31 - 60 days</label>
            </value>
            <value>
                <fullName>61</fullName>
                <label>Past due 61 - 90 days</label>
            </value>
            <value>
                <fullName>91</fullName>
                <label>Past due 91 - 120 days</label>
            </value>
            <value>
                <fullName>121</fullName>
                <label>Past due 121 - 150 days</label>
            </value>
            <value>
                <fullName>151</fullName>
                <label>Past due 151 - 180 days</label>
            </value>
            <value>
                <fullName>181</fullName>
                <label>Past due 181 days and more</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

peac_dev/force-app/main/default/objects/Contract__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Disposed</fullName>
            </value>
            <value>
                <fullName>Disposed - Charged Off</fullName>
            </value>
            <value>
                <fullName>Renewal</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

peac_dev/force-app/main/default/objects/Contract__c/fields/Term_Date__c.field-meta.xml
<CustomField>
    <fullName>Term_Date__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Term Date</label>
    <type>Date</type>
</CustomField>

peac_dev/force-app/main/default/objects/Contract__c/fields/Total_Past_Due__c.field-meta.xml
<CustomField>
    <fullName>Total_Past_Due__c</fullName>
    <label>Total Past Due</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

peac_dev/force-app/main/default/classes/SL_OtherContractsController.cls
/**
 * SL-1283 Developed by Harsh@Silverline 11/04/2022
 */
public with sharing class SL_OtherContractsController {
    @AuraEnabled
    public static List<Contract__c> getContractList(Id recordId){
        List<Contract__c> conLst = [SELECT Id, Customer__c FROM Contract__c WHERE Id =: recordId LIMIT 1];
        List<Contract__c> contractList;
        if(conLst.size() > 0){
            contractList = [SELECT Id, Name, Contract_Balance_Remaining__c,
                            Total_Past_Due__c, Delinquency_Status_Code__c, Status__c,
                            Commencement_Date__c, Term_Date__c, OwnerId, Owner.Name
                            FROM Contract__c 
                            WHERE Customer__c =: conLst[0].Customer__c 
                            AND Id !=: recordId];
        }
        return contractList;
    }
}