peac_dev/force-app/main/default/objects/Contract__c/Contract__c.object-meta.xml
<CustomObject>
    <description>Custom Object created so we can use Queue functionality</description>
    <label>Contract</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Contract Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Contracts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

peac_dev/force-app/main/default/objects/Contract__c/fields/Dealer_Account__c.field-meta.xml
<CustomField>
    <fullName>Dealer_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Account related to the Partner user who created the Opportunity through the Dealer Portal</description>
    <label>Dealer Account (Do Not Use)</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Contracts (Dealer Account)</relationshipLabel>
    <relationshipName>DealerAccount_Contracts</relationshipName>
    <type>Lookup</type>
</CustomField>

peac_dev/force-app/main/default/objects/Contract__c/fields/Dealer_Name__c.field-meta.xml
<CustomField>
    <fullName>Dealer_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Dealer Name</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 OR 2 OR 3</booleanFilter>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Broker Account</value>
        </filterItems>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Dealer Account</value>
        </filterItems>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Franchisor Account</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Contracts (Dealer Name)</relationshipLabel>
    <relationshipName>Custom_Contracts</relationshipName>
    <type>Lookup</type>
</CustomField>

peac_dev/force-app/main/default/objects/Contract__c/fields/Dealer_User__c.field-meta.xml
<CustomField>
    <fullName>Dealer_User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>user that created the Opportunity through the Dealer Portal</description>
    <label>Dealer User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>DealerUser_Contracts</relationshipName>
    <type>Lookup</type>
</CustomField>

peac_dev/force-app/main/default/objects/Contract__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipName>Custom_Contracts</relationshipName>
    <type>Lookup</type>
</CustomField>

peac_dev/force-app/main/default/objects/Dealer__c/Dealer__c.object-meta.xml
<CustomObject>
    <label>Dealer</label>
    <nameField>
        <displayFormat>B-{0000}</displayFormat>
        <label>Dealer Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Dealers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

peac_dev/force-app/main/default/objects/Dealer__c/fields/Dealer__c.field-meta.xml
<CustomField>
    <fullName>Dealer__c</fullName>
    <label>Account</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Dealer Account, Dealer_Account Development, Dealer_Account Penetration, Dealer_Close, Dealer_Discovery, Dealer_Proposal, Dealer_Qualification</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Dealer Opportunities</relationshipLabel>
    <relationshipName>Dealers</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

peac_dev/force-app/main/default/objects/Dealer__c/fields/Funded__c.field-meta.xml
<CustomField>
    <fullName>Funded__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Funded?</label>
    <type>Checkbox</type>
</CustomField>

peac_dev/force-app/main/default/objects/Dealer__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipName>Brokers</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

peac_dev/force-app/main/default/objects/Dealer__c/fields/Primary_Dealer__c.field-meta.xml
<CustomField>
    <fullName>Primary_Dealer__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Indicates if the dealer is primary dealer.</description>
    <label>Primary Dealer</label>
    <type>Checkbox</type>
</CustomField>

peac_dev/force-app/main/default/classes/SL_DPSharingRecalcTest.cls
@isTest
public with sharing class SL_DPSharingRecalcTest {
    @TestSetup
    static void makeData(){
        SL_SCTestData.createExternalHierarchy();
    }

    @isTest
    public static void sendContractBatch() {
        List<User> portalUsers = [SELECT Id, Contact.AccountId, userName, isPortalEnabled, IsActive, IsPrmSuperUser FROM User WHERE UserName LIKE 'Portal.SL.test.user%@silverlinecrm.com'];
        List<Contract__c> contracts = [SELECT Id, Dealer_Name__c FROM Contract__c];
        List<Opportunity> opps = [SELECT Id, Dealer_Account__c FROM Opportunity];
        List<Account> theAccounts = [SELECT Id, Name FROM Account];
        Account portalAccount = theAccounts[1];
        Test.startTest();
        contracts[0].Dealer_Name__c = portalAccount.Id;
        contracts[0].Dealer_User__c = portalUsers[0].Id;
        update contracts[0];
        Dealer__c testDealer = new Dealer__c(Opportunity__c = opps[0].Id, Dealer__c = portalAccount.Id,
            Funded__c = false, Primary_Dealer__c = true);
        insert testDealer;
        opps[0].Dealer_User__c = portalUsers[0].Id;
        update opps[0];
        List<String> dealerAccountIds = new List<String>();
        dealerAccountIds.add(theAccounts[1].Id);
        Database.executeBatch(new SL_DPSharingRecalcBatch('AccountShare', dealerAccountIds));
        Database.executeBatch(new SL_DPSharingRecalcBatch('Contract__Share', dealerAccountIds));
        Database.executeBatch(new SL_DPSharingRecalcBatch('OpportunityShare', dealerAccountIds));
        Database.executeBatch(new SL_DPSharingRecalcBatch('UserShare', true));
        Database.executeBatch(new SL_DPSharingRecalcBatch('UserShare', dealerAccountIds));
        SL_DPSharingRecalcBatch extraInstance = new SL_DPSharingRecalcBatch('Contract__Share', dealerAccountIds);
        List<Contract__Share> sharesToDelete = new List<Contract__Share>{
            new Contract__Share(AccessLevel = 'Read',
                    RowCause = 'Manual', ParentId = contracts[0].Id, UserOrGroupId = portalUsers[0].Id)};
        insert sharesToDelete;
        extraInstance.recalculateDeleteShares((List<SObject>)sharesToDelete);
        List<UserShare> userSharesToDelete = new List<UserShare>{
            new UserShare(UserAccessLevel = 'Read', RowCause = 'Manual', UserId = portalUsers[0].Id, UserOrGroupId = portalUsers[1].Id)
        };
        insert userSharesToDelete;
        extraInstance = new SL_DPSharingRecalcBatch('UserShare', dealerAccountIds);
        extraInstance.recalculateDeleteShares((List<SObject>)userSharesToDelete);
        extraInstance = new SL_DPSharingRecalcBatch('User', dealerAccountIds);
        extraInstance.recalculateInsertShares((List<SObject>)portalUsers);
        Database.executeBatch(new SL_DPSharingRecalcBatch((List<SObject>)sharesToDelete, 'Contract__c'));// insert remaining
        List<SObject> allTheRecords = new List<SObject>();
        for(Integer i = 0; i < 20001; i++){
            allTheRecords.add(new Contract__Share(AccessLevel = 'Read',
                RowCause = 'Manual', ParentId = contracts[0].Id, UserOrGroupId = portalUsers[0].Id));
        }
        List<List<SObject>> partitionedList = SL_DPSharingRecalcBatch.splitDMLList(allTheRecords);
        Test.stopTest();
        System.Assert.areEqual(10000, partitionedList[0].size(), 'first element must have 10000 records');
        System.Assert.areEqual(1, partitionedList[2].size(), 'third element must have 1 record');
    }
}