peac_dev/force-app/main/default/objects/Contract__c/Contract__c.object-meta.xml
<CustomObject>
    <description>Custom Object created so we can use Queue functionality</description>
    <label>Contract</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Contract Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Contracts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

peac_dev/force-app/main/default/objects/Contract__c/fields/Address_1__c.field-meta.xml
<CustomField>
    <fullName>Address_1__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Address 1</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

peac_dev/force-app/main/default/objects/Contract__c/fields/Address_2__c.field-meta.xml
<CustomField>
    <fullName>Address_2__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Address 2</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

peac_dev/force-app/main/default/objects/Contract__c/fields/Address_3__c.field-meta.xml
<CustomField>
    <fullName>Address_3__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Address 3</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

peac_dev/force-app/main/default/objects/Contract__c/fields/AR_Address_1__c.field-meta.xml
<CustomField>
    <fullName>AR_Address_1__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>AR Address 1</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

peac_dev/force-app/main/default/objects/Contract__c/fields/AR_Address_2__c.field-meta.xml
<CustomField>
    <fullName>AR_Address_2__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>AR Address 2</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

peac_dev/force-app/main/default/objects/Contract__c/fields/AR_Address_3__c.field-meta.xml
<CustomField>
    <fullName>AR_Address_3__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>AR Address 3</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

peac_dev/force-app/main/default/objects/Contract__c/fields/AR_City__c.field-meta.xml
<CustomField>
    <fullName>AR_City__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>AR City</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

peac_dev/force-app/main/default/objects/Contract__c/fields/AR_Name__c.field-meta.xml
<CustomField>
    <fullName>AR_Name__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>AR Name</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

peac_dev/force-app/main/default/objects/Contract__c/fields/AR_State__c.field-meta.xml
<CustomField>
    <fullName>AR_State__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>AR State</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

peac_dev/force-app/main/default/objects/Contract__c/fields/AR_Zip_Code__c.field-meta.xml
<CustomField>
    <fullName>AR_Zip_Code__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>AR Zip Code</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

peac_dev/force-app/main/default/objects/Contract__c/fields/Attention__c.field-meta.xml
<CustomField>
    <fullName>Attention__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Attention</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

peac_dev/force-app/main/default/objects/Contract__c/fields/City__c.field-meta.xml
<CustomField>
    <fullName>City__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>City</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

peac_dev/force-app/main/default/objects/Contract__c/fields/Customer__c.field-meta.xml
<CustomField>
    <fullName>Customer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Customer account</description>
    <label>Customer</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Customer_Contracts</relationshipName>
    <type>Lookup</type>
</CustomField>

peac_dev/force-app/main/default/objects/Contract__c/fields/Invoice_Code__c.field-meta.xml
<CustomField>
    <fullName>Invoice_Code__c</fullName>
    <label>Invoice Code</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>A</fullName>
                <label>A - Inv By Customer</label>
            </value>
            <value>
                <fullName>S</fullName>
                <label>S - Inv Suppressed</label>
            </value>
            <value>
                <fullName>C</fullName>
                <label>C - Inv By Contract</label>
            </value>
            <value>
                <fullName>B</fullName>
                <label>B - Contract Separated</label>
            </value>
            <value>
                <fullName>R</fullName>
                <label>R - Rentals Separated</label>
            </value>
            <value>
                <fullName>N</fullName>
                <label>N - No More Invoicing</label>
            </value>
            <value>
                <fullName>M</fullName>
                <label>M - Manual Invoicing</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

peac_dev/force-app/main/default/objects/Contract__c/fields/PO_Number__c.field-meta.xml
<CustomField>
    <fullName>PO_Number__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>PO#</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

peac_dev/force-app/main/default/objects/Contract__c/fields/Quote_Buyout__c.field-meta.xml
<CustomField>
    <fullName>Quote_Buyout__c</fullName>
    <label>Quote Buyout</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>01</fullName>
                <label>01 - Yes, limit 1</label>
            </value>
            <value>
                <fullName>02</fullName>
                <label>02 - Yes, unlimited</label>
            </value>
            <value>
                <fullName>03</fullName>
                <label>03 - No B/O</label>
            </value>
            <value>
                <fullName>04</fullName>
                <label>04 - Assigned Resid, Notify Vendor to Quote B/O, Send Rep Alert</label>
            </value>
            <value>
                <fullName>05</fullName>
                <label>05 - Yes, notify vendor</label>
            </value>
            <value>
                <fullName>06</fullName>
                <label>06 - No, vendor to quote</label>
            </value>
            <value>
                <fullName>07</fullName>
                <label>07 - 1st Right of Refusal, Notify Vendor of Buyout Before Lessee</label>
            </value>
            <value>
                <fullName>08</fullName>
                <label>08 - Unlocked Assigned Resid - CS</label>
            </value>
            <value>
                <fullName>09</fullName>
                <label>09 - Unlocked Assigned Resid - Contract in Default</label>
            </value>
            <value>
                <fullName>11</fullName>
                <label>11 - Special Net Investment Addendum - see file</label>
            </value>
            <value>
                <fullName>12</fullName>
                <label>12 - Add-on contract, Must quote b/o together w/ main asset</label>
            </value>
            <value>
                <fullName>13</fullName>
                <label>13 - Software addendum, special buyout letter, no ownership</label>
            </value>
            <value>
                <fullName>14</fullName>
                <label>14 - Do not quote to lessee for 7 Days, notify vendor first</label>
            </value>
            <value>
                <fullName>15</fullName>
                <label>15 - Service Fees</label>
            </value>
            <value>
                <fullName>18</fullName>
                <label>18 - EOT</label>
            </value>
            <value>
                <fullName>19</fullName>
                <label>19 - Adtran if equipment return or Repo</label>
            </value>
            <value>
                <fullName>20</fullName>
                <label>20 - Assigned Residual No Renewal</label>
            </value>
            <value>
                <fullName>22</fullName>
                <label>22 - NO BUYOUT - RENTAL NO PURCHASE OPTION</label>
            </value>
            <value>
                <fullName>23</fullName>
                <label>23 - Call Syndication Partner for Buyout Quotes</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

peac_dev/force-app/main/default/objects/Contract__c/fields/Reprint_Invoice__c.field-meta.xml
<CustomField>
    <fullName>Reprint_Invoice__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Reprint Invoice</label>
    <type>Checkbox</type>
</CustomField>

peac_dev/force-app/main/default/objects/Contract__c/fields/State__c.field-meta.xml
<CustomField>
    <fullName>State__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>State</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

peac_dev/force-app/main/default/objects/Contract__c/fields/Tax_ID__c.field-meta.xml
<CustomField>
    <fullName>Tax_ID__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Tax ID</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

peac_dev/force-app/main/default/objects/Contract__c/fields/User_Code__c.field-meta.xml
<CustomField>
    <fullName>User_Code__c</fullName>
    <label>User Code</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>01</fullName>
                <label>01 - Early Buyout More Than 2 Payments Left in Term</label>
            </value>
            <value>
                <fullName>02</fullName>
                <label>02 - Early Buyout 2 or Less Payments Left in Term</label>
            </value>
            <value>
                <fullName>03</fullName>
                <label>03 - 90 Day Same as Cash Buyout</label>
            </value>
            <value>
                <fullName>04</fullName>
                <label>04 - Trade Up</label>
            </value>
            <value>
                <fullName>05</fullName>
                <label>05 - Insurance Payoff</label>
            </value>
            <value>
                <fullName>06</fullName>
                <label>06 - Settlement With Gain</label>
            </value>
            <value>
                <fullName>07</fullName>
                <label>07 - Residual Refinance</label>
            </value>
            <value>
                <fullName>11</fullName>
                <label>11 - Paid Lease Returned Equipment</label>
            </value>
            <value>
                <fullName>12</fullName>
                <label>12 - Paid Lease Previously in Renewal</label>
            </value>
            <value>
                <fullName>13</fullName>
                <label>13 - Paid Lease Previously in Renewal With Equipment Return</label>
            </value>
            <value>
                <fullName>14</fullName>
                <label>14 - End of Term Trade Up</label>
            </value>
            <value>
                <fullName>15</fullName>
                <label>15 - Trade Up To Return</label>
            </value>
            <value>
                <fullName>16</fullName>
                <label>16 - Residual Charge Off Legal Transfer</label>
            </value>
            <value>
                <fullName>19</fullName>
                <label>19 - Fee Settlement Disposition</label>
            </value>
            <value>
                <fullName>20</fullName>
                <label>20 - Contractual Default Company OOB</label>
            </value>
            <value>
                <fullName>21</fullName>
                <label>21 - Contractual Default Cash Flow Problem</label>
            </value>
            <value>
                <fullName>22</fullName>
                <label>22 - Contractual Default Company Sold</label>
            </value>
            <value>
                <fullName>23</fullName>
                <label>23 - Contractual Default Hell or High Water</label>
            </value>
            <value>
                <fullName>24</fullName>
                <label>24 - Type 1 Fraud</label>
            </value>
            <value>
                <fullName>25</fullName>
                <label>25 - Bankruptcy Chapter 7</label>
            </value>
            <value>
                <fullName>26</fullName>
                <label>26 - Bankruptcy Chapter 11</label>
            </value>
            <value>
                <fullName>27</fullName>
                <label>27 - Bankruptcy Chapter 13</label>
            </value>
            <value>
                <fullName>28</fullName>
                <label>28 - Settlement/Hell or High Water</label>
            </value>
            <value>
                <fullName>29</fullName>
                <label>29 - Apparent Authority</label>
            </value>
            <value>
                <fullName>30</fullName>
                <label>30 - Vendor Buy Back With Loss</label>
            </value>
            <value>
                <fullName>31</fullName>
                <label>31 - OOB No PG</label>
            </value>
            <value>
                <fullName>32</fullName>
                <label>32 - Receiverships</label>
            </value>
            <value>
                <fullName>33</fullName>
                <label>33 - Deceased</label>
            </value>
            <value>
                <fullName>34</fullName>
                <label>34 - Contractual Default Buyer&apos;s Remorse</label>
            </value>
            <value>
                <fullName>35</fullName>
                <label>35 - Settlement With Loss</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

peac_dev/force-app/main/default/objects/Contract__c/fields/Zip_Code__c.field-meta.xml
<CustomField>
    <fullName>Zip_Code__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Zip Code</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

peac_dev/force-app/main/default/classes/SL_InfoleaseContractHelper.cls
public with sharing class SL_InfoleaseContractHelper {
    private List<String> errorMessages;
    private Contract__c thisContract;
    public Id recordId;

    private SL_InfoleaseContractRequestWrapper request;
    public SL_InfoleaseUtils util = SL_InfoleaseUtils.getInstance();

    public SL_InfoleaseContractHelper(Id contractId) {
        recordId = contractId;
        thisContract = getFields(recordId);
    }

    public SL_InfoleaseContractRequestWrapper createRequest() {
        mapFields();
        return request;
    }

    public Boolean validate() {
        errorMessages = new List<String>();

        if (thisContract == null) {
            errorMessages.add('Null object sent to updateContract!');
            return errorMessages.isEmpty();
        }
        return errorMessages.isEmpty();
    }

    public List<String> getErrorMessages() { return errorMessages; }

    public boolean isValid() {
        return errorMessages.isEmpty();
    }

    private SL_InfoleaseContractRequestWrapper mapFields() {  
        String insuranceCode = getInsuranceCode(thisContract, errorMessages);
        request = new SL_InfoleaseContractRequestWrapper();

        request.Request.ContractNumber = thisContract.Name;
        request.Request.UserId = util.getServiceSettings().UserId__c == null ? 'servcloud' : util.getServiceSettings().UserId__c;

        request.Request.CUST_NAME = thisContract.Customer__r.Name;
        request.Request.CUST_ADDRESS1 = thisContract.Address_1__c;
        request.Request.CUST_ADDRESS2 = thisContract.Address_2__c;
        request.Request.CUST_ADDRESS3 = thisContract.Address_3__c;
        request.Request.CUST_CITY = thisContract.City__c;
        request.Request.CUST_STATE = thisContract.State__c;
        request.Request.CUST_ZIP = thisContract.Zip_Code__c;
        request.Request.AR_NAME = thisContract.AR_Name__c;
        request.Request.AR_ADDRESS1 = thisContract.AR_Address_1__c;
        request.Request.AR_ADDRESS2 = thisContract.AR_Address_2__c;
        request.Request.AR_ADDRESS3 = thisContract.AR_Address_3__c;
        request.Request.AR_CITY = thisContract.AR_City__c;
        request.Request.AR_STATE = thisContract.AR_State__c;
        request.Request.AR_ZIP = thisContract.AR_Zip_Code__c;
        request.Request.AR_ATTN = thisContract.Attention__c;
        request.Request.FED_ID = thisContract.Tax_ID__c;
        request.Request.INVOICE_CODE = thisContract.Invoice_Code__c;
        request.Request.USER_CODE = thisContract.User_Code__c;
        request.Request.UM_ALPHA_FIELD3 = thisContract.Reprint_Invoice__c ? 'Yes' : '';
        request.Request.INSURANCE_CODE = insuranceCode;
        request.Request.PUR_ORDER_NUM = thisContract.PO_Number__c;
		request.Request.QUOTE_BUYOUT = thisContract.Quote_Buyout__c; 
        request.Request.INVOICE_FRMT = thisContract.Invoice_Format__c;
        //End Mapping
        return request;

    }

    public String mapSpecificFields(String contractId, Set<String> changedFieldSet){
        List<String> fieldList = new List<String>(changedFieldSet);

        Map<String,String> wrapVarFieldMap = new Map<String,String>{
            'Name' => 'ContractNumber',
            'Customer__r.Name' => 'CUST_NAME',
            'Address_1__c' => 'CUST_ADDRESS1',
            'Address_2__c' => 'CUST_ADDRESS2',
            'Address_3__c' => 'CUST_ADDRESS3',
            'City__c' => 'CUST_CITY',
            'State__c' => 'CUST_STATE',
            'Zip_Code__c' => 'CUST_ZIP',
            'AR_Name__c' => 'AR_NAME',
            'AR_Address_1__c' => 'AR_ADDRESS1',
            'AR_Address_2__c' => 'AR_ADDRESS2',
            'AR_Address_3__c' => 'AR_ADDRESS3',
            'AR_City__c' => 'AR_CITY',
            'AR_State__c' => 'AR_STATE',
            'AR_Zip_Code__c' => 'AR_ZIP',
            'Attention__c' => 'AR_ATTN',
            'Tax_ID__c' => 'FED_ID',
            'Invoice_Code__c' => 'INVOICE_CODE',
            'User_Code__c' => 'USER_CODE',
            'Reprint_Invoice__c' => 'UM_ALPHA_FIELD3',
            'Insurance_Status__c' => 'INSURANCE_CODE',
            'PO_Number__c' => 'PUR_ORDER_NUM',
            'Quote_Buyout__c' => 'QUOTE_BUYOUT',
            'Invoice_Format__c' => 'INVOICE_FRMT'
        }; 

        JSONGenerator gen = JSON.createGenerator(true);

        gen.writeStartObject();
        for(String thisField : fieldList){
            switch on thisField{
                when 'Reprint_Invoice__c'{
                    gen.writeStringField('UM_ALPHA_FIELD3', thisContract.get('Reprint_Invoice__c') == true ? 'Yes' : '');
                }
                when 'Insurance_Status__c'{
                    String insuranceCode = getInsuranceCode(thisContract, errorMessages);
                    gen.writeStringField(wrapVarFieldMap.get(thisField), String.valueOf(insuranceCode != null ? insuranceCode : ''));
                }
                when else{
                    gen.writeStringField(wrapVarFieldMap.get(thisField), String.valueOf(thisContract.get(thisField) != null ? thisContract.get(thisField) : ''));
                }
            }
            if(thisField == 'Reprint_Invoice__c'){
                
            }else{
                
            }
        }
        gen.writeStringField('UserId', util.getServiceSettings().UserId__c == null ? 'servcloud' : util.getServiceSettings().UserId__c);
        gen.writeEndObject();

        String pretty = gen.getAsString();

        pretty = '{'+
                '"Header" : {'+
                '"NitroApi" : "BW.UPDATE.CONTRACT"'+
                '},'+
                '"Request" : '+ pretty +
                '}';
        return pretty;
    }

    private Contract__c getFields(Id contractId) {

        Contract__c thisContract;
        try{
            thisContract =  [SELECT Customer__r.Name, Address_1__c, Address_2__c,Address_3__c, City__c, State__c, Zip_Code__c, AR_Name__c, 
                AR_Address_1__c, AR_Address_2__c,  AR_Address_3__c, AR_City__c, AR_State__c, Name,PO_Number__c,
                    AR_Zip_Code__c, Attention__c, Tax_ID__c, Invoice_Code__c, User_Code__c, Reprint_Invoice__c, Insurance_Status__c, 
                    Quote_Buyout__c, Invoice_Format__c, Infolease_Environment__c
                    FROM Contract__c  
                    WHERE Id = :contractId];
            return thisContract;
        }catch(Exception e){
            return null;
        }
    }

    public static String getInsuranceCode(Contract__c thisContract, List<String> errorMessages){
        String insuranceCode = thisContract.Insurance_Status__c;
        IL10_Flag__c il10Setting = IL10_Flag__c.getValues('GeneralSetting');
        Boolean isIL10 = TC_BWUtility.isIL10Record(thisContract);
        Map<String, String> insuranceStatuses = new Map<String, String>();
        Map<String, String> insuranceCodesByValue = new Map<String, String>();
        Schema.DescribeFieldResult dfr = Contract__c.Insurance_Status__c.getDescribe();
        for (Schema.PicklistEntry ple : dfr.getPicklistValues()){
            insuranceStatuses.put(ple.getValue(), ple.getLabel().toLowerCase());
        }
        for(Insurance_Status_Code__mdt insuranceCodeMDT : [SELECT Infolease_9_Code__c, Picklist_Value__c, Infolease_10_Code__c FROM Insurance_Status_Code__mdt]){
            if(il10Setting.use_IL10__c && isIL10){
                insuranceCodesByValue.put(insuranceCodeMDT.Picklist_Value__c.toLowerCase(), insuranceCodeMDT.Infolease_10_Code__c);
            }else{
                insuranceCodesByValue.put(insuranceCodeMDT.Picklist_Value__c.toLowerCase(), insuranceCodeMDT.Infolease_9_Code__c);
            }
        }
        String picklistValue = insuranceStatuses.get(thisContract.Insurance_Status__c);
        String codeToSend = insuranceCodesByValue.get(picklistValue);
        insuranceCode = codeToSend == null? thisContract.Insurance_Status__c: codeToSend;
        if(il10Setting.use_IL10__c && isIL10 && insuranceCode != '25'){// Jaclyn stated that only 25 is gonna be sent to IL10
            insuranceCode = '';
            errorMessages.add('Contract not Synced, The Insurance Status wasn\'t sent to InfoLease, only Request Cancel can be sent.');
        }
        return insuranceCode;
    }
}