peac_dev/force-app/main/default/objects/Contract__c/Contract__c.object-meta.xml
<CustomObject>
    <description>Custom Object created so we can use Queue functionality</description>
    <label>Contract</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Contract Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Contracts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

peac_dev/force-app/main/default/objects/Contract__c/fields/Customer__c.field-meta.xml
<CustomField>
    <fullName>Customer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Customer account</description>
    <label>Customer</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Customer_Contracts</relationshipName>
    <type>Lookup</type>
</CustomField>

peac_dev/force-app/main/default/objects/Contract__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipName>Custom_Contracts</relationshipName>
    <type>Lookup</type>
</CustomField>

peac_dev/force-app/main/default/objects/Contract__c/recordTypes/Loan.recordType-meta.xml
<RecordType>
    <fullName>Loan</fullName>
    <active>false</active>
    <label>Loan</label>
</RecordType>

peac_dev/force-app/main/default/objects/Contract_Attachment__c/Contract_Attachment__c.object-meta.xml
<CustomObject>
    <description>this will use OnBase</description>
    <label>Contract Attachment</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>File Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Contract Attachments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

peac_dev/force-app/main/default/objects/Contract_Attachment__c/fields/Contract__c.field-meta.xml
<CustomField>
    <fullName>Contract__c</fullName>
    <label>Contract</label>
    <referenceTo>Contract__c</referenceTo>
    <relationshipLabel>Contract Attachments</relationshipLabel>
    <relationshipName>Contract_Attachments</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

peac_dev/force-app/main/default/objects/Contract_Attachment__c/fields/isFromDocGen__c.field-meta.xml
<CustomField>
    <fullName>isFromDocGen__c</fullName>
    <defaultValue>false</defaultValue>
    <description>to send automatically to OnBase when they attach the file</description>
    <label>isFromDocGen</label>
    <type>Checkbox</type>
</CustomField>

peac_dev/force-app/main/default/objects/Contract_Attachment__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Document Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Type_Group__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>CL - Credit Bureau Reports</fullName>
            </value>
            <value>
                <fullName>CL - Customer Correspondence</fullName>
            </value>
            <value>
                <fullName>CL - Demand Letters</fullName>
            </value>
            <value>
                <fullName>CL - Investigations</fullName>
            </value>
            <value>
                <fullName>CL - Misc</fullName>
            </value>
            <value>
                <fullName>CS - Address Change</fullName>
            </value>
            <value>
                <fullName>CS - Assumption / Restructure Documentation</fullName>
            </value>
            <value>
                <fullName>CS - Change Request</fullName>
            </value>
            <value>
                <fullName>CS - EOT Form</fullName>
            </value>
            <value>
                <fullName>CS - Letters of Intent</fullName>
            </value>
            <value>
                <fullName>CS - Misc</fullName>
            </value>
            <value>
                <fullName>CS - Tax Exempt Certificates</fullName>
            </value>
            <value>
                <fullName>FS - ACH_Auto Debit Forms and Copy of Check</fullName>
            </value>
            <value>
                <fullName>FS - Additional Stipulations</fullName>
            </value>
            <value>
                <fullName>FS - Bank Account Change Request</fullName>
            </value>
            <value>
                <fullName>FS - Bank Statements</fullName>
            </value>
            <value>
                <fullName>FS - Bank Statements - Apr</fullName>
            </value>
            <value>
                <fullName>FS - Bank Statements - Aug</fullName>
            </value>
            <value>
                <fullName>FS - Bank Statements - Dec</fullName>
            </value>
            <value>
                <fullName>FS - Bank Statements - Feb</fullName>
            </value>
            <value>
                <fullName>FS - Bank Statements - Jan</fullName>
            </value>
            <value>
                <fullName>FS - Bank Statements - Jul</fullName>
            </value>
            <value>
                <fullName>FS - Bank Statements - Jun</fullName>
            </value>
            <value>
                <fullName>FS - Bank Statements - Mar</fullName>
            </value>
            <value>
                <fullName>FS - Bank Statements - May</fullName>
            </value>
            <value>
                <fullName>FS - Bank Statements - Nov</fullName>
            </value>
            <value>
                <fullName>FS - Bank Statements - Oct</fullName>
            </value>
            <value>
                <fullName>FS - Bank Statements - Sept</fullName>
            </value>
            <value>
                <fullName>FS - Bank Statements MTD</fullName>
            </value>
            <value>
                <fullName>FS - Blank Loan Documents</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

peac_dev/force-app/main/default/objects/Opportunity_Attachment__c/Opportunity_Attachment__c.object-meta.xml
<CustomObject>
    <label>OnBase Attachment</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>File Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>OnBase Attachments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

peac_dev/force-app/main/default/objects/Opportunity_Attachment__c/fields/Attachment__c.field-meta.xml
<CustomField>
    <fullName>Attachment__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Attachment</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

peac_dev/force-app/main/default/objects/Opportunity_Attachment__c/fields/Dealer_Doc_Type__c.field-meta.xml
<CustomField>
    <fullName>Dealer_Doc_Type__c</fullName>
    <description>DP-254</description>
    <label>Document Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>LC - Assignment of Proceeds</fullName>
                <label>Assignment of Proceeds</label>
            </value>
            <value>
                <fullName>CR - Bank Statements</fullName>
                <label>Bank Statements</label>
            </value>
            <value>
                <fullName>CR - Credit Application</fullName>
                <label>Credit Application</label>
            </value>
            <value>
                <fullName>LC - Invoice</fullName>
                <label>Invoice</label>
            </value>
            <value>
                <fullName>CR - Invoice/Quote/Proposal</fullName>
                <label>Invoice/Quote/Proposal</label>
            </value>
            <value>
                <fullName>LC - Lease</fullName>
                <label>Lease</label>
            </value>
            <value>
                <fullName>LC - Misc</fullName>
                <label>Misc</label>
            </value>
            <value>
                <fullName>LC - Proof of Location</fullName>
                <label>POL</label>
            </value>
            <value>
                <fullName>LC - Tax Exempt Forms/Resale Certificate</fullName>
                <label>Tax Exempt Certificate</label>
            </value>
            <value>
                <fullName>Approval Letter</fullName>
            </value>
            <value>
                <fullName>FS - Approval Letter</fullName>
                <isActive>false</isActive>
                <label>FS - Approval Letter</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

peac_dev/force-app/main/default/objects/Opportunity_Attachment__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipName>Attachments</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

peac_dev/force-app/main/default/objects/Opportunity_Attachment__c/fields/Sent_To_OnBase__c.field-meta.xml
<CustomField>
    <fullName>Sent_To_OnBase__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Sent To OnBase</label>
    <type>Checkbox</type>
</CustomField>

peac_dev/force-app/main/default/objects/Opportunity_Attachment__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Document Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>CR - Credit Application</fullName>
            </value>
            <value>
                <fullName>CR - Invoice/Quote/Proposal</fullName>
            </value>
            <value>
                <fullName>CR - Financial Statements</fullName>
            </value>
            <value>
                <fullName>CR - Misc</fullName>
            </value>
            <value>
                <fullName>FS - Bank Statements</fullName>
            </value>
            <value>
                <fullName>FS - Bank Statements - Apr</fullName>
            </value>
            <value>
                <fullName>FS - Bank Statements - Aug</fullName>
            </value>
            <value>
                <fullName>FS - Bank Statements - Dec</fullName>
            </value>
            <value>
                <fullName>FS - Bank Statements - Feb</fullName>
            </value>
            <value>
                <fullName>FS - Bank Statements - Jan</fullName>
            </value>
            <value>
                <fullName>FS - Bank Statements - Jul</fullName>
            </value>
            <value>
                <fullName>FS - Bank Statements - Jun</fullName>
            </value>
            <value>
                <fullName>FS - Bank Statements - Mar</fullName>
            </value>
            <value>
                <fullName>FS - Bank Statements - May</fullName>
            </value>
            <value>
                <fullName>FS - Bank Statements - Nov</fullName>
            </value>
            <value>
                <fullName>FS - Bank Statements - Oct</fullName>
            </value>
            <value>
                <fullName>FS - Bank Statements - Sept</fullName>
            </value>
            <value>
                <fullName>FS - Bank Statements MTD</fullName>
            </value>
            <value>
                <fullName>FS - Competitor Payoff</fullName>
            </value>
            <value>
                <fullName>FS - Credit Application</fullName>
            </value>
            <value>
                <fullName>FS - Financial Statements</fullName>
            </value>
            <value>
                <fullName>FS - Tax Returns</fullName>
            </value>
            <value>
                <fullName>FS - Voided Check</fullName>
            </value>
            <value>
                <fullName>CR - Bank Statements</fullName>
            </value>
            <value>
                <fullName>FS - Landlord Reference</fullName>
            </value>
            <value>
                <fullName>FS - Lease Agreement</fullName>
            </value>
            <value>
                <fullName>FS - Mortgage Statement</fullName>
            </value>
            <value>
                <fullName>FS - Payoff Agreement</fullName>
            </value>
            <value>
                <fullName>FS - Signed Loan Agreement</fullName>
            </value>
            <value>
                <fullName>FS - Bank Statements -Sept</fullName>
            </value>
            <value>
                <fullName>FS - Approval Letter</fullName>
            </value>
            <value>
                <fullName>Approval Letter</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

peac_dev/force-app/main/default/classes/SL_AttachmentTriggerHandler.cls
public with sharing class SL_AttachmentTriggerHandler extends SL_Trigger.baseHandler {
    private Map<Id, Contract_Attachment__c> contractAttachments = new Map<Id, Contract_Attachment__c>();

    public override void afterInsert(Map<Id, SObject> newMap){
        for(SObject theObject :newMap.values()){
            getLookupMaps(theObject);
        }
        getInfoFromOthers();
        afterChangesToOthers(newMap, true);
        sendApprovedEmail(newMap);
    }

    public override void afterUpdate(Map<Id, SObject> oldMap, Map<Id, SObject> newMap) {
        for(SObject theObject :newMap.values()){
            getLookupMaps(theObject);
        }
        getInfoFromOthers();
        afterChangesToOthers(newMap, false);
        
    }

    private void getLookupMaps(SObject obj){
        Attachment theAttachment = (Attachment)obj;
        if(theAttachment.ParentId != null){
            this.contractAttachments.put(theAttachment.ParentId, new Contract_Attachment__c());
        }
    }

    private void getInfoFromOthers(){
        this.contractAttachments.putAll([SELECT Id, isFromDocGen__c, Sent_To_OnBase__c, Contract__c, Contract__r.Customer__r.Name, Attachment__c FROM Contract_Attachment__c WHERE Id IN :this.contractAttachments.keySet()]);
    }

    private void afterChangesToOthers(Map<Id, SObject> newMap, Boolean isNew){
        List<String> contractIds = new List<String>();
        List<Contract_Attachment__c> contractAttachmentsToUpdate = new List<Contract_Attachment__c>();
        Map<Id, Attachment> opportunityAttachmentsToUpdate = new Map<Id, Attachment>();
        for(SObject theObject :newMap.values()){
            Attachment theAttachment = (Attachment)theObject;
            Contract_Attachment__c contractAttachment = this.contractAttachments.get(theAttachment.ParentId);
            if(contractAttachment != null && contractAttachment.isFromDocGen__c && !contractAttachment.Sent_To_OnBase__c 
                && contractAttachment.Contract__c != null && contractAttachment.Contract__r.Customer__c != null 
                && String.isNotBlank(contractAttachment.Contract__r.Customer__r.Name)){
                contractIds.add(contractAttachment.Contract__c);
            }
            if(contractAttachment != null && theAttachment.ParentId.getSObjectType().getDescribe().getName() == 'Contract_Attachment__c'){
                contractAttachment.Attachment__c=theObject.Id;
                contractAttachmentsToUpdate.add(contractAttachment);
            }
            
            if(theAttachment.ParentId.getSObjectType().getDescribe().getName() == 'Opportunity_Attachment__c'){
                opportunityAttachmentsToUpdate.put(theAttachment.ParentId, theAttachment);
            }
            
        }
        //Update contract attachment
        if(contractAttachmentsToUpdate.size() > 0){
            update contractAttachmentsToUpdate;
        }
        //Update opportunity attachment
        if(opportunityAttachmentsToUpdate.size() > 0){
            List<Opportunity_Attachment__c> oppAttList = [SELECT Id, Name, Attachment__c FROM Opportunity_Attachment__c WHERE Id IN :opportunityAttachmentsToUpdate.keySet()];
            for(Opportunity_Attachment__c oppa : oppAttList){
                oppa.Attachment__c = opportunityAttachmentsToUpdate.get(oppa.Id).Id;
            }
            update oppAttList;
        }
        if(contractIds.size() > 0){
            System.enqueueJob(new SL_UploadAttachmentQ(contractIds));
        }
    }
    
    
    public void sendApprovedEmail(Map<Id, SObject> newMap) {
        set<id> parentIdSet = new set<id>();
        for(Attachment theAttachment : (List<Attachment>) newMap.values()) {
            if(theAttachment.ParentId.getSObjectType().getDescribe().getName() == 'Opportunity_Attachment__c'){
                parentIdSet.add(theAttachment.ParentId);
            }
        }
        Map<Id, Opportunity> approvedMap = new Map<Id, Opportunity>([select Id, OwnerId, StageName, Application_Status__c, Primary_Broker__c from Opportunity 
                                            where Id IN 
                                            (select Opportunity__c from Opportunity_Attachment__c 
                                             where 
                                             Opportunity__r.Loan_Record_Type__c = true
                                             AND (Dealer_Doc_Type__c = 'Approval Letter' OR Type__c = 'FS - Approval Letter' OR Type__c = 'Approval Letter')
                                             AND Id IN :parentIdSet)
                                           ]);
        System.debug('sendApprovedEmail::');
        if(approvedMap.size() > 0) {
             TC_SendLoanNotifications.checkNotificationCenter(approvedMap, 'Approved_Loan__c', 'Loan Approved');
        }
        
    }



}