peac_dev/force-app/main/default/objects/Contract__c/Contract__c.object-meta.xml
<CustomObject>
    <description>Custom Object created so we can use Queue functionality</description>
    <label>Contract</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Contract Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Contracts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

peac_dev/force-app/main/default/objects/Contract__c/fields/Address_1__c.field-meta.xml
<CustomField>
    <fullName>Address_1__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Address 1</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

peac_dev/force-app/main/default/objects/Contract__c/fields/Address_2__c.field-meta.xml
<CustomField>
    <fullName>Address_2__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Address 2</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

peac_dev/force-app/main/default/objects/Contract__c/fields/Address_3__c.field-meta.xml
<CustomField>
    <fullName>Address_3__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Address 3</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

peac_dev/force-app/main/default/objects/Contract__c/fields/AR_Address_1__c.field-meta.xml
<CustomField>
    <fullName>AR_Address_1__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>AR Address 1</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

peac_dev/force-app/main/default/objects/Contract__c/fields/AR_Address_2__c.field-meta.xml
<CustomField>
    <fullName>AR_Address_2__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>AR Address 2</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

peac_dev/force-app/main/default/objects/Contract__c/fields/AR_Address_3__c.field-meta.xml
<CustomField>
    <fullName>AR_Address_3__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>AR Address 3</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

peac_dev/force-app/main/default/objects/Contract__c/fields/AR_City__c.field-meta.xml
<CustomField>
    <fullName>AR_City__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>AR City</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

peac_dev/force-app/main/default/objects/Contract__c/fields/AR_Name__c.field-meta.xml
<CustomField>
    <fullName>AR_Name__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>AR Name</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

peac_dev/force-app/main/default/objects/Contract__c/fields/AR_State__c.field-meta.xml
<CustomField>
    <fullName>AR_State__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>AR State</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

peac_dev/force-app/main/default/objects/Contract__c/fields/AR_Zip_Code__c.field-meta.xml
<CustomField>
    <fullName>AR_Zip_Code__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>AR Zip Code</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

peac_dev/force-app/main/default/objects/Contract__c/fields/Attention__c.field-meta.xml
<CustomField>
    <fullName>Attention__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Attention</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

peac_dev/force-app/main/default/objects/Contract__c/fields/City__c.field-meta.xml
<CustomField>
    <fullName>City__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>City</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

peac_dev/force-app/main/default/objects/Contract__c/fields/Infolease_Environment__c.field-meta.xml
<CustomField>
    <fullName>Infolease_Environment__c</fullName>
    <label>Infolease Environment</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>9</fullName>
            </value>
            <value>
                <fullName>10</fullName>
            </value>
            <value>
                <fullName>C</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

peac_dev/force-app/main/default/objects/Contract__c/fields/Invoice_Code__c.field-meta.xml
<CustomField>
    <fullName>Invoice_Code__c</fullName>
    <label>Invoice Code</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>A</fullName>
                <label>A - Inv By Customer</label>
            </value>
            <value>
                <fullName>S</fullName>
                <label>S - Inv Suppressed</label>
            </value>
            <value>
                <fullName>C</fullName>
                <label>C - Inv By Contract</label>
            </value>
            <value>
                <fullName>B</fullName>
                <label>B - Contract Separated</label>
            </value>
            <value>
                <fullName>R</fullName>
                <label>R - Rentals Separated</label>
            </value>
            <value>
                <fullName>N</fullName>
                <label>N - No More Invoicing</label>
            </value>
            <value>
                <fullName>M</fullName>
                <label>M - Manual Invoicing</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

peac_dev/force-app/main/default/objects/Contract__c/fields/PO_Number__c.field-meta.xml
<CustomField>
    <fullName>PO_Number__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>PO#</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

peac_dev/force-app/main/default/objects/Contract__c/fields/Quote_Buyout__c.field-meta.xml
<CustomField>
    <fullName>Quote_Buyout__c</fullName>
    <label>Quote Buyout</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>01</fullName>
                <label>01 - Yes, limit 1</label>
            </value>
            <value>
                <fullName>02</fullName>
                <label>02 - Yes, unlimited</label>
            </value>
            <value>
                <fullName>03</fullName>
                <label>03 - No B/O</label>
            </value>
            <value>
                <fullName>04</fullName>
                <label>04 - Assigned Resid, Notify Vendor to Quote B/O, Send Rep Alert</label>
            </value>
            <value>
                <fullName>05</fullName>
                <label>05 - Yes, notify vendor</label>
            </value>
            <value>
                <fullName>06</fullName>
                <label>06 - No, vendor to quote</label>
            </value>
            <value>
                <fullName>07</fullName>
                <label>07 - 1st Right of Refusal, Notify Vendor of Buyout Before Lessee</label>
            </value>
            <value>
                <fullName>08</fullName>
                <label>08 - Unlocked Assigned Resid - CS</label>
            </value>
            <value>
                <fullName>09</fullName>
                <label>09 - Unlocked Assigned Resid - Contract in Default</label>
            </value>
            <value>
                <fullName>11</fullName>
                <label>11 - Special Net Investment Addendum - see file</label>
            </value>
            <value>
                <fullName>12</fullName>
                <label>12 - Add-on contract, Must quote b/o together w/ main asset</label>
            </value>
            <value>
                <fullName>13</fullName>
                <label>13 - Software addendum, special buyout letter, no ownership</label>
            </value>
            <value>
                <fullName>14</fullName>
                <label>14 - Do not quote to lessee for 7 Days, notify vendor first</label>
            </value>
            <value>
                <fullName>15</fullName>
                <label>15 - Service Fees</label>
            </value>
            <value>
                <fullName>18</fullName>
                <label>18 - EOT</label>
            </value>
            <value>
                <fullName>19</fullName>
                <label>19 - Adtran if equipment return or Repo</label>
            </value>
            <value>
                <fullName>20</fullName>
                <label>20 - Assigned Residual No Renewal</label>
            </value>
            <value>
                <fullName>22</fullName>
                <label>22 - NO BUYOUT - RENTAL NO PURCHASE OPTION</label>
            </value>
            <value>
                <fullName>23</fullName>
                <label>23 - Call Syndication Partner for Buyout Quotes</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

peac_dev/force-app/main/default/objects/Contract__c/fields/Reprint_Invoice__c.field-meta.xml
<CustomField>
    <fullName>Reprint_Invoice__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Reprint Invoice</label>
    <type>Checkbox</type>
</CustomField>

peac_dev/force-app/main/default/objects/Contract__c/fields/State__c.field-meta.xml
<CustomField>
    <fullName>State__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>State</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

peac_dev/force-app/main/default/objects/Contract__c/fields/Tax_ID__c.field-meta.xml
<CustomField>
    <fullName>Tax_ID__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Tax ID</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

peac_dev/force-app/main/default/objects/Contract__c/fields/User_Code__c.field-meta.xml
<CustomField>
    <fullName>User_Code__c</fullName>
    <label>User Code</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>01</fullName>
                <label>01 - Early Buyout More Than 2 Payments Left in Term</label>
            </value>
            <value>
                <fullName>02</fullName>
                <label>02 - Early Buyout 2 or Less Payments Left in Term</label>
            </value>
            <value>
                <fullName>03</fullName>
                <label>03 - 90 Day Same as Cash Buyout</label>
            </value>
            <value>
                <fullName>04</fullName>
                <label>04 - Trade Up</label>
            </value>
            <value>
                <fullName>05</fullName>
                <label>05 - Insurance Payoff</label>
            </value>
            <value>
                <fullName>06</fullName>
                <label>06 - Settlement With Gain</label>
            </value>
            <value>
                <fullName>07</fullName>
                <label>07 - Residual Refinance</label>
            </value>
            <value>
                <fullName>11</fullName>
                <label>11 - Paid Lease Returned Equipment</label>
            </value>
            <value>
                <fullName>12</fullName>
                <label>12 - Paid Lease Previously in Renewal</label>
            </value>
            <value>
                <fullName>13</fullName>
                <label>13 - Paid Lease Previously in Renewal With Equipment Return</label>
            </value>
            <value>
                <fullName>14</fullName>
                <label>14 - End of Term Trade Up</label>
            </value>
            <value>
                <fullName>15</fullName>
                <label>15 - Trade Up To Return</label>
            </value>
            <value>
                <fullName>16</fullName>
                <label>16 - Residual Charge Off Legal Transfer</label>
            </value>
            <value>
                <fullName>19</fullName>
                <label>19 - Fee Settlement Disposition</label>
            </value>
            <value>
                <fullName>20</fullName>
                <label>20 - Contractual Default Company OOB</label>
            </value>
            <value>
                <fullName>21</fullName>
                <label>21 - Contractual Default Cash Flow Problem</label>
            </value>
            <value>
                <fullName>22</fullName>
                <label>22 - Contractual Default Company Sold</label>
            </value>
            <value>
                <fullName>23</fullName>
                <label>23 - Contractual Default Hell or High Water</label>
            </value>
            <value>
                <fullName>24</fullName>
                <label>24 - Type 1 Fraud</label>
            </value>
            <value>
                <fullName>25</fullName>
                <label>25 - Bankruptcy Chapter 7</label>
            </value>
            <value>
                <fullName>26</fullName>
                <label>26 - Bankruptcy Chapter 11</label>
            </value>
            <value>
                <fullName>27</fullName>
                <label>27 - Bankruptcy Chapter 13</label>
            </value>
            <value>
                <fullName>28</fullName>
                <label>28 - Settlement/Hell or High Water</label>
            </value>
            <value>
                <fullName>29</fullName>
                <label>29 - Apparent Authority</label>
            </value>
            <value>
                <fullName>30</fullName>
                <label>30 - Vendor Buy Back With Loss</label>
            </value>
            <value>
                <fullName>31</fullName>
                <label>31 - OOB No PG</label>
            </value>
            <value>
                <fullName>32</fullName>
                <label>32 - Receiverships</label>
            </value>
            <value>
                <fullName>33</fullName>
                <label>33 - Deceased</label>
            </value>
            <value>
                <fullName>34</fullName>
                <label>34 - Contractual Default Buyer&apos;s Remorse</label>
            </value>
            <value>
                <fullName>35</fullName>
                <label>35 - Settlement With Loss</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

peac_dev/force-app/main/default/objects/Contract__c/fields/Zip_Code__c.field-meta.xml
<CustomField>
    <fullName>Zip_Code__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Zip Code</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

peac_dev/force-app/main/default/classes/SL_InfoleaseContractQueueable.cls
public class SL_InfoleaseContractQueueable implements Database.AllowsCallouts, Database.Batchable<SObject>, Database.Stateful{
	private Map<Id, Set<String>> fieldsByContractId = new Map<Id, Set<String>>();
	private Set<Id> contractIds = new Set<ID>();
	String stepName = '';
	Boolean needToPublishError = false;
	String lastErrorId = '';
	String lastErrorMessage = '';
	final String mainQuery = 'SELECT Id, Infolease_Environment__c, Address_1__c, Address_2__c, Address_3__c, City__c, State__c, Zip_Code__c, '
			+ 'AR_Name__c, AR_Address_1__c, AR_Address_2__c, AR_Address_3__c, AR_City__c, AR_State__c, AR_Zip_Code__c, Attention__c, '
			+ 'Tax_ID__c, Invoice_Code__c, User_Code__c, Reprint_Invoice__c, PO_Number__c, Name, Quote_Buyout__c, Invoice_Format__c, '
			+ 'Insurance_Status__c FROM Contract__c WHERE Id IN:contractIds';
   
	public SL_InfoleaseContractQueueable(List<Contract__c> contractList,Map<Contract__c,Set<String>> contractMap,Boolean listMap){
		if(listMAp == true){
			for(Contract__c cont:contractList){
				contractIds.add(cont.Id);
			}
		}else{
			for(Contract__c con:contractMap.keySet()){
				fieldsByContractId.put(con.Id, contractMap.get(con));
				contractIds.add(con.Id);
			}
		}
		
	}
	public SL_InfoleaseContractQueueable(String stepName){
		this.stepName = stepName;
	}

	public Database.QueryLocator start(Database.BatchableContext bc){
		String query = mainQuery;
		switch on stepName {
			when 'processPending' {
				query = 'SELECT Id, Record_Id__c, Fields_To_Update__c, Processed__c FROM IL_Update__c WHERE Processed__c = false';
			}
		}
		return Database.getQueryLocator(query);
	}
   
	public void execute(Database.BatchableContext bc, List<SObject> batchOfRecords){
		List<Contract__c> batchContracts = new List<Contract__c>();
		List<IL_Update__c> processedUpdates = new List<IL_Update__c>();
		switch on stepName {
			when 'processPending' {
				contractIds.clear();
				for(SObject obj:batchOfRecords){
					IL_Update__c pendingRecord = (IL_Update__c)obj;
					Id recordId = Id.valueOf(pendingRecord.Record_Id__c);
					if(recordId.getSObjectType().getDescribe().getName() == 'Contract__c'){
						contractIds.add(recordId);
						if(String.isNotEmpty(pendingRecord.Fields_To_Update__c)){
							fieldsByContractId.put(recordId, new Set<String>(pendingRecord.Fields_To_Update__c.split(',')));
						}
						pendingRecord.Processed__c = true;
						processedUpdates.add(pendingRecord);
					}
				}
				batchContracts = (List<Contract__c>)Database.query(mainQuery);
			}
			when else{
				batchContracts = (List<Contract__c>)batchOfRecords;
			}
		}
		String lastSuccessId = '';
		lastErrorId = '';
		for(Contract__c currentCon:batchContracts){
			SL_InfoleaseContractHelper contractAPI = new SL_InfoleaseContractHelper(currentCon.Id);
			SL_InfoleaseContractService service = new SL_InfoleaseContractService();
			Set<String> changeSet= new Set<String>();
			if(fieldsByContractId.size()>0){
				changeSet=fieldsByContractId.get(currentCon.Id);
			}	
			service.recordId = contractAPI.recordId;
			if (contractAPI.validate()) {
				try{
					String errorMessage = String.join(contractAPI.getErrorMessages(), ',');
					if(String.isNotEmpty(errorMessage)){
						storeError(errorMessage, currentCon, true);
					}else{
						String requestString = '';
						SL_InfoleaseIntegrationResponseWrapper response = null;
						if(changeSet.size() == 0){
							SL_InfoleaseContractRequestWrapper request = contractAPI.createRequest();
							response = service.updateContract(request, null, currentCon.Infolease_Environment__c);
							requestString = JSON.serialize(request, true);
						}else{
							requestString = contractAPI.mapSpecificFields(currentCon.Id, changeSet);
							response = service.updateContract(null, requestString,currentCon.Infolease_Environment__c);
						}
						errorMessage = processResponse(requestString, response, currentCon.Id);
						if(errorMessage == ''){
							currentCon.Integration_Status__c = 'Synced';
							lastSuccessId = currentCon.Id;
						}else{
							storeError(errorMessage, currentCon, false);
						}
					}
				} catch (Exception e) {
					storeError(e.getMessage(), currentCon, true);
				}
			}else{
				String errorMessage = String.join(contractAPI.getErrorMessages(), ',');
				storeError(errorMessage, currentCon, true);
				return;
			}
		}
		if(needToPublishError){
			EventBus.publish( new SL_BW_Integration_Status__e(Message__c = SL_InfoleaseConstants.errorOccurred+lastErrorMessage+'\n'+SL_InfoleaseConstants.contactAdmin,
				Status__c = 'Error', Record_Id__c = lastErrorId));
		}else{
			EventBus.publish( new SL_BW_Integration_Status__e(Message__c = 'Record Synced Successfully.', 
				Status__c = 'Success', Record_Id__c = lastSuccessId));
		}
		update batchContracts;
		SL_InfoleaseLoggingUtils.flush();
		update processedUpdates;
	}
   
	void storeError(String errorMessage, Contract__c theContract, Boolean needsToLogError){
		Id contractId = theContract.Id;
		theContract.Integration_Status__c = 'Error';
		needToPublishError = true;
		lastErrorId = contractId;
		lastErrorMessage = errorMessage;
		if(needsToLogError){
			SL_InfoleaseLoggingUtils.addLog(SL_InfoleaseConstants.contractUpdateJob , contractId, '', '', errorMessage, true);
		}
	}

	String processResponse(String editrequestJSON, SL_InfoleaseIntegrationResponseWrapper respBean, String contractId){
		String message = '';
		if(respBean != null){
			String responseJSON = JSON.serialize(respBean);
			if (respBean.response.Response.errors != null && !respBean.response.Response.errors.isEmpty ()) {
				
				for (String error : respBean.response.Response.errors) {
					System.debug('error: '+error);
					message = message + error +', ';
				}
				if (String.isNotBlank(message) && message.contains(',')) message = message.removeEnd (',');
				SL_InfoleaseLoggingUtils.addLog(SL_InfoleaseConstants.contractUpdateJob , contractId, editrequestJSON, responseJSON, message, true);
			}else{
				SL_InfoleaseLoggingUtils.addLog(SL_InfoleaseConstants.contractUpdateJob , contractId, editrequestJSON, responseJSON, '', false);
			}
		}
		return message;
	}
   
   public void finish(Database.BatchableContext bc){
		Id thisBatchId = bc.getJobId();
		Integer enqueuedBatchJobs = [SELECT COUNT() FROM AsyncApexJob 
            WHERE JobType='BatchApex' AND ApexClass.Name = 'SL_InfoleaseContractQueueable' AND Status IN ('Processing','Preparing','Queued', 'Holding')
			AND Id != :thisBatchId];
		if(enqueuedBatchJobs == 0){
			Integer pendingUpdates = [SELECT COUNT() FROM IL_Update__c WHERE Processed__c = false];
			if(pendingUpdates > 0){
				Database.executeBatch(new SL_InfoleaseContractQueueable('processPending'), Integer.valueOf(Label.SL_MaxCalloutsToIL));
			}
			
		}
   }
}