peac_dev/force-app/main/default/objects/Contract__c/Contract__c.object-meta.xml
<CustomObject>
    <description>Custom Object created so we can use Queue functionality</description>
    <label>Contract</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Contract Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Contracts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

peac_dev/force-app/main/default/objects/Contract__c/fields/Customer__c.field-meta.xml
<CustomField>
    <fullName>Customer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Customer account</description>
    <label>Customer</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Customer_Contracts</relationshipName>
    <type>Lookup</type>
</CustomField>

peac_dev/force-app/main/default/objects/Contract__c/fields/Insurance__c.field-meta.xml
<CustomField>
    <fullName>Insurance__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Insurance</label>
    <referenceTo>Insurance__c</referenceTo>
    <relationshipName>Custom_Contracts</relationshipName>
    <type>Lookup</type>
</CustomField>

peac_dev/force-app/main/default/objects/Contract__c/fields/Insurance_Status__c.field-meta.xml
<CustomField>
    <fullName>Insurance_Status__c</fullName>
    <label>Insurance Status</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Infolease_Environment__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>01</fullName>
                <label>Pending</label>
            </value>
            <value>
                <fullName>02</fullName>
                <label>Outside coverage</label>
            </value>
            <value>
                <fullName>03</fullName>
                <label>Marlin program</label>
            </value>
            <value>
                <fullName>04</fullName>
                <label>Reinstated</label>
            </value>
            <value>
                <fullName>05</fullName>
                <label>Voided-No Coverage</label>
            </value>
            <value>
                <fullName>06</fullName>
                <label>Non-Solicitable</label>
            </value>
            <value>
                <fullName>07</fullName>
                <label>Cancel Nonpay</label>
            </value>
            <value>
                <fullName>08</fullName>
                <label>Disposed</label>
            </value>
            <value>
                <fullName>09</fullName>
                <label>Self Insured</label>
            </value>
            <value>
                <fullName>10</fullName>
                <label>NOT REQUIRED</label>
            </value>
            <value>
                <fullName>11</fullName>
                <label>Sale</label>
            </value>
            <value>
                <fullName>16</fullName>
                <label>Ins through Unifi</label>
            </value>
            <value>
                <fullName>21</fullName>
                <label>Pending Auto</label>
            </value>
            <value>
                <fullName>22</fullName>
                <label>Outside Ins Auto</label>
            </value>
            <value>
                <fullName>23</fullName>
                <label>In-House TV</label>
            </value>
            <value>
                <fullName>24</fullName>
                <label>Reinstated TV</label>
            </value>
            <value>
                <fullName>25</fullName>
                <label>CANCELED NON PAYMENT</label>
            </value>
            <value>
                <fullName>26</fullName>
                <label>TV- Not Required</label>
            </value>
            <value>
                <fullName>27</fullName>
                <label>InsCanc-Delinq</label>
            </value>
            <value>
                <fullName>28</fullName>
                <label>TV-Disposed</label>
            </value>
            <value>
                <fullName>83</fullName>
                <label>Ext-2 Year</label>
            </value>
            <value>
                <fullName>91</fullName>
                <label>Sol Not Owned</label>
            </value>
            <value>
                <fullName>93</fullName>
                <label>Ext-Year 1</label>
            </value>
            <value>
                <fullName>94</fullName>
                <label>Does not want</label>
            </value>
            <value>
                <fullName>95</fullName>
                <label>Canceled-no response</label>
            </value>
            <value>
                <fullName>97</fullName>
                <label>Cancel Pro Rated</label>
            </value>
            <value>
                <fullName>98</fullName>
                <label>Cancel Non Renewal</label>
            </value>
            <value>
                <fullName>99</fullName>
                <label>Can-NoRsp-Y2</label>
            </value>
            <value>
                <fullName>1A</fullName>
                <label>Pending - New</label>
            </value>
            <value>
                <fullName>3A</fullName>
                <label>Request Reissue</label>
            </value>
            <value>
                <fullName>20A</fullName>
                <label>Marlin Program (10)</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

peac_dev/force-app/main/default/objects/Contract__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Disposed</fullName>
            </value>
            <value>
                <fullName>Disposed - Charged Off</fullName>
            </value>
            <value>
                <fullName>Renewal</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

peac_dev/force-app/main/default/objects/Contract_Asset__c/Contract_Asset__c.object-meta.xml
<CustomObject>
    <label>Contract Asset</label>
    <nameField>
        <displayFormat>CA-{0000}</displayFormat>
        <label>Contract Asset Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contract Assets</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

peac_dev/force-app/main/default/objects/Contract_Asset__c/fields/Contract__c.field-meta.xml
<CustomField>
    <fullName>Contract__c</fullName>
    <label>Contract</label>
    <referenceTo>Contract__c</referenceTo>
    <relationshipLabel>Contract Assets</relationshipLabel>
    <relationshipName>Contract_Assets</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

peac_dev/force-app/main/default/objects/Contract_Asset__c/fields/Customer__c.field-meta.xml
<CustomField>
    <fullName>Customer__c</fullName>
    <formula>Contract__r.Customer_name__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Customer</label>
    <type>Text</type>
</CustomField>

peac_dev/force-app/main/default/objects/Contract_Asset__c/fields/Insurance__c.field-meta.xml
<CustomField>
    <fullName>Insurance__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Insurance</label>
    <referenceTo>Insurance__c</referenceTo>
    <relationshipLabel>Contract Assets</relationshipLabel>
    <relationshipName>Contract_Assets</relationshipName>
    <type>Lookup</type>
</CustomField>

peac_dev/force-app/main/default/objects/Contract_Asset__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>DP-905</description>
    <formula>IF(ISBLANK(Asset_Disposed_Date__c), &quot;Active&quot;, &quot;Disposed&quot;)</formula>
    <label>Status</label>
    <type>Text</type>
</CustomField>

peac_dev/force-app/main/default/objects/Insurance__c/Insurance__c.object-meta.xml
<CustomObject>
    <label>Insurance</label>
    <nameField>
        <displayFormat>INS-{0000}</displayFormat>
        <label>Insurance Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Insurance</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

peac_dev/force-app/main/default/objects/Insurance__c/fields/Account_Level__c.field-meta.xml
<CustomField>
    <fullName>Account_Level__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Apply at Account Level?</label>
    <type>Checkbox</type>
</CustomField>

peac_dev/force-app/main/default/objects/Insurance__c/fields/Cancel_Date__c.field-meta.xml
<CustomField>
    <fullName>Cancel_Date__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Cancel Date</label>
    <type>Date</type>
</CustomField>

peac_dev/force-app/main/default/objects/Insurance__c/fields/Carrier__c.field-meta.xml
<CustomField>
    <fullName>Carrier__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Carrier Name</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

peac_dev/force-app/main/default/objects/Insurance__c/fields/Customer__c.field-meta.xml
<CustomField>
    <fullName>Customer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Account set as the customer</description>
    <inlineHelpText>select the Customer who owns the Insurance</inlineHelpText>
    <label>Customer</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Insurance</relationshipLabel>
    <relationshipName>Insurance</relationshipName>
    <type>Lookup</type>
</CustomField>

peac_dev/force-app/main/default/objects/Insurance__c/fields/Expiration_Date__c.field-meta.xml
<CustomField>
    <fullName>Expiration_Date__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Expiration Date</label>
    <type>Date</type>
</CustomField>

peac_dev/force-app/main/default/objects/Insurance__c/fields/Insurance_Id__c.field-meta.xml
<CustomField>
    <fullName>Insurance_Id__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <externalId>true</externalId>
    <label>Insurance Id</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

peac_dev/force-app/main/default/objects/Insurance__c/fields/Property_Damage_Coverage__c.field-meta.xml
<CustomField>
    <fullName>Property_Damage_Coverage__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Property Damage Coverage</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

peac_dev/force-app/main/default/objects/Insurance__c/fields/Save_at_Account_Level__c.field-meta.xml
<CustomField>
    <fullName>Save_at_Account_Level__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Save at Account Level</label>
    <type>Checkbox</type>
</CustomField>

peac_dev/force-app/main/default/objects/Insurance__c/fields/Titled_Vehicles__c.field-meta.xml
<CustomField>
    <fullName>Titled_Vehicles__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Titled Vehicles</label>
    <type>Checkbox</type>
</CustomField>

peac_dev/force-app/main/default/classes/SL_InsuranceTriggerHandlerTest.cls
@isTest
public class SL_InsuranceTriggerHandlerTest {
    @isTest
    static void activeInsurance() {
        SL_SCTestData.createAccountAndContracts(1,5);
        Account acc = SL_SCTestData.testAccounts[0];
        List<Contract__c> contracts = SL_SCTestData.testContracts;
        Date aMonthFromToday = Date.valueOf(Date.today() + 30);
        Test.startTest();
        SL_SCTestData.createInsurancesAndContractAssets(5, 1);
        List<Insurance__c> insurances = SL_SCTestData.testInsurances;
        contracts[2].Insurance_Status__c = '20A';
        contracts[2].Insurance__c = insurances[2].Id;
        contracts[3].Insurance_Status__c = '20A';
        contracts[3].Insurance__c = insurances[3].Id;
        contracts[4].Insurance_Status__c = '20A';
        contracts[4].Insurance__c = insurances[4].Id;
        update contracts;
        insurances[0].Account_Level__c = true;
        insurances[0].Expiration_Date__c = aMonthFromToday;
        insurances[0].Customer__c = acc.Id;
        insurances[2].Expiration_Date__c = aMonthFromToday;
        insurances[3].Expiration_Date__c = aMonthFromToday;
        insurances[3].Cancel_Date__c = aMonthFromToday;
        insurances[4].Cancel_Date__c = aMonthFromToday;
        List<Database.SaveResult> insuranceResults = Database.update(insurances, false);
        Test.stopTest();
        Account accAfter = [SELECT Id, Active_Insurance__c FROM Account LIMIT 1];
        if(insuranceResults[2].getErrors().size()>0){
            System.Assert.areEqual('This insurance policy must be updated in Infolease 10', insuranceResults[2].getErrors()[0].getMessage(), 'only Cancel Date is editable for IL 10 OR C');
            System.Assert.areEqual('This insurance policy must be updated in Infolease 10', insuranceResults[3].getErrors()[0].getMessage(), 'only Cancel Date is editable for IL 10 OR C');
        }
        System.Assert.areEqual(accAfter.Active_Insurance__c, insurances[0].Id);
        List<Insurance__c> insurancesAfter = [SELECT Id, Cancel_Date__c, Expiration_Date__c FROM Insurance__c];
        System.Assert.areEqual(aMonthFromToday, insurancesAfter[4].Cancel_Date__c, 'Cancel Date must be editable for IL 10 OR C');
    }
    @isTest
    static void syncInsurances() {
        SL_SCTestData.createAccountAndContracts(1,3);
        Account acc = SL_SCTestData.testAccounts[0];
        SL_SCTestData.createInsurancesAndContractAssets(3, 1);
        List<Contract__c> contracts = new List<Contract__c>();
        List<Contract_Asset__c> assets = [SELECT Id, Insurance__c, Contract__c FROM Contract_Asset__c];
        for(Contract_Asset__c asset : assets){
            Contract__c c = new Contract__c(Id = asset.Contract__c,
                Customer__c = acc.Id, Insurance__c = asset.Insurance__c);
            contracts.add(c);
        }
        update contracts;
        List<Insurance__c> insurances = [SELECT Id, Account_Level__c, Expiration_Date__c FROM Insurance__c];
        insurances[1].Insurance_Id__c = String.valueOf(insurances[1].Id);
        insurances[2].Insurance_Id__c = String.valueOf(insurances[2].Id);
        update insurances;
        Test.startTest();
        insurances[0].Customer__c = acc.Id;
        insurances[0].Insurance_Id__c = String.valueOf(insurances[0].Id);
        insurances[0].Carrier__c = 'Carrier Name to test';
        insurances[0].Property_Damage_Coverage__c = 2000;
        insurances[0].Save_at_Account_Level__c = true;
        update insurances;
        Test.stopTest();
        List<Insurance__c> insurancesAfter = [SELECT Id, Carrier__c, Property_Damage_Coverage__c, Insurance_Id__c FROM Insurance__c WHERE Titled_Vehicles__c = FALSE];
        System.assertEquals(2000, insurancesAfter[0].Property_Damage_Coverage__c);
        System.assertEquals(2000, insurancesAfter[1].Property_Damage_Coverage__c);
        System.assertEquals(2000, insurancesAfter[2].Property_Damage_Coverage__c);
        System.assertEquals('Carrier Name to test', insurancesAfter[0].Carrier__c);
        System.assertEquals('Carrier Name to test', insurancesAfter[1].Carrier__c);
        System.assertEquals('Carrier Name to test', insurancesAfter[2].Carrier__c);
        System.assert(insurancesAfter[0].Id == insurancesAfter[0].Insurance_Id__c);
        System.assert(insurancesAfter[1].Id == insurancesAfter[1].Insurance_Id__c);
        System.assert(insurancesAfter[2].Id == insurancesAfter[2].Insurance_Id__c);
    }
    @isTest
    static void syncInsurances2() {
        SL_SCTestData.createAccountAndContracts(1,3);
        Account acc = SL_SCTestData.testAccounts[0];
        SL_SCTestData.createInsurancesAndContractAssets(3, 1);
        List<Contract__c> contracts = new List<Contract__c>();
        List<Contract_Asset__c> assets = [SELECT Id, Insurance__c, Contract__c FROM Contract_Asset__c];
        for(Contract_Asset__c asset : assets){
            Contract__c c = new Contract__c(Id = asset.Contract__c,
                Customer__c = acc.Id, Insurance__c = asset.Insurance__c);
            contracts.add(c);
        }
        update contracts;
        List<Insurance__c> insurances = [SELECT Id, Account_Level__c, Expiration_Date__c FROM Insurance__c];
        insurances[1].Insurance_Id__c = String.valueOf(insurances[1].Id);
        insurances[2].Insurance_Id__c = String.valueOf(insurances[2].Id);
        update insurances;
        Test.startTest();
        Integer childContracts = [select count() from Contract__c WHERE Customer__c = : acc.Id AND Insurance__c = :insurances[0].Id AND Insurance__r.Titled_Vehicles__c = FALSE AND (NOT Status__c LIKE 'Disposed%')];
        System.assert(childContracts > 0);
        insurances[0].Customer__c = null;
        insurances[0].Insurance_Id__c = String.valueOf(insurances[0].Id);
        insurances[0].Carrier__c = 'Carrier Name to test';
        insurances[0].Property_Damage_Coverage__c = 2000;
        insurances[0].Save_at_Account_Level__c = true;
        update insurances;
        Test.stopTest();
        List<Insurance__c> insurancesAfter = [SELECT Id, Carrier__c, Property_Damage_Coverage__c, Insurance_Id__c FROM Insurance__c WHERE Titled_Vehicles__c = FALSE];
        System.assertEquals(2000, insurancesAfter[0].Property_Damage_Coverage__c);
        System.assertEquals(2000, insurancesAfter[1].Property_Damage_Coverage__c);
        System.assertEquals(2000, insurancesAfter[2].Property_Damage_Coverage__c);
        System.assertEquals('Carrier Name to test', insurancesAfter[0].Carrier__c);
        System.assertEquals('Carrier Name to test', insurancesAfter[1].Carrier__c);
        System.assertEquals('Carrier Name to test', insurancesAfter[2].Carrier__c);
        System.assert(insurancesAfter[0].Id == insurancesAfter[0].Insurance_Id__c);
        System.assert(insurancesAfter[1].Id == insurancesAfter[1].Insurance_Id__c);
        System.assert(insurancesAfter[2].Id == insurancesAfter[2].Insurance_Id__c);
    }

    @isTest
    static void dataAdminExcemption() {
        SL_SCTestData.createAccountAndContracts(1,1);
        Account acc = SL_SCTestData.testAccounts[0];
        List<Contract__c> contracts = SL_SCTestData.testContracts;
        Date aMonthFromToday = Date.valueOf(Date.today() + 30);
        List<User> theDataAdmin = [SELECT Id, Name FROM User WHERE Name = 'User Informatica'];
        SL_SCTestData.createInsurancesAndContractAssets(1, 1);
        List<Insurance__c> insurances = SL_SCTestData.testInsurances;
        contracts[0].Insurance_Status__c = '20A';
        contracts[0].Insurance__c = insurances[0].Id;
        update contracts;
        Test.startTest();
        if(theDataAdmin.size() > 0){
            System.runAs(theDataAdmin[0]){
                insurances[0].Expiration_Date__c = aMonthFromToday;
                List<Database.SaveResult> insuranceResults = Database.update(insurances, false);
            }
        }
        Test.stopTest();
        List<Insurance__c> insurancesAfter = [SELECT Id, Cancel_Date__c, Expiration_Date__c FROM Insurance__c];
        System.Assert.areEqual(aMonthFromToday, insurancesAfter[0].Expiration_Date__c, 'fields must be editable for IL 10 OR C using DataAdmin profile');
    }
}