peac_dev/force-app/main/default/objects/Contract__c/Contract__c.object-meta.xml
<CustomObject>
    <description>Custom Object created so we can use Queue functionality</description>
    <label>Contract</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Contract Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Contracts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

peac_dev/force-app/main/default/objects/Contract__c/fields/Address_1__c.field-meta.xml
<CustomField>
    <fullName>Address_1__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Address 1</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

peac_dev/force-app/main/default/objects/Contract__c/fields/Address_2__c.field-meta.xml
<CustomField>
    <fullName>Address_2__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Address 2</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

peac_dev/force-app/main/default/objects/Contract__c/fields/Address_3__c.field-meta.xml
<CustomField>
    <fullName>Address_3__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Address 3</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

peac_dev/force-app/main/default/objects/Contract__c/fields/AR_Address_1__c.field-meta.xml
<CustomField>
    <fullName>AR_Address_1__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>AR Address 1</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

peac_dev/force-app/main/default/objects/Contract__c/fields/AR_Address_2__c.field-meta.xml
<CustomField>
    <fullName>AR_Address_2__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>AR Address 2</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

peac_dev/force-app/main/default/objects/Contract__c/fields/AR_Address_3__c.field-meta.xml
<CustomField>
    <fullName>AR_Address_3__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>AR Address 3</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

peac_dev/force-app/main/default/objects/Contract__c/fields/AR_City__c.field-meta.xml
<CustomField>
    <fullName>AR_City__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>AR City</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

peac_dev/force-app/main/default/objects/Contract__c/fields/AR_Name__c.field-meta.xml
<CustomField>
    <fullName>AR_Name__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>AR Name</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

peac_dev/force-app/main/default/objects/Contract__c/fields/AR_State__c.field-meta.xml
<CustomField>
    <fullName>AR_State__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>AR State</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

peac_dev/force-app/main/default/objects/Contract__c/fields/AR_Zip_Code__c.field-meta.xml
<CustomField>
    <fullName>AR_Zip_Code__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>AR Zip Code</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

peac_dev/force-app/main/default/objects/Contract__c/fields/Attention__c.field-meta.xml
<CustomField>
    <fullName>Attention__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Attention</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

peac_dev/force-app/main/default/objects/Contract__c/fields/City__c.field-meta.xml
<CustomField>
    <fullName>City__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>City</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

peac_dev/force-app/main/default/objects/Contract__c/fields/Invoice_Code__c.field-meta.xml
<CustomField>
    <fullName>Invoice_Code__c</fullName>
    <label>Invoice Code</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>A</fullName>
                <label>A - Inv By Customer</label>
            </value>
            <value>
                <fullName>S</fullName>
                <label>S - Inv Suppressed</label>
            </value>
            <value>
                <fullName>C</fullName>
                <label>C - Inv By Contract</label>
            </value>
            <value>
                <fullName>B</fullName>
                <label>B - Contract Separated</label>
            </value>
            <value>
                <fullName>R</fullName>
                <label>R - Rentals Separated</label>
            </value>
            <value>
                <fullName>N</fullName>
                <label>N - No More Invoicing</label>
            </value>
            <value>
                <fullName>M</fullName>
                <label>M - Manual Invoicing</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

peac_dev/force-app/main/default/objects/Contract__c/fields/Invoice_Format__c.field-meta.xml
<CustomField>
    <fullName>Invoice_Format__c</fullName>
    <label>Invoice Format</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>ASSET</fullName>
                <label>Asset Detail</label>
            </value>
            <value>
                <fullName>STAND</fullName>
                <label>Contract Invoicing</label>
            </value>
            <value>
                <fullName>ACH</fullName>
                <label>Non OSG ACH</label>
            </value>
            <value>
                <fullName>ASST2</fullName>
                <label>Asset Summary</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

peac_dev/force-app/main/default/objects/Contract__c/fields/PO_Number__c.field-meta.xml
<CustomField>
    <fullName>PO_Number__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>PO#</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

peac_dev/force-app/main/default/objects/Contract__c/fields/Quote_Buyout__c.field-meta.xml
<CustomField>
    <fullName>Quote_Buyout__c</fullName>
    <label>Quote Buyout</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>01</fullName>
                <label>01 - Yes, limit 1</label>
            </value>
            <value>
                <fullName>02</fullName>
                <label>02 - Yes, unlimited</label>
            </value>
            <value>
                <fullName>03</fullName>
                <label>03 - No B/O</label>
            </value>
            <value>
                <fullName>04</fullName>
                <label>04 - Assigned Resid, Notify Vendor to Quote B/O, Send Rep Alert</label>
            </value>
            <value>
                <fullName>05</fullName>
                <label>05 - Yes, notify vendor</label>
            </value>
            <value>
                <fullName>06</fullName>
                <label>06 - No, vendor to quote</label>
            </value>
            <value>
                <fullName>07</fullName>
                <label>07 - 1st Right of Refusal, Notify Vendor of Buyout Before Lessee</label>
            </value>
            <value>
                <fullName>08</fullName>
                <label>08 - Unlocked Assigned Resid - CS</label>
            </value>
            <value>
                <fullName>09</fullName>
                <label>09 - Unlocked Assigned Resid - Contract in Default</label>
            </value>
            <value>
                <fullName>11</fullName>
                <label>11 - Special Net Investment Addendum - see file</label>
            </value>
            <value>
                <fullName>12</fullName>
                <label>12 - Add-on contract, Must quote b/o together w/ main asset</label>
            </value>
            <value>
                <fullName>13</fullName>
                <label>13 - Software addendum, special buyout letter, no ownership</label>
            </value>
            <value>
                <fullName>14</fullName>
                <label>14 - Do not quote to lessee for 7 Days, notify vendor first</label>
            </value>
            <value>
                <fullName>15</fullName>
                <label>15 - Service Fees</label>
            </value>
            <value>
                <fullName>18</fullName>
                <label>18 - EOT</label>
            </value>
            <value>
                <fullName>19</fullName>
                <label>19 - Adtran if equipment return or Repo</label>
            </value>
            <value>
                <fullName>20</fullName>
                <label>20 - Assigned Residual No Renewal</label>
            </value>
            <value>
                <fullName>22</fullName>
                <label>22 - NO BUYOUT - RENTAL NO PURCHASE OPTION</label>
            </value>
            <value>
                <fullName>23</fullName>
                <label>23 - Call Syndication Partner for Buyout Quotes</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

peac_dev/force-app/main/default/objects/Contract__c/fields/Reprint_Invoice__c.field-meta.xml
<CustomField>
    <fullName>Reprint_Invoice__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Reprint Invoice</label>
    <type>Checkbox</type>
</CustomField>

peac_dev/force-app/main/default/objects/Contract__c/fields/State__c.field-meta.xml
<CustomField>
    <fullName>State__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>State</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

peac_dev/force-app/main/default/objects/Contract__c/fields/Tax_ID__c.field-meta.xml
<CustomField>
    <fullName>Tax_ID__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Tax ID</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

peac_dev/force-app/main/default/objects/Contract__c/fields/User_Code__c.field-meta.xml
<CustomField>
    <fullName>User_Code__c</fullName>
    <label>User Code</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>01</fullName>
                <label>01 - Early Buyout More Than 2 Payments Left in Term</label>
            </value>
            <value>
                <fullName>02</fullName>
                <label>02 - Early Buyout 2 or Less Payments Left in Term</label>
            </value>
            <value>
                <fullName>03</fullName>
                <label>03 - 90 Day Same as Cash Buyout</label>
            </value>
            <value>
                <fullName>04</fullName>
                <label>04 - Trade Up</label>
            </value>
            <value>
                <fullName>05</fullName>
                <label>05 - Insurance Payoff</label>
            </value>
            <value>
                <fullName>06</fullName>
                <label>06 - Settlement With Gain</label>
            </value>
            <value>
                <fullName>07</fullName>
                <label>07 - Residual Refinance</label>
            </value>
            <value>
                <fullName>11</fullName>
                <label>11 - Paid Lease Returned Equipment</label>
            </value>
            <value>
                <fullName>12</fullName>
                <label>12 - Paid Lease Previously in Renewal</label>
            </value>
            <value>
                <fullName>13</fullName>
                <label>13 - Paid Lease Previously in Renewal With Equipment Return</label>
            </value>
            <value>
                <fullName>14</fullName>
                <label>14 - End of Term Trade Up</label>
            </value>
            <value>
                <fullName>15</fullName>
                <label>15 - Trade Up To Return</label>
            </value>
            <value>
                <fullName>16</fullName>
                <label>16 - Residual Charge Off Legal Transfer</label>
            </value>
            <value>
                <fullName>19</fullName>
                <label>19 - Fee Settlement Disposition</label>
            </value>
            <value>
                <fullName>20</fullName>
                <label>20 - Contractual Default Company OOB</label>
            </value>
            <value>
                <fullName>21</fullName>
                <label>21 - Contractual Default Cash Flow Problem</label>
            </value>
            <value>
                <fullName>22</fullName>
                <label>22 - Contractual Default Company Sold</label>
            </value>
            <value>
                <fullName>23</fullName>
                <label>23 - Contractual Default Hell or High Water</label>
            </value>
            <value>
                <fullName>24</fullName>
                <label>24 - Type 1 Fraud</label>
            </value>
            <value>
                <fullName>25</fullName>
                <label>25 - Bankruptcy Chapter 7</label>
            </value>
            <value>
                <fullName>26</fullName>
                <label>26 - Bankruptcy Chapter 11</label>
            </value>
            <value>
                <fullName>27</fullName>
                <label>27 - Bankruptcy Chapter 13</label>
            </value>
            <value>
                <fullName>28</fullName>
                <label>28 - Settlement/Hell or High Water</label>
            </value>
            <value>
                <fullName>29</fullName>
                <label>29 - Apparent Authority</label>
            </value>
            <value>
                <fullName>30</fullName>
                <label>30 - Vendor Buy Back With Loss</label>
            </value>
            <value>
                <fullName>31</fullName>
                <label>31 - OOB No PG</label>
            </value>
            <value>
                <fullName>32</fullName>
                <label>32 - Receiverships</label>
            </value>
            <value>
                <fullName>33</fullName>
                <label>33 - Deceased</label>
            </value>
            <value>
                <fullName>34</fullName>
                <label>34 - Contractual Default Buyer&apos;s Remorse</label>
            </value>
            <value>
                <fullName>35</fullName>
                <label>35 - Settlement With Loss</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

peac_dev/force-app/main/default/objects/Contract__c/fields/Zip_Code__c.field-meta.xml
<CustomField>
    <fullName>Zip_Code__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Zip Code</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

peac_dev/force-app/main/default/objects/Contract__c/recordTypes/Working_Capital_Loan.recordType-meta.xml
<RecordType>
    <fullName>Working_Capital_Loan</fullName>
    <active>true</active>
    <label>Working Capital Loan</label>
</RecordType>

peac_dev/force-app/main/default/classes/SL_InfoleaseContractController.cls
public with sharing class SL_InfoleaseContractController {
    public static void updateContract(Map <Id, Contract__c> oldMap, Map <Id, Contract__c> newMap){

        SL_InfoleaseUtils.isRecursive = true;

        Id workingCapRTId = Schema.SObjectType.Contract__c.getRecordTypeInfosByDeveloperName().get('Working_Capital_Loan').getRecordTypeId();

        List<Contract__c> validContractList = new List<Contract__c>();
        Map<Contract__c, Set<String>> conToFieldsMap = new Map<Contract__c, Set<String>>();
        //to exclude Informatica user updates
        Id informaticaUserId = SL_InfoleaseUtils.getUserId('User Informatica');

        Set<String> fieldSet = new Set<String>{ 'Address_1__c',
                                                'Address_2__c',
                                                'Address_3__c',
                                                'City__c',
                                                'State__c',
                                                'Zip_Code__c',
                                                'AR_Name__c',
                                                'AR_Address_1__c',
                                                'AR_Address_2__c',
                                                'AR_Address_3__c',
                                                'AR_City__c',
                                                'AR_State__c',
                                                'AR_Zip_Code__c',
                                                'Attention__c',
                                                'Tax_ID__c',
                                                'Invoice_Code__c',
                                                'User_Code__c',
                                                'Reprint_Invoice__c',
                                                'PO_Number__c',
                                                'Name',
            									'Quote_Buyout__c',
                                                'Invoice_Format__c',
                                                'Insurance_Status__c'
                                                };

        for(Contract__c newContract : newMap.values()){
            if(newContract.Name == null || newContract.RecordTypeId == workingCapRTId || newContract.LastModifiedById == informaticaUserId){
                continue;
            }else{
                //check if updates were made to these specific fields
                Set<String> changedFieldSet = new Set<String>{'Name'};
                for(String s : fieldSet){
                    if(newContract.get(s) != oldMap.get(newContract.Id).get(s)){
                        changedFieldSet.add(s); //adding fields whose value changed
                    }
                }
                if((changedFieldSet.size() > 1)){
                    conToFieldsMap.put(newContract, changedFieldSet);
                }
                if(newContract.Integration_Status__c == 'Re-sync' && oldMap.get(newContract.Id).Integration_Status__c != 'Re-sync'){
                    validContractList.add(newContract);
                }
            }
            
            
        }
        if(validContractList.size() > 0){
            SL_InfoleaseContractHandler.updateContractInIL(validContractList);
        }
        else if(conToFieldsMap.size() > 0){
            SL_InfoleaseContractHandler.updateSpecificFields(conToFieldsMap);
        }
    }
}