peac_dev/force-app/main/default/objects/Contract__c/Contract__c.object-meta.xml
<CustomObject>
    <description>Custom Object created so we can use Queue functionality</description>
    <label>Contract</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Contract Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Contracts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

peac_dev/force-app/main/default/objects/Contract__c/fields/Dealer_Name__c.field-meta.xml
<CustomField>
    <fullName>Dealer_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Dealer Name</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 OR 2 OR 3</booleanFilter>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Broker Account</value>
        </filterItems>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Dealer Account</value>
        </filterItems>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Franchisor Account</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Contracts (Dealer Name)</relationshipLabel>
    <relationshipName>Custom_Contracts</relationshipName>
    <type>Lookup</type>
</CustomField>

peac_dev/force-app/main/default/objects/Contract_Asset__c/Contract_Asset__c.object-meta.xml
<CustomObject>
    <label>Contract Asset</label>
    <nameField>
        <displayFormat>CA-{0000}</displayFormat>
        <label>Contract Asset Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contract Assets</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

peac_dev/force-app/main/default/objects/Contract_Asset__c/fields/Contract__c.field-meta.xml
<CustomField>
    <fullName>Contract__c</fullName>
    <label>Contract</label>
    <referenceTo>Contract__c</referenceTo>
    <relationshipLabel>Contract Assets</relationshipLabel>
    <relationshipName>Contract_Assets</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

peac_dev/force-app/main/default/objects/Contract_Asset__c/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Location</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Location.Is_Active__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Location</referenceTo>
    <relationshipLabel>Contract Assets</relationshipLabel>
    <relationshipName>Contract_Asset_Location</relationshipName>
    <type>Lookup</type>
</CustomField>

peac_dev/force-app/main/default/objects/Contract_Asset__c/fields/Return_Auth_Create_Date__c.field-meta.xml
<CustomField>
    <fullName>Return_Auth_Create_Date__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Return Auth Create Date</label>
    <type>Date</type>
</CustomField>

peac_dev/force-app/main/default/objects/Contract_Asset__c/fields/Return_Authorization__c.field-meta.xml
<CustomField>
    <fullName>Return_Authorization__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Return Authorization</label>
    <type>Checkbox</type>
</CustomField>

peac_dev/force-app/main/default/objects/Contract_Asset__c/fields/Service_Provider__c.field-meta.xml
<CustomField>
    <fullName>Service_Provider__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Service Provider</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordType.Name</field>
            <operation>equals</operation>
            <value>Service Provider</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Contract Assets (Service Provider)</relationshipLabel>
    <relationshipName>Contract_Assets_Providers</relationshipName>
    <type>Lookup</type>
</CustomField>

peac_dev/force-app/main/default/classes/SL_ContractAssetReportTest.cls
@isTest
public class SL_ContractAssetReportTest {
@TestSetup
    static void setup(){
        String ServProvRecordTypeID = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Service Provider').getRecordTypeId();
        SL_SCTestData.createAccountAndContracts(3, 1);
        List<Account> testAccs = SL_SCTestData.testAccounts;
		List<Contract__c> testCont = SL_SCTestData.testContracts;        
        SL_SCTestData.createInsurancesAndContractAssets(1, 2);
        List<Contract_Asset__c> ContAs = SL_SCTestData.testCAssets;
        Contract__c con = testCont[0];
        Account DealerAcc = testAccs[1];
        DealerAcc.RecordTypeId = SL_SCTestData.DEALER_ACC;
        con.Dealer_Name__c = DealerAcc.Id;
        Contract_Asset__c ca = ContAs[1];
        Account serviceProv = testAccs[2];
        serviceProv.RecordTypeId=ServProvRecordTypeID;
        serviceProv.Return_Authorization_Email__c ='test@testingemail.com';
        ca.Service_Provider__c = serviceProv.Id;
        ca.Return_Auth_Create_Date__c = Date.Today().addDays(-1);
        ca.Return_Authorization__c = true;
        Schema.Location testLoc = new Schema.Location();
        testLoc.Name = 'Test Location 1';
        testLoc.LocationType = 'Building';
        testLoc.Service_Provider__c = serviceProv.Id;
        testLoc.Is_Active__c = true;
        insert testLoc;
        ca.Location__c = testLoc.Id;
        update DealerAcc;
        update con;
        update serviceProv;
        update ca;
    }
    @isTest
    static void testBatch(){
       Test.startTest();
        SL_ContractAssetReport testReports = new SL_ContractAssetReport();
		ID testReportBatch = Database.executeBatch(testReports);
        Test.stopTest();
    }
    
    @isTest
    static void testBatch2(){
       Test.startTest();
        SL_ContractAssetReportUnified testReports = new SL_ContractAssetReportUnified();
		ID testReportBatch = Database.executeBatch(testReports);
        Test.stopTest();
    }
}