peac_dev/force-app/main/default/objects/Contract__c/Contract__c.object-meta.xml
<CustomObject>
    <description>Custom Object created so we can use Queue functionality</description>
    <label>Contract</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Contract Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Contracts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

peac_dev/force-app/main/default/objects/Contract__c/fields/Customer__c.field-meta.xml
<CustomField>
    <fullName>Customer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Customer account</description>
    <label>Customer</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Customer_Contracts</relationshipName>
    <type>Lookup</type>
</CustomField>

peac_dev/force-app/main/default/objects/Contract__c/fields/Infolease_Environment__c.field-meta.xml
<CustomField>
    <fullName>Infolease_Environment__c</fullName>
    <label>Infolease Environment</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>9</fullName>
            </value>
            <value>
                <fullName>10</fullName>
            </value>
            <value>
                <fullName>C</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

peac_dev/force-app/main/default/objects/Contract__c/fields/Insurance__c.field-meta.xml
<CustomField>
    <fullName>Insurance__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Insurance</label>
    <referenceTo>Insurance__c</referenceTo>
    <relationshipName>Custom_Contracts</relationshipName>
    <type>Lookup</type>
</CustomField>

peac_dev/force-app/main/default/objects/Contract__c/fields/Integration_Status__c.field-meta.xml
<CustomField>
    <fullName>Integration_Status__c</fullName>
    <label>Integration Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Not Synced</fullName>
                <default>true</default>
                <label>Not Synced</label>
            </value>
            <value>
                <fullName>Error</fullName>
            </value>
            <value>
                <fullName>Re-sync</fullName>
            </value>
            <value>
                <fullName>Synced</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

peac_dev/force-app/main/default/objects/Contract__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Disposed</fullName>
            </value>
            <value>
                <fullName>Disposed - Charged Off</fullName>
            </value>
            <value>
                <fullName>Renewal</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

peac_dev/force-app/main/default/objects/Insurance__c/Insurance__c.object-meta.xml
<CustomObject>
    <label>Insurance</label>
    <nameField>
        <displayFormat>INS-{0000}</displayFormat>
        <label>Insurance Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Insurance</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

peac_dev/force-app/main/default/objects/Insurance__c/fields/Account_Level__c.field-meta.xml
<CustomField>
    <fullName>Account_Level__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Apply at Account Level?</label>
    <type>Checkbox</type>
</CustomField>

peac_dev/force-app/main/default/objects/Insurance__c/fields/Cancel_Date__c.field-meta.xml
<CustomField>
    <fullName>Cancel_Date__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Cancel Date</label>
    <type>Date</type>
</CustomField>

peac_dev/force-app/main/default/objects/Insurance__c/fields/Carrier__c.field-meta.xml
<CustomField>
    <fullName>Carrier__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Carrier Name</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

peac_dev/force-app/main/default/objects/Insurance__c/fields/Customer__c.field-meta.xml
<CustomField>
    <fullName>Customer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Account set as the customer</description>
    <inlineHelpText>select the Customer who owns the Insurance</inlineHelpText>
    <label>Customer</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Insurance</relationshipLabel>
    <relationshipName>Insurance</relationshipName>
    <type>Lookup</type>
</CustomField>

peac_dev/force-app/main/default/objects/Insurance__c/fields/Effective_Date__c.field-meta.xml
<CustomField>
    <fullName>Effective_Date__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Effective Date</label>
    <type>Date</type>
</CustomField>

peac_dev/force-app/main/default/objects/Insurance__c/fields/Expiration_Date__c.field-meta.xml
<CustomField>
    <fullName>Expiration_Date__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Expiration Date</label>
    <type>Date</type>
</CustomField>

peac_dev/force-app/main/default/objects/Insurance__c/fields/Infolease_Environment__c.field-meta.xml
<CustomField>
    <fullName>Infolease_Environment__c</fullName>
    <label>Infolease Environment</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>9</fullName>
            </value>
            <value>
                <fullName>10</fullName>
            </value>
            <value>
                <fullName>C</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

peac_dev/force-app/main/default/objects/Insurance__c/fields/Insurance_Agent__c.field-meta.xml
<CustomField>
    <fullName>Insurance_Agent__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Select a Contact related to the Carrier</inlineHelpText>
    <label>Insurance Agent</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Insurance (Agent)</relationshipLabel>
    <relationshipName>Agent_Insurance</relationshipName>
    <type>Lookup</type>
</CustomField>

peac_dev/force-app/main/default/objects/Insurance__c/fields/Insurance_Contact__c.field-meta.xml
<CustomField>
    <fullName>Insurance_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Insurance Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Insurance (Contact)</relationshipLabel>
    <relationshipName>Insurance</relationshipName>
    <type>Lookup</type>
</CustomField>

peac_dev/force-app/main/default/objects/Insurance__c/fields/Insurance_Id__c.field-meta.xml
<CustomField>
    <fullName>Insurance_Id__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <externalId>true</externalId>
    <label>Insurance Id</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

peac_dev/force-app/main/default/objects/Insurance__c/fields/Insurance_Type__c.field-meta.xml
<CustomField>
    <fullName>Insurance_Type__c</fullName>
    <label>Insurance Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>01</fullName>
                <label>Property</label>
            </value>
            <value>
                <fullName>02</fullName>
                <label>Business Auto</label>
            </value>
            <value>
                <fullName>09</fullName>
                <label>Extended Coverage</label>
            </value>
            <value>
                <fullName>10</fullName>
                <label>Additional equipment</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

peac_dev/force-app/main/default/objects/Insurance__c/fields/Integration_Status__c.field-meta.xml
<CustomField>
    <fullName>Integration_Status__c</fullName>
    <label>Integration Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Not Synced</fullName>
                <default>true</default>
                <label>Not Synced</label>
            </value>
            <value>
                <fullName>Error</fullName>
            </value>
            <value>
                <fullName>Re-sync</fullName>
            </value>
            <value>
                <fullName>Synced</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

peac_dev/force-app/main/default/objects/Insurance__c/fields/Policy_Status__c.field-meta.xml
<CustomField>
    <fullName>Policy_Status__c</fullName>
    <label>Policy Status</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Infolease_Environment__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>01</fullName>
                <label>Marlin Business Bank</label>
            </value>
            <value>
                <fullName>00</fullName>
                <label>Marlin Leasing Corp</label>
            </value>
            <value>
                <fullName>02</fullName>
                <label>PEAC</label>
            </value>
            <value>
                <fullName>05</fullName>
                <label>Outside Coverage</label>
            </value>
            <value>
                <fullName>06</fullName>
                <label>Marlin Program</label>
            </value>
            <value>
                <fullName>07</fullName>
                <label>Reinstated</label>
            </value>
            <value>
                <fullName>08</fullName>
                <label>Voided - No Coverage</label>
            </value>
            <value>
                <fullName>09</fullName>
                <label>Non-Solicitable</label>
            </value>
            <value>
                <fullName>10</fullName>
                <label>Cancel Non Payment</label>
            </value>
            <value>
                <fullName>11</fullName>
                <label>Disposed</label>
            </value>
            <value>
                <fullName>12</fullName>
                <label>Self Insured</label>
            </value>
            <value>
                <fullName>13</fullName>
                <label>Not Required</label>
            </value>
            <value>
                <fullName>14</fullName>
                <label>Pending Auto</label>
            </value>
            <value>
                <fullName>15</fullName>
                <label>Outside Ins Auto</label>
            </value>
            <value>
                <fullName>16</fullName>
                <label>TV In-House</label>
            </value>
            <value>
                <fullName>17</fullName>
                <label>TV Reinstated</label>
            </value>
            <value>
                <fullName>18</fullName>
                <label>Canceled - Delinquent</label>
            </value>
            <value>
                <fullName>19</fullName>
                <label>TV Disposed</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

peac_dev/force-app/main/default/objects/Insurance__c/fields/Property_Damage_Coverage__c.field-meta.xml
<CustomField>
    <fullName>Property_Damage_Coverage__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Property Damage Coverage</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

peac_dev/force-app/main/default/objects/Insurance__c/fields/Save_at_Account_Level__c.field-meta.xml
<CustomField>
    <fullName>Save_at_Account_Level__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Save at Account Level</label>
    <type>Checkbox</type>
</CustomField>

peac_dev/force-app/main/default/objects/Insurance__c/fields/Title__c.field-meta.xml
<CustomField>
    <fullName>Title__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Yes or No</inlineHelpText>
    <label>Title</label>
    <type>Checkbox</type>
</CustomField>

peac_dev/force-app/main/default/objects/Insurance__c/fields/Titled_Vehicles__c.field-meta.xml
<CustomField>
    <fullName>Titled_Vehicles__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Titled Vehicles</label>
    <type>Checkbox</type>
</CustomField>

peac_dev/force-app/main/default/classes/SL_InsuranceTriggerHandler.cls
public with sharing class SL_InsuranceTriggerHandler extends SL_Trigger.baseHandler {
    private Map<Id, List<String>> fieldsChangedById = new Map<Id, List<String>>();
    private Map<Id, Account> customerAccounts = new Map<Id, Account>();
    private Map<Id, Map<Id, Contract__c>> contracts = new Map<Id, Map<Id, Contract__c>>();
    User currentUser = new User();
    
    public override void beforeUpdate(Map<Id, SObject> oldMap, Map<Id, SObject> newMap){
        checkUpdatedFields(oldMap, newMap);
        for (Id insuranceId :newMap.keySet()){
            getLookupMaps(newMap.get(insuranceId));
        }
        getInfoFromOthers();
        beforeChangesToSelf(newMap, false);
    }

    public override void afterInsert(Map<Id, SObject> newMap){
        for(SObject obj : newMap.values()){
            getLookupMaps(obj);
        }
        getInfoFromOthers();
        afterChangesToOthers(newMap, true);
    }

    public override void afterUpdate(Map<Id, SObject> oldMap, Map<Id, SObject> newMap) {
        //push to Bridgeware to Sync with Infolease
        if(!SL_InfoleaseUtils.isRecursive && !System.isFuture() && !System.isBatch()){
            Map <Id, Insurance__c> oldMapInsurance = new Map <Id, Insurance__c>();
            Map <Id, Insurance__c> newMapInsurance = new Map <Id, Insurance__c>();
            for (SObject theObj : oldMap.values()){
                oldMapInsurance.put(theObj.Id, (Insurance__c)theObj);
                newMapInsurance.put(theObj.Id, ((Insurance__c)newMap.get(theObj.Id)));
            }
            SL_InfoleaseInsuranceController.updateInsurance(oldMapInsurance, newMapInsurance);
        }
        for(SObject obj : newMap.values()){
            getLookupMaps(obj);
        }
        getInfoFromOthers();
        afterChangesToOthers(newMap, false);
    }

    public override void afterDelete(Map<Id, SObject> oldMap){
        // not yet sure if doing anything when insurance gets deleted
    }

    private void checkUpdatedFields(Map<Id, SObject> oldMap, Map<Id, SObject> newMap){
        List<String> fieldsToCheck = new List<String>{'Account_Level__c', 'Cancel_Date__c', 'Carrier__c', 'Customer__c', 'Effective_Date__c',
            'Expiration_Date__c', 'Insurance_Agent__c', 'Insurance_Contact__c', 'Insurance_Id__c', 'Insurance_Type__c',
            'Integration_Status__c', 'Name', 'Policy_Status__c', 'Property_Damage_Coverage__c', 'Save_at_Account_Level__c',
            'Title__c', 'Titled_Vehicles__c'};
        for(Id insuranceId :newMap.keySet()){
            Insurance__c newInsurance = (Insurance__c)newMap.get(insuranceId);
            Insurance__c oldInsurance = (Insurance__c)oldMap.get(insuranceId);
            SL_TriggerUtil.findChangedFields(insuranceId, newInsurance, oldInsurance, fieldsChangedById, fieldsToCheck);

        }
    }

    private void getLookupMaps(SObject obj){
        Insurance__c insurance = (Insurance__c)obj;
        if(insurance.Customer__c != null){
            this.customerAccounts.put(insurance.Customer__c, new Account());
        }
        contracts.put(insurance.Id, new Map<Id, Contract__c>());
    }
    
    private void getInfoFromOthers(){
        this.customerAccounts.putAll([SELECT Id, Active_Insurance__c, Active_Insurance__r.Expiration_Date__c,
            Account_CurrentUser_Profile__c 
            FROM Account WHERE Id IN : this.customerAccounts.keySet()]);
        for(Contract__c contract : [SELECT Id, Name, Customer__c, Insurance__c, Infolease_Environment__c, Insurance_Status__c 
            FROM Contract__c WHERE Insurance__c IN :contracts.keySet()]){
            contracts.get(contract.Insurance__c).put(contract.Id, contract);
        }
        if(Trigger.isBefore /*&& (this.customerAccounts.values().size() == 0 || SL_TriggerUtil.checkForMissingInfo(this.customerAccounts.values()))*/){
            this.currentUser = [SELECT Id, Profile.Name FROM User WHERE Id = :System.UserInfo.getUserId()];
        }
    }

    private void beforeChangesToSelf(Map<Id, SObject> newMap, Boolean isNew){
        for(SObject obj : newMap.values()){
            Insurance__c insurance = (Insurance__c)obj;
            Map<Id, Contract__c> relatedContracts = this.contracts.get(insurance.Id);
            Account customerAccount = this.customerAccounts.get(insurance.Customer__c);
            Contract__c currentCon = null;
            if(relatedContracts != null && relatedContracts.values().size() > 0){
                for(Contract__c relatedContract : relatedContracts.values()){
                    if(insurance.Insurance_Id__c != null && insurance.Insurance_Id__c.contains(relatedContract.Name)){
                        currentCon = relatedContract;
                        break;
                    }
                }
            }
            String currentProfile = customerAccount != null? 
                customerAccount.Account_CurrentUser_Profile__c: this.currentUser.Profile.Name;
            List<String> fieldsChanged = this.fieldsChangedById.get(insurance.Id);
            if(currentProfile != 'DataAdmin' && currentCon != null 
                && (currentCon.Insurance_Status__c=='03'||currentCon.Insurance_Status__c=='20A') 
                && (insurance.Infolease_Environment__c=='10' || insurance.Infolease_Environment__c=='C')
               && fieldsChanged != null && ((fieldsChanged.contains('Cancel_Date__c') && fieldsChanged.size() > 1)
               || (!fieldsChanged.contains('Cancel_Date__c') && fieldsChanged.size() > 0))){
                insurance.addError('This insurance policy must be updated in Infolease 10');
            }
        }
    }

    private void afterChangesToOthers(Map<Id, SObject> newMap, Boolean isNewInsurance){
        List<Account> customersToUpdate = new List<Account>();
        List<Insurance__c> insurancesToSync = new List<Insurance__c>();
        Set<Id> accountIds = new Set<Id>();
        for(SObject obj : newMap.values()){
            Insurance__c insurance = (Insurance__c)obj;
            if(insurance.Customer__c != null && !accountIds.contains(insurance.Customer__c)){
                accountIds.add(insurance.Customer__c);
                Account customer = SL_InsuranceTriggerHandler.newActiveInsuranceToAccount(this.customerAccounts.get(insurance.Customer__c), insurance);
                if (customer != null){
                    customersToUpdate.add(customer);
                }
            }
            if(insurance.Save_at_Account_Level__c){
                Insurance__c turnOff = new Insurance__c(Id = insurance.Id, Save_at_Account_Level__c = false);
                insurancesToSync.add(turnOff);
                Id accountId = null;
                if(insurance.Customer__c != null){
                    accountId = insurance.Customer__c;
                }else{
                    List<Contract__c> contractList = contracts.get(insurance.Id).values();
                    for(Integer i = 0; i < contractList.size(); i++){
                        if(contractList[i].Customer__c != null){
                            accountId = contractList[i].Customer__c;
                            break;
                        }
                    }
                }
                Set<Id> insuranceIds = new Set<Id>();
                List<Contract__c> otherContracts = [SELECT Insurance__c, Insurance__r.Insurance_Id__c FROM Contract__c 
                    WHERE Customer__c = : accountId AND Insurance__c != null AND Insurance__r.Titled_Vehicles__c = FALSE AND Insurance__r.Save_at_Account_Level__c = FALSE AND (NOT Status__c LIKE 'Disposed%')];
                for(Contract__c contract: otherContracts){
                    if(!insuranceIds.contains(contract.Insurance__c) && contract.Insurance__c != insurance.Id){
                        insuranceIds.add(contract.Insurance__c);
                        Insurance__c copy = new Insurance__c();
                        copy = insurance.clone(false,false,false,false);
                        copy.Id = contract.Insurance__c;
                        copy.Insurance_Id__c = contract.Insurance__r.Insurance_Id__c;
                        copy.Save_at_Account_Level__c = false;
                        insurancesToSync.add(copy);
                    }
                }
                    
            }
            
        }
        update customersToUpdate;
        if(insurancesToSync.size() > 0){
            SL_InfoleaseUtils.isRecursive = false;
            update insurancesToSync;
        }
    }

    public static Account newActiveInsuranceToAccount(Account customer, Insurance__c insurance){
        Account updatedCustomer = null;
        if (insurance.Account_Level__c && insurance.Expiration_Date__c > Date.today()
            && (customer.Active_Insurance__c == null 
            || customer.Active_Insurance__r.Expiration_Date__c <= Date.today()
            || customer.Active_Insurance__r.Expiration_Date__c <= insurance.Expiration_Date__c)){
            customer.Active_Insurance__c = insurance.Id;
            updatedCustomer = customer;
        }
        return updatedCustomer;
    }
}