peac_dev/force-app/main/default/objects/Contract__c/Contract__c.object-meta.xml
<CustomObject>
    <description>Custom Object created so we can use Queue functionality</description>
    <label>Contract</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Contract Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Contracts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

peac_dev/force-app/main/default/objects/Contract__c/recordTypes/Lease.recordType-meta.xml
<RecordType>
    <fullName>Lease</fullName>
    <active>true</active>
    <label>Lease</label>
</RecordType>

peac_dev/force-app/main/default/objects/Contract_Attachment__c/Contract_Attachment__c.object-meta.xml
<CustomObject>
    <description>this will use OnBase</description>
    <label>Contract Attachment</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>File Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Contract Attachments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

peac_dev/force-app/main/default/objects/Contract_Attachment__c/fields/Contract__c.field-meta.xml
<CustomField>
    <fullName>Contract__c</fullName>
    <label>Contract</label>
    <referenceTo>Contract__c</referenceTo>
    <relationshipLabel>Contract Attachments</relationshipLabel>
    <relationshipName>Contract_Attachments</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

peac_dev/force-app/main/default/objects/Contract_Attachment__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Document Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Type_Group__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>CL - Credit Bureau Reports</fullName>
            </value>
            <value>
                <fullName>CL - Customer Correspondence</fullName>
            </value>
            <value>
                <fullName>CL - Demand Letters</fullName>
            </value>
            <value>
                <fullName>CL - Investigations</fullName>
            </value>
            <value>
                <fullName>CL - Misc</fullName>
            </value>
            <value>
                <fullName>CS - Address Change</fullName>
            </value>
            <value>
                <fullName>CS - Assumption / Restructure Documentation</fullName>
            </value>
            <value>
                <fullName>CS - Change Request</fullName>
            </value>
            <value>
                <fullName>CS - EOT Form</fullName>
            </value>
            <value>
                <fullName>CS - Letters of Intent</fullName>
            </value>
            <value>
                <fullName>CS - Misc</fullName>
            </value>
            <value>
                <fullName>CS - Tax Exempt Certificates</fullName>
            </value>
            <value>
                <fullName>FS - ACH_Auto Debit Forms and Copy of Check</fullName>
            </value>
            <value>
                <fullName>FS - Additional Stipulations</fullName>
            </value>
            <value>
                <fullName>FS - Bank Account Change Request</fullName>
            </value>
            <value>
                <fullName>FS - Bank Statements</fullName>
            </value>
            <value>
                <fullName>FS - Bank Statements - Apr</fullName>
            </value>
            <value>
                <fullName>FS - Bank Statements - Aug</fullName>
            </value>
            <value>
                <fullName>FS - Bank Statements - Dec</fullName>
            </value>
            <value>
                <fullName>FS - Bank Statements - Feb</fullName>
            </value>
            <value>
                <fullName>FS - Bank Statements - Jan</fullName>
            </value>
            <value>
                <fullName>FS - Bank Statements - Jul</fullName>
            </value>
            <value>
                <fullName>FS - Bank Statements - Jun</fullName>
            </value>
            <value>
                <fullName>FS - Bank Statements - Mar</fullName>
            </value>
            <value>
                <fullName>FS - Bank Statements - May</fullName>
            </value>
            <value>
                <fullName>FS - Bank Statements - Nov</fullName>
            </value>
            <value>
                <fullName>FS - Bank Statements - Oct</fullName>
            </value>
            <value>
                <fullName>FS - Bank Statements - Sept</fullName>
            </value>
            <value>
                <fullName>FS - Bank Statements MTD</fullName>
            </value>
            <value>
                <fullName>FS - Blank Loan Documents</fullName>
            </value>
            <value>
                <fullName>LC - External</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

peac_dev/force-app/main/default/objects/Contract_Attachment__c/fields/Type_Group__c.field-meta.xml
<CustomField>
    <fullName>Type_Group__c</fullName>
    <label>Document Type Group</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Collections</fullName>
            </value>
            <value>
                <fullName>Customer Service</fullName>
            </value>
            <value>
                <fullName>Funding Stream</fullName>
            </value>
            <value>
                <fullName>Insurance</fullName>
            </value>
            <value>
                <fullName>Titled Vehicles</fullName>
            </value>
            <value>
                <fullName>Lease Contract</fullName>
            </value>
            <value>
                <fullName>Asset Management</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

peac_dev/force-app/main/default/classes/showContractDocumentsTest.cls
@isTest
public with sharing class showContractDocumentsTest {
    @isTest
    public static void scenario1() {
        SL_SCTestData.createAccountAndContracts(1, 1);
        Contract__c contract = SL_SCTestData.testContracts[0];
        SL_SCTestData.createContractAttachment(contract.Id);
        Contract_Attachment__c conattachment = [SELECT Id FROM Contract_Attachment__c];
        conattachment.Type__c = 'LC - External';
        conattachment.Type_Group__c = 'Lease Contract';
        update conattachment;
        String contractAttas = showContractDocuments.hubExecute('getContractAttachments',new List<String>{contract.Id});
        system.debug('contractAttas:'+contractAttas);
        Boolean containsId = contractAttas.contains(conattachment.Id);
        Assert.isTrue(containsId); 
    }
}