peac_dev/force-app/main/default/objects/Contract__c/Contract__c.object-meta.xml
<CustomObject>
    <description>Custom Object created so we can use Queue functionality</description>
    <label>Contract</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Contract Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Contracts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

peac_dev/force-app/main/default/objects/Contract__c/fields/Contract_Balance_Remaining__c.field-meta.xml
<CustomField>
    <fullName>Contract_Balance_Remaining__c</fullName>
    <label>Contract Balance Remaining</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

peac_dev/force-app/main/default/objects/Contract__c/fields/Current_Invoice__c.field-meta.xml
<CustomField>
    <fullName>Current_Invoice__c</fullName>
    <label>Current Invoice</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

peac_dev/force-app/main/default/objects/Contract__c/fields/Customer__c.field-meta.xml
<CustomField>
    <fullName>Customer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Customer account</description>
    <label>Customer</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Customer_Contracts</relationshipName>
    <type>Lookup</type>
</CustomField>

peac_dev/force-app/main/default/objects/Contract__c/fields/Dealer_Name__c.field-meta.xml
<CustomField>
    <fullName>Dealer_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Dealer Name</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 OR 2 OR 3</booleanFilter>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Broker Account</value>
        </filterItems>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Dealer Account</value>
        </filterItems>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Franchisor Account</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Contracts (Dealer Name)</relationshipLabel>
    <relationshipName>Custom_Contracts</relationshipName>
    <type>Lookup</type>
</CustomField>

peac_dev/force-app/main/default/objects/Contract__c/fields/Late_Charge_Amount__c.field-meta.xml
<CustomField>
    <fullName>Late_Charge_Amount__c</fullName>
    <label>Late Charges Due</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

peac_dev/force-app/main/default/objects/Contract__c/fields/Misc_Amount_Due__c.field-meta.xml
<CustomField>
    <fullName>Misc_Amount_Due__c</fullName>
    <label>Misc Amount Due</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

peac_dev/force-app/main/default/objects/Contract__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipName>Custom_Contracts</relationshipName>
    <type>Lookup</type>
</CustomField>

peac_dev/force-app/main/default/objects/Contract__c/fields/Past_Due_130__c.field-meta.xml
<CustomField>
    <fullName>Past_Due_130__c</fullName>
    <label>Rental Pastdue (1-30)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

peac_dev/force-app/main/default/objects/Contract__c/fields/Past_Due_3160__c.field-meta.xml
<CustomField>
    <fullName>Past_Due_3160__c</fullName>
    <label>Rental Pastdue (31-60)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

peac_dev/force-app/main/default/objects/Contract__c/fields/Past_Due_6190__c.field-meta.xml
<CustomField>
    <fullName>Past_Due_6190__c</fullName>
    <label>Rental Pastdue (61-90)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

peac_dev/force-app/main/default/objects/Contract__c/fields/Past_Due_90__c.field-meta.xml
<CustomField>
    <fullName>Past_Due_90__c</fullName>
    <label>Rental Pastdue (Over 90)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

peac_dev/force-app/main/default/objects/Contract__c/fields/Program__c.field-meta.xml
<CustomField>
    <fullName>Program__c</fullName>
    <description>The value is populated from the Program field on the Opportunity. SL - 2093</description>
    <label>Program</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Program</valueSetName>
    </valueSet>
</CustomField>

peac_dev/force-app/main/default/objects/Contract__c/fields/Total_Amount_Due__c.field-meta.xml
<CustomField>
    <fullName>Total_Amount_Due__c</fullName>
    <label>Total Due</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

peac_dev/force-app/main/default/objects/Contract__c/fields/Total_Past_Due__c.field-meta.xml
<CustomField>
    <fullName>Total_Past_Due__c</fullName>
    <label>Total Past Due</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

peac_dev/force-app/main/default/objects/Contract__c/fields/Total_Tax_Past_Due__c.field-meta.xml
<CustomField>
    <fullName>Total_Tax_Past_Due__c</fullName>
    <label>Tax</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

peac_dev/force-app/main/default/objects/Opportunity_Attachment__c/Opportunity_Attachment__c.object-meta.xml
<CustomObject>
    <label>OnBase Attachment</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>File Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>OnBase Attachments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

peac_dev/force-app/main/default/objects/Opportunity_Attachment__c/fields/Application__c.field-meta.xml
<CustomField>
    <fullName>Application__c</fullName>
    <formula>Opportunity__r.Application__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Application #</label>
    <type>Text</type>
</CustomField>

peac_dev/force-app/main/default/objects/Opportunity_Attachment__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipName>Attachments</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

peac_dev/force-app/main/default/objects/Opportunity_Attachment__c/fields/Sent_To_OnBase__c.field-meta.xml
<CustomField>
    <fullName>Sent_To_OnBase__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Sent To OnBase</label>
    <type>Checkbox</type>
</CustomField>

peac_dev/force-app/main/default/objects/Program__c/Program__c.object-meta.xml
<CustomObject>
    <label>Program</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Programs</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Programs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

peac_dev/force-app/main/default/classes/SL_DPImperative.cls
public without sharing class SL_DPImperative {
    @AuraEnabled
    public static string hubExecute(String methodName, List<String> parameters){
        String result = '';
        try {
            switch on methodName {
                when 'getCustomerSummary'{
                    result = getCustomerSummary(parameters[0]);
                }
            }
        } catch (Exception e) {
            system.debug('e: ' + e);
            system.debug('e.getMessage(): ' + e.getMessage());
            throw new AuraHandledException(e.getMessage());
        }
        return result;
    }

    public static String getCustomerSummary(String customerId){
        String result = '{}';
        User currentUser = [SELECT Id, Name, Contact.AccountId FROM User WHERE Id = :System.UserInfo.getUserId()];
        Id dealerAccountId = currentUser.Contact.AccountId;
        // if(Test.isRunningTest()){
        //     dealerAccountId = SL_SCTestData.dealerAccountId;
        // }
        List<AggregateResult> customerSummary = [SELECT SUM(Total_Amount_Due__c) totalAmountDue, SUM(Total_Past_Due__c) totalAmtPastDue, SUM(Total_Tax_Past_Due__c) totalTax,
            SUM(Misc_Amount_Due__c) miscellaneous, SUM(Past_Due_130__c) pastDue130, SUM(Past_Due_3160__c) pastDue3160, SUM(Past_Due_6190__c) pastDue6190, 
            SUM(Past_Due_90__c) pastDue90, SUM(Contract_Balance_Remaining__c) totalCbr, COUNT(Id) totalActive, SUM(Current_Invoice__c) currentInvoiced,
            SUM(Late_Charge_Amount__c) lateCharges FROM Contract__c 
            WHERE Is_Active__c = true AND Customer__c = :customerId AND Dealer_Name__c = :dealerAccountId
            GROUP BY Customer__c ];
        system.debug('customerSummary: ' + customerSummary);
        if(customerSummary.size() == 1){
            result = JSON.serialize(customerSummary[0], false);
        }
        return result;
    }
    
    @AuraEnabled
    public static void SendOnBaseEmailXBS(String recordId){
        Opportunity opp = [Select Id, Program__c, StageName, Assign_To_CMS_User__c, Application__c from Opportunity Where Id =:recordId Limit 1];
        
        List<Opportunity_Attachment__c> oppAtList = new List<Opportunity_Attachment__c>();
        opp.StageName = 'Docs In';
        oppAtList = [Select Id from Opportunity_Attachment__c Where Opportunity__c =:recordId AND Sent_to_Onbase__c = false];
        OrgWideEmailAddress noReply = [select Id, Address from OrgWideEmailAddress where Address = 'noreply@peacsolutions.com' Limit 1];
        String subject = 'New Portal Document (app #'+opp.Application__c+')';
        String body = 'Please see the attached document that was uploaded to the Dealer Portal: Application Number: '+opp.Application__c;
        if(opp.Program__c<>NULL && opp.Assign_To_CMS_User__c <> null){
            User CMS = [Select Email from User Where Id=:opp.Assign_To_CMS_User__c Limit 1];
            if(opp.Program__c.Contains('XBS')&&opp.StageName=='Docs In'&& oppAtList.size()>0 && CMS.Email<>NULL){                
        		System.Debug('CMS Email '+CMS.Email);
                List<String> recipientL = new List<String>();
                System.debug('Got to the email');
                recipientL.add(CMS.Email);
                // test email recipient
                // recipientL.add('carlos.herrera@silverlinecrm.com');
                Messaging.SingleEmailMessage mail = CustomSendMailUtil.SetCustomSingleEmail(recipientL,subject,body,null,noReply.ID);
                List<Messaging.SingleEmailMessage> emails = new List<Messaging.SingleEmailMessage>();
                emails.add(mail);
                List<Messaging.SendEmailResult> results = Messaging.sendEmail(emails);
            }
        }
    }

    public static void updateDealerAccounts(List<Account> accLst){
        update accLst;
    }
}