peac_dev/force-app/main/default/objects/Contract__c/Contract__c.object-meta.xml
<CustomObject>
    <description>Custom Object created so we can use Queue functionality</description>
    <label>Contract</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Contract Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Contracts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

peac_dev/force-app/main/default/objects/Contract__c/fields/Customer__c.field-meta.xml
<CustomField>
    <fullName>Customer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Customer account</description>
    <label>Customer</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Customer_Contracts</relationshipName>
    <type>Lookup</type>
</CustomField>

peac_dev/force-app/main/default/objects/Contract__c/fields/Gross_Equipment_Cost__c.field-meta.xml
<CustomField>
    <fullName>Gross_Equipment_Cost__c</fullName>
    <label>Gross Equipment Cost</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

peac_dev/force-app/main/default/objects/Contract__c/recordTypes/Lease.recordType-meta.xml
<RecordType>
    <fullName>Lease</fullName>
    <active>true</active>
    <label>Lease</label>
</RecordType>

peac_dev/force-app/main/default/objects/Contract_Attachment__c/Contract_Attachment__c.object-meta.xml
<CustomObject>
    <description>this will use OnBase</description>
    <label>Contract Attachment</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>File Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Contract Attachments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

peac_dev/force-app/main/default/objects/Contract_Attachment__c/fields/Contract__c.field-meta.xml
<CustomField>
    <fullName>Contract__c</fullName>
    <label>Contract</label>
    <referenceTo>Contract__c</referenceTo>
    <relationshipLabel>Contract Attachments</relationshipLabel>
    <relationshipName>Contract_Attachments</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

peac_dev/force-app/main/default/objects/Contract_Attachment__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Document Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Type_Group__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>CL - Credit Bureau Reports</fullName>
            </value>
            <value>
                <fullName>CL - Customer Correspondence</fullName>
            </value>
            <value>
                <fullName>CL - Demand Letters</fullName>
            </value>
            <value>
                <fullName>CL - Investigations</fullName>
            </value>
            <value>
                <fullName>CL - Misc</fullName>
            </value>
            <value>
                <fullName>CS - Address Change</fullName>
            </value>
            <value>
                <fullName>CS - Assumption / Restructure Documentation</fullName>
            </value>
            <value>
                <fullName>CS - Change Request</fullName>
            </value>
            <value>
                <fullName>CS - EOT Form</fullName>
            </value>
            <value>
                <fullName>CS - Letters of Intent</fullName>
            </value>
            <value>
                <fullName>CS - Misc</fullName>
            </value>
            <value>
                <fullName>CS - Tax Exempt Certificates</fullName>
            </value>
            <value>
                <fullName>FS - ACH_Auto Debit Forms and Copy of Check</fullName>
            </value>
            <value>
                <fullName>FS - Additional Stipulations</fullName>
            </value>
            <value>
                <fullName>FS - Bank Account Change Request</fullName>
            </value>
            <value>
                <fullName>FS - Bank Statements</fullName>
            </value>
            <value>
                <fullName>FS - Bank Statements - Apr</fullName>
            </value>
            <value>
                <fullName>FS - Bank Statements - Aug</fullName>
            </value>
            <value>
                <fullName>FS - Bank Statements - Dec</fullName>
            </value>
            <value>
                <fullName>FS - Bank Statements - Feb</fullName>
            </value>
            <value>
                <fullName>FS - Bank Statements - Jan</fullName>
            </value>
            <value>
                <fullName>FS - Bank Statements - Jul</fullName>
            </value>
            <value>
                <fullName>FS - Bank Statements - Jun</fullName>
            </value>
            <value>
                <fullName>FS - Bank Statements - Mar</fullName>
            </value>
            <value>
                <fullName>FS - Bank Statements - May</fullName>
            </value>
            <value>
                <fullName>FS - Bank Statements - Nov</fullName>
            </value>
            <value>
                <fullName>FS - Bank Statements - Oct</fullName>
            </value>
            <value>
                <fullName>FS - Bank Statements - Sept</fullName>
            </value>
            <value>
                <fullName>FS - Bank Statements MTD</fullName>
            </value>
            <value>
                <fullName>FS - Blank Loan Documents</fullName>
            </value>
            <value>
                <fullName>Title</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

peac_dev/force-app/main/default/objects/Contract_Attachment__c/fields/Updated_Rapport__c.field-meta.xml
<CustomField>
    <fullName>Updated_Rapport__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Updated Rapport</label>
    <type>Checkbox</type>
</CustomField>

peac_dev/force-app/main/default/objects/OnBase_Attachment__c/OnBase_Attachment__c.object-meta.xml
<CustomObject>
    <label>OnBase Attachment</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>File Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>OnBase Attachments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

peac_dev/force-app/main/default/objects/OnBase_Attachment__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>IF Notes &amp; Attachments</relationshipLabel>
    <relationshipName>Account_Attachments</relationshipName>
    <type>Lookup</type>
</CustomField>

peac_dev/force-app/main/default/objects/OnBase_Attachment__c/fields/Sent_To_OnBase__c.field-meta.xml
<CustomField>
    <fullName>Sent_To_OnBase__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Sent To OnBase</label>
    <type>Checkbox</type>
</CustomField>

peac_dev/force-app/main/default/objects/OnBase_Attachment__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Document Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>CS - Master Lease</fullName>
            </value>
            <value>
                <fullName>IF-Internal</fullName>
            </value>
            <value>
                <fullName>IF-External</fullName>
            </value>
            <value>
                <fullName>IF-ACH/Auto Debit Forms &amp; Copy Of Check</fullName>
            </value>
            <value>
                <fullName>IF-Misc</fullName>
            </value>
            <value>
                <fullName>IF-Credit Bureaus</fullName>
            </value>
            <value>
                <fullName>IF-Credit Application</fullName>
            </value>
            <value>
                <fullName>IF-Proof Of Insurance</fullName>
            </value>
            <value>
                <fullName>IF-Additional Stipulations</fullName>
            </value>
            <value>
                <fullName>IF-Bank Account Change Reques</fullName>
                <label>IF-Bank Account Change Request</label>
            </value>
            <value>
                <fullName>IF-Bank Statements</fullName>
            </value>
            <value>
                <fullName>IF-Booking Sheet</fullName>
            </value>
            <value>
                <fullName>IF-Financial Statements</fullName>
            </value>
            <value>
                <fullName>IF-Email Credit/Sales/Booking</fullName>
            </value>
            <value>
                <fullName>IF-Invoice</fullName>
            </value>
            <value>
                <fullName>IF-UCC Filed Copy</fullName>
            </value>
            <value>
                <fullName>IF-Guarantor- Corp or PG</fullName>
            </value>
            <value>
                <fullName>IF-Purchase Order</fullName>
            </value>
            <value>
                <fullName>IF-MSRP-Equipment Details</fullName>
            </value>
            <value>
                <fullName>IF-SOS/License Verification</fullName>
            </value>
            <value>
                <fullName>IF-Tax Returns</fullName>
            </value>
            <value>
                <fullName>IF-Addendum- Terms</fullName>
            </value>
            <value>
                <fullName>IF-Addendum Location</fullName>
            </value>
            <value>
                <fullName>IF-Master Inventory Finance Agreement</fullName>
            </value>
            <value>
                <fullName>IF-Takedown Inventory Finance Agreement</fullName>
            </value>
            <value>
                <fullName>IF-Certificate Of Authentication</fullName>
            </value>
            <value>
                <fullName>IF-Customer Correspondence</fullName>
            </value>
            <value>
                <fullName>IF-Inventory Finance Scorecard</fullName>
            </value>
            <value>
                <fullName>IF-Reg B Letter</fullName>
            </value>
            <value>
                <fullName>IF-Booking Documentation</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

peac_dev/force-app/main/default/classes/SL_UploadAttachmentTest.cls
@isTest
public with sharing class SL_UploadAttachmentTest {
    static final String TYPE = 'Title';
    static final String ATTACHMENT_NAME = 'new.log ';
    static final String FILL_CUSTOMER_MESSAGE = 'The Customer Account Name is required in order to Send to Onbase';

    @isTest
    static void sendAttachmentToOnBase() {
        SL_SCTestData.createAccountAndContracts(1, 1);
        Contract__c contract = SL_SCTestData.testContracts[0];
        SL_SCTestData.createContractAttachment(contract.Id);
        Test.startTest();
        ApexPages.currentPage().getParameters().put('id', contract.Id);
        SL_UploadAttachment ctrl = new SL_UploadAttachment();
        Contract_Attachment__c attachmentBefore = [SELECT Id FROM Contract_Attachment__c];
        SL_UploadAttachment.saveAttachment(attachmentBefore.Id, ATTACHMENT_NAME, 'BLOB');
        ctrl.sendAttachmentToOnBase();
        Test.stopTest();
        system.assert(true);
    }

    @isTest
    static void sendAttachmentToOnBase_otherType() {
        SL_SCTestData.createAccountAndContracts(1, 1);
        Contract__c contract = SL_SCTestData.testContracts[0];
        SL_SCTestData.createContractAttachment(contract.Id);
        contract.Gross_Equipment_Cost__c = 100;
        update contract;
        Test.startTest();
        ApexPages.currentPage().getParameters().put('id', contract.Id);
        SL_UploadAttachment ctrl = new SL_UploadAttachment ();
        Contract_Attachment__c attachmentBefore = [SELECT Id FROM Contract_Attachment__c];
        SL_UploadAttachment.hubExecute('saveAttachment', new List<String>{String.valueOf(attachmentBefore.Id),
                ATTACHMENT_NAME, 'BLOB'});
        ctrl.sendAttachmentToOnBase();
        Test.stopTest();
        system.assert(true);
    }
@isTest
    static void sendAttachmentToOnBase_noCustomer() {
        SL_SCTestData.createAccountAndContracts(1, 1);
        Contract__c contract = SL_SCTestData.testContracts[0];
        SL_SCTestData.createContractAttachment(contract.Id);
        contract.Customer__c = null;
        update contract;
        Test.startTest();
        ApexPages.currentPage().getParameters().put('id', contract.Id);
        SL_UploadAttachment ctrl = new SL_UploadAttachment ();
        Contract_Attachment__c attachmentBefore = [SELECT Id FROM Contract_Attachment__c];
        SL_UploadAttachment.saveAttachment(attachmentBefore.Id, ATTACHMENT_NAME, 'BLOB');
        ctrl.sendAttachmentToOnBase();
        attachmentBefore.Sent_To_OnBase__c = true;
        attachmentBefore.Updated_Rapport__c = true;
        update attachmentBefore;
        ctrl.sendAttachmentToOnBase();
        ctrl.back();
        ctrl.success();
        Test.stopTest();
        system.assertEquals([select Id from Attachment].size(), 1);
    }
    
    @isTest
    static void getOtherContracts(){
        SL_SCTestData.createAccountAndContracts(1, 2);
        Test.startTest();
        List<Account> accounts = [SELECT Id FROM Account];
        List<Contract__c> contracts = [SELECT Id FROM Contract__c WHERE Customer__c = :SL_SCTestData.testAccounts[0].Id];
        List<Contract__c> otherContracts = SL_UploadAttachment.getOtherContracts(contracts[0].Id);
        Test.stopTest();
        system.assert(otherContracts[0].Id == contracts[1].Id);
    }

    @isTest
    static void saveOtherContracts_noCustomer(){
        SL_SCTestData.createAccountAndContracts(1, 3);
        String errorResult = '';
        Test.startTest();
        List<Account> accounts = SL_SCTestData.testAccounts;
        List<Contract__c> contracts = [SELECT Id FROM Contract__c WHERE Customer__c = :accounts[0].Id];
        SL_SCTestData.createContractAttachment(contracts[0].Id);
        Contract_Attachment__c contractAtta = [SELECT Id FROM Contract_Attachment__c WHERE Contract__c=:contracts[0].Id];
        SL_UploadAttachment.saveAttachment(contractAtta.Id, ATTACHMENT_NAME, 'BLOB');
        contracts[0].Customer__c = null;
        update contracts[0];
        errorResult = SL_UploadAttachment.hubExecute('saveOtherContracts', new List<String>{String.valueOf(contractAtta.Id),
            contracts[0].Id, String.valueOf(contracts[1].id) + ',' + String.valueOf(contracts[2].id)});
        Test.stopTest();
        Integer createdAttachments = [SELECT COUNT() FROM Contract_Attachment__c WHERE Contract__r.Customer__c = :accounts[0].Id];
        System.assertEquals(2, createdAttachments);
        System.assertEquals(FILL_CUSTOMER_MESSAGE, errorResult);
    }

    @isTest
    static void saveOtherContracts2(){
        SL_SCTestData.createAccountAndContracts(1, 1);
        Contract__c contract = SL_SCTestData.testContracts[0];
        SL_SCTestData.createContractAttachment(contract.Id);
        Test.startTest();
        Contract_Attachment__c contractAtta = [SELECT Id FROM Contract_Attachment__c WHERE Contract__c=:contract.Id];
        SL_UploadAttachment.saveAttachment(contractAtta.Id, ATTACHMENT_NAME, 'BLOB');
        SL_UploadAttachment.hubExecute('saveOtherContracts', new List<String>{String.valueOf(contractAtta.Id),
            contract.Id, ''});
        Test.stopTest();
        Integer createdAttachments = [SELECT COUNT() FROM Contract_Attachment__c WHERE Contract__r.Customer__c = :SL_SCTestData.testAccounts[0].Id];
        System.assertEquals(1, createdAttachments);
    }

    @isTest
    static void saveOtherContracts3(){
        SL_SCTestData.createAccountAndContracts(1, 3);
        Account testAccount = SL_SCTestData.testAccounts[0];
        List<Contract__c> contracts = SL_SCTestData.testContracts;
        String errorResult = '';
        Test.startTest();
        SL_SCTestData.createContractAttachment(contracts[0].Id);
        Contract_Attachment__c contractAtta = [SELECT Id FROM Contract_Attachment__c WHERE Contract__c=:contracts[0].Id];
        SL_UploadAttachment.saveAttachment(contractAtta.Id, ATTACHMENT_NAME, 'BLOB');
        errorResult = SL_UploadAttachment.hubExecute('saveOtherContracts', new List<String>{String.valueOf(contractAtta.Id),
            contracts[0].Id, String.valueOf(contracts[1].id) + ',' + String.valueOf(contracts[2].id)});
        Test.stopTest();
        Integer createdAttachments = [SELECT COUNT() FROM Contract_Attachment__c WHERE Contract__r.Customer__c = :testAccount.Id];
        System.assertEquals(3, createdAttachments);
        System.assertEquals('success', errorResult);
    }
    
    @isTest
    static void testSendToOnBaseFromAcc(){
      SL_SCTestData.createAccountAndContracts(1, 1);
      List<OnBase_Attachment__c> lstOnBaseAttachment = new List<OnBase_Attachment__c>();
      for(Integer i=0; i<10; i++){
        OnBase_Attachment__c onBaseAttachment = new OnBase_Attachment__c();
        onBaseAttachment.Name = 'Test ' + i;
        onBaseAttachment.Type__c = 'CS - Master Lease'; // IF-Internal is type for Dealer_Vendor
        onBaseAttachment.Account__c = SL_SCTestData.testAccounts[0].Id;

        lstOnBaseAttachment.add(onBaseAttachment);
      } 

      INSERT lstOnBaseAttachment;

      List<Attachment> lstAttachment = new List<Attachment>();
      for(OnBase_Attachment__c onBaseAttachment :lstOnBaseAttachment){
        Attachment attachment = new Attachment();
        attachment.body = EncodingUtil.base64Decode(EncodingUtil.urlDecode('test', 'UTF-8'));
        attachment.name = onBaseAttachment.Name;
        attachment.parentId = onBaseAttachment.Id;

        lstAttachment.add(attachment);
      }
      
      INSERT lstAttachment;
        
      String result, result2, result3;
        
      Test.StartTest();
      result = SL_UploadAttachment.hubExecute('sendToOnBaseFromAcc', new List<String>{SL_SCTestData.testAccounts[0].Id});
      result2 = SL_UploadAttachment.hubExecute('justSaveAttachment', new List<String>{SL_SCTestData.testAccounts[0].Id, 'testfile', 'BLOB'});
      result3 = SL_UploadAttachment.hubExecute('appendChunk', new List<String>{result2, 'testfile', 'BLOB', 'true'});
      Test.StopTest();
        
        Assert.areEqual('success', result, 'Expecting a success response');
    }
}