peac_dev/force-app/main/default/objects/Contract__c/Contract__c.object-meta.xml
<CustomObject>
    <description>Custom Object created so we can use Queue functionality</description>
    <label>Contract</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Contract Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Contracts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

peac_dev/force-app/main/default/objects/Contract__c/fields/Insurance__c.field-meta.xml
<CustomField>
    <fullName>Insurance__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Insurance</label>
    <referenceTo>Insurance__c</referenceTo>
    <relationshipName>Custom_Contracts</relationshipName>
    <type>Lookup</type>
</CustomField>

peac_dev/force-app/main/default/objects/Contract__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipName>Custom_Contracts</relationshipName>
    <type>Lookup</type>
</CustomField>

peac_dev/force-app/main/default/objects/Contract_Asset__c/Contract_Asset__c.object-meta.xml
<CustomObject>
    <label>Contract Asset</label>
    <nameField>
        <displayFormat>CA-{0000}</displayFormat>
        <label>Contract Asset Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contract Assets</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

peac_dev/force-app/main/default/objects/Contract_Asset__c/fields/Contract__c.field-meta.xml
<CustomField>
    <fullName>Contract__c</fullName>
    <label>Contract</label>
    <referenceTo>Contract__c</referenceTo>
    <relationshipLabel>Contract Assets</relationshipLabel>
    <relationshipName>Contract_Assets</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

peac_dev/force-app/main/default/objects/Contract_Asset__c/fields/Insurance__c.field-meta.xml
<CustomField>
    <fullName>Insurance__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Insurance</label>
    <referenceTo>Insurance__c</referenceTo>
    <relationshipLabel>Contract Assets</relationshipLabel>
    <relationshipName>Contract_Assets</relationshipName>
    <type>Lookup</type>
</CustomField>

peac_dev/force-app/main/default/objects/IL_Integration_Logs__c/IL_Integration_Logs__c.object-meta.xml
<CustomObject>
    <label>IL Integration Log</label>
    <nameField>
        <displayFormat>Log-{000000}</displayFormat>
        <label>IL Integration Logs Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>IL Integration Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

peac_dev/force-app/main/default/objects/IL_Integration_Logs__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>IL Integration Logs</relationshipLabel>
    <relationshipName>IL_Integration_Logs</relationshipName>
    <type>Lookup</type>
</CustomField>

peac_dev/force-app/main/default/objects/IL_Integration_Logs__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>IL Integration Logs</relationshipLabel>
    <relationshipName>IL_Integration_Logs</relationshipName>
    <type>Lookup</type>
</CustomField>

peac_dev/force-app/main/default/objects/IL_Integration_Logs__c/fields/Contract__c.field-meta.xml
<CustomField>
    <fullName>Contract__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contract</label>
    <referenceTo>Contract__c</referenceTo>
    <relationshipLabel>IL Integration Logs</relationshipLabel>
    <relationshipName>IL_Integration_Logs</relationshipName>
    <type>Lookup</type>
</CustomField>

peac_dev/force-app/main/default/objects/IL_Integration_Logs__c/fields/ContractAsset__c.field-meta.xml
<CustomField>
    <fullName>ContractAsset__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contract Asset</label>
    <referenceTo>Contract_Asset__c</referenceTo>
    <relationshipLabel>IL Integration Logs</relationshipLabel>
    <relationshipName>IL_Integration_Logs</relationshipName>
    <type>Lookup</type>
</CustomField>

peac_dev/force-app/main/default/objects/IL_Integration_Logs__c/fields/Error_Message__c.field-meta.xml
<CustomField>
    <fullName>Error_Message__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Error Message</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

peac_dev/force-app/main/default/objects/IL_Integration_Logs__c/fields/External_Id__c.field-meta.xml
<CustomField>
    <fullName>External_Id__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <externalId>true</externalId>
    <label>External Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

peac_dev/force-app/main/default/objects/IL_Integration_Logs__c/fields/Insurance__c.field-meta.xml
<CustomField>
    <fullName>Insurance__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Insurance</label>
    <referenceTo>Insurance__c</referenceTo>
    <relationshipLabel>IL Integration Logs</relationshipLabel>
    <relationshipName>IL_Integration_Logs</relationshipName>
    <type>Lookup</type>
</CustomField>

peac_dev/force-app/main/default/objects/IL_Integration_Logs__c/fields/Integration_Name__c.field-meta.xml
<CustomField>
    <fullName>Integration_Name__c</fullName>
    <label>Integration Name</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Infolease Update Customer</fullName>
            </value>
            <value>
                <fullName>Infolease Update Insurance</fullName>
            </value>
            <value>
                <fullName>Infolease Update Asset</fullName>
            </value>
            <value>
                <fullName>Infolease Update Contract</fullName>
            </value>
            <value>
                <fullName>Infolease Open Item Waiver</fullName>
            </value>
            <value>
                <fullName>InfoLease Generate Buyout Quote</fullName>
            </value>
            <value>
                <fullName>InfoLease Generate Buyout Quote DP</fullName>
            </value>
            <value>
                <fullName>InfoLease Create Insurance</fullName>
            </value>
            <value>
                <fullName>Infolease Create Customer</fullName>
                <isActive>false</isActive>
                <label>Infolease Create Customer</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

peac_dev/force-app/main/default/objects/IL_Integration_Logs__c/fields/Open_Item_Waived_Amount__c.field-meta.xml
<CustomField>
    <fullName>Open_Item_Waived_Amount__c</fullName>
    <label>Open Item Waived Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

peac_dev/force-app/main/default/objects/IL_Integration_Logs__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>IL Integration Logs</relationshipLabel>
    <relationshipName>IL_Integration_Logs</relationshipName>
    <type>Lookup</type>
</CustomField>

peac_dev/force-app/main/default/objects/IL_Integration_Logs__c/fields/Record_Id__c.field-meta.xml
<CustomField>
    <fullName>Record_Id__c</fullName>
    <description>Sits in backend, used to sort sObject Type when logging errors</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Record Id</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

peac_dev/force-app/main/default/objects/IL_Integration_Logs__c/fields/Request_Text__c.field-meta.xml
<CustomField>
    <fullName>Request_Text__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Request Text</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

peac_dev/force-app/main/default/objects/IL_Integration_Logs__c/fields/ResponseText__c.field-meta.xml
<CustomField>
    <fullName>ResponseText__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Response Text</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

peac_dev/force-app/main/default/objects/IL_Integration_Logs__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Success</fullName>
            </value>
            <value>
                <fullName>Error</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

peac_dev/force-app/main/default/objects/Insurance__c/Insurance__c.object-meta.xml
<CustomObject>
    <label>Insurance</label>
    <nameField>
        <displayFormat>INS-{0000}</displayFormat>
        <label>Insurance Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Insurance</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

peac_dev/force-app/main/default/classes/SL_InfoleaseLoggingUtils.cls
/**
 * @File Name          : SL_InfoleaseLoggingUtils.cls
 * @Description        : Logging Utils for CCAN Account SF to IL via BW
 * @Author             : Silverline
 * @Group              :
 * @Last Modified By   :
 * @Last Modified On   :
 * @Modification Log   :
 * Ver       Date            Author                 Modification
 * 1.0    10/06/2021      Silverline                Initial Version
 */
public with sharing class SL_InfoleaseLoggingUtils {

    public static List <IL_Integration_Logs__c> logs = new List <IL_Integration_Logs__c>();

    public static SL_InfoleaseUtils util = SL_InfoleaseUtils.getInstance();
    
    
    public static void addLog(String a, Id b, String c, String d, String e){
        // to pass test validations, this must be removed when deploying
    }
    public static void addLog(String a, String b, String c, String d, String e){
        // to pass test validations, this must be removed when deploying
    }
    
    public static void addLog(String aIntName, String aRecordId, String aReqMessage, String resp, String aErrMessage, Boolean isErrorMessage) {
        addLog(aIntName, aRecordId, aReqMessage, resp, aErrMessage, isErrorMessage, 0);
    }

    public static void addLog(String aIntName, String aRecordId, String aReqMessage, String resp, String aErrMessage, Boolean isErrorMessage, Decimal waivedAmount) {
        logs.add (
            new IL_Integration_Logs__c(
                Integration_Name__c = aIntName, 
                Record_Id__c = aRecordId, 
                Request_Text__c = trimMessage (aReqMessage, 32767), 
                Error_Message__c = trimMessage(aErrMessage,32767),
                External_Id__c = isErrorMessage ? trimMessage(aErrMessage,255) : trimMessage(resp,255),
                ResponseText__c = trimMessage (resp, 32768),
                Type__c = isErrorMessage ? 'Error' : 'Success',
                Open_Item_Waived_Amount__c = waivedAmount
                )
            );
    }
    
    private static String trimMessage (String message, Integer fieldLimit) {
         return message != null && message.length() >= fieldLimit ? message.left(fieldLimit) : message;
    }
    
    public static void flush () {
        //separating success and error logs to be controlled by custom setting
        List<IL_Integration_Logs__c> successLogs = new List<IL_Integration_Logs__c>();
        List<IL_Integration_Logs__c> errorLogs = new List<IL_Integration_Logs__c>();
        try {
            // tam update
            for (IL_Integration_Logs__c log : logs) {
                if (log.Record_Id__c != null && log.Record_Id__c instanceof Id && Id.valueOf (log.Record_Id__c).getSObjectType() == Schema.Opportunity.SObjectType) log.Opportunity__c = log.Record_Id__c;
                if (log.Record_Id__c != null && log.Record_Id__c instanceof Id && Id.valueOf (log.Record_Id__c).getSObjectType() == Schema.Account.SObjectType) log.Account__c = log.Record_Id__c;
                if (log.Record_Id__c != null && log.Record_Id__c instanceof Id && Id.valueOf (log.Record_Id__c).getSObjectType() == Schema.Contact.SObjectType) log.Contact__c = log.Record_Id__c;
                if (log.Record_Id__c != null && log.Record_Id__c instanceof Id && Id.valueOf (log.Record_Id__c).getSObjectType() == Schema.Contract__c.SObjectType) log.Contract__c = log.Record_Id__c;
                if (log.Record_Id__c != null && log.Record_Id__c instanceof Id && Id.valueOf (log.Record_Id__c).getSObjectType() == Schema.Contract_Asset__c.SObjectType) log.ContractAsset__c = log.Record_Id__c;
                if (log.Record_Id__c != null && log.Record_Id__c instanceof Id && Id.valueOf (log.Record_Id__c).getSObjectType() == Schema.Insurance__c.SObjectType) log.Insurance__c = log.Record_Id__c;
                if(log.Type__c == 'Error') errorLogs.add(log);
                else if(log.Type__c == 'Success') successLogs.add(log);
            }
            if(util.getServiceSettings().Generate_Success_Logs__c){
                if(util.getServiceSettings().Upsert_Logs__c){
                    Database.upsert(errorLogs, IL_Integration_Logs__c.External_Id__c);
                    Database.upsert(successLogs, IL_Integration_Logs__c.External_Id__c);
                }else {
                    Database.insert(errorLogs);
                    Database.insert(successLogs);
                }
            }else{
                if(util.getServiceSettings().Upsert_Logs__c){
                    Database.upsert(errorLogs, IL_Integration_Logs__c.External_Id__c);
                }else {
                    Database.insert(errorLogs);
                }
            }
            
            logs = new List <IL_Integration_Logs__c> ();
        } catch (Exception e) {
            System.debug ('Error logging errors: '+e.getMessage());
        }    
    }
}