peac_dev/force-app/main/default/objects/Contract__c/Contract__c.object-meta.xml
<CustomObject>
    <description>Custom Object created so we can use Queue functionality</description>
    <label>Contract</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Contract Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Contracts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

peac_dev/force-app/main/default/objects/Contract__c/fields/Customer__c.field-meta.xml
<CustomField>
    <fullName>Customer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Customer account</description>
    <label>Customer</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Customer_Contracts</relationshipName>
    <type>Lookup</type>
</CustomField>

peac_dev/force-app/main/default/objects/Contract__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Disposed</fullName>
            </value>
            <value>
                <fullName>Disposed - Charged Off</fullName>
            </value>
            <value>
                <fullName>Renewal</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

peac_dev/force-app/main/default/objects/Repurchase_Invoice__c/Repurchase_Invoice__c.object-meta.xml
<CustomObject>
    <label>Repurchase Invoice</label>
    <nameField>
        <displayFormat>DINV-{0000}</displayFormat>
        <label>Repurchase Invoice #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Repurchase Invoices</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

peac_dev/force-app/main/default/objects/Repurchase_Invoice__c/fields/Amount_Invoiced__c.field-meta.xml
<CustomField>
    <fullName>Amount_Invoiced__c</fullName>
    <label>Amount Invoiced</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

peac_dev/force-app/main/default/objects/Repurchase_Invoice__c/fields/Contract__c.field-meta.xml
<CustomField>
    <fullName>Contract__c</fullName>
    <label>Contract</label>
    <referenceTo>Contract__c</referenceTo>
    <relationshipLabel>Repurchase Invoices</relationshipLabel>
    <relationshipName>Repurchase_Invoices</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

peac_dev/force-app/main/default/objects/Repurchase_Invoice__c/fields/Customer__c.field-meta.xml
<CustomField>
    <fullName>Customer__c</fullName>
    <formula>Contract__r.Customer__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Customer</label>
    <type>Text</type>
</CustomField>

peac_dev/force-app/main/default/objects/Repurchase_Invoice__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Invoice Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Open</fullName>
            </value>
            <value>
                <fullName>Paid</fullName>
            </value>
            <value>
                <fullName>Delinquent</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

peac_dev/force-app/main/default/classes/SL_Repurchase_InvoiceTriggerHandler.cls
public with sharing class SL_Repurchase_InvoiceTriggerHandler extends SL_Trigger.baseHandler {

// Map status transitions to task description templates
    public static final Map<String, String> STATUS_DESCRIPTION_MAP = new Map<String, String>{
        'OpenToPaid'       => 'Repurchase Invoice #{0} has been paid. ${1} was received.',
        'OpenToDelinquent' => 'Repurchase Invoice #{0} is now delinquent.',
        'OpenToCancelled'   => 'Repurchase Invoice #{0} is now canceled.'
    };

    public override void afterUpdate(Map<Id, SObject> oldMap, Map<Id, SObject> newMap) {

        checkStatusChange(oldMap, newMap);

    }

    //SL-2204 - Rodrigo Castro
    public void checkStatusChange(Map<Id, SObject> oldMap, Map<Id, SObject> newMap){
                System.debug('checkStatusChange ' );

        Map<Id, Repurchase_Invoice__c> newInvoices = (Map<Id, Repurchase_Invoice__c>)newMap;
        Set<Id> contractIds = new Set<Id>();
        for(Repurchase_Invoice__c inv : newInvoices.values()){
            contractIds.add(inv.Contract__c);
        }

    Map<Id, Contract__c> contracts = new Map<Id, Contract__c>([SELECT Id, Customer__c FROM Contract__c WHERE Id IN :contractIds]);    
    List<Task> newTasks = new List<Task>();
        for(Repurchase_Invoice__c inv : newInvoices.values()){
            if(inv.Status__c == 'Paid' && ((Repurchase_Invoice__c)oldMap.get(inv.Id)).Status__c == 'Open'){
                newTasks.add(createTask(inv,'OpenToPaid', contracts.get(inv.Contract__c).Customer__c));
            }
            if(inv.Status__c == 'Delinquent' && ((Repurchase_Invoice__c)oldMap.get(inv.Id)).Status__c == 'Open'){
                newTasks.add(createTask(inv,'OpenToDelinquent', contracts.get(inv.Contract__c).Customer__c));
            }
            if(inv.Status__c == 'Cancelled' && ((Repurchase_Invoice__c)oldMap.get(inv.Id)).Status__c == 'Open'){
                newTasks.add(createTask(inv,'OpenToCancelled', contracts.get(inv.Contract__c).Customer__c));
            }
        }
        if(newTasks.size() > 0){
            insert newTasks;
        }
    }


    public Task createTask(Repurchase_Invoice__c invoiceRecord, String statusChange, String customerId){
            //Creating task for automatic notation as requested in SL-2204
            Task taskRecord =  new Task();
            taskRecord.Contract__c =invoiceRecord.Contract__c;
            taskRecord.WhatId = customerId;
            taskRecord.Type ='Other';
            taskRecord.ActivityDate =Date.today();
            taskRecord.Description = String.format(STATUS_DESCRIPTION_MAP.get(statusChange), new List<String>{invoiceRecord.Name, String.valueOf(invoiceRecord.Amount_Invoiced__c)});
            taskRecord.Status ='Completed';
            return taskRecord;
        }
    


}