peac_dev/force-app/main/default/objects/Contract__c/Contract__c.object-meta.xml
<CustomObject>
    <description>Custom Object created so we can use Queue functionality</description>
    <label>Contract</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Contract Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Contracts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

peac_dev/force-app/main/default/objects/Contract__c/fields/Active_Service_Billable__c.field-meta.xml
<CustomField>
    <fullName>Active_Service_Billable__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Field used in to SL_ContractMiscBillableTriggerHandler, If there is an active misc. billable with GL code 0017 the field is checked as true</description>
    <label>Active Service Billable</label>
    <type>Checkbox</type>
</CustomField>

peac_dev/force-app/main/default/objects/Contract_Misc_Billable__c/Contract_Misc_Billable__c.object-meta.xml
<CustomObject>
    <label>Contract Misc Billable</label>
    <nameField>
        <displayFormat>CMB-{0000}</displayFormat>
        <label>Contract Misc Billable Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contract Misc Billables</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

peac_dev/force-app/main/default/objects/Contract_Misc_Billable__c/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <formula>IF( AND( First_Payment_Date__c &lt;= TODAY() , Final_Payment_Date__c &gt;= TODAY() ) , true, false)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

peac_dev/force-app/main/default/objects/Contract_Misc_Billable__c/fields/Contract__c.field-meta.xml
<CustomField>
    <fullName>Contract__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contract</label>
    <referenceTo>Contract__c</referenceTo>
    <relationshipLabel>Contract Misc Billables</relationshipLabel>
    <relationshipName>Contract_Misc_Billables</relationshipName>
    <type>Lookup</type>
</CustomField>

peac_dev/force-app/main/default/objects/Contract_Misc_Billable__c/fields/GL_Code__c.field-meta.xml
<CustomField>
    <fullName>GL_Code__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>G/L Code</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

peac_dev/force-app/main/default/objects/Gl_Code__c/Gl_Code__c.object-meta.xml
<CustomObject>
    <label>Gl Code</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Gl Code Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>GL Codes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

peac_dev/force-app/main/default/classes/SL_ContractUpdateBatch.cls
public class SL_ContractUpdateBatch implements Database.Batchable<SObject> {
    public Database.QueryLocator start(Database.BatchableContext bc) {
        String query = 'SELECT Id, Contract__c, GL_Code__c, Active__c, Contract__r.Active_Service_Billable__c ' +
                       'FROM Contract_Misc_Billable__c ' +
                       'WHERE GL_Code__c = \'0017\' AND ' +
                       '((Active__c = false AND Contract__r.Active_Service_Billable__c = true) OR ' +
                       '(Active__c = true AND Contract__r.Active_Service_Billable__c = false))';
        return Database.getQueryLocator(query);
    }

    public void execute(Database.BatchableContext bc, List<Contract_Misc_Billable__c> scope) {
        Set<Id> contractIds = new Set<Id>();
        for (Contract_Misc_Billable__c cmb : scope) {
            contractIds.add(cmb.Contract__c);
        }

        // Query all related Contract_Misc_Billable__c records in one query
        Map<Id, List<Contract_Misc_Billable__c>> contractToCmbMap = new Map<Id, List<Contract_Misc_Billable__c>>();
        for (Contract_Misc_Billable__c cmb : [SELECT Id, Contract__c, Active__c FROM Contract_Misc_Billable__c WHERE Contract__c IN :contractIds]) {
            if (!contractToCmbMap.containsKey(cmb.Contract__c)) {
                contractToCmbMap.put(cmb.Contract__c, new List<Contract_Misc_Billable__c>());
            }
            contractToCmbMap.get(cmb.Contract__c).add(cmb);
        }

        // Query all related Contract__c records in one query
        Map<Id, Contract__c> contractsMap = new Map<Id, Contract__c>([SELECT Id, Active_Service_Billable__c FROM Contract__c WHERE Id IN :contractIds]);
    
        List<Contract__c> contractsToUpdate = new List<Contract__c>();
        for (Id contractId : contractToCmbMap.keySet()) {
            Boolean shouldBeActive = false;
            for (Contract_Misc_Billable__c cmb : contractToCmbMap.get(contractId)) {
                if (cmb.Active__c == true) {
                    shouldBeActive = true;
                    break;
                }
            }

            Contract__c contract = contractsMap.get(contractId);
            if (contract.Active_Service_Billable__c != shouldBeActive) {
                contract.Active_Service_Billable__c = shouldBeActive;
                contractsToUpdate.add(contract);
            }
        }

        if (!contractsToUpdate.isEmpty()) {
            update contractsToUpdate;
        }
    }

    public void finish(Database.BatchableContext bc) {
        // Optional: Add any post-processing logic here
    }
}