peac_dev/force-app/main/default/objects/Contract__c/Contract__c.object-meta.xml
<CustomObject>
    <description>Custom Object created so we can use Queue functionality</description>
    <label>Contract</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Contract Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Contracts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

peac_dev/force-app/main/default/objects/Contract__c/fields/Customer__c.field-meta.xml
<CustomField>
    <fullName>Customer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Customer account</description>
    <label>Customer</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Customer_Contracts</relationshipName>
    <type>Lookup</type>
</CustomField>

peac_dev/force-app/main/default/objects/Contract__c/fields/Dealer_Name__c.field-meta.xml
<CustomField>
    <fullName>Dealer_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Dealer Name</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 OR 2 OR 3</booleanFilter>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Broker Account</value>
        </filterItems>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Dealer Account</value>
        </filterItems>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Franchisor Account</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Contracts (Dealer Name)</relationshipLabel>
    <relationshipName>Custom_Contracts</relationshipName>
    <type>Lookup</type>
</CustomField>

peac_dev/force-app/main/default/objects/Contract_Asset__c/Contract_Asset__c.object-meta.xml
<CustomObject>
    <label>Contract Asset</label>
    <nameField>
        <displayFormat>CA-{0000}</displayFormat>
        <label>Contract Asset Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contract Assets</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

peac_dev/force-app/main/default/objects/Contract_Asset__c/fields/Asset_Address_1__c.field-meta.xml
<CustomField>
    <fullName>Asset_Address_1__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Asset Address 1</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

peac_dev/force-app/main/default/objects/Contract_Asset__c/fields/Asset_City__c.field-meta.xml
<CustomField>
    <fullName>Asset_City__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Asset City</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

peac_dev/force-app/main/default/objects/Contract_Asset__c/fields/Asset_State__c.field-meta.xml
<CustomField>
    <fullName>Asset_State__c</fullName>
    <label>Asset State</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>State_Code</valueSetName>
    </valueSet>
</CustomField>

peac_dev/force-app/main/default/objects/Contract_Asset__c/fields/Asset_Zip_Code__c.field-meta.xml
<CustomField>
    <fullName>Asset_Zip_Code__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Asset Zip Code</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

peac_dev/force-app/main/default/objects/Contract_Asset__c/fields/Contract__c.field-meta.xml
<CustomField>
    <fullName>Contract__c</fullName>
    <label>Contract</label>
    <referenceTo>Contract__c</referenceTo>
    <relationshipLabel>Contract Assets</relationshipLabel>
    <relationshipName>Contract_Assets</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

peac_dev/force-app/main/default/objects/Contract_Asset__c/fields/Customer__c.field-meta.xml
<CustomField>
    <fullName>Customer__c</fullName>
    <formula>Contract__r.Customer_name__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Customer</label>
    <type>Text</type>
</CustomField>

peac_dev/force-app/main/default/objects/Contract_Asset__c/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Location</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Location.Is_Active__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Location</referenceTo>
    <relationshipLabel>Contract Assets</relationshipLabel>
    <relationshipName>Contract_Asset_Location</relationshipName>
    <type>Lookup</type>
</CustomField>

peac_dev/force-app/main/default/objects/Contract_Asset__c/fields/Manufacturer__c.field-meta.xml
<CustomField>
    <fullName>Manufacturer__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Manufacturer</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

peac_dev/force-app/main/default/objects/Contract_Asset__c/fields/Model_Number__c.field-meta.xml
<CustomField>
    <fullName>Model_Number__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Model Number</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

peac_dev/force-app/main/default/objects/Contract_Asset__c/fields/Return_Auth_Create_Date__c.field-meta.xml
<CustomField>
    <fullName>Return_Auth_Create_Date__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Return Auth Create Date</label>
    <type>Date</type>
</CustomField>

peac_dev/force-app/main/default/objects/Contract_Asset__c/fields/Return_Authorization__c.field-meta.xml
<CustomField>
    <fullName>Return_Authorization__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Return Authorization</label>
    <type>Checkbox</type>
</CustomField>

peac_dev/force-app/main/default/objects/Contract_Asset__c/fields/Serial_Number__c.field-meta.xml
<CustomField>
    <fullName>Serial_Number__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <externalId>true</externalId>
    <label>Serial Number</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

peac_dev/force-app/main/default/objects/Contract_Asset__c/fields/Service_Provider__c.field-meta.xml
<CustomField>
    <fullName>Service_Provider__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Service Provider</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordType.Name</field>
            <operation>equals</operation>
            <value>Service Provider</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Contract Assets (Service Provider)</relationshipLabel>
    <relationshipName>Contract_Assets_Providers</relationshipName>
    <type>Lookup</type>
</CustomField>

peac_dev/force-app/main/default/classes/SL_ContractAssetReportUnified.cls
public class SL_ContractAssetReportUnified implements Database.Batchable<sObject>, Database.Stateful, Schedulable{
    List<Messaging.SingleEmailMessage> emailsToSend;
    private Set<ID> providers = new Set<ID>();
    private Map<String,String> providersToDocMap = new Map<String,String>();
    private String columnHeaders='Dealer Name, Contract Name, Customer Name, Address, Manufacturer, Model#, Serial#, Partner Location, Return Authorization Created Date, Service Provider\n';
    private List<Account> providersAcc = new List<Account>();
    private Map<String,String>contentDocumentIds = new Map<String,String>();
    private Map<String,String>contentVersions = new Map<String,String>();
    private Map<String,String> providerName = new Map<String,String>();
    public Database.QueryLocator start(Database.BatchableContext bc){        
        for(AggregateResult ar:[Select Service_Provider__c from Contract_Asset__c Where Return_Authorization__c = true AND Service_Provider__c != NULL Group by Service_Provider__c]){
            this.providers.add(String.ValueOf(ar.get('Service_Provider__c')));
        }
        System.debug('provider Ids:');
        System.debug(providers);
        providersAcc = [Select Id, Name from Account Where Id In:providers];
        String query = 'Select Id, Service_Provider__c, Model_Number__c, Serial_Number__c, Return_Auth_Create_Date__c, Asset_Address_1__c, Asset_City__c, Asset_Zip_Code__c, Asset_State__c, Location__c, Location__r.Name, Contract__c, Contract__r.Dealer_Name__c, Contract__r.Dealer_Name__r.Name, Contract__r.Name, Contract__r.Customer__c, Contract__r.Customer__r.Name, Manufacturer__c From Contract_Asset__c Where Service_Provider__c IN:providers AND Return_Authorization__c = true AND Return_Auth_Create_Date__c =YESTERDAY';
        return Database.getQueryLocator(query);   
    }
    
    public void execute(Database.BatchableContext bc, List<sObject>ContractAssets){        
        //Map<String,List<Contract_Asset__c>> assetsByProviders = new Map<String,List<Contract_Asset__c>>();
        System.debug('Contract Assets:');
        System.debug(ContractAssets);
        List<ContentVersion> documents = new List<ContentVersion>();
        List<String>cvIds = new List<String>();
        System.debug('Providers in execute');
        System.debug(providers);
        for(String providerId:this.providers){
            String ProviderAccNAme;
            for(Account ac: this.providersAcc){
                if(ac.Id == providerId){
                    ProviderAccNAme = ac.Name.escapeCsv();
                    providerName.put(ac.Id,ProviderAccNAme);
                }
            }
        }
            String ReturnAddress;
        	ContentVersion doc = new ContentVersion();
            List<Contract_Asset__c> assets = new List<Contract_Asset__c>();
            List<String>rowValues=new List<String>();
            for(SObject obj:ContractAssets){
                Contract_Asset__c ca = (Contract_Asset__c)obj;
                assets.add(ca);                               
            }
            System.debug('Asset Size');
            System.debug(assets.size());
            if(assets.size()>0){
                for(Contract_Asset__c cons:assets){
                    String servProv = providerName.get(cons.Service_Provider__c);
                	String formatedDate = String.valueOf(cons.Return_Auth_Create_Date__c);
                	String addressString = cons.Asset_Address_1__c + ' ' + cons.Asset_City__c + ' ' + cons.Asset_State__c + ' '+ cons.Asset_Zip_Code__c ;
                    String rowData;
                    String manufacturer ='';
                    if(cons.Manufacturer__c != NULL){
                        manufacturer = cons.Manufacturer__c.escapeCsv();
                    }
                    if(cons.Location__c<>null){
                        // SL-2683 - Carlos Herrera
                        if(cons.Contract__r.Customer__c <> null){
                      rowData=cons.Contract__r.Dealer_Name__r.Name.escapeCsv()+','+cons.Contract__r.Name+','+cons.Contract__r.Customer__r.Name.escapeCsv()+','+addressString.escapeCsv()+ ',' + manufacturer+','+cons.Model_Number__c+','+cons.Serial_Number__c+','+cons.Location__r.Name.escapeCsv()+','+formatedDate+','+servProv;  
                    }else{
                            rowData=cons.Contract__r.Dealer_Name__r.Name.escapeCsv()+','+' '+','+addressString.escapeCsv()+ ',' + manufacturer+','+cons.Model_Number__c+','+cons.Serial_Number__c+','+cons.Location__r.Name.escapeCsv()+','+formatedDate+','+servProv;
                        }
                        
                    }else{
                        // SL-2683 - Carlos Herrera
                        if(cons.Contract__r.Customer__c <> null){
                        rowData=cons.Contract__r.Dealer_Name__r.Name.escapeCsv()+','+cons.Contract__r.Name+','+cons.Contract__r.Customer__r.Name.escapeCsv()+','+addressString.escapeCsv()+ ',' + manufacturer+','+cons.Model_Number__c+','+cons.Serial_Number__c+','+' '+','+formatedDate+','+servProv;
                        }else{
                            rowData=cons.Contract__r.Dealer_Name__r.Name.escapeCsv()+','+cons.Contract__r.Name+','+' '+','+addressString.escapeCsv()+ ',' + manufacturer+','+cons.Model_Number__c+','+cons.Serial_Number__c+','+' '+','+formatedDate+','+servProv;
                        }
                        
                    }
                	
                	rowValues.add(rowData);                
            	}
                System.debug('Doc Content');
                System.debug(rowValues);
            	doc.Title = 'Unified'+' Contract Asset Report '+String.valueOf(Date.Today())+'.csv';
            	String content = columnHeaders + String.join(rowValues,'\n');
            	doc.VersionData = Blob.valueOf(content);
            	doc.ContentLocation = 'S';
				doc.PathOnClient = doc.Title;
                System.debug('Document:');
                System.debug(doc);
				documents.add(doc);
				providersToDocMap.put('providerId',doc.Title);                
                
            }     
            
			            
        
        Database.insert (documents,false);
        System.debug('Documents:');
        System.debug(documents);
        for(ContentVersion cv: documents){
            cvIds.add(cv.Id);
        }
        for(ContentVersion contV:[Select Id, Title, ContentDocumentId from ContentVersion Where Id In:cvIds]){
            contentDocumentIds.put(contV.Title,contV.ContentDocumentId);
            contentVersions.put(contV.Title,contV.Id);
        }
        
        
        
        
    }
    
    public void finish(Database.BatchableContext bc){
        //ContentFolder folders = [Select Id, Name from ContentFolder Where Name ='Remarketer Autoreporting' Limit 1];
        List<ContentDocumentLink> documentLinks = new List<ContentDocumentLink>();
        OrgWideEmailAddress noReply = [select Id from OrgWideEmailAddress where Address = 'noreply@peacsolutions.com' Limit 1];
        /*for(String porvider:this.providers){
            ContentDocumentLink cl = new ContentDocumentLink();
            String DocTitle = providersToDocMap.get(porvider);
            if(DocTitle<>null){
                String DocumentId = contentDocumentIds.get(DocTitle);
            	cl.ContentDocumentId = DocumentId;
            	cl.LinkedEntityId = porvider;
            	cl.ShareType = 'I';
            	cl.Visibility = 'AllUsers';
            	documentLinks.add(cl);
            	ContentDocumentLink cl2 = new ContentDocumentLink();
            	cl2.ContentDocumentId = DocumentId;
            	cl2.LinkedEntityId = folders.Id;
            	cl2.ShareType = 'I';
            	cl2.Visibility = 'AllUsers';
            	documentLinks.add(cl2);
            }  
        }*/
        //insert documentLinks;
        //System.debug('Document Links');
        //System.debug(documentLinks);
        String body = 'Please find the attached report of pending returns.';
        System.debug('providers in Finish');
        System.debug(providers);
        System.debug('contentVersions: ');
        System.debug(contentVersions);
        
            List<ID> attachmentList = new List<ID>();            
            String Title = this.providersToDocMap.get('providerId');
            String contentVersion = this.contentVersions.get(Title);
            System.debug(contentVersion);
            attachmentList.add(contentVersion);            
            Messaging.SingleEmailMessage returnMail = new Messaging.SingleEmailMessage(); //customSendMailUtil.SetCustomSingleEmail(toAddress,'Return Assets',body,null,noReply);
            Messaging.EmailFileAttachment efa = new messaging.EmailFileAttachment();            
            //returnMail.setWhatId(provider);
            List<String> toAddresses = new List<String>{'PeacAssetManagement@peacsolutions.com'};
            //Testing Addresses
            //String testaddress1 = 'carlos.herrera@silverlinecrm.com';
            returnMail.setToAddresses(toAddresses);
            returnMail.setOrgWideEmailAddressId(noReply.Id);
            returnMail.setSubject('Return Assets');
            returnMail.setPlainTextBody(body);
            returnMail.setEntityAttachments(attachmentList);
            Messaging.SendEmailResult[] results = Messaging.sendEmail(new List<Messaging.SingleEmailMessage>{returnMail});
            
        
        //Messaging.SendEmailResult[] results = Messaging.sendEmail(emailsToSend);
    }
    
    public void execute(SchedulableContext sc){
       String Id = Database.ExecuteBatch(new SL_ContractAssetReportUnified(),500);
    }
}