peac_dev/force-app/main/default/objects/Contract__c/Contract__c.object-meta.xml
<CustomObject>
    <description>Custom Object created so we can use Queue functionality</description>
    <label>Contract</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Contract Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Contracts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

peac_dev/force-app/main/default/objects/Contract__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipName>Custom_Contracts</relationshipName>
    <type>Lookup</type>
</CustomField>

peac_dev/force-app/main/default/objects/Dealer__c/Dealer__c.object-meta.xml
<CustomObject>
    <label>Dealer</label>
    <nameField>
        <displayFormat>B-{0000}</displayFormat>
        <label>Dealer Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Dealers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

peac_dev/force-app/main/default/objects/Dealer__c/fields/Dealer__c.field-meta.xml
<CustomField>
    <fullName>Dealer__c</fullName>
    <label>Account</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Dealer Account, Dealer_Account Development, Dealer_Account Penetration, Dealer_Close, Dealer_Discovery, Dealer_Proposal, Dealer_Qualification</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Dealer Opportunities</relationshipLabel>
    <relationshipName>Dealers</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

peac_dev/force-app/main/default/objects/Dealer__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipName>Brokers</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

peac_dev/force-app/main/default/objects/Dealer__c/fields/Primary_Dealer__c.field-meta.xml
<CustomField>
    <fullName>Primary_Dealer__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Indicates if the dealer is primary dealer.</description>
    <label>Primary Dealer</label>
    <type>Checkbox</type>
</CustomField>

peac_dev/force-app/main/default/classes/SL_DealerPortalShareOppTest.cls
@isTest
public with sharing class SL_DealerPortalShareOppTest {
  private static final String OEG_DEALER_PROFILE = 'OEG Dealer';
  private static final String USERNAME = 'Portal.SL.test.user@silverlinecrm.com';

    @isTest
    static void insertAndUpdate() {
        SL_SCTestData.createAccountAndContracts(1, 1);
        SL_SCTestData.createOpportunitiesAndAssets(SL_SCTestData.testAccounts[0].Id, 1, 1);
        Id accId = SL_SCTestData.testAccounts[0].Id;
        User dpUser = SL_SCTestData.createDPUser(accId);
        Map<Id, List<Id>> usersByOppsToShare = new Map<Id, List<Id>>();
        usersByOppsToShare.put(SL_SCTestData.testOpportunities[0].Id, new List<Id>{dpUser.Id});
        Test.startTest();
        System.enqueueJob(new SL_DealerPortalShareOppQ(usersByOppsToShare));
        List<Contract__c> contractsToUpdate = new List<Contract__c>();
    List<Dealer__c> primDealersToUpd = new List<Dealer__c>();
    List<Dealer__c> primDealersToInsert = new List<Dealer__c>();
    List<Dealer__c> primDealersToDelete = new List<Dealer__c>();

        Test.stopTest();
    }

    @isTest
    static void secondConstructor() {
        SL_SCTestData.createAccountAndContracts(3, 1);
        SL_SCTestData.createOpportunitiesAndAssets(SL_SCTestData.testAccounts[0].Id, 1, 1);
        // Id accId = SL_SCTestData.testAccounts[0].Id;
        // User dpUser = SL_SCTestData.createDPUser(accId);
        Test.startTest();
        Opportunity opp = SL_SCTestData.testOpportunities[0];
        SL_SCTestData.testAccounts[1].recordTypeId = SL_SCTestData.DEALER_ACC;
        SL_SCTestData.testAccounts[2].recordTypeId = SL_SCTestData.DEALER_ACC;
        update SL_SCTestData.testAccounts;
        Dealer__c testDealer = new Dealer__c(Opportunity__c = opp.Id, Primary_Dealer__c = true, Dealer__c = SL_SCTestData.testAccounts[1].Id);
        Dealer__c testDealer2 = new Dealer__c(Opportunity__c = opp.Id, Dealer__c = SL_SCTestData.testAccounts[2].Id);
        insert testDealer;
        List<Contract__c> contractsToUpdate = new List<Contract__c>{SL_SCTestData.testContracts[0]};
        List<Dealer__c> primDealersToUpd = new List<Dealer__c>{testDealer};
        List<Dealer__c> primDealersToInsert = new List<Dealer__c>{testDealer2};
        List<Dealer__c> primDealersToDelete = new List<Dealer__c>{testDealer2};
        System.enqueueJob(new SL_DealerPortalShareOppQ(contractsToUpdate, primDealersToUpd, primDealersToInsert, primDealersToDelete));
        Test.stopTest();
    }
}