peac_dev/force-app/main/default/objects/Contract__c/Contract__c.object-meta.xml
<CustomObject>
    <description>Custom Object created so we can use Queue functionality</description>
    <label>Contract</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Contract Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Contracts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

peac_dev/force-app/main/default/objects/Contract_Contact_Role__c/Contract_Contact_Role__c.object-meta.xml
<CustomObject>
    <label>Contract Contact Role</label>
    <nameField>
        <displayFormat>CR-{0000}</displayFormat>
        <label>Contract Contact Role Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contract Contact Roles</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

peac_dev/force-app/main/default/objects/Contract_Contact_Role__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipName>Contract_Roles</relationshipName>
    <type>Lookup</type>
</CustomField>

peac_dev/force-app/main/default/objects/Contract_Contact_Role__c/fields/Contract__c.field-meta.xml
<CustomField>
    <fullName>Contract__c</fullName>
    <label>Contract</label>
    <referenceTo>Contract__c</referenceTo>
    <relationshipName>Contract_Roles</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

peac_dev/force-app/main/default/objects/Contract_Contact_Role__c/fields/Role__c.field-meta.xml
<CustomField>
    <fullName>Role__c</fullName>
    <label>Role</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Principal</fullName>
            </value>
            <value>
                <fullName>Personal Guarantor</fullName>
            </value>
            <value>
                <fullName>Co-Borrower</fullName>
            </value>
            <value>
                <fullName>Family Member</fullName>
            </value>
            <value>
                <fullName>Landlord</fullName>
            </value>
            <value>
                <fullName>Attorney</fullName>
            </value>
            <value>
                <fullName>Primary Contact</fullName>
            </value>
            <value>
                <fullName>Billing Contact</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

peac_dev/force-app/main/default/classes/PEAC_ContractContRoleTriggerHandler_Test.cls
/**************************************************************************************************************
@Author:Rajesh Kumar(LTIMindtree)
@Description:PEAC_ContractContRoleTriggerHandler_Test class is used to test the business logic of
			Contract_Contact_Role__c object and code cover of PEAC_ContractContactRoleTriggerHandlerand 
			and PEAC_ContractContactRoleTriggerHelper
@User Story:DP-903	
@Created Date:June-19-2024
**************************************************************************************************************/
@isTest
Private with sharing class PEAC_ContractContRoleTriggerHandler_Test {
    /************************************************************************************
    @Author:Rajesh Kumar(LTIMindtree)    
    @Description: Testsetup method to create test data for the test class
    ************************************************************************************/
    @TestSetup
    static void createTestData(){
        SL_SCTestData.createAccountAndContracts(3,1);
        List<Contract__c> contracts = [SELECT Id, OwnerId FROM Contract__c];
        List<Contact> conts = [SELECT Id, OwnerId FROM Contact];
        Contract_Contact_Role__c contractConRole = new Contract_Contact_Role__c();
        contractConRole.Contract__c = contracts[0].id;
        contractConRole.Contact__c = conts[0].id;
        contractConRole.Role__c = PEAC_ConstantClass.PRIMARY_CONTACT;
        test.StartTest();
        insert contractConRole;//Insert Contract Contact Role record
        test.StopTest();
        List<Contract_Contact_Role__c> contRolelInsList = [SELECT Id, Contact__c FROM Contract_Contact_Role__c];
        Assert.areEqual(1, contRolelInsList.size(), 'Contract contact role is not created');// Positive test case
    }
    /************************************************************************************
    @Author:Rajesh Kumar(LTIMindtree)     
    @Description: updatePrimaryContactTest method is testing the Primary Contact update
    on contract records
    ************************************************************************************/
    @isTest
    static void updatePrimaryContactTest()
    {
        List<Contract__c> contractList = [SELECT Id, OwnerId FROM Contract__c];
        List<Contact> contactList = [SELECT Id, OwnerId FROM Contact];
        List<Contract_Contact_Role__c> contRoleList = [SELECT Id, Contact__c FROM Contract_Contact_Role__c];
        
        contRoleList[0].Contact__c = contactList[1].id;
        test.StartTest();
        Update contRoleList;//Update Contract Contact Role with contact
        test.StopTest();
        List<Contract_Contact_Role__c> contRoleUptList = [SELECT Id, Contact__c FROM Contract_Contact_Role__c WHERE ID =:contRoleList[0].ID];
        Assert.areEqual(contRoleUptList[0].Contact__c, contRoleList[0].Contact__c, 'Contract contact role is not updated with contact');// Positive test case
        
    }
    /************************************************************************************
    @Author:Rajesh Kumar(LTIMindtree)     
    @Description: deletePrimaryContactTest method is testing the Primary Contact
    deletion/update on contract records
    ************************************************************************************/
    @isTest
    static void deletePrimaryContactTest()
    {
        List<Contract_Contact_Role__c> contRoleList = [SELECT Id, Contact__c FROM Contract_Contact_Role__c];
        test.StartTest();
        delete contRoleList;//Delete COntract Contact Role 
        test.StopTest();
        List<Contract_Contact_Role__c> contRoleDelList = [SELECT Id, Contact__c FROM Contract_Contact_Role__c];
        Assert.areEqual(0, contRoleDelList.size(), 'Contract contact role is not deleted');
    }
    
}