peac_dev/force-app/main/default/objects/Modifier__c/Modifier__c.object-meta.xml
<CustomObject>
    <description>Pricing users should configure modifiers that adjust base rates or residual tables without hard-coding logic.</description>
    <label>Modifier</label>
    <nameField>
        <displayFormat>M-{0000}</displayFormat>
        <label>Modifier Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Modifiers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

peac_dev/force-app/main/default/objects/Modifier__c/fields/Rate_Card__c.field-meta.xml
<CustomField>
    <fullName>Rate_Card__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Rate Card</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>RateCard__c.Rate_Card_Type__c</field>
            <operation>equals</operation>
            <value>Interest Rate, Rate Factor</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>RateCard__c</referenceTo>
    <relationshipLabel>Modifiers</relationshipLabel>
    <relationshipName>Modifiers</relationshipName>
    <type>Lookup</type>
</CustomField>

peac_dev/force-app/main/default/objects/Modifier__c/fields/Residual_Balloon_Table__c.field-meta.xml
<CustomField>
    <fullName>Residual_Balloon_Table__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Residual/Balloon Table</label>
    <referenceTo>Program_Residual__c</referenceTo>
    <relationshipLabel>Modifiers</relationshipLabel>
    <relationshipName>Modifiers</relationshipName>
    <type>Lookup</type>
</CustomField>

peac_dev/force-app/main/default/objects/Program_Residual__c/Program_Residual__c.object-meta.xml
<CustomObject>
    <description>Pricing users should associate programs with residual or balloon tables so that residual pricing can be configured centrally.</description>
    <label>Program Residual</label>
    <nameField>
        <displayFormat>PRN-{0000}</displayFormat>
        <label>Program Residual  Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Program Residuals</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

peac_dev/force-app/main/default/objects/Program_Residual__c/fields/Residual_Balloon_Table__c.field-meta.xml
<CustomField>
    <fullName>Residual_Balloon_Table__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Residual/Balloon Table</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Must select a Residual card for Program Residuals.</errorMessage>
        <filterItems>
            <field>RateCard__c.Rate_Card_Type__c</field>
            <operation>equals</operation>
            <value>Residual</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>RateCard__c</referenceTo>
    <relationshipLabel>Program Residuals</relationshipLabel>
    <relationshipName>Program_Residuals</relationshipName>
    <type>Lookup</type>
</CustomField>

peac_dev/force-app/main/default/objects/Rate__c/Rate__c.object-meta.xml
<CustomObject>
    <label>Rate</label>
    <nameField>
        <displayFormat>R-{0000}</displayFormat>
        <label>Rate Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Rates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

peac_dev/force-app/main/default/objects/Rate_Card_Column__c/Rate_Card_Column__c.object-meta.xml
<CustomObject>
    <label>Rate Card Column</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Rate Card Column Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Rate Card Columns</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

peac_dev/force-app/main/default/objects/Rate_Card_Column__c/fields/Column_Criteria__c.field-meta.xml
<CustomField>
    <fullName>Column_Criteria__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>The set of conditions used to determine if the transaction meets the criteria of the column.</inlineHelpText>
    <label>Column Criteria</label>
    <referenceTo>TCRE__Rule_Config__c</referenceTo>
    <relationshipLabel>Rate Card Columns</relationshipLabel>
    <relationshipName>Rate_Card_Columns</relationshipName>
    <type>Lookup</type>
</CustomField>

peac_dev/force-app/main/default/objects/Rate_Card_Column__c/fields/Rate_Card__c.field-meta.xml
<CustomField>
    <fullName>Rate_Card__c</fullName>
    <label>Rate Card</label>
    <referenceTo>RateCard__c</referenceTo>
    <relationshipLabel>Rate Card Columns</relationshipLabel>
    <relationshipName>Rate_Card_Columns</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

peac_dev/force-app/main/default/objects/Rate_Card_Rate__c/Rate_Card_Rate__c.object-meta.xml
<CustomObject>
    <label>Rate Card Rate</label>
    <nameField>
        <displayFormat>RCR-{0000}</displayFormat>
        <label>Rate Card Rate Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Rate Card Rates</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

peac_dev/force-app/main/default/objects/Rate_Card_Rate__c/fields/Rate__c.field-meta.xml
<CustomField>
    <fullName>Rate__c</fullName>
    <inlineHelpText>The Rate that is added to the Base Rate used for the transaction if it meets the column and row criteria.</inlineHelpText>
    <label>Rate</label>
    <precision>13</precision>
    <scale>10</scale>
    <type>Percent</type>
</CustomField>

peac_dev/force-app/main/default/objects/Rate_Card_Rate__c/fields/Rate_Card_Column__c.field-meta.xml
<CustomField>
    <fullName>Rate_Card_Column__c</fullName>
    <label>Rate Card Column</label>
    <referenceTo>Rate_Card_Column__c</referenceTo>
    <relationshipLabel>Rate Card Rates</relationshipLabel>
    <relationshipName>Rate_Card_Rates</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

peac_dev/force-app/main/default/objects/Rate_Card_Rate__c/fields/Rate_Card_Row__c.field-meta.xml
<CustomField>
    <fullName>Rate_Card_Row__c</fullName>
    <label>Rate Card Row</label>
    <referenceTo>Rate_Card_Row__c</referenceTo>
    <relationshipLabel>Rate Card Rates</relationshipLabel>
    <relationshipName>Rate_Card_Rates</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

peac_dev/force-app/main/default/objects/Rate_Card_Row__c/Rate_Card_Row__c.object-meta.xml
<CustomObject>
    <label>Rate Card Row</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Rate Card Row Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Rate Card Rows</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

peac_dev/force-app/main/default/objects/Rate_Card_Row__c/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <inlineHelpText>The order that the row should appear in the rate card rows. For ex, the first row would have a 1. This drives how the rate card matrix appears.</inlineHelpText>
    <label>Order</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

peac_dev/force-app/main/default/objects/Rate_Card_Row__c/fields/Rate_Card__c.field-meta.xml
<CustomField>
    <fullName>Rate_Card__c</fullName>
    <label>Rate Card</label>
    <referenceTo>RateCard__c</referenceTo>
    <relationshipLabel>Rate Card Rows</relationshipLabel>
    <relationshipName>Rate_Card_Rows</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

peac_dev/force-app/main/default/objects/Rate_Card_Row__c/fields/Row_Criteria__c.field-meta.xml
<CustomField>
    <fullName>Row_Criteria__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>The set of conditions used to determine if the transaction meets the criteria of the row.</inlineHelpText>
    <label>Row Criteria</label>
    <referenceTo>TCRE__Rule_Config__c</referenceTo>
    <relationshipLabel>Rate Card Rows</relationshipLabel>
    <relationshipName>Rate_Card_Rows</relationshipName>
    <type>Lookup</type>
</CustomField>

peac_dev/force-app/main/default/objects/RateCard__c/RateCard__c.object-meta.xml
<CustomObject>
    <label>Rate Card</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Rate Card Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Rate Cards</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

peac_dev/force-app/main/default/objects/RateCard__c/fields/Base_Rate__c.field-meta.xml
<CustomField>
    <fullName>Base_Rate__c</fullName>
    <inlineHelpText>The starting rate that is added to the rate in the rate card to arrive at a total  defaulted rate.</inlineHelpText>
    <label>Base Rate</label>
    <precision>13</precision>
    <scale>10</scale>
    <type>Percent</type>
</CustomField>

peac_dev/force-app/main/default/objects/RateCard__c/fields/Entry_Criteria__c.field-meta.xml
<CustomField>
    <fullName>Entry_Criteria__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>The set of conditions used to determine if the rate card is applicable to a transaction for opportunities.</inlineHelpText>
    <label>Opportunity Entry Criteria</label>
    <referenceTo>TCRE__Rule_Config__c</referenceTo>
    <relationshipLabel>Rate Cards</relationshipLabel>
    <relationshipName>Rate_Cards</relationshipName>
    <type>Lookup</type>
</CustomField>

peac_dev/force-app/main/default/objects/RateCard__c/fields/Quote_Entry_Config__c.field-meta.xml
<CustomField>
    <fullName>Quote_Entry_Config__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>The set of conditions used to determine if the rate card is applicable to a transaction for quotes.</inlineHelpText>
    <label>Quote Entry Config</label>
    <referenceTo>TCRE__Rule_Config__c</referenceTo>
    <relationshipLabel>Rate Cards (Quote Rule Config)</relationshipLabel>
    <relationshipName>Rate_Cards_Quotes</relationshipName>
    <type>Lookup</type>
</CustomField>

peac_dev/force-app/main/default/classes/NT_ModifierService.cls
/**
 * @description Service class for evaluating and applying modifiers.
 *              Modifiers are additive/subtractive point adjustments - order does not affect results.
 * @author Northteq
 */
public without sharing class NT_ModifierService {

    @TestVisible private static Decimal testResidualOverride = null;
    @TestVisible private static Boolean forceEvaluationException = false;
    @TestVisible private static Map<Id, Map<Id, Boolean>> mockModifierRowRuleResults = null;
    @TestVisible private static Map<Id, Map<Id, Boolean>> mockModifierColumnRuleResults = null;
    
    /**
     * @description Evaluates and applies all applicable modifiers
     * @param ctx The pricing context
     * @return NT_PricingContext The updated context with applied modifiers
     */
    public NT_PricingContext applyModifiers(NT_PricingContext ctx) {
        ctx.finalResidual = ctx.baseResidual;
        
        if (ctx.eligibleModifiers.isEmpty()) {
            return ctx;
        }
        
        if (!ctx.hasSelectedRateCard()) {
            return ctx;
        }
        
        // Filter modifiers for the selected rate card
        List<Modifier__c> relevantModifiers = filterModifiersForRateCard(ctx);
        
        
        // Track cumulative adjustments
        Decimal rateAdjustment = 0;
        Decimal residualAdjustment = 0;
        
        // Evaluate and apply each modifier (additive)
        for (Modifier__c modifier : relevantModifiers) {
            try {
                if (forceEvaluationException) { throw new IllegalArgumentException('Forced test exception'); }
                if (isModifierApplicable(modifier, ctx)) {
                    // Get rate adjustment
                    Decimal modRate = getModifierRate(modifier, ctx);
                    if (modRate != null) {
                        rateAdjustment += modRate;
                    }

                    // Get residual adjustment
                    Decimal modResidual = getResidualAdjustment(modifier, ctx);
                    if (modResidual != null) {
                        residualAdjustment += modResidual;
                    }

                    ctx.appliedModifiers.add(modifier);
                    ctx.modifierRateAdjustments.put(modifier.Id, modRate != null ? modRate : 0);
                    ctx.modifierResidualAdjustments.put(modifier.Id, modResidual != null ? modResidual : 0);
                }
            } catch (Exception e) {
                // Track error and continue processing other modifiers
                System.debug('Warning: Error evaluating modifier ' + modifier.Name + ': ' + e.getMessage());
                ctx.modifierErrors.put(modifier.Id, modifier.Name + ': ' + e.getMessage());
            }
        }
        
        ctx.totalModifierRateAdjustment = rateAdjustment;
        ctx.totalModifierResidualAdjustment = residualAdjustment;

        if (ctx.finalRate != null) {
            ctx.finalRate = ctx.finalRate + rateAdjustment;
        } else if (rateAdjustment != 0) {
            ctx.finalRate = rateAdjustment;
        }
        
        if (ctx.finalRateFactor != null) {
            ctx.finalRateFactor = ctx.finalRateFactor + rateAdjustment;
        }
        
        if (ctx.finalResidual != null) {
            ctx.finalResidual = ctx.finalResidual + residualAdjustment;
        } else if (residualAdjustment != 0) {
            ctx.finalResidual = residualAdjustment;
        }
        
        // Apply the same modifier adjustments to each per-term result (Quote context)
        if (ctx.hasTermPricingResults()) {
            for (NT_PricingContext.TermPricingResult tpr : ctx.termPricingResults.values()) {
                if (tpr.finalRate != null) {
                    tpr.finalRate = tpr.finalRate + rateAdjustment;
                } else if (rateAdjustment != 0) {
                    tpr.finalRate = rateAdjustment;
                }
                
                if (tpr.finalRateFactor != null) {
                    tpr.finalRateFactor = tpr.finalRateFactor + rateAdjustment;
                }
                
                if (tpr.finalResidual != null) {
                    tpr.finalResidual = tpr.finalResidual + residualAdjustment;
                } else if (tpr.baseResidual != null) {
                    tpr.finalResidual = tpr.baseResidual + residualAdjustment;
                } else if (residualAdjustment != 0) {
                    tpr.finalResidual = residualAdjustment;
                }
            }
        }
        
        return ctx;
    }
    
    /**
     * @description Filters modifiers to only those related to the selected rate card
     * @param ctx The pricing context
     * @return List<Modifier__c> Filtered list of modifiers
     */
    private List<Modifier__c> filterModifiersForRateCard(NT_PricingContext ctx) {
        List<Modifier__c> filteredModifiers = new List<Modifier__c>();
        
        for (Modifier__c mod : ctx.eligibleModifiers) {
            if (mod.Rate_Card__c == ctx.selectedRateCard.Id) {
                filteredModifiers.add(mod);
            }
        }
        
        return filteredModifiers;
    }
    
    
    /**
     * @description Checks if a modifier is applicable based on its entry criteria
     * @param modifier The modifier to check
     * @param ctx The pricing context
     * @return Boolean true if modifier should be applied
     */
    private Boolean isModifierApplicable(Modifier__c modifier, NT_PricingContext ctx) {
        if (modifier.Modifier_Rate_Card__c == null) {
            return true;
        }

        Id entryCriteria = ctx.isQuote()
            ? modifier.Modifier_Rate_Card__r.Quote_Entry_Config__c
            : modifier.Modifier_Rate_Card__r.Entry_Criteria__c;

        if (entryCriteria == null) {
            return true;
        }

        TCRE.RuleEngine modRE = new TCRE.RuleEngine();
        modRE.logicObjectIds = new Set<Id>{ ctx.parentId };
        modRE.ruleConfigIds = new Set<Id>{ entryCriteria };
        modRE.ruleObjectType = 'RateCard__c';
        try {
            modRE.testRuleConditions();
            for (Map<Id, Boolean> ruleResult : modRE.ruleResults.values()) {
                for (Id ruleConfigId : ruleResult.keySet()) {
                    if (ruleResult.get(ruleConfigId) == true) { return true; }
                }
            }
        } catch (Exception e) {
            System.debug('Error evaluating modifier criteria: ' + e.getMessage());
            return false;
        }
        return false;
    }
    
    
    /**
     * @description Gets the rate adjustment from the modifier's rate card.
     *              Returns Base_Rate__c plus the grid rate matched by row/column criteria
     *              (e.g. credit risk score row × term column intersection).
     * @param modifier The modifier
     * @param ctx The pricing context
     * @return Decimal The rate adjustment value
     */
    private Decimal getModifierRate(Modifier__c modifier, NT_PricingContext ctx) {
        if (modifier.Modifier_Rate_Card__c == null) {
            return null;
        }
        Decimal baseRate = modifier.Modifier_Rate_Card__r.Base_Rate__c != null
            ? modifier.Modifier_Rate_Card__r.Base_Rate__c
            : 0;
        Decimal gridRate = getModifierGridRate(modifier.Modifier_Rate_Card__c, ctx);
        return baseRate + (gridRate != null ? gridRate : 0);
    }

    /**
     * @description Evaluates the modifier rate card's row/column grid to find the
     *              contextual rate adjustment (e.g. credit risk score lookup).
     * @param modRateCardId The modifier rate card Id
     * @param ctx The pricing context
     * @return Decimal The grid rate, or null if no matching row/column found
     */
    private Decimal getModifierGridRate(Id modRateCardId, NT_PricingContext ctx) {
        Boolean useQuoteField = ctx.isQuote();

        // Collect row criteria IDs for this modifier rate card
        Set<Id> rowCriteriaIds = new Set<Id>();
        for (Rate_Card_Row__c row : [
            SELECT Id, Row_Criteria__c, Quote_Row_Criteria__c
            FROM Rate_Card_Row__c
            WHERE Rate_Card__c = :modRateCardId
        ]) {
            Id criteriaId = useQuoteField ? row.Quote_Row_Criteria__c : row.Row_Criteria__c;
            if (criteriaId != null) {
                rowCriteriaIds.add(criteriaId);
            }
        }

        if (rowCriteriaIds.isEmpty()) {
            return null;
        }

        // Evaluate row criteria via TCRE
        Set<Id> matchingRowCriteriaIds = new Set<Id>();
        TCRE.RuleEngine rowRE = new TCRE.RuleEngine();
        rowRE.logicObjectIds = new Set<Id>{ ctx.parentId };
        rowRE.ruleConfigIds = rowCriteriaIds;
        rowRE.ruleObjectType = 'Rate_Card_Row__c';
        try {
            Map<Id, Map<Id, Boolean>> rowResults;
            if (mockModifierRowRuleResults != null) {
                rowResults = mockModifierRowRuleResults;
            } else {
                rowRE.testRuleConditions();
                rowResults = rowRE.ruleResults;
            }
            for (Map<Id, Boolean> ruleResult : rowResults.values()) {
                for (Id ruleConfigId : ruleResult.keySet()) {
                    if (ruleResult.get(ruleConfigId) == true) {
                        matchingRowCriteriaIds.add(ruleConfigId);
                    }
                }
            }
        } catch (Exception e) {
            System.debug('Error evaluating modifier row criteria: ' + e.getMessage());
            return null;
        }

        if (matchingRowCriteriaIds.isEmpty()) {
            return null;
        }

        // Collect column criteria IDs for this modifier rate card
        Set<Id> columnCriteriaIds = new Set<Id>();
        for (Rate_Card_Column__c col : [
            SELECT Id, Column_Criteria__c, Quote_Column_Criteria__c
            FROM Rate_Card_Column__c
            WHERE Rate_Card__c = :modRateCardId
        ]) {
            Id criteriaId = useQuoteField ? col.Quote_Column_Criteria__c : col.Column_Criteria__c;
            if (criteriaId != null) {
                columnCriteriaIds.add(criteriaId);
            }
        }

        // A modifier rate card may have a single catch-all column (e.g. "All term lengths")
        // with no criteria configured. In that case we match on row only. When column
        // criteria DO exist, we require a column match (strict, mirrors NT_RateCardService).
        Boolean hadColumnCriteria = !columnCriteriaIds.isEmpty();

        // Evaluate column criteria if any exist
        Set<Id> matchingColumnCriteriaIds = new Set<Id>();
        if (hadColumnCriteria) {
            TCRE.RuleEngine colRE = new TCRE.RuleEngine();
            colRE.logicObjectIds = new Set<Id>{ ctx.parentId };
            colRE.ruleConfigIds = columnCriteriaIds;
            colRE.ruleObjectType = 'Rate_Card_Column__c';
            try {
                Map<Id, Map<Id, Boolean>> colResults;
                if (mockModifierColumnRuleResults != null) {
                    colResults = mockModifierColumnRuleResults;
                } else {
                    colRE.testRuleConditions();
                    colResults = colRE.ruleResults;
                }
                for (Map<Id, Boolean> ruleResult : colResults.values()) {
                    for (Id ruleConfigId : ruleResult.keySet()) {
                        if (ruleResult.get(ruleConfigId) == true) {
                            matchingColumnCriteriaIds.add(ruleConfigId);
                        }
                    }
                }
            } catch (Exception e) {
                System.debug('Error evaluating modifier column criteria: ' + e.getMessage());
            }
        }

        // Column criteria existed but none matched — no valid intersection, skip this modifier's grid
        if (hadColumnCriteria && matchingColumnCriteriaIds.isEmpty()) {
            return null;
        }

        // Query Rate_Card_Rate__c at the row/column intersection
        List<Rate_Card_Rate__c> rates;
        if (matchingColumnCriteriaIds.isEmpty()) {
            // No column criteria configured — match on row only (catch-all column)
            if (useQuoteField) {
                rates = [
                    SELECT Id, Rate__c
                    FROM Rate_Card_Rate__c
                    WHERE Rate_Card_Row__r.Rate_Card__c = :modRateCardId
                    AND Rate_Card_Row__r.Quote_Row_Criteria__c IN :matchingRowCriteriaIds
                    ORDER BY Rate_Card_Column__r.Order__c
                    LIMIT 1
                ];
            } else {
                rates = [
                    SELECT Id, Rate__c
                    FROM Rate_Card_Rate__c
                    WHERE Rate_Card_Row__r.Rate_Card__c = :modRateCardId
                    AND Rate_Card_Row__r.Row_Criteria__c IN :matchingRowCriteriaIds
                    ORDER BY Rate_Card_Column__r.Order__c
                    LIMIT 1
                ];
            }
        } else {
            if (useQuoteField) {
                rates = [
                    SELECT Id, Rate__c
                    FROM Rate_Card_Rate__c
                    WHERE Rate_Card_Row__r.Rate_Card__c = :modRateCardId
                    AND Rate_Card_Row__r.Quote_Row_Criteria__c IN :matchingRowCriteriaIds
                    AND Rate_Card_Column__r.Quote_Column_Criteria__c IN :matchingColumnCriteriaIds
                    ORDER BY Rate_Card_Column__r.Order__c
                    LIMIT 1
                ];
            } else {
                rates = [
                    SELECT Id, Rate__c
                    FROM Rate_Card_Rate__c
                    WHERE Rate_Card_Row__r.Rate_Card__c = :modRateCardId
                    AND Rate_Card_Row__r.Row_Criteria__c IN :matchingRowCriteriaIds
                    AND Rate_Card_Column__r.Column_Criteria__c IN :matchingColumnCriteriaIds
                    ORDER BY Rate_Card_Column__r.Order__c
                    LIMIT 1
                ];
            }
        }

        return rates.isEmpty() ? null : rates[0].Rate__c;
    }
    
    /**
     * @description Gets the residual adjustment from the modifier
     * @param modifier The modifier
     * @param ctx The pricing context
     * @return Decimal The residual adjustment value
     */
    private Decimal getResidualAdjustment(Modifier__c modifier, NT_PricingContext ctx) {
        if (testResidualOverride != null) {
            return testResidualOverride;
        }
        // Get residual from linked Program_Residual
        if (modifier.Residual_Balloon_Table__c == null) { return null; }
        List<Program_Residual__c> residuals = [SELECT Id, Residual_Balloon_Table__r.Base_Rate__c FROM Program_Residual__c WHERE Id = :modifier.Residual_Balloon_Table__c LIMIT 1];
        if (!residuals.isEmpty() && residuals[0].Residual_Balloon_Table__r != null) {
            return residuals[0].Residual_Balloon_Table__r.Base_Rate__c;
        }
        return null;
    }
    
}