peac_dev/force-app/main/default/objects/Asset__c/Asset__c.object-meta.xml
<CustomObject>
    <label>Asset</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Asset Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Assets</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

peac_dev/force-app/main/default/objects/Asset__c/fields/Cost__c.field-meta.xml
<CustomField>
    <fullName>Cost__c</fullName>
    <inlineHelpText>Value will default from Opportunity on First Asset</inlineHelpText>
    <label>Cost</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

peac_dev/force-app/main/default/objects/Asset__c/fields/List_Price__c.field-meta.xml
<CustomField>
    <fullName>List_Price__c</fullName>
    <label>List Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

peac_dev/force-app/main/default/classes/TC_ChangedToDocsRequestedTest.cls
@isTest
public with sharing class TC_ChangedToDocsRequestedTest {
    @isTest 
    public static void changedToDocsRequested(){
        SL_SCTestData.createAccountAndContracts(1, 1);
        SL_SCTestData.createOpportunitiesAndAssets(SL_SCTestData.testAccounts[0].Id, 1, 1);
        List<Opportunity> opportunities = SL_SCTestData.testOpportunities;
        // List<Asset__c> assets = SL_SCTestData.testAssets;
        // assets[0].List_Price__c = 0;
        // update assets;
        opportunities[0].Probability = 75;
        Test.startTest();
        update opportunities;
        Test.stopTest();
        // List<Opportunity> oppsAfter = [SELECT Id, Branch__c, Equipment_Cost__c FROM Opportunity];
        List<Asset__c> assetsAfter = [SELECT Id, Cost__c, List_Price__c FROM Asset__c];
        Assert.areEqual(assetsAfter[0].List_Price__c, assetsAfter[0].Cost__c, 'TC_ChangedToDocsRequested sets the cost equals to the List Price');
    }
    
}