peac_dev/force-app/main/default/objects/Asset__c/Asset__c.object-meta.xml
<CustomObject>
    <label>Asset</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Asset Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Assets</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

peac_dev/force-app/main/default/objects/Asset__c/fields/List_Price__c.field-meta.xml
<CustomField>
    <fullName>List_Price__c</fullName>
    <label>List Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

peac_dev/force-app/main/default/objects/Asset__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipName>Assets</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

peac_dev/force-app/main/default/classes/TC_CalculateAssetRentalAmount.cls
public class TC_CalculateAssetRentalAmount {
public static void calculateAssetRentalAmount (Map <Id, Asset__c> oldMap, List <Asset__c> newList) {
        /*if (TC_RecursiveTriggerHelper.calculateAssetRentalAmount) {
            return;
        } else {
            TC_RecursiveTriggerHelper.calculateAssetRentalAmount = true;
        }*/
        Set <Id> oppIds = new Set <Id> ();
        
        if (newList == null) {
            for (Asset__c asset : oldMap.values ()) {
                oppIds.add (asset.Opportunity__c);
            }
        } else {
            for (Asset__c asset : newList) {
                if (oldMap == null || oldMap.get (asset.Id).List_Price__c != asset.List_Price__c)
                    oppIds.add (asset.Opportunity__c);
            }
        }
        
        TC_CalculateAssetRentalAmt.calculateAssetRentalAmount (oppIds);
    }
}