peac_dev/force-app/main/default/objects/Asset__c/Asset__c.object-meta.xml
<CustomObject>
    <label>Asset</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Asset Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Assets</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

peac_dev/force-app/main/default/objects/Asset__c/fields/End_User_Billing_Address__c.field-meta.xml
<CustomField>
    <fullName>End_User_Billing_Address__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Want to utilize the Business address from the opportunity? If yes, check this box and select save. If not, provide the alternative address.</inlineHelpText>
    <label>End User Business Address?</label>
    <type>Checkbox</type>
</CustomField>

peac_dev/force-app/main/default/objects/Asset__c/fields/Equipment_Code__c.field-meta.xml
<CustomField>
    <fullName>Equipment_Code__c</fullName>
    <label>Equipment Code</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Asset_Equipment_Code</valueSetName>
    </valueSet>
</CustomField>

peac_dev/force-app/main/default/objects/Asset__c/fields/Equipment_Sub_Category__c.field-meta.xml
<CustomField>
    <fullName>Equipment_Sub_Category__c</fullName>
    <label>Equipment Sub-Category</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Equipment_Code__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>Equipment_Sub_Category</valueSetName>
    </valueSet>
</CustomField>

peac_dev/force-app/main/default/objects/Asset__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipName>Assets</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

peac_dev/force-app/main/default/objects/Asset__c/fields/Quantity__c.field-meta.xml
<CustomField>
    <fullName>Quantity__c</fullName>
    <defaultValue>1</defaultValue>
    <label>Quantity</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

peac_dev/force-app/main/default/objects/Asset__c/fields/Usage_Dealer_Invoice_Number__c.field-meta.xml
<CustomField>
    <fullName>Usage_Dealer_Invoice_Number__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Usage - Dealer Invoice #</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

peac_dev/force-app/main/default/classes/PEAC_PurchaseOrderControllerTest.cls
/***********************************************************************************************************************
@Author: Vinod Rathod (LTIMindtree)
@Description: This test class validates the PEAC_PurchaseOrderController logic for creating Purchase orders from Assets
grouped by Customer PO number.
@User Story: SAL-6375
@Created Date: JAN-28-2026
*************************************************************************************************************************/
@IsTest
public class PEAC_PurchaseOrderControllerTest {
    @TestSetup
    public static void setupAssetTest () {
        //Create Account
        Account acc = new Account (Name = 'test');
        insert acc;
        //Create Opportunity
        Opportunity opp = new Opportunity (CloseDate = Date.today()+10,Name='test',AccountId=acc.Id,Equipment_Cost__c=50000,StageName='Decision',Contract_Type__c='TL');
        insert opp;
        //Create Asset with Same Customer PO Number
        List <Asset__c> assetList = new List <Asset__c>();
        assetList.add(new Asset__c (End_User_Billing_Address__c = true, Quantity__c = 1, Equipment_Code__c = 'ATM',Usage_Dealer_Invoice_Number__c ='INV-01',
                                    Customer_PO_Number__c = 'PO-001',Equipment_Sub_Category__c = 'ATM', Opportunity__c = opp.Id));
        assetList.add(new Asset__c (End_User_Billing_Address__c = true, Quantity__c = 1, Equipment_Code__c = 'ATM',Usage_Dealer_Invoice_Number__c ='INV-01',
                                    Customer_PO_Number__c = 'PO-001',Equipment_Sub_Category__c = 'ATM', Opportunity__c = opp.Id));
        
        
        //Create Asset with Different Customer PO Number
        assetList.add(new Asset__c (End_User_Billing_Address__c = true, Quantity__c = 1, Equipment_Code__c = 'ATM',Usage_Dealer_Invoice_Number__c ='INV-02',
                                    Customer_PO_Number__c = 'PO-002',Equipment_Sub_Category__c = 'ATM', Opportunity__c = opp.Id));
        insert assetList;
        //Existing Purchase Order (duplicate previntion case)
        Purchase_Order__c existingPurchaseOrder= new Purchase_Order__c();
        existingPurchaseOrder.Customer_PO_Number__c = 'PO-002';
        existingPurchaseOrder.Opportunity__c = opp.Id;
        insert existingPurchaseOrder;
        
    }
    
    @IsTest
    public static void testCreatePurchaseOrders(){
        Test.startTest();
        Opportunity opportunity = [SELECT Id FROM Opportunity LIMIT 1];
        String result = PEAC_PurchaseOrderController.createPurchaseOrders(opportunity.Id);
        
        // Verify Purchase Orders
        List<Purchase_Order__c> purchaseOrderList = [SELECT Id, Customer_PO_Number__c FROM Purchase_Order__c
                                                     WHERE Opportunity__c = :opportunity.Id 
                                                    ];
        // Verify Assets updated with PO lookup
        List<Asset__c> updatedAssets = [SELECT Id, Customer_PO_Number__c, Purchase_Order__c FROM Asset__c
                                        WHERE Opportunity__c = :opportunity.Id 
                                       ];
        Test.stopTest();
        system.debug('updatedAssets ---'+updatedAssets);
        system.debug('purchaseOrderList ---'+purchaseOrderList);
        
        system.assertEquals('Purchase Orders created successfully.',result,'Success message should be returned');
        system.assertEquals(2, purchaseOrderList.size(), 'Two Purchase Order should exist');
    }    
}