peac_dev/force-app/main/default/objects/Asset__c/Asset__c.object-meta.xml
<CustomObject>
    <label>Asset</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Asset Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Assets</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

peac_dev/force-app/main/default/objects/Asset__c/fields/Cost__c.field-meta.xml
<CustomField>
    <fullName>Cost__c</fullName>
    <inlineHelpText>Value will default from Opportunity on First Asset</inlineHelpText>
    <label>Cost</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

peac_dev/force-app/main/default/objects/Asset__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Value will default from Opportunity on First Asset</inlineHelpText>
    <label>Description</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

peac_dev/force-app/main/default/objects/Asset__c/fields/End_User_Billing_Address__c.field-meta.xml
<CustomField>
    <fullName>End_User_Billing_Address__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Want to utilize the Business address from the opportunity? If yes, check this box and select save. If not, provide the alternative address.</inlineHelpText>
    <label>End User Business Address?</label>
    <type>Checkbox</type>
</CustomField>

peac_dev/force-app/main/default/objects/Asset__c/fields/Equipment_City__c.field-meta.xml
<CustomField>
    <fullName>Equipment_City__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Equipment City</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

peac_dev/force-app/main/default/objects/Asset__c/fields/Equipment_Code__c.field-meta.xml
<CustomField>
    <fullName>Equipment_Code__c</fullName>
    <label>Equipment Code</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Asset_Equipment_Code</valueSetName>
    </valueSet>
</CustomField>

peac_dev/force-app/main/default/objects/Asset__c/fields/Equipment_State__c.field-meta.xml
<CustomField>
    <fullName>Equipment_State__c</fullName>
    <label>Equipment State</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>AL</fullName>
            </value>
            <value>
                <fullName>AK</fullName>
            </value>
            <value>
                <fullName>AS</fullName>
            </value>
            <value>
                <fullName>AZ</fullName>
            </value>
            <value>
                <fullName>AR</fullName>
            </value>
            <value>
                <fullName>CA</fullName>
            </value>
            <value>
                <fullName>CO</fullName>
            </value>
            <value>
                <fullName>CT</fullName>
            </value>
            <value>
                <fullName>DE</fullName>
            </value>
            <value>
                <fullName>DC</fullName>
            </value>
            <value>
                <fullName>FL</fullName>
            </value>
            <value>
                <fullName>GA</fullName>
            </value>
            <value>
                <fullName>GU</fullName>
            </value>
            <value>
                <fullName>HI</fullName>
            </value>
            <value>
                <fullName>ID</fullName>
            </value>
            <value>
                <fullName>IL</fullName>
            </value>
            <value>
                <fullName>IN</fullName>
            </value>
            <value>
                <fullName>IA</fullName>
            </value>
            <value>
                <fullName>KS</fullName>
            </value>
            <value>
                <fullName>KY</fullName>
            </value>
            <value>
                <fullName>LA</fullName>
            </value>
            <value>
                <fullName>ME</fullName>
            </value>
            <value>
                <fullName>MD</fullName>
            </value>
            <value>
                <fullName>MH</fullName>
            </value>
            <value>
                <fullName>MA</fullName>
            </value>
            <value>
                <fullName>MI</fullName>
            </value>
            <value>
                <fullName>FM</fullName>
            </value>
            <value>
                <fullName>MN</fullName>
            </value>
            <value>
                <fullName>MS</fullName>
            </value>
            <value>
                <fullName>MO</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

peac_dev/force-app/main/default/objects/Asset__c/fields/Equipment_Street__c.field-meta.xml
<CustomField>
    <fullName>Equipment_Street__c</fullName>
    <defaultValue>&quot;&quot;</defaultValue>
    <encryptionScheme>None</encryptionScheme>
    <label>Equipment Street</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

peac_dev/force-app/main/default/objects/Asset__c/fields/Equipment_Zip__c.field-meta.xml
<CustomField>
    <fullName>Equipment_Zip__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Equipment Zip</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

peac_dev/force-app/main/default/objects/Asset__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipName>Assets</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

peac_dev/force-app/main/default/objects/Asset__c/fields/Quantity__c.field-meta.xml
<CustomField>
    <fullName>Quantity__c</fullName>
    <defaultValue>1</defaultValue>
    <label>Quantity</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

peac_dev/force-app/main/default/objects/Bridgeware_Service_Setting__c/Bridgeware_Service_Setting__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Various settings for Bridgeware Service</description>
    <label>Bridgeware Service Setting</label>
</CustomObject>

peac_dev/force-app/main/default/objects/Bridgeware_Service_Setting__c/fields/Config_Name__c.field-meta.xml
<CustomField>
    <fullName>Config_Name__c</fullName>
    <defaultValue>&quot;DEMO&quot;</defaultValue>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>CONFIG-NAME Parameter that specifies database name to connect to</inlineHelpText>
    <label>Config Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

peac_dev/force-app/main/default/objects/Bridgeware_Service_Setting__c/fields/Enable_Debug_Log__c.field-meta.xml
<CustomField>
    <fullName>Enable_Debug_Log__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Enable Debug Log</label>
    <type>Checkbox</type>
</CustomField>

peac_dev/force-app/main/default/objects/Bridgeware_Service_Setting__c/fields/Mock_Callout__c.field-meta.xml
<CustomField>
    <fullName>Mock_Callout__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Mock Callout</label>
    <type>Checkbox</type>
</CustomField>

peac_dev/force-app/main/default/objects/Bridgeware_Service_Setting__c/fields/Mock_Endpoint__c.field-meta.xml
<CustomField>
    <fullName>Mock_Endpoint__c</fullName>
    <defaultValue>&quot;http://www.mocky.io/v2/54fe5204862a3ae70ddc9617&quot;</defaultValue>
    <description>Something like http://www.mocky.io/v2/54fe5204862a3ae70ddc9617 or http://requestb.in/</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Something like http://www.mocky.io/v2/54fe5204862a3ae70ddc9617 or http://requestb.in/

DO NOT FORGET TO ADD REMOTE SITE SETTINGS!</inlineHelpText>
    <label>Mock Endpoint</label>
    <type>Url</type>
</CustomField>

peac_dev/force-app/main/default/classes/TestFirstAssetOnOpportunity.cls
@isTest

Public class TestFirstAssetOnOpportunity
{

    @testSetup public static void setupTest () {
    
        Bridgeware_Service_Setting__c setting = new Bridgeware_Service_Setting__c ();
        setting.Enable_Debug_Log__c = true;
        setting.Mock_Callout__c = true;
        setting.Mock_Endpoint__c = 'https://private-b2bb6-bridgewaretamarack.apiary-mock.com/';
        setting.SetupOwnerId = UserInfo.getOrganizationId ();
        setting.Config_Name__c = 'TEST';
        insert setting;
        
        Test.setMock(HttpCalloutMock.class, new TC_BridgewareBookContractCalloutMockImpl ());
        
        String accntid = '';
        RecordType accrectypeid = [select id from RecordType where DeveloperName = 'End_User'];
        if(accrectypeid <> null)
        {
            Account acc = new Account();
            acc.RecordTypeId = accrectypeid.id;
            acc.Name = 'Test Account';
            
            if(acc <> null)
            {
            insert acc;
            }
            accntid = acc.id;
        }

        //RecordType optyrectypeid = [select id from RecordType where DeveloperName = 'Franchise_Quote'];
        //if(optyrectypeid <> null)
        //{
            Opportunity opty = new Opportunity();
            //opty.RecordTypeId = optyrectypeid.id;
            opty.Name = 'Testing Trigger Opportunity Franchise';
            opty.AccountId = accntid;
            opty.StageName = 'Quote';
            opty.CloseDate = system.today() + 10;
            opty.Account_Business_City__c = 'city';
            opty.Account_Business_Street__c= 'street';
            opty.Account_Business_State_Province__c= 'IL';
            opty.Account_Business_Zip_Postal_Code__c= '678909';
           
            
            if(opty <> null)
            {
                insert opty;
            }
    
           //}
    }
    
    @isTest
    static void updOppMock() {
        
        	Opportunity opty = [SELECT id from opportunity][0];
       
            Asset__c newAsset = new Asset__c ();
            newAsset.Quantity__c = 5;
            newAsset.Opportunity__c = opty.id;
            newAsset.Equipment_Code__c = 'ATM';
            newAsset.Description__c = 'Testing';
            newAsset.Cost__c = 1234;
            newAsset.Equipment_Street__c = 'CMC Street';
            newAsset.Equipment_City__c = 'Chicago';
            newAsset.Equipment_State__c = 'IL';
            newAsset.Equipment_Zip__c = '60607';
            
            if (newAsset <> null)
            {
                Test.starttest();
	            Test.setMock(HttpCalloutMock.class, new TC_BridgewareBookContractCalloutMockImpl ());
                insert newAsset;        
                Test.stoptest();
            }
    }
    
    /*
    @isTest
    static void testAssertTrigger()
    {
            Opportunity opty = [SELECT id from opportunity][0];
            
            Asset__c newAsset = new Asset__c ();
            newAsset.Quantity__c = 5;
            newAsset.Opportunity__c = opty.id;
            newAsset.Equipment_Code__c = 'ATM';
            newAsset.Description__c = 'Testing';
            newAsset.Cost__c = 1234;
            newAsset.Equipment_Street__c = 'CMC Street';
            newAsset.Equipment_City__c = 'Chicago';
            newAsset.Equipment_State__c = 'IL';
            newAsset.Equipment_Zip__c = '60607';            
            
            if (newAsset <> null)
            {
                insert newAsset;
            }
            
            
            
            newAsset.Equipment_City__c = 'city';
            newAsset.Equipment_Street__c = 'street';
            newAsset.Equipment_State__c = 'IL';
            newAsset.Equipment_Zip__c ='387450';
            update newAsset;
            
            // split
            Test.setMock(HttpCalloutMock.class, new TC_BridgewareBookContractCalloutMockImpl ());
            Test.starttest();
            
            
            Asset__c newAsset1 = new Asset__c ();
            newAsset1.Quantity__c = 5;
            newAsset1.Opportunity__c = opty.id;
            newAsset1.Equipment_Code__c = 'ATM';
            newAsset1.Description__c = 'Testing';
            newAsset1.Cost__c = 1234;
            newAsset1.Equipment_Street__c = 'CMC Street';
            newAsset1.Equipment_City__c = 'Chicago';
            newAsset1.Equipment_State__c = 'IL';
            newAsset1.Equipment_Zip__c = '60607';            
            
            if (newAsset1 <> null)
            {
                insert newAsset1;
            }
            
          newAsset1.End_User_Billing_Address__c = true;
          delete newAsset1;
       
           Test.stoptest(); 
            
        }*/
    
    
}