peac_dev/force-app/main/default/objects/Asset__c/Asset__c.object-meta.xml
<CustomObject>
    <label>Asset</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Asset Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Assets</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

peac_dev/force-app/main/default/objects/Asset__c/fields/Cost__c.field-meta.xml
<CustomField>
    <fullName>Cost__c</fullName>
    <inlineHelpText>Value will default from Opportunity on First Asset</inlineHelpText>
    <label>Cost</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

peac_dev/force-app/main/default/objects/Asset__c/fields/End_User_Billing_Address__c.field-meta.xml
<CustomField>
    <fullName>End_User_Billing_Address__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Want to utilize the Business address from the opportunity? If yes, check this box and select save. If not, provide the alternative address.</inlineHelpText>
    <label>End User Business Address?</label>
    <type>Checkbox</type>
</CustomField>

peac_dev/force-app/main/default/objects/Asset__c/fields/Equipment_Code__c.field-meta.xml
<CustomField>
    <fullName>Equipment_Code__c</fullName>
    <label>Equipment Code</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Asset_Equipment_Code</valueSetName>
    </valueSet>
</CustomField>

peac_dev/force-app/main/default/objects/Asset__c/fields/Equipment_Sub_Category__c.field-meta.xml
<CustomField>
    <fullName>Equipment_Sub_Category__c</fullName>
    <label>Equipment Sub-Category</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Equipment_Code__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>Equipment_Sub_Category</valueSetName>
    </valueSet>
</CustomField>

peac_dev/force-app/main/default/objects/Asset__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipName>Assets</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

peac_dev/force-app/main/default/objects/Asset__c/fields/Opportunity_Contract_Type__c.field-meta.xml
<CustomField>
    <fullName>Opportunity_Contract_Type__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Opportunity Contract Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

peac_dev/force-app/main/default/objects/Asset__c/fields/Quantity__c.field-meta.xml
<CustomField>
    <fullName>Quantity__c</fullName>
    <defaultValue>1</defaultValue>
    <label>Quantity</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

peac_dev/force-app/main/default/objects/Asset__c/fields/Usage_User_Table__c.field-meta.xml
<CustomField>
    <fullName>Usage_User_Table__c</fullName>
    <label>Tax Exempt Certificate</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
                <label>Requested</label>
            </value>
            <value>
                <fullName>2</fullName>
                <label>Received</label>
            </value>
            <value>
                <fullName>3</fullName>
                <label>Exempt Equipment</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

peac_dev/force-app/main/default/objects/Marlin_Configuration__c/Marlin_Configuration__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Marlin Configuration</label>
</CustomObject>

peac_dev/force-app/main/default/objects/Marlin_Configuration__c/fields/Disable_Standard_Asset_Generation__c.field-meta.xml
<CustomField>
    <fullName>Disable_Standard_Asset_Generation__c</fullName>
    <defaultValue>false</defaultValue>
    <description>When this checkbox is checked, a standard asset is not created for each custom asset object. The standard assets are being created for the CSC UCC Filing Integration</description>
    <inlineHelpText>When this checkbox is checked, a standard asset is not created for each custom asset object. The standard assets are being created for the CSC UCC Filing Integration</inlineHelpText>
    <label>Disable Standard Asset Generation</label>
    <type>Checkbox</type>
</CustomField>

peac_dev/force-app/main/default/classes/PEAC_LeaseCalculationServiceTest.cls
@isTest 
public class PEAC_LeaseCalculationServiceTest {
    
    @TestSetup
    public static void setupAssetTest () {
		PEAC_GenerateTaxMatrixBatch.isRunning = true;
        Account acc = new Account (Name = 'test');
        insert acc;
        Opportunity opp = new Opportunity (CloseDate = Date.today()+10,Name='test',AccountId=acc.Id,Equipment_Cost__c=50000,StageName='Decision',
                                           Account_Business_Street__c='208 East 58th St' , Account_Business_City__c ='New York',Account_Business_State_Province__c ='NY' , 
                                           Account_Business_Zip_Postal_Code__c='10022',Hard_Lease_Rate_Factor__c = 0.05,Soft_Lease_Rate_Factor__c = 0.10 );
        insert opp;
        insert new Asset__c (End_User_Billing_Address__c = true, Quantity__c = 1, Equipment_Code__c = 'ATM',Opportunity_Contract_Type__c='TL',
                             Usage_User_Table__c = '1',Equipment_Sub_Category__c = 'ATM', Opportunity__c = opp.Id, Cost__c = 0);
        
        insert new Marlin_Configuration__c(Disable_Standard_Asset_Generation__c = false);
    }
    
    @IsTest
    public static void updateAssetsFromOpportunityAsyncTest(){
        PEAC_GenerateTaxMatrixBatch.isRunning = true;
        
        Opportunity opp = [ SELECT Id, Hard_Lease_Rate_Factor__c, Soft_Lease_Rate_Factor__c  FROM Opportunity ];
        Set<Id> oppIds = new Set<Id>{opp.Id};
        
        Test.startTest();
        PEAC_LeaseCalculationService.updateAssetsFromOpportunityAsync(oppIds);
        Test.stopTest();
                       
    }

}