peac_dev/force-app/main/default/objects/Asset__c/Asset__c.object-meta.xml
<CustomObject>
    <label>Asset</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Asset Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Assets</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

peac_dev/force-app/main/default/objects/Asset__c/fields/End_User_Billing_Address__c.field-meta.xml
<CustomField>
    <fullName>End_User_Billing_Address__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Want to utilize the Business address from the opportunity? If yes, check this box and select save. If not, provide the alternative address.</inlineHelpText>
    <label>End User Business Address?</label>
    <type>Checkbox</type>
</CustomField>

peac_dev/force-app/main/default/objects/Asset__c/fields/Equipment_Code__c.field-meta.xml
<CustomField>
    <fullName>Equipment_Code__c</fullName>
    <label>Equipment Code</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Asset_Equipment_Code</valueSetName>
    </valueSet>
</CustomField>

peac_dev/force-app/main/default/objects/Asset__c/fields/Equipment_Sub_Category__c.field-meta.xml
<CustomField>
    <fullName>Equipment_Sub_Category__c</fullName>
    <label>Equipment Sub-Category</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Equipment_Code__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>Equipment_Sub_Category</valueSetName>
    </valueSet>
</CustomField>

peac_dev/force-app/main/default/objects/Asset__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipName>Assets</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

peac_dev/force-app/main/default/objects/Asset__c/fields/Quantity__c.field-meta.xml
<CustomField>
    <fullName>Quantity__c</fullName>
    <defaultValue>1</defaultValue>
    <label>Quantity</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

peac_dev/force-app/main/default/objects/Asset__c/fields/Usage_Dealer_Invoice_Number__c.field-meta.xml
<CustomField>
    <fullName>Usage_Dealer_Invoice_Number__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Usage - Dealer Invoice #</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

peac_dev/force-app/main/default/classes/PEAC_CSVFileDownloadControllerTest.cls
/********************************************************************************************************************
@Description: This test class validates The PEAC_CSVFileDownloadController generic calss to generate csv file 
from salesforce objects.
@Author: Vinod Rathod (LTIMindtree)
@User Story: SAL-6229
@Created Date: Feb-26-2026
*********************************************************************************************************************/
@isTest
public class PEAC_CSVFileDownloadControllerTest {
    @TestSetup
    public static void setupAssetTest () {
        //Create Account
        Account acc = new Account (Name = 'test');
        insert acc;
        PEAC_GenerateTaxMatrixBatch.isRunning = true;
        //Create a parent record Opportunity
        Opportunity opp = new Opportunity (CloseDate = Date.today()+10,Name='test',AccountId=acc.Id,Equipment_Cost__c=50000,
                                           StageName='Decision',Contract_Type__c='TL');
        insert opp;
        test.startTest();
        //Create child records (Assets) linked to that Opportunity  
        List <Asset__c> assetList = new List <Asset__c>();
        assetList.add(new Asset__c (End_User_Billing_Address__c = true, Quantity__c = 1, Equipment_Code__c = 'ATM',Usage_Dealer_Invoice_Number__c ='INV-01',
                                    Customer_PO_Number__c = 'PO-001',Equipment_Sub_Category__c = 'ATM', Opportunity__c = opp.Id));
        
       insert assetList; 
       test.StopTest();
    }
    
    @isTest
    static void testGetRecords() {
        // Retrieve the test Opportunity
        Opportunity opportunity = [SELECT Id FROM Opportunity LIMIT 1];
        
        // Define parameters for the dynamic query
        String objName = 'Asset__c';
        List<String> fieldList = new List<String>{'Id', 'End_User_Billing_Address__c', 'Quantity__c','Equipment_Code__c','Usage_Dealer_Invoice_Number__c','Customer_PO_Number__c'};
        String parentField = 'Opportunity__c';
        
        Test.startTest();
        List<SObject> results = PEAC_CSVFileDownloadController.getRecords(objName, fieldList, parentField, opportunity.Id);
        Test.stopTest();
        
        // Assertions: verify the result is not null and contains the expected number of records
        Assert.isNotNull(results, 'The result list should not be null.');
        Assert.areEqual(1, results.size(), 'Should return exactly 1 Assets linked to the Opportunity.');
    }
    
}