peac_dev/force-app/main/default/objects/Asset__c/Asset__c.object-meta.xml
<CustomObject>
    <label>Asset</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Asset Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Assets</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

peac_dev/force-app/main/default/objects/Asset__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipName>Assets</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

peac_dev/force-app/main/default/objects/Miscellaneous_Billable_Item__c/Miscellaneous_Billable_Item__c.object-meta.xml
<CustomObject>
    <label>Miscellaneous Billable Item</label>
    <nameField>
        <displayFormat>MB-{0}</displayFormat>
        <label>Miscellaneous Billable Item Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Miscellaneous Billable Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

peac_dev/force-app/main/default/objects/Miscellaneous_Billable_Item__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <inlineHelpText>Opportunity related to this Misc Billable</inlineHelpText>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Misc Billables</relationshipLabel>
    <relationshipName>Miscellaneous_Billable_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

peac_dev/force-app/main/default/objects/Miscellaneous_Invoice_Item__c/Miscellaneous_Invoice_Item__c.object-meta.xml
<CustomObject>
    <label>Miscellaneous Invoice Item</label>
    <nameField>
        <displayFormat>MI-{0}</displayFormat>
        <label>Miscellaneous Invoice Item Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Miscellaneous Invoice Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

peac_dev/force-app/main/default/objects/Miscellaneous_Invoice_Item__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <inlineHelpText>Opportunity related to this Misc Invoice Item.</inlineHelpText>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Misc Invoices</relationshipLabel>
    <relationshipName>Miscellaneous_Invoice_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

peac_dev/force-app/main/default/classes/PEAC_MixedObjIterator.cls
/**************************************************************************************************************
@Author: Chalapati Murru (LTIMindtree)
@Description: This class is used to Generate Tax Matrix for bulk processing multiple object types
@User Story: SAL-5692 Expo: Opportunity Refactor
@Created Date: Nov-10-2025
**************************************************************************************************************/
public class PEAC_MixedObjIterator implements Iterator<PEAC_MixedObjWrapper>{
	private Integer index = 0;
    private List<PEAC_MixedObjWrapper> records;
    
    public PEAC_MixedObjIterator(Set<Id> oppIds){
        records = new List<PEAC_MixedObjWrapper>();
        //Fetch Asset__c
        for(Asset__c asset : [SELECT Id, Opportunity__c FROM Asset__c WHERE Opportunity__c IN: oppIds]){
            records.add(new PEAC_MixedObjWrapper('Asset__c',asset));
        }
        //Fetch Miscellaneous_Billable_Item__c
        for(Miscellaneous_Billable_Item__c mbItem : [SELECT Id, Opportunity__c FROM Miscellaneous_Billable_Item__c WHERE Opportunity__c IN: oppIds]){
            records.add(new PEAC_MixedObjWrapper('Miscellaneous_Billable_Item__c',mbItem));
        }
        //Fetch Miscellaneous_Invoice_Item__c
		for(Miscellaneous_Invoice_Item__c miItem : [SELECT Id, Opportunity__c FROM Miscellaneous_Invoice_Item__c WHERE Opportunity__c IN: oppIds]){
            records.add(new PEAC_MixedObjWrapper('Miscellaneous_Invoice_Item__c',miItem));
        }
    }
    
    public Boolean hasNext(){
        return index < records.size();
    }
    
    public PEAC_MixedObjWrapper next(){
        if(!hasNext()){
            throw new NoSuchElementException('No more records');
        }
        return records[index++];
    }
}