peac_dev/force-app/main/default/objects/Asset__c/Asset__c.object-meta.xml
<CustomObject>
    <label>Asset</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Asset Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Assets</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

peac_dev/force-app/main/default/objects/Asset__c/fields/Asset_Description__c.field-meta.xml
<CustomField>
    <fullName>Asset_Description__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Detailed Equipment Description</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

peac_dev/force-app/main/default/objects/Asset__c/fields/Cost__c.field-meta.xml
<CustomField>
    <fullName>Cost__c</fullName>
    <inlineHelpText>Value will default from Opportunity on First Asset</inlineHelpText>
    <label>Cost</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

peac_dev/force-app/main/default/objects/Asset__c/fields/Equipment_Code__c.field-meta.xml
<CustomField>
    <fullName>Equipment_Code__c</fullName>
    <label>Equipment Code</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Asset_Equipment_Code</valueSetName>
    </valueSet>
</CustomField>

peac_dev/force-app/main/default/objects/Asset__c/fields/Manufacturer__c.field-meta.xml
<CustomField>
    <fullName>Manufacturer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Store Manufacturer name from account where Type is M.</description>
    <label>Manufacturer</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Dealer Account Type should be as Manufacturer</errorMessage>
        <filterItems>
            <field>Account.Type</field>
            <operation>equals</operation>
            <value>Manufacturer</value>
        </filterItems>
        <filterItems>
            <field>Account.Dealer_Number__c</field>
            <operation>notEqual</operation>
            <value></value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Assets</relationshipLabel>
    <relationshipName>Asset_Manufacturer</relationshipName>
    <type>Lookup</type>
</CustomField>

peac_dev/force-app/main/default/objects/Asset__c/fields/Model__c.field-meta.xml
<CustomField>
    <fullName>Model__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Model</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

peac_dev/force-app/main/default/objects/Asset__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipName>Assets</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

peac_dev/force-app/main/default/objects/Asset__c/fields/Serial_Number__c.field-meta.xml
<CustomField>
    <fullName>Serial_Number__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Serial Number</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

peac_dev/force-app/main/default/classes/SL_DPOffers.cls
public with sharing class SL_DPOffers {
    @AuraEnabled(cacheable=true)
    public static string hubExecute(String methodName, List<String> parameters){
        String result = '';
        try {
            switch on methodName {
                when 'getAssets'{
                    result = getAssets(parameters[0]);
                }
            }
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
        return result;
    }

    static string getAssets(Id OpportunityId){
        Opportunity oppInfo = [SELECT Account_Billing_State_Province__c, EF_Approved_Offers__r.Monthly_Payment__c, EF_Approved_Offers__r.Rate_Factor__c,Offer_Rate_Factor__c, StageName FROM Opportunity WHERE Id = :OpportunityId];
        //SAL-4968
        List<Asset__c> assets = [SELECT Id, Name, Asset_Description__c, Cost__c, Equipment_Code__c, Manufacturer__c, Model__c,Serial_Number__c FROM Asset__c WHERE Opportunity__c = :OpportunityId];
        //List<Asset__c> assets = [SELECT Id, Name, Asset_Description__c, Cost__c, Equipment_Code__c, Model__c,Serial_Number__c FROM Asset__c WHERE Opportunity__c = :OpportunityId];
        
        return '{"oppInfo": ' + JSON.serialize(oppInfo) + ', "assets": ' + JSON.serialize(assets) + '}';
    }

}