peac_dev/force-app/main/default/objects/Asset__c/Asset__c.object-meta.xml
<CustomObject>
    <label>Asset</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Asset Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Assets</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

peac_dev/force-app/main/default/objects/Asset__c/fields/Equipment_City__c.field-meta.xml
<CustomField>
    <fullName>Equipment_City__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Equipment City</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

peac_dev/force-app/main/default/objects/Asset__c/fields/Equipment_Street__c.field-meta.xml
<CustomField>
    <fullName>Equipment_Street__c</fullName>
    <defaultValue>&quot;&quot;</defaultValue>
    <encryptionScheme>None</encryptionScheme>
    <label>Equipment Street</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

peac_dev/force-app/main/default/objects/Asset__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipName>Assets</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

peac_dev/force-app/main/default/objects/Asset__c/fields/Purchase_Options__c.field-meta.xml
<CustomField>
    <fullName>Purchase_Options__c</fullName>
    <formula>TEXT(Opportunity__r.Purchase_Options__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Purchase option from deal defaulted to asset</inlineHelpText>
    <label>Purchase Option</label>
    <type>Text</type>
</CustomField>

peac_dev/force-app/main/default/objects/Blended_Income_Item__c/Blended_Income_Item__c.object-meta.xml
<CustomObject>
    <label>Blended Income Item</label>
    <nameField>
        <displayFormat>BI-{0}</displayFormat>
        <label>Blended Income Item Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Blended Income Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

peac_dev/force-app/main/default/objects/Blended_Income_Item__c/fields/Begin_Date__c.field-meta.xml
<CustomField>
    <fullName>Begin_Date__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Begin Date</label>
    <type>Date</type>
</CustomField>

peac_dev/force-app/main/default/objects/Blended_Income_Item__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <inlineHelpText>Opportunity related to this Blended Income Item</inlineHelpText>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Blended Income Items</relationshipLabel>
    <relationshipName>Blended_Income_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

peac_dev/force-app/main/default/classes/PEAC_UpdateAssetsBlenIncItemAsyncTest.cls
/*************************************************************************************************************************
@Author: Chalapati Murru (LTIMindtree)
@Description: This test class is used for PEAC_UpdateAssetsBlenIncItemAsync code coverage
@User Story: SAL-5692 Expo: Opportunity Refactor
@Created Date: Jan-30-2026
*************************************************************************************************************************/
@IsTest(seeAllData=false)
public class PEAC_UpdateAssetsBlenIncItemAsyncTest {
	private static Opportunity makeOpp(
        String name,
        Boolean loanRecordType,
        String stage,
        Decimal totalPaymentsSent,
        Decimal totalPaymentsSentLoan,
        DateTime bookedDt,
        Date commencementDt,
        Decimal floridaSum,
        String purchaseOptions,
        Boolean readyToDoc,
        Boolean manualFunding,
        Decimal secDeposit
    ) {
        Opportunity o = new Opportunity(
            Name = name,
            StageName = stage,
            Opportunity_Booked_Date__c = bookedDt,
            Commencement_Date__c = commencementDt,
            Purchase_Options__c = purchaseOptions,
            Ready_to_Doc__c = readyToDoc ? PEAC_ConstantClass.Yes : PEAC_ConstantClass.No,
            Manual_Funding__c = manualFunding,
            Security_Deposit__c = secDeposit,
            closeDate = DateTime.now().Date()
        );
        Account acc = TestDataFactory.createTestAccount();
        Contact con = TestDataFactory.createTestContact(acc.Id);
        Opportunity opp = TestDataFactory.createTestOpp(acc.Id);
        return opp;
    }
    
    private static Asset__c makeAsset(Id oppId, String street, String city, String state, String zip) {
        Asset__c a = new Asset__c(
            Opportunity__c = oppId,
            Equipment_Street__c = street,
            Equipment_City__c = city
        );
        insert a;
        return a;
    }
    
    private static Blended_Income_Item__c makeBII(Id oppId) {
        Blended_Income_Item__c b = new Blended_Income_Item__c(
            Opportunity__c = oppId
        );
        insert b;
        return b;
    }
    
    @IsTest static void bookedDateUpdatesBII_Test() {
        Opportunity o = makeOpp('Opp-01', false, PEAC_ConstantClass.OPPORTUNITY_STAGENAME_BOOKING,
                                0.0, 0.0, DateTime.now(), (Date)null, 0.0, (String)null, false, false,0.0);
        
        Blended_Income_Item__c bii = makeBII(o.Id);
        Map<Id, Opportunity> newMap = new Map<Id, Opportunity>{ o.Id => o };

        Test.startTest();
        o.Commencement_Date__c = DateTime.now().Date();
        update o;
        Test.stopTest();

        bii = [SELECT Begin_Date__c FROM Blended_Income_Item__c WHERE Id = :bii.Id];
        System.assertEquals(o.Commencement_Date__c, bii.Begin_Date__c, 'BII booking date should match Opp Commencement_Date__c');
    }
    
    @IsTest static void assetsQueueableTest() {
        Opportunity o = makeOpp('Opp-01', false, PEAC_ConstantClass.OPPORTUNITY_STAGENAME_BOOKING,
                                0.0, 0.0, DateTime.now(), (Date)null, 0.0, (String)null, false, false,0.0);
        
		makeAsset(o.Id, '1 Main', 'CityA', 'AL', '12345');
        Test.startTest();
        o.Opportunity_Booked_Date__c = DateTime.now().Date();
        update o;
        Test.stopTest();
	}
    
}