peac_dev/force-app/main/default/objects/Asset__c/Asset__c.object-meta.xml
<CustomObject>
    <label>Asset</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Asset Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Assets</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

peac_dev/force-app/main/default/objects/Asset__c/fields/City_Code__c.field-meta.xml
<CustomField>
    <fullName>City_Code__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>City Location Code</label>
    <length>4</length>
    <type>Text</type>
</CustomField>

peac_dev/force-app/main/default/objects/Asset__c/fields/County_Code__c.field-meta.xml
<CustomField>
    <fullName>County_Code__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>County Location Code</label>
    <length>3</length>
    <type>Text</type>
</CustomField>

peac_dev/force-app/main/default/objects/Asset__c/fields/Equipment_Zip__c.field-meta.xml
<CustomField>
    <fullName>Equipment_Zip__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Equipment Zip</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

peac_dev/force-app/main/default/objects/Asset__c/fields/State_Code__c.field-meta.xml
<CustomField>
    <fullName>State_Code__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>State Code Returned from Vertex</inlineHelpText>
    <label>State Location Code</label>
    <length>6</length>
    <type>Text</type>
</CustomField>

peac_dev/force-app/main/default/objects/Asset__c/fields/Tax_Zip_Updated__c.field-meta.xml
<CustomField>
    <fullName>Tax_Zip_Updated__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Tax Zip Updated</label>
    <type>Checkbox</type>
</CustomField>

peac_dev/force-app/main/default/objects/County__c/County__c.object-meta.xml
<CustomObject>
    <label>County</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>County</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Counties</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

peac_dev/force-app/main/default/objects/County__c/fields/State__c.field-meta.xml
<CustomField>
    <fullName>State__c</fullName>
    <label>State</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>State_Code</valueSetName>
    </valueSet>
</CustomField>

peac_dev/force-app/main/default/objects/IL10_Flag__c/IL10_Flag__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Setting to indicate whether or not the Infolease integration classes should process logic to dewtermine if records update IL9 or IL 10. Used primarily as a backout mechanism.</description>
    <label>IL10 Flag</label>
</CustomObject>

peac_dev/force-app/main/default/objects/IL10_Flag__c/fields/use_IL10__c.field-meta.xml
<CustomField>
    <fullName>use_IL10__c</fullName>
    <defaultValue>true</defaultValue>
    <description>to restrict the IL10 when needed</description>
    <label>use IL10</label>
    <type>Checkbox</type>
</CustomField>

peac_dev/force-app/main/default/objects/Rate__c/Rate__c.object-meta.xml
<CustomObject>
    <label>Rate</label>
    <nameField>
        <displayFormat>R-{0000}</displayFormat>
        <label>Rate Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Rates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

peac_dev/force-app/main/default/objects/Rate__c/fields/City__c.field-meta.xml
<CustomField>
    <fullName>City__c</fullName>
    <description>The city where the business is located.</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>The city where the business is located.</inlineHelpText>
    <label>City</label>
    <length>64</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

peac_dev/force-app/main/default/objects/Rate__c/fields/City_Code__c.field-meta.xml
<CustomField>
    <fullName>City_Code__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>City Code</label>
    <length>16</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

peac_dev/force-app/main/default/objects/Rate__c/fields/County__c.field-meta.xml
<CustomField>
    <fullName>County__c</fullName>
    <description>The county the business is located in.</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>The county the business is located in.</inlineHelpText>
    <label>County</label>
    <length>64</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

peac_dev/force-app/main/default/objects/Rate__c/fields/County_Code__c.field-meta.xml
<CustomField>
    <fullName>County_Code__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>County Code</label>
    <length>16</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

peac_dev/force-app/main/default/objects/Rate__c/fields/Rate_Code__c.field-meta.xml
<CustomField>
    <fullName>Rate_Code__c</fullName>
    <description>Field that store the code of the tax type.</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Enter the tax type code.</inlineHelpText>
    <label>Rate Code</label>
    <length>16</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

peac_dev/force-app/main/default/objects/Rate__c/fields/State__c.field-meta.xml
<CustomField>
    <fullName>State__c</fullName>
    <description>State your business is located in.</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>State your business is located in.</inlineHelpText>
    <label>State</label>
    <length>64</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

peac_dev/force-app/main/default/objects/Rate__c/fields/State_Code__c.field-meta.xml
<CustomField>
    <fullName>State_Code__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>State Code</label>
    <length>16</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

peac_dev/force-app/main/default/classes/PEAC_BridgewareSelectZipGeoCodes.cls
/**************************************************************************************************************
@Author: Chalapati Murru (LTIMindtree)
@Description: This class is used to call create Zip Geo Code to process multiple assets at once.
@User Story: SAL-5692 Expo: Opportunity Refactor
@Created Date: 01-Sep-2025
**************************************************************************************************************/

public class PEAC_BridgewareSelectZipGeoCodes {

	public PEAC_BridgewareSelectZipGeoCodes() {

	}

	public static void searchMultipleAssets(List<Asset__c> assetsList) {
		List<Asset__c> assetsToUpdate = new List<Asset__c>();
		List<Rate__c> ratesToUpsert = new List<Rate__c>();
		List<Rate__c> ratesToInsert = new List<Rate__c>();
		Set<String> uniqueZipsSet = new Set<String>();
		Map<Id, Rate__c> ratesToUpdate = new Map<Id, Rate__c>();
		Map<String, String> fieldsConfig = new Map<String, String>();
		List<TC_BridgewareTaxJurisdiction> ratesRespList = new List<TC_BridgewareTaxJurisdiction>();

		for(PEAC_BulkAssetsUpload__mdt mdt : [SELECT DeveloperName,Value__c FROM PEAC_BulkAssetsUpload__mdt WHERE DeveloperName IN ('AssetFieldsRespDataMapping','RateFieldsRespDataMapping')]){
			fieldsConfig.put(mdt.DeveloperName, mdt.Value__c);
		}
		for(Asset__c asset :assetsList){
			if(String.isNotEmpty(asset.Equipment_Zip__c)){
				uniqueZipsSet.add(asset.Equipment_Zip__c);
			}
		}
		Map<String, Map<String, List<TC_BridgewareTaxJurisdiction>>> zipRespsMap = getZipTaxCodes(uniqueZipsSet);
		for(String zip : uniqueZipsSet){
			if(zipRespsMap?.get(zip)?.get('Rates')?.isEmpty() == false)
				ratesRespList.addAll(zipRespsMap?.get(zip)?.get('Rates'));
		}
		if(!ratesRespList.isEmpty())
			saveRates(ratesRespList, fieldsConfig.get('RateFieldsRespDataMapping'));

		//try {
			for(Asset__c asset :assetsList){
				if(zipRespsMap?.get(asset?.Equipment_Zip__c)?.get('Assets')?.isEmpty() == false){
					assetsToUpdate.addAll(updateAssets(asset, zipRespsMap.get(asset.Equipment_Zip__c).get('Assets'), fieldsConfig.get('AssetFieldsRespDataMapping')));
				}
				/*if(zipRespsMap.get(asset.Equipment_Zip__c).get('Rates').size() > 0){
					ratesToUpsert.addAll(saveRates(zipRespsMap.get(asset.Equipment_Zip__c).get('Rates'), fieldsConfig.get('RateFieldsRespDataMapping')));
				}*/
			}
			system.debug(LoggingLevel.error,'assetsToUpdate size : '+ assetsToUpdate.size());
			system.debug(LoggingLevel.error,'ratesToUpsert size : '+ ratesToUpsert.size());
			update assetsToUpdate;

			/*if(ratesToUpsert.size() > 0){
				for(Rate__c rate : ratesToUpsert){
					if(rate.Id == null){
						ratesToInsert.add(rate);
					}else if(!ratesToUpdate.containsKey(rate.Id)){
						ratesToUpdate.put(rate.Id, rate);
					}
				}
			}
			system.debug(LoggingLevel.error,'ratesToInsert size : '+ ratesToInsert.size());
			system.debug(LoggingLevel.error,'ratesToUpdate size : '+ ratesToUpdate.values().size());
			if(ratesToInsert.size() > 0){
				insert ratesToInsert;
			}
			if(ratesToUpdate.values().size() > 0){
				update ratesToUpdate.values();
			}*/
		//} catch(Exception ex) {
			//handleException(ex);return null;
		//}
	}

	public static Map<String, Map<String, List<TC_BridgewareTaxJurisdiction>>> getZipTaxCodes(Set<String> uniqueZips){
		TC_BridgewareUtility serviceUtil = TC_BridgewareUtility.getInstance();
		TC_BridgewareSelectZipGeoCodeRespBean respBean;
		Boolean isIL10 = IL10_Flag__c.getValues('GeneralSetting').use_IL10__c;
		Boolean mockCallout = serviceUtil.getServiceSettings().Mock_Callout__c;
		String mockEndpoint = serviceUtil.getServiceSettings().Mock_Endpoint__c;
		String configName = serviceUtil.getServiceSettings().Config_Name__c;
		Blob headerValue = Blob.valueOf('username' + ':' + 'password');
		String authorizationHeader = 'Basic ' + EncodingUtil.base64Encode(headerValue);
		Map<String, Map<String, List<TC_BridgewareTaxJurisdiction>>> zipResps = new Map<String, Map<String, List<TC_BridgewareTaxJurisdiction>>>();

		for(String zipCode : uniqueZips){
			TC_BridgewareSelectZipGeoCodeRequestBean bean = new TC_BridgewareSelectZipGeoCodeRequestBean();
			bean.setZipCode(zipCode);
			bean.setTaxCode('');
			bean.setRequestUserId('');

			Http h = new Http ();
			HttpRequest req = new HttpRequest ();
			if(mockCallout && !String.isEmpty(mockEndpoint)){
				req.setHeader('Authorization', authorizationHeader);
				req.setEndpoint(mockEndpoint + '/selectZipGeoCode');
			}else{
				if(isIL10){
					TC_BWUtility.requestToIL10(req, 'ZIP');
				}else{
					req.setEndpoint('callout:Bridgeware/selectZipGeoCode');
				}
			}
			req.setMethod('POST');
			req.setHeader('CONFIG-NAME', configName);
			req.setHeader('Content-Type','application/json');
			req.setBody(JSON.serialize(bean));
			req.setTimeout(120000);

			HttpResponse resp = h.send(req);
			String responseJson = TC_BWResponseBean.unWrap(resp.getBody());
			if(resp.getStatusCode() == 200) {
				if(isIL10){
					respBean = TC_BridgewareSelectZipGeoCodeRespBean.createResponseBeanFromXml(responseJson);
				}else{
					respBean = TC_BridgewareSelectZipGeoCodeRespBean.createResponseBeanFromJson(responseJson);
				}
			}else{
				respBean = TC_BridgewareSelectZipGeoCodeRespBean.createResponseBeanFromJson(responseJson);
			}
			Map<String, List<TC_BridgewareTaxJurisdiction>> respAssetsRates = getTaxJurisdictions(respBean);
			zipResps.put(zipCode, respAssetsRates);
		}
		return zipResps;
	}

	public static Map<String, List<TC_BridgewareTaxJurisdiction>> getTaxJurisdictions(TC_BridgewareSelectZipGeoCodeRespBean selectZipGeoCodeResp) {
		List<TC_BridgewareTaxJurisdiction> taxJurisdictionList = new List<TC_BridgewareTaxJurisdiction>();
		Map<String,TC_BridgewareTaxJurisdiction> rateMap = new Map<String,TC_BridgewareTaxJurisdiction>();
		Map<String, List<TC_BridgewareTaxJurisdiction>> respAssetsRates = new Map<String, List<TC_BridgewareTaxJurisdiction>>();
		
		if (selectZipGeoCodeResp.getContentData() != null) {
			TC_BridgewareSelectZipGeoCodeRespBean.UniDataVtZipState[] uniDataVtZipStateList = selectZipGeoCodeResp.getContentData().getVtZipStateList();
			
			if (uniDataVtZipStateList != null) {
				for (TC_BridgewareSelectZipGeoCodeRespBean.UniDataVtZipState uniDataVtZipState : uniDataVtZipStateList) {
					String state = uniDataVtZipState.getDescription();
					String stateCode = uniDataVtZipState.getCode();
					TC_BridgewareSelectZipGeoCodeRespBean.UniDataVtZipCounty[] uniDataVtZipCountyList = uniDataVtZipState.getVtZipCountyList();
					
					if (uniDataVtZipCountyList != null) {
						for (TC_BridgewareSelectZipGeoCodeRespBean.UniDataVtZipCounty uniDataVtZipCounty : uniDataVtZipCountyList) {
							String county = uniDataVtZipCounty.getDescription();
							String countyCode = uniDataVtZipCounty.getCode();
							TC_BridgewareSelectZipGeoCodeRespBean.UniDataVtZipCity[] uniDataVtZipCityList = uniDataVtZipCounty.getVtZipCityList();
							
							if (uniDataVtZipCityList != null) {
								for (TC_BridgewareSelectZipGeoCodeRespBean.UniDataVtZipCity uniDataVtZipCity : uniDataVtZipCityList) {
									String city = uniDataVtZipCity.getDescription();
									String cityCode = uniDataVtZipCity.getCode();
									TC_BridgewareTaxJurisdiction taxJurisdiction = new TC_BridgewareTaxJurisdiction();
									taxJurisdiction.city = city;
									taxJurisdiction.county = county;
									taxJurisdiction.state = state;
									taxJurisdiction.cityCode = cityCode;
									taxJurisdiction.countyCode = countyCode;
									taxJurisdiction.stateCode = stateCode;
									taxJurisdictionList.add(taxJurisdiction);
									
									TC_BridgewareSelectZipGeoCodeRespBean.UniDataTaxType[] uniDataTaxTypeList = uniDataVtZipCity.getTaxTypeList();
									if (uniDataTaxTypeList != null) {
										for (TC_BridgewareSelectZipGeoCodeRespBean.UniDataTaxType uniDataTaxType : uniDataTaxTypeList) {
											TC_BridgewareTaxJurisdiction rate = new TC_BridgewareTaxJurisdiction();
											rate.city = city;
											rate.county = county;
											rate.state = state;
											rate.cityCode = cityCode;
											rate.countyCode = countyCode;
											rate.stateCode = stateCode;
											rate.rateCodeDescription = uniDataTaxType.getDescription();
											rate.rateCode = uniDataTaxType.getCode();
											rate.stateTaxRate = uniDataTaxType.getStateTaxRate();
											rate.countyTaxRate = uniDataTaxType.getCountyTaxRate();
											rate.countyTransTaxRate = uniDataTaxType.getCountyTransTaxRate();
											rate.cityTaxRate = uniDataTaxType.getCityTaxRate();
											rate.cityTransTaxRate = uniDataTaxType.getCityTransTaxRate();
											String mapKey = city+rate.rateCode;
											rateMap.put(mapKey,rate);
										}
									}
								}
							}
						}
					}
				}
			}
		}
		if(taxJurisdictionList.size() > 0)
			respAssetsRates.put('Assets', taxJurisdictionList);

		if(rateMap != null && rateMap.Values().size() > 0)
			respAssetsRates.put('Rates', rateMap.Values());
		
		return respAssetsRates;
	}

	public static List<Asset__c> updateAssets(Asset__c asset, List<TC_BridgewareTaxJurisdiction> taxJurisdictionList, String fields) {
		try {
			if(taxJurisdictionList.size() == 1){
				Map<String, Object> taxJdr = (Map<String, Object>) JSON.deserializeUntyped(JSON.serialize(taxJurisdictionList[0]));
				for(String fieldName: fields.split(', ')){
					asset.put(fieldName.split('\\|\\|')[0], taxJdr.get(fieldName.split('\\|\\|')[1]));
				}
			}else if(taxJurisdictionList.size() > 1){
				asset.Multiple_Counties__c = true;
			}
			asset.Tax_Zip_Updated__c = false;
		} catch(Exception ex) { 
			//handleException(ex);
			return null;
		}
		return new List<Asset__c>{asset};
	}

	public static void saveRates(List<TC_BridgewareTaxJurisdiction> rateList, String fields) {
		Set<String> respCodes = new Set<String>();
		List<Rate__c> ratesToInsert = new List<Rate__c>();
		Map<Id, Rate__c> ratesToUpdate = new Map<Id, Rate__c>();
		Map<String, String> existingRates = new Map<String, String>();
		
		for(TC_BridgewareTaxJurisdiction taxJdx : rateList){
			respCodes.add(taxJdx.rateCode+'~'+taxJdx.state+'~'+taxJdx.stateCode+'~'+taxJdx.county+'~'+taxJdx.countyCode+'~'+taxJdx.city+'~'+taxJdx.cityCode);
		}
		for(Rate__c rate : [SELECT Id,Rate_Code__c,State__c,State_Code__c,County__c,County_Code__c,City__c,City_Code__c FROM Rate__c WHERE GeoCodes__c IN :respCodes]){
			existingRates.put(rate.Rate_Code__c+'~'+rate.State__c+'~'+rate.State_Code__c+'~'+rate.County__c+'~'+rate.County_Code__c+'~'+rate.City__c+'~'+rate.City_Code__c, rate.Id);
		}
		for(TC_BridgewareTaxJurisdiction taxJdx : rateList){
			String taxCodesKey = taxJdx.rateCode+'~'+taxJdx.state+'~'+taxJdx.stateCode+'~'+taxJdx.county+'~'+taxJdx.countyCode+'~'+taxJdx.city+'~'+taxJdx.cityCode;
			Map<String, Object> taxJdxMap = (Map<String, Object>) JSON.deserializeUntyped(JSON.serialize(taxJdx));
			Rate__c rate = new Rate__c();

			if(existingRates.containsKey(taxCodesKey) && existingRates.get(taxCodesKey) != null){
				rate.Id = existingRates.get(taxCodesKey);
			}
			for(String fieldName: fields.split(', ')){
				rate.put(fieldName.split('\\|\\|')[0], taxJdxMap.get(fieldName.split('\\|\\|')[1]));
			}
			if(rate.Id == null)
				ratesToInsert.add(rate);
			else if(!ratesToUpdate.containsKey(rate.Id)){
				ratesToUpdate.put(rate.Id, rate);
			}
		}
		if(!ratesToInsert.isEmpty())
			insert ratesToInsert;
		if(!ratesToUpdate.values().isEmpty())
			update ratesToUpdate.values();
	}
}