peac_dev/force-app/main/default/objects/Asset__c/Asset__c.object-meta.xml
<CustomObject>
    <label>Asset</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Asset Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Assets</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

peac_dev/force-app/main/default/objects/Asset__c/fields/City_Tax_Amount__c.field-meta.xml
<CustomField>
    <fullName>City_Tax_Amount__c</fullName>
    <label>City Tax Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

peac_dev/force-app/main/default/objects/Asset__c/fields/City_Tax_Code__c.field-meta.xml
<CustomField>
    <fullName>City_Tax_Code__c</fullName>
    <label>City Tax Code</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Tax_Codes</valueSetName>
    </valueSet>
</CustomField>

peac_dev/force-app/main/default/objects/Asset__c/fields/City_Tax_Percentage__c.field-meta.xml
<CustomField>
    <fullName>City_Tax_Percentage__c</fullName>
    <label>City Tax Percentage</label>
    <precision>18</precision>
    <scale>6</scale>
    <type>Percent</type>
</CustomField>

peac_dev/force-app/main/default/objects/Asset__c/fields/City_Transit_Tax_Amount__c.field-meta.xml
<CustomField>
    <fullName>City_Transit_Tax_Amount__c</fullName>
    <label>City Transit Tax Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

peac_dev/force-app/main/default/objects/Asset__c/fields/City_Transit_Tax_Percentage__c.field-meta.xml
<CustomField>
    <fullName>City_Transit_Tax_Percentage__c</fullName>
    <label>City Transit Tax Percentage</label>
    <precision>18</precision>
    <scale>6</scale>
    <type>Percent</type>
</CustomField>

peac_dev/force-app/main/default/objects/Asset__c/fields/County_Tax_Amount__c.field-meta.xml
<CustomField>
    <fullName>County_Tax_Amount__c</fullName>
    <label>County Tax Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

peac_dev/force-app/main/default/objects/Asset__c/fields/County_Tax_Code__c.field-meta.xml
<CustomField>
    <fullName>County_Tax_Code__c</fullName>
    <label>County Tax Code</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Tax_Codes</valueSetName>
    </valueSet>
</CustomField>

peac_dev/force-app/main/default/objects/Asset__c/fields/County_Tax_Percentage__c.field-meta.xml
<CustomField>
    <fullName>County_Tax_Percentage__c</fullName>
    <label>County Tax Percentage</label>
    <precision>18</precision>
    <scale>6</scale>
    <type>Percent</type>
</CustomField>

peac_dev/force-app/main/default/objects/Asset__c/fields/County_Transit_Tax_Amount__c.field-meta.xml
<CustomField>
    <fullName>County_Transit_Tax_Amount__c</fullName>
    <label>County Transit Tax Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

peac_dev/force-app/main/default/objects/Asset__c/fields/County_Transit_Tax_Percentage__c.field-meta.xml
<CustomField>
    <fullName>County_Transit_Tax_Percentage__c</fullName>
    <label>County Transit Tax Percentage</label>
    <precision>18</precision>
    <scale>6</scale>
    <type>Percent</type>
</CustomField>

peac_dev/force-app/main/default/objects/Asset__c/fields/Federal_Method__c.field-meta.xml
<CustomField>
    <fullName>Federal_Method__c</fullName>
    <label>Federal Depreciation Method</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>14</fullName>
                <label>0.25</label>
            </value>
            <value>
                <fullName>4</fullName>
                <label>150% DDB</label>
            </value>
            <value>
                <fullName>34</fullName>
                <label>150% DDB - 50% Bonus</label>
            </value>
            <value>
                <fullName>24</fullName>
                <label>150% DDB - No Bonus</label>
            </value>
            <value>
                <fullName>8</fullName>
                <label>200% DDB</label>
            </value>
            <value>
                <fullName>38</fullName>
                <label>200% DDB - 50% Bonus</label>
            </value>
            <value>
                <fullName>28</fullName>
                <label>200% DDB - No Bonus</label>
            </value>
            <value>
                <fullName>6</fullName>
                <label>DDB Non 1/2</label>
            </value>
            <value>
                <fullName>11</fullName>
                <label>Diminish Value</label>
            </value>
            <value>
                <fullName>18</fullName>
                <label>DV/SL Optimization</label>
            </value>
            <value>
                <fullName>13</fullName>
                <label>DV-With Limit</label>
            </value>
            <value>
                <fullName>12</fullName>
                <label>Expensed</label>
            </value>
            <value>
                <fullName>15</fullName>
                <label>Foreign 10%</label>
            </value>
            <value>
                <fullName>N</fullName>
                <label>No</label>
            </value>
            <value>
                <fullName>10</fullName>
                <label>Prime Cost</label>
            </value>
            <value>
                <fullName>16</fullName>
                <label>Prin Reduction</label>
            </value>
            <value>
                <fullName>31</fullName>
                <label>S/L - 50% Bonus</label>
            </value>
            <value>
                <fullName>21</fullName>
                <label>S/L - No Bonus</label>
            </value>
            <value>
                <fullName>5</fullName>
                <label>S/L Non 1/2</label>
            </value>
            <value>
                <fullName>7</fullName>
                <label>S/L Non 1/2 (2)</label>
            </value>
            <value>
                <fullName>9</fullName>
                <label>Straight Line</label>
            </value>
            <value>
                <fullName>17</fullName>
                <label>Straight Line - International</label>
            </value>
            <value>
                <fullName>Y</fullName>
                <label>Yes</label>
            </value>
            <value>
                <fullName>61</fullName>
                <label>S/L - 80% Bonus</label>
            </value>
            <value>
                <fullName>64</fullName>
                <label>150% DDB - 80% Bonus</label>
            </value>
            <value>
                <fullName>58</fullName>
                <default>true</default>
                <label>200% DDB - 80% Bonus</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

peac_dev/force-app/main/default/objects/Asset__c/fields/LC_City_Tax_Code__c.field-meta.xml
<CustomField>
    <fullName>LC_City_Tax_Code__c</fullName>
    <label>LC City Tax Code</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Tax_Codes</valueSetName>
    </valueSet>
</CustomField>

peac_dev/force-app/main/default/objects/Asset__c/fields/LC_County_Tax_Code__c.field-meta.xml
<CustomField>
    <fullName>LC_County_Tax_Code__c</fullName>
    <label>LC County Tax Code</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Tax_Codes</valueSetName>
    </valueSet>
</CustomField>

peac_dev/force-app/main/default/objects/Asset__c/fields/LC_State_Tax_Code__c.field-meta.xml
<CustomField>
    <fullName>LC_State_Tax_Code__c</fullName>
    <label>LC State Tax Code</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Tax_Codes</valueSetName>
    </valueSet>
</CustomField>

peac_dev/force-app/main/default/objects/Asset__c/fields/Misc_City_Tax_Code__c.field-meta.xml
<CustomField>
    <fullName>Misc_City_Tax_Code__c</fullName>
    <label>Misc City Tax Code</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Tax_Codes</valueSetName>
    </valueSet>
</CustomField>

peac_dev/force-app/main/default/objects/Asset__c/fields/Misc_County_Tax_Code__c.field-meta.xml
<CustomField>
    <fullName>Misc_County_Tax_Code__c</fullName>
    <label>Misc County Tax Code</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Tax_Codes</valueSetName>
    </valueSet>
</CustomField>

peac_dev/force-app/main/default/objects/Asset__c/fields/Misc_State_Tax_Code__c.field-meta.xml
<CustomField>
    <fullName>Misc_State_Tax_Code__c</fullName>
    <label>Misc State Tax Code</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Tax_Codes</valueSetName>
    </valueSet>
</CustomField>

peac_dev/force-app/main/default/objects/Asset__c/fields/Responsibility_Code__c.field-meta.xml
<CustomField>
    <fullName>Responsibility_Code__c</fullName>
    <label>Responsibility Code</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>D</fullName>
                <label>Bank Pays</label>
            </value>
            <value>
                <fullName>E</fullName>
                <label>Bank Pays Lessor</label>
            </value>
            <value>
                <fullName>L</fullName>
                <label>Lessor Pays</label>
            </value>
            <value>
                <fullName>N</fullName>
                <label>N/A</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

peac_dev/force-app/main/default/objects/Asset__c/fields/State_Tax_Amount__c.field-meta.xml
<CustomField>
    <fullName>State_Tax_Amount__c</fullName>
    <label>State Tax Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

peac_dev/force-app/main/default/objects/Asset__c/fields/State_Tax_Code__c.field-meta.xml
<CustomField>
    <fullName>State_Tax_Code__c</fullName>
    <label>State Tax Code</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Tax_Codes</valueSetName>
    </valueSet>
</CustomField>

peac_dev/force-app/main/default/objects/Asset__c/fields/Tax_Date_Time__c.field-meta.xml
<CustomField>
    <fullName>Tax_Date_Time__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>This is the date and time that the taxes were auto - calculated</inlineHelpText>
    <label>Tax Date / Time</label>
    <type>DateTime</type>
</CustomField>

peac_dev/force-app/main/default/objects/Asset__c/fields/Tax_Exempt_Equipment__c.field-meta.xml
<CustomField>
    <fullName>Tax_Exempt_Equipment__c</fullName>
    <inlineHelpText>Defaults to No. Select Yes if the Equipment is Tax Exempt.</inlineHelpText>
    <label>Tax Exempt Equipment</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>No</fullName>
                <default>true</default>
                <label>No</label>
            </value>
            <value>
                <fullName>Yes</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

peac_dev/force-app/main/default/objects/Asset__c/fields/Upfront_City_Tax_Amount__c.field-meta.xml
<CustomField>
    <fullName>Upfront_City_Tax_Amount__c</fullName>
    <label>Upfront City Tax Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

peac_dev/force-app/main/default/objects/Asset__c/fields/Upfront_City_Transit_Tax_Amount__c.field-meta.xml
<CustomField>
    <fullName>Upfront_City_Transit_Tax_Amount__c</fullName>
    <label>Upfront City Transit Tax Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

peac_dev/force-app/main/default/objects/Asset__c/fields/Upfront_County_Tax_Amount__c.field-meta.xml
<CustomField>
    <fullName>Upfront_County_Tax_Amount__c</fullName>
    <label>Upfront County Tax Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

peac_dev/force-app/main/default/objects/Asset__c/fields/Upfront_County_Transit_Tax_Amount__c.field-meta.xml
<CustomField>
    <fullName>Upfront_County_Transit_Tax_Amount__c</fullName>
    <label>Upfront County Transit Tax Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

peac_dev/force-app/main/default/objects/Asset__c/fields/Upfront_Responsibility_Code__c.field-meta.xml
<CustomField>
    <fullName>Upfront_Responsibility_Code__c</fullName>
    <label>Upfront Responsibility Code</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>D</fullName>
                <label>Bank Pays</label>
            </value>
            <value>
                <fullName>E</fullName>
                <label>Bank Pays Lessor</label>
            </value>
            <value>
                <fullName>L</fullName>
                <label>Lessor Pays</label>
            </value>
            <value>
                <fullName>N</fullName>
                <label>N/A</label>
            </value>
            <value>
                <fullName>TBD</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

peac_dev/force-app/main/default/objects/Asset__c/fields/Upfront_State_Tax_Amount__c.field-meta.xml
<CustomField>
    <fullName>Upfront_State_Tax_Amount__c</fullName>
    <label>Upfront State Tax Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

peac_dev/force-app/main/default/objects/Asset__c/fields/Upfront_Tax_Code__c.field-meta.xml
<CustomField>
    <fullName>Upfront_Tax_Code__c</fullName>
    <label>Upfront Tax Code</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Tax_Codes</valueSetName>
    </valueSet>
</CustomField>

peac_dev/force-app/main/default/objects/Asset__c/fields/Upfront_Tax_Method__c.field-meta.xml
<CustomField>
    <fullName>Upfront_Tax_Method__c</fullName>
    <label>Upfront Tax Method</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>GRM</fullName>
            </value>
            <value>
                <fullName>PPM</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

peac_dev/force-app/main/default/objects/Asset__c/fields/Usage_User_Table__c.field-meta.xml
<CustomField>
    <fullName>Usage_User_Table__c</fullName>
    <label>Tax Exempt Certificate</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
                <label>Requested</label>
            </value>
            <value>
                <fullName>2</fullName>
                <label>Received</label>
            </value>
            <value>
                <fullName>3</fullName>
                <label>Exempt Equipment</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

peac_dev/force-app/main/default/classes/PEAC_AssetTriggerPBHelper.cls
/**************************************************************************************************************
@Author: Chalapati Murru (LTIMindtree)
@Description: This class is used to implement apex for the Process builders which were converted to Apex
@User Story: SAL-5692 Expo: Opportunity Refactor
@Created Date: Jan-07-2026
**************************************************************************************************************/
public class PEAC_AssetTriggerPBHelper {
	/************************************************************************************************************
	 * @Author:Rajesh Kumar(LTM)
	 * @Description: Reset the Asset fields for tax calculation
	 * @Param: List of Assets
	 * **********************************************************************************************************/
    
    public static void stateTaxCodeChanged(List<Asset__c> assets)
    {
        for(Asset__c oppAsset: assets)
        {
           resetTaxFields(oppAsset);
        }
    }
    /* Start: SAL-6445 - Vinod Rathod
     * Logic migrated from TC Asset: Sets Tax Code, Amt, & Percentages if 036, 060 And Set Tax Fields to Null Process Builder.
     */
    public static void setsTaxCodeAmtPercentages(List<Asset__c> assets, Boolean isNew){
        for(Asset__c asset : assets){
            
            //Tax Exempt Equipment = YES
            if(asset.Tax_Exempt_Equipment__c == 'Yes'){
                asset.City_Tax_Code__c = '036';
                asset.County_Tax_Code__c = '036';
                asset.Responsibility_Code__c = null;
                asset.State_Tax_Code__c = '036';
                asset.Tax_Date_Time__c = System.now();
                asset.Upfront_City_Tax_Amount__c = 0;
                asset.Upfront_City_Transit_Tax_Amount__c = 0;
                asset.Upfront_County_Tax_Amount__c = 0;
                asset.Upfront_County_Transit_Tax_Amount__c = 0;
                asset.Upfront_State_Tax_Amount__c = 0;
                asset.Upfront_Tax_Code__c = '036';
                asset.Upfront_Tax_Method__c = null;
                asset.Usage_User_Table__c = '3'; 
				asset.Responsibility_Code__c = Null;
                asset.Upfront_Responsibility_Code__c = Null;
				//asset.Federal_Method__c = '21';                
            }
            //Upfront Tax Vendor (State Tax Code = 050)
            if(asset.State_Tax_Code__c == '050'){
                asset.City_Tax_Amount__c = 0;
                asset.City_Tax_Code__c = '050';
                asset.City_Tax_Percentage__c = 0;
                asset.City_Transit_Tax_Amount__c = 0;
                asset.City_Transit_Tax_Percentage__c = 0;
                asset.County_Tax_Amount__c = 0;
                asset.County_Tax_Code__c = '050';
                asset.County_Tax_Percentage__c = 0;
                asset.County_Transit_Tax_Amount__c = 0;
                asset.County_Transit_Tax_Percentage__c = 0;
                asset.LC_City_Tax_Code__c = '050';
                asset.LC_County_Tax_Code__c = '050';
                asset.LC_State_Tax_Code__c = '050';
                asset.Misc_City_Tax_Code__c = '050';
                asset.Misc_County_Tax_Code__c = '050';
                asset.Misc_State_Tax_Code__c = '050';
                asset.Responsibility_Code__c = null;
                asset.State_Tax_Amount__c = 0;
                asset.State_Tax_Percentage__c = 0;
                asset.Tax_Date_Time__c = System.now();
                asset.Upfront_City_Tax_Amount__c = 0;
                asset.Upfront_City_Transit_Tax_Amount__c = 0;
                asset.Upfront_County_Tax_Amount__c = 0;
                asset.Upfront_County_Transit_Tax_Amount__c = 0;
                asset.Upfront_Responsibility_Code__c = null;
                asset.Upfront_State_Tax_Amount__c = 0;
                asset.Upfront_Tax_Code__c = '050';
                asset.Upfront_Tax_Method__c = null;
            }
            //Switched off tax exempt
            if(!isNew && asset.Tax_Exempt_Equipment__c == 'No' && asset.State_Tax_Code__c == '036'){
                resetTaxFields(asset);
            }
            //State Tax moved to 031
            if(!isNew && asset.State_Tax_Code__c == '031'){
                if (asset.LC_County_Tax_Code__c != null)
                    asset.LC_County_Tax_Code__c = '031';
                if (asset.LC_State_Tax_Code__c != null)
                    asset.LC_State_Tax_Code__c = '031';
                if (asset.LC_City_Tax_Code__c != null)
                    asset.LC_City_Tax_Code__c = '031';
            }
        }        
    }
        
    //Sets all tax fields to null when it needs to reset values
    private static void resetTaxFields(Asset__c a) {
        a.City_Tax_Amount__c = 0;
        a.City_Tax_Code__c = null;
        a.City_Tax_Percentage__c = 0;
        a.City_Transit_Tax_Amount__c = 0;
        a.City_Transit_Tax_Percentage__c = 0;
        a.County_Tax_Amount__c = 0;
        a.County_Tax_Code__c = null;
        a.County_Tax_Percentage__c = 0;
        a.County_Transit_Tax_Amount__c = 0;
        a.County_Transit_Tax_Percentage__c = 0;
        a.LC_City_Tax_Code__c = null;
        a.LC_County_Tax_Code__c = null;
        a.LC_State_Tax_Code__c = null;    
        a.Misc_City_Tax_Code__c = null;
        a.Misc_County_Tax_Code__c = null;
        a.Misc_State_Tax_Code__c = null;
        a.Misc_GST__c = 0;
        a.Responsibility_Code__c = null;
        a.State_Tax_Amount__c = 0;
        a.State_Tax_Code__c = null;
        a.State_Tax_Percentage__c = 0;   
        a.Upfront_City_Tax_Amount__c = 0;
        a.Upfront_City_Transit_Tax_Amount__c = 0;
        a.Upfront_County_Tax_Amount__c = 0;
        a.Upfront_County_Transit_Tax_Amount__c = 0;
        a.Upfront_Responsibility_Code__c = null;
        a.Upfront_State_Tax_Amount__c = 0;
        a.Upfront_Tax_Code__c = null;
        a.Upfront_Tax_Method__c = null;
        a.Usage_User_Table__c = null;
    }
    /* End:
     * Process Builder:TC Asset: Sets Tax Code, Amt, & Percentages if 036, 060 And Set Tax Fields to Null.
    /* END: SAL-6445 - Vinod Rathod */
    //SAL-6445 -Vinod Rathod
    //Logic migrated from Process Builder TC Asset -- Tax Exempt Certificate Requested
    public static void tCAssetTaxExemptCertificateRequested(List<Asset__c> assets){
        for(Asset__c asset : assets){
            asset.City_Tax_Code__c = asset.Misc_City_Tax_Code__c;
            asset.County_Tax_Code__c = asset.Misc_County_Tax_Code__c;
            asset.Financed_Trigger__c = false;
            asset.Responsibility_Code__c = null;
            asset.State_Tax_Code__c = asset.Misc_State_Tax_Code__c;
            asset.Upfront_City_Tax_Amount__c = null;
            asset.Upfront_City_Transit_Tax_Amount__c = null;
            asset.Upfront_County_Tax_Amount__c = null;
            asset.Upfront_County_Transit_Tax_Amount__c = null;
            asset.Upfront_State_Tax_Amount__c = null;
            asset.Upfront_Tax_Code__c = null;
            asset.Upfront_Tax_Method__c = null;
        }        
    }
    
    /* Start: SAL-6284 - Manish */
    /* Start:
     * Process Builder: TC Asset Booking Default – Tax Method & Responsibility Code
	 * Apex Trigger Implementation for TC Asset Booking Default – Tax Method & Responsibility Code
	*/

    public static void tcAssetBookingDefaultTaXMethodResponsibilityCode(List<Asset__c> assets){
        Set<Id> opportunityIds = new Set<Id>();
        Map<Id, Opportunity> opportunityMap = new Map<Id, Opportunity>();
        for(Asset__c obj : assets){
            if(obj.Opportunity__c != Null){
                opportunityIds.add(obj.Opportunity__c);
            }
        }
        if(!opportunityIds.isEmpty()){
			opportunityMap = getOpportunityMapByIds(opportunityIds);
        }
        for(Asset__c asset : assets){
            // Null Tax Code Logic
            if(asset.Upfront_Tax_Code__c == null) {
                asset.Responsibility_Code__c = null;
                asset.Upfront_Responsibility_Code__c = null;
                asset.Upfront_Tax_Method__c = null;
                //return;
            }            
            // Responsibility Code Logic
            // Below code has been commented as this is overriding the logic for SAL-6445
            /*if(asset.Upfront_Tax_Code__c != null ) {
            	asset.Responsibility_Code__c = 'L';
               	asset.Upfront_Responsibility_Code__c = 'L'; 
            } */         
            // Tax Method Logic
            if(asset.Upfront_Tax_Code__c != null && asset.State_Tax_Code__c != '050' && asset.State_Tax_Code__c != '036'){
                //Added by Rajesh- Should be defaulted
                asset.Responsibility_Code__c = 'L';
                asset.Upfront_Responsibility_Code__c = 'L';
                if(isPPMState(asset)) {
                    asset.Upfront_Tax_Method__c = 'PPM';
                } else if(isGRMState(asset)) {
                    asset.Upfront_Tax_Method__c = 'GRM';
                }            
            // California Logic
            if(asset.Equipment_Location_State__c == 'CALIFORNIA' && asset.Opportunity__c != null && opportunityMap.containskey(asset.Opportunity__c)) {
                if(opportunityMap.get(asset.Opportunity__c).Purchase_Options__c == '1.00 Out') {
                    asset.Upfront_Tax_Method__c = 'PPM';
                } /*else if(opportunityMap.get(asset.Opportunity__c).Purchase_Options__c == '$101 Purchase Option') { // SAL-6284: $101 Purchase Option is inactive value, hence commenting code. Confirmed with business
                    asset.Upfront_Tax_Method__c = 'GRM';
                }*/
            }            
            // Maine Logic
            if(asset.Equipment_Location_State__c == 'MAINE' && asset.Opportunity__c != null && opportunityMap.containskey(asset.Opportunity__c)) {
                if(opportunityMap.get(asset.Opportunity__c).Purchase_Options__c == 'FMV') {
                    asset.Upfront_Tax_Method__c = 'PPM';
                } else if(opportunityMap.get(asset.Opportunity__c).Purchase_Options__c == '1.00 Out'
                          /* || opportunityMap.get(asset.Opportunity__c).Purchase_Options__c == '$101 Purchase Option'*/ ) { // SAL-6284: $101 Purchase Option is inactive value, hence commenting code. Confirmed with business
                  	asset.Upfront_Tax_Method__c = 'GRM';
                }
            }            
            }
            // Reset Trigger Asset Recalc
            /*if(asset.Trigger_Asset_PB__c == true) {
            asset.Trigger_Asset_PB__c = false;
            }*/
        }        
    }
	@TestVisible
    private static Boolean isCaliforniaOrMaine(String state) {
        return state == 'CALIFORNIA' || state == 'MAINE';
    }

    private static Boolean isPPMState(Asset__c asset) {
        List<String> ppmStates = new List<String>{'ALABAMA','IDAHO','ILLINOIS','NEVADA','TENNESSEE'};
        return ppmStates.contains(asset.Equipment_Location_State__c);
    }

    private static Boolean isGRMState(Asset__c asset) {
        List<String> grmStates = new List<String>{
            'DISTRICT OF COLUMBIA','FLORIDA','GEORGIA','HAWAII','INDIANA','IOWA','KANSAS','KENTUCKY',
                'LOUISIANA','MASSACHUSETTS','MICHIGAN','MINNESOTA','NEBRASKA','NEW JERSEY','NEW MEXICO',
                'NORTH CAROLINA','NORTH DAKOTA','OHIO','OKLAHOMA','RHODE ISLAND','SOUTH DAKOTA','TEXAS',
                'UTAH','VERMONT','WISCONSIN','WASHINGTON','WEST VIRGINIA'
                };
        return grmStates.contains(asset.Equipment_Location_State__c);
    }

    private static Map<Id, Opportunity> getOpportunityMapByIds(Set<Id> ids) {
        return new Map<Id, Opportunity>(
            [SELECT Id, Purchase_Options__c FROM Opportunity WHERE Id IN :ids]
        );
    }
    /* End:
     * Process Builder: TC Asset Booking Default – Tax Method & Responsibility Code
	 * Apex Trigger Implementation for TC Asset Booking Default – Tax Method & Responsibility Code
	*/
	/* END: SAL-6284 - Manish */
}