peac_dev/force-app/main/default/objects/Asset__c/Asset__c.object-meta.xml
<CustomObject>
    <label>Asset</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Asset Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Assets</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

peac_dev/force-app/main/default/objects/Asset__c/fields/Asset_Description__c.field-meta.xml
<CustomField>
    <fullName>Asset_Description__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Detailed Equipment Description</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

peac_dev/force-app/main/default/objects/Asset__c/fields/Cost__c.field-meta.xml
<CustomField>
    <fullName>Cost__c</fullName>
    <inlineHelpText>Value will default from Opportunity on First Asset</inlineHelpText>
    <label>Cost</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

peac_dev/force-app/main/default/objects/Asset__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Value will default from Opportunity on First Asset</inlineHelpText>
    <label>Description</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

peac_dev/force-app/main/default/objects/Asset__c/fields/End_User_Billing_Address__c.field-meta.xml
<CustomField>
    <fullName>End_User_Billing_Address__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Want to utilize the Business address from the opportunity? If yes, check this box and select save. If not, provide the alternative address.</inlineHelpText>
    <label>End User Business Address?</label>
    <type>Checkbox</type>
</CustomField>

peac_dev/force-app/main/default/objects/Asset__c/fields/Equipment_Address_2__c.field-meta.xml
<CustomField>
    <fullName>Equipment_Address_2__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Equipment Street 2</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

peac_dev/force-app/main/default/objects/Asset__c/fields/Equipment_City__c.field-meta.xml
<CustomField>
    <fullName>Equipment_City__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Equipment City</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

peac_dev/force-app/main/default/objects/Asset__c/fields/Equipment_Code__c.field-meta.xml
<CustomField>
    <fullName>Equipment_Code__c</fullName>
    <label>Equipment Code</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Asset_Equipment_Code</valueSetName>
    </valueSet>
</CustomField>

peac_dev/force-app/main/default/objects/Asset__c/fields/Equipment_State__c.field-meta.xml
<CustomField>
    <fullName>Equipment_State__c</fullName>
    <label>Equipment State</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>AL</fullName>
            </value>
            <value>
                <fullName>AK</fullName>
            </value>
            <value>
                <fullName>AS</fullName>
            </value>
            <value>
                <fullName>AZ</fullName>
            </value>
            <value>
                <fullName>AR</fullName>
            </value>
            <value>
                <fullName>CA</fullName>
            </value>
            <value>
                <fullName>CO</fullName>
            </value>
            <value>
                <fullName>CT</fullName>
            </value>
            <value>
                <fullName>DE</fullName>
            </value>
            <value>
                <fullName>DC</fullName>
            </value>
            <value>
                <fullName>FL</fullName>
            </value>
            <value>
                <fullName>GA</fullName>
            </value>
            <value>
                <fullName>GU</fullName>
            </value>
            <value>
                <fullName>HI</fullName>
            </value>
            <value>
                <fullName>ID</fullName>
            </value>
            <value>
                <fullName>IL</fullName>
            </value>
            <value>
                <fullName>IN</fullName>
            </value>
            <value>
                <fullName>IA</fullName>
            </value>
            <value>
                <fullName>KS</fullName>
            </value>
            <value>
                <fullName>KY</fullName>
            </value>
            <value>
                <fullName>LA</fullName>
            </value>
            <value>
                <fullName>ME</fullName>
            </value>
            <value>
                <fullName>MD</fullName>
            </value>
            <value>
                <fullName>MH</fullName>
            </value>
            <value>
                <fullName>MA</fullName>
            </value>
            <value>
                <fullName>MI</fullName>
            </value>
            <value>
                <fullName>FM</fullName>
            </value>
            <value>
                <fullName>MN</fullName>
            </value>
            <value>
                <fullName>MS</fullName>
            </value>
            <value>
                <fullName>MO</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

peac_dev/force-app/main/default/objects/Asset__c/fields/Equipment_Street__c.field-meta.xml
<CustomField>
    <fullName>Equipment_Street__c</fullName>
    <defaultValue>&quot;&quot;</defaultValue>
    <encryptionScheme>None</encryptionScheme>
    <label>Equipment Street</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

peac_dev/force-app/main/default/objects/Asset__c/fields/Equipment_Sub_Category__c.field-meta.xml
<CustomField>
    <fullName>Equipment_Sub_Category__c</fullName>
    <label>Equipment Sub-Category</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Equipment_Code__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>Equipment_Sub_Category</valueSetName>
    </valueSet>
</CustomField>

peac_dev/force-app/main/default/objects/Asset__c/fields/Equipment_Zip__c.field-meta.xml
<CustomField>
    <fullName>Equipment_Zip__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Equipment Zip</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

peac_dev/force-app/main/default/objects/Asset__c/fields/List_Price__c.field-meta.xml
<CustomField>
    <fullName>List_Price__c</fullName>
    <label>List Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

peac_dev/force-app/main/default/objects/Asset__c/fields/Model__c.field-meta.xml
<CustomField>
    <fullName>Model__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Model</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

peac_dev/force-app/main/default/objects/Asset__c/fields/New_Used__c.field-meta.xml
<CustomField>
    <fullName>New_Used__c</fullName>
    <label>New/Used</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>Used</fullName>
            </value>
            <value>
                <fullName>Refurbished</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

peac_dev/force-app/main/default/objects/Asset__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipName>Assets</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

peac_dev/force-app/main/default/objects/Asset__c/fields/Quantity__c.field-meta.xml
<CustomField>
    <fullName>Quantity__c</fullName>
    <defaultValue>1</defaultValue>
    <label>Quantity</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

peac_dev/force-app/main/default/objects/Asset__c/fields/Residual_Percentage__c.field-meta.xml
<CustomField>
    <fullName>Residual_Percentage__c</fullName>
    <label>Residual Percentage</label>
    <precision>18</precision>
    <scale>6</scale>
    <type>Percent</type>
</CustomField>

peac_dev/force-app/main/default/objects/Asset__c/fields/Serial_Number__c.field-meta.xml
<CustomField>
    <fullName>Serial_Number__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Serial Number</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

peac_dev/force-app/main/default/objects/Beneficial_Owner__c/Beneficial_Owner__c.object-meta.xml
<CustomObject>
    <label>Beneficial Owner</label>
    <nameField>
        <displayFormat>O-{0000}</displayFormat>
        <label>Beneficial Owner</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Beneficial Owners</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

peac_dev/force-app/main/default/objects/Beneficial_Owner__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Beneficial Owners</relationshipLabel>
    <relationshipName>Beneficial_Owners</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

peac_dev/force-app/main/default/objects/Beneficial_Owner__c/fields/Ownership_Percent__c.field-meta.xml
<CustomField>
    <fullName>Ownership_Percent__c</fullName>
    <label>Ownership Percent</label>
    <precision>14</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

peac_dev/force-app/main/default/objects/County__c/County__c.object-meta.xml
<CustomObject>
    <label>County</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>County</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Counties</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

peac_dev/force-app/main/default/objects/County__c/fields/State__c.field-meta.xml
<CustomField>
    <fullName>State__c</fullName>
    <label>State</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>State_Code</valueSetName>
    </valueSet>
</CustomField>

peac_dev/force-app/main/default/objects/Rate__c/Rate__c.object-meta.xml
<CustomObject>
    <label>Rate</label>
    <nameField>
        <displayFormat>R-{0000}</displayFormat>
        <label>Rate Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Rates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

peac_dev/force-app/main/default/objects/Rate__c/fields/City__c.field-meta.xml
<CustomField>
    <fullName>City__c</fullName>
    <description>The city where the business is located.</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>The city where the business is located.</inlineHelpText>
    <label>City</label>
    <length>64</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

peac_dev/force-app/main/default/objects/Rate__c/fields/County__c.field-meta.xml
<CustomField>
    <fullName>County__c</fullName>
    <description>The county the business is located in.</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>The county the business is located in.</inlineHelpText>
    <label>County</label>
    <length>64</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

peac_dev/force-app/main/default/objects/Rate__c/fields/State__c.field-meta.xml
<CustomField>
    <fullName>State__c</fullName>
    <description>State your business is located in.</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>State your business is located in.</inlineHelpText>
    <label>State</label>
    <length>64</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

peac_dev/force-app/main/default/objects/Tax_Rules_Settings__c/Tax_Rules_Settings__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Tax Rules Settings</label>
</CustomObject>

peac_dev/force-app/main/default/objects/Tax_Rules_Settings__c/fields/Parent_Object__c.field-meta.xml
<CustomField>
    <fullName>Parent_Object__c</fullName>
    <defaultValue>&quot;Opportunity&quot;</defaultValue>
    <encryptionScheme>None</encryptionScheme>
    <label>Parent Object</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

peac_dev/force-app/main/default/objects/Tax_Rules_Settings__c/fields/Rate_City_Field__c.field-meta.xml
<CustomField>
    <fullName>Rate_City_Field__c</fullName>
    <defaultValue>&quot;TC_TAX__City__c&quot;</defaultValue>
    <encryptionScheme>None</encryptionScheme>
    <label>Rate City Field</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

peac_dev/force-app/main/default/objects/Tax_Rules_Settings__c/fields/Rate_Code_Field__c.field-meta.xml
<CustomField>
    <fullName>Rate_Code_Field__c</fullName>
    <defaultValue>&quot;TC_TAX__Rate_Code__c&quot;</defaultValue>
    <encryptionScheme>None</encryptionScheme>
    <label>Rate Code Field</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

peac_dev/force-app/main/default/objects/Tax_Rules_Settings__c/fields/Rate_County_Field__c.field-meta.xml
<CustomField>
    <fullName>Rate_County_Field__c</fullName>
    <defaultValue>&quot;TC_TAX__County__c&quot;</defaultValue>
    <encryptionScheme>None</encryptionScheme>
    <label>Rate County Field</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

peac_dev/force-app/main/default/objects/Tax_Rules_Settings__c/fields/Rate_Object__c.field-meta.xml
<CustomField>
    <fullName>Rate_Object__c</fullName>
    <defaultValue>&quot;TC_TAX__Rate__c&quot;</defaultValue>
    <encryptionScheme>None</encryptionScheme>
    <label>Rate Object</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

peac_dev/force-app/main/default/objects/Tax_Rules_Settings__c/fields/Rate_State_Field__c.field-meta.xml
<CustomField>
    <fullName>Rate_State_Field__c</fullName>
    <defaultValue>&quot;TC_TAX__State__c&quot;</defaultValue>
    <encryptionScheme>None</encryptionScheme>
    <label>Rate State Field</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

peac_dev/force-app/main/default/classes/PEAC_CreateAssetsBatchTest.cls
/**************************************************************************************************************
@Author: Chalapati Murru (LTIMindtree)
@Description: This test class is used to cover PEAC_ImportCSVController, PEAC_CreateAssetsBatch and PEAC_BridgewareSelectZipGeoCodes
@User Story: SAL-5692 Expo: Opportunity Refactor
@Created Date: 01-Sep-2025
**************************************************************************************************************/

@isTest
private class PEAC_CreateAssetsBatchTest {

    //Static String str = 'Asset_Description__c,Model__c,Serial_Number__c,List_Price__c,Quantity__c,New_Used__c,Equipment_Code__c,Equipment_Sub_Category__c,Residual_Percentage__c,End_User_Billing_Address__c,Equipment_Street__c,Equipment_Address_2__c,Equipment_City__c,Equipment_State__c,Equipment_Zip__c\n'
				//+'Test Asset,New Model,2342324,2300.00,1,New,Automotive Equipment (General),Automotive (General),10,TRUE,Jacone Drive,,Indianapolis,IN,46204';
    Static String str = 'Asset_Description__c,Model__c,Serial_Number__c,List_Price__c,Quantity__c,New_Used__c,Equipment_Code__c,Equipment_Sub_Category__c,Equipment_Street__c,Equipment_Address_2__c,Equipment_City__c,Equipment_State__c,Equipment_Zip__c\n'
				+'Test Asset,New Model,2342324,2300.00,1,New,Automotive Equipment (General),Automotive (General),Jacone Drive,,Indianapolis,IN,66067';

	@testSetup
    static void prepareData(){
        SL_SCTestData.createBridgeWareSetting();
        Account acc = new Account (Name = 'testbeni', RecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('End User Account').getRecordTypeId(), Business_Phone__c = '1234567890');
        insert acc;
        Contact c = new Contact (AccountId = acc.Id, FirstName = 'test', LastName = 'testbeni', OtherStreet = 'test', OtherCity = 'test', OtherStateCode = 'MN', OtherPostalCode = '11111', Title = 'title', SSN__c = '111111111', BirthDate = Date.today (), Email = 'test@test.com');
        insert c;
        insert new Beneficial_Owner__c (Account__c = acc.Id, Contact__c = c.Id, Ownership_Percent__c = 50);
		
        Test.startTest();
        Opportunity opp = new Opportunity (AccountId = acc.Id,StageName = 'Quote',CloseDate = date.today()+10,Name = 'test');
        insert opp;
        insert new Asset__c (End_User_Billing_Address__c = true, Quantity__c = 1, Equipment_Code__c = 'ATM', 
            Equipment_Sub_Category__c = 'ATM',Opportunity__c = opp.Id, Cost__c = 0
        );
        //Asset__c asset = new Asset__c(Asset_Description__c='Test',Opportunity__c=opp.Id,Quantity__c=1,Equipment_Code__c='Automotive (General)',Equipment_Sub_Category__c='Automotive (General)',Equipment_Zip__c='66067');
        //insert asset;
        Test.stopTest();
        PEAC_TestDataFactory.createBridgeWareSetting();
    }
    static testmethod void saveFileTest(){
        Tax_Rules_Settings__c settings = new Tax_Rules_Settings__c();
        settings.Parent_Object__c = 'Opportunity';
        settings.Rate_Object__c = 'Rate__c';
        settings.Rate_State_Field__c = 'State__c';
        settings.Rate_County_Field__c = 'County__c';
        settings.Rate_City_Field__c = 'City__c';
        settings.Rate_Code_Field__c = 'Rate_Code__c';
        settings.State_Tax_Rate_Field__c = 'State_Tax_Rate__c';
        settings.County_Tax_Rate_Field__c = 'County_Tax_Rate__c';
        settings.TCounty_Tax_Rate_Field__c = 'County_Transit_Tax_Rate__c';
        settings.City_Tax_Rate_Field__c = 'City_Tax_Rate__c';
        settings.TCity_Tax_Rate_Field__c = 'City_Transit_Tax_Rate__c';
        settings.Tax_Parent_Object_Field__c = 'Opportunity__c';
        settings.Parent_Generate_Tax_Matrix_Message_Field__c = 'Description';
        settings.Parent_Tax_Calculation_Begin_Field__c = 'Last_Tax_Calculation_Begin__c';
        settings.Parent_Tax_Calculation_Complete_Field__c = 'Last_Tax_Calculation_Complete__c';
        settings.Parent_Tax_Calculation_Successful_Field__c = 'Last_Tax_Calculation_Successful__c';
        settings.Parent_Tax_Calculation_Error_Field__c = 'Last_Tax_Calculation_Error_Details__c';
        settings.Parent_Tax_Calculation_In_Progress_Field__c = 'Is_Tax_Calculation_In_Progress__c';
        settings.Tax_Calculation_Completion_Alert_Seconds__c = 90;
        insert settings;
        List<opportunity> oppList = [SELECT ID FROM Opportunity LIMIT 1];
        
        Map<String,String> fieldsDataTypes = new Map<String,String>{'Description__c'=>'String','Quantity__c'=>'INTEGER','List_Price__c'=>'DOUBLE'};
        Map<String,Map<String,String>> picklistFieldsValueMap = new Map<String,Map<String,String>>{'Equipment_Sub_Category__c'=>new Map<String,String>{'Copiers'=>'Copiers'}};
            
        Test.startTest();
        Test.setMock(HttpCalloutMock.class, new TC_BridgewareSelectZipGeoCalloutMockImpl());
        //TC_BridgewareService service = new TC_BridgewareServiceImpl();
        String fieldTypes = PEAC_ImportCSVController.getFieldDataTypes();
        String picklistLabels = PEAC_ImportCSVController.getPicklistLabelAPIs('Asset__c',new List<String>{'Equipment_Sub_Category__c'});
        PEAC_ImportCSVController.saveFile(JSON.serialize(str),oppList[0].Id, fieldsDataTypes,picklistFieldsValueMap);
        Test.stopTest();
                
        String toAddress = 'marlintest@peacsolutions.com'; 
        String status = 'Success';
        List<String> failedAssetList = new List<String>();
        Integer successCount = 1;
        Integer failedCount = 1;
        Asset__c asset = new Asset__c(Asset_Description__c='Test',Opportunity__c=oppList[0].Id,Quantity__c=1,Equipment_Code__c='Automotive (General)',Equipment_Sub_Category__c='Automotive (General)',Equipment_Zip__c='66067');
        //insert asset;
        List<Asset__c> assetList = [SELECT ID FROM Asset__c LIMIT 1];
        Assert.areEqual(assetList.size(), 1, 'There is no asset created on opportunity.');
        PEAC_CommonUtils comUtils = new PEAC_CommonUtils();
        PEAC_CommonUtils.byPassAssetTrigger = false;
        PEAC_SelectZipGeoCodeBatch batchJob1 = new PEAC_SelectZipGeoCodeBatch(assetList);
        PEAC_SelectZipGeoCodeBatch.sendToUserMail(toAddress,  status, failedAssetList, successCount, failedCount);
        PEAC_GenerateTaxMatrixBatch taxBatch = new PEAC_GenerateTaxMatrixBatch(new Set<Id>{oppList[0].Id}, false);
        PEAC_GenerateTaxMatrixBatch.sendToUserMail(toAddress,  status, failedAssetList, successCount, failedCount);
    }
    static testmethod void saveFile1Test(){
        Tax_Rules_Settings__c settings = new Tax_Rules_Settings__c();
        settings.Parent_Object__c = 'Opportunity';
        settings.Rate_Object__c = 'Rate__c';
        settings.Rate_State_Field__c = 'State__c';
        settings.Rate_County_Field__c = 'County__c';
        settings.Rate_City_Field__c = 'City__c';
        settings.Rate_Code_Field__c = 'Rate_Code__c';
        settings.State_Tax_Rate_Field__c = 'State_Tax_Rate__c';
        settings.County_Tax_Rate_Field__c = 'County_Tax_Rate__c';
        settings.TCounty_Tax_Rate_Field__c = 'County_Transit_Tax_Rate__c';
        settings.City_Tax_Rate_Field__c = 'City_Tax_Rate__c';
        settings.TCity_Tax_Rate_Field__c = 'City_Transit_Tax_Rate__c';
        settings.Tax_Parent_Object_Field__c = 'Opportunity__c';
        settings.Parent_Generate_Tax_Matrix_Message_Field__c = 'Description';
        settings.Parent_Tax_Calculation_Begin_Field__c = 'Last_Tax_Calculation_Begin__c';
        settings.Parent_Tax_Calculation_Complete_Field__c = 'Last_Tax_Calculation_Complete__c';
        settings.Parent_Tax_Calculation_Successful_Field__c = 'Last_Tax_Calculation_Successful__c';
        settings.Parent_Tax_Calculation_Error_Field__c = 'Last_Tax_Calculation_Error_Details__c';
        settings.Parent_Tax_Calculation_In_Progress_Field__c = 'Is_Tax_Calculation_In_Progress__c';
        settings.Tax_Calculation_Completion_Alert_Seconds__c = 90;
        insert settings;
        List<opportunity> oppList = [SELECT ID FROM Opportunity LIMIT 1];
        
        Map<String,String> fieldsDataTypes = new Map<String,String>{'Description__c'=>'String','Quantity__c'=>'INTEGER','List_Price__c'=>'DOUBLE'};
        Map<String,Map<String,String>> picklistFieldsValueMap = new Map<String,Map<String,String>>{'Equipment_Sub_Category__c'=>new Map<String,String>{'Copiers'=>'Copiers'}};
            
        Test.startTest();
        Test.setMock(HttpCalloutMock.class, new TC_BridgewareSelectZipGeoCalloutMockImpl());
        
        List<Asset__c> assetList = new List<Asset__c>();
        Asset__c asset = new Asset__c(Asset_Description__c='Test',Opportunity__c=oppList[0].Id,Quantity__c=1,Equipment_Code__c='Automotive (General)',Equipment_Sub_Category__c='Automotive (General)',Equipment_Zip__c='66067');
        assetList.add(asset);
        insert assetList;
         
        PEAC_CreateAssetsBatch taxMatBatch = new PEAC_CreateAssetsBatch(assetList);
        Database.executeBatch(taxMatBatch, Integer.Valueof(Label.PEAC_SelectZipGeoCodeBatch_Limit)); 
        Test.stopTest();
        
    }
}