peac_dev/force-app/main/default/objects/Asset__c/Asset__c.object-meta.xml
<CustomObject>
    <label>Asset</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Asset Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Assets</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

peac_dev/force-app/main/default/objects/Meter_Type__c/Meter_Type__c.object-meta.xml
<CustomObject>
    <label>Meter Type</label>
    <nameField>
        <displayFormat>MT-{000}</displayFormat>
        <label>Meter Type Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Meter Types</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

peac_dev/force-app/main/default/objects/Meter_Type__c/fields/Asset__c.field-meta.xml
<CustomField>
    <fullName>Asset__c</fullName>
    <label>Asset</label>
    <referenceTo>Asset__c</referenceTo>
    <relationshipLabel>Meter Types</relationshipLabel>
    <relationshipName>Meter_Types</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

peac_dev/force-app/main/default/objects/Meter_Type__c/fields/Meter_Type__c.field-meta.xml
<CustomField>
    <fullName>Meter_Type__c</fullName>
    <label>Meter Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>BW1</fullName>
                <label>Black And White</label>
            </value>
            <value>
                <fullName>C1</fullName>
                <label>Color</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

peac_dev/force-app/main/default/classes/SL_Meter_TypeTriggerHandlerTest.cls
@isTest
public class SL_Meter_TypeTriggerHandlerTest {
    @isTest
    static void afterDelete() {
        SL_SCTestData.createAccountAndContracts(1, 1);
        SL_SCTestData.createOpportunitiesAndAssets(SL_SCTestData.testAccounts[0].Id, 3, 3);
        List<Asset__c> assets = SL_SCTestData.testAssets;
        List<Meter_Type__c> meterTypes = new List<Meter_Type__c>();
        meterTypes.add(new Meter_Type__c(Asset__c = assets[0].Id));
        meterTypes.add(new Meter_Type__c(Asset__c = assets[1].Id));
        meterTypes.add(new Meter_Type__c(Asset__c = assets[2].Id));
        meterTypes.add(new Meter_Type__c(Asset__c = assets[3].Id));
        meterTypes.add(new Meter_Type__c(Asset__c = assets[6].Id));
        meterTypes.add(new Meter_Type__c(Asset__c = assets[6].Id));
        meterTypes.add(new Meter_Type__c(Asset__c = assets[6].Id));
        Test.startTest();
        insert meterTypes;
        List<Opportunity> oppsAfter = [SELECT Id, CPC__c FROM Opportunity];
        System.Assert.areEqual(true, oppsAfter[0].CPC__c, 'when adding a Meter Type To the Asset the Opp gets CPC__c = true');
        System.Assert.areEqual(true, oppsAfter[1].CPC__c, 'when adding a Meter Type To the Asset the Opp gets CPC__c = true');
        System.Assert.areEqual(true, oppsAfter[2].CPC__c, 'when adding a Meter Type To the Asset the Opp gets CPC__c = true');
        List<Meter_Type__c> mtToDelete = new List<Meter_Type__c>();
        mtToDelete.add(meterTypes[0]);
        mtToDelete.add(meterTypes[3]);
        mtToDelete.add(meterTypes[4]);
        mtToDelete.add(meterTypes[5]);
        mtToDelete.add(meterTypes[6]);
        delete mtToDelete;
        Test.stopTest();
        oppsAfter = [SELECT Id, CPC__c FROM Opportunity];
        System.Assert.areEqual(true, oppsAfter[0].CPC__c, 
            'when deleting a Meter Type the Opp keeps CPC__c = true if there is still at least one Meter Type left');
        System.Assert.areEqual(false, oppsAfter[1].CPC__c, 'when deleting a Meter Type the Opp gets CPC__c = false if there is no Meter Type left');
        // System.Assert.areEqual(false, oppsAfter[2].CPC__c); //this is very unlikely to be done by a user
    }
}