peac_dev/force-app/main/default/objects/Asset__c/Asset__c.object-meta.xml
<CustomObject>
    <label>Asset</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Asset Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Assets</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

peac_dev/force-app/main/default/objects/Asset__c/fields/City_Tax_Code__c.field-meta.xml
<CustomField>
    <fullName>City_Tax_Code__c</fullName>
    <label>City Tax Code</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Tax_Codes</valueSetName>
    </valueSet>
</CustomField>

peac_dev/force-app/main/default/objects/Asset__c/fields/Cost__c.field-meta.xml
<CustomField>
    <fullName>Cost__c</fullName>
    <inlineHelpText>Value will default from Opportunity on First Asset</inlineHelpText>
    <label>Cost</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

peac_dev/force-app/main/default/objects/Asset__c/fields/County_Tax_Code__c.field-meta.xml
<CustomField>
    <fullName>County_Tax_Code__c</fullName>
    <label>County Tax Code</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Tax_Codes</valueSetName>
    </valueSet>
</CustomField>

peac_dev/force-app/main/default/objects/Asset__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Value will default from Opportunity on First Asset</inlineHelpText>
    <label>Description</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

peac_dev/force-app/main/default/objects/Asset__c/fields/End_User_Billing_Address__c.field-meta.xml
<CustomField>
    <fullName>End_User_Billing_Address__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Want to utilize the Business address from the opportunity? If yes, check this box and select save. If not, provide the alternative address.</inlineHelpText>
    <label>End User Business Address?</label>
    <type>Checkbox</type>
</CustomField>

peac_dev/force-app/main/default/objects/Asset__c/fields/Equipment_City__c.field-meta.xml
<CustomField>
    <fullName>Equipment_City__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Equipment City</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

peac_dev/force-app/main/default/objects/Asset__c/fields/Equipment_Code__c.field-meta.xml
<CustomField>
    <fullName>Equipment_Code__c</fullName>
    <label>Equipment Code</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Asset_Equipment_Code</valueSetName>
    </valueSet>
</CustomField>

peac_dev/force-app/main/default/objects/Asset__c/fields/Equipment_Location_City__c.field-meta.xml
<CustomField>
    <fullName>Equipment_Location_City__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Equipment Location City</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

peac_dev/force-app/main/default/objects/Asset__c/fields/Equipment_Location_County__c.field-meta.xml
<CustomField>
    <fullName>Equipment_Location_County__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Equipment Location County</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

peac_dev/force-app/main/default/objects/Asset__c/fields/Equipment_State__c.field-meta.xml
<CustomField>
    <fullName>Equipment_State__c</fullName>
    <label>Equipment State</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>AL</fullName>
            </value>
            <value>
                <fullName>AK</fullName>
            </value>
            <value>
                <fullName>AS</fullName>
            </value>
            <value>
                <fullName>AZ</fullName>
            </value>
            <value>
                <fullName>AR</fullName>
            </value>
            <value>
                <fullName>CA</fullName>
            </value>
            <value>
                <fullName>CO</fullName>
            </value>
            <value>
                <fullName>CT</fullName>
            </value>
            <value>
                <fullName>DE</fullName>
            </value>
            <value>
                <fullName>DC</fullName>
            </value>
            <value>
                <fullName>FL</fullName>
            </value>
            <value>
                <fullName>GA</fullName>
            </value>
            <value>
                <fullName>GU</fullName>
            </value>
            <value>
                <fullName>HI</fullName>
            </value>
            <value>
                <fullName>ID</fullName>
            </value>
            <value>
                <fullName>IL</fullName>
            </value>
            <value>
                <fullName>IN</fullName>
            </value>
            <value>
                <fullName>IA</fullName>
            </value>
            <value>
                <fullName>KS</fullName>
            </value>
            <value>
                <fullName>KY</fullName>
            </value>
            <value>
                <fullName>LA</fullName>
            </value>
            <value>
                <fullName>ME</fullName>
            </value>
            <value>
                <fullName>MD</fullName>
            </value>
            <value>
                <fullName>MH</fullName>
            </value>
            <value>
                <fullName>MA</fullName>
            </value>
            <value>
                <fullName>MI</fullName>
            </value>
            <value>
                <fullName>FM</fullName>
            </value>
            <value>
                <fullName>MN</fullName>
            </value>
            <value>
                <fullName>MS</fullName>
            </value>
            <value>
                <fullName>MO</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

peac_dev/force-app/main/default/objects/Asset__c/fields/Equipment_Street__c.field-meta.xml
<CustomField>
    <fullName>Equipment_Street__c</fullName>
    <defaultValue>&quot;&quot;</defaultValue>
    <encryptionScheme>None</encryptionScheme>
    <label>Equipment Street</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

peac_dev/force-app/main/default/objects/Asset__c/fields/Equipment_Zip__c.field-meta.xml
<CustomField>
    <fullName>Equipment_Zip__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Equipment Zip</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

peac_dev/force-app/main/default/objects/Asset__c/fields/List_Price__c.field-meta.xml
<CustomField>
    <fullName>List_Price__c</fullName>
    <label>List Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

peac_dev/force-app/main/default/objects/Asset__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipName>Assets</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

peac_dev/force-app/main/default/objects/Asset__c/fields/Opportunity_Contract_Type__c.field-meta.xml
<CustomField>
    <fullName>Opportunity_Contract_Type__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Opportunity Contract Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

peac_dev/force-app/main/default/objects/Asset__c/fields/Property_Status__c.field-meta.xml
<CustomField>
    <fullName>Property_Status__c</fullName>
    <label>Property Tax Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>11</fullName>
                <label>11 - PPTX Admin Fee of $18.00</label>
            </value>
            <value>
                <fullName>10</fullName>
                <label>10 - Not Reportable</label>
            </value>
            <value>
                <fullName>01</fullName>
                <label>01 - Lessor Files / Bill Lessee</label>
            </value>
            <value>
                <fullName>02</fullName>
                <label>02 - Lessee Files / Do Not Bill</label>
            </value>
            <value>
                <fullName>03</fullName>
                <label>03 - Lessor Files / Lessee Financed</label>
            </value>
            <value>
                <fullName>04</fullName>
                <label>04 - Honeywell pptx in rental</label>
            </value>
            <value>
                <fullName>05</fullName>
                <label>05 - PPTX included in rental</label>
            </value>
            <value>
                <fullName>07</fullName>
                <label>07 - PPTX admin fee of $12.00</label>
            </value>
            <value>
                <fullName>08</fullName>
                <label>08 - PPTX admin fee of $15.00</label>
            </value>
            <value>
                <fullName>09</fullName>
                <label>09 - No admin fee charge</label>
            </value>
            <value>
                <fullName>12</fullName>
                <label>12 - PPTax Billing (Actual only)</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

peac_dev/force-app/main/default/objects/Asset__c/fields/Quantity__c.field-meta.xml
<CustomField>
    <fullName>Quantity__c</fullName>
    <defaultValue>1</defaultValue>
    <label>Quantity</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

peac_dev/force-app/main/default/objects/Asset__c/fields/State_Tax_Code__c.field-meta.xml
<CustomField>
    <fullName>State_Tax_Code__c</fullName>
    <label>State Tax Code</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Tax_Codes</valueSetName>
    </valueSet>
</CustomField>

peac_dev/force-app/main/default/objects/Asset__c/fields/Tax_Code__c.field-meta.xml
<CustomField>
    <fullName>Tax_Code__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Tax Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

peac_dev/force-app/main/default/objects/Asset__c/fields/Total_Upfront_Tax_Amount__c.field-meta.xml
<CustomField>
    <fullName>Total_Upfront_Tax_Amount__c</fullName>
    <formula>Upfront_County_Tax_Amount__c + Upfront_City_Transit_Tax_Amount__c + Upfront_City_Tax_Amount__c + Upfront_County_Transit_Tax_Amount__c + Upfront_State_Tax_Amount__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Total Upfront Tax Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

peac_dev/force-app/main/default/objects/Asset__c/fields/Upfront_City_Tax_Amount__c.field-meta.xml
<CustomField>
    <fullName>Upfront_City_Tax_Amount__c</fullName>
    <label>Upfront City Tax Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

peac_dev/force-app/main/default/objects/Asset__c/fields/Upfront_City_Transit_Tax_Amount__c.field-meta.xml
<CustomField>
    <fullName>Upfront_City_Transit_Tax_Amount__c</fullName>
    <label>Upfront City Transit Tax Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

peac_dev/force-app/main/default/objects/Asset__c/fields/Upfront_County_Tax_Amount__c.field-meta.xml
<CustomField>
    <fullName>Upfront_County_Tax_Amount__c</fullName>
    <label>Upfront County Tax Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

peac_dev/force-app/main/default/objects/Asset__c/fields/Upfront_County_Transit_Tax_Amount__c.field-meta.xml
<CustomField>
    <fullName>Upfront_County_Transit_Tax_Amount__c</fullName>
    <label>Upfront County Transit Tax Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

peac_dev/force-app/main/default/objects/Asset__c/fields/Upfront_State_Tax_Amount__c.field-meta.xml
<CustomField>
    <fullName>Upfront_State_Tax_Amount__c</fullName>
    <label>Upfront State Tax Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

peac_dev/force-app/main/default/objects/Asset__c/fields/Upfront_Tax_Code__c.field-meta.xml
<CustomField>
    <fullName>Upfront_Tax_Code__c</fullName>
    <label>Upfront Tax Code</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Tax_Codes</valueSetName>
    </valueSet>
</CustomField>

peac_dev/force-app/main/default/objects/Asset__c/fields/Upfront_Tax_Method__c.field-meta.xml
<CustomField>
    <fullName>Upfront_Tax_Method__c</fullName>
    <label>Upfront Tax Method</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>GRM</fullName>
            </value>
            <value>
                <fullName>PPM</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

peac_dev/force-app/main/default/objects/Asset__c/fields/Upfront_Tax_Paid_To__c.field-meta.xml
<CustomField>
    <fullName>Upfront_Tax_Paid_To__c</fullName>
    <label>Upfront Tax Paid To</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>State</fullName>
            </value>
            <value>
                <fullName>County</fullName>
            </value>
            <value>
                <fullName>City</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

peac_dev/force-app/main/default/classes/TC_CheckAssetFieldsWhenBookingStage.cls
public class TC_CheckAssetFieldsWhenBookingStage {
    public static Marlin_Configuration__c config = Marlin_Configuration__c.getOrgDefaults ();
public static void checkAssetFieldsWhenBookingStage (Map <Id, Opportunity> oldMap, Map <Id, Opportunity> newMap) {
        
        Set <Id> bookingOppIds = new Set <Id> ();
        // only on change to booking stage
        for (Opportunity opp : newMap.values ()) {
            if (!opp.Loan_Record_Type__c && opp.StageName == 'Booking' && opp.StageName != oldMap.get (opp.Id).StageName) {
                bookingOppIds.add (opp.Id);
            }
        }
        
        if (!bookingOppIds.isEmpty ()) {
            List <Opportunity> oppsWithAssets = new List <Opportunity > ([SELECT Id, Name, (SELECT Id, Name, Opportunity__c, Description__c, List_Price__c, Cost__c, Quantity__c, Equipment_Code__c, Property_Status__c, Tax_Code__c, State_Tax_Code__c, City_Tax_Code__c, Equipment_Street__c, Equipment_City__c, Equipment_State__c, Equipment_Zip__c, End_User_Billing_Address__c, Upfront_Tax_Code__c, Upfront_Tax_Paid_To__c, County_Tax_Code__c, Upfront_Tax_Method__c, Upfront_State_Tax_Amount__c, Upfront_County_Transit_Tax_Amount__c, Upfront_County_Tax_Amount__c, Upfront_City_Transit_Tax_Amount__c, Upfront_City_Tax_Amount__c, Total_Upfront_Tax_Amount__c, Opportunity_Contract_Type__c, Equipment_Location_City__c, Equipment_Location_County__c, Equipment_Location_State__c  FROM Assets__r) FROM Opportunity WHERE Id IN :bookingOppIds]);
            
            for (Opportunity opp : oppsWithAssets) {
                List <String> errors = new List <String> ();
                for (Asset__c asset : opp.Assets__r) {
                    TC_RequiredFieldHelper.assetEnterBookingStage (asset, errors);
                    if (!errors.isEmpty () && config != null && config.Apex_Validations_Active__c) newMap.get (asset.Opportunity__c).addError ('Asset ' + asset.Name + ': ' + errors + ' required when stage is changed to Booking');
                }
            }
        }
        
    }
}