peac_dev/force-app/main/default/objects/Asset__c/Asset__c.object-meta.xml
<CustomObject>
    <label>Asset</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Asset Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Assets</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

peac_dev/force-app/main/default/objects/Asset__c/fields/Equipment_Code__c.field-meta.xml
<CustomField>
    <fullName>Equipment_Code__c</fullName>
    <label>Equipment Code</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Asset_Equipment_Code</valueSetName>
    </valueSet>
</CustomField>

peac_dev/force-app/main/default/objects/Asset__c/fields/Equipment_Sub_Category__c.field-meta.xml
<CustomField>
    <fullName>Equipment_Sub_Category__c</fullName>
    <label>Equipment Sub-Category</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Equipment_Code__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>Equipment_Sub_Category</valueSetName>
    </valueSet>
</CustomField>

peac_dev/force-app/main/default/objects/Asset__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipName>Assets</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

peac_dev/force-app/main/default/objects/Payee__c/Payee__c.object-meta.xml
<CustomObject>
    <label>Payee</label>
    <nameField>
        <displayFormat>PAY-{000000}</displayFormat>
        <label>Payee Indentification</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payees</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

peac_dev/force-app/main/default/objects/Payment__c/Payment__c.object-meta.xml
<CustomObject>
    <description>Payments to a Payee related to an opportunity</description>
    <label>Payment</label>
    <nameField>
        <displayFormat>PYMT-{0}</displayFormat>
        <label>Payment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

peac_dev/force-app/main/default/objects/Payment__c/fields/Date_Sent_to_External_System__c.field-meta.xml
<CustomField>
    <fullName>Date_Sent_to_External_System__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Date Sent to External System</label>
    <type>DateTime</type>
</CustomField>

peac_dev/force-app/main/default/objects/Payment__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <inlineHelpText>Opportunity related to this payment</inlineHelpText>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Payments</relationshipLabel>
    <relationshipName>Payments</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

peac_dev/force-app/main/default/objects/Payment__c/fields/Payee__c.field-meta.xml
<CustomField>
    <fullName>Payee__c</fullName>
    <inlineHelpText>Payee related to this payment</inlineHelpText>
    <label>Payee</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 AND 2 AND 3</booleanFilter>
        <errorMessage>Value does not exist or does not match filter criteria or the Payee in Inactive</errorMessage>
        <filterItems>
            <field>Payee__c.SL_Vendor_ID__c</field>
            <operation>notEqual</operation>
            <value></value>
        </filterItems>
        <filterItems>
            <field>Payee__c.Active__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <filterItems>
            <field>Payee__c.Payee_Name__c</field>
            <operation>notContain</operation>
            <value>Do Not</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Payee__c</referenceTo>
    <relationshipLabel>Payments</relationshipLabel>
    <relationshipName>Payments</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

peac_dev/force-app/main/default/objects/Payment__c/fields/Payment_Status__c.field-meta.xml
<CustomField>
    <fullName>Payment_Status__c</fullName>
    <label>Payment Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>Ready to Send</fullName>
            </value>
            <value>
                <fullName>Payment Sent</fullName>
            </value>
            <value>
                <fullName>Payment Confirmed</fullName>
                <label>Payment Acknowledged</label>
            </value>
            <value>
                <fullName>Payment Released</fullName>
            </value>
            <value>
                <fullName>Void/Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

peac_dev/force-app/main/default/classes/TC_LGHTNSendPaymentsCTRL.cls
public class TC_LGHTNSendPaymentsCTRL {
    
    @auraEnabled
    public static Integer sendPayments (Id recId) {
        
        // NOTE: recId can be an Opportunity or a Payment__c
        
        try {
            
            List <Payment__c> payments = new List <Payment__c> ();
            
            // begin: SAL-1509
            Id currentUserId = UserInfo.getUserId();
            User currentUser = [SELECT CMS_Credit_Authority_Lease__c, ProfileId, Profile.Name FROM User WHERE Id = :currentUserId LIMIT 1][0];
            Decimal CMSAuthorityLimit = currentUser.CMS_Credit_Authority_Lease__c;
            AuraHandledException ae_Authority = new AuraHandledException  ('Equipment Cost is greater than user\'s CMS Credit Authority (Lease).'); 
            ae_Authority.setMessage ('Equipment Cost is greater than user\'s CMS Credit Authority (Lease).');
            // end: SAL-1509
            
            Opportunity opp;
            // Asset logic check
            List <Asset__c> assets = new List <Asset__c> ();
            
            if (recId.getSObjectType () == Schema.Opportunity.getSObjectType ()) {

                assets = queryAssets (recId);

                payments = [SELECT Id, Payee__c FROM Payment__c WHERE Opportunity__c = :recId AND Payment_Status__c = 'Ready to Send'];
                
                // begin: SAL-1509
                opp = [SELECT Id, Equipment_Cost__c, Last_Funded_By__c, Loan_Record_Type__c, StageName FROM Opportunity WHERE Id = :recId LIMIT 1][0];  
                if (opp.Loan_Record_Type__c == false && currentUser.ProfileId != null && (currentUser.Profile.Name == 'CMS' || currentUser.Profile.Name == 'Partner Ambassador') && (CMSAuthorityLimit == null || (opp != null && opp.Equipment_Cost__c > CMSAuthorityLimit))) throw ae_Authority;
                // end: SAL-1509
                 
                // START: SAL-1664
                if(opp.Loan_Record_Type__c == false && opp.StageName != 'Funding'){
                    AuraHandledException ae = new AuraHandledException  ('Opportunity Stage is not Funding.'); 
                    ae.setMessage ('Opportunity Stage is not Funding.');
                    throw ae;
                }
                // END: SAL-1664
                
            } else {
                payments = [SELECT Id, Payee__c, Opportunity__c FROM Payment__c WHERE Id = :recId AND Payment_Status__c = 'Ready to Send'];
                
                // begin: SAL-1509
                Id oppId = payments[0].Opportunity__c;                
                opp = [SELECT Id, Equipment_Cost__c, Last_Funded_By__c, Loan_Record_Type__c, StageName FROM Opportunity WHERE Id = :oppId LIMIT 1][0];  
                
                if (opp.Loan_Record_Type__c == false && currentUser.ProfileId != null && (currentUser.Profile.Name == 'CMS' || currentUser.Profile.Name == 'Partner Ambassador') &&  (CMSAuthorityLimit == null || (opp != null && opp.Equipment_Cost__c > CMSAuthorityLimit))) throw ae_Authority;
                // end: SAL-1509
                
                // START: SAL-1664
                if(opp.Loan_Record_Type__c == false && opp.StageName != 'Funding'){
                    AuraHandledException ae = new AuraHandledException  ('Opportunity Stage is not Funding.'); 
                    ae.setMessage ('Opportunity Stage is not Funding.');
                    throw ae;
                }
                // END: SAL-1664

                assets = queryAssets (oppId);
            }

            // if equipment code label contains general sub category is required
            Map <String, String> labelMap = TC_PicklistUtil.getLabelMap(Asset__c.Equipment_Code__c);
            Map <String, String> subCatLabelMap = TC_PicklistUtil.getLabelMap(Asset__c.Equipment_Sub_Category__c);

            for (Asset__c asset : assets) {
                if (String.isEmpty(asset.Equipment_Code__c)) {
                    throwException ('Equipment Code is required on Asset: ' + asset.Name);
                } else if (labelMap.get (asset.Equipment_Code__c).containsIgnoreCase('general') && (String.isEmpty(asset.Equipment_Sub_Category__c) || subCatLabelMap.get (asset.Equipment_Sub_Category__c).containsIgnoreCase('general')) ) {
                    throwException (labelMap.get (asset.Equipment_Code__c) + ' equipment code requires a non General Sub Category on Asset: ' + asset.Name);
                }
            }
            
            if (payments != null && !payments.isEmpty ()) {
                Solomon.SendPayments (payments);
            } else {
                // no payments to send  
                AuraHandledException ae = new AuraHandledException  ('No payments are ready to send'); 
                ae.setMessage ('No payments are ready to send');
                throw ae;
            }
            
            List <Payment__c> updateList = new List <Payment__c> ();
            
            for (Payment__c payment : payments) {
                updateList.add (new Payment__c (Id = payment.Id
                                                , Payment_Status__c = 'Payment Sent'
                                                , Date_Sent_to_External_System__c = Datetime.now ()));
            }
            
            update updateList;
            
            // begin: SAL-1510
            if (opp.Last_Funded_By__c == null) update new Opportunity (Id = opp.Id, Last_Funded_By__c = currentUserId);
            // end: SAL-1510



            
            return payments.size ();
        } catch (Exception e) {
            AuraHandledException ae = new AuraHandledException  (e.getMessage ()); 
            ae.setMessage (e.getMessage ());
            throw ae;
        }
        
    }

    private static List <Asset__C> queryAssets (Id oppId) {
        return new List <Asset__C> ([SELECT Id, Name, Equipment_Code__c, Equipment_Sub_Category__c FROM Asset__C WHERE Opportunity__c = :oppId]);
    }

    @testvisible private static void throwException (String message) {
        AuraHandledException ae = new AuraHandledException  (message);
        ae.setMessage (message);
        throw ae;
    }
}