peac_dev/force-app/main/default/objects/Asset__c/Asset__c.object-meta.xml
<CustomObject>
    <label>Asset</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Asset Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Assets</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

peac_dev/force-app/main/default/objects/Contract_Asset__c/Contract_Asset__c.object-meta.xml
<CustomObject>
    <label>Contract Asset</label>
    <nameField>
        <displayFormat>CA-{0000}</displayFormat>
        <label>Contract Asset Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contract Assets</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

peac_dev/force-app/main/default/objects/Contract_Asset__c/fields/Dealer_Repurchase_Date__c.field-meta.xml
<CustomField>
    <fullName>Dealer_Repurchase_Date__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Dealer Repurchase Date</label>
    <type>Date</type>
</CustomField>

peac_dev/force-app/main/default/objects/Contract_Asset__c/fields/Gross_Sale_Price__c.field-meta.xml
<CustomField>
    <fullName>Gross_Sale_Price__c</fullName>
    <label>Gross Sale Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

peac_dev/force-app/main/default/objects/Contract_Asset__c/fields/Status2__c.field-meta.xml
<CustomField>
    <fullName>Status2__c</fullName>
    <label>Asset Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Accessory</fullName>
            </value>
            <value>
                <fullName>Buyout to Keep</fullName>
            </value>
            <value>
                <fullName>Deleted</fullName>
            </value>
            <value>
                <fullName>Disposed</fullName>
            </value>
            <value>
                <fullName>Disposed - Customer</fullName>
            </value>
            <value>
                <fullName>DLR Repurchase</fullName>
            </value>
            <value>
                <fullName>Duplicate</fullName>
            </value>
            <value>
                <fullName>Equipment Received</fullName>
            </value>
            <value>
                <fullName>In Transit</fullName>
            </value>
            <value>
                <fullName>Non-Serialized Asset</fullName>
            </value>
            <value>
                <fullName>Non-Xerox Owned</fullName>
            </value>
            <value>
                <fullName>On Contract</fullName>
            </value>
            <value>
                <fullName>Pending Return</fullName>
            </value>
            <value>
                <fullName>Proceeds Received</fullName>
            </value>
            <value>
                <fullName>Recycled</fullName>
            </value>
            <value>
                <fullName>Repossession Requested</fullName>
            </value>
            <value>
                <fullName>Sold</fullName>
            </value>
            <value>
                <fullName>Received</fullName>
                <isActive>false</isActive>
                <label>Received</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

peac_dev/force-app/main/default/objects/Contract_Asset__c/fields/Status_Date__c.field-meta.xml
<CustomField>
    <fullName>Status_Date__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Status Date</label>
    <type>Date</type>
</CustomField>

peac_dev/force-app/main/default/objects/Invoice_Asset__c/Invoice_Asset__c.object-meta.xml
<CustomObject>
    <label>Invoice Asset</label>
    <nameField>
        <displayFormat>IA-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoice Assets</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

peac_dev/force-app/main/default/objects/Invoice_Asset__c/fields/Asset__c.field-meta.xml
<CustomField>
    <fullName>Asset__c</fullName>
    <label>Asset</label>
    <referenceTo>Contract_Asset__c</referenceTo>
    <relationshipLabel>Invoice Assets</relationshipLabel>
    <relationshipName>Invoice_Assets</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

peac_dev/force-app/main/default/classes/SL_InvoiceAssetTriggerHandler.cls
public class SL_InvoiceAssetTriggerHandler extends SL_Trigger.baseHandler{
    private Map<Id, List<String>> fieldsChangedById = new Map<Id, List<String>>();
    Map<Id, Contract_Asset__c> contractAssets = new Map<Id, Contract_Asset__c>();
    private Set<Id> invoiceAssetIds = new Set<Id>();
    
    public override void afterInsert(Map<Id,sObject> newMap){
        for (Id invoiceAssetId :newMap.keySet()){
            getLookupMaps(newMap.get(invoiceAssetId));
        }
        afterChangesToOthers(true, newMap);
    }

    // private void checkUpdatedFields(Map<Id, SObject> oldMap, Map<Id, SObject> newMap){
    //     List<String> fieldsToCheck = null;
    //     if(Trigger.isBefore){
    //         fieldsToCheck = new List<String>{'Name'};
    //     }else{// isAfter
    //         fieldsToCheck = new List<String>{'Name'};
    //     }
        
    //     for(Id recordId : newMap.keySet()){
    //         SObject newObj = newMap.get(recordId);
    //         SObject oldObj = oldMap.get(recordId);
    //         SL_TriggerUtil.findChangedFields(recordId, newObj, oldObj, fieldsChangedById, fieldsToCheck);
    //     }
    // }

    private void getLookupMaps(SObject obj){
        Invoice_Asset__c theInvoiceAsset = (Invoice_Asset__c)obj;
        if(theInvoiceAsset.Asset__c != null){
            this.contractAssets.put(theInvoiceAsset.Asset__c, new Contract_Asset__c());
        }
        if(theInvoiceAsset.Id != null){
            this.invoiceAssetIds.add(theInvoiceAsset.Id);           
        }
    }

    private void getInfoFromOthers(){
        if(invoiceAssetIds.size() > 0){
            for(Invoice_Asset__c related : [SELECT Id, Asset__r.Status2__c, Asset__r.Status_Date__c, Asset__r.Gross_Sale_Price__c
                FROM Invoice_Asset__c WHERE Id IN :invoiceAssetIds]){
                if(this.contractAssets.get(related.Asset__c) != null){
                    this.contractAssets.put(related.Asset__c, related.Asset__r);
                }
            }
        }
        // uncomment when we have beforeInsert scenario, or Contract asset lookup changed in beforeUpdate
        // if(this.contractAssets.size() > 0 && SL_TriggerUtil.checkForMissingInfo(this.contractAssets.values())){
        //     this.contractAssets.putAll([SELECT Id, Status2__c, Status_Date__c, Gross_Sale_Price__c
        //         FROM Contract_Asset__c WHERE Id IN :this.contractAssets.keySet()]);
        // }
    }

    private void afterChangesToOthers(Boolean isNew, Map<Id, SObject> newMap){
        List<Contract_Asset__c> UpdatecaList = new List<Contract_Asset__c>();
        getInfoFromOthers();
        for(SObject obj :newMap.values()){
            Invoice_Asset__c theInvoiceAsset = (Invoice_Asset__c) obj;
            Contract_Asset__c relatedCAsset = this.contractAssets.get(theInvoiceAsset.Asset__c);
            // List<String> fieldsChanged = fieldsChangedById.get(theInvoiceAsset.Id);
            if(isNew && relatedCAsset != null){// right now we only have afterInsert
                relatedCAsset.Status2__c='DLR Repurchase';
                relatedCAsset.Status_Date__c = Date.Today();
                relatedCAsset.Dealer_Repurchase_Date__c = Date.Today();
                relatedCAsset.Gross_Sale_Price__c = theInvoiceAsset.Unit_Price__c;
                UpdatecaList.add(relatedCAsset);
            }
        }
        if(UpdatecaList.size()>0){
            update UpdatecaList;
        }
    }

}