peac_dev/force-app/main/default/objects/Asset__c/Asset__c.object-meta.xml
<CustomObject>
    <label>Asset</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Asset Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Assets</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

peac_dev/force-app/main/default/objects/Contract__c/Contract__c.object-meta.xml
<CustomObject>
    <description>Custom Object created so we can use Queue functionality</description>
    <label>Contract</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Contract Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Contracts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

peac_dev/force-app/main/default/objects/Contract__c/fields/Memo__c.field-meta.xml
<CustomField>
    <fullName>Memo__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Memo</label>
    <type>TextArea</type>
</CustomField>

peac_dev/force-app/main/default/objects/Contract__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Disposed</fullName>
            </value>
            <value>
                <fullName>Disposed - Charged Off</fullName>
            </value>
            <value>
                <fullName>Renewal</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

peac_dev/force-app/main/default/objects/Contract_Asset__c/Contract_Asset__c.object-meta.xml
<CustomObject>
    <label>Contract Asset</label>
    <nameField>
        <displayFormat>CA-{0000}</displayFormat>
        <label>Contract Asset Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contract Assets</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

peac_dev/force-app/main/default/objects/Contract_Asset__c/fields/Contract__c.field-meta.xml
<CustomField>
    <fullName>Contract__c</fullName>
    <label>Contract</label>
    <referenceTo>Contract__c</referenceTo>
    <relationshipLabel>Contract Assets</relationshipLabel>
    <relationshipName>Contract_Assets</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

peac_dev/force-app/main/default/objects/Contract_Asset__c/fields/Dealer_Repurchase_Date__c.field-meta.xml
<CustomField>
    <fullName>Dealer_Repurchase_Date__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Dealer Repurchase Date</label>
    <type>Date</type>
</CustomField>

peac_dev/force-app/main/default/objects/Contract_Asset__c/fields/Gross_Sale_Price__c.field-meta.xml
<CustomField>
    <fullName>Gross_Sale_Price__c</fullName>
    <label>Gross Sale Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

peac_dev/force-app/main/default/objects/Contract_Asset__c/fields/Status2__c.field-meta.xml
<CustomField>
    <fullName>Status2__c</fullName>
    <label>Asset Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Accessory</fullName>
            </value>
            <value>
                <fullName>Buyout to Keep</fullName>
            </value>
            <value>
                <fullName>Deleted</fullName>
            </value>
            <value>
                <fullName>Disposed</fullName>
            </value>
            <value>
                <fullName>Disposed - Customer</fullName>
            </value>
            <value>
                <fullName>DLR Repurchase</fullName>
            </value>
            <value>
                <fullName>Duplicate</fullName>
            </value>
            <value>
                <fullName>Equipment Received</fullName>
            </value>
            <value>
                <fullName>In Transit</fullName>
            </value>
            <value>
                <fullName>Non-Serialized Asset</fullName>
            </value>
            <value>
                <fullName>Non-Xerox Owned</fullName>
            </value>
            <value>
                <fullName>On Contract</fullName>
            </value>
            <value>
                <fullName>Pending Return</fullName>
            </value>
            <value>
                <fullName>Proceeds Received</fullName>
            </value>
            <value>
                <fullName>Recycled</fullName>
            </value>
            <value>
                <fullName>Repossession Requested</fullName>
            </value>
            <value>
                <fullName>Sold</fullName>
            </value>
            <value>
                <fullName>Received</fullName>
                <isActive>false</isActive>
                <label>Received</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

peac_dev/force-app/main/default/objects/Contract_Asset__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>DP-905</description>
    <formula>IF(ISBLANK(Asset_Disposed_Date__c), &quot;Active&quot;, &quot;Disposed&quot;)</formula>
    <label>Status</label>
    <type>Text</type>
</CustomField>

peac_dev/force-app/main/default/objects/Contract_Asset__c/fields/Status_Date__c.field-meta.xml
<CustomField>
    <fullName>Status_Date__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Status Date</label>
    <type>Date</type>
</CustomField>

peac_dev/force-app/main/default/objects/Invoice__c/Invoice__c.object-meta.xml
<CustomObject>
    <label>Invoice</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Invoice #</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

peac_dev/force-app/main/default/objects/Invoice__c/fields/Contract__c.field-meta.xml
<CustomField>
    <fullName>Contract__c</fullName>
    <label>Contract</label>
    <referenceTo>Contract__c</referenceTo>
    <relationshipLabel>Invoices</relationshipLabel>
    <relationshipName>Invoices</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

peac_dev/force-app/main/default/objects/Invoice__c/fields/Date_Due__c.field-meta.xml
<CustomField>
    <fullName>Date_Due__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Date Due</label>
    <type>Date</type>
</CustomField>

peac_dev/force-app/main/default/objects/Invoice__c/fields/Invoice_Date__c.field-meta.xml
<CustomField>
    <fullName>Invoice_Date__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Invoice Date</label>
    <type>Date</type>
</CustomField>

peac_dev/force-app/main/default/objects/Invoice_Asset__c/Invoice_Asset__c.object-meta.xml
<CustomObject>
    <label>Invoice Asset</label>
    <nameField>
        <displayFormat>IA-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoice Assets</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

peac_dev/force-app/main/default/objects/Invoice_Asset__c/fields/Asset__c.field-meta.xml
<CustomField>
    <fullName>Asset__c</fullName>
    <label>Asset</label>
    <referenceTo>Contract_Asset__c</referenceTo>
    <relationshipLabel>Invoice Assets</relationshipLabel>
    <relationshipName>Invoice_Assets</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

peac_dev/force-app/main/default/objects/Invoice_Asset__c/fields/Invoice__c.field-meta.xml
<CustomField>
    <fullName>Invoice__c</fullName>
    <label>Invoice</label>
    <referenceTo>Repurchase_Invoice__c</referenceTo>
    <relationshipLabel>Invoice Assets</relationshipLabel>
    <relationshipName>Invoice_Assets</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

peac_dev/force-app/main/default/objects/Repurchase_Invoice__c/Repurchase_Invoice__c.object-meta.xml
<CustomObject>
    <label>Repurchase Invoice</label>
    <nameField>
        <displayFormat>DINV-{0000}</displayFormat>
        <label>Repurchase Invoice #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Repurchase Invoices</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

peac_dev/force-app/main/default/objects/Repurchase_Invoice__c/fields/Contract__c.field-meta.xml
<CustomField>
    <fullName>Contract__c</fullName>
    <label>Contract</label>
    <referenceTo>Contract__c</referenceTo>
    <relationshipLabel>Repurchase Invoices</relationshipLabel>
    <relationshipName>Repurchase_Invoices</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

peac_dev/force-app/main/default/objects/Repurchase_Invoice__c/fields/Memo__c.field-meta.xml
<CustomField>
    <fullName>Memo__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Memo</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

peac_dev/force-app/main/default/objects/Repurchase_Invoice__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Invoice Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Open</fullName>
            </value>
            <value>
                <fullName>Paid</fullName>
            </value>
            <value>
                <fullName>Delinquent</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

peac_dev/force-app/main/default/objects/Repurchase_Invoice__c/fields/Term__c.field-meta.xml
<CustomField>
    <fullName>Term__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Term</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

peac_dev/force-app/main/default/classes/SL_Invoice_AssetTriggerHandlerTest.cls
@isTest
public class SL_Invoice_AssetTriggerHandlerTest {

    @isTest
    public static void testInsert(){
        SL_SCTestData.createAccountAndContracts(1, 1);
        SL_SCTestData.createInsurancesAndContractAssets(1, 2);
        Repurchase_Invoice__c ri = new Repurchase_Invoice__c();
        ri.Contract__c=SL_SCTestData.testContracts[0].ID;
        ri.Invoice_Date__c= Date.today();
        ri.Memo__c='Dealer Invoicing';
        ri.Term__c='Net 15';
        ri.Date_Due__c= Date.today().addDays(15);
        ri.Status__c = 'Open';        
        insert ri;
        Invoice_Asset__c ia = new Invoice_Asset__c();
        ia.Invoice__c = ri.Id;
        ia.Asset__c = SL_SCTestData.testCAssets[0].id;
        ia.Unit_Price__c = 12;
        Invoice_Asset__c ia2 = new Invoice_Asset__c();
        ia2.Invoice__c = ri.Id;
        ia2.Asset__c = SL_SCTestData.testCAssets[1].id;
        ia2.Unit_Price__c = 120;
        List<Invoice_Asset__c> ias = new List<Invoice_Asset__c>();
        ias.add(ia);
        ias.add(ia2);
        Test.startTest();
        insert ias;
        Test.stopTest();
        List<Invoice_Asset__c> iasAfter = [SELECT Id, Asset__r.Status2__c, Asset__r.Status_Date__c,  Asset__r.Dealer_Repurchase_Date__c,
             Asset__r.Gross_Sale_Price__c, Unit_Price__c
            FROM Invoice_Asset__c];
        System.Assert.areEqual('DLR Repurchase', iasAfter[0].Asset__r.Status2__c, 'When invoice Asset is created Status2__c is stamped the value DLR Repurchase on the related Contract Asset');
        System.Assert.areEqual(Date.today(), iasAfter[0].Asset__r.Status_Date__c, 'When invoice Asset is created the current date is stamped in the field Status_Date__c on the related Contract Asset');
        System.Assert.areEqual(Date.today(), iasAfter[0].Asset__r.Dealer_Repurchase_Date__c, 'When invoice Asset is created the current date is stamped in the field Dealer_Repurchase_Date__c on the related Contract Asset');
        System.Assert.areEqual(iasAfter[0].Unit_Price__c, iasAfter[0].Asset__r.Gross_Sale_Price__c, 'The unit price in invoice Asset is stamped to the Gross Sale Price of the related Contract Asset');
        System.Assert.areEqual(iasAfter[1].Unit_Price__c, iasAfter[1].Asset__r.Gross_Sale_Price__c, 'The unit price in invoice Asset is stamped to the Gross Sale Price of the related Contract Asset');
    }
}