peac_dev/force-app/main/default/objects/Integration_Log__c/Integration_Log__c.object-meta.xml
<CustomObject>
    <description>To collect all the custom integration exceptions</description>
    <label>Integration Log</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Interface Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Integration Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

peac_dev/force-app/main/default/objects/Integration_Log__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Integration Logs</relationshipLabel>
    <relationshipName>Integration_Logs</relationshipName>
    <type>Lookup</type>
</CustomField>

peac_dev/force-app/main/default/objects/Integration_Log__c/fields/Callout_Duration__c.field-meta.xml
<CustomField>
    <fullName>Callout_Duration__c</fullName>
    <label>Callout Duration (milliseconds)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

peac_dev/force-app/main/default/objects/Integration_Log__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Integration Logs</relationshipLabel>
    <relationshipName>Integration_Logs</relationshipName>
    <type>Lookup</type>
</CustomField>

peac_dev/force-app/main/default/objects/Integration_Log__c/fields/Error_Code__c.field-meta.xml
<CustomField>
    <fullName>Error_Code__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Error Code</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

peac_dev/force-app/main/default/objects/Integration_Log__c/fields/Error_Message__c.field-meta.xml
<CustomField>
    <fullName>Error_Message__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Error Message</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

peac_dev/force-app/main/default/objects/Integration_Log__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Integration Logs</relationshipLabel>
    <relationshipName>Integration_Logs</relationshipName>
    <type>Lookup</type>
</CustomField>

peac_dev/force-app/main/default/objects/Integration_Log__c/fields/Record_Id__c.field-meta.xml
<CustomField>
    <fullName>Record_Id__c</fullName>
    <description>It holds the Id field of integration(Salesforce Id/ External Id)</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Object Id</label>
    <length>32</length>
    <type>Text</type>
</CustomField>

peac_dev/force-app/main/default/objects/Integration_Log__c/fields/Request_Message__c.field-meta.xml
<CustomField>
    <fullName>Request_Message__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Request Message</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

peac_dev/force-app/main/default/objects/Integration_Log__c/fields/Response_Message__c.field-meta.xml
<CustomField>
    <fullName>Response_Message__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Response Message</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

peac_dev/force-app/main/default/objects/Integration_Log__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Success</fullName>
            </value>
            <value>
                <fullName>Error</fullName>
            </value>
            <value>
                <fullName>Failure</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

peac_dev/force-app/main/default/classes/MARLIN_IntegrationLog.cls
public class MARLIN_IntegrationLog {
/****************************************************************************************
* @Author       Huron Team
* @Date         April 04, 2017
* @Description  Integration Call
*****************************************************************************************/	
    public static void LogException(String aIntName,String aRecordId, String aStatus,String aReqMessage,String aResMessage,String aErrCode,String aErrMessage){
        
        Integration_Log__c lIntLog = new Integration_Log__c(
            Name = aIntName,
            Record_Id__c = aRecordId,
            Status__c = aStatus,
            Request_Message__c = (aReqMessage.length() > 32000 ? aReqMessage.left(32000) : aReqMessage),
            Response_Message__c = aResMessage,
            Error_Code__c = aErrCode,
            Error_Message__c = aErrMessage
        );
        
        try{
        	if(System.Label.IntegrationLogFlag == 'Y')
             	insert lIntLog;        
               
        	}catch( QueryException ex ){
        	// supressing error;
        }
    }
    
    @Future
       public static void LogExceptionAsynch(String aIntName,String aRecordId, String aStatus,String aReqMessage,String aResMessage,String aErrCode,String aErrMessage){

        Integration_Log__c lIntLog = new Integration_Log__c(
            Name = aIntName,
            Record_Id__c = aRecordId,
            Status__c = aStatus,
            Request_Message__c = aReqMessage,
            Response_Message__c = aResMessage,
            Error_Code__c = aErrCode,
            Error_Message__c = aErrMessage
        );

        try{
            if(System.Label.IntegrationLogFlag == 'Y')
                insert lIntLog;        
               
        	}catch( QueryException ex ){
        	// supressing error;
        }
    }

    public static Integer startTime = 0;
    public static Integer calloutDuration = 0;

    public static void startDurationTimer() {
        startTime = Limits.getCpuTime();
    }
    public static void endDurationTimer() {
        calloutDuration =  Limits.getCpuTime() - startTime;
    }
    
    // Tamarack Added, bulk logging
    public static List <Integration_Log__c> logs = new List <Integration_Log__c>();
    
    public static void addLog (String aIntName,String aRecordId, String aStatus,String aReqMessage,String aResMessage,String aErrCode,String aErrMessage) {
        logs.add (
            new Integration_Log__c(
                Name = aIntName, 
                Record_Id__c = aRecordId, 
                Status__c = aStatus, 
                Request_Message__c = trimMessage (aReqMessage, 32000), 
                Response_Message__c = trimMessage(aResMessage,131071), 
                Error_Code__c = aErrCode, 
                Error_Message__c = trimMessage(aErrMessage,32767),
                Callout_Duration__c = calloutDuration
                )
            );
    }
    
    private static String trimMessage (String message, Integer fieldLimit) {
         return message != null && message.length() >= fieldLimit ? message.left(fieldLimit) : message;
    }
    
    public static void insertLogs () {
        if (System.Label.IntegrationLogFlag == 'Y') {
            try {
                // tam update
                for (Integration_Log__c log : logs) {
                    if (log.Record_Id__c != null && log.Record_Id__c instanceof Id && Id.valueOf (log.Record_Id__c).getSObjectType() == Schema.Opportunity.SObjectType) log.Opportunity__c = log.Record_Id__c;
                	if (log.Record_Id__c != null && log.Record_Id__c instanceof Id && Id.valueOf (log.Record_Id__c).getSObjectType() == Schema.Account.SObjectType) log.Account__c = log.Record_Id__c;
                    if (log.Record_Id__c != null && log.Record_Id__c instanceof Id && Id.valueOf (log.Record_Id__c).getSObjectType() == Schema.Contact.SObjectType) log.Contact__c = log.Record_Id__c;
                }
                insert logs;
                logs = new List <Integration_Log__c> ();
            } catch (Exception e) {
                System.debug ('Error logging errors');
            }
        }
    }
    
}