peac_dev/force-app/main/default/objects/Bank_Information__c/Bank_Information__c.object-meta.xml
<CustomObject>
    <label>Bank Information</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Bank Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Bank Information</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

peac_dev/force-app/main/default/objects/Bank_Information__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Bank Information</relationshipLabel>
    <relationshipName>Bank_Information</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

peac_dev/force-app/main/default/objects/Bank_Statement__c/Bank_Statement__c.object-meta.xml
<CustomObject>
    <label>Bank Statement</label>
    <nameField>
        <displayFormat>STMT-{0000000}</displayFormat>
        <label>Bank Statement Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Bank Statements</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

peac_dev/force-app/main/default/objects/Bank_Statement__c/fields/Bank_Information__c.field-meta.xml
<CustomField>
    <fullName>Bank_Information__c</fullName>
    <label>Bank Information</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Financial_Bank_Information__c.Opportunity__c</field>
            <operation>equals</operation>
            <valueField>$Source.Opportunity__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Financial_Bank_Information__c</referenceTo>
    <relationshipLabel>Bank Statements</relationshipLabel>
    <relationshipName>Bank_Statements</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

peac_dev/force-app/main/default/objects/Bank_Statement__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Bank Statements</relationshipLabel>
    <relationshipName>Bank_Statements</relationshipName>
    <type>Lookup</type>
</CustomField>

peac_dev/force-app/main/default/objects/Financial__c/Financial__c.object-meta.xml
<CustomObject>
    <description>This object is created to store financial related information on Opportunity.</description>
    <label>Financial</label>
    <nameField>
        <displayFormat>FD-{000}</displayFormat>
        <label>Financial Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Financials</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

peac_dev/force-app/main/default/objects/Financial__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <description>Opportunity as master object.</description>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Financials</relationshipLabel>
    <relationshipName>Financials_Opportunity</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

peac_dev/force-app/main/default/objects/Financial_Bank_Information__c/Financial_Bank_Information__c.object-meta.xml
<CustomObject>
    <label>Bank Information</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Bank Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Bank Information</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

peac_dev/force-app/main/default/objects/Financial_Bank_Information__c/fields/Bank_Account_Number_No_Masking__c.field-meta.xml
<CustomField>
    <fullName>Bank_Account_Number_No_Masking__c</fullName>
    <description>Store Bank account number without masking</description>
    <encryptionScheme>CaseSensitiveDeterministicEncryption</encryptionScheme>
    <label>Account Number</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

peac_dev/force-app/main/default/objects/Financial_Bank_Information__c/fields/Financial__c.field-meta.xml
<CustomField>
    <fullName>Financial__c</fullName>
    <label>Financial</label>
    <referenceTo>Financial__c</referenceTo>
    <relationshipLabel>Bank Information</relationshipLabel>
    <relationshipName>Bank_Information</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

peac_dev/force-app/main/default/objects/Financial_Bank_Information__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Bank Information</relationshipLabel>
    <relationshipName>Financial_Bank_Information</relationshipName>
    <type>Lookup</type>
</CustomField>

peac_dev/force-app/main/default/classes/PEAC_BankInfoStatementDataFactoryTest.cls
@isTest
public class PEAC_BankInfoStatementDataFactoryTest {

    public static Account createAccount() {
        Account acc = new Account(Name = 'Test Account');
        insert acc;
        return acc;
    }

    public static Opportunity createOpportunity(Id accountId) {
        Opportunity opp = new Opportunity(
            Name = 'Test Opportunity',
            StageName = 'Prospecting',
            CloseDate = Date.today().addDays(7),
            AccountId = accountId,
            OwnerId = UserInfo.getUserId()
        );
        insert opp;
        return opp;
    }

    public static Financial__c createFinancial(Id oppId) {
        Financial__c fin = new Financial__c(Opportunity__c = oppId);
        insert fin;
        return fin;
    }

    public static Financial_Bank_Information__c createBankInfo(Id financialId) {
        Financial_Bank_Information__c bank = new Financial_Bank_Information__c(
            Name = 'Test Bank Info',
            Financial__c = financialId,
            Bank_Account_Number_No_Masking__c = '1234567890'
        );
        insert bank;
        return bank;
    }

    public static Bank_Statement__c createBankStatement(Id bankInfoId) {
        Bank_Statement__c bs = new Bank_Statement__c(
            Bank_Information__c = bankInfoId
        );
        insert bs;
        return bs;
    }
}