peac_dev/force-app/main/default/objects/Bank_Information__c/Bank_Information__c.object-meta.xml
<CustomObject>
    <label>Bank Information</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Bank Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Bank Information</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

peac_dev/force-app/main/default/objects/Bank_Statement__c/Bank_Statement__c.object-meta.xml
<CustomObject>
    <label>Bank Statement</label>
    <nameField>
        <displayFormat>STMT-{0000000}</displayFormat>
        <label>Bank Statement Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Bank Statements</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

peac_dev/force-app/main/default/objects/Bank_Statement__c/fields/Amount_of_Deposits__c.field-meta.xml
<CustomField>
    <fullName>Amount_of_Deposits__c</fullName>
    <label>Amount of Deposits</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

peac_dev/force-app/main/default/objects/Bank_Statement__c/fields/Bank_Information__c.field-meta.xml
<CustomField>
    <fullName>Bank_Information__c</fullName>
    <label>Bank Information</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Financial_Bank_Information__c.Opportunity__c</field>
            <operation>equals</operation>
            <valueField>$Source.Opportunity__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Financial_Bank_Information__c</referenceTo>
    <relationshipLabel>Bank Statements</relationshipLabel>
    <relationshipName>Bank_Statements</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

peac_dev/force-app/main/default/objects/Financial__c/Financial__c.object-meta.xml
<CustomObject>
    <description>This object is created to store financial related information on Opportunity.</description>
    <label>Financial</label>
    <nameField>
        <displayFormat>FD-{000}</displayFormat>
        <label>Financial Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Financials</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

peac_dev/force-app/main/default/objects/Financial_Bank_Information__c/Financial_Bank_Information__c.object-meta.xml
<CustomObject>
    <label>Bank Information</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Bank Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Bank Information</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

peac_dev/force-app/main/default/objects/Financial_Bank_Information__c/fields/Financial__c.field-meta.xml
<CustomField>
    <fullName>Financial__c</fullName>
    <label>Financial</label>
    <referenceTo>Financial__c</referenceTo>
    <relationshipLabel>Bank Information</relationshipLabel>
    <relationshipName>Bank_Information</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

peac_dev/force-app/main/default/classes/PEAC_BankStatementTriggerHandlerTest.cls
@isTest
private class PEAC_BankStatementTriggerHandlerTest {

    @isTest
    static void testInsertUpdateDelete_BankStatement() {
        // Setup using utility class
        Account acc = PEAC_BankInfoStatementDataFactoryTest.createAccount();
        Opportunity opp = PEAC_BankInfoStatementDataFactoryTest.createOpportunity(acc.Id);
        Financial__c fin = PEAC_BankInfoStatementDataFactoryTest.createFinancial(opp.Id);
        Financial_Bank_Information__c bank = PEAC_BankInfoStatementDataFactoryTest.createBankInfo(fin.Id);

        // Insert
        Bank_Statement__c stmt = PEAC_BankInfoStatementDataFactoryTest.createBankStatement(bank.Id);

        // Update
        stmt.Amount_of_Deposits__c = 100;
        update stmt;

        // Delete
        delete stmt;
    }

    @isTest
    static void testBulkInsertUpdateDelete_BankStatement() {
        Account acc = PEAC_BankInfoStatementDataFactoryTest.createAccount();
        Opportunity opp = PEAC_BankInfoStatementDataFactoryTest.createOpportunity(acc.Id);
        Financial__c fin = PEAC_BankInfoStatementDataFactoryTest.createFinancial(opp.Id);
        Financial_Bank_Information__c bank = PEAC_BankInfoStatementDataFactoryTest.createBankInfo(fin.Id);

        List<Bank_Statement__c> stmtList = new List<Bank_Statement__c>();
        for (Integer i = 0; i < 5; i++) {
            stmtList.add(new Bank_Statement__c(
                Amount_of_Deposits__c = 100,
                Bank_Information__c = bank.Id
            ));
        }
        insert stmtList;

        for (Bank_Statement__c stmt : stmtList) {
            stmt.Amount_of_Deposits__c = 100;
        }
        update stmtList;

        delete stmtList;
    }
}