peac_dev/force-app/main/default/objects/Opportunity_Attachment__c/Opportunity_Attachment__c.object-meta.xml
<CustomObject>
    <label>OnBase Attachment</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>File Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>OnBase Attachments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

peac_dev/force-app/main/default/objects/Opportunity_Attachment__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipName>Attachments</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

peac_dev/force-app/main/default/objects/Opportunity_Attachment__c/fields/Sent_To_Ocrolus__c.field-meta.xml
<CustomField>
    <fullName>Sent_To_Ocrolus__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Sent To Ocrolus</label>
    <type>Checkbox</type>
</CustomField>

peac_dev/force-app/main/default/objects/Opportunity_Attachment__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Document Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>CR - Credit Application</fullName>
            </value>
            <value>
                <fullName>CR - Invoice/Quote/Proposal</fullName>
            </value>
            <value>
                <fullName>CR - Financial Statements</fullName>
            </value>
            <value>
                <fullName>CR - Misc</fullName>
            </value>
            <value>
                <fullName>FS - Bank Statements</fullName>
            </value>
            <value>
                <fullName>FS - Bank Statements - Apr</fullName>
            </value>
            <value>
                <fullName>FS - Bank Statements - Aug</fullName>
            </value>
            <value>
                <fullName>FS - Bank Statements - Dec</fullName>
            </value>
            <value>
                <fullName>FS - Bank Statements - Feb</fullName>
            </value>
            <value>
                <fullName>FS - Bank Statements - Jan</fullName>
            </value>
            <value>
                <fullName>FS - Bank Statements - Jul</fullName>
            </value>
            <value>
                <fullName>FS - Bank Statements - Jun</fullName>
            </value>
            <value>
                <fullName>FS - Bank Statements - Mar</fullName>
            </value>
            <value>
                <fullName>FS - Bank Statements - May</fullName>
            </value>
            <value>
                <fullName>FS - Bank Statements - Nov</fullName>
            </value>
            <value>
                <fullName>FS - Bank Statements - Oct</fullName>
            </value>
            <value>
                <fullName>FS - Bank Statements - Sept</fullName>
            </value>
            <value>
                <fullName>FS - Bank Statements MTD</fullName>
            </value>
            <value>
                <fullName>FS - Competitor Payoff</fullName>
            </value>
            <value>
                <fullName>FS - Credit Application</fullName>
            </value>
            <value>
                <fullName>FS - Financial Statements</fullName>
            </value>
            <value>
                <fullName>FS - Tax Returns</fullName>
            </value>
            <value>
                <fullName>FS - Voided Check</fullName>
            </value>
            <value>
                <fullName>CR - Bank Statements</fullName>
            </value>
            <value>
                <fullName>FS - Landlord Reference</fullName>
            </value>
            <value>
                <fullName>FS - Lease Agreement</fullName>
            </value>
            <value>
                <fullName>FS - Mortgage Statement</fullName>
            </value>
            <value>
                <fullName>FS - Payoff Agreement</fullName>
            </value>
            <value>
                <fullName>FS - Signed Loan Agreement</fullName>
            </value>
            <value>
                <fullName>FS - Bank Statements -Sept</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

peac_dev/force-app/main/default/objects/TC_Ocrolus_Upload_File__e/TC_Ocrolus_Upload_File__e.object-meta.xml
<CustomObject>
    <label>TC Ocrolus Upload File</label>
    <pluralLabel>TC Ocrolus Upload Files</pluralLabel>
</CustomObject>

peac_dev/force-app/main/default/objects/TC_Ocrolus_Upload_File__e/fields/Att_Id__c.field-meta.xml
<CustomField>
    <fullName>Att_Id__c</fullName>
    <label>Att Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

peac_dev/force-app/main/default/objects/TC_Ocrolus_Upload_File__e/fields/Callout_Type__c.field-meta.xml
<CustomField>
    <fullName>Callout_Type__c</fullName>
    <label>Callout Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

peac_dev/force-app/main/default/objects/TC_Ocrolus_Upload_File__e/fields/Opp_Att_Id__c.field-meta.xml
<CustomField>
    <fullName>Opp_Att_Id__c</fullName>
    <label>Opp Att Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

peac_dev/force-app/main/default/objects/TC_Ocrolus_Upload_File__e/fields/PK__c.field-meta.xml
<CustomField>
    <fullName>PK__c</fullName>
    <label>PK</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

peac_dev/force-app/main/default/classes/PEAC_OcrolusDelayQueueable.cls
public class PEAC_OcrolusDelayQueueable  implements Queueable, Database.AllowsCallouts {
    
    String oppdId;
    
    public PEAC_OcrolusDelayQueueable (String oppdId) {        
        this.oppdId = oppdId;
    }
    
    public void execute(QueueableContext context) {
        sendAttachmentsToOnbaseAndOcrolus(oppdId);
        
    }
    
    public static void sendAttachmentsToOnbaseAndOcrolus(Id oppId) {
        
        if (oppId == null) return;
        
        //Get Opportunity PK
        Opportunity opp = [
            SELECT Id, PK__c
            FROM Opportunity
            WHERE Id = :oppId
            LIMIT 1
        ];
        
        if (String.isBlank(opp.PK__c)) {
            Marlin_IntegrationLog.LogException(
                'Ocrolus File Upload',
                oppId,
                'Error',
                '',
                '',
                '',
                'PK__c is blank on Opportunity'
            );
            return;
        }
        
        // Get Opportunity Attachments
        List<Opportunity_Attachment__c> oppAttachments = [
            SELECT Id, Name, Type__c
            FROM Opportunity_Attachment__c
            WHERE Opportunity__c = :oppId AND Sent_To_Ocrolus__c = false
        ];
        
        if (oppAttachments.isEmpty()) return;
        
        Set<Id> oppAttIds = new Set<Id>();
        for (Opportunity_Attachment__c oa : oppAttachments) {
            oppAttIds.add(oa.Id);
        }
        
        List<Id> smallFileOppAttIds = new List<Id>();
        List<Id> bigFileOppAttIds = new List<Id>();
        
        Map<Id, Attachment> attachmentMap = new Map<Id, Attachment>();
        
        // Handle Classic Attachments
        for (Attachment att : [
            SELECT Id, Name, BodyLength, ParentId
            FROM Attachment
            WHERE ParentId IN :oppAttIds
        ]) {
            
            if (att.BodyLength < 7000000) {
                smallFileOppAttIds.add(att.ParentId);
                attachmentMap.put(att.ParentId, att);
            } else {
                bigFileOppAttIds.add(att.ParentId);
            }
        }
        
        // Handle Files
        Map<Id, ContentDocumentLink> fileMap = new Map<Id, ContentDocumentLink>();
        
        for (ContentDocumentLink doc : [
            SELECT LinkedEntityId,
            ContentDocumentId,
            ContentDocument.LatestPublishedVersion.Title,
            ContentDocument.LatestPublishedVersion.ContentSize,
            ContentDocument.LatestPublishedVersion.FileExtension
            FROM ContentDocumentLink
            WHERE LinkedEntityId IN :oppAttIds
        ]) {
            
            Integer size = doc.ContentDocument.LatestPublishedVersion.ContentSize;
            
            if (size < 7000000) {
                smallFileOppAttIds.add(doc.LinkedEntityId);
                fileMap.put(doc.LinkedEntityId, doc);
            } else {
                bigFileOppAttIds.add(doc.LinkedEntityId);
            }
        }
        
        // Send Big Files to HCL
        if (!bigFileOppAttIds.isEmpty()) {
            SL_OnBaseCallout.sendOnbaseAttachemntToHCL(oppId, bigFileOppAttIds);
        }
        
        
        
        // Send Small PDF Files to Ocrolus
        List<TC_Ocrolus_Upload_File__e> eventsToPublish = new List<TC_Ocrolus_Upload_File__e>();
        
        for (Opportunity_Attachment__c oppAttachment : oppAttachments) {
            
            if(oppAttachment.Type__c.contains(Label.TC_BankStatementFileType) && !oppAttachment.Type__c.contains(Label.TC_MTDFileType)){
            // Only process small files
            if (!smallFileOppAttIds.contains(oppAttachment.Id)) {
                continue;
            }
            
            Boolean isPDF = false;
            Id fileId;
            String fileName;
            String errorMessage;
            
            // Case 1: Classic Attachment
            if (attachmentMap.containsKey(oppAttachment.Id)) {
                
                Attachment att = attachmentMap.get(oppAttachment.Id);
                fileId = att.Id;
                fileName = att.Name;
                
                if (att.Name != null && att.Name.toLowerCase().endsWith('.pdf')) {
                    isPDF = true;
                }
                
            }
            // Case 2: File (ContentDocument)
            else if (fileMap.containsKey(oppAttachment.Id)) {
                
                ContentDocumentLink doc = fileMap.get(oppAttachment.Id);
                
                fileId = doc.ContentDocumentId;
                fileName = doc.ContentDocument.LatestPublishedVersion.Title;
                
                if (doc.ContentDocument.LatestPublishedVersion.FileExtension != null &&
                    doc.ContentDocument.LatestPublishedVersion.FileExtension.toLowerCase() == 'pdf') {
                        isPDF = true;
                    }
                
            }
            // No attachment found
            else {
                
                errorMessage = 'OnBase Attachment "' + oppAttachment.Name +
                    '" has no file attachments. Nothing uploaded to Ocrolus';
                
                Marlin_IntegrationLog.LogException(
                    'Ocrolus File Upload',
                    oppAttachment.Id,
                    'Error',
                    '',
                    '',
                    '',
                    errorMessage
                );
                
                continue;
            }
            
            // Not a PDF
            if (!isPDF) {
                
                errorMessage = '"' + fileName + '" is of unsupported or unknown file type, upload must be PDF. Not uploaded to Ocrolus';
                
                Marlin_IntegrationLog.LogException('Ocrolus File Upload', oppAttachment.Id, 'Error', '', '', '', errorMessage);
                
                continue;
            }
            
            // Valid PDF → Publish Event
            eventsToPublish.add(
                new TC_Ocrolus_Upload_File__e( PK__c = opp.PK__c, Att_Id__c = fileId, Opp_Att_Id__c = oppAttachment.Id, Callout_Type__c = 'upload'));
            }

        }
        
        if (!eventsToPublish.isEmpty()) {
            EventBus.publish(eventsToPublish);
        }
    }
    
    
}