peac_dev/force-app/main/default/objects/Opportunity_Attachment__c/Opportunity_Attachment__c.object-meta.xml
<CustomObject>
    <label>OnBase Attachment</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>File Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>OnBase Attachments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

peac_dev/force-app/main/default/objects/Opportunity_Attachment__c/fields/Attachment__c.field-meta.xml
<CustomField>
    <fullName>Attachment__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Attachment</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

peac_dev/force-app/main/default/objects/Opportunity_Attachment__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Description</label>
    <length>1000</length>
    <type>LongTextArea</type>
</CustomField>

peac_dev/force-app/main/default/objects/Opportunity_Attachment__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipName>Attachments</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

peac_dev/force-app/main/default/objects/Opportunity_Attachment__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Document Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>CR - Credit Application</fullName>
            </value>
            <value>
                <fullName>CR - Invoice/Quote/Proposal</fullName>
            </value>
            <value>
                <fullName>CR - Financial Statements</fullName>
            </value>
            <value>
                <fullName>CR - Misc</fullName>
            </value>
            <value>
                <fullName>FS - Bank Statements</fullName>
            </value>
            <value>
                <fullName>FS - Bank Statements - Apr</fullName>
            </value>
            <value>
                <fullName>FS - Bank Statements - Aug</fullName>
            </value>
            <value>
                <fullName>FS - Bank Statements - Dec</fullName>
            </value>
            <value>
                <fullName>FS - Bank Statements - Feb</fullName>
            </value>
            <value>
                <fullName>FS - Bank Statements - Jan</fullName>
            </value>
            <value>
                <fullName>FS - Bank Statements - Jul</fullName>
            </value>
            <value>
                <fullName>FS - Bank Statements - Jun</fullName>
            </value>
            <value>
                <fullName>FS - Bank Statements - Mar</fullName>
            </value>
            <value>
                <fullName>FS - Bank Statements - May</fullName>
            </value>
            <value>
                <fullName>FS - Bank Statements - Nov</fullName>
            </value>
            <value>
                <fullName>FS - Bank Statements - Oct</fullName>
            </value>
            <value>
                <fullName>FS - Bank Statements - Sept</fullName>
            </value>
            <value>
                <fullName>FS - Bank Statements MTD</fullName>
            </value>
            <value>
                <fullName>FS - Competitor Payoff</fullName>
            </value>
            <value>
                <fullName>FS - Credit Application</fullName>
            </value>
            <value>
                <fullName>FS - Financial Statements</fullName>
            </value>
            <value>
                <fullName>FS - Tax Returns</fullName>
            </value>
            <value>
                <fullName>FS - Voided Check</fullName>
            </value>
            <value>
                <fullName>CR - Bank Statements</fullName>
            </value>
            <value>
                <fullName>FS - Landlord Reference</fullName>
            </value>
            <value>
                <fullName>FS - Lease Agreement</fullName>
            </value>
            <value>
                <fullName>FS - Mortgage Statement</fullName>
            </value>
            <value>
                <fullName>FS - Payoff Agreement</fullName>
            </value>
            <value>
                <fullName>FS - Signed Loan Agreement</fullName>
            </value>
            <value>
                <fullName>FS - Bank Statements -Sept</fullName>
            </value>
            <value>
                <fullName>LC - Booking Sheet - Final</fullName>
            </value>
            <value>
                <fullName>FS - Booking Sheet</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

peac_dev/force-app/main/default/classes/TC_AttachmentTriggerHandler.cls
/** @author : Tamarack Consulting, Inc.
 * @date : 4/6/20
 * @description: 
 *
 */
public with sharing class TC_AttachmentTriggerHandler {

    public class AttachmentRelation {

        public Opportunity_Attachment__c onBaseAttachment;
        public Attachment attachment;

        public AttachmentRelation(Opportunity_Attachment__c onBaseAttachment, Attachment attachment) {
            this.onBaseAttachment = onBaseAttachment;
            this.attachment = attachment;
        }
    }

    public static void convertBookingSheetsToOnBaseAttachments(List<Attachment> attachments) {

        List<Opportunity_Attachment__c> onBaseAttachments = new List<Opportunity_Attachment__c>();
        List<AttachmentRelation> attachmentRelations = new List<AttachmentRelation>();

        Set<Id> opportunityIds = new Set<Id>();
        for (Attachment a : attachments) {
            if (a.ParentId.getSobjectType() == Schema.Opportunity.getSObjectType()) {
                opportunityIds.add(a.ParentId);
            }
        }
        Map<Id, Opportunity> opportunityMap = new Map<Id, Opportunity>([SELECT Id, Loan_Record_Type__c FROM Opportunity WHERE Id IN :opportunityIds]);

        for (Attachment attachment : attachments) {
            if (attachment.ParentId.getSobjectType() == Schema.Opportunity.getSObjectType()) {
                if (attachment.Name.contains('Booking Sheet')) {
                    Opportunity_Attachment__c onBaseAttachment = new Opportunity_Attachment__c();
                    onBaseAttachment.Name = attachment.Name;
                    onBaseAttachment.Description__c = attachment.Description;
                    onBaseAttachment.Type__c = (opportunityMap.get(attachment.ParentId).Loan_Record_Type__c
                            || attachment.Name.contains('Loan')) ? 'FS - Booking Sheet' : 'LC - Booking Sheet - Final';
                    onBaseAttachment.Opportunity__c = attachment.ParentId;
                    onBaseAttachment.Attachment__c = attachment.Id;
                    onBaseAttachments.add(onBaseAttachment);

                    Attachment clonedAttachment = attachment.clone();
                    attachmentRelations.add(new AttachmentRelation(onBaseAttachment, clonedAttachment));
                }
            }
        }

        if (!onBaseAttachments.isEmpty()) {
            insert onBaseAttachments;
        }

        List<Attachment> clonedAttachments = new List<Attachment>();
        for (AttachmentRelation attachmentRelation : attachmentRelations) {
            attachmentRelation.attachment.ParentId = attachmentRelation.onBaseAttachment.Id;
            clonedAttachments.add(attachmentRelation.attachment);
        }
        if (!clonedAttachments.isEmpty()) {
            insert clonedAttachments;
        }

        onBaseAttachments = new List<Opportunity_Attachment__c>();
        for (AttachmentRelation ar : attachmentRelations) {
            onBaseAttachments.add(new Opportunity_Attachment__c(Id = ar.onBaseAttachment.Id, Attachment__c = ar.attachment.Id));
        }
        if (!onBaseAttachments.isEmpty()) {
            update onBaseAttachments;
        }
    }
}