peac_dev/force-app/main/default/objects/Opportunity_Attachment__c/Opportunity_Attachment__c.object-meta.xml
<CustomObject>
    <label>OnBase Attachment</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>File Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>OnBase Attachments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

peac_dev/force-app/main/default/objects/Opportunity_Attachment__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Opportunity_Attachments</relationshipName>
    <type>Lookup</type>
</CustomField>

peac_dev/force-app/main/default/objects/Opportunity_Attachment__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipName>Attachments</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

peac_dev/force-app/main/default/objects/Opportunity_Attachment__c/fields/Sent_To_OnBase__c.field-meta.xml
<CustomField>
    <fullName>Sent_To_OnBase__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Sent To OnBase</label>
    <type>Checkbox</type>
</CustomField>

peac_dev/force-app/main/default/objects/Opportunity_Attachment__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Document Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>CR - Credit Application</fullName>
            </value>
            <value>
                <fullName>CR - Invoice/Quote/Proposal</fullName>
            </value>
            <value>
                <fullName>CR - Financial Statements</fullName>
            </value>
            <value>
                <fullName>CR - Misc</fullName>
            </value>
            <value>
                <fullName>FS - Bank Statements</fullName>
            </value>
            <value>
                <fullName>FS - Bank Statements - Apr</fullName>
            </value>
            <value>
                <fullName>FS - Bank Statements - Aug</fullName>
            </value>
            <value>
                <fullName>FS - Bank Statements - Dec</fullName>
            </value>
            <value>
                <fullName>FS - Bank Statements - Feb</fullName>
            </value>
            <value>
                <fullName>FS - Bank Statements - Jan</fullName>
            </value>
            <value>
                <fullName>FS - Bank Statements - Jul</fullName>
            </value>
            <value>
                <fullName>FS - Bank Statements - Jun</fullName>
            </value>
            <value>
                <fullName>FS - Bank Statements - Mar</fullName>
            </value>
            <value>
                <fullName>FS - Bank Statements - May</fullName>
            </value>
            <value>
                <fullName>FS - Bank Statements - Nov</fullName>
            </value>
            <value>
                <fullName>FS - Bank Statements - Oct</fullName>
            </value>
            <value>
                <fullName>FS - Bank Statements - Sept</fullName>
            </value>
            <value>
                <fullName>FS - Bank Statements MTD</fullName>
            </value>
            <value>
                <fullName>FS - Competitor Payoff</fullName>
            </value>
            <value>
                <fullName>FS - Credit Application</fullName>
            </value>
            <value>
                <fullName>FS - Financial Statements</fullName>
            </value>
            <value>
                <fullName>FS - Tax Returns</fullName>
            </value>
            <value>
                <fullName>FS - Voided Check</fullName>
            </value>
            <value>
                <fullName>CR - Bank Statements</fullName>
            </value>
            <value>
                <fullName>FS - Landlord Reference</fullName>
            </value>
            <value>
                <fullName>FS - Lease Agreement</fullName>
            </value>
            <value>
                <fullName>FS - Mortgage Statement</fullName>
            </value>
            <value>
                <fullName>FS - Payoff Agreement</fullName>
            </value>
            <value>
                <fullName>FS - Signed Loan Agreement</fullName>
            </value>
            <value>
                <fullName>FS - Bank Statements -Sept</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

peac_dev/force-app/main/default/objects/Opportunity_Attachment__c/fields/Updated_Rapport__c.field-meta.xml
<CustomField>
    <fullName>Updated_Rapport__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Updated Rapport</label>
    <type>Checkbox</type>
</CustomField>

peac_dev/force-app/main/default/classes/PEAC_OcrolusDelayQueueableTest.cls
@IsTest
private class PEAC_OcrolusDelayQueueableTest {
    
    private static Opportunity createBaseData(Boolean withPK) {
        
        SL_SCTestData.createAccountAndContracts(1,1);
        Account acc = [SELECT Id FROM Account ORDER BY CreatedDate DESC LIMIT 1];
        
        SL_SCTestData.createOpportunities(acc.Id,1);
        Opportunity opp = [SELECT Id, RecordTypeId FROM Opportunity ORDER BY CreatedDate DESC LIMIT 1];
        
        opp.RecordTypeId = Schema.SObjectType.Opportunity
            .getRecordTypeInfosByName()
            .get('Loan Booking')
            .getRecordTypeId();
        
        opp.StageName = 'Application';
        opp.Requested_Amount__c = 55000;
        
        if(withPK){
            opp.PK__c = 'PK-12345';
        }
        
        update opp;
        
        return opp;
    }
    
    
    @IsTest
    static void testQueueableExecution() {
        
        Opportunity opp = createBaseData(true);
        Account acc = [SELECT Id FROM Account ORDER BY CreatedDate DESC LIMIT 1];
        
        Opportunity_Attachment__c oppAtt = new Opportunity_Attachment__c(
            Opportunity__c = opp.Id,
            Account__c = acc.Id,
            Type__c = Label.TC_BankStatementFileType,
            Sent_To_OnBase__c = true,
            Updated_Rapport__c = false
        );
        insert oppAtt;
        
        Attachment att = new Attachment(
            Name = 'statement.pdf',
            ParentId = oppAtt.Id,
            Body = Blob.valueOf('PDF Content'),
            ContentType = 'application/pdf'
        );
        insert att;
        
        Test.startTest();
        System.enqueueJob(new PEAC_OcrolusDelayQueueable(opp.Id));
        Test.stopTest();
        
        System.assert(true);
    }
    
    
    @IsTest
    static void testNonPdfScenario() {
        
        Opportunity opp = createBaseData(true);
        Account acc = [SELECT Id FROM Account ORDER BY CreatedDate DESC LIMIT 1];
        
        Opportunity_Attachment__c oppAtt = new Opportunity_Attachment__c(
            Opportunity__c = opp.Id,
            Account__c = acc.Id,
            Type__c = Label.TC_BankStatementFileType,
            Sent_To_OnBase__c = true,
            Updated_Rapport__c = false
        );
        insert oppAtt;
        
        Attachment nonPdf = new Attachment(
            Name = 'image.jpg',
            ParentId = oppAtt.Id,
            Body = Blob.valueOf('Image'),
            ContentType = 'image/jpeg'
        );
        insert nonPdf;
        
        Test.startTest();
        PEAC_OcrolusDelayQueueable.sendAttachmentsToOnbaseAndOcrolus(opp.Id);
        Test.stopTest();
        
        System.assert(true);
    }
    
    
    @IsTest
    static void testContentDocumentBranch() {
        
        Opportunity opp = createBaseData(true);
        Account acc = [SELECT Id FROM Account ORDER BY CreatedDate DESC LIMIT 1];
        
        Opportunity_Attachment__c oppAtt = new Opportunity_Attachment__c(
            Opportunity__c = opp.Id,
            Account__c = acc.Id,
            Type__c = Label.TC_BankStatementFileType,
            Sent_To_OnBase__c = true,
            Updated_Rapport__c = false
        );
        insert oppAtt;
        
        ContentVersion cv = new ContentVersion(
            Title = 'statement',
            PathOnClient = 'statement.pdf',
            VersionData = Blob.valueOf('PDF Body'),
            IsMajorVersion = true
        );
        insert cv;
        
        cv = [SELECT Id, ContentDocumentId FROM ContentVersion WHERE Id = :cv.Id];
        
        ContentDocumentLink cdl = new ContentDocumentLink(
            LinkedEntityId = oppAtt.Id,
            ContentDocumentId = cv.ContentDocumentId,
            ShareType = 'V'
        );
        insert cdl;
        
        Test.startTest();
        PEAC_OcrolusDelayQueueable.sendAttachmentsToOnbaseAndOcrolus(opp.Id);
        Test.stopTest();
        
        System.assert(true);
    }
    
    
    @IsTest
    static void testPKBlankScenario() {
        
        Opportunity opp = createBaseData(false);
        
        Test.startTest();
        PEAC_OcrolusDelayQueueable.sendAttachmentsToOnbaseAndOcrolus(opp.Id);
        Test.stopTest();
        
        System.assert(true);
    }
    
    
    @IsTest
    static void testNullOppId() {
        Test.startTest();
        PEAC_OcrolusDelayQueueable.sendAttachmentsToOnbaseAndOcrolus(null);
        Test.stopTest();
        System.assert(true);
    }
}