peac_dev/force-app/main/default/objects/Opportunity_Attachment__c/Opportunity_Attachment__c.object-meta.xml
<CustomObject>
    <label>OnBase Attachment</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>File Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>OnBase Attachments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

peac_dev/force-app/main/default/objects/Opportunity_Attachment__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipName>Attachments</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

peac_dev/force-app/main/default/objects/Opportunity_Attachment__c/fields/Sent_To_Ocrolus__c.field-meta.xml
<CustomField>
    <fullName>Sent_To_Ocrolus__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Sent To Ocrolus</label>
    <type>Checkbox</type>
</CustomField>

peac_dev/force-app/main/default/objects/Opportunity_Attachment__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Document Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>CR - Credit Application</fullName>
            </value>
            <value>
                <fullName>CR - Invoice/Quote/Proposal</fullName>
            </value>
            <value>
                <fullName>CR - Financial Statements</fullName>
            </value>
            <value>
                <fullName>CR - Misc</fullName>
            </value>
            <value>
                <fullName>FS - Bank Statements</fullName>
            </value>
            <value>
                <fullName>FS - Bank Statements - Apr</fullName>
            </value>
            <value>
                <fullName>FS - Bank Statements - Aug</fullName>
            </value>
            <value>
                <fullName>FS - Bank Statements - Dec</fullName>
            </value>
            <value>
                <fullName>FS - Bank Statements - Feb</fullName>
            </value>
            <value>
                <fullName>FS - Bank Statements - Jan</fullName>
            </value>
            <value>
                <fullName>FS - Bank Statements - Jul</fullName>
            </value>
            <value>
                <fullName>FS - Bank Statements - Jun</fullName>
            </value>
            <value>
                <fullName>FS - Bank Statements - Mar</fullName>
            </value>
            <value>
                <fullName>FS - Bank Statements - May</fullName>
            </value>
            <value>
                <fullName>FS - Bank Statements - Nov</fullName>
            </value>
            <value>
                <fullName>FS - Bank Statements - Oct</fullName>
            </value>
            <value>
                <fullName>FS - Bank Statements - Sept</fullName>
            </value>
            <value>
                <fullName>FS - Bank Statements MTD</fullName>
            </value>
            <value>
                <fullName>FS - Competitor Payoff</fullName>
            </value>
            <value>
                <fullName>FS - Credit Application</fullName>
            </value>
            <value>
                <fullName>FS - Financial Statements</fullName>
            </value>
            <value>
                <fullName>FS - Tax Returns</fullName>
            </value>
            <value>
                <fullName>FS - Voided Check</fullName>
            </value>
            <value>
                <fullName>CR - Bank Statements</fullName>
            </value>
            <value>
                <fullName>FS - Landlord Reference</fullName>
            </value>
            <value>
                <fullName>FS - Lease Agreement</fullName>
            </value>
            <value>
                <fullName>FS - Mortgage Statement</fullName>
            </value>
            <value>
                <fullName>FS - Payoff Agreement</fullName>
            </value>
            <value>
                <fullName>FS - Signed Loan Agreement</fullName>
            </value>
            <value>
                <fullName>FS - Bank Statements -Sept</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

peac_dev/force-app/main/default/objects/TC_Ocrolus_Upload_File__e/TC_Ocrolus_Upload_File__e.object-meta.xml
<CustomObject>
    <label>TC Ocrolus Upload File</label>
    <pluralLabel>TC Ocrolus Upload Files</pluralLabel>
</CustomObject>

peac_dev/force-app/main/default/objects/TC_Ocrolus_Upload_File__e/fields/Att_Id__c.field-meta.xml
<CustomField>
    <fullName>Att_Id__c</fullName>
    <label>Att Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

peac_dev/force-app/main/default/objects/TC_Ocrolus_Upload_File__e/fields/Callout_Type__c.field-meta.xml
<CustomField>
    <fullName>Callout_Type__c</fullName>
    <label>Callout Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

peac_dev/force-app/main/default/objects/TC_Ocrolus_Upload_File__e/fields/Opp_Att_Id__c.field-meta.xml
<CustomField>
    <fullName>Opp_Att_Id__c</fullName>
    <label>Opp Att Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

peac_dev/force-app/main/default/objects/TC_Ocrolus_Upload_File__e/fields/PK__c.field-meta.xml
<CustomField>
    <fullName>PK__c</fullName>
    <label>PK</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

peac_dev/force-app/main/default/classes/TC_OcrolusCtrl.cls
/**
 * Created by tamarack on 2019-07-19.
 */

public with sharing class TC_OcrolusCtrl  {
    

    public static void processOcrolusAttachmentList(Id oppId) {

        String errorMessage;
        
        // don't send mtds 4-13-2020
        // 
        String likeMTD = '%' + Label.TC_MTDFileType + '%';

        List<Opportunity_Attachment__c> originalAttachmentList = new List<Opportunity_Attachment__c>([SELECT Id,Type__c,
                Name, Sent_To_Ocrolus__c FROM Opportunity_Attachment__c WHERE Opportunity__c = :oppId AND Sent_To_Ocrolus__c = False AND (NOT Type__c LIKE :likeMTD)]);

        if (originalAttachmentList.isEmpty()) {
            errorMessage = 'No attachments to process';
            Marlin_IntegrationLog.LogException('Ocrolus File Upload', oppId, 'Error', '', '', '', errorMessage);
            return;
        }

        String pk;
        List<Opportunity> oppList = new List<Opportunity>([SELECT Pk__c FROM Opportunity WHERE Id =: oppId]);
        if (!oppList.isEmpty() && oppList[0].Pk__c != null) {
            pk = oppList[0].Pk__c;
        } else {
            pk = TC_OcrolusService.addBookCallout(oppId);
            if (String.isEmpty(pk)) {
                return;
            }
        }

        for (Opportunity_Attachment__c oppAttachment : originalAttachmentList) {
            if(oppAttachment.Type__c.contains(Label.TC_BankStatementFileType) && !oppAttachment.Type__c.contains(Label.TC_MTDFileType)) {
                //system.debug('>>>>>?????: Heap size is ' + limits.getHeapSize() + ' enforced is ' + limits.getLimitHeapSize());
                sendAttachmentToOcrolus(oppAttachment, pk);
            } else {
                errorMessage = '"' + oppAttachment.Name + '" is not a bank statement. Not uploaded to Ocrolus';
                Marlin_IntegrationLog.LogException('Ocrolus File Upload', oppAttachment.Id, 'Error', '', '', '', errorMessage);
            }

        }

    }

    public static void sendAttachmentToOcrolus(Opportunity_Attachment__c oppAttachment, String pk) {

        String errorMessage;

        Attachment attachment = new Attachment ();
        List<Attachment> attachList = new List<Attachment>([SELECT Id, Name FROM Attachment WHERE parentId =: oppAttachment.Id]);

        if (!attachList.isEmpty()) {
            attachment = attachList[0];
        } else {
            errorMessage = 'OnBase Attachment "' + oppAttachment.Name + '" has no file attachments. Nothing uploaded to Ocrolus';
            Marlin_IntegrationLog.LogException('Ocrolus File Upload', oppAttachment.Id, 'Error', '', '', '', errorMessage);
            return;
        }

        String attachmentName = attachment.Name.toLowerCase();

        /*if (attachment.Name.substringAfterLast('.') == 'png' || attachment.Name.substringAfterLast('.') == 'jpeg') {

            responseBean = TC_OcrolusService.uploadImageCallout(pk, attachment, oppAttachId);
            if (responseBean.status == '200') {
                responseBean = TC_OcrolusService.doneImageCallout(pk, oppAttachId);
            }

        } else*/ if (attachmentName.contains('.pdf')) {

            //TC_OcrolusService.OcrolusQueueable queueable = new TC_OcrolusService.OcrolusQueueable(pk, attachment.Id, oppAttachment.Id, 'upload');
            //System.enqueueJob(queueable);
            // platform event 10-9-2019
            EventBus.publish (new TC_Ocrolus_Upload_File__e  (PK__c = pk, Att_Id__c = attachment.Id, Opp_Att_Id__c = oppAttachment.Id, Callout_Type__c = 'upload'));

        } else {
            errorMessage = '"' + attachment.Name + '" is of unsupported or unknown file type, upload must be PDF. Not uploaded to Ocrolus';
            Marlin_IntegrationLog.LogException('Ocrolus File Upload', oppAttachment.Id, 'Error', '', '', '', errorMessage);
        }

    }

}