peac_dev/force-app/main/default/objects/Opportunity_Attachment__c/Opportunity_Attachment__c.object-meta.xml
<CustomObject>
    <label>OnBase Attachment</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>File Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>OnBase Attachments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

peac_dev/force-app/main/default/objects/Opportunity_Attachment__c/fields/Dealer_Doc_Type__c.field-meta.xml
<CustomField>
    <fullName>Dealer_Doc_Type__c</fullName>
    <description>DP-254</description>
    <label>Document Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>LC - Assignment of Proceeds</fullName>
                <label>Assignment of Proceeds</label>
            </value>
            <value>
                <fullName>CR - Bank Statements</fullName>
                <label>Bank Statements</label>
            </value>
            <value>
                <fullName>CR - Credit Application</fullName>
                <label>Credit Application</label>
            </value>
            <value>
                <fullName>LC - Invoice</fullName>
                <label>Invoice</label>
            </value>
            <value>
                <fullName>CR - Invoice/Quote/Proposal</fullName>
                <label>Invoice/Quote/Proposal</label>
            </value>
            <value>
                <fullName>LC - Lease</fullName>
                <label>Lease</label>
            </value>
            <value>
                <fullName>LC - Misc</fullName>
                <label>Misc</label>
            </value>
            <value>
                <fullName>LC - Proof of Location</fullName>
                <label>POL</label>
            </value>
            <value>
                <fullName>LC - Tax Exempt Forms/Resale Certificate</fullName>
                <label>Tax Exempt Certificate</label>
            </value>
            <value>
                <fullName>Approval Letter</fullName>
            </value>
            <value>
                <fullName>FS - Approval Letter</fullName>
                <isActive>false</isActive>
                <label>FS - Approval Letter</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

peac_dev/force-app/main/default/objects/Opportunity_Attachment__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipName>Attachments</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

peac_dev/force-app/main/default/objects/Opportunity_Attachment__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Document Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>CR - Credit Application</fullName>
            </value>
            <value>
                <fullName>CR - Invoice/Quote/Proposal</fullName>
            </value>
            <value>
                <fullName>CR - Financial Statements</fullName>
            </value>
            <value>
                <fullName>CR - Misc</fullName>
            </value>
            <value>
                <fullName>FS - Bank Statements</fullName>
            </value>
            <value>
                <fullName>FS - Bank Statements - Apr</fullName>
            </value>
            <value>
                <fullName>FS - Bank Statements - Aug</fullName>
            </value>
            <value>
                <fullName>FS - Bank Statements - Dec</fullName>
            </value>
            <value>
                <fullName>FS - Bank Statements - Feb</fullName>
            </value>
            <value>
                <fullName>FS - Bank Statements - Jan</fullName>
            </value>
            <value>
                <fullName>FS - Bank Statements - Jul</fullName>
            </value>
            <value>
                <fullName>FS - Bank Statements - Jun</fullName>
            </value>
            <value>
                <fullName>FS - Bank Statements - Mar</fullName>
            </value>
            <value>
                <fullName>FS - Bank Statements - May</fullName>
            </value>
            <value>
                <fullName>FS - Bank Statements - Nov</fullName>
            </value>
            <value>
                <fullName>FS - Bank Statements - Oct</fullName>
            </value>
            <value>
                <fullName>FS - Bank Statements - Sept</fullName>
            </value>
            <value>
                <fullName>FS - Bank Statements MTD</fullName>
            </value>
            <value>
                <fullName>FS - Competitor Payoff</fullName>
            </value>
            <value>
                <fullName>FS - Credit Application</fullName>
            </value>
            <value>
                <fullName>FS - Financial Statements</fullName>
            </value>
            <value>
                <fullName>FS - Tax Returns</fullName>
            </value>
            <value>
                <fullName>FS - Voided Check</fullName>
            </value>
            <value>
                <fullName>CR - Bank Statements</fullName>
            </value>
            <value>
                <fullName>FS - Landlord Reference</fullName>
            </value>
            <value>
                <fullName>FS - Lease Agreement</fullName>
            </value>
            <value>
                <fullName>FS - Mortgage Statement</fullName>
            </value>
            <value>
                <fullName>FS - Payoff Agreement</fullName>
            </value>
            <value>
                <fullName>FS - Signed Loan Agreement</fullName>
            </value>
            <value>
                <fullName>FS - Bank Statements -Sept</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

peac_dev/force-app/main/default/classes/PEAC_LoanAppContoller.cls
/****************************************************************************************************
 * Author:Rajesh Kumar(LTMindtree)
 * Description: This class is used for loan app controller
 * Created Date: 05/12/2025
 *****************************************************************************************************/
public without sharing class PEAC_LoanAppContoller {
    
    @AuraEnabled
    public static string deleteAttachment(String oppId, String attachmentId){
        try {
            
            delete [SELECT Id FROM Opportunity_Attachment__c  WHERE Id = :attachmentId];
            return getOppAttachments(oppId);
        } catch (Exception ex) {
            throw new AuraHandledException(ex.getMessage());
        }
    }
    public static String getOppAttachments(String opportunityId){
        List<Opportunity_Attachment__c> oppAttachmentsList = [SELECT Id, Name, Dealer_Doc_Type__c,Type__c, createdById FROM Opportunity_Attachment__c WHERE Opportunity__c = :opportunityId];
        return JSON.serialize(oppAttachmentsList, true);
    }
}