peac_dev/force-app/main/default/objects/Opportunity_Attachment__c/Opportunity_Attachment__c.object-meta.xml
<CustomObject>
    <label>OnBase Attachment</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>File Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>OnBase Attachments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

peac_dev/force-app/main/default/objects/Opportunity_Attachment__c/fields/Attachment__c.field-meta.xml
<CustomField>
    <fullName>Attachment__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Attachment</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

peac_dev/force-app/main/default/objects/Opportunity_Attachment__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipName>Attachments</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

peac_dev/force-app/main/default/objects/Opportunity_Attachment__c/fields/Sent_To_OnBase__c.field-meta.xml
<CustomField>
    <fullName>Sent_To_OnBase__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Sent To OnBase</label>
    <type>Checkbox</type>
</CustomField>

peac_dev/force-app/main/default/classes/SentToOnBaseCalloutController.cls
public class SentToOnBaseCalloutController {
	
    public String selectedType {get;set;}
    public Boolean selectedAwesomeness {get;set;}
    public String description {get;set;}
    private Opportunity oppty {get;set;} 
    public String fileName {get;set;}
    public Blob fileBody {get;set;}
    
    public SentToOnBaseCalloutController(ApexPages.StandardController controller) { 
        this.oppty = (Opportunity)controller.getRecord();
        //processAttachments();
    }   
    
    // creates a new Contact_Attachment__c record
    public PageReference processAttachments() {
    	
        try {
                List<Opportunity_Attachment__c> lAttachmentList = [select id,Attachment__c,Name from Opportunity_Attachment__c 
                											where Opportunity__c = :oppty.Id 
                											And Sent_To_OnBase__c = False];
                											
				System.Debug('On Base List to process:' + lAttachmentList);
				
			//	for(Opportunity_Attachment__c att : lAttachmentList)
           //   		MARLIN_OnBaseCallout.sendDocToOnbase(att.Attachment__c);
           
            
        } catch (Exception e) {
            ApexPages.AddMessages(e);
        }    	
		return new PageReference('/'+oppty.Id);
		
    }
    
 
    
    public PageReference back() {
        return new PageReference('/'+oppty.Id);
    }  
    
    
}