peac_dev/force-app/main/default/objects/Bridgeware_Service_Setting__c/Bridgeware_Service_Setting__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Various settings for Bridgeware Service</description>
    <label>Bridgeware Service Setting</label>
</CustomObject>

peac_dev/force-app/main/default/objects/Bridgeware_Service_Setting__c/fields/Config_Name__c.field-meta.xml
<CustomField>
    <fullName>Config_Name__c</fullName>
    <defaultValue>&quot;DEMO&quot;</defaultValue>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>CONFIG-NAME Parameter that specifies database name to connect to</inlineHelpText>
    <label>Config Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

peac_dev/force-app/main/default/objects/Bridgeware_Service_Setting__c/fields/Enable_Debug_Log__c.field-meta.xml
<CustomField>
    <fullName>Enable_Debug_Log__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Enable Debug Log</label>
    <type>Checkbox</type>
</CustomField>

peac_dev/force-app/main/default/objects/Bridgeware_Service_Setting__c/fields/Mock_Callout__c.field-meta.xml
<CustomField>
    <fullName>Mock_Callout__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Mock Callout</label>
    <type>Checkbox</type>
</CustomField>

peac_dev/force-app/main/default/objects/Bridgeware_Service_Setting__c/fields/Mock_Callout_createCustomer__c.field-meta.xml
<CustomField>
    <fullName>Mock_Callout_createCustomer__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Mocky IO field for createCustomer request. Should return a CCAN.</inlineHelpText>
    <label>Mock_Callout_createCustomer</label>
    <type>Url</type>
</CustomField>

peac_dev/force-app/main/default/objects/Bridgeware_Service_Setting__c/fields/Mock_Endpoint__c.field-meta.xml
<CustomField>
    <fullName>Mock_Endpoint__c</fullName>
    <defaultValue>&quot;http://www.mocky.io/v2/54fe5204862a3ae70ddc9617&quot;</defaultValue>
    <description>Something like http://www.mocky.io/v2/54fe5204862a3ae70ddc9617 or http://requestb.in/</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Something like http://www.mocky.io/v2/54fe5204862a3ae70ddc9617 or http://requestb.in/

DO NOT FORGET TO ADD REMOTE SITE SETTINGS!</inlineHelpText>
    <label>Mock Endpoint</label>
    <type>Url</type>
</CustomField>

peac_dev/force-app/main/default/objects/Dealer_Surveillance__c/Dealer_Surveillance__c.object-meta.xml
<CustomObject>
    <label>Dealer Surveillance</label>
    <nameField>
        <displayFormat>A-{00000}</displayFormat>
        <label>Dealer Surveillance Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Dealer Surveillances</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

peac_dev/force-app/main/default/objects/Dealer_Surveillance__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Dealer Surveillances</relationshipLabel>
    <relationshipName>Dealer_Surveillances</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

peac_dev/force-app/main/default/objects/Dealer_Surveillance__c/fields/Completed_By_Auto_Process__c.field-meta.xml
<CustomField>
    <fullName>Completed_By_Auto_Process__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Added for SAL-3077 to avoid validation rules when automated process is updating Status to completed.</description>
    <label>Completed By Auto Process</label>
    <type>Checkbox</type>
</CustomField>

peac_dev/force-app/main/default/objects/Dealer_Surveillance__c/fields/Dealer_Surveillance__c.field-meta.xml
<CustomField>
    <fullName>Dealer_Surveillance__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Dealer Surveillance</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

peac_dev/force-app/main/default/objects/Dealer_Surveillance__c/fields/Next_Scheduled_Review__c.field-meta.xml
<CustomField>
    <fullName>Next_Scheduled_Review__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Next Scheduled Review</label>
    <type>Date</type>
</CustomField>

peac_dev/force-app/main/default/classes/TC_DealerSurveillancePortBatchSchdTest.cls
@IsTest public with sharing class TC_DealerSurveillancePortBatchSchdTest {
    private static String CRON_EXP = '0 5 0 * * ? 2023';

    @TestSetup static void setupData () {

        Bridgeware_Service_Setting__c setting = new Bridgeware_Service_Setting__c ();
        setting.Enable_Debug_Log__c = true;
        setting.Mock_Callout__c = true;
        setting.Mock_Endpoint__c = 'https://private-b2bb6-bridgewaretamarack.apiary-mock.com/';
//        setting.SetupOwnerId = UserInfo.getOrganizationId ();
        setting.Config_Name__c = 'TEST';
        setting.Mock_Callout_createCustomer__c = 'https://private-b2bb6-bridgewaretamarack.apiary-mock.com/';
        insert setting;
        
        Test.setMock(HttpCalloutMock.class, new TC_BWDealerCalloutMockImpl ());
        Test.startTest();

        Account a = new Account(Name = 'dealerSurveillanceTestAccount', Next_Scheduled_Review__c = Date.today());
        a.RecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Dealer Account').getRecordTypeId();
        a.Dealer_Number__c = '12345';
        a.Pass_Through_Maint__c = 'Yes';
        a.Pass_Thru_Maintenance_Frequency__c = 'QTLY';
        a.Account_Dealer_Status__c = 'Active';
        a.Dealer_Number__c = '585412.1234';
        a.Account_Dealer_LTD_Volume__c = 100;
        a.Portfolio_Review_Threshold__c = '250,000';
        a.Equipment_Type__c = 'A/V (General)';
        Account a2 = new Account(Name = 'dealerSurveillanceTestAccount2', Next_Scheduled_Review__c = Date.today());
        a2.RecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Dealer Account').getRecordTypeId();
        a2.Dealer_Number__c = '12345';
        a2.Pass_Through_Maint__c = 'Yes';
        a2.Pass_Thru_Maintenance_Frequency__c = 'QTLY';
        a2.Account_Dealer_Status__c = 'Active';
        a2.Dealer_Number__c = '585412.1234';
        a2.Equipment_Type__c = 'A/V (General)';
        insert new List <Account> {a,a2};
        
        Dealer_Surveillance__c suv = new Dealer_Surveillance__c  (Account__c = a.Id, Status__c = 'Completed', Completed_By_Auto_Process__c = true, Next_Scheduled_Review__c = Date.today());
        insert suv;
        
        Dealer_Surveillance__c suv2 = new Dealer_Surveillance__c  (Account__c = a2.Id, Status__c = 'Completed', Completed_By_Auto_Process__c = true, Next_Scheduled_Review__c = Date.today());
        insert suv2;
        Test.stopTest();

    }
    
    //Account_Dealer_LTD_Volume__c

    testMethod static void dealerSurveillanceTest () {

        Account a = [SELECT Id FROM Account WHERE Name = 'dealerSurveillanceTestAccount'][0];

Test.setMock(HttpCalloutMock.class, new TC_BWDealerCalloutMockImpl ());
        Test.startTest();
        

        insert new Dealer_Surveillance__c(Account__c = a.Id, Status__c = 'Completed', Completed_By_Auto_Process__c = true);



        TC_DealerSurveillancePortfolioBatchSchd s = new TC_DealerSurveillancePortfolioBatchSchd();
        System.schedule('Job Started at ' + String.valueOf(Datetime.now()), CRON_EXP, s);
        Test.stopTest();
    }
}