peac_dev/force-app/main/default/objects/Bridgeware_Service_Setting__c/Bridgeware_Service_Setting__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Various settings for Bridgeware Service</description>
    <label>Bridgeware Service Setting</label>
</CustomObject>

peac_dev/force-app/main/default/objects/Bridgeware_Service_Setting__c/fields/Config_Name__c.field-meta.xml
<CustomField>
    <fullName>Config_Name__c</fullName>
    <defaultValue>&quot;DEMO&quot;</defaultValue>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>CONFIG-NAME Parameter that specifies database name to connect to</inlineHelpText>
    <label>Config Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

peac_dev/force-app/main/default/objects/Bridgeware_Service_Setting__c/fields/Enable_Debug_Log__c.field-meta.xml
<CustomField>
    <fullName>Enable_Debug_Log__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Enable Debug Log</label>
    <type>Checkbox</type>
</CustomField>

peac_dev/force-app/main/default/objects/Bridgeware_Service_Setting__c/fields/Mock_Callout__c.field-meta.xml
<CustomField>
    <fullName>Mock_Callout__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Mock Callout</label>
    <type>Checkbox</type>
</CustomField>

peac_dev/force-app/main/default/objects/Bridgeware_Service_Setting__c/fields/Mock_Callout_createCustomer__c.field-meta.xml
<CustomField>
    <fullName>Mock_Callout_createCustomer__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Mocky IO field for createCustomer request. Should return a CCAN.</inlineHelpText>
    <label>Mock_Callout_createCustomer</label>
    <type>Url</type>
</CustomField>

peac_dev/force-app/main/default/objects/Bridgeware_Service_Setting__c/fields/Mock_Endpoint__c.field-meta.xml
<CustomField>
    <fullName>Mock_Endpoint__c</fullName>
    <defaultValue>&quot;http://www.mocky.io/v2/54fe5204862a3ae70ddc9617&quot;</defaultValue>
    <description>Something like http://www.mocky.io/v2/54fe5204862a3ae70ddc9617 or http://requestb.in/</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Something like http://www.mocky.io/v2/54fe5204862a3ae70ddc9617 or http://requestb.in/

DO NOT FORGET TO ADD REMOTE SITE SETTINGS!</inlineHelpText>
    <label>Mock Endpoint</label>
    <type>Url</type>
</CustomField>

peac_dev/force-app/main/default/classes/TC_DealerEmailageValidationTest.cls
/**
 * Created by trohweder on 2/19/21.
 * Test for SAL-2233, TC_DealerEmailageValidation
 */
@IsTest
public with sharing class TC_DealerEmailageValidationTest {

    @TestSetup
    public static void createTestDealerAndContact(){

        //had to set because it calls out durring the testing process for dealers
        Bridgeware_Service_Setting__c setting = new Bridgeware_Service_Setting__c ();
        setting.Enable_Debug_Log__c = true;
        setting.Mock_Callout__c = true;
        setting.Mock_Endpoint__c = 'https://private-b2bb6-bridgewaretamarack.apiary-mock.com/';
        setting.SetupOwnerId = UserInfo.getOrganizationId ();
        setting.Config_Name__c = 'TEST';
        setting.Mock_Callout_createCustomer__c = 'https://private-b2bb6-bridgewaretamarack.apiary-mock.com/';
        insert setting;

        Account a = new Account();
        a.RecordType = [SELECT Id FROM RecordType WHERE Name = 'Dealer Account' LIMIT 1];
        a.Name = 'Test Dealer';
        a.Account_Dealer_Status__c = 'Pending';
        a.Business_Phone__c = '8888888888';
        insert a;

        Contact c = new Contact();
        c.FirstName = 'test';
        c.LastName = 'contact';
        c.Emailage_Result__c = 'FAIL';
        c.AccountId = a.Id;
        insert c;

        AccountContactRelation r = [SELECT Id FROM AccountContactRelation WHERE ContactId = :c.Id LIMIT 1];
        r.Roles = 'Primary Contact';
        update r;
    }

    @IsTest
    public static void testErrorGetsThrown(){

        Test.setMock(HttpCalloutMock.class, new TC_BWDealerCalloutMockImpl ());

        Test.startTest();

        Account a = [SELECT Id, Account_Dealer_Status__c FROM Account WHERE Name = 'Test Dealer' LIMIT 1];

        a.Account_Dealer_Status__c = 'Active';

        update a;

        Test.stopTest();

    }


}