peac_dev/force-app/main/default/objects/Bridgeware_Service_Setting__c/Bridgeware_Service_Setting__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Various settings for Bridgeware Service</description>
    <label>Bridgeware Service Setting</label>
</CustomObject>

peac_dev/force-app/main/default/objects/Bridgeware_Service_Setting__c/fields/Config_Name__c.field-meta.xml
<CustomField>
    <fullName>Config_Name__c</fullName>
    <defaultValue>&quot;DEMO&quot;</defaultValue>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>CONFIG-NAME Parameter that specifies database name to connect to</inlineHelpText>
    <label>Config Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

peac_dev/force-app/main/default/objects/Bridgeware_Service_Setting__c/fields/Enable_Debug_Log__c.field-meta.xml
<CustomField>
    <fullName>Enable_Debug_Log__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Enable Debug Log</label>
    <type>Checkbox</type>
</CustomField>

peac_dev/force-app/main/default/objects/Bridgeware_Service_Setting__c/fields/Mock_Callout__c.field-meta.xml
<CustomField>
    <fullName>Mock_Callout__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Mock Callout</label>
    <type>Checkbox</type>
</CustomField>

peac_dev/force-app/main/default/objects/Bridgeware_Service_Setting__c/fields/Mock_Endpoint__c.field-meta.xml
<CustomField>
    <fullName>Mock_Endpoint__c</fullName>
    <defaultValue>&quot;http://www.mocky.io/v2/54fe5204862a3ae70ddc9617&quot;</defaultValue>
    <description>Something like http://www.mocky.io/v2/54fe5204862a3ae70ddc9617 or http://requestb.in/</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Something like http://www.mocky.io/v2/54fe5204862a3ae70ddc9617 or http://requestb.in/

DO NOT FORGET TO ADD REMOTE SITE SETTINGS!</inlineHelpText>
    <label>Mock Endpoint</label>
    <type>Url</type>
</CustomField>

peac_dev/force-app/main/default/objects/Broker__c/Broker__c.object-meta.xml
<CustomObject>
    <label>Broker</label>
    <nameField>
        <displayFormat>BR-{0000}</displayFormat>
        <label>Broker Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Brokers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

peac_dev/force-app/main/default/objects/Broker__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordType.Name</field>
            <operation>equals</operation>
            <value>Broker Account</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Broker Opportunities</relationshipLabel>
    <relationshipName>Brokers</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

peac_dev/force-app/main/default/objects/Broker__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Brokers</relationshipLabel>
    <relationshipName>Brokers1</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

peac_dev/force-app/main/default/objects/Contract__c/Contract__c.object-meta.xml
<CustomObject>
    <description>Custom Object created so we can use Queue functionality</description>
    <label>Contract</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Contract Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Contracts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

peac_dev/force-app/main/default/objects/Contract__c/fields/Dealer_Number__c.field-meta.xml
<CustomField>
    <fullName>Dealer_Number__c</fullName>
    <description>Get the Dealer Number from Dealer Account</description>
    <formula>Dealer_Name__r.Dealer_Number__c</formula>
    <label>Dealer Number</label>
    <type>Text</type>
</CustomField>

peac_dev/force-app/main/default/objects/Contract__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipName>Custom_Contracts</relationshipName>
    <type>Lookup</type>
</CustomField>

peac_dev/force-app/main/default/objects/Contract__c/fields/Tax_ID__c.field-meta.xml
<CustomField>
    <fullName>Tax_ID__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Tax ID</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

peac_dev/force-app/main/default/objects/Contract__c/recordTypes/Loan.recordType-meta.xml
<RecordType>
    <fullName>Loan</fullName>
    <active>false</active>
    <label>Loan</label>
</RecordType>

peac_dev/force-app/main/default/objects/Dealer__c/Dealer__c.object-meta.xml
<CustomObject>
    <label>Dealer</label>
    <nameField>
        <displayFormat>B-{0000}</displayFormat>
        <label>Dealer Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Dealers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

peac_dev/force-app/main/default/objects/Dealer__c/fields/Dealer__c.field-meta.xml
<CustomField>
    <fullName>Dealer__c</fullName>
    <label>Account</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Dealer Account, Dealer_Account Development, Dealer_Account Penetration, Dealer_Close, Dealer_Discovery, Dealer_Proposal, Dealer_Qualification</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Dealer Opportunities</relationshipLabel>
    <relationshipName>Dealers</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

peac_dev/force-app/main/default/objects/Dealer__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipName>Brokers</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

peac_dev/force-app/main/default/objects/Dealer__c/fields/Primary_Dealer__c.field-meta.xml
<CustomField>
    <fullName>Primary_Dealer__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Indicates if the dealer is primary dealer.</description>
    <label>Primary Dealer</label>
    <type>Checkbox</type>
</CustomField>

peac_dev/force-app/main/default/objects/ORE__c/ORE__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Settings to Bypass Org Rules</description>
    <label>OrgExceptions</label>
</CustomObject>

peac_dev/force-app/main/default/objects/ORE__c/fields/Bypass__c.field-meta.xml
<CustomField>
    <fullName>Bypass__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Bypass</label>
    <type>Checkbox</type>
</CustomField>

peac_dev/force-app/main/default/objects/Payee__c/Payee__c.object-meta.xml
<CustomObject>
    <label>Payee</label>
    <nameField>
        <displayFormat>PAY-{000000}</displayFormat>
        <label>Payee Indentification</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payees</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

peac_dev/force-app/main/default/objects/Payee__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Contact address information overrides the Dealer if the address fields exists.</inlineHelpText>
    <label>Contact</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>(1 OR 2)</booleanFilter>
        <filterItems>
            <field>Contact.AccountId</field>
            <operation>equals</operation>
            <valueField>$Source.Dealer__c</valueField>
        </filterItems>
        <filterItems>
            <field>$Source.Dealer__c</field>
            <operation>equals</operation>
            <value></value>
        </filterItems>
        <infoMessage>The Contact should be related to the Dealer/Broker</infoMessage>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Payees</relationshipLabel>
    <relationshipName>Payees</relationshipName>
    <type>Lookup</type>
</CustomField>

peac_dev/force-app/main/default/objects/Payee__c/fields/Dealer__c.field-meta.xml
<CustomField>
    <fullName>Dealer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Select a Dealer if one exists. After selection, pressing save will default the address information into the Payee entry.</inlineHelpText>
    <label>Dealer/Broker</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Dealer Account, Dealer_Account Development, Dealer_Account Penetration, Dealer_Close, Dealer_Discovery, Dealer_Proposal, Dealer_Qualification, Broker Account, End User Account</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Payees</relationshipLabel>
    <relationshipName>Payees</relationshipName>
    <type>Lookup</type>
</CustomField>

peac_dev/force-app/main/default/objects/Payee__c/fields/Payee_ID__c.field-meta.xml
<CustomField>
    <fullName>Payee_ID__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>This is typically the same as the Payee&apos;s phone number.</inlineHelpText>
    <label>Payee ID</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

peac_dev/force-app/main/default/objects/Payee__c/fields/Payee_Name__c.field-meta.xml
<CustomField>
    <fullName>Payee_Name__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Payee Name</label>
    <length>60</length>
    <type>Text</type>
</CustomField>

peac_dev/force-app/main/default/objects/Payee__c/fields/SL_Vendor_ID__c.field-meta.xml
<CustomField>
    <fullName>SL_Vendor_ID__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <externalId>true</externalId>
    <label>SL Vendor ID</label>
    <length>12</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

peac_dev/force-app/main/default/objects/Payee__c/fields/Tax_ID_Nbr__c.field-meta.xml
<CustomField>
    <fullName>Tax_ID_Nbr__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Tax ID Nbr</label>
    <length>11</length>
    <type>Text</type>
</CustomField>

peac_dev/force-app/main/default/classes/TC_AutoCreateLoanPaymentRecordsTest.cls
@isTest
public with sharing class TC_AutoCreateLoanPaymentRecordsTest {
    @TestSetup
    static void dataSetup(){

        ORE__c o = new ORE__c(Bypass__c = true);
        insert o;

        Bridgeware_Service_Setting__c setting = new Bridgeware_Service_Setting__c ();
        setting.Enable_Debug_Log__c = true;
        setting.Mock_Callout__c = true;
        setting.Mock_Endpoint__c = 'https://private-b2bb6-bridgewaretamarack.apiary-mock.com/';
        setting.SetupOwnerId = UserInfo.getOrganizationId ();
        setting.Config_Name__c = 'TEST';
        insert setting;

        List<Account> accountList = new List<Account>();

        Account brokerAccount = new Account(
            Name = 'TC_CreditDecisionTriggerTest Broker Account'
            , RecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Broker Account').getRecordTypeId()
            , Business_Address__c = 'Test Address', Business_City__c = 'Test City', Business_State__c = 'MN', Business_Zip__c = '11111'
            , Account_EU_FS_SIC_Description__c = '8661'
            , Account_Months_In_Business__c = 13
            , Dealer_Number__c = '855331.7237'
        );
        accountList.add(brokerAccount);

        Account franchiseeAccount = new Account(
                Name = 'TC_CreditDecisionTriggerTest Franchisee Account'
                , RecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Franchisee Account').getRecordTypeId()
                , Business_Address__c = 'Test Address', Business_City__c = 'Test City', Business_State__c = 'MN', Business_Zip__c = '11111'
                , Account_EU_FS_SIC_Description__c = '8661'
                , Account_Months_In_Business__c = 13
                , Tax_ID__c = '900978989'
        );
        accountList.add(franchiseeAccount);

        Account dealerAccount = new Account (
                Name = 'TC_CreditDecisionTriggerTest Dealer Account'
                , RecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Dealer Account').getRecordTypeId()
                , Business_Address__c = 'Test Address', Business_City__c = 'Test City', Business_State__c = 'MN', Business_Zip__c = '11111'
                , Account_EU_FS_SIC_Description__c = '8661'
                , Preferred_Dealer_Level__c = '3'
                , Dealer_Number__c = '855331.7237'
                ,Equipment_Type__c = 'A/V (General)'

        );
        accountList.add(dealerAccount);

        insert accountList;

        Contact dc = new Contact (
            AccountId = dealerAccount.Id, 
            FirstName = 'dealer test', 
            LastName = 'dealer contact', 
            MailingStreet = 'dealer test', 
            MailingCity = 'dealer test', 
            MailingStateCode = 'MN', 
            MailingPostalCode = '11190', 
            MailingCountry='United States', 
            Phone='1234555555',
            Title = 'Mr', 
            SSN__c = '156431111', 
            BirthDate = Date.today () - 365, 
            Email = 'testdealer123@test.com'
        );
        insert dc;

        Opportunity opp = new Opportunity(
                Name = 'TC_CreditDecisionTriggerTest'
                , StageName = 'Quote'
                , CloseDate = Date.today()
                , Last_Date_Scorex_Retrieved__c = Date.today()
                , RecordTypeId = Schema.SObjectType.Opportunity.getRecordTypeInfosByName().get('Loan Docs').getRecordTypeId()
                , AccountId = franchiseeAccount.Id
                , Application__c = 'TestApplicationNumber'
                , Loan_Ready_To_Doc__c = 'Yes'
                , Lessor__c = 201
                , Origination_Fee__c = 0
                , Months_Verified__c = 12
                ,Loan_Points_Amount__c = 4
        );
		Test.startTest();
        insert opp;
        

        Dealer__c dealer = new Dealer__c(
                Opportunity__c = opp.Id
                , Primary_Dealer__c = TRUE
                , Dealer__c = dealerAccount.Id
        );
        
        insert dealer;
        Test.stopTest();

        Broker__c broker = new Broker__c (Opportunity__c = opp.Id, Account__c = brokerAccount.Id);
        insert broker;

        Payee__c payee = new Payee__c(Dealer__c =dealerAccount.Id, Contact__c = dc.Id, Tax_ID_Nbr__c = '900978989', Payee_ID__c	= '855331.7237', Active__c = true, SL_Vendor_ID__c ='900-090-ASD', Payee_Name__c = 'Test Payee' );
        insert payee;
    }

    @IsTest
    public static void AutoCreateLoanPaymentRecordsTest(){

            Map<Id, Opportunity> oldMap = new Map<Id, Opportunity>([SELECT Id, Loan_Points_Amount__c, Contract__c, Origination_Fee__c, Loan_Amount__c, Loan_Record_Type__c, StageName, RecordTypeId FROM Opportunity]);
            Map<Id, Opportunity> newMap = new Map<Id, Opportunity>([SELECT Id, Loan_Points_Amount__c, Contract__c, Origination_Fee__c, Loan_Amount__c, Loan_Record_Type__c, StageName, RecordTypeId FROM Opportunity]);

            for(Id key : newMap.keyset()){
                newMap.get(key).StageName = 'Review for Booking';
                oldMap.get(key).StageName = 'Docs In';
            }
    
            try{
                TC_AutoCreateLoanPaymentRecords.autoCreateLoanPaymentRecords(oldMap,newMap);
                }
                catch (Exception e) {
                    System.debug(e.getMessage());
                }
    }

}