peac_dev/force-app/main/default/objects/Account_Program__c/Account_Program__c.object-meta.xml
<CustomObject>
    <label>Account Program</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Account Program Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Account Programs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

peac_dev/force-app/main/default/objects/Account_Program__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Dealer Account, Dealer_Account Development, Dealer_Qualification, Dealer_Proposal, Dealer_Discovery, Dealer_Close, Dealer_Account Penetration</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Programs</relationshipLabel>
    <relationshipName>Account_Programs</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

peac_dev/force-app/main/default/objects/Account_Program__c/fields/Program__c.field-meta.xml
<CustomField>
    <fullName>Program__c</fullName>
    <label>Program</label>
    <referenceTo>Program__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Account_Programs</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

peac_dev/force-app/main/default/objects/Program__c/Program__c.object-meta.xml
<CustomObject>
    <label>Program</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Programs</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Programs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

peac_dev/force-app/main/default/classes/PEAC_DealerAccountProgramUpdate.cls
public class PEAC_DealerAccountProgramUpdate {

    public static void checkDealerAccountAndUpdateProgram(Map <Id, Account> oldMap, Map <Id, Account> newMap){
        
        Id dealerVendorRtId = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('Dealer_Vendor').getRecordTypeId();
        Map<Id, Account> dealerAccountsWithDealerProgramMap = new Map<Id, Account>();
        Set<String> accountDealerPrograms = new Set<String>();
        for(Account acc: newMap.values()){
            if(acc.RecordTypeId == dealerVendorRtId && acc.Account_Dealer_Program__c != Null){
                dealerAccountsWithDealerProgramMap.put(acc.Id, acc);
                accountDealerPrograms.add(acc.Account_Dealer_Program__c);
            }
        }
        if(!dealerAccountsWithDealerProgramMap.isEmpty() && !accountDealerPrograms.isEmpty()){
			Map<Id, Program__c> programsMap = checkProgramsArePresent(accountDealerPrograms);
            if(!programsMap.isEmpty()){
                Map<Id, List<Account_Program__c>> relatedAccountPrograms = getAllRelatedAccountPrograms(dealerAccountsWithDealerProgramMap);
                for(Account acc : dealerAccountsWithDealerProgramMap.values()){
                    //System.debug(relatedAccountPrograms.get(acc.Id).Name);
                    if(relatedAccountPrograms.containskey(acc.Id)){
                        
                    }
                }
            }
        }
    }
    
    public static Map<Id, Program__c> checkProgramsArePresent(Set<String> accountDealerPrograms) {
        return new Map<Id, Program__c>([SELECT Id, Name FROM Program__c WHERE Name IN :accountDealerPrograms]);
    }
    
    public static Map<Id, List<Account_Program__c>> getAllRelatedAccountPrograms(Map<Id, Account> dealerAccountsWithDealerProgramMap){
        Map<Id, List<Account_Program__c>> accountProgramMap = new Map<Id, List<Account_Program__c>>();
        if (dealerAccountsWithDealerProgramMap == null || dealerAccountsWithDealerProgramMap.isEmpty()) {
            return accountProgramMap;
        }
        for (Account_Program__c accProg : [SELECT Id, Name, Account__c, Program__c
                                           FROM Account_Program__c
                                           WHERE Account__c IN :dealerAccountsWithDealerProgramMap.keySet()]) {
            if (!accountProgramMap.containsKey(accProg.Account__c)) {
                accountProgramMap.put(accProg.Account__c, new List<Account_Program__c>());
            }
            accountProgramMap.get(accProg.Account__c).add(accProg);
        }
        return accountProgramMap;
    }


}