peac_dev/force-app/main/default/objects/Account_Program__c/Account_Program__c.object-meta.xml
<CustomObject>
    <label>Account Program</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Account Program Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Account Programs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

peac_dev/force-app/main/default/objects/Account_Program__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Dealer Account, Dealer_Account Development, Dealer_Qualification, Dealer_Proposal, Dealer_Discovery, Dealer_Close, Dealer_Account Penetration</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Programs</relationshipLabel>
    <relationshipName>Account_Programs</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

peac_dev/force-app/main/default/objects/Account_Program__c/fields/Program__c.field-meta.xml
<CustomField>
    <fullName>Program__c</fullName>
    <label>Program</label>
    <referenceTo>Program__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Account_Programs</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

peac_dev/force-app/main/default/objects/Dealer__c/Dealer__c.object-meta.xml
<CustomObject>
    <label>Dealer</label>
    <nameField>
        <displayFormat>B-{0000}</displayFormat>
        <label>Dealer Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Dealers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

peac_dev/force-app/main/default/objects/Dealer__c/fields/Dealer__c.field-meta.xml
<CustomField>
    <fullName>Dealer__c</fullName>
    <label>Account</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Dealer Account, Dealer_Account Development, Dealer_Account Penetration, Dealer_Close, Dealer_Discovery, Dealer_Proposal, Dealer_Qualification</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Dealer Opportunities</relationshipLabel>
    <relationshipName>Dealers</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

peac_dev/force-app/main/default/objects/Dealer__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipName>Brokers</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

peac_dev/force-app/main/default/objects/Program__c/Program__c.object-meta.xml
<CustomObject>
    <label>Program</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Programs</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Programs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

peac_dev/force-app/main/default/classes/DealerInfoUpdateOnOPPbatchTest.cls
@isTest
public class DealerInfoUpdateOnOPPbatchTest {
     @TestSetup
     static void makeData(){
        List<Account> lstAcc = new List<Account>();        
        //Account record of type dealer
        
        RecordType rt = [select id,Name from RecordType where SobjectType='Account' and Name='Dealer_Qualification' Limit 1];
        Account accRecDealer = new Account(Name='Test Account1' , recordTypeId=rt.id, Business_Phone__c = '0987654321');
        lstAcc.add(accRecDealer);
        
        
        //Account record of type End USer
        RecordType rt1 = [select id,Name from RecordType where SobjectType='Account' and Name='End User Account' Limit 1];
        Account accRecEndUser = new Account(Name='Test Account2' , recordTypeId=rt1.id,Business_Phone__c = '0987654321');
        lstAcc.add(accRecEndUser);
        insert lstAcc;

        //program for an account
        Program__c pr = new Program__c(Name = 'testProgram');
        insert pr;
        
        //Account Program for dealer Account 
        Account_Program__c ap = new Account_Program__c(Account__c = accRecDealer.id , Program__c = pr.id);
        insert ap;
        Test.startTest();
        opportunity opp = new opportunity(Name='testOpty' , StageName = 'Quote', 
                                          CloseDate = System.today() , Primary_Source__c = 'Email');
        
        opp.AccountId = accRecEndUser.Id;                            
        insert opp;
        Test.stopTest();
     }
     public static testMethod void testData(){

        Test.startTest();
        //Dealer Record
        Dealer__c dlr = new Dealer__c();
        dlr.Opportunity__c = [SELECT Id FROM Opportunity LIMIT 1].Id;
        dlr.Dealer__c = [SELECT Id FROM Account WHERE Name='Test Account1' LIMIT 1].Id;
        insert dlr;
        Test.stopTest();
        DealerInfoUpdateOnOPPbatch dd=new  DealerInfoUpdateOnOPPbatch();
        Database.executeBatch(dd); 
    }

}