peac_dev/force-app/main/default/objects/Account_Program__c/Account_Program__c.object-meta.xml
<CustomObject>
    <label>Account Program</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Account Program Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Account Programs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

peac_dev/force-app/main/default/objects/Account_Program__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Dealer Account, Dealer_Account Development, Dealer_Qualification, Dealer_Proposal, Dealer_Discovery, Dealer_Close, Dealer_Account Penetration</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Programs</relationshipLabel>
    <relationshipName>Account_Programs</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

peac_dev/force-app/main/default/objects/Account_Program__c/fields/Program__c.field-meta.xml
<CustomField>
    <fullName>Program__c</fullName>
    <label>Program</label>
    <referenceTo>Program__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Account_Programs</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

peac_dev/force-app/main/default/objects/Dealer__c/Dealer__c.object-meta.xml
<CustomObject>
    <label>Dealer</label>
    <nameField>
        <displayFormat>B-{0000}</displayFormat>
        <label>Dealer Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Dealers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

peac_dev/force-app/main/default/objects/Dealer__c/fields/Dealer__c.field-meta.xml
<CustomField>
    <fullName>Dealer__c</fullName>
    <label>Account</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Dealer Account, Dealer_Account Development, Dealer_Account Penetration, Dealer_Close, Dealer_Discovery, Dealer_Proposal, Dealer_Qualification</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Dealer Opportunities</relationshipLabel>
    <relationshipName>Dealers</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

peac_dev/force-app/main/default/objects/Dealer__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipName>Brokers</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

peac_dev/force-app/main/default/objects/Opportunity_Program__c/Opportunity_Program__c.object-meta.xml
<CustomObject>
    <label>Opportunity Program</label>
    <nameField>
        <displayFormat>OP-{0000}</displayFormat>
        <label>Opportunity Program Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Opportunity Program</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

peac_dev/force-app/main/default/objects/Opportunity_Program__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Opportunity Program</relationshipLabel>
    <relationshipName>Opportunity_Program</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

peac_dev/force-app/main/default/objects/Opportunity_Program__c/fields/Program__c.field-meta.xml
<CustomField>
    <fullName>Program__c</fullName>
    <label>Program</label>
    <referenceTo>Program__c</referenceTo>
    <relationshipLabel>Opportunity Program</relationshipLabel>
    <relationshipName>Opportunity_Program</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

peac_dev/force-app/main/default/objects/Program__c/Program__c.object-meta.xml
<CustomObject>
    <label>Program</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Programs</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Programs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

peac_dev/force-app/main/default/objects/Program__c/recordTypes/Programs.recordType-meta.xml
<RecordType>
    <fullName>Programs</fullName>
    <active>true</active>
    <description>Programs offered by a Dealer, Franchisor or Manufacturer that would affect the pricing of an application</description>
    <label>Programs</label>
</RecordType>

peac_dev/force-app/main/default/classes/PEAC_DealerTriggerHandlerTest.cls
@IsTest
public class PEAC_DealerTriggerHandlerTest {

    @IsTest
    static void testAddProgram_CoversAllConditions() {
		PEAC_GenerateTaxMatrixBatch.isRunning = true;
        // -----------------------------
        // 0) Resolve Account RecordType DeveloperNames from Custom Label
        // -----------------------------
        // Your production code treats the label as DeveloperName(s) even though variable says "Id".
        List<String> rtDevNames = new List<String>();
        if (!String.isBlank(System.Label.AccountRecordTypeId)) {
            for (String s : System.Label.AccountRecordTypeId.split(',')) {
                if (!String.isBlank(s)) rtDevNames.add(s.trim());
            }
        }

        // Pick one "allowed" Account record type from the label list
        RecordType goodRt = [
            SELECT Id, DeveloperName
            FROM RecordType
            WHERE SObjectType = 'Account'
            AND DeveloperName IN :rtDevNames
            LIMIT 1
        ];

        // Optional "not allowed" RT (to cover accIds.contains == false path if org has >1 RT)
        RecordType badRt;
        List<RecordType> badRts = [
            SELECT Id, DeveloperName
            FROM RecordType
            WHERE SObjectType = 'Account'
            AND DeveloperName NOT IN :rtDevNames
            LIMIT 1
        ];
        if (!badRts.isEmpty()) badRt = badRts[0];

        // -----------------------------
        // 1) Create Programs
        // -----------------------------
        Program__c prog1 = new Program__c(Name = 'Program-1');
        Program__c prog2 = new Program__c(Name = 'Program-2');
        Program__c prog3 = new Program__c(Name = 'Program-3');
        insert new List<Program__c>{ prog1, prog2, prog3 };

        // -----------------------------
        // 2) Create Accounts (Good + Optional Bad)
        // -----------------------------
        Account accGood = new Account(
            Name = 'Good Dealer Account',
            RecordTypeId = goodRt.Id
        );
        insert accGood;

        Account accBad;
        if (badRt != null) {
            accBad = new Account(
                Name = 'Bad Dealer Account',
                RecordTypeId = badRt.Id
            );
            insert accBad;
        }

        // -----------------------------
        // 3) Create Account Programs for good account
        // -----------------------------
        Account_Program__c ap1 = new Account_Program__c(Account__c = accGood.Id, Program__c = prog1.Id);
        Account_Program__c ap2 = new Account_Program__c(Account__c = accGood.Id, Program__c = prog2.Id);
        insert new List<Account_Program__c>{ ap1, ap2 };

        // -----------------------------
        // 4) Create Opportunities
        // -----------------------------
        Opportunity oppA = new Opportunity(Name = 'Opp-A', StageName = 'Prospecting', CloseDate = Date.today().addDays(10));
        Opportunity oppB = new Opportunity(Name = 'Opp-B', StageName = 'Prospecting', CloseDate = Date.today().addDays(10));
        Opportunity oppC = new Opportunity(Name = 'Opp-C', StageName = 'Prospecting', CloseDate = Date.today().addDays(10));
        insert new List<Opportunity>{ oppA, oppB, oppC };

        // -----------------------------
        // 5) FIRST INVOCATION: cover optyprogramLst.isEmpty() == true
        //    - Provide only oppA (no existing Opportunity_Program__c anywhere yet)
        // -----------------------------
        Dealer__c dA = new Dealer__c(
            Dealer__c = accGood.Id,
            Opportunity__c = oppA.Id
        );

        Test.startTest();
        DealerTriggerHandler.addProgram(new List<Dealer__c>{ dA });
        Test.stopTest();
    }

    
	@IsTest
    static void testDeleteFieldsOnOpportunity() {
		PEAC_GenerateTaxMatrixBatch.isRunning = true;
        // -----------------------------
        // 0) Resolve Account RecordType DeveloperNames from Custom Label
        // -----------------------------
        // Your production code treats the label as DeveloperName(s) even though variable says "Id".
        List<String> rtDevNames = new List<String>();
        if (!String.isBlank(System.Label.AccountRecordTypeId)) {
            for (String s : System.Label.AccountRecordTypeId.split(',')) {
                if (!String.isBlank(s)) rtDevNames.add(s.trim());
            }
        }

        // Pick one "allowed" Account record type from the label list
        RecordType goodRt = [
            SELECT Id, DeveloperName
            FROM RecordType
            WHERE SObjectType = 'Account'
            AND DeveloperName IN :rtDevNames
            LIMIT 1
        ];

        // Optional "not allowed" RT (to cover accIds.contains == false path if org has >1 RT)
        RecordType badRt;
        List<RecordType> badRts = [
            SELECT Id, DeveloperName
            FROM RecordType
            WHERE SObjectType = 'Account'
            AND DeveloperName NOT IN :rtDevNames
            LIMIT 1
        ];
        if (!badRts.isEmpty()) badRt = badRts[0];

        // -----------------------------
        // 1) Create Programs
        // -----------------------------
        Program__c prog1 = new Program__c(Name = 'Program-1');
        Program__c prog2 = new Program__c(Name = 'Program-2');
        Program__c prog3 = new Program__c(Name = 'Program-3');
        insert new List<Program__c>{ prog1, prog2, prog3 };

        // -----------------------------
        // 2) Create Accounts (Good + Optional Bad)
        // -----------------------------
        Account accGood = new Account(
            Name = 'Good Dealer Account',
            RecordTypeId = goodRt.Id
        );
        insert accGood;

        Account accBad;
        if (badRt != null) {
            accBad = new Account(
                Name = 'Bad Dealer Account',
                RecordTypeId = badRt.Id
            );
            insert accBad;
        }

        // -----------------------------
        // 3) Create Account Programs for good account
        // -----------------------------
        Account_Program__c ap1 = new Account_Program__c(Account__c = accGood.Id, Program__c = prog1.Id);
        Account_Program__c ap2 = new Account_Program__c(Account__c = accGood.Id, Program__c = prog2.Id);
        insert new List<Account_Program__c>{ ap1, ap2 };

        // -----------------------------
        // 4) Create Opportunities
        // -----------------------------
        Opportunity oppA = new Opportunity(Name = 'Opp-A', StageName = 'Prospecting', CloseDate = Date.today().addDays(10));
        Opportunity oppB = new Opportunity(Name = 'Opp-B', StageName = 'Prospecting', CloseDate = Date.today().addDays(10));
        Opportunity oppC = new Opportunity(Name = 'Opp-C', StageName = 'Prospecting', CloseDate = Date.today().addDays(10));
        insert new List<Opportunity>{ oppA, oppB, oppC };

        // -----------------------------
        // 5) FIRST INVOCATION: cover optyprogramLst.isEmpty() == true
        //    - Provide only oppA (no existing Opportunity_Program__c anywhere yet)
        // -----------------------------
        Dealer__c dA = new Dealer__c(
            Dealer__c = accGood.Id,
            Opportunity__c = oppA.Id
        );

        // 5. Execute method
        Test.startTest();
        DealerTriggerHandler.deleteFieldsOnOpportunity(new List<Dealer__c>{ dA });
        Test.stopTest();
    }
    
        
    @IsTest
    static void testInsertUpdateDealer() {
		PEAC_GenerateTaxMatrixBatch.isRunning = true;
        // -----------------------------
        // 0) Resolve Account RecordType DeveloperNames from Custom Label
        // -----------------------------
        // Your production code treats the label as DeveloperName(s) even though variable says "Id".
        List<String> rtDevNames = new List<String>();
        if (!String.isBlank(System.Label.AccountRecordTypeId)) {
            for (String s : System.Label.AccountRecordTypeId.split(',')) {
                if (!String.isBlank(s)) rtDevNames.add(s.trim());
            }
        }

        // Pick one "allowed" Account record type from the label list
        RecordType goodRt = [
            SELECT Id, DeveloperName
            FROM RecordType
            WHERE SObjectType = 'Account'
            AND DeveloperName IN :rtDevNames
            LIMIT 1
        ];

        // Optional "not allowed" RT (to cover accIds.contains == false path if org has >1 RT)
        RecordType badRt;
        List<RecordType> badRts = [
            SELECT Id, DeveloperName
            FROM RecordType
            WHERE SObjectType = 'Account'
            AND DeveloperName NOT IN :rtDevNames
            LIMIT 1
        ];
        if (!badRts.isEmpty()) badRt = badRts[0];
        Account accGood = new Account(
            Name = 'Good Dealer Account',
            RecordTypeId = goodRt.Id
        );
        insert accGood;
        Opportunity oppA = new Opportunity(Name = 'Opp-A', StageName = 'Prospecting', CloseDate = Date.today().addDays(10));
        insert oppA;
        
        Dealer__c dA = new Dealer__c(
            Dealer__c = accGood.Id,
            Opportunity__c = oppA.Id
        );
        
        Test.startTest();
        	insert dA;
        Test.stopTest();
    }

    @IsTest
    static void testUpdateDealer() {
		PEAC_GenerateTaxMatrixBatch.isRunning = true;
        // -----------------------------
        // 0) Resolve Account RecordType DeveloperNames from Custom Label
        // -----------------------------
        // Your production code treats the label as DeveloperName(s) even though variable says "Id".
        List<String> rtDevNames = new List<String>();
        if (!String.isBlank(System.Label.AccountRecordTypeId)) {
            for (String s : System.Label.AccountRecordTypeId.split(',')) {
                if (!String.isBlank(s)) rtDevNames.add(s.trim());
            }
        }

        // Pick one "allowed" Account record type from the label list
        RecordType goodRt = [
            SELECT Id, DeveloperName
            FROM RecordType
            WHERE SObjectType = 'Account'
            AND DeveloperName IN :rtDevNames
            LIMIT 1
        ];

        // Optional "not allowed" RT (to cover accIds.contains == false path if org has >1 RT)
        RecordType badRt;
        List<RecordType> badRts = [
            SELECT Id, DeveloperName
            FROM RecordType
            WHERE SObjectType = 'Account'
            AND DeveloperName NOT IN :rtDevNames
            LIMIT 1
        ];
        if (!badRts.isEmpty()) badRt = badRts[0];
        Account accGood = new Account(
            Name = 'Good Dealer Account',
            RecordTypeId = goodRt.Id
        );
        insert accGood;
        Opportunity oppA = new Opportunity(Name = 'Opp-A', StageName = 'Prospecting', CloseDate = Date.today().addDays(10));
        insert oppA;
        
        Dealer__c dA = new Dealer__c(
            Dealer__c = accGood.Id,
            Opportunity__c = oppA.Id
        );
        
        Test.startTest();
        	insert dA;
        	update dA;
        Test.stopTest();
    }

}