peac_dev/force-app/main/default/objects/Account_Program__c/Account_Program__c.object-meta.xml
<CustomObject>
    <label>Account Program</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Account Program Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Account Programs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

peac_dev/force-app/main/default/objects/Account_Program__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Dealer Account, Dealer_Account Development, Dealer_Qualification, Dealer_Proposal, Dealer_Discovery, Dealer_Close, Dealer_Account Penetration</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Programs</relationshipLabel>
    <relationshipName>Account_Programs</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

peac_dev/force-app/main/default/objects/Account_Program__c/fields/Program__c.field-meta.xml
<CustomField>
    <fullName>Program__c</fullName>
    <label>Program</label>
    <referenceTo>Program__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Account_Programs</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

peac_dev/force-app/main/default/objects/Program__c/Program__c.object-meta.xml
<CustomObject>
    <label>Program</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Programs</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Programs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

peac_dev/force-app/main/default/objects/Program__c/fields/Program_Code__c.field-meta.xml
<CustomField>
    <fullName>Program_Code__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Program Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

peac_dev/force-app/main/default/objects/Program__c/recordTypes/Programs.recordType-meta.xml
<RecordType>
    <fullName>Programs</fullName>
    <active>true</active>
    <description>Programs offered by a Dealer, Franchisor or Manufacturer that would affect the pricing of an application</description>
    <label>Programs</label>
</RecordType>

peac_dev/force-app/main/default/classes/NT_QuoteScreenUtil.cls
/**
 * @description Utility class for Quote screen operations, including Flow invocable actions.
 * @author Northteq
 */
public without sharing class NT_QuoteScreenUtil {

    /**
     * @description Invocable method to retrieve Program__c records associated with
     *              the dealer account via Account_Program__c junction object.
     *              Queries Account_Program__c for the dealer, then fetches the
     *              related Program__c records to drive the Program picklist on the
     *              Quote Input screen.
     * @param requests List of GetDealerProgramsRequest containing dealerAccountId
     * @return List<List<Program__c>> Program records per request
     */
    @InvocableMethod(label='Get Dealer Programs' description='Returns Program__c records linked to the dealer account via Account_Program__c')
    public static List<List<Program__c>> getDealerPrograms(List<GetDealerProgramsRequest> requests) {
        List<List<Program__c>> results = new List<List<Program__c>>();

        for (GetDealerProgramsRequest request : requests) {
            List<Program__c> programs = new List<Program__c>();

            if (String.isNotBlank(request.dealerAccountId)) {
                // Step 1: get Program Ids linked to this dealer via the junction object
                List<Account_Program__c> junctionRecords = [
                    SELECT Program__c
                    FROM Account_Program__c
                    WHERE Account__c = :request.dealerAccountId
                    AND Program__c != null
                ];

                Set<Id> programIds = new Set<Id>();
                for (Account_Program__c ap : junctionRecords) {
                    programIds.add(ap.Program__c);
                }

                // Step 2: query the actual Program__c records for display
                if (!programIds.isEmpty()) {
                    programs = [
                        SELECT Id, Name, Program_Code__c
                        FROM Program__c
                        WHERE Id IN :programIds
                        ORDER BY Program_Code__c ASC
                    ];
                }
            }

            results.add(programs);
        }

        return results;
    }

    /**
     * @description Request wrapper for getDealerPrograms invocable method
     */
    public class GetDealerProgramsRequest {
        @InvocableVariable(label='Dealer Account Id' description='The Id of the dealer Account record' required=true)
        public String dealerAccountId;
    }
}