peac_dev/force-app/main/default/objects/Broker__c/Broker__c.object-meta.xml
<CustomObject>
    <label>Broker</label>
    <nameField>
        <displayFormat>BR-{0000}</displayFormat>
        <label>Broker Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Brokers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

peac_dev/force-app/main/default/objects/Broker__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordType.Name</field>
            <operation>equals</operation>
            <value>Broker Account</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Broker Opportunities</relationshipLabel>
    <relationshipName>Brokers</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

peac_dev/force-app/main/default/objects/Broker__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Brokers</relationshipLabel>
    <relationshipName>Brokers1</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

peac_dev/force-app/main/default/classes/TC_BrokerLockRule.cls
public class TC_BrokerLockRule extends TC_LockRuleAbstract{
    
	// If in a lockable stage and user is not credit, do not allow user to add a broker
    public override void doCheck (TC_TriggerParams params) {
        
        Map <Id, Broker__c> newMap = (Map <Id, Broker__c>) params.getNewMap ();
        Map <Id, Broker__c> oldMap = (Map <Id, Broker__c>) params.getOldMap ();
        
        List <Broker__c> filtered = getFilteredList (params);
        Set <Id> oppIds = new Set <Id> ();
        Set <Id> accIds = new Set <Id> ();
        
        for (Broker__c broker : filtered) {
            oppIds.add (broker.Opportunity__c);
            accIds.add (broker.Account__c);
        }
        
        if (oppIds.isEmpty () || accIds.isEmpty()) return;
        
        Map <Id, Opportunity> oppMap = getOppMap (oppIds);
        Map <Id, Account> brokerAccounts = getAccMap (accIds);
        User user = getCurrentUser ();
            
        if (isCreditUser(user) || alwaysExcludedFromRules (user)) return;
            
        for (Broker__c broker : filtered) {
			if (inLockableStage (oppMap.get (broker.Opportunity__c))
				&& !oppMap.get (broker.Opportunity__c).Loan_Record_Type__c
                && !brokerAccounts.get (broker.Account__c).Override_Sales_Lockdown_Restrictions__c) {
					broker.addError ('Only Credit Users can add/update/delete a Broker in this stage'); 
			}
         }
    }
}