peac_dev/force-app/main/default/objects/Broker__c/Broker__c.object-meta.xml
<CustomObject>
    <label>Broker</label>
    <nameField>
        <displayFormat>BR-{0000}</displayFormat>
        <label>Broker Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Brokers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

peac_dev/force-app/main/default/objects/Broker__c/fields/Broker_Dealer_Number__c.field-meta.xml
<CustomField>
    <fullName>Broker_Dealer_Number__c</fullName>
    <formula>Account__r.Dealer_Number__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Broker Dealer Number</label>
    <type>Text</type>
</CustomField>

peac_dev/force-app/main/default/objects/Broker__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Brokers</relationshipLabel>
    <relationshipName>Brokers1</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

peac_dev/force-app/main/default/objects/Dealer__c/Dealer__c.object-meta.xml
<CustomObject>
    <label>Dealer</label>
    <nameField>
        <displayFormat>B-{0000}</displayFormat>
        <label>Dealer Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Dealers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

peac_dev/force-app/main/default/objects/Dealer__c/fields/Dealer__c.field-meta.xml
<CustomField>
    <fullName>Dealer__c</fullName>
    <label>Account</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Dealer Account, Dealer_Account Development, Dealer_Account Penetration, Dealer_Close, Dealer_Discovery, Dealer_Proposal, Dealer_Qualification</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Dealer Opportunities</relationshipLabel>
    <relationshipName>Dealers</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

peac_dev/force-app/main/default/objects/Dealer__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipName>Brokers</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

peac_dev/force-app/main/default/objects/Dealer__c/fields/Primary_Dealer__c.field-meta.xml
<CustomField>
    <fullName>Primary_Dealer__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Indicates if the dealer is primary dealer.</description>
    <label>Primary Dealer</label>
    <type>Checkbox</type>
</CustomField>

peac_dev/force-app/main/default/classes/TC_CDR011.cls
/**
 * Created by tamarack on 1/8/20.
 */

public with sharing class TC_CDR011 implements TC_CDRInterface {

    /**
     * CDR-011 Check Equip Approval Stip for 855331.7237
     * @description: https://marlinbusiness.atlassian.net/browse/SAL-1033
     * If:
     *    1. Decision_Status__c = Approved
     *    2. Dealer on Opportunity is marked as Primary_Dealer__c = TRUE
     *    3. Dealer_Number__c = 855331.7237
     * Then:
     *    1. set Stipulations__c = Equipment Approval
     * @param oldMap Map of old records from opportunity trigger
     * @param newMap Map of new records from opportunity trigger
     * @param filterIds Set of relevant opp Ids from opportunity trigger
     * @param relatedRecordsWrapper Wrapper object of related records to DML at end of CDRs
     */

    public static void runRule(Map<Id, Opportunity> oldMap, Map<Id, Opportunity> newMap
            , Set<Id> filterIds, TC_CreditDecision.relatedRecords relatedRecordsWrapper) {

        List<Broker__c> brokerList = new List<Broker__c>();
        if (!filterIds.isEmpty()) {
            brokerList = new List<Broker__c>([
                    SELECT Id, Opportunity__c
                    FROM Broker__c
                    WHERE Broker_Dealer_Number__c = '855331.7237' AND Opportunity__c IN: filterIds
            ]);
        }

        Map<Id, Broker__c> oppBrokerMap = new Map<Id, Broker__c>();
        for (Broker__c broker : brokerList) {
            oppBrokerMap.put(broker.Opportunity__c, broker);
        }

        for (Id oppId : filterIds) {
            if (newMap.get(oppId).Decision_Status__c == 'A' && oppBrokerMap.containsKey(oppId)
                    && (newMap.get(oppId).Stipulations__c == null
                    || (newMap.get(oppId).Stipulations__c != null && !newMap.get(oppId).Stipulations__c.contains('Equipment Approval')))) {
                if (newMap.get(oppId).Stipulations__c != null) newMap.get(oppId).Stipulations__c += ';';
                newMap.get(oppId).Stipulations__c += 'Equipment Approval';
                TC_ChatterHelper.addMessage(relatedRecordsWrapper.relatedChatterMap, oppId, 'Set Stipulations to \'Equipment Approval\'');
            }
        }

        /*
        Logic switched from Dealer to Broker
        List<Dealer__c> dealerList = new List<Dealer__c>();
        if (!filterIds.isEmpty()) {
            dealerList = new List<Dealer__c>([
                    SELECT Id, Opportunity__c
                    FROM Dealer__c
                    WHERE Primary_Dealer__c = TRUE AND Dealer__r.Dealer_Number__c = '855331.7237' AND Opportunity__c IN: filterIds
            ]);
        }

        Map<Id, Dealer__c> oppDealerMap = new Map<Id, Dealer__c>();
        for (Dealer__c dealer : dealerList) {
            oppDealerMap.put(dealer.Opportunity__c, dealer);
        }

        for (Id oppId : filterIds) {
            if (newMap.get(oppId).Decision_Status__c == 'A' && oppDealerMap.containsKey(oppId)
                    && (newMap.get(oppId).Stipulations__c == null
                        || (newMap.get(oppId).Stipulations__c != null && !newMap.get(oppId).Stipulations__c.contains('Equipment Approval')))) {
                newMap.get(oppId).Stipulations__c = 'Equipment Approval';
                TC_ChatterHelper.addMessage(relatedRecordsWrapper.relatedChatterMap, oppId, 'Set Stipulations to \'Equipment Approval\'');
            }
        }
        */

    }

}