peac_dev/force-app/main/default/objects/Broker__c/Broker__c.object-meta.xml
<CustomObject>
    <label>Broker</label>
    <nameField>
        <displayFormat>BR-{0000}</displayFormat>
        <label>Broker Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Brokers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

peac_dev/force-app/main/default/objects/Broker__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordType.Name</field>
            <operation>equals</operation>
            <value>Broker Account</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Broker Opportunities</relationshipLabel>
    <relationshipName>Brokers</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

peac_dev/force-app/main/default/objects/Broker__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Brokers</relationshipLabel>
    <relationshipName>Brokers1</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

peac_dev/force-app/main/default/objects/Broker__c/fields/Primary_Broker__c.field-meta.xml
<CustomField>
    <fullName>Primary_Broker__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Primary Broker</label>
    <type>Checkbox</type>
</CustomField>

peac_dev/force-app/main/default/objects/Contract__c/Contract__c.object-meta.xml
<CustomObject>
    <description>Custom Object created so we can use Queue functionality</description>
    <label>Contract</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Contract Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Contracts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

peac_dev/force-app/main/default/objects/Contract__c/fields/Dealer_Number__c.field-meta.xml
<CustomField>
    <fullName>Dealer_Number__c</fullName>
    <description>Get the Dealer Number from Dealer Account</description>
    <formula>Dealer_Name__r.Dealer_Number__c</formula>
    <label>Dealer Number</label>
    <type>Text</type>
</CustomField>

peac_dev/force-app/main/default/objects/Contract__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipName>Custom_Contracts</relationshipName>
    <type>Lookup</type>
</CustomField>

peac_dev/force-app/main/default/objects/Contract__c/fields/Tax_ID__c.field-meta.xml
<CustomField>
    <fullName>Tax_ID__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Tax ID</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

peac_dev/force-app/main/default/objects/Contract__c/recordTypes/Loan.recordType-meta.xml
<RecordType>
    <fullName>Loan</fullName>
    <active>false</active>
    <label>Loan</label>
</RecordType>

peac_dev/force-app/main/default/objects/Payee__c/Payee__c.object-meta.xml
<CustomObject>
    <label>Payee</label>
    <nameField>
        <displayFormat>PAY-{000000}</displayFormat>
        <label>Payee Indentification</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payees</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

peac_dev/force-app/main/default/objects/Payee__c/fields/Payee_ID__c.field-meta.xml
<CustomField>
    <fullName>Payee_ID__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>This is typically the same as the Payee&apos;s phone number.</inlineHelpText>
    <label>Payee ID</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

peac_dev/force-app/main/default/objects/Payee__c/fields/Payee_ID_Digits__c.field-meta.xml
<CustomField>
    <fullName>Payee_ID_Digits__c</fullName>
    <formula>SUBSTITUTE(
SUBSTITUTE(
SUBSTITUTE(Payee_ID__c, &quot;-&quot;, &quot;&quot;),
&quot;.&quot;, &quot;&quot;),
&quot; &quot;, &quot;&quot;)</formula>
    <label>Payee ID Digits</label>
    <type>Text</type>
</CustomField>

peac_dev/force-app/main/default/objects/Payee__c/fields/Tax_ID_Nbr__c.field-meta.xml
<CustomField>
    <fullName>Tax_ID_Nbr__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Tax ID Nbr</label>
    <length>11</length>
    <type>Text</type>
</CustomField>

peac_dev/force-app/main/default/objects/Payee__c/fields/Tax_Id_Nbr_Digits__c.field-meta.xml
<CustomField>
    <fullName>Tax_Id_Nbr_Digits__c</fullName>
    <formula>SUBSTITUTE(
SUBSTITUTE(
SUBSTITUTE(Tax_ID_Nbr__c, &quot;-&quot;, &quot;&quot;),
&quot;.&quot;, &quot;&quot;),
&quot; &quot;, &quot;&quot;)</formula>
    <label>Tax_Id_Nbr_Digits__c</label>
    <type>Text</type>
</CustomField>

peac_dev/force-app/main/default/objects/Payment__c/Payment__c.object-meta.xml
<CustomObject>
    <description>Payments to a Payee related to an opportunity</description>
    <label>Payment</label>
    <nameField>
        <displayFormat>PYMT-{0}</displayFormat>
        <label>Payment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

peac_dev/force-app/main/default/objects/Payment__c/fields/Invoice_Number__c.field-meta.xml
<CustomField>
    <fullName>Invoice_Number__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Invoice Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

peac_dev/force-app/main/default/objects/Payment__c/fields/Less_Origination_Fee__c.field-meta.xml
<CustomField>
    <fullName>Less_Origination_Fee__c</fullName>
    <label>Less Origination Fee</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

peac_dev/force-app/main/default/objects/Payment__c/fields/Loan_Amount__c.field-meta.xml
<CustomField>
    <fullName>Loan_Amount__c</fullName>
    <label>Loan Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

peac_dev/force-app/main/default/objects/Payment__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <inlineHelpText>Opportunity related to this payment</inlineHelpText>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Payments</relationshipLabel>
    <relationshipName>Payments</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

peac_dev/force-app/main/default/objects/Payment__c/fields/Payee__c.field-meta.xml
<CustomField>
    <fullName>Payee__c</fullName>
    <inlineHelpText>Payee related to this payment</inlineHelpText>
    <label>Payee</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 AND 2 AND 3</booleanFilter>
        <errorMessage>Value does not exist or does not match filter criteria or the Payee in Inactive</errorMessage>
        <filterItems>
            <field>Payee__c.SL_Vendor_ID__c</field>
            <operation>notEqual</operation>
            <value></value>
        </filterItems>
        <filterItems>
            <field>Payee__c.Active__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <filterItems>
            <field>Payee__c.Payee_Name__c</field>
            <operation>notContain</operation>
            <value>Do Not</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Payee__c</referenceTo>
    <relationshipLabel>Payments</relationshipLabel>
    <relationshipName>Payments</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

peac_dev/force-app/main/default/objects/Payment__c/fields/Payment_Method__c.field-meta.xml
<CustomField>
    <fullName>Payment_Method__c</fullName>
    <label>Payment Method</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Wire</fullName>
            </value>
            <value>
                <fullName>ACH</fullName>
            </value>
            <value>
                <fullName>Check</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

peac_dev/force-app/main/default/objects/Payment__c/fields/Payment_Status__c.field-meta.xml
<CustomField>
    <fullName>Payment_Status__c</fullName>
    <label>Payment Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>Ready to Send</fullName>
            </value>
            <value>
                <fullName>Payment Sent</fullName>
            </value>
            <value>
                <fullName>Payment Confirmed</fullName>
                <label>Payment Acknowledged</label>
            </value>
            <value>
                <fullName>Payment Released</fullName>
            </value>
            <value>
                <fullName>Void/Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

peac_dev/force-app/main/default/objects/Payment__c/fields/Plus_Commission__c.field-meta.xml
<CustomField>
    <fullName>Plus_Commission__c</fullName>
    <label>Plus Commission</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

peac_dev/force-app/main/default/classes/TC_AutoCreateLoanPaymentRecords.cls
public class TC_AutoCreateLoanPaymentRecords {
public static Set<Id> autoCreateLoanPaymentRecordsRanOppIds = new Set <Id> ();
    
    public static void autoCreateLoanPaymentRecords(Map <Id, Opportunity> oldMap, Map <Id, Opportunity> newMap) {
        
        Set <Id> oppIds = new Set <Id> ();
        
        for (Opportunity opp : newMap.values()) {
            if (opp.Loan_Record_Type__c && opp.StageName == 'Review for Booking' && oldMap.get(opp.Id).StageName == 'Docs In' && !autoCreateLoanPaymentRecordsRanOppIds.contains(opp.Id)) {
                oppIds.add(opp.Id);
                autoCreateLoanPaymentRecordsRanOppIds.add(opp.Id);
            }
        }
        
        if (!oppIds.isEmpty()) {
            
            //            Map <Id, Opportunity> oppMap = new Map <Id, Opportunity> ([SELECT Id, Account.Tax_ID__c, Primary_Broker__r.Dealer_Number__c, Contract__c, Origination_Fee__c, Loan_Amount__c, Loan_Points_Amount__c FROM Opportunity WHERE Id IN :oppIds]);
            Map <Id, Opportunity> oppMap = new Map <Id, Opportunity> ([SELECT Id, Account.Tax_ID__c, Contract__c, Origination_Fee__c, Loan_Amount__c, Loan_Points_Amount__c, (SELECT Id, Account__c, Account__r.Dealer_Number__c FROM Brokers1__r) FROM Opportunity WHERE Id IN :oppIds]);
            Map <Id, String> oppIdsToTaxIds = new Map <Id, String> ();
            //            Map <Id, String> oppIdsToDealerNumbers = new Map <Id, String> ();
            Map <Id, List <String>> oppIdsToDealerNumbers = new Map <Id, List <String>> ();
            Set <String> dealerNumberSet = new Set <String> ();
            
            for (Opportunity opp : oppMap.values()) {
                if (opp.Account.Tax_ID__c != null) oppIdsToTaxIds.put(opp.Id, opp.Account.Tax_ID__c.replaceAll('[^0-9]', ''));
                //                if (opp.Primary_Broker__r.Dealer_Number__c != null) oppIdsToDealerNumbers.put(opp.Id, opp.Primary_Broker__r.Dealer_Number__c.replaceAll('[^0-9]', ''));
                if (!opp.Brokers1__r.isEmpty()){
                    for (Broker__c b : opp.Brokers1__r){
                        if (b.Account__c != null && b.Account__r.Dealer_Number__c != null){
                            if (oppIdsToDealerNumbers.get(opp.Id) == null){
                                oppIdsToDealerNumbers.put(opp.Id, new List <String> {b.Account__r.Dealer_Number__c.replaceAll('[^0-9]', '')});
                            }else{
                                oppIdsToDealerNumbers.get(opp.Id).add(b.Account__r.Dealer_Number__c.replaceAll('[^0-9]', ''));
                            }
                            dealerNumberSet.add(b.Account__r.Dealer_Number__c.replaceAll('[^0-9]', ''));
                        }
                    }
                }
            }
            
            Boolean multiplePayeesFound;
            
            Id loanPaymentRecordTypeId = Schema.SObjectType.Payment__c.getRecordTypeInfosByName().get('Loan Payment').getRecordTypeId(); // would like to use getRecordTypesByDeveloperName instead, but that method isn't available in this API version used by this class.
            
            // Tax Ids
            
            Map <Id, Payment__c> oppIdsToTaxIdPayments = new Map <Id, Payment__c> ();
            
            if (!oppIdsToTaxIds.isEmpty()) {
                List <Payee__c> payeesByTaxIDs = [SELECT Id, Tax_ID_Nbr__c FROM Payee__c WHERE Tax_Id_Nbr_Digits__c IN :oppIdsToTaxIds.values()];
                
                if (!payeesByTaxIDs.isEmpty()) {
                    for (Id oppId : oppIdsToTaxIds.keySet()) {
                        multiplePayeesFound = false;
                        Integer i = 0;
                        
                        while (!multiplePayeesFound && i < payeesByTaxIDs.size()) {
                            
                            if (oppIdsToTaxIds.get(oppId) == payeesByTaxIDs[i].Tax_ID_Nbr__c.replaceAll('[^0-9]', '')) {
                                if (oppIdsToTaxIdPayments.get(oppId) == null) {
                                    //Need to make sure the fee is rounded to 2 decimal places for Solomon integration SAL-689
                                    Decimal lessOriginationFee = oppMap.get(oppId).Origination_Fee__c == 0 ? null : oppMap.get(oppId).Origination_Fee__c * oppMap.get(oppId).Loan_Amount__c * 0.01;
                                    if (lessOriginationFee != null) lessOriginationFee = lessOriginationFee.setScale(2, System.RoundingMode.HALF_UP);
                                    
                                    oppIdsToTaxIdPayments.put(oppId, new Payment__c(
                                        Payee__c = payeesByTaxIDs[i].Id,
                                        Loan_Amount__c = (oppMap.get(oppId).Loan_Amount__c == 0 ? null : oppMap.get(oppId).Loan_Amount__c),
                                        Payment_Status__c = 'Draft',
                                        Payment_Method__c = 'ACH',
                                        Invoice_Number__c = oppMap.get(oppId).Contract__c,
                                        Less_Origination_Fee__c = lessOriginationFee, //SAL-689
                                        Opportunity__c = oppId,
                                        RecordTypeId = loanPaymentRecordTypeId
                                    ));
                                } else {
                                    multiplePayeesFound = true;
                                    oppIdsToTaxIdPayments.remove(oppId);
                                }
                            }
                            i++;
                        }
                    }
                }
            }
            
            // Dealer Numbers
            
            Map <Id, Map <String, Payment__c>> oppIdsToDealerNumberPayments = new Map <Id, Map <String, Payment__c>> ();
            
            if (!oppIdsToDealerNumbers.isEmpty()) {
                List <Payee__c> payeesByDealerNumbers = [SELECT Id, Payee_ID__c FROM Payee__c WHERE Payee_ID_Digits__c IN :dealerNumberSet];
                
                if (!payeesByDealerNumbers.isEmpty()) {
                    for (Id oppId : oppIdsToDealerNumbers.keySet()) {
                        //Need to make sure the fee is rounded to 2 decimal places for Solomon integration SAL-689
                        Decimal lessOriginationFee = oppMap.get(oppId).Origination_Fee__c == 0 ? null : oppMap.get(oppId).Origination_Fee__c * oppMap.get(oppId).Loan_Amount__c * 0.01;
                        
                        for (String dealerNumberString : oppIdsToDealerNumbers.get(oppId)) {
                            
                            multiplePayeesFound = false;
                            Integer i = 0;
                            
                            while (!multiplePayeesFound && i < payeesByDealerNumbers.size()) {
                                
                                if (dealerNumberString == payeesByDealerNumbers[i].Payee_ID__c.replaceAll('[^0-9]', '') && oppMap.get(oppId).Loan_Points_Amount__c > 0) {
                                    if (oppIdsToDealerNumberPayments.get(oppId) == null) {
                                        
                                        if (lessOriginationFee != null) lessOriginationFee = lessOriginationFee.setScale(2, System.RoundingMode.HALF_UP);
                                        
                                        oppIdsToDealerNumberPayments.put(oppId, new Map<String, Payment__c>{
                                            dealerNumberString =>
                                                new Payment__c(
                                                    Payee__c = payeesByDealerNumbers[i].Id,
                                                    Plus_Commission__c = (oppMap.get(oppId).Loan_Points_Amount__c == 0 ? null : oppMap.get(oppId).Loan_Points_Amount__c),
                                                    Payment_Status__c = 'Draft',
                                                    Payment_Method__c = 'ACH',
                                                    Invoice_Number__c = oppMap.get(oppId).Contract__c,
                                                    //Less_Origination_Fee__c = lessOriginationFee, //SAL-689 // commented for SAL-1801
                                                    Opportunity__c = oppId,
                                                    RecordTypeId = loanPaymentRecordTypeId
                                                )
                                                });
                                    } else if (oppIdsToDealerNumberPayments.get(oppId).get(dealerNumberString) == null){
                                        oppIdsToDealerNumberPayments.get(oppId).put(dealerNumberString, new Payment__c(
                                            Payee__c = payeesByDealerNumbers[i].Id,
                                            Plus_Commission__c = (oppMap.get(oppId).Loan_Points_Amount__c == 0 ? null : oppMap.get(oppId).Loan_Points_Amount__c),
                                            Payment_Status__c = 'Draft',
                                            Payment_Method__c = 'ACH',
                                            Invoice_Number__c = oppMap.get(oppId).Contract__c,
                                            //Less_Origination_Fee__c = lessOriginationFee, //SAL-689 // commented for SAL-1801
                                            Opportunity__c = oppId,
                                            RecordTypeId = loanPaymentRecordTypeId
                                        ));
                                    } else {
                                        multiplePayeesFound = true;
                                        oppIdsToDealerNumberPayments.get(oppId).remove(dealerNumberString);
                                    }
                                }
                                i++;
                            }
                        }
                    }
                }
            }
            
            if (!(oppIdsToDealerNumberPayments.isEmpty() && oppIdsToTaxIdPayments.isEmpty())) {
                List <Payment__c> newPayments = new List <Payment__c> ();
                //                newPayments.addAll(oppIdsToDealerNumberPayments.values());
                for (Map <String, Payment__c> m : oppIdsToDealerNumberPayments.values()){
                    if (!m.isEmpty()) newPayments.addAll(m.values());
                }
                
                newPayments.addAll(oppIdsToTaxIdPayments.values());
                insert newPayments;
            }
        }
    }
    
}