peac_dev/force-app/main/default/objects/Broker__c/Broker__c.object-meta.xml
<CustomObject>
    <label>Broker</label>
    <nameField>
        <displayFormat>BR-{0000}</displayFormat>
        <label>Broker Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Brokers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

peac_dev/force-app/main/default/objects/Broker__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordType.Name</field>
            <operation>equals</operation>
            <value>Broker Account</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Broker Opportunities</relationshipLabel>
    <relationshipName>Brokers</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

peac_dev/force-app/main/default/objects/Broker__c/fields/Broker_Dealer_Number__c.field-meta.xml
<CustomField>
    <fullName>Broker_Dealer_Number__c</fullName>
    <formula>Account__r.Dealer_Number__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Broker Dealer Number</label>
    <type>Text</type>
</CustomField>

peac_dev/force-app/main/default/objects/Broker__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Brokers</relationshipLabel>
    <relationshipName>Brokers1</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

peac_dev/force-app/main/default/objects/Broker__c/fields/Primary_Broker__c.field-meta.xml
<CustomField>
    <fullName>Primary_Broker__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Primary Broker</label>
    <type>Checkbox</type>
</CustomField>

peac_dev/force-app/main/default/objects/Field_Tracker__c/Field_Tracker__c.object-meta.xml
<CustomObject>
    <label>Field Tracker</label>
    <nameField>
        <displayFormat>CFT-{000000000}</displayFormat>
        <label>Credit Fields Tracker Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Field Tracker</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

peac_dev/force-app/main/default/objects/Field_Tracker__c/fields/Action__c.field-meta.xml
<CustomField>
    <fullName>Action__c</fullName>
    <label>Action</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Created</fullName>
            </value>
            <value>
                <fullName>Modified</fullName>
            </value>
            <value>
                <fullName>Deleted</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

peac_dev/force-app/main/default/objects/Field_Tracker__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipName>Credit_Fields_Tracker</relationshipName>
    <type>Lookup</type>
</CustomField>

peac_dev/force-app/main/default/objects/FieldTrackingForLoan__mdt/FieldTrackingForLoan__mdt.object-meta.xml
<CustomObject>
    <label>FieldTrackingForLoan</label>
    <pluralLabel>FieldTrackingForLoan</pluralLabel>
</CustomObject>

peac_dev/force-app/main/default/objects/FieldTrackingForLoan__mdt/fields/GDS_Fields__c.field-meta.xml
<CustomField>
    <fullName>GDS_Fields__c</fullName>
    <label>GDS Fields</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

peac_dev/force-app/main/default/objects/FieldTrackingForLoan__mdt/fields/Object_Name__c.field-meta.xml
<CustomField>
    <fullName>Object_Name__c</fullName>
    <label>Object Name</label>
    <type>TextArea</type>
</CustomField>

peac_dev/force-app/main/default/objects/GDS_Mapping__mdt/GDS_Mapping__mdt.object-meta.xml
<CustomObject>
    <description>Store the GDS Mapping for xml preparation</description>
    <label>GDS Mapping</label>
    <pluralLabel>GDS Mapping</pluralLabel>
</CustomObject>

peac_dev/force-app/main/default/objects/GDS_Mapping__mdt/fields/Object_Name__c.field-meta.xml
<CustomField>
    <fullName>Object_Name__c</fullName>
    <description>Store object name</description>
    <label>Object Name</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Gds_Score_Request_Company__c</fullName>
                <default>true</default>
                <label>Gds Score Request Company</label>
            </value>
            <value>
                <fullName>Contact</fullName>
            </value>
            <value>
                <fullName>Opportunity</fullName>
            </value>
            <value>
                <fullName>Gds_Score_Request_Individual__c</fullName>
                <label>Gds Score Request Individual</label>
            </value>
            <value>
                <fullName>Financial__c</fullName>
                <label>Financial</label>
            </value>
            <value>
                <fullName>Competitor__c</fullName>
                <label>Competitor</label>
            </value>
            <value>
                <fullName>Bank Information</fullName>
            </value>
            <value>
                <fullName>Bank Statements</fullName>
            </value>
            <value>
                <fullName>Webservice_Field__c</fullName>
                <label>Webservice Field</label>
            </value>
            <value>
                <fullName>GDS_Score__c</fullName>
                <label>GDS Score</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

peac_dev/force-app/main/default/objects/Gds_Score__c/Gds_Score__c.object-meta.xml
<CustomObject>
    <label>Gds Score Request/Response</label>
    <nameField>
        <displayFormat>GdsScore-{0000}</displayFormat>
        <label>Gds Score Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Gds Score Gds Score Requests/Responses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

peac_dev/force-app/main/default/objects/Gds_Score__c/fields/Broker__c.field-meta.xml
<CustomField>
    <fullName>Broker__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Broker</label>
    <referenceTo>Gds_Score_Request_Company__c</referenceTo>
    <relationshipName>Gds_Scores2</relationshipName>
    <type>Lookup</type>
</CustomField>

peac_dev/force-app/main/default/objects/Gds_Score__c/fields/Credit_Strategy__c.field-meta.xml
<CustomField>
    <fullName>Credit_Strategy__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Credit Strategy</label>
    <type>TextArea</type>
</CustomField>

peac_dev/force-app/main/default/objects/Gds_Score__c/fields/Loan_Purpose__c.field-meta.xml
<CustomField>
    <fullName>Loan_Purpose__c</fullName>
    <description>Store loan purpose from opportunity</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Loan Purpose</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

peac_dev/force-app/main/default/objects/Gds_Score__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipName>Gds_Scores</relationshipName>
    <type>Lookup</type>
</CustomField>

peac_dev/force-app/main/default/objects/Gds_Score_Request_Company__c/Gds_Score_Request_Company__c.object-meta.xml
<CustomObject>
    <label>Gds Score Request Company</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Gds Score Request Company Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Gds Score Request Companies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

peac_dev/force-app/main/default/objects/Gds_Score_Request_Company__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <description>Store Primary contact name</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Contact</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

peac_dev/force-app/main/default/objects/Gds_Score_Request_Individual__c/Gds_Score_Request_Individual__c.object-meta.xml
<CustomObject>
    <label>Gds Score Request Individual</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Gds Score Request Individual Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Gds Score Request Individuals</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

peac_dev/force-app/main/default/objects/Gds_Score_Request_Individual__c/fields/PG_Number__c.field-meta.xml
<CustomField>
    <fullName>PG_Number__c</fullName>
    <label>PG Number</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

peac_dev/force-app/main/default/objects/Guarantor__c/Guarantor__c.object-meta.xml
<CustomObject>
    <label>Guarantor</label>
    <nameField>
        <displayFormat>G-{00000}</displayFormat>
        <label>Guarantor Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Guarantors</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

peac_dev/force-app/main/default/objects/Guarantor__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>GuarantorS</relationshipLabel>
    <relationshipName>GuarantorAccount</relationshipName>
    <type>Lookup</type>
</CustomField>

peac_dev/force-app/main/default/objects/Guarantor__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Guarantors</relationshipLabel>
    <relationshipName>GuarantorContact</relationshipName>
    <type>Lookup</type>
</CustomField>

peac_dev/force-app/main/default/objects/Guarantor__c/fields/Latest_Rescore_Date__c.field-meta.xml
<CustomField>
    <fullName>Latest_Rescore_Date__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Latest Rescore Date</label>
    <type>DateTime</type>
</CustomField>

peac_dev/force-app/main/default/objects/Guarantor__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <description>master detail relationship to Opportunity</description>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Guarantors</relationshipLabel>
    <relationshipName>Guarantor</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

peac_dev/force-app/main/default/objects/Guarantor__c/fields/PG_N__c.field-meta.xml
<CustomField>
    <fullName>PG_N__c</fullName>
    <formula>IF( TEXT( PG_Number__c )== &apos;PG1&apos;,1,  IF( TEXT( PG_Number__c )== &apos;PG2&apos;,2,  IF( TEXT( PG_Number__c )== &apos;PG3&apos;,3,  IF( TEXT( PG_Number__c )== &apos;PG4&apos;,4, 0) ) ) )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>PG N</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

peac_dev/force-app/main/default/objects/Guarantor__c/fields/PG_Number__c.field-meta.xml
<CustomField>
    <fullName>PG_Number__c</fullName>
    <inlineHelpText>This PG number identifies the sequence of Guarantors.</inlineHelpText>
    <label>PG Number</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>PG1</fullName>
            </value>
            <value>
                <fullName>PG2</fullName>
            </value>
            <value>
                <fullName>PG3</fullName>
            </value>
            <value>
                <fullName>PG4</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

peac_dev/force-app/main/default/objects/Guarantor__c/fields/Primary__c.field-meta.xml
<CustomField>
    <fullName>Primary__c</fullName>
    <formula>IF(Priority__c =1,true,false)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Primary</label>
    <type>Checkbox</type>
</CustomField>

peac_dev/force-app/main/default/objects/Guarantor__c/fields/RP_PRIN_GUAR_CODE__c.field-meta.xml
<CustomField>
    <fullName>RP_PRIN_GUAR_CODE__c</fullName>
    <label>Guarantor Code</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Principal</fullName>
            </value>
            <value>
                <fullName>Guarantor</fullName>
                <default>true</default>
                <label>Guarantor</label>
            </value>
            <value>
                <fullName>Corporate Guaranty</fullName>
            </value>
            <value>
                <fullName>Brokers Vendor</fullName>
            </value>
            <value>
                <fullName>Franchisors Vendor</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

peac_dev/force-app/main/default/objects/Guarantor__c/fields/Sync_To_GDS__c.field-meta.xml
<CustomField>
    <fullName>Sync_To_GDS__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Determine whether the PG value has already been sent from rescore or not.</description>
    <label>Sync To GDS</label>
    <type>Checkbox</type>
</CustomField>

peac_dev/force-app/main/default/objects/Guarantor__c/recordTypes/Corporate.recordType-meta.xml
<RecordType>
    <fullName>Corporate</fullName>
    <active>true</active>
    <label>Corporate</label>
</RecordType>

peac_dev/force-app/main/default/objects/Webservice_Field__c/Webservice_Field__c.object-meta.xml
<CustomObject>
    <label>Webservice Field</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Webservice Field Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Webservice Fields</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

peac_dev/force-app/main/default/objects/Webservice_Field__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Webservice Fields</relationshipLabel>
    <relationshipName>Webservice_Fields</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

peac_dev/force-app/main/default/classes/PEAC_GdsScoreLoanMapper.cls
/************************************************************************************************************************
 @Description: Queries aplication data and map usinf flow and custom metadata.
 @Author: Rajesh Kumar(LTIMindtree)
 @Created Date: 06/16/2025
 ************************************************************************************************************************/

public with sharing class PEAC_GdsScoreLoanMapper {
    
    public static PEAC_GDSScoreLoanReqRespBean mapSalesforceToBean(Id oppId) {
        PEAC_GDSScoreLoanReqRespBean reqRespBean = new PEAC_GDSScoreLoanReqRespBean ();

        // get salesforce ids to pass into mapping flows, apex orchestrates the flows
        List <Opportunity> opps = new List <Opportunity> ([
                SELECT Id
                        , Primary_Source__c
                        , AccountId
                        , Marlin_Business_Group__c,Loan_Purpose__c, CustomerType__c,Decision_Status__c, Digital_Portal_ID__c, Credit_Strategy__c
                        , (SELECT Id, Account__c, Contact__c, RecordType.Name, Primary__c,Sync_To_GDS__c,LastModifiedDate,Latest_Rescore_Date__c, IsDeleted, PG_Number__c, PG_N__c FROM Guarantor__r WHERE RP_PRIN_GUAR_CODE__c != 'Principal' 
                           AND PG_Number__c != null AND PG_N__c != 0 ORDER BY CreatedDate ASC)
                        , (SELECT Account__c, Primary_Broker__c, Broker_Dealer_Number__c  FROM Brokers1__r ORDER BY CreatedDate ASC)
                        
                FROM Opportunity
                WHERE Id = :oppId ALL ROWS
        ]);
        Opportunity opp = new Opportunity ();
        if (!opps.isEmpty ()) {
            reqRespBean.opp = opps[0];
            opp = opps[0];
            if( PEAC_GDSScoreLoanAPI.callType == 'SF' || PEAC_GDSScoreLoanAPI.callType == 'LP')
            {
                //LTIMindtree updated date 02-12-2025. SAL-6014
               reqRespBean.opp.Application_Status__c = (opp.Loan_Purpose__c != 'Teaser') ? 'In Process'  : 'Pending';
            }
        }
        Id salesforcePrimaryBrokerId;
        for (Broker__c broker : opp.Brokers1__r) {
            if (salesforcePrimaryBrokerId == null) {
                salesforcePrimaryBrokerId = broker.Account__c;
            }
        }
        List<Webservice_Field__c> latestCustomerCreditExpList = getWebserviceField ('DWH_GetCustomerCreditExposure','getGdsGetCustCreditExpLoan',oppId);
        List<Webservice_Field__c> latestFraudList = getWebserviceField ('GetFraudFlags','getGDSFraudFlags',oppId);
 
        
        reqRespBean.wsFields = !latestCustomerCreditExpList.isEmpty() ? latestCustomerCreditExpList[0] : null;
        reqRespBean.wsFieldsFraud = !latestFraudList.isEmpty() ? latestFraudList[0] : null;
        
        /*** instantiate req bean ***/

        // set oppId
        reqRespBean.oppId = oppId;
        reqRespBean.scoreReq.Opportunity__c = oppId;

        /*** add salesforce records to easy access variables ***/

        set <Id> salesforcePgIds = new set <Id> ();
        
        // pgs and ccg
        Map <Id, Id> conPgIdMap = new Map <Id, Id> (); // need to find assosiate the 2 becuase I map back to the pg
        Map<string, PGTypeWrapper> pgMap = new Map<string, PGTypeWrapper>();
        List<Guarantor__c> guarList = [SELECT Latest_Rescore_Date__c FROM Guarantor__c WHERE RP_PRIN_GUAR_CODE__c != 'Principal' 
                                       AND PG_Number__c != null AND PG_N__c != 0 AND Opportunity__c =: oppId AND Latest_Rescore_Date__c != null
                                       ORDER BY Latest_Rescore_Date__c DESC ALL ROWS];
        DateTime latestRescoreDate;
        
        if(guarList.size() > 0) {
            if(guarList.get(0).Latest_Rescore_Date__c != null) {
                latestRescoreDate = guarList.get(0).Latest_Rescore_Date__c;
            }
        }
                            System.debug('Debugger::latestRescoreDate::'+latestRescoreDate);
        // get salesforce list of pgs only up to 4 pgs
        if (!opp.Guarantor__r.isEmpty ()) {
            for (Integer i = 0; i < opp.Guarantor__r.size(); i++) {
                Guarantor__c guar = opp.Guarantor__r[i];
                if (guar.RecordType.Name != 'Corporate') {
                if(guar.IsDeleted && (guar.Latest_Rescore_Date__c == null || guar.LastModifiedDate < latestRescoreDate)) {
                     continue;
                  }
                 // if (guar.IsDeleted) continue; 
                  
                    PGTypeWrapper pg = new PGTypeWrapper();
                    pg.pgType = guar.PG_Number__c;
                    pg.pgN = Integer.valueOf(guar.PG_N__c);
                    
                    // NEW: mark unsynced guarantors as "new" (to be considered changed)
                    Boolean isNewUnsynced = (guar.Sync_To_GDS__c == false || guar.Sync_To_GDS__c == null);
                    
                    if(pgMap.containsKey(guar.PG_Number__c)) {
                        pg = pgMap.get(guar.PG_Number__c);
                       // if(guar.PG_Number__c == 'PG2') {
                            System.debug('Debugger::guar::'+guar);
                       // }
                        if(!guar.IsDeleted && pg.isDeleted && !guar.Sync_To_GDS__c) {
                            //Old Record is deleted and Creating new record 
                            //Added new check - To check, whether the details, it's already been synced or not
                            pg.guar = guar;
                            pg.ContactId = guar.Contact__c;
                            pg.isChanged = true;
                            pg.isDeleted = false;
                        } else if(guar.IsDeleted && !pg.isChanged && (latestRescoreDate == null || (guar.LastModifiedDate > latestRescoreDate))) {
                            System.debug('Debugger::gaur::'+ guar.LastModifiedDate);
                            System.debug('Debugger::gaur::'+ latestRescoreDate);
                            //Old Record is deleted
                            //Added new check - To check, whether the details, it's already been synced or not
                            pg.isDeleted = true;
                        } else {
                            // Nothing
                            pg.guar = guar;
                            pg.ContactId = guar.Contact__c;
                            pg.isChanged = false;
                            pg.isDeleted = false;
                            
                        }
                        
                        // NEW: if not deleted and not yet synced, consider it "changed" (Y)
                        if (!pg.isDeleted && isNewUnsynced) { pg.isChanged = true; }
                   
                            System.debug('Debugger::'+pg);
                     
                    } else {
                        // Initialize
                        pg.guar = guar;
                        pg.ContactId = guar.Contact__c;
                        pg.isDeleted = guar.IsDeleted && (guar.LastModifiedDate > latestRescoreDate);
                        
                        // NEW: if not deleted and not yet synced, consider it "changed" (Y)
                        if (!pg.isDeleted && isNewUnsynced) 
                        { 
                            pg.isChanged = true; 
                        }
                        
                    }
                    if(pg.ContactId == null) {
                        pg.ContactId = guar.Contact__c;
                    } 
                    pgMap.put(guar.PG_Number__c, pg);
                    salesforcePgIds.add (guar.Contact__c);
                    //conPgIdMap.put (guar.Contact__c, guar.Id);
                }
            }
        }
        Set<Id> changeContactIdSet = new Set<Id>();
        Boolean isAccountChanged = false;
        FieldTrackingForLoan__mdt trackingContactConfigs = FieldTrackingForLoan__mdt.getInstance('Contact');
        FieldTrackingForLoan__mdt trackingAccountConfigs = FieldTrackingForLoan__mdt.getInstance('Account');
        for(Field_Tracker__c tracker : [select Record_Id__c,Object_Name__c from Field_Tracker__c
                                        where (Object_Name__c = 'Contact' 
                                        AND Field_Name__c IN :trackingContactConfigs.GDS_Fields__c.split(';')
                                        AND Record_Id__c IN :salesforcePgIds AND Opportunity__c = :opp.Id
                                        AND Action__c = 'Modified') 
                                        OR 
                                        (Object_Name__c = 'Account' 
                                        AND Field_Name__c IN :trackingAccountConfigs.GDS_Fields__c.split(';')
                                        AND Record_Id__c = :opp.AccountId AND Opportunity__c = :opp.Id
                                        AND Action__c = 'Modified')
                                       ]) {
                                           if(tracker.Object_Name__c == 'Contact') {
                                               changeContactIdSet.add(tracker.Record_Id__c);     
                                           } else if(tracker.Object_Name__c == 'Account') {
                                               isAccountChanged = true;
                                           }
        }

        /*** Send salesforce ids into mapping flows ***/

        // map main applicaton bean
        Flow.Interview.GDS_Score_Loan_Application_Request_Mapping mapApplicationLevelFields = new Flow.Interview.GDS_Score_Loan_Application_Request_Mapping(new Map <String, Object>{
                'varOppId' => oppId, 'CallType' =>PEAC_GDSScoreLoanAPI.callType
        });
        mapApplicationLevelFields.start ();
        reqRespBean.scoreReq = (Gds_Score__c) mapApplicationLevelFields.getVariableValue('varRequestBean');
        // map company1 bean
        Flow.Interview.GDS_Score_Loan_Company_Request_Mapping1 mapCompany1LevelFields = new Flow.Interview.GDS_Score_Loan_Company_Request_Mapping1(new Map <String, Object>{
                'varAccId' => opp.AccountId, 'varCompanyType' => 'company1','varOppId' =>opp.Id 
        });
        mapCompany1LevelFields.start ();
        Gds_Score_Request_Company__c company = (Gds_Score_Request_Company__c) mapCompany1LevelFields.getVariableValue('varRequestBean');
        company.Is_Company_Changed__c = isAccountChanged;
        reqRespBean.company1 = company;
        
        //Map broker
        Flow.Interview.GDS_Score_Loan_Company_Request_Mapping1 mapBrokerLevelFields = new Flow.Interview.GDS_Score_Loan_Company_Request_Mapping1(new Map <String, Object>{
                'varAccId' => salesforcePrimaryBrokerId, 'varCompanyType' => 'BV','varOppId' =>opp.Id 
        });
        mapBrokerLevelFields.start ();
        reqRespBean.broker = (Gds_Score_Request_Company__c) mapBrokerLevelFields.getVariableValue('varRequestBean');
        
        // Map pg
        /*if (!salesforcePgIds.isEmpty ()) {
            for (Id pgId : salesforcePgIds) {
                Flow.Interview.GDS_Score_Loan_Individual_Request_Mapping mapPgLevelFields = new Flow.Interview.GDS_Score_Loan_Individual_Request_Mapping(new Map <String, Object>{
                        'varConId' => pgId
                });
                mapPgLevelFields.start ();
                Gds_Score_Request_Individual__c ind = (Gds_Score_Request_Individual__c) mapPgLevelFields.getVariableValue('varRequestBean');
                ind.Guarantor_Based_On__c = conPgIdMap.get (pgId);
                reqRespBean.pgs.add (ind);
            }
        }*/
        System.debug('pgMap::'+pgMap);
        if (!pgMap.isEmpty ()) {
            for (string pgId : pgMap.keySet()) {
                PGTypeWrapper pg = pgMap.get(pgId);
                
                Flow.Interview.GDS_Score_Loan_Individual_Request_Mapping mapPgLevelFields = new Flow.Interview.GDS_Score_Loan_Individual_Request_Mapping(new Map <String, Object>{
                        'varConId' => pg.ContactId
                });
                mapPgLevelFields.start ();
                Gds_Score_Request_Individual__c ind = (Gds_Score_Request_Individual__c) mapPgLevelFields.getVariableValue('varRequestBean');
                if( pg.guar != null && !pg.guar.IsDeleted) {
                    ind.Guarantor_Based_On__c = pg.guar.Id;
                }
                
                ind.Is_PG_Deleted__c = pg.isDeleted;
                ind.PG_Number__c = pg.pgN;
                ind.Is_PG_Changed__c = pg.isChanged || changeContactIdSet.contains(pg.ContactId);
                reqRespBean.pgs.add (ind);
            }
        }
         
        System.debug('reqRespBean.pgs::'+reqRespBean.pgs);
        return reqRespBean;
    }

    public static List<Webservice_Field__c> getWebserviceField (String nodePath, String storeProcedure,Id oppId)
    {
        String sQueryFields = getDyanamicFields(nodePath);
        string sQuery = 'SELECT ' + sQueryFields + ' FROM Webservice_Field__c WHERE Opportunity__c =:oppId AND Stored_Procedure__c =:storeProcedure ORDER BY CreatedDate DESC LIMIT 1';
        List<Webservice_Field__c> latestWebServiceFieldRecord = new List<Webservice_Field__c>();
        latestWebServiceFieldRecord = Database.query(sQuery);
        return latestWebServiceFieldRecord;
    }
    //get gds_score related field mapping from custom metadata
    public static String getDyanamicFields(String nodePathName){
        GDS_Mapping__mdt gdsMapping = [SELECT label,Field_Mapping_Details__c,Object_Name__c FROM GDS_Mapping__mdt WHERE developerName =:nodePathName];
        string sQueryFields = 'Id';
        Set<String> strValueSet = new Set<String>();
        if(gdsMapping !=null)
        {
            list<String> gdsTagWithFieldsList = gdsMapping.Field_Mapping_Details__c.split('\\r?\\n');
            if(!gdsTagWithFieldsList.isEmpty() )
            {

                for(String gdsTagWithFieldMap : gdsTagWithFieldsList)
                {
                    List<String> gdsTagAndFieldList = gdsTagWithFieldMap.split('-');
                    strValueSet.add(gdsTagAndFieldList[1]);
                }
            }
            for (String field : strValueSet) {
                if(field != 'Id')
                sQueryFields += ',' + field;
            }
        }
        return sQueryFields;
    }

    public static void mapBeanToSalesforce(PEAC_GDSScoreLoanReqRespBean reqResp) {
        PEAC_GdsScoreLoanApi.dmlSObjectCalloutRecords (reqResp);
    }

    public class PGTypeWrapper {
        public string pgType;
        public boolean isChanged;
        public boolean isDeleted;
        public Guarantor__c guar;
        public string contactId;
        public integer pgN;
        
        public PGTypeWrapper() {
            isChanged = false;
            isDeleted = false;
        }
    }




}