peac_dev/force-app/main/default/objects/SF2SLLog__c/SF2SLLog__c.object-meta.xml
<CustomObject>
    <label>SF2SLLog</label>
    <nameField>
        <displayFormat>SF2SL{0000000}</displayFormat>
        <label>SF2SLLog Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SF2SLLogs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

peac_dev/force-app/main/default/objects/SF2SLLog__c/fields/CreateDate__c.field-meta.xml
<CustomField>
    <fullName>CreateDate__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>CreateDate</label>
    <required>true</required>
    <type>DateTime</type>
</CustomField>

peac_dev/force-app/main/default/objects/SF2SLLog__c/fields/LogType__c.field-meta.xml
<CustomField>
    <fullName>LogType__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>LogType</label>
    <length>128</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

peac_dev/force-app/main/default/objects/SLIntegration__c/SLIntegration__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Settings for SL Integration</description>
    <label>SL Integration</label>
</CustomObject>

peac_dev/force-app/main/default/objects/SLIntegration__c/fields/SLAuthorization__c.field-meta.xml
<CustomField>
    <fullName>SLAuthorization__c</fullName>
    <description>SL Authorization</description>
    <encryptionScheme>None</encryptionScheme>
    <label>SLAuthorization</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

peac_dev/force-app/main/default/objects/SLIntegration__c/fields/SLIntegrationEndpoint__c.field-meta.xml
<CustomField>
    <fullName>SLIntegrationEndpoint__c</fullName>
    <description>SL Integration Endpoint</description>
    <encryptionScheme>None</encryptionScheme>
    <label>SLIntegrationEndpoint</label>
    <required>true</required>
    <type>Url</type>
</CustomField>

peac_dev/force-app/main/default/objects/SLIntegration__c/fields/SLSiteID__c.field-meta.xml
<CustomField>
    <fullName>SLSiteID__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>SLSiteID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

peac_dev/force-app/main/default/classes/xct_Solomon.cls
@isTest
public class xct_Solomon {
    @isTest static void xctSolomonBaseTest() {
        System.debug ('<<<<< xctDataClassTest');
        // Test data setup
        
        // Perform test
        Test.startTest();
            System.debug ('<<<<< right before xctDataClass.makeCallout');
                SLIntegration__c SLI = new SLIntegration__c(Name='SLINTEGRATE',SLSiteID__c='TEST', SLAuthorization__c='QVBJS0VZMTpBRTRFM0Q0MEJFRTU0NjA0QUI0QTgzRkFGQzMzRjJDQg==', SLIntegrationEndpoint__c='https://dsliis.asu-nvg.com/ctIntegrator/api/integration/ctQueue/');
                insert SLI;
                xctDataClass.makeCallout('SFDATA', 'DUMMYID', 'TEST', 'XMLContentField');
            System.debug ('<<<<< right afterCall');
            System.debug ('<<<<< right before xctSLLogging.creatLog');
                xctSLLogging.creatLog('makeCallout', 'SFDATA', 'TEST', 'TEST');
            System.debug ('<<<<< right afterCall');
            
            System.debug ('<<<<< right before sf2SLLogs');
                 SF2SLLog__c obj = new SF2SLLog__c(CreateDate__c=System.today(), LogType__c='TEST');
                 insert obj;
        
                 PageReference pageRef = Page.SF2SLLog1;
                 Test.setCurrentPage(pageRef);
                 ApexPages.StandardController sc = new ApexPages.StandardController(obj);
                 xctSF2SLLogs testPlan = new xctSF2SLLogs(sc);
                 testPlan.clearSF2SLLogs();
                
                     System.debug ('<<<<< right afterCall');
           
        Test.stopTest();
       
    }
    
}