peac_dev/force-app/main/default/objects/SF2SLLog__c/SF2SLLog__c.object-meta.xml
<CustomObject>
    <label>SF2SLLog</label>
    <nameField>
        <displayFormat>SF2SL{0000000}</displayFormat>
        <label>SF2SLLog Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SF2SLLogs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

peac_dev/force-app/main/default/objects/SF2SLLog__c/fields/CreateDate__c.field-meta.xml
<CustomField>
    <fullName>CreateDate__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>CreateDate</label>
    <required>true</required>
    <type>DateTime</type>
</CustomField>

peac_dev/force-app/main/default/objects/SF2SLLog__c/fields/IDField__c.field-meta.xml
<CustomField>
    <fullName>IDField__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>IDField</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

peac_dev/force-app/main/default/objects/SF2SLLog__c/fields/LogType__c.field-meta.xml
<CustomField>
    <fullName>LogType__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>LogType</label>
    <length>128</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

peac_dev/force-app/main/default/objects/SF2SLLog__c/fields/Object__c.field-meta.xml
<CustomField>
    <fullName>Object__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Object</label>
    <length>128</length>
    <type>Text</type>
</CustomField>

peac_dev/force-app/main/default/objects/SF2SLLog__c/fields/Request__c.field-meta.xml
<CustomField>
    <fullName>Request__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Request</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

peac_dev/force-app/main/default/objects/SF2SLLog__c/fields/Response__c.field-meta.xml
<CustomField>
    <fullName>Response__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Response</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

peac_dev/force-app/main/default/classes/xctSLLogging.cls
public with sharing class xctSLLogging {

    public static void creatLog(String CallingAPI, String ObjectName, String Request, String Response) {
        creatLog(CallingAPI, ObjectName, '0', Request, Response);
    }
    public static void creatLog(String CallingAPI, String ObjectName, String IDO, String Request, String Response) {
        System.debug('creatLog:' + CallingAPI);
        try {
            DateTime createdOn = DateTime.NOW();
            SF2SLLog__c SLlog = new SF2SLLog__c(CreateDate__c=createdOn, Object__c=ObjectName,LogType__c=CallingAPI, IDField__c=IDO, Request__c=Request, Response__c=Response);
            insert SLlog;
        } catch(DmlException e) {
            System.debug('An unexpected error has occurred: ' + e.getMessage());
        }
    }

}