peac_dev/force-app/main/default/objects/Buyout__c/Buyout__c.object-meta.xml
<CustomObject>
    <description>Object to store active and legacy Buyouts returned by Infolease. Data in this object will be purged on a 6 month rolling basis</description>
    <label>Buyout</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Buyout Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Buyouts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

peac_dev/force-app/main/default/objects/Buyout__c/fields/Buyout_Amount__c.field-meta.xml
<CustomField>
    <fullName>Buyout_Amount__c</fullName>
    <defaultValue>0.00</defaultValue>
    <label>Buyout Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

peac_dev/force-app/main/default/objects/Buyout__c/fields/Buyout_Type__c.field-meta.xml
<CustomField>
    <fullName>Buyout_Type__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Buyout Type</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

peac_dev/force-app/main/default/objects/Buyout__c/fields/Contract__c.field-meta.xml
<CustomField>
    <fullName>Contract__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contract</label>
    <referenceTo>Contract__c</referenceTo>
    <relationshipLabel>Buyouts</relationshipLabel>
    <relationshipName>Buyouts</relationshipName>
    <type>Lookup</type>
</CustomField>

peac_dev/force-app/main/default/objects/Buyout__c/fields/Date_Quoted__c.field-meta.xml
<CustomField>
    <fullName>Date_Quoted__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Date Quoted</label>
    <type>Date</type>
</CustomField>

peac_dev/force-app/main/default/objects/Buyout__c/fields/Expiration_Date__c.field-meta.xml
<CustomField>
    <fullName>Expiration_Date__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Expiration Date</label>
    <type>Date</type>
</CustomField>

peac_dev/force-app/main/default/objects/Buyout__c/fields/Partial_Buyout__c.field-meta.xml
<CustomField>
    <fullName>Partial_Buyout__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Partial Buyout</label>
    <type>Checkbox</type>
</CustomField>

peac_dev/force-app/main/default/objects/Buyout__c/fields/Quote_Sequence__c.field-meta.xml
<CustomField>
    <fullName>Quote_Sequence__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Quote Sequence</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

peac_dev/force-app/main/default/objects/Buyout_Asset__c/Buyout_Asset__c.object-meta.xml
<CustomObject>
    <description>Object to represent the many-to-many relationship between Buyouts and Contract Assets</description>
    <label>Buyout Asset</label>
    <nameField>
        <displayFormat>BA-{00000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Buyout Assets</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

peac_dev/force-app/main/default/objects/Buyout_Asset__c/fields/Buyout__c.field-meta.xml
<CustomField>
    <fullName>Buyout__c</fullName>
    <label>Buyout</label>
    <referenceTo>Buyout__c</referenceTo>
    <relationshipLabel>Buyout Assets</relationshipLabel>
    <relationshipName>Buyout_Assets</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

peac_dev/force-app/main/default/objects/Buyout_Asset__c/fields/Contract_Asset__c.field-meta.xml
<CustomField>
    <fullName>Contract_Asset__c</fullName>
    <label>Contract Asset</label>
    <referenceTo>Contract_Asset__c</referenceTo>
    <relationshipLabel>Buyout Assets</relationshipLabel>
    <relationshipName>Buyout_Assets</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

peac_dev/force-app/main/default/objects/Contract__c/Contract__c.object-meta.xml
<CustomObject>
    <description>Custom Object created so we can use Queue functionality</description>
    <label>Contract</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Contract Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Contracts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

peac_dev/force-app/main/default/objects/Contract_Asset__c/Contract_Asset__c.object-meta.xml
<CustomObject>
    <label>Contract Asset</label>
    <nameField>
        <displayFormat>CA-{0000}</displayFormat>
        <label>Contract Asset Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contract Assets</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

peac_dev/force-app/main/default/objects/Contract_Asset__c/fields/Buyout_Type__c.field-meta.xml
<CustomField>
    <fullName>Buyout_Type__c</fullName>
    <label>Buyout Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>DISPOSED</fullName>
            </value>
            <value>
                <fullName>RECEIVED</fullName>
            </value>
            <value>
                <fullName>Investigate</fullName>
            </value>
            <value>
                <fullName>Upgrade to Return</fullName>
            </value>
            <value>
                <fullName>Upgrade to Keep</fullName>
            </value>
            <value>
                <fullName>Customer Buyout to Return</fullName>
            </value>
            <value>
                <fullName>Customer Buyout to Keep</fullName>
            </value>
            <value>
                <fullName>Buyout to Return</fullName>
            </value>
            <value>
                <fullName>Buyout to Keep</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

peac_dev/force-app/main/default/objects/Contract_Asset__c/fields/Contract__c.field-meta.xml
<CustomField>
    <fullName>Contract__c</fullName>
    <label>Contract</label>
    <referenceTo>Contract__c</referenceTo>
    <relationshipLabel>Contract Assets</relationshipLabel>
    <relationshipName>Contract_Assets</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

peac_dev/force-app/main/default/classes/SL_ReturnAuthorizationHelperTest.cls
/**
 * Tests for SL_ReturnAuthorizationHelper
 */

@IsTest
public with sharing class SL_ReturnAuthorizationHelperTest {

    @isTest
    static void testUpdateContractAssets() {
        // Create necessary test data using SL_SCTestData methods
        SL_SCTestData.createAccountAndContracts(1, 1);
        SL_SCTestData.createInsurancesAndContractAssets(1, 2); // Creating 1 insurance with 2 contract assets

        Contract__c contract = [SELECT Id FROM Contract__c LIMIT 1];
        Test.startTest();
        SL_ReturnAuthorizationHelper.updateContractAssets(contract.Id, '2');
        Test.stopTest();
    }


    @isTest
    static void testCheckReturnAuthorizationContractAssets() {
        // Create necessary test data using SL_SCTestData methods
        SL_SCTestData.createAccountAndContracts(1, 1);
        SL_SCTestData.createInsurancesAndContractAssets(1, 2); // Creating 1 insurance with 2 contract assets

        Contract__c contract = [SELECT Id FROM Contract__c LIMIT 1];
        Test.startTest();
        SL_ReturnAuthorizationHelper.checkReturnAuthorizationContractAssets(contract.Id, 'TestBuyoutNoPartial');
        Test.stopTest();
    }


    @isTest
    static void testCheckReturnAuthorizationContractAssetsBuyouts() {
        // Create necessary test data using SL_SCTestData methods
        SL_SCTestData.createAccountAndContracts(1, 1);
        SL_SCTestData.createInsurancesAndContractAssets(1, 2); // Creating 1 insurance with 2 contract assets

		Date currentDate = System.today();        	
        // Create a Buyout__c record with Partial_Buyout__c set to true
        Buyout__c buyout = new Buyout__c(
            Contract__c = SL_SCTestData.testContracts[0].Id,
            Name = 'TestBuyout',
            Partial_Buyout__c = true,
            Quote_Sequence__c = 'TestBuyout',
            Buyout_Amount__c = 1000,
            Buyout_Type__c = '22',
            Date_Quoted__c = currentDate,
            Expiration_Date__c = currentDate.addDays(30)
            
        );
        insert buyout;

        // Create Buyout_Asset__c records linked to the Buyout__c
        List<Buyout_Asset__c> buyoutAssets = new List<Buyout_Asset__c>();
        for (Contract_Asset__c asset : SL_SCTestData.testCAssets) {
            buyoutAssets.add(new Buyout_Asset__c(
                Buyout__c = buyout.Id,
                Contract_Asset__c = asset.Id
            ));
        }
        insert buyoutAssets;
        Contract__c contract = [SELECT Id FROM Contract__c LIMIT 1];
        Buyout__c singleBuyout = [SELECT Id FROM Buyout__c LIMIT 1];
        Test.startTest();
        SL_ReturnAuthorizationHelper.checkReturnAuthorizationContractAssets(contract.Id, 'TestBuyout');
        SL_ReturnAuthorizationHelper.returnAuthorizationRequest(singleBuyout.Id);
        Test.stopTest();
    }
    
    
}