peac_dev/force-app/main/default/objects/Buyout__c/Buyout__c.object-meta.xml
<CustomObject>
    <description>Object to store active and legacy Buyouts returned by Infolease. Data in this object will be purged on a 6 month rolling basis</description>
    <label>Buyout</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Buyout Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Buyouts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

peac_dev/force-app/main/default/objects/Buyout__c/fields/Contract__c.field-meta.xml
<CustomField>
    <fullName>Contract__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contract</label>
    <referenceTo>Contract__c</referenceTo>
    <relationshipLabel>Buyouts</relationshipLabel>
    <relationshipName>Buyouts</relationshipName>
    <type>Lookup</type>
</CustomField>

peac_dev/force-app/main/default/objects/Buyout__c/fields/Partial_Buyout__c.field-meta.xml
<CustomField>
    <fullName>Partial_Buyout__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Partial Buyout</label>
    <type>Checkbox</type>
</CustomField>

peac_dev/force-app/main/default/objects/Buyout__c/fields/Quote_Sequence__c.field-meta.xml
<CustomField>
    <fullName>Quote_Sequence__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Quote Sequence</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

peac_dev/force-app/main/default/objects/Buyout_Asset__c/Buyout_Asset__c.object-meta.xml
<CustomObject>
    <description>Object to represent the many-to-many relationship between Buyouts and Contract Assets</description>
    <label>Buyout Asset</label>
    <nameField>
        <displayFormat>BA-{00000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Buyout Assets</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

peac_dev/force-app/main/default/objects/Buyout_Asset__c/fields/Buyout__c.field-meta.xml
<CustomField>
    <fullName>Buyout__c</fullName>
    <label>Buyout</label>
    <referenceTo>Buyout__c</referenceTo>
    <relationshipLabel>Buyout Assets</relationshipLabel>
    <relationshipName>Buyout_Assets</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

peac_dev/force-app/main/default/objects/Buyout_Asset__c/fields/Contract_Asset__c.field-meta.xml
<CustomField>
    <fullName>Contract_Asset__c</fullName>
    <label>Contract Asset</label>
    <referenceTo>Contract_Asset__c</referenceTo>
    <relationshipLabel>Buyout Assets</relationshipLabel>
    <relationshipName>Buyout_Assets</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

peac_dev/force-app/main/default/objects/Contract__c/Contract__c.object-meta.xml
<CustomObject>
    <description>Custom Object created so we can use Queue functionality</description>
    <label>Contract</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Contract Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Contracts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

peac_dev/force-app/main/default/objects/Contract__c/fields/IsXBS__c.field-meta.xml
<CustomField>
    <fullName>IsXBS__c</fullName>
    <formula>IF(
  OR(
    Lessor_Code__c = &quot;111&quot;,
    Lessor_Code__c = &quot;113&quot;,
    Lessor_Code__c = &quot;211&quot;,
    Lessor_Code__c = &quot;213&quot;
    ), 
  TRUE,
  FALSE
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Is XBS?</label>
    <type>Checkbox</type>
</CustomField>

peac_dev/force-app/main/default/objects/Contract__c/fields/State__c.field-meta.xml
<CustomField>
    <fullName>State__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>State</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

peac_dev/force-app/main/default/objects/Contract_Asset__c/Contract_Asset__c.object-meta.xml
<CustomObject>
    <label>Contract Asset</label>
    <nameField>
        <displayFormat>CA-{0000}</displayFormat>
        <label>Contract Asset Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contract Assets</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

peac_dev/force-app/main/default/objects/Contract_Asset__c/fields/Asset_Disposed_Date__c.field-meta.xml
<CustomField>
    <fullName>Asset_Disposed_Date__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Asset Disposed Date</label>
    <type>Date</type>
</CustomField>

peac_dev/force-app/main/default/objects/Contract_Asset__c/fields/Asset_State__c.field-meta.xml
<CustomField>
    <fullName>Asset_State__c</fullName>
    <label>Asset State</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>State_Code</valueSetName>
    </valueSet>
</CustomField>

peac_dev/force-app/main/default/objects/Contract_Asset__c/fields/Contract__c.field-meta.xml
<CustomField>
    <fullName>Contract__c</fullName>
    <label>Contract</label>
    <referenceTo>Contract__c</referenceTo>
    <relationshipLabel>Contract Assets</relationshipLabel>
    <relationshipName>Contract_Assets</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

peac_dev/force-app/main/default/objects/Contract_Asset__c/fields/Equipment_Subtype__c.field-meta.xml
<CustomField>
    <fullName>Equipment_Subtype__c</fullName>
    <label>Equipment Subtype</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Equipment_Sub_Category</valueSetName>
    </valueSet>
</CustomField>

peac_dev/force-app/main/default/objects/Contract_Asset__c/fields/Equipment_Type__c.field-meta.xml
<CustomField>
    <fullName>Equipment_Type__c</fullName>
    <label>Equipment Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Asset_Equipment_Code</valueSetName>
    </valueSet>
</CustomField>

peac_dev/force-app/main/default/objects/Contract_Asset__c/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Location</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Location.Is_Active__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Location</referenceTo>
    <relationshipLabel>Contract Assets</relationshipLabel>
    <relationshipName>Contract_Asset_Location</relationshipName>
    <type>Lookup</type>
</CustomField>

peac_dev/force-app/main/default/objects/Contract_Asset__c/fields/Return_Auth_Create_Date__c.field-meta.xml
<CustomField>
    <fullName>Return_Auth_Create_Date__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Return Auth Create Date</label>
    <type>Date</type>
</CustomField>

peac_dev/force-app/main/default/objects/Contract_Asset__c/fields/Return_Authorization__c.field-meta.xml
<CustomField>
    <fullName>Return_Authorization__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Return Authorization</label>
    <type>Checkbox</type>
</CustomField>

peac_dev/force-app/main/default/objects/Contract_Asset__c/fields/Service_Provider__c.field-meta.xml
<CustomField>
    <fullName>Service_Provider__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Service Provider</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordType.Name</field>
            <operation>equals</operation>
            <value>Service Provider</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Contract Assets (Service Provider)</relationshipLabel>
    <relationshipName>Contract_Assets_Providers</relationshipName>
    <type>Lookup</type>
</CustomField>

peac_dev/force-app/main/default/objects/Contract_Attachment__c/Contract_Attachment__c.object-meta.xml
<CustomObject>
    <description>this will use OnBase</description>
    <label>Contract Attachment</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>File Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Contract Attachments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

peac_dev/force-app/main/default/objects/Contract_Attachment__c/fields/Contract__c.field-meta.xml
<CustomField>
    <fullName>Contract__c</fullName>
    <label>Contract</label>
    <referenceTo>Contract__c</referenceTo>
    <relationshipLabel>Contract Attachments</relationshipLabel>
    <relationshipName>Contract_Attachments</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

peac_dev/force-app/main/default/objects/Contract_Attachment__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Document Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Type_Group__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>CL - Credit Bureau Reports</fullName>
            </value>
            <value>
                <fullName>CL - Customer Correspondence</fullName>
            </value>
            <value>
                <fullName>CL - Demand Letters</fullName>
            </value>
            <value>
                <fullName>CL - Investigations</fullName>
            </value>
            <value>
                <fullName>CL - Misc</fullName>
            </value>
            <value>
                <fullName>CS - Address Change</fullName>
            </value>
            <value>
                <fullName>CS - Assumption / Restructure Documentation</fullName>
            </value>
            <value>
                <fullName>CS - Change Request</fullName>
            </value>
            <value>
                <fullName>CS - EOT Form</fullName>
            </value>
            <value>
                <fullName>CS - Letters of Intent</fullName>
            </value>
            <value>
                <fullName>CS - Misc</fullName>
            </value>
            <value>
                <fullName>CS - Tax Exempt Certificates</fullName>
            </value>
            <value>
                <fullName>FS - ACH_Auto Debit Forms and Copy of Check</fullName>
            </value>
            <value>
                <fullName>FS - Additional Stipulations</fullName>
            </value>
            <value>
                <fullName>FS - Bank Account Change Request</fullName>
            </value>
            <value>
                <fullName>FS - Bank Statements</fullName>
            </value>
            <value>
                <fullName>FS - Bank Statements - Apr</fullName>
            </value>
            <value>
                <fullName>FS - Bank Statements - Aug</fullName>
            </value>
            <value>
                <fullName>FS - Bank Statements - Dec</fullName>
            </value>
            <value>
                <fullName>FS - Bank Statements - Feb</fullName>
            </value>
            <value>
                <fullName>FS - Bank Statements - Jan</fullName>
            </value>
            <value>
                <fullName>FS - Bank Statements - Jul</fullName>
            </value>
            <value>
                <fullName>FS - Bank Statements - Jun</fullName>
            </value>
            <value>
                <fullName>FS - Bank Statements - Mar</fullName>
            </value>
            <value>
                <fullName>FS - Bank Statements - May</fullName>
            </value>
            <value>
                <fullName>FS - Bank Statements - Nov</fullName>
            </value>
            <value>
                <fullName>FS - Bank Statements - Oct</fullName>
            </value>
            <value>
                <fullName>FS - Bank Statements - Sept</fullName>
            </value>
            <value>
                <fullName>FS - Bank Statements MTD</fullName>
            </value>
            <value>
                <fullName>FS - Blank Loan Documents</fullName>
            </value>
            <value>
                <fullName>AM - Return Authorization</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

peac_dev/force-app/main/default/objects/Remarketer_Matrix_Obj__c/Remarketer_Matrix_Obj__c.object-meta.xml
<CustomObject>
    <label>Remarketer Matrix</label>
    <nameField>
        <displayFormat>RM-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Remarketer Matrix</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

peac_dev/force-app/main/default/objects/Remarketer_Matrix_Obj__c/fields/Equipment_Subtype__c.field-meta.xml
<CustomField>
    <fullName>Equipment_Subtype__c</fullName>
    <label>Equipment Subtype</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Equipment_Sub_Category</valueSetName>
    </valueSet>
</CustomField>

peac_dev/force-app/main/default/objects/Remarketer_Matrix_Obj__c/fields/Equipment_Type__c.field-meta.xml
<CustomField>
    <fullName>Equipment_Type__c</fullName>
    <label>Equipment Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Equipment_Type</valueSetName>
    </valueSet>
</CustomField>

peac_dev/force-app/main/default/objects/Remarketer_Matrix_Obj__c/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Location</label>
    <referenceTo>Location</referenceTo>
    <relationshipLabel>Remarketer Matrix</relationshipLabel>
    <relationshipName>Remarketer_Matrix</relationshipName>
    <type>Lookup</type>
</CustomField>

peac_dev/force-app/main/default/objects/Remarketer_Matrix_Obj__c/fields/Return_Warehouse_Code__c.field-meta.xml
<CustomField>
    <fullName>Return_Warehouse_Code__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Return Warehouse Code</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

peac_dev/force-app/main/default/objects/Remarketer_Matrix_Obj__c/fields/Service_Provider__c.field-meta.xml
<CustomField>
    <fullName>Service_Provider__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Service Provider</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Remarketer Matrix</relationshipLabel>
    <relationshipName>Remarketer_Matrix</relationshipName>
    <type>Lookup</type>
</CustomField>

peac_dev/force-app/main/default/classes/SL_ReturnAuthorizationHelper.cls
/**
*
* Summary:       This helper contains methods used in the LWC sL_BiewBuyout
* Author:        -
* Created:       -
* Test Class:    SL_ReturnAuthorizationHelperTest
* History
* <Date>        <Authors Name>          <Jira#>      <Brief Description of Change>
* 09/27/2024     Paul Trujillo          SL-2242       Adding method to create returnAuthorization pdf and attach it to the buyout and contract
**/
public without sharing class SL_ReturnAuthorizationHelper {

    @AuraEnabled
    public static String updateContractAssets(String recordId, String quoteSeq)
    {
        SL_PartialBuyout.checkExistingFullBAssets(recordId, quoteSeq);
        String result = '';
        Contract__c contract = [SELECT ID, IsXBS__c  FROM Contract__c WHERE Id = :recordId LIMIT 1];
        List<Contract_Asset__c> contractAssets = [SELECT Id, Equipment_Type__c, Equipment_Subtype__c, Asset_State__c, Location__c, Service_Provider__c, Asset_Disposed_Date__c FROM Contract_Asset__c WHERE Contract__c = :recordId AND Asset_Disposed_Date__c=null];
        List<Remarketer_Matrix_Obj__c> remarketers = [SELECT Id, Equipment_Type__c, Equipment_Subtype__c, State__c, Return_Warehouse_Code__c, Service_Provider__c, Location__c FROM Remarketer_Matrix_Obj__c];

        List<String> locationCodes = new List<String>();
        Boolean isUpdateNeeded = false;
        //Is needed to create this data here as Custom Metadata Type cannot be created from test class.
        if(Test.isRunningTest()){
            locationCodes.add('TestLocation');
            Schema.Location testLocation = new Schema.Location(Name='TestLocation');
            insert testLocation;
        }        
        //getLocationCodes
        try{
            for(Contract_Asset__c ca : contractAssets)
            {         
    
                for(Remarketer_Matrix_Obj__c rmkt : remarketers)
                {
                    if(ca.Equipment_Subtype__c == rmkt.Equipment_Subtype__c && ca.Asset_State__c == rmkt.State__c && ca.Equipment_Type__c == rmkt.Equipment_Type__c)
                    {
                                isUpdateNeeded = true;//Indicates if there are matching values in the remarketer matrix
                        if(ca.Location__c == null)ca.Location__c = rmkt.Location__c;
                        if(ca.Service_Provider__c != rmkt.Service_Provider__c)ca.Service_Provider__c = rmkt.Service_Provider__c;
                                ca.Return_Authorization__c = true;
                                if(ca.Asset_Disposed_Date__c == null)ca.Return_Auth_Create_Date__c = Date.today();
                            } 
                    
                }
            }
    
        if(isUpdateNeeded)
        {
            update contractAssets;
            result = 'OK';
        }
        else {
            if(contractAssets.size()>0 ){
                result = 'Verify the following fields: '
                + 'Equipment type = Office Equipment(General).  '
                + 'Equipment Subtype = Copiers.  '
                + 'Asset state is not Blank.';
            }
            else{
                result = 'OK';
            }

        }
    }catch(Exception e){
            System.debug('ERROR ' + e.getMessage());
        }
        
        return result;
    }


    @AuraEnabled
    public static void checkReturnAuthorizationContractAssets(String contractId, String buyoutSeq)
    {
        System.debug('In checkReturnAuthorizationContractAssets - contractId: ' + contractId);
        System.debug('In checkReturnAuthorizationContractAssets - buyoutSeq: ' + buyoutSeq);
        Map<Id, Contract_Asset__c> contractAssetsToUpdate = new Map<Id, Contract_Asset__c>();
        Contract__c contract = [SELECT Id, Name FROM Contract__c WHERE Id = :contractId];
        List<Buyout__c> buyouts = [
            SELECT Id, Name, Partial_Buyout__c, Contract__r.Name
            FROM Buyout__c
            WHERE Contract__c = :contractId AND Quote_Sequence__c = :buyoutSeq
        ];


        System.debug('In checkReturnAuthorizationContractAssets - buyouts: ' + buyouts);
        addReturnAuthorizationPDFToBuyout(contractId, contract.Name, buyoutSeq);
        

        if (!buyouts.isEmpty() && buyouts[0].Partial_Buyout__c) {

            List<Buyout_Asset__c> buyoutAssets = [
                SELECT Contract_Asset__c, Contract_Asset__r.Return_Authorization__c, Contract_Asset__r.Return_Auth_Create_Date__c, Contract_Asset__r.Asset_Disposed_Date__c
                FROM Buyout_Asset__c
                WHERE Buyout__c = :buyouts[0].Id
            ];

            for (Buyout_Asset__c buyoutAsset : buyoutAssets) {
                if(!contractAssetsToUpdate.containsKey(buyoutAsset.Contract_Asset__c)) {

                    Contract_Asset__c contractAsset = new Contract_Asset__c(Id = buyoutAsset.Contract_Asset__c);
                    contractAsset.Return_Authorization__c = true;
                    if(buyoutAsset.Contract_Asset__r.Asset_Disposed_Date__c == null){
                    contractAsset.Return_Auth_Create_Date__c = Date.today();
                    contractAsset.Status2__c = 'Pending Return';
                    }

                    contractAssetsToUpdate.put(buyoutAsset.Contract_Asset__c, contractAsset);
                }

            }
        } else {
            Map<ID, Contract_Asset__c> m = new Map<ID, Contract_Asset__c>([SELECT Id, Return_Authorization__c, Return_Auth_Create_Date__c, Status2__c, Asset_Disposed_Date__c
            FROM Contract_Asset__c
            WHERE Contract__c = :contractId]);       
            contractAssetsToUpdate = m;            
            for (Id contractAssetId : contractAssetsToUpdate.keySet()) {
                contractAssetsToUpdate.get(contractAssetId).Return_Authorization__c = true;
                if(contractAssetsToUpdate.get(contractAssetId).Asset_Disposed_Date__c == null){
                    contractAssetsToUpdate.get(contractAssetId).Return_Auth_Create_Date__c = Date.today();
                    contractAssetsToUpdate.get(contractAssetId).Status2__c = 'Pending Return';
                }

            }
        }
        System.debug('contractAssetsToUpdate ' + contractAssetsToUpdate);
        if(!contractAssetsToUpdate.isEmpty()) update contractAssetsToUpdate.values();
    }

    /**
    *
    * Summary:       Create the Return Authorization PDF and related it to the buyout and the contract.
    * Inputs:        String contractId, String contractName, String buyoutSeq, Id buyoutID
    * Returns:       void
    * Author:        Paul Trujillo 
    * Created:       10/17/2024
    * History
    * <Date>        <Authors Name>          <Jira#>      <Brief Description of Change>
    * 09/27/2024     Paul Trujillo          SL-2242          Initial version.
    */
    public static void addReturnAuthorizationPDFToBuyout(Id contractId, String contractName, String buyoutSeq)
    {
        System.debug('addReturnAuthorizationPDFToBuyout contractId::'+contractId+' contractName::'+contractName+' buyoutSeq::'+buyoutSeq);
        if (contractId != null) {
            PageReference reportPage = (PageReference) Page.SL_ReturnAuthorization;
            reportPage.getParameters().put('contractId', contractId);
            reportPage.getParameters().put('buyoutSeq', buyoutSeq);
            Blob reportPdf;
            try {
                if(Test.isRunningTest()){
                    reportPdf = Blob.valueOf('Test');
                } else {
                    reportPdf = reportPage.getContentAsPDF();
                }
                //Check if document already exist
                String fileTitle = 'Return_Authorization_'+contractName+'_'+buyoutSeq+'.pdf';
                
                Contract_Attachment__c relatedContractAttachment = new Contract_Attachment__c();
                relatedContractAttachment.Contract__c = contractId;
                relatedContractAttachment.Type_Group__c = 'Asset Management';
                relatedContractAttachment.Type__c = 'AM - Return Authorization';
                relatedContractAttachment.Name = fileTitle;
                insert relatedContractAttachment;
                

                String result = SL_UploadAttachment.saveAttachment(relatedContractAttachment.Id, fileTitle, EncodingUtil.urlEncode(EncodingUtil.base64Encode(reportPdf), 'UTF-8'));
                System.debug('result::'+result);
                SL_OnBaseCallout.sendRapportAttachmentToOnBase(contractId, true);
            } catch(Exception ex) {
                System.debug('Exception::message::'+ex.getMessage());
                System.debug('Exception::stackTrace::'+ex.getStackTraceString());
            }
        }
    }


    @AuraEnabled
    public static string returnAuthorizationRequest(String buyoutId){
        try {
            User currentUser = [SELECT Id, ContactId FROM User WHERE Id=:UserInfo.getUserId()];
            Group queue = new Group();
            Buyout__c buyout = [SELECT Id, Name, Contract__c, Contract__r.Customer_name__c, Buyout_Amount__c, Buyout_Type__c, Contract__r.Name, Contract__r.IsXBS__c, Date_Quoted__c, Expiration_Date__c FROM Buyout__c WHERE Id =:buyoutId];
            System.debug('buyout type '+ buyout.Buyout_Type__c);

            List<PEAC_BuyoutPrettyNames__mdt> buyoutPrettyName = [SELECT DeveloperName, Buyout_Type__c, Pretty_Name__c, Type__c FROM PEAC_BuyoutPrettyNames__mdt WHERE Type__c = :buyout.Buyout_Type__c LIMIT 1];

            if(!buyout.Contract__r.IsXBS__c)
            {
                queue = [SELECT Id, Name FROM Group WHERE Name = 'Vendor Servicing' AND Type = 'Queue'];
            }
            else
            {
                queue = [SELECT Id, Name FROM Group WHERE Name = 'XBS Vendor Support' AND Type = 'Queue'];
            }    
            String buyoutType =  buyoutPrettyName.size() > 0? buyoutPrettyName[0].Buyout_Type__c: buyout.Name;       
            Case RArequest = new Case();
            RArequest.ContactId = currentUser.ContactId;
            RArequest.Buyout__c = buyoutId;
            RArequest.Contract_custom__c = buyout.Contract__c;
            RArequest.Subject = 'Dealer Return Instruction Request for ' + buyout.Contract__r.Customer_name__c;
            RArequest.Description = 'Contract Number: '+ buyout.Contract__r.Name +' \n'
            +'Buyout Type: '+  buyoutType  +' \n'
            +'Quote Type: '+ buyout.Buyout_Type__c +' \n'
            +'Quote total: $'+String.valueOf(buyout.Buyout_Amount__c)+' \n'            
            +'Buyout Date: '+  String.valueOf(buyout.Date_Quoted__c.month())+ '/'+ +  String.valueOf(buyout.Date_Quoted__c.day())+ '/'+ +  String.valueOf(buyout.Date_Quoted__c.year())+ '/'+ ' \n'
            +'Expired Date: '+ String.valueOf(buyout.Expiration_Date__c.month())+ '/'+ +  String.valueOf(buyout.Expiration_Date__c.day())+ '/'+ +  String.valueOf(buyout.Expiration_Date__c.year())+ '/'+ ' \n'
            + 'Please see request for return instructions. Please review account to validate if return instructions can be provided to dealership. All term payments must be made, LOI must be submitted on time or Customer buyout to return payment has been received.';
            if(!Test.isRunningTest())RArequest.OwnerId = queue.Id;
            insert RArequest;
            return RArequest.Id;

        } catch (Exception e) {
            System.debug('ERROR '+ e.getMessage());
            throw new AuraHandledException(e.getMessage());
        }
    }

}