peac_dev/force-app/main/default/objects/Buyout__c/Buyout__c.object-meta.xml
<CustomObject>
    <description>Object to store active and legacy Buyouts returned by Infolease. Data in this object will be purged on a 6 month rolling basis</description>
    <label>Buyout</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Buyout Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Buyouts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

peac_dev/force-app/main/default/objects/Buyout__c/fields/Buyout_Amount__c.field-meta.xml
<CustomField>
    <fullName>Buyout_Amount__c</fullName>
    <defaultValue>0.00</defaultValue>
    <label>Buyout Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

peac_dev/force-app/main/default/objects/Buyout__c/fields/Buyout_Description__c.field-meta.xml
<CustomField>
    <fullName>Buyout_Description__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Buyout Description</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

peac_dev/force-app/main/default/objects/Buyout__c/fields/Buyout_Type__c.field-meta.xml
<CustomField>
    <fullName>Buyout_Type__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Buyout Type</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

peac_dev/force-app/main/default/objects/Buyout__c/fields/Contract__c.field-meta.xml
<CustomField>
    <fullName>Contract__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contract</label>
    <referenceTo>Contract__c</referenceTo>
    <relationshipLabel>Buyouts</relationshipLabel>
    <relationshipName>Buyouts</relationshipName>
    <type>Lookup</type>
</CustomField>

peac_dev/force-app/main/default/objects/Buyout__c/fields/Date_Quoted__c.field-meta.xml
<CustomField>
    <fullName>Date_Quoted__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Date Quoted</label>
    <type>Date</type>
</CustomField>

peac_dev/force-app/main/default/objects/Buyout__c/fields/Expiration_Date__c.field-meta.xml
<CustomField>
    <fullName>Expiration_Date__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Expiration Date</label>
    <type>Date</type>
</CustomField>

peac_dev/force-app/main/default/objects/Buyout__c/fields/Most_Recent__c.field-meta.xml
<CustomField>
    <fullName>Most_Recent__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Most Recent</label>
    <type>Checkbox</type>
</CustomField>

peac_dev/force-app/main/default/objects/Buyout__c/fields/Partial_Buyout__c.field-meta.xml
<CustomField>
    <fullName>Partial_Buyout__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Partial Buyout</label>
    <type>Checkbox</type>
</CustomField>

peac_dev/force-app/main/default/objects/Contract__c/Contract__c.object-meta.xml
<CustomObject>
    <description>Custom Object created so we can use Queue functionality</description>
    <label>Contract</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Contract Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Contracts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

peac_dev/force-app/main/default/classes/PEAC_BuyoutComparisonControllerTest.cls
@isTest
public with sharing class PEAC_BuyoutComparisonControllerTest {
    @isTest
    static void printPdf() {
        SL_SCTestData.createAccountAndContracts(1, 1);
        Test.startTest();
        Contract__c contract = [SELECT Id FROM Contract__c];
        Buyout__c buyout1 = new Buyout__c(
            Contract__c = contract.Id,
            Name = 'Buyout 1',
            Buyout_Type__c = 'Type 1',
            Date_Quoted__c = Date.today(),
            Expiration_Date__c = Date.today().addDays(30),
            Buyout_Amount__c = 1000,
            Buyout_Description__c = 'Test Buyout',
            Most_Recent__c = true,
            Partial_Buyout__c = false
        );
        
        Buyout__c buyout2 = new Buyout__c(
            Contract__c = contract.Id,
            Name = 'Buyout 2',
            Buyout_Type__c = 'Type 2',
            Date_Quoted__c = Date.today().addDays(-10),
            Expiration_Date__c = Date.today().addDays(20),
            Buyout_Amount__c = 2000,
            Buyout_Description__c = 'Test Buyout 2',
            Most_Recent__c = false,
            Partial_Buyout__c = false
        );

        insert new List<Buyout__c>{buyout1, buyout2};
        ApexPages.currentPage().getParameters().put('recId', contract.Id);
        ApexPages.currentPage().getParameters().put('action', 'letter');
        
        PEAC_BuyoutComparisonController ctrl = new PEAC_BuyoutComparisonController();
        ctrl.getLogoResourceName();
        Test.stopTest();
        
    }
}