peac_dev/force-app/main/default/objects/Buyout__c/Buyout__c.object-meta.xml
<CustomObject>
    <description>Object to store active and legacy Buyouts returned by Infolease. Data in this object will be purged on a 6 month rolling basis</description>
    <label>Buyout</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Buyout Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Buyouts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

peac_dev/force-app/main/default/objects/Buyout__c/fields/Buyout_Amount__c.field-meta.xml
<CustomField>
    <fullName>Buyout_Amount__c</fullName>
    <defaultValue>0.00</defaultValue>
    <label>Buyout Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

peac_dev/force-app/main/default/objects/Buyout__c/fields/Buyout_Description__c.field-meta.xml
<CustomField>
    <fullName>Buyout_Description__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Buyout Description</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

peac_dev/force-app/main/default/objects/Buyout__c/fields/Contract__c.field-meta.xml
<CustomField>
    <fullName>Contract__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contract</label>
    <referenceTo>Contract__c</referenceTo>
    <relationshipLabel>Buyouts</relationshipLabel>
    <relationshipName>Buyouts</relationshipName>
    <type>Lookup</type>
</CustomField>

peac_dev/force-app/main/default/objects/Buyout__c/fields/Date_Quoted__c.field-meta.xml
<CustomField>
    <fullName>Date_Quoted__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Date Quoted</label>
    <type>Date</type>
</CustomField>

peac_dev/force-app/main/default/objects/Buyout__c/fields/Early_Termination_Fee__c.field-meta.xml
<CustomField>
    <fullName>Early_Termination_Fee__c</fullName>
    <defaultValue>0.00</defaultValue>
    <label>Early Termination Fee</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

peac_dev/force-app/main/default/objects/Buyout__c/fields/Ending_Deposit__c.field-meta.xml
<CustomField>
    <fullName>Ending_Deposit__c</fullName>
    <defaultValue>0.00</defaultValue>
    <label>Ending Deposit</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

peac_dev/force-app/main/default/objects/Buyout__c/fields/Expiration_Date__c.field-meta.xml
<CustomField>
    <fullName>Expiration_Date__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Expiration Date</label>
    <type>Date</type>
</CustomField>

peac_dev/force-app/main/default/objects/Buyout__c/fields/Insurance__c.field-meta.xml
<CustomField>
    <fullName>Insurance__c</fullName>
    <defaultValue>0.00</defaultValue>
    <label>Insurance</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

peac_dev/force-app/main/default/objects/Buyout__c/fields/LateCharges__c.field-meta.xml
<CustomField>
    <fullName>LateCharges__c</fullName>
    <defaultValue>0.00</defaultValue>
    <label>LateCharges</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

peac_dev/force-app/main/default/objects/Buyout__c/fields/Most_Recent__c.field-meta.xml
<CustomField>
    <fullName>Most_Recent__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Most Recent</label>
    <type>Checkbox</type>
</CustomField>

peac_dev/force-app/main/default/objects/Buyout__c/fields/Other_Lease_Charges__c.field-meta.xml
<CustomField>
    <fullName>Other_Lease_Charges__c</fullName>
    <defaultValue>0.00</defaultValue>
    <label>Other Lease Charges</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

peac_dev/force-app/main/default/objects/Buyout__c/fields/Partial_Buyout__c.field-meta.xml
<CustomField>
    <fullName>Partial_Buyout__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Partial Buyout</label>
    <type>Checkbox</type>
</CustomField>

peac_dev/force-app/main/default/objects/Buyout__c/fields/Property_tax__c.field-meta.xml
<CustomField>
    <fullName>Property_tax__c</fullName>
    <defaultValue>0.00</defaultValue>
    <label>Property tax</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

peac_dev/force-app/main/default/objects/Buyout__c/fields/Quote_Sequence__c.field-meta.xml
<CustomField>
    <fullName>Quote_Sequence__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Quote Sequence</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

peac_dev/force-app/main/default/objects/Buyout__c/fields/Receivable_Balance__c.field-meta.xml
<CustomField>
    <fullName>Receivable_Balance__c</fullName>
    <defaultValue>0.00</defaultValue>
    <label>Receivable Balance</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

peac_dev/force-app/main/default/objects/Buyout__c/fields/Residual__c.field-meta.xml
<CustomField>
    <fullName>Residual__c</fullName>
    <defaultValue>0.00</defaultValue>
    <label>Residual</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

peac_dev/force-app/main/default/objects/Buyout__c/fields/SalesTax__c.field-meta.xml
<CustomField>
    <fullName>SalesTax__c</fullName>
    <defaultValue>0.00</defaultValue>
    <label>SalesTax</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

peac_dev/force-app/main/default/objects/Buyout__c/fields/Security_Deposit__c.field-meta.xml
<CustomField>
    <fullName>Security_Deposit__c</fullName>
    <defaultValue>0.00</defaultValue>
    <label>Security Deposit</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

peac_dev/force-app/main/default/objects/Buyout__c/fields/Service_pass_through__c.field-meta.xml
<CustomField>
    <fullName>Service_pass_through__c</fullName>
    <defaultValue>0.00</defaultValue>
    <label>Pass Through</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

peac_dev/force-app/main/default/objects/Buyout__c/fields/Total_Buyout__c.field-meta.xml
<CustomField>
    <fullName>Total_Buyout__c</fullName>
    <defaultValue>0.00</defaultValue>
    <label>Total Buyout</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

peac_dev/force-app/main/default/objects/Buyout_Asset__c/Buyout_Asset__c.object-meta.xml
<CustomObject>
    <description>Object to represent the many-to-many relationship between Buyouts and Contract Assets</description>
    <label>Buyout Asset</label>
    <nameField>
        <displayFormat>BA-{00000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Buyout Assets</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

peac_dev/force-app/main/default/objects/Buyout_Asset__c/fields/Buyout__c.field-meta.xml
<CustomField>
    <fullName>Buyout__c</fullName>
    <label>Buyout</label>
    <referenceTo>Buyout__c</referenceTo>
    <relationshipLabel>Buyout Assets</relationshipLabel>
    <relationshipName>Buyout_Assets</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

peac_dev/force-app/main/default/objects/Buyout_Asset__c/fields/Contract_Asset__c.field-meta.xml
<CustomField>
    <fullName>Contract_Asset__c</fullName>
    <label>Contract Asset</label>
    <referenceTo>Contract_Asset__c</referenceTo>
    <relationshipLabel>Buyout Assets</relationshipLabel>
    <relationshipName>Buyout_Assets</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

peac_dev/force-app/main/default/objects/Contract__c/Contract__c.object-meta.xml
<CustomObject>
    <description>Custom Object created so we can use Queue functionality</description>
    <label>Contract</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Contract Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Contracts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

peac_dev/force-app/main/default/objects/Contract__c/fields/Insurance__c.field-meta.xml
<CustomField>
    <fullName>Insurance__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Insurance</label>
    <referenceTo>Insurance__c</referenceTo>
    <relationshipName>Custom_Contracts</relationshipName>
    <type>Lookup</type>
</CustomField>

peac_dev/force-app/main/default/objects/Contract__c/fields/Security_Deposit__c.field-meta.xml
<CustomField>
    <fullName>Security_Deposit__c</fullName>
    <label>Security Deposit</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

peac_dev/force-app/main/default/objects/Contract_Asset__c/Contract_Asset__c.object-meta.xml
<CustomObject>
    <label>Contract Asset</label>
    <nameField>
        <displayFormat>CA-{0000}</displayFormat>
        <label>Contract Asset Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contract Assets</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

peac_dev/force-app/main/default/objects/Contract_Asset__c/fields/Contract__c.field-meta.xml
<CustomField>
    <fullName>Contract__c</fullName>
    <label>Contract</label>
    <referenceTo>Contract__c</referenceTo>
    <relationshipLabel>Contract Assets</relationshipLabel>
    <relationshipName>Contract_Assets</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

peac_dev/force-app/main/default/objects/Contract_Asset__c/fields/Insurance__c.field-meta.xml
<CustomField>
    <fullName>Insurance__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Insurance</label>
    <referenceTo>Insurance__c</referenceTo>
    <relationshipLabel>Contract Assets</relationshipLabel>
    <relationshipName>Contract_Assets</relationshipName>
    <type>Lookup</type>
</CustomField>

peac_dev/force-app/main/default/objects/Contract_Asset__c/fields/Serial_Number__c.field-meta.xml
<CustomField>
    <fullName>Serial_Number__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <externalId>true</externalId>
    <label>Serial Number</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

peac_dev/force-app/main/default/objects/Insurance__c/Insurance__c.object-meta.xml
<CustomObject>
    <label>Insurance</label>
    <nameField>
        <displayFormat>INS-{0000}</displayFormat>
        <label>Insurance Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Insurance</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

peac_dev/force-app/main/default/objects/Insurance__c/fields/Expiration_Date__c.field-meta.xml
<CustomField>
    <fullName>Expiration_Date__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Expiration Date</label>
    <type>Date</type>
</CustomField>

peac_dev/force-app/main/default/classes/PEAC_PartnerQuotePDFControllerTest.cls
@isTest
public class PEAC_PartnerQuotePDFControllerTest {
    @testSetup
    static void setup() {
        SL_SCTestData.createAccountAndContracts(1, 1);
        SL_SCTestData.createInsurancesAndContractAssets(1, 1);
        Contract__c contract = [SELECT Id FROM Contract__c];
        // Create a test Buyout__c record linked to the Contract__c
        Buyout__c buyout = new Buyout__c(
            Contract__c = contract.Id,
            Buyout_Description__c = 'End of Term Buyout',
            Quote_Sequence__c = '1',
            Buyout_Amount__c = 5000,
            Most_Recent__c = true,
            Receivable_Balance__c = 3000,
            Residual__c = 1500,
            SalesTax__c = 100,
            LateCharges__c = 50,
            Early_Termination_Fee__c = 200,
            Security_Deposit__c = 500,
            Ending_Deposit__c = 200,
            Service_pass_through__c = 50,
            Property_tax__c = 75,
            Insurance__c = 60,
            Other_Lease_Charges__c = 40,
            Total_Buyout__c = 7500,
            Partial_Buyout__c = true,
            Date_Quoted__c = Date.today(),
            Expiration_Date__c = Date.today().addDays(30)
        );
        insert buyout;
         Buyout__c buyout1 = new Buyout__c(
            Contract__c = contract.Id,
            Buyout_Description__c = 'End of Term Buyout',
            Quote_Sequence__c = '1',
            Buyout_Amount__c = 5000,
            Most_Recent__c = true,
            Receivable_Balance__c = 3000,
            Residual__c = 1500,
            SalesTax__c = 100,
            LateCharges__c = 50,
            Early_Termination_Fee__c = 200,
            Security_Deposit__c = 500,
            Ending_Deposit__c = 200,
            Service_pass_through__c = 50,
            Property_tax__c = 75,
            Insurance__c = 60,
            Other_Lease_Charges__c = 40,
            Total_Buyout__c = 7500,
            Partial_Buyout__c = false,
            Date_Quoted__c = Date.today(),
            Expiration_Date__c = Date.today().addDays(30)
        );
        insert buyout1;
        List<Contract_Asset__c> contractAssets = new List<Contract_Asset__c>();
        
        for (Contract_Asset__c asset : [select Id,Serial_Number__c from Contract_Asset__c where Contract__c = :contract.Id]) {
            asset.Serial_Number__c = '12345';
            contractAssets.add(asset);
        }
        update contractAssets;
    }
    
    @isTest
    static void testController() {
        // Retrieve the test Buyout__c record for the buyoutId
        Buyout__c testBuyout = [SELECT Id,Contract__c FROM Buyout__c where Partial_Buyout__c = true LIMIT 1];
        
        // Set up the page and add the parameter
        Test.startTest();
        List<Buyout_Asset__c> buyoutAssets = new List<Buyout_Asset__c>();
        for (Contract_Asset__c asset : [select Id from Contract_Asset__c where Contract__c = :testBuyout.Contract__c]) {
            buyoutAssets.add(new Buyout_Asset__c(
                Buyout__c = testBuyout.Id,
                Contract_Asset__c = asset.Id
            ));
        }
        
        insert buyoutAssets;
        PageReference pageRef = Page.PEAC_PartnerQuotePDF; // Replace with actual VF page name if different
        pageRef.getParameters().put('buyoutId', testBuyout.Id);
        Test.setCurrentPage(pageRef);
        
        // Instantiate the controller
        PEAC_PartnerQuotePDFController controller = new PEAC_PartnerQuotePDFController();
        
        
        Test.stopTest();
    }
     @isTest
    static void testControllerPartial() {
        // Retrieve the test Buyout__c record for the buyoutId
        Buyout__c testBuyout = [SELECT Id FROM Buyout__c where Partial_Buyout__c = false LIMIT 1];
        
        // Set up the page and add the parameter
        Test.startTest();
        PageReference pageRef = Page.PEAC_PartnerQuotePDF; // Replace with actual VF page name if different
        pageRef.getParameters().put('buyoutId', testBuyout.Id);
        Test.setCurrentPage(pageRef);
        
        // Instantiate the controller
        PEAC_PartnerQuotePDFController controller = new PEAC_PartnerQuotePDFController();
        
        
        Test.stopTest();
    }
}