peac_dev/force-app/main/default/objects/Buyout__c/Buyout__c.object-meta.xml
<CustomObject>
    <description>Object to store active and legacy Buyouts returned by Infolease. Data in this object will be purged on a 6 month rolling basis</description>
    <label>Buyout</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Buyout Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Buyouts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

peac_dev/force-app/main/default/objects/Buyout__c/fields/Contract__c.field-meta.xml
<CustomField>
    <fullName>Contract__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contract</label>
    <referenceTo>Contract__c</referenceTo>
    <relationshipLabel>Buyouts</relationshipLabel>
    <relationshipName>Buyouts</relationshipName>
    <type>Lookup</type>
</CustomField>

peac_dev/force-app/main/default/objects/Buyout__c/fields/Date_Quoted__c.field-meta.xml
<CustomField>
    <fullName>Date_Quoted__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Date Quoted</label>
    <type>Date</type>
</CustomField>

peac_dev/force-app/main/default/objects/Buyout__c/fields/Partial_Buyout__c.field-meta.xml
<CustomField>
    <fullName>Partial_Buyout__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Partial Buyout</label>
    <type>Checkbox</type>
</CustomField>

peac_dev/force-app/main/default/objects/Buyout__c/fields/Quote_Sequence__c.field-meta.xml
<CustomField>
    <fullName>Quote_Sequence__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Quote Sequence</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

peac_dev/force-app/main/default/objects/Buyout_Asset__c/Buyout_Asset__c.object-meta.xml
<CustomObject>
    <description>Object to represent the many-to-many relationship between Buyouts and Contract Assets</description>
    <label>Buyout Asset</label>
    <nameField>
        <displayFormat>BA-{00000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Buyout Assets</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

peac_dev/force-app/main/default/objects/Buyout_Asset__c/fields/Buyout__c.field-meta.xml
<CustomField>
    <fullName>Buyout__c</fullName>
    <label>Buyout</label>
    <referenceTo>Buyout__c</referenceTo>
    <relationshipLabel>Buyout Assets</relationshipLabel>
    <relationshipName>Buyout_Assets</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

peac_dev/force-app/main/default/objects/Buyout_Asset__c/fields/Contract_Asset_Serial_Number__c.field-meta.xml
<CustomField>
    <fullName>Contract_Asset_Serial_Number__c</fullName>
    <formula>Contract_Asset__r.Serial_Number__c</formula>
    <label>Contract Asset Serial Number</label>
    <type>Text</type>
</CustomField>

peac_dev/force-app/main/default/objects/Contract__c/Contract__c.object-meta.xml
<CustomObject>
    <description>Custom Object created so we can use Queue functionality</description>
    <label>Contract</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Contract Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Contracts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

peac_dev/force-app/main/default/objects/Contract__c/fields/AR_Address_1__c.field-meta.xml
<CustomField>
    <fullName>AR_Address_1__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>AR Address 1</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

peac_dev/force-app/main/default/objects/Contract__c/fields/AR_Address_2__c.field-meta.xml
<CustomField>
    <fullName>AR_Address_2__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>AR Address 2</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

peac_dev/force-app/main/default/objects/Contract__c/fields/AR_Address_3__c.field-meta.xml
<CustomField>
    <fullName>AR_Address_3__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>AR Address 3</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

peac_dev/force-app/main/default/objects/Contract__c/fields/AR_City__c.field-meta.xml
<CustomField>
    <fullName>AR_City__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>AR City</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

peac_dev/force-app/main/default/objects/Contract__c/fields/AR_State__c.field-meta.xml
<CustomField>
    <fullName>AR_State__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>AR State</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

peac_dev/force-app/main/default/objects/Contract__c/fields/AR_Zip_Code__c.field-meta.xml
<CustomField>
    <fullName>AR_Zip_Code__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>AR Zip Code</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

peac_dev/force-app/main/default/objects/Contract__c/fields/Customer__c.field-meta.xml
<CustomField>
    <fullName>Customer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Customer account</description>
    <label>Customer</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Customer_Contracts</relationshipName>
    <type>Lookup</type>
</CustomField>

peac_dev/force-app/main/default/objects/Contract__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Description</label>
    <length>32000</length>
    <type>LongTextArea</type>
</CustomField>

peac_dev/force-app/main/default/objects/Contract__c/fields/Insurance_Expiration_Date__c.field-meta.xml
<CustomField>
    <fullName>Insurance_Expiration_Date__c</fullName>
    <formula>Insurance__r.Expiration_Date__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Insurance Expiration Date</label>
    <type>Date</type>
</CustomField>

peac_dev/force-app/main/default/objects/Contract__c/fields/Is_Blind__c.field-meta.xml
<CustomField>
    <fullName>Is_Blind__c</fullName>
    <formula>IF(
  CASE(Lessor_Code__c, 
        &quot;002&quot;, 1, 
        &quot;004&quot;, 1,
        &quot;006&quot;, 1,
        &quot;402&quot;, 1,
        &quot;404&quot;, 1, 
        &quot;406&quot;, 1,
        &quot;414&quot;, 1, 
        &quot;422&quot;, 1,
        &quot;424&quot;, 1,
        &quot;102&quot;, 1,
        &quot;104&quot;, 1,
        0)
     = 1, TRUE, FALSE)</formula>
    <label>Is Blind</label>
    <type>Checkbox</type>
</CustomField>

peac_dev/force-app/main/default/objects/Contract__c/fields/IsXBS__c.field-meta.xml
<CustomField>
    <fullName>IsXBS__c</fullName>
    <formula>IF(
  OR(
    Lessor_Code__c = &quot;111&quot;,
    Lessor_Code__c = &quot;113&quot;,
    Lessor_Code__c = &quot;211&quot;,
    Lessor_Code__c = &quot;213&quot;
    ), 
  TRUE,
  FALSE
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Is XBS?</label>
    <type>Checkbox</type>
</CustomField>

peac_dev/force-app/main/default/objects/Contract__c/fields/Program__c.field-meta.xml
<CustomField>
    <fullName>Program__c</fullName>
    <description>The value is populated from the Program field on the Opportunity. SL - 2093</description>
    <label>Program</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Program</valueSetName>
    </valueSet>
</CustomField>

peac_dev/force-app/main/default/objects/Contract__c/fields/Remit_To_Address__c.field-meta.xml
<CustomField>
    <fullName>Remit_To_Address__c</fullName>
    <formula>Remit_To__r.Remit_To_Address__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Remit To Address</label>
    <type>Text</type>
</CustomField>

peac_dev/force-app/main/default/objects/Contract__c/fields/Remit_To_City__c.field-meta.xml
<CustomField>
    <fullName>Remit_To_City__c</fullName>
    <formula>Remit_To__r.Remit_To_City__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Remit To City</label>
    <type>Text</type>
</CustomField>

peac_dev/force-app/main/default/objects/Contract__c/fields/Remit_To_State__c.field-meta.xml
<CustomField>
    <fullName>Remit_To_State__c</fullName>
    <formula>Remit_To__r.Remit_To_State__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Remit To State</label>
    <type>Text</type>
</CustomField>

peac_dev/force-app/main/default/objects/Contract__c/fields/Remit_To_Zip_Code__c.field-meta.xml
<CustomField>
    <fullName>Remit_To_Zip_Code__c</fullName>
    <formula>Remit_To__r.Remit_To_Zip_Code__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Remit To Zip Code</label>
    <type>Text</type>
</CustomField>

peac_dev/force-app/main/default/objects/Contract__c/fields/Total_Amount_Due__c.field-meta.xml
<CustomField>
    <fullName>Total_Amount_Due__c</fullName>
    <label>Total Due</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

peac_dev/force-app/main/default/objects/ExcludeRemitToAddressOnBuyoutPDFS__mdt/ExcludeRemitToAddressOnBuyoutPDFS__mdt.object-meta.xml
<CustomObject>
    <label>ExcludeRemitToAddressOnBuyoutPDF</label>
    <pluralLabel>ExcludeRemitToAddressOnBuyoutPDFS</pluralLabel>
</CustomObject>

peac_dev/force-app/main/default/objects/ExcludeRemitToAddressOnBuyoutPDFS__mdt/fields/BuyoutType__c.field-meta.xml
<CustomField>
    <fullName>BuyoutType__c</fullName>
    <label>BuyoutType</label>
    <type>TextArea</type>
</CustomField>

peac_dev/force-app/main/default/objects/Program__c/Program__c.object-meta.xml
<CustomObject>
    <label>Program</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Programs</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Programs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

peac_dev/force-app/main/default/classes/SL_PrintDetailedBuyout.cls
public with sharing class SL_PrintDetailedBuyout {
    public List<FieldWrapper> headers{get;set;}
    public List<FieldWrapper> fields{get;set;}
    public Contract__c thisContract{get;set;}
    public string logoResourceName{get;set;}
    public string serialNumbers{get;set;}
    public boolean showAddress{get;set;}
    
    public void setHeaders(String contractId, string quoteSeq){
        
        List<FieldWrapper> allHeaders = new List<FieldWrapper>();
        thisContract = [SELECT Name, Customer__r.Name, AR_Address_1__c, 
                        AR_Address_2__c, AR_Address_3__c, AR_City__c, 
                        AR_State__c,AR_Zip_Code__c, Program__c,Is_Blind__c,IsXBS__c, Remit_To_City__c,Remit_To_Address__c,Remit_To_State__c,Remit_To_Zip_Code__c 
                        FROM Contract__c 
                        WHERE Id =:contractId 
                        LIMIT 1];
        String addressString = thisContract.AR_Address_1__c +' '+ 
            thisContract.AR_Address_2__c +' '+ 
            thisContract.AR_Address_3__c +' \n'+
            thisContract.AR_City__c +', '+ 
            thisContract.AR_State__c +' '+ 
            thisContract.AR_Zip_Code__c;
        allHeaders.add(new FieldWrapper('Contract#', thisContract.Name, false, true));
        allHeaders.add(new FieldWrapper('Customer Name', thisContract.Customer__r.Name, false, true));
        allHeaders.add(new FieldWrapper('Customer Address', addressString.replaceAll('null', ''), false, true));
        if (thisContract.Program__c != null && thisContract.Program__c.contains('XBS')) {
            logoResourceName = 'XBSLogo';
        } else if(thisContract.Is_Blind__c == true){
            logoResourceName = 'LeaseServicesLogo';
        } else if(thisContract.Is_Blind__c == false && thisContract.IsXBS__c == false) {    
            logoResourceName ='PeacSolutionsLogo';
        } 
        if(quoteSeq != null) {
            List<Buyout__c> thisBuyoutList = [select Id,Name,Partial_Buyout__c,Date_Quoted__c FROM Buyout__c WHERE Quote_Sequence__c = :quoteSeq AND Contract__c =: contractId];
            if(thisBuyoutList.size() > 0) {
                Buyout__c thisBuyout = thisBuyoutList.get(0);
                System.debug('ThisBuyout::'+thisBuyout);
                allHeaders.add(new FieldWrapper('Buyout Type', thisBuyout.Name, false, true));
                showAddress = true;
                for(ExcludeRemitToAddressOnBuyoutPDFS__mdt excludeConfig : [select Id, BuyoutType__c from ExcludeRemitToAddressOnBuyoutPDFS__mdt]) {
                    if(thisBuyout.Name.contains(excludeConfig.BuyoutType__c)) {
                        showAddress = false;
                        break;
                    }
                }
                // SL-2644 Misael Romero
                for(Buyout_Asset__c buyoutAsset : [select Id, Contract_Asset_Serial_Number__c from Buyout_Asset__c where Buyout__c =: thisBuyout.Id]) {
                    if(buyoutAsset.Contract_Asset_Serial_Number__c != null) {
                        serialNumbers = serialNumbers != null ? serialNumbers + ', ' + buyoutAsset.Contract_Asset_Serial_Number__c : buyoutAsset.Contract_Asset_Serial_Number__c;
                    }
                }
            }
        }
        
        this.headers = allHeaders;
    }
    
    public List<FieldWrapper> getHeaders(){
        return this.headers;
    }
    
    public void setFields(String incoming, String contractId){
        List<FieldWrapper> allFields = new List<FieldWrapper>();
        // Contract__c thisContract = [SELECT Name, Description__c, Total_Amount_Due__c, Insurance_Expiration_Date__c
        //                             FROM Contract__c 
        //                             WHERE Id =:contractId 
        //                             LIMIT 1];
        
        // allFields.add(new FieldWrapper('Invoice Description', thisContract.Description__c, false, true));
        // allFields.add(new FieldWrapper('Total Amount Due', String.valueOf(thisContract.Total_Amount_Due__c), true, false));
        // allFields.add(new FieldWrapper('Expiration Date', String.valueOf(thisContract.Insurance_Expiration_Date__c), false, true));
        JSONParser parser = JSON.createParser(incoming);
        while (parser.nextToken() != null) {
            if (parser.getCurrentToken() == JSONToken.START_ARRAY) {
                while (parser.nextToken() != null) {
                    if (parser.getCurrentToken() == JSONToken.START_OBJECT) {
                        FieldWrapper aField = (FieldWrapper)parser.readValueAs(FieldWrapper.class);
                        
                        allFields.add(aField);
                    }
                }
            }
        }
        this.fields = allFields;
    }
    public List<FieldWrapper> getFields(){
        return this.fields;
    }
    
    public SL_PrintDetailedBuyout(){
        this.setFields(ApexPages.currentPage().getParameters().get('rows'), ApexPages.currentPage().getParameters().get('contractId'));
        this.setHeaders(ApexPages.currentPage().getParameters().get('contractId'),ApexPages.currentPage().getParameters().get('quoteSeq'));
        
        System.debug('####this.setFields: '+this.fields);
        System.debug('####this.setHeaders: '+this.headers);
    }
    
    public class FieldWrapper{
        public String label{get;set;}
        public String value{get;set;}
        public Boolean isCurrency{get;set;}
        public Boolean isPlain{get;set;}
        public FieldWrapper(String label, String value, Boolean isCurrency, Boolean isPlain){
            this.label = label;
            this.value = value;
            this.isCurrency = isCurrency;
            this.isPlain = isPlain;
        }
    }
}