peac_dev/force-app/main/default/objects/Buyout__c/Buyout__c.object-meta.xml
<CustomObject>
    <description>Object to store active and legacy Buyouts returned by Infolease. Data in this object will be purged on a 6 month rolling basis</description>
    <label>Buyout</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Buyout Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Buyouts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

peac_dev/force-app/main/default/objects/Buyout__c/fields/Buyout_Amount__c.field-meta.xml
<CustomField>
    <fullName>Buyout_Amount__c</fullName>
    <defaultValue>0.00</defaultValue>
    <label>Buyout Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

peac_dev/force-app/main/default/objects/Buyout__c/fields/Buyout_Description__c.field-meta.xml
<CustomField>
    <fullName>Buyout_Description__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Buyout Description</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

peac_dev/force-app/main/default/objects/Buyout__c/fields/Contract__c.field-meta.xml
<CustomField>
    <fullName>Contract__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contract</label>
    <referenceTo>Contract__c</referenceTo>
    <relationshipLabel>Buyouts</relationshipLabel>
    <relationshipName>Buyouts</relationshipName>
    <type>Lookup</type>
</CustomField>

peac_dev/force-app/main/default/objects/Buyout__c/fields/Date_Quoted__c.field-meta.xml
<CustomField>
    <fullName>Date_Quoted__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Date Quoted</label>
    <type>Date</type>
</CustomField>

peac_dev/force-app/main/default/objects/Buyout__c/fields/Early_Termination_Fee__c.field-meta.xml
<CustomField>
    <fullName>Early_Termination_Fee__c</fullName>
    <defaultValue>0.00</defaultValue>
    <label>Early Termination Fee</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

peac_dev/force-app/main/default/objects/Buyout__c/fields/Ending_Deposit__c.field-meta.xml
<CustomField>
    <fullName>Ending_Deposit__c</fullName>
    <defaultValue>0.00</defaultValue>
    <label>Ending Deposit</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

peac_dev/force-app/main/default/objects/Buyout__c/fields/Expiration_Date__c.field-meta.xml
<CustomField>
    <fullName>Expiration_Date__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Expiration Date</label>
    <type>Date</type>
</CustomField>

peac_dev/force-app/main/default/objects/Buyout__c/fields/Insurance__c.field-meta.xml
<CustomField>
    <fullName>Insurance__c</fullName>
    <defaultValue>0.00</defaultValue>
    <label>Insurance</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

peac_dev/force-app/main/default/objects/Buyout__c/fields/LateCharges__c.field-meta.xml
<CustomField>
    <fullName>LateCharges__c</fullName>
    <defaultValue>0.00</defaultValue>
    <label>LateCharges</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

peac_dev/force-app/main/default/objects/Buyout__c/fields/Most_Recent__c.field-meta.xml
<CustomField>
    <fullName>Most_Recent__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Most Recent</label>
    <type>Checkbox</type>
</CustomField>

peac_dev/force-app/main/default/objects/Buyout__c/fields/Other_Lease_Charges__c.field-meta.xml
<CustomField>
    <fullName>Other_Lease_Charges__c</fullName>
    <defaultValue>0.00</defaultValue>
    <label>Other Lease Charges</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

peac_dev/force-app/main/default/objects/Buyout__c/fields/Partial_Buyout__c.field-meta.xml
<CustomField>
    <fullName>Partial_Buyout__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Partial Buyout</label>
    <type>Checkbox</type>
</CustomField>

peac_dev/force-app/main/default/objects/Buyout__c/fields/Property_tax__c.field-meta.xml
<CustomField>
    <fullName>Property_tax__c</fullName>
    <defaultValue>0.00</defaultValue>
    <label>Property tax</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

peac_dev/force-app/main/default/objects/Buyout__c/fields/Quote_Sequence__c.field-meta.xml
<CustomField>
    <fullName>Quote_Sequence__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Quote Sequence</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

peac_dev/force-app/main/default/objects/Buyout__c/fields/Receivable_Balance__c.field-meta.xml
<CustomField>
    <fullName>Receivable_Balance__c</fullName>
    <defaultValue>0.00</defaultValue>
    <label>Receivable Balance</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

peac_dev/force-app/main/default/objects/Buyout__c/fields/Residual__c.field-meta.xml
<CustomField>
    <fullName>Residual__c</fullName>
    <defaultValue>0.00</defaultValue>
    <label>Residual</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

peac_dev/force-app/main/default/objects/Buyout__c/fields/SalesTax__c.field-meta.xml
<CustomField>
    <fullName>SalesTax__c</fullName>
    <defaultValue>0.00</defaultValue>
    <label>SalesTax</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

peac_dev/force-app/main/default/objects/Buyout__c/fields/Security_Deposit__c.field-meta.xml
<CustomField>
    <fullName>Security_Deposit__c</fullName>
    <defaultValue>0.00</defaultValue>
    <label>Security Deposit</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

peac_dev/force-app/main/default/objects/Buyout__c/fields/Service_pass_through__c.field-meta.xml
<CustomField>
    <fullName>Service_pass_through__c</fullName>
    <defaultValue>0.00</defaultValue>
    <label>Pass Through</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

peac_dev/force-app/main/default/objects/Buyout__c/fields/Total_Buyout__c.field-meta.xml
<CustomField>
    <fullName>Total_Buyout__c</fullName>
    <defaultValue>0.00</defaultValue>
    <label>Total Buyout</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

peac_dev/force-app/main/default/objects/Buyout_Asset__c/Buyout_Asset__c.object-meta.xml
<CustomObject>
    <description>Object to represent the many-to-many relationship between Buyouts and Contract Assets</description>
    <label>Buyout Asset</label>
    <nameField>
        <displayFormat>BA-{00000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Buyout Assets</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

peac_dev/force-app/main/default/objects/Buyout_Asset__c/fields/Buyout__c.field-meta.xml
<CustomField>
    <fullName>Buyout__c</fullName>
    <label>Buyout</label>
    <referenceTo>Buyout__c</referenceTo>
    <relationshipLabel>Buyout Assets</relationshipLabel>
    <relationshipName>Buyout_Assets</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

peac_dev/force-app/main/default/objects/Buyout_Asset__c/fields/Contract_Asset__c.field-meta.xml
<CustomField>
    <fullName>Contract_Asset__c</fullName>
    <label>Contract Asset</label>
    <referenceTo>Contract_Asset__c</referenceTo>
    <relationshipLabel>Buyout Assets</relationshipLabel>
    <relationshipName>Buyout_Assets</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

peac_dev/force-app/main/default/objects/Contract__c/Contract__c.object-meta.xml
<CustomObject>
    <description>Custom Object created so we can use Queue functionality</description>
    <label>Contract</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Contract Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Contracts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

peac_dev/force-app/main/default/objects/Contract__c/fields/AR_Address_1__c.field-meta.xml
<CustomField>
    <fullName>AR_Address_1__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>AR Address 1</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

peac_dev/force-app/main/default/objects/Contract__c/fields/Customer__c.field-meta.xml
<CustomField>
    <fullName>Customer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Customer account</description>
    <label>Customer</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Customer_Contracts</relationshipName>
    <type>Lookup</type>
</CustomField>

peac_dev/force-app/main/default/objects/Contract__c/fields/Insurance__c.field-meta.xml
<CustomField>
    <fullName>Insurance__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Insurance</label>
    <referenceTo>Insurance__c</referenceTo>
    <relationshipName>Custom_Contracts</relationshipName>
    <type>Lookup</type>
</CustomField>

peac_dev/force-app/main/default/objects/Contract__c/fields/Purchase_Option__c.field-meta.xml
<CustomField>
    <fullName>Purchase_Option__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Purchase Option</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

peac_dev/force-app/main/default/objects/Contract__c/fields/Security_Deposit__c.field-meta.xml
<CustomField>
    <fullName>Security_Deposit__c</fullName>
    <label>Security Deposit</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

peac_dev/force-app/main/default/objects/Contract_Asset__c/Contract_Asset__c.object-meta.xml
<CustomObject>
    <label>Contract Asset</label>
    <nameField>
        <displayFormat>CA-{0000}</displayFormat>
        <label>Contract Asset Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contract Assets</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

peac_dev/force-app/main/default/objects/Contract_Asset__c/fields/Asset_Cost__c.field-meta.xml
<CustomField>
    <fullName>Asset_Cost__c</fullName>
    <label>Asset Cost</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

peac_dev/force-app/main/default/objects/Contract_Asset__c/fields/Contract__c.field-meta.xml
<CustomField>
    <fullName>Contract__c</fullName>
    <label>Contract</label>
    <referenceTo>Contract__c</referenceTo>
    <relationshipLabel>Contract Assets</relationshipLabel>
    <relationshipName>Contract_Assets</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

peac_dev/force-app/main/default/objects/Contract_Asset__c/fields/Customer__c.field-meta.xml
<CustomField>
    <fullName>Customer__c</fullName>
    <formula>Contract__r.Customer_name__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Customer</label>
    <type>Text</type>
</CustomField>

peac_dev/force-app/main/default/objects/Contract_Asset__c/fields/Insurance__c.field-meta.xml
<CustomField>
    <fullName>Insurance__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Insurance</label>
    <referenceTo>Insurance__c</referenceTo>
    <relationshipLabel>Contract Assets</relationshipLabel>
    <relationshipName>Contract_Assets</relationshipName>
    <type>Lookup</type>
</CustomField>

peac_dev/force-app/main/default/objects/Contract_Asset__c/fields/Purchase_Option__c.field-meta.xml
<CustomField>
    <fullName>Purchase_Option__c</fullName>
    <label>Purchase Option</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>01</fullName>
                <label>FMV</label>
            </value>
            <value>
                <fullName>02</fullName>
                <label>10% Purchase Option</label>
            </value>
            <value>
                <fullName>03</fullName>
                <label>1.00 Out</label>
            </value>
            <value>
                <fullName>05</fullName>
                <label>Put</label>
            </value>
            <value>
                <fullName>06</fullName>
                <label>Assigned Residual</label>
            </value>
            <value>
                <fullName>08</fullName>
                <label>Customer Owned  (EFA)</label>
            </value>
            <value>
                <fullName>09</fullName>
                <label>FMV - Capped</label>
            </value>
            <value>
                <fullName>10</fullName>
                <label>$101 Purchase Option</label>
            </value>
            <value>
                <fullName>11</fullName>
                <label>Fixed Purchase Option</label>
            </value>
            <value>
                <fullName>12</fullName>
                <label>FMV - Used Equipment</label>
            </value>
            <value>
                <fullName>15</fullName>
                <label>FMV No Renewal</label>
            </value>
            <value>
                <fullName>17</fullName>
                <label>PUT No Renewal</label>
            </value>
            <value>
                <fullName>18</fullName>
                <label>Assign Resid No Renewal</label>
            </value>
            <value>
                <fullName>22</fullName>
                <label>FMV Used No Renewal</label>
            </value>
            <value>
                <fullName>25</fullName>
                <label>Guaranteed Residual</label>
            </value>
            <value>
                <fullName>26</fullName>
                <label>Rental - No Purchase Option</label>
            </value>
            <value>
                <fullName>27</fullName>
                <label>Call Wells Fargo for Quote</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

peac_dev/force-app/main/default/objects/Contract_Asset__c/fields/Serial_Number__c.field-meta.xml
<CustomField>
    <fullName>Serial_Number__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <externalId>true</externalId>
    <label>Serial Number</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

peac_dev/force-app/main/default/objects/Insurance__c/Insurance__c.object-meta.xml
<CustomObject>
    <label>Insurance</label>
    <nameField>
        <displayFormat>INS-{0000}</displayFormat>
        <label>Insurance Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Insurance</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

peac_dev/force-app/main/default/objects/Insurance__c/fields/Customer__c.field-meta.xml
<CustomField>
    <fullName>Customer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Account set as the customer</description>
    <inlineHelpText>select the Customer who owns the Insurance</inlineHelpText>
    <label>Customer</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Insurance</relationshipLabel>
    <relationshipName>Insurance</relationshipName>
    <type>Lookup</type>
</CustomField>

peac_dev/force-app/main/default/objects/Insurance__c/fields/Expiration_Date__c.field-meta.xml
<CustomField>
    <fullName>Expiration_Date__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Expiration Date</label>
    <type>Date</type>
</CustomField>

peac_dev/force-app/main/default/classes/PEAC_PartnerQuotePDFController.cls
public class PEAC_PartnerQuotePDFController {
    public Contract__c thisContract{get;set;}
    public Buyout__c thisBuyout {get; set;}
    public Buyout_Asset__c thisContractAsset {get; set;}
    public string serialNumbers{get; set;}
    public PEAC_PartnerQuotePDFController(){
        String buyoutId = ApexPages.currentPage().getParameters().get('buyoutId');
        
        thisBuyout = [ SELECT Id,Name, Contract__c, Buyout_Description__c, Quote_Sequence__c, Buyout_Amount__c, Most_Recent__c, Receivable_Balance__c, Residual__c, SalesTax__c, LateCharges__c, Early_Termination_Fee__c, Security_Deposit__c, Ending_Deposit__c, Service_pass_through__c, Property_tax__c, Insurance__c, Other_Lease_Charges__c, Total_Buyout__c, Partial_Buyout__c, Date_Quoted__c, Expiration_Date__c, Createddate FROM Buyout__c WHERE Id = :buyoutId];
       //  thisContractAsset = [SELECT Id, Contract_Asset__r.Asset_Cost__c,Serial_Number__c, Contract_Asset__r.Purchase_Option__c FROM Buyout_Asset__c];
        thisContract = [SELECT Name, Customer__r.Name, AR_Address_1__c, 
                                    AR_Address_2__c, AR_Address_3__c, AR_City__c,Contract_Term__c,Payments_Made__c,Dealer_Name__r.name, 
                                    AR_State__c,AR_Zip_Code__c,Next_Payment_Date__c,Commencement_Date__c, Payments_Remaining__c, Purchase_Option_Description__c, Payment_Amount__c
                                    FROM Contract__c 
                                    WHERE Id =:thisBuyout.Contract__c
                                    LIMIT 1];
        Set<string> serialNumberSet = new Set<string>();
        if(thisBuyout.Partial_Buyout__c) {
            for(Buyout_Asset__c buyoutAsset : [select Id, Contract_Asset_Serial_Number__c from Buyout_Asset__c where Buyout__c =: buyoutId]) {
                if(buyoutAsset.Contract_Asset_Serial_Number__c != null) {
                    serialNumbers = serialNumbers != null ? serialNumbers + ', ' + buyoutAsset.Contract_Asset_Serial_Number__c : buyoutAsset.Contract_Asset_Serial_Number__c;
                }
            }
        } else {
            Date buyoutDate; 
            buyoutDate = thisBuyout.Date_Quoted__c;
            for(Contract_Asset__c contractAsset : [select Id, Serial_Number__c from Contract_Asset__c where Contract__c =: thisBuyout.Contract__c AND (Asset_Disposed_Date__c = null OR Asset_Disposed_Date__c > :buyoutDate ) AND Asset_Cost__c > 0]) {
                if(contractAsset.Serial_Number__c != null) {
                    serialNumbers = serialNumbers != null ? serialNumbers + ', ' + contractAsset.Serial_Number__c : contractAsset.Serial_Number__c;
                    
                }
                
            }
        }
       // serialNumbers = serialNumberSet.toString();
        
    }
    
}