peac_dev/force-app/main/default/objects/Payment__c/Payment__c.object-meta.xml
<CustomObject>
    <description>Payments to a Payee related to an opportunity</description>
    <label>Payment</label>
    <nameField>
        <displayFormat>PYMT-{0}</displayFormat>
        <label>Payment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

peac_dev/force-app/main/default/objects/Payment__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <inlineHelpText>Opportunity related to this payment</inlineHelpText>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Payments</relationshipLabel>
    <relationshipName>Payments</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

peac_dev/force-app/main/default/objects/Payoff__c/Payoff__c.object-meta.xml
<CustomObject>
    <label>Payoff</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Contract Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Payoffs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

peac_dev/force-app/main/default/objects/Payoff__c/fields/Lender_Name__c.field-meta.xml
<CustomField>
    <fullName>Lender_Name__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Lender Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

peac_dev/force-app/main/default/objects/Payoff__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Payoffs</relationshipLabel>
    <relationshipName>Payoffs</relationshipName>
    <type>Lookup</type>
</CustomField>

peac_dev/force-app/main/default/objects/Payoff__c/fields/Payment__c.field-meta.xml
<CustomField>
    <fullName>Payment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Payment</label>
    <referenceTo>Payment__c</referenceTo>
    <relationshipLabel>Payoffs</relationshipLabel>
    <relationshipName>Payoffs</relationshipName>
    <type>Lookup</type>
</CustomField>

peac_dev/force-app/main/default/objects/Payoff__c/fields/Payoff_Amount__c.field-meta.xml
<CustomField>
    <fullName>Payoff_Amount__c</fullName>
    <label>Payoff Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

peac_dev/force-app/main/default/objects/Payoff__c/fields/Third_Party__c.field-meta.xml
<CustomField>
    <fullName>Third_Party__c</fullName>
    <defaultValue>false</defaultValue>
    <label>3rd Party?</label>
    <type>Checkbox</type>
</CustomField>

peac_dev/force-app/main/default/objects/Payoff__c/fields/Trade_Up_to_Return__c.field-meta.xml
<CustomField>
    <fullName>Trade_Up_to_Return__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Trade Up to Return</label>
    <type>Checkbox</type>
</CustomField>

peac_dev/force-app/main/default/classes/TC_LGTNExistingOppPayOffCTRL.cls
public class TC_LGTNExistingOppPayOffCTRL {
    
    @auraEnabled public static String grabPayOffs (String recordId, String oppId) {

        List <PayOffWrapper> payOffs = new List <PayOffWrapper > ();
        for (Payoff__c payOff: [SELECT Id, Name, Payoff_Amount__c, Third_Party__c, Lender_Name__c, Trade_Up_to_Return__c   FROM Payoff__c WHERE Opportunity__c = :oppId AND Payment__c != :recordId]){
            payOffs.add (new PayOffWrapper (payOff.Name, payOff.Payoff_Amount__c, payOff.Lender_Name__c, payOff.Third_Party__c, payOff.Id, payOff.Trade_Up_to_Return__c));
        }
        return JSON.serialize(payOffs);
    }
    
    @auraEnabled public static void savePayOffs (String payOffsJSON, String recordId) {
        List <PayOffWrapper> payOffs = (List <PayOffWrapper>) JSON.deserialize(payOffsJSON, List<PayOffWrapper>.class);
        List <Payoff__c> updateList = new List <Payoff__c> ();
        for (PayOffWrapper pow : payOffs) {
            if (pow != null && pow.selected !=null && pow.selected) {
                updateList.add (new Payoff__c (Id = pow.payOffId
                                                , Payment__c = recordId));
            }
        }
        System.debug ('>>>>> payOffs ' + updateList);
        update updateList;
        
    }
    
    @auraEnabled public static String grabOppInfo (String recordId) {
        return JSON.serialize([SELECT Opportunity__c, Opportunity__r.Loan_Record_Type__c FROM Payment__c WHERE Id = :recordId][0]);
    }
    
    
    
    public class PayOffWrapper {
        @auraEnabled public Boolean selected;
        @auraEnabled public String contractNumber;
        @auraEnabled public Decimal paymentAmount;
        @auraEnabled public String lenderName;
        @auraEnabled public Boolean thirdParty;
        @auraEnabled public Id payOffId;
        @auraEnabled public Boolean tradeUpToReturn; 
        
        public PayOffWrapper (String contractNumber, Decimal paymentAmount, String lenderName, Boolean thirdParty, Id payOffId, Boolean tradeUpToReturn) {
            this.selected = false;
            this.contractNumber = contractNumber;
            this.paymentAmount = paymentAmount;
            this.lenderName = lenderName;
            this.thirdParty = thirdParty;
            this.payOffId = payOffId;
            this.tradeUpToReturn = tradeUpToReturn;
            
        }
    }

}