peac_dev/force-app/main/default/objects/EF_Approved_Offers__c/EF_Approved_Offers__c.object-meta.xml
<CustomObject>
    <label>EF Approved Offers</label>
    <nameField>
        <displayFormat>Offer-{0}</displayFormat>
        <label>EF Approved Offers ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>EF Approved Offers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

peac_dev/force-app/main/default/objects/EF_Approved_Offers__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>EF Approved Offers</relationshipLabel>
    <relationshipName>EF_Approved_Offers</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

peac_dev/force-app/main/default/objects/EF_Approved_Offers__c/fields/Term_in_Months__c.field-meta.xml
<CustomField>
    <fullName>Term_in_Months__c</fullName>
    <label>Term (in Months)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

peac_dev/force-app/main/default/objects/EF_Approved_Offers__c/fields/Yield__c.field-meta.xml
<CustomField>
    <fullName>Yield__c</fullName>
    <description>Populates from matching rate card for system generated offers, not editable. Needs to interpolate as needed for non-aligned Terms.</description>
    <label>Yield</label>
    <precision>7</precision>
    <scale>4</scale>
    <type>Percent</type>
</CustomField>

peac_dev/force-app/main/default/objects/EF_Approved_Offers__c/recordTypes/System.recordType-meta.xml
<RecordType>
    <fullName>System</fullName>
    <active>true</active>
    <description>System Generated Offer</description>
    <label>System</label>
</RecordType>

peac_dev/force-app/main/default/classes/TC_SobjectRecordFactory.cls
/** @author : Tamarack Consulting, Inc.
 * @date : 10/29/20
 * @description: 
 *
 */
public with sharing class TC_SobjectRecordFactory {

    /**
     * Creates an account record
     *
     * @return An account
     */
    public static Account createAccount(TC_RateCardRequestBean req) {

        Account acc = new Account();
        acc.RecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('End User Account').getRecordTypeId();
        acc.Name = 'STATIC ACCOUNT FOR RATE CARDS - DO NOT DELETE';
        acc.Channel_Approver__c = UserInfo.getUserId();

        return acc;
    }

    /**
     * Creates an opportunity record
     *
     * @param acc The parent account
     * @return An opportunity
     */
    public static Opportunity createOpportunity(Account acc) {

        if (acc.Id <> null) {

            Opportunity opp = new Opportunity();
            opp.RecordTypeId = Schema.SObjectType.Opportunity.getRecordTypeInfosByName().get('Express Quote').getRecordTypeId();
            opp.Name = 'STATIC OPPORTUNITY FOR RATE CARDS - DO NOT DELETE';
            opp.AccountId = acc.Id;
            opp.StageName = 'Proposal';
            opp.Primary_Source__c = 'Customer Inbound - Call';
            opp.CloseDate = System.today();

            return opp;
        }

        return null;
    }

    /**
     * @return a list of dummy rate cards for testing purposes
     */
    @TestVisible
    private static List<EF_Approved_Offers__c> createEfApprovedOffers(Opportunity opp, Integer numOfCards, Decimal term, Decimal yield) {

        List<EF_Approved_Offers__c> rateCards = new List<EF_Approved_Offers__c>();

        for (Integer i = 0; i < numOfCards; i++) {
            EF_Approved_Offers__c rateCard = new EF_Approved_Offers__c(
                    Opportunity__c = opp.Id,
                    Term_in_Months__c = term,
                    Yield__c = yield
            );
            rateCards.add(rateCard);
        }

        return rateCards;
    }
}