peac_dev/force-app/main/default/objects/EF_Approved_Offers__c/EF_Approved_Offers__c.object-meta.xml
<CustomObject>
    <label>EF Approved Offers</label>
    <nameField>
        <displayFormat>Offer-{0}</displayFormat>
        <label>EF Approved Offers ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>EF Approved Offers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

peac_dev/force-app/main/default/objects/EF_Approved_Offers__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>EF Approved Offers</relationshipLabel>
    <relationshipName>EF_Approved_Offers</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

peac_dev/force-app/main/default/objects/EF_Approved_Offers__c/fields/Term_in_Months__c.field-meta.xml
<CustomField>
    <fullName>Term_in_Months__c</fullName>
    <label>Term (in Months)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

peac_dev/force-app/main/default/objects/EF_Approved_Offers__c/fields/Yield__c.field-meta.xml
<CustomField>
    <fullName>Yield__c</fullName>
    <description>Populates from matching rate card for system generated offers, not editable. Needs to interpolate as needed for non-aligned Terms.</description>
    <label>Yield</label>
    <precision>7</precision>
    <scale>4</scale>
    <type>Percent</type>
</CustomField>

peac_dev/force-app/main/default/objects/EF_Approved_Offers__c/recordTypes/Custom.recordType-meta.xml
<RecordType>
    <fullName>Custom</fullName>
    <active>true</active>
    <description>User created custom offer</description>
    <label>Custom</label>
</RecordType>

peac_dev/force-app/main/default/objects/EF_Approved_Offers__c/recordTypes/System.recordType-meta.xml
<RecordType>
    <fullName>System</fullName>
    <active>true</active>
    <description>System Generated Offer</description>
    <label>System</label>
</RecordType>

peac_dev/force-app/main/default/classes/TC_CustomEfOfferDefaults.cls
/**
 * Created by andrewmayer on 9/15/20.
 *
 * default yield and term for custom offers
 */

public with sharing class TC_CustomEfOfferDefaults implements TC_TriggerActionI{

    public final Id SYSTEM_GEN_RT = Schema.SObjectType.EF_Approved_Offers__c.getRecordTypeInfosByName().get('System').getRecordTypeId();

    public void doAction(TC_TriggerContext tc) {
        // before insert
        List <EF_Approved_Offers__c> newList = (List <EF_Approved_Offers__c>) tc.getNewList ();

        Set <Id> oppIds = new Set <Id> ();
        for (EF_Approved_Offers__c offer : newList) {
            if (offer.RecordTypeId != SYSTEM_GEN_RT && String.isNotBlank(offer.Opportunity__c)) oppIds.add (offer.Opportunity__c);
        }
        if (oppIds.isEmpty()) return;

        Map <Id, Opportunity> defaultValues = new Map <Id, Opportunity> ([SELECT Id, Yield__c, Terms__c FROM Opportunity WHERE Id IN :oppIds]);

        for (EF_Approved_Offers__c offer : newList) {
            if (offer.RecordTypeId != SYSTEM_GEN_RT && String.isNotBlank(offer.Opportunity__c) && defaultValues.get (offer.Opportunity__c) != null) {
                Opportunity opp = defaultValues.get (offer.Opportunity__c);
                if (offer.Yield__c == null) offer.Yield__c = opp.Yield__c;
                if (offer.Term_in_Months__c == null) offer.Term_in_Months__c = opp.Terms__c;
            }
        }
    }
}