peac_dev/force-app/main/default/objects/EF_Approved_Offers__c/EF_Approved_Offers__c.object-meta.xml
<CustomObject>
    <label>EF Approved Offers</label>
    <nameField>
        <displayFormat>Offer-{0}</displayFormat>
        <label>EF Approved Offers ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>EF Approved Offers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

peac_dev/force-app/main/default/objects/EF_Approved_Offers__c/fields/Advanced_Rental__c.field-meta.xml
<CustomField>
    <fullName>Advanced_Rental__c</fullName>
    <label>Advanced Rental</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>First Payment</fullName>
            </value>
            <value>
                <fullName>First &amp; Last Payment</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

peac_dev/force-app/main/default/objects/EF_Approved_Offers__c/fields/Monthly_Payment__c.field-meta.xml
<CustomField>
    <fullName>Monthly_Payment__c</fullName>
    <formula>Rate_Factor__c * ((Equipment_Cost__c *(1 + (Points__c / 100))) - Advanced_Rental_Amount__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Monthly Payment</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

peac_dev/force-app/main/default/objects/EF_Approved_Offers__c/fields/Offer_Selected__c.field-meta.xml
<CustomField>
    <fullName>Offer_Selected__c</fullName>
    <label>Selected Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Not Selected</fullName>
            </value>
            <value>
                <fullName>Selected</fullName>
            </value>
            <value>
                <fullName>Pending Exception Approval</fullName>
            </value>
            <value>
                <fullName>Exception Approved</fullName>
                <label>Exception Approved (Selected)</label>
            </value>
            <value>
                <fullName>Exception Rejected</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

peac_dev/force-app/main/default/objects/EF_Approved_Offers__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>EF Approved Offers</relationshipLabel>
    <relationshipName>EF_Approved_Offers</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

peac_dev/force-app/main/default/objects/EF_Approved_Offers__c/fields/Points__c.field-meta.xml
<CustomField>
    <fullName>Points__c</fullName>
    <description>Formula from Opportunity.Points__c. For use with system generated offers.</description>
    <formula>Opportunity__r.Points__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Points</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

peac_dev/force-app/main/default/objects/EF_Approved_Offers__c/fields/Rate_Factor__c.field-meta.xml
<CustomField>
    <fullName>Rate_Factor__c</fullName>
    <label>Rate Factor</label>
    <precision>18</precision>
    <scale>8</scale>
    <type>Number</type>
</CustomField>

peac_dev/force-app/main/default/objects/EF_Approved_Offers__c/fields/Term_in_Months__c.field-meta.xml
<CustomField>
    <fullName>Term_in_Months__c</fullName>
    <label>Term (in Months)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

peac_dev/force-app/main/default/objects/EF_Approved_Offers__c/fields/Yield__c.field-meta.xml
<CustomField>
    <fullName>Yield__c</fullName>
    <description>Populates from matching rate card for system generated offers, not editable. Needs to interpolate as needed for non-aligned Terms.</description>
    <label>Yield</label>
    <precision>7</precision>
    <scale>4</scale>
    <type>Percent</type>
</CustomField>

peac_dev/force-app/main/default/objects/EF_Approved_Offers__c/recordTypes/Custom.recordType-meta.xml
<RecordType>
    <fullName>Custom</fullName>
    <active>true</active>
    <description>User created custom offer</description>
    <label>Custom</label>
</RecordType>

peac_dev/force-app/main/default/objects/EF_Approved_Offers__c/recordTypes/System.recordType-meta.xml
<RecordType>
    <fullName>System</fullName>
    <active>true</active>
    <description>System Generated Offer</description>
    <label>System</label>
</RecordType>

peac_dev/force-app/main/default/classes/TC_EFOfferStatusIsSelected.cls
/**
 * Created by andrewmayer on 9/16/20.
 * updates fields on the opportunity after a offer's selected status is selected/approved
 */

public with sharing class TC_EFOfferStatusIsSelected implements TC_TriggerActionI{

    public Set <String> selectedStatuses = new Set <String> {'Selected','Exception Approved'};
    public static final Id SYSTEM_GEN_RT = Schema.SObjectType.EF_Approved_Offers__c.getRecordTypeInfosByName().get('System').getRecordTypeId();

    public void doAction(TC_TriggerContext tc) {
        // on runs on after update
        Map <Id, EF_Approved_Offers__c> oldMap = (Map <Id, EF_Approved_Offers__c>) tc.getOldMap ();
        Map <Id, EF_Approved_Offers__c> newMap = (Map <Id, EF_Approved_Offers__c>) tc.getNewMap ();

        Map <Id, Opportunity> oppUpdates = new Map <Id, Opportunity> ();
        Set <Id> selected = new Set <Id> ();

        for (EF_Approved_Offers__c offer : newMap.values ()) {
            if (offer.Offer_Selected__c != null
                && selectedStatuses.contains(offer.Offer_Selected__c)
                && (oldMap == null || !selectedStatuses.contains(oldMap.get (offer.Id).Offer_Selected__c) )) {
                selected.add (offer.Id);
                
                /* Removed Section per sal 2884
                oppUpdates.put (offer.Opportunity__c
                , new Opportunity (Id = offer.Opportunity__c
                        , Payment_Amount__c = offer.Monthly_Payment__c
                        , Terms__c = offer.Term_in_Months__c
                        , X_Rate_Factor__c = offer.Rate_Factor__c
                        , Yield__c = offer.Yield__c
                        , of_Payments__c = offer.Term_in_Months__c
                        , EF_Approved_Offers__c = offer.Id));
                */
                Opportunity opp = new Opportunity (
                    Id = offer.Opportunity__c, 
                    Payment_Amount__c = offer.Monthly_Payment__c, 
                    Terms__c = offer.Term_in_Months__c, 
                    X_Rate_Factor__c = offer.Rate_Factor__c, 
                    Yield__c = offer.Yield__c, 
                    of_Payments__c = offer.Term_in_Months__c, 
                    EF_Approved_Offers__c = offer.Id
                );

                // SAL-2884 - If the new “Advanced Rental” field is set to First Payment, update the Opportunity.Required_Adv_Payments__c = 1; or 2 if First & Last Payment
                if (offer.Advanced_Rental__c=='First Payment') {
                    opp.Required_Adv_Payments__c = 1;
                } else if (offer.Advanced_Rental__c=='First & Last Payment') {
                    opp.Required_Adv_Payments__c = 2;
                }

                oppUpdates.put (offer.Opportunity__c, opp);
                
                // only custom has points set
                if (offer.RecordTypeId != SYSTEM_GEN_RT) oppUpdates.get (offer.Opportunity__c).Points__c = offer.Points__c;
            }
        }
        if (selected.isEmpty()) return;

        update oppUpdates.values ();

        // deselect rest
        List <EF_Approved_Offers__c> offersToDeSelect = new List <EF_Approved_Offers__c> ([SELECT Id,Offer_Selected__c FROM EF_Approved_Offers__c WHERE Opportunity__c IN :oppUpdates.keySet() AND Id NOT IN :selected AND Offer_Selected__c IN :selectedStatuses]);
        if (offersToDeSelect.isEmpty()) return;

        for (EF_Approved_Offers__c offer : offersToDeSelect) {
            offer.Offer_Selected__c = 'Not Selected';
        }
        update offersToDeSelect;
    }
}