peac_dev/force-app/main/default/objects/Beneficial_Owner__c/Beneficial_Owner__c.object-meta.xml
<CustomObject>
    <label>Beneficial Owner</label>
    <nameField>
        <displayFormat>O-{0000}</displayFormat>
        <label>Beneficial Owner</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Beneficial Owners</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

peac_dev/force-app/main/default/objects/Beneficial_Owner__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Beneficial Owners</relationshipLabel>
    <relationshipName>Beneficial_Owners</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

peac_dev/force-app/main/default/objects/Beneficial_Owner__c/fields/Ownership_Percent__c.field-meta.xml
<CustomField>
    <fullName>Ownership_Percent__c</fullName>
    <label>Ownership Percent</label>
    <precision>14</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

peac_dev/force-app/main/default/objects/Dealer__c/Dealer__c.object-meta.xml
<CustomObject>
    <label>Dealer</label>
    <nameField>
        <displayFormat>B-{0000}</displayFormat>
        <label>Dealer Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Dealers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

peac_dev/force-app/main/default/objects/Dealer__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipName>Brokers</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

peac_dev/force-app/main/default/objects/Guarantor__c/Guarantor__c.object-meta.xml
<CustomObject>
    <label>Guarantor</label>
    <nameField>
        <displayFormat>G-{00000}</displayFormat>
        <label>Guarantor Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Guarantors</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

peac_dev/force-app/main/default/objects/Guarantor__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>GuarantorS</relationshipLabel>
    <relationshipName>GuarantorAccount</relationshipName>
    <type>Lookup</type>
</CustomField>

peac_dev/force-app/main/default/objects/Guarantor__c/fields/Business_Phone__c.field-meta.xml
<CustomField>
    <fullName>Business_Phone__c</fullName>
    <formula>Account__r.Business_Phone__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Business Phone</label>
    <type>Text</type>
</CustomField>

peac_dev/force-app/main/default/objects/Guarantor__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Guarantors</relationshipLabel>
    <relationshipName>GuarantorContact</relationshipName>
    <type>Lookup</type>
</CustomField>

peac_dev/force-app/main/default/objects/Guarantor__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <description>master detail relationship to Opportunity</description>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Guarantors</relationshipLabel>
    <relationshipName>Guarantor</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

peac_dev/force-app/main/default/objects/Guarantor__c/fields/SSN__c.field-meta.xml
<CustomField>
    <fullName>SSN__c</fullName>
    <formula>Contact__r.SSN__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>SSN</label>
    <type>Text</type>
</CustomField>

peac_dev/force-app/main/default/objects/Guarantor__c/fields/Tax_Id__c.field-meta.xml
<CustomField>
    <fullName>Tax_Id__c</fullName>
    <formula>Account__r.Tax_ID__c</formula>
    <label>Tax Id</label>
    <type>Text</type>
</CustomField>

peac_dev/force-app/main/default/objects/ORE__c/ORE__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Settings to Bypass Org Rules</description>
    <label>OrgExceptions</label>
</CustomObject>

peac_dev/force-app/main/default/objects/ORE__c/fields/Bypass__c.field-meta.xml
<CustomField>
    <fullName>Bypass__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Bypass</label>
    <type>Checkbox</type>
</CustomField>

peac_dev/force-app/main/default/objects/Payee__c/Payee__c.object-meta.xml
<CustomObject>
    <label>Payee</label>
    <nameField>
        <displayFormat>PAY-{000000}</displayFormat>
        <label>Payee Indentification</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payees</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

peac_dev/force-app/main/default/objects/Payee__c/fields/Address1__c.field-meta.xml
<CustomField>
    <fullName>Address1__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Address1</label>
    <length>60</length>
    <type>Text</type>
</CustomField>

peac_dev/force-app/main/default/objects/Payee__c/fields/City__c.field-meta.xml
<CustomField>
    <fullName>City__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>City</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

peac_dev/force-app/main/default/objects/Payee__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Contact address information overrides the Dealer if the address fields exists.</inlineHelpText>
    <label>Contact</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>(1 OR 2)</booleanFilter>
        <filterItems>
            <field>Contact.AccountId</field>
            <operation>equals</operation>
            <valueField>$Source.Dealer__c</valueField>
        </filterItems>
        <filterItems>
            <field>$Source.Dealer__c</field>
            <operation>equals</operation>
            <value></value>
        </filterItems>
        <infoMessage>The Contact should be related to the Dealer/Broker</infoMessage>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Payees</relationshipLabel>
    <relationshipName>Payees</relationshipName>
    <type>Lookup</type>
</CustomField>

peac_dev/force-app/main/default/objects/Payee__c/fields/Payee_Name__c.field-meta.xml
<CustomField>
    <fullName>Payee_Name__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Payee Name</label>
    <length>60</length>
    <type>Text</type>
</CustomField>

peac_dev/force-app/main/default/objects/Payee__c/fields/SL_Vendor_ID__c.field-meta.xml
<CustomField>
    <fullName>SL_Vendor_ID__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <externalId>true</externalId>
    <label>SL Vendor ID</label>
    <length>12</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

peac_dev/force-app/main/default/objects/Payee__c/fields/State__c.field-meta.xml
<CustomField>
    <fullName>State__c</fullName>
    <label>State</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>AB</fullName>
            </value>
            <value>
                <fullName>AK</fullName>
            </value>
            <value>
                <fullName>AL</fullName>
            </value>
            <value>
                <fullName>AR</fullName>
            </value>
            <value>
                <fullName>AUC</fullName>
            </value>
            <value>
                <fullName>AZ</fullName>
            </value>
            <value>
                <fullName>BC</fullName>
            </value>
            <value>
                <fullName>CA</fullName>
            </value>
            <value>
                <fullName>CO</fullName>
            </value>
            <value>
                <fullName>CT</fullName>
            </value>
            <value>
                <fullName>DC</fullName>
            </value>
            <value>
                <fullName>DE</fullName>
            </value>
            <value>
                <fullName>FL</fullName>
            </value>
            <value>
                <fullName>GA</fullName>
            </value>
            <value>
                <fullName>HI</fullName>
            </value>
            <value>
                <fullName>IA</fullName>
            </value>
            <value>
                <fullName>ID</fullName>
            </value>
            <value>
                <fullName>IL</fullName>
            </value>
            <value>
                <fullName>IN</fullName>
            </value>
            <value>
                <fullName>KS</fullName>
            </value>
            <value>
                <fullName>KY</fullName>
            </value>
            <value>
                <fullName>LA</fullName>
            </value>
            <value>
                <fullName>LB</fullName>
            </value>
            <value>
                <fullName>MA</fullName>
            </value>
            <value>
                <fullName>MB</fullName>
            </value>
            <value>
                <fullName>MD</fullName>
            </value>
            <value>
                <fullName>ME</fullName>
            </value>
            <value>
                <fullName>MI</fullName>
            </value>
            <value>
                <fullName>MN</fullName>
            </value>
            <value>
                <fullName>MO</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

peac_dev/force-app/main/default/objects/Payment__c/Payment__c.object-meta.xml
<CustomObject>
    <description>Payments to a Payee related to an opportunity</description>
    <label>Payment</label>
    <nameField>
        <displayFormat>PYMT-{0}</displayFormat>
        <label>Payment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

peac_dev/force-app/main/default/objects/Payment__c/fields/Less_UPS_Charge__c.field-meta.xml
<CustomField>
    <fullName>Less_UPS_Charge__c</fullName>
    <label>Less UPS Charge</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

peac_dev/force-app/main/default/objects/Payment__c/fields/Less_Wire_Fee__c.field-meta.xml
<CustomField>
    <fullName>Less_Wire_Fee__c</fullName>
    <label>Less Wire Fee</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

peac_dev/force-app/main/default/objects/Payment__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <inlineHelpText>Opportunity related to this payment</inlineHelpText>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Payments</relationshipLabel>
    <relationshipName>Payments</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

peac_dev/force-app/main/default/objects/Payment__c/fields/Payee__c.field-meta.xml
<CustomField>
    <fullName>Payee__c</fullName>
    <inlineHelpText>Payee related to this payment</inlineHelpText>
    <label>Payee</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 AND 2 AND 3</booleanFilter>
        <errorMessage>Value does not exist or does not match filter criteria or the Payee in Inactive</errorMessage>
        <filterItems>
            <field>Payee__c.SL_Vendor_ID__c</field>
            <operation>notEqual</operation>
            <value></value>
        </filterItems>
        <filterItems>
            <field>Payee__c.Active__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <filterItems>
            <field>Payee__c.Payee_Name__c</field>
            <operation>notContain</operation>
            <value>Do Not</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Payee__c</referenceTo>
    <relationshipLabel>Payments</relationshipLabel>
    <relationshipName>Payments</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

peac_dev/force-app/main/default/objects/Payment__c/fields/Payee_Name__c.field-meta.xml
<CustomField>
    <fullName>Payee_Name__c</fullName>
    <formula>Payee__r.Payee_Name__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Payee Name</label>
    <type>Text</type>
</CustomField>

peac_dev/force-app/main/default/objects/Payment__c/fields/Payment_Method__c.field-meta.xml
<CustomField>
    <fullName>Payment_Method__c</fullName>
    <label>Payment Method</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Wire</fullName>
            </value>
            <value>
                <fullName>ACH</fullName>
            </value>
            <value>
                <fullName>Check</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

peac_dev/force-app/main/default/objects/Variable_Payment__c/Variable_Payment__c.object-meta.xml
<CustomObject>
    <label>Variable Payment</label>
    <nameField>
        <displayFormat>VP-{0000}</displayFormat>
        <label>Variable Payments Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Variable Payments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

peac_dev/force-app/main/default/objects/Variable_Payment__c/fields/of_payments__c.field-meta.xml
<CustomField>
    <fullName>of_payments__c</fullName>
    <label># of payments</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

peac_dev/force-app/main/default/objects/Variable_Payment__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Variable Payments</relationshipLabel>
    <relationshipName>Variable_Payments</relationshipName>
    <type>Lookup</type>
</CustomField>

peac_dev/force-app/main/default/objects/Variable_Payment__c/fields/Payment_Amount__c.field-meta.xml
<CustomField>
    <fullName>Payment_Amount__c</fullName>
    <label>Payment Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

peac_dev/force-app/main/default/classes/TC_OpportunityTriggerHelperTest.cls
@isTest
public class TC_OpportunityTriggerHelperTest {
    
    @isTest public static void insertOppTest2 () {
        TC_OpportunityTriggerHelper testmtd = new TC_OpportunityTriggerHelper();
    }
    
    
    @testSetup 
    public static void setupBeneficialOwners () {
        Account acc = new Account (Name = 'testbeni', RecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('End User Account').getRecordTypeId(), Business_Phone__c = '1234567890');
        insert acc;
        
        Contact c = new Contact (AccountId = acc.Id, FirstName = 'test', LastName = 'testbeni', OtherStreet = 'test', OtherCity = 'test', OtherStateCode = 'MN', OtherPostalCode = '11111', Title = 'title', SSN__c = '111111111', BirthDate = Date.today (), Email = 'test@test.com');
        insert c;
        
        insert new Beneficial_Owner__c (Account__c = acc.Id, Contact__c = c.Id, Ownership_Percent__c = 50);

        Test.startTest();
        Id loanOppId = Schema.SObjectType.Opportunity.getRecordTypeInfosByName().get('Loan Opportunity').getRecordTypeId();
        Opportunity opp = new Opportunity (AccountId = acc.Id
                                           , StageName = 'Quote'
                                           , CloseDate = date.today () + 10
                                           , Name = 'test', RecordTypeId = loanOppId);

        
        insert opp;
        Test.stopTest();

    }
    
    @isTest public static void TestApproved(){
        Account acc = new Account (Name = 'testbeni', Account_Dealer_Status__c  = '1-time Need Profile Unused', RecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('End User Account').getRecordTypeId());
        Test.startTest();
        insert acc;
        Test.stopTest();
    }
    
    @isTest public static void expressOrtValidationTest() {
        Opportunity op = new Opportunity (Name = 'test'
                                         ,AccountId = [SELECT Id FROM Account WHERE Name = 'testbeni'][0].Id
                                         ,StageName='Quote'
                                         ,CloseDate = date.today()+15
                                         ,Primary_Source__c='LendingTree');
        Test.startTest();
        insert op;
        op.Primary_Source__c='Customer Inbound - Call';
       // op.Lessor__c =409;
        TC_OpportunityTriggerHelper.validationForManager(new Map<Id, Opportunity>{op.Id => op}, new List<Opportunity> {op});
        //update op;
        Test.stopTest();
    }
    
    @isTest public static void insertOppTest () {
        
        Opportunity opp = [SELECT Id FROM Opportunity LIMIT 1];

        Variable_Payment__c objVP = new Variable_Payment__c();
        objVP.Opportunity__c = opp.Id;
        objVP.Payment_Amount__c  = 100;
        objVP.of_payments__c = 2;
        Test.startTest();
        insert objVP;
        Test.stopTest();
        //update opp;

    }
/*
    @isTest public static void insertOppTest2 () {
        
        ORE__c objORE = new ORE__c();
        objORE.Bypass__c = true;
        insert objORE ;
        
        Opportunity testOpp = new Opportunity (AccountId = [SELECT Id FROM Account WHERE Name = 'testbeni'][0].Id
                               , StageName = 'Funding'
                               , CloseDate = date.today () + 10
                               , Name = 'test'
                               , Tax_ID__c = '123456789'
                               , Assign_To_CMS_User__c = [SELECT Id FROM User LIMIT 1][0].Id
                               , Business_Phone__c = '1234563333',
                                Credit_Stips_Completed_Date__c = date.today () +10 );
        insert testOpp;
        
        Payee__c payee = new Payee__c(Payee_Name__c = 'test', Address1__c = 'test', City__c = 'test', State__c ='MN', Email__c ='a@a.com', SL_Vendor_ID__c = 'je3loxm4s90f');
        insert payee;
        
        insert new Payment__c(Payee__c = payee.Id, Opportunity__c = testOpp.Id, Payment_Method__c = 'Check', Less_UPS_Charge__c = 1, Less_Wire_Fee__c = 2, Less_Titling_Fee__c = 3, Less_Delivery_Guarantee__c = 4, Plus_Points__c = 5);
        
        testOpp.StageName = 'Booking';
        update testOpp;
    }*/

    /*
    @isTest public static void insertOppTest3 () {

//
        TC_GenerateTaxMatrixCtrlTestUtil.generateCustomSettings();

        ORE__c ore = ORE__c.getOrgDefaults();
        ore.Bypass__c = true;
        upsert ore;

//        StaticResource sr = [SELECT Id, Body FROM StaticResource WHERE Name = 'SAL366JSONacc' LIMIT 1][0];
//        String body = sr.Body.toString();
        String body = TC_JSONTestRecordsUtil.SAL366JSONacc;
        Account acc = (Account) JSON.deserialize(body, Account.class);
        acc.Id = null;
        insert acc;

//        sr = [SELECT Id, Body FROM StaticResource WHERE Name = 'SAL366JSON' LIMIT 1][0];
//        body = sr.Body.toString();
        body = TC_JSONTestRecordsUtil.SAL366JSON;
        Opportunity opp = (Opportunity) JSON.deserialize(body, Opportunity.class);
        opp.AccountId = acc.Id;
        opp.Id = null;
        insert opp;

//        sr = [SELECT Id, Body FROM StaticResource WHERE Name = 'SAL366JSONdealAcc' LIMIT 1][0];
//        body = sr.Body.toString();
        body = TC_JSONTestRecordsUtil.SAL366JSONdealAcc;
        Account acc2 = (Account) JSON.deserialize(body, Account.class);
        acc2.Id = null;
        insert acc2;

//        sr = [SELECT Id, Body FROM StaticResource WHERE Name = 'SAL366JSONdlr' LIMIT 1][0];
//        body = sr.Body.toString();
        body = TC_JSONTestRecordsUtil.SAL366JSONdlr;
        Dealer__c d = (Dealer__c) JSON.deserialize(body, Dealer__c.class);
        d.Id = null;
        d.Opportunity__c = opp.Id;
        d.Dealer__c = acc2.Id;
        insert d;

        opp.StageName = 'Funding';
        update opp;

        Contact c = [SELECT Id FROM Contact WHERE LastName = 'testbeni' LIMIT 1][0];
        OpportunityContactRole cr = new OpportunityContactRole(OpportunityId = opp.Id, ContactId = c.Id, Role = 'Dealer Sales Rep');
        insert cr;

        opp.Ready_to_Doc__c = 'Yes';
        update opp;
    }*/
    
    /* Moved to TC_TestSetApprovalMergeFields Apex test class
    @IsTest
    static void testSetApprovalMergeFields() {
        Account account = new Account(Name = 'test account', Business_Phone__c = '1234567890');
        insert account;

        Contact contact = new Contact(
                FirstName = 'Joe',
                LastName = 'Smith',
                AccountId = account.Id
        );
        insert contact;
        
        Opportunity opportunity = new Opportunity(
                AccountId = account.Id,
                Name = 'testSetApprovalMergeFields',
                StageName = 'Decision',
                CloseDate = Date.today(),
                Application__c = '12345'
        );
        Test.startTest();
        insert opportunity;

        Guarantor__c guarantor = new Guarantor__c(
                Opportunity__c = opportunity.Id,
                Contact__c = contact.Id
        );
        insert guarantor;

        opportunity.Application_Status__c = 'Automatically Approved';
        update opportunity;
        Test.stopTest();
    }*/


}