peac_dev/force-app/main/default/objects/Contract_Asset__c/Contract_Asset__c.object-meta.xml
<CustomObject>
    <label>Contract Asset</label>
    <nameField>
        <displayFormat>CA-{0000}</displayFormat>
        <label>Contract Asset Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contract Assets</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

peac_dev/force-app/main/default/objects/Contract_Asset__c/fields/Asset_Code__c.field-meta.xml
<CustomField>
    <fullName>Asset_Code__c</fullName>
    <label>Asset Code</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>006.005</fullName>
                <label>Air Compressors</label>
            </value>
            <value>
                <fullName>900.001</fullName>
                <label>ATM</label>
            </value>
            <value>
                <fullName>013.006</fullName>
                <label>Emmissions Testing Equipm</label>
            </value>
            <value>
                <fullName>013.008</fullName>
                <label>Frame Machine</label>
            </value>
            <value>
                <fullName>013.010</fullName>
                <label>Tire Balancer</label>
            </value>
            <value>
                <fullName>013.001</fullName>
                <label>Air Compressors - 013.001</label>
            </value>
            <value>
                <fullName>013.003</fullName>
                <label>Key Trak</label>
            </value>
            <value>
                <fullName>013.000</fullName>
                <label>Automotive (General)</label>
            </value>
            <value>
                <fullName>013.002</fullName>
                <label>Auto Lifts</label>
            </value>
            <value>
                <fullName>013.004</fullName>
                <label>Waste Oil Heater</label>
            </value>
            <value>
                <fullName>013.005</fullName>
                <label>Automotive Diagnostic Mac</label>
            </value>
            <value>
                <fullName>013.011</fullName>
                <label>Paint Booth</label>
            </value>
            <value>
                <fullName>013.100</fullName>
                <label>Other Auto Equipment</label>
            </value>
            <value>
                <fullName>013.007</fullName>
                <label>Pipe Bender</label>
            </value>
            <value>
                <fullName>013.009</fullName>
                <label>Tire Changer</label>
            </value>
            <value>
                <fullName>045.000</fullName>
                <label>Broker</label>
            </value>
            <value>
                <fullName>008.001</fullName>
                <label>CCTV Security System</label>
            </value>
            <value>
                <fullName>006.000</fullName>
                <label>Commerce &amp; Indus (Gen)</label>
            </value>
            <value>
                <fullName>006.003</fullName>
                <label>Scales</label>
            </value>
            <value>
                <fullName>006.007</fullName>
                <label>Used Fork Lift</label>
            </value>
            <value>
                <fullName>006.100</fullName>
                <label>Other C&amp;I</label>
            </value>
            <value>
                <fullName>006.001</fullName>
                <label>Carpet Cutting Machine</label>
            </value>
            <value>
                <fullName>006.002</fullName>
                <label>Packaging Equipment</label>
            </value>
            <value>
                <fullName>006.004</fullName>
                <label>Paint Sprayers</label>
            </value>
            <value>
                <fullName>006.017</fullName>
                <label>Scissor Lifts</label>
            </value>
            <value>
                <fullName>006.010</fullName>
                <label>Furnace</label>
            </value>
            <value>
                <fullName>006.006</fullName>
                <label>Generator</label>
            </value>
            <value>
                <fullName>006.013</fullName>
                <label>Boiler</label>
            </value>
            <value>
                <fullName>006.015</fullName>
                <label>Machine Tool</label>
            </value>
            <value>
                <fullName>006.014</fullName>
                <label>Bailer</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

peac_dev/force-app/main/default/objects/Contract_Asset__c/fields/Insurance__c.field-meta.xml
<CustomField>
    <fullName>Insurance__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Insurance</label>
    <referenceTo>Insurance__c</referenceTo>
    <relationshipLabel>Contract Assets</relationshipLabel>
    <relationshipName>Contract_Assets</relationshipName>
    <type>Lookup</type>
</CustomField>

peac_dev/force-app/main/default/objects/Insurance__c/Insurance__c.object-meta.xml
<CustomObject>
    <label>Insurance</label>
    <nameField>
        <displayFormat>INS-{0000}</displayFormat>
        <label>Insurance Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Insurance</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

peac_dev/force-app/main/default/objects/Insurance__c/fields/Titled_Vehicles__c.field-meta.xml
<CustomField>
    <fullName>Titled_Vehicles__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Titled Vehicles</label>
    <type>Checkbox</type>
</CustomField>

peac_dev/force-app/main/default/classes/SL_InsuranceTVCheckBatch.cls
public class SL_InsuranceTVCheckBatch implements Database.Batchable<SObject>, Database.Stateful {
    List<String> allErrors = new List<String>();

    public Database.querylocator start(Database.BatchableContext BC){
        return Database.getQueryLocator('SELECT Titled_Vehicles__c, '
        + '(SELECT Id, Asset_Code__c FROM Contract_Assets__r '
        + 'WHERE Asset_Code__c != null AND Asset_Code__c LIKE \'%Titled_V%\') '
        + 'FROM Insurance__c');
    }
    public void execute(Database.BatchableContext BC, List<SObject> scope){
        List<Insurance__c> insurancesTochange = new List<Insurance__c>();
        for(sObject s : scope){
            Insurance__c insurance = (Insurance__c)s;
            Boolean hasTitledVehicle = insurance.Contract_Assets__r.size() > 0;
            if(insurance.Titled_Vehicles__c != hasTitledVehicle){
                insurance.Titled_Vehicles__c = hasTitledVehicle;
                insurancesTochange.add(insurance);
            }
        }
        if (insurancesTochange.size() > 0){
            List<List<SObject>> bigInsertList = SL_DPSharingRecalcBatch.splitDMLList(insurancesTochange);
            allErrors = SL_DPSharingRecalcBatch.bigUpsert(bigInsertList, false, allErrors);
        }
    }
    public void finish(Database.BatchableContext BC){
        if(allErrors.size() > 0){
            String serializedMap = String.join(allErrors, '. \r\n');
            MARLIN_IntegrationLog.addLog ('Insurance TV Check Batch', BC.getJobId(), 'Error', '', serializedMap.left(131071),
                'Error', 'Error encountered while update Insurance records described in the Response_Message__c field, Validation errors are expected though.');
            MARLIN_IntegrationLog.insertLogs();
            //System.enqueueJob(new SL_CollectionAssignmentQ('dl-salesforcesupport@peacsolutions.com', 'Error Summary shareObject: ' + shareObject, serializedMap));
        }
    }
}