peac_dev/force-app/main/default/objects/Rate__c/Rate__c.object-meta.xml
<CustomObject>
    <label>Rate</label>
    <nameField>
        <displayFormat>R-{0000}</displayFormat>
        <label>Rate Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Rates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

peac_dev/force-app/main/default/objects/Rate_Card_Column__c/Rate_Card_Column__c.object-meta.xml
<CustomObject>
    <label>Rate Card Column</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Rate Card Column Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Rate Card Columns</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

peac_dev/force-app/main/default/objects/Rate_Card_Column__c/fields/Rate_Card__c.field-meta.xml
<CustomField>
    <fullName>Rate_Card__c</fullName>
    <label>Rate Card</label>
    <referenceTo>RateCard__c</referenceTo>
    <relationshipLabel>Rate Card Columns</relationshipLabel>
    <relationshipName>Rate_Card_Columns</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

peac_dev/force-app/main/default/objects/Rate_Card_Column__c/fields/Residual__c.field-meta.xml
<CustomField>
    <fullName>Residual__c</fullName>
    <description>DP-153</description>
    <label>Residual</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

peac_dev/force-app/main/default/objects/Rate_Card_Rate__c/Rate_Card_Rate__c.object-meta.xml
<CustomObject>
    <label>Rate Card Rate</label>
    <nameField>
        <displayFormat>RCR-{0000}</displayFormat>
        <label>Rate Card Rate Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Rate Card Rates</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

peac_dev/force-app/main/default/objects/Rate_Card_Rate__c/fields/Rate__c.field-meta.xml
<CustomField>
    <fullName>Rate__c</fullName>
    <inlineHelpText>The Rate that is added to the Base Rate used for the transaction if it meets the column and row criteria.</inlineHelpText>
    <label>Rate</label>
    <precision>13</precision>
    <scale>10</scale>
    <type>Percent</type>
</CustomField>

peac_dev/force-app/main/default/objects/Rate_Card_Rate__c/fields/Rate_Card_Column__c.field-meta.xml
<CustomField>
    <fullName>Rate_Card_Column__c</fullName>
    <label>Rate Card Column</label>
    <referenceTo>Rate_Card_Column__c</referenceTo>
    <relationshipLabel>Rate Card Rates</relationshipLabel>
    <relationshipName>Rate_Card_Rates</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

peac_dev/force-app/main/default/objects/Rate_Card_Rate__c/fields/Rate_Card_Row__c.field-meta.xml
<CustomField>
    <fullName>Rate_Card_Row__c</fullName>
    <label>Rate Card Row</label>
    <referenceTo>Rate_Card_Row__c</referenceTo>
    <relationshipLabel>Rate Card Rates</relationshipLabel>
    <relationshipName>Rate_Card_Rates</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

peac_dev/force-app/main/default/objects/Rate_Card_Row__c/Rate_Card_Row__c.object-meta.xml
<CustomObject>
    <label>Rate Card Row</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Rate Card Row Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Rate Card Rows</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

peac_dev/force-app/main/default/objects/Rate_Card_Row__c/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <inlineHelpText>The order that the row should appear in the rate card rows. For ex, the first row would have a 1. This drives how the rate card matrix appears.</inlineHelpText>
    <label>Order</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

peac_dev/force-app/main/default/objects/Rate_Card_Row__c/fields/Rate_Card__c.field-meta.xml
<CustomField>
    <fullName>Rate_Card__c</fullName>
    <label>Rate Card</label>
    <referenceTo>RateCard__c</referenceTo>
    <relationshipLabel>Rate Card Rows</relationshipLabel>
    <relationshipName>Rate_Card_Rows</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

peac_dev/force-app/main/default/objects/RateCard__c/RateCard__c.object-meta.xml
<CustomObject>
    <label>Rate Card</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Rate Card Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Rate Cards</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

peac_dev/force-app/main/default/objects/RateCard__c/fields/Entry_Criteria__c.field-meta.xml
<CustomField>
    <fullName>Entry_Criteria__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>The set of conditions used to determine if the rate card is applicable to a transaction for opportunities.</inlineHelpText>
    <label>Opportunity Entry Criteria</label>
    <referenceTo>TCRE__Rule_Config__c</referenceTo>
    <relationshipLabel>Rate Cards</relationshipLabel>
    <relationshipName>Rate_Cards</relationshipName>
    <type>Lookup</type>
</CustomField>

peac_dev/force-app/main/default/classes/TC_RateCardCtrl.cls
public with sharing class TC_RateCardCtrl {
    
    @AuraEnabled
    public static List <Rate_Card_Row__c> getRows (String rateCardId) {
        System.debug ('getRows trying - ' + rateCardId);
        
        
        
        try {
            List <Rate_Card_Row__c> rateCardRows = retrieveRateCardRows (rateCardId);
            
            return rateCardRows;
        } catch (Exception ex) {
            System.debug ('Error : ' + ex.getMessage() + ' - ' + ex.getStacktraceString());
            throw new AuraHandledException ('Error : ' + ex.getMessage() + ' - ' + ex.getStacktraceString());
        }
    }
    
    
    
    @AuraEnabled
    public static List <Rate_Card_Column__c> getColumns (String rateCardId) {
        System.debug ('getColumns trying - ' + rateCardId);
        
        
        
        try {
            List <Rate_Card_Column__c> rateCardCols = retrieveRateCardCols (rateCardId);
            
            return rateCardCols;
        } catch (Exception ex) {
            System.debug ('Error : ' + ex.getMessage() + ' - ' + ex.getStacktraceString());
            throw new AuraHandledException ('Error : ' + ex.getMessage() + ' - ' + ex.getStacktraceString());
        }
    }
 
        
    @AuraEnabled
    public static List<Rate_Card_Column__c> saveRateCardValues (Id rateCardId, List <Rate_Card_Rate__c> rateList) {

        try {

            system.debug('rateCardId = ' + rateCardId);
            system.debug('rateList = ' + rateList);
            
            update rateList;      

            return retrieveRateCardCols(rateCardId);
            
        } catch (Exception ex) {
            System.debug ('Error : ' + ex.getMessage() + ' - ' + ex.getStacktraceString());
            throw new AuraHandledException ('Error : ' + ex.getMessage() + ' - ' + ex.getStacktraceString());
        }

    }
    
    
    
    private static List <Rate_Card_Row__c> retrieveRateCardRows (String rateCardId) {
        return new List <Rate_Card_Row__c> ([SELECT Id
                                             ,Name
                                             ,Order__c
                                             FROM Rate_Card_Row__c 
                                             WHERE Rate_Card__c = :rateCardId
                                             ORDER BY Order__c ASC]);
    }     
    private static List <Rate_Card_Column__c> retrieveRateCardCols (String rateCardId) {
        return new List <Rate_Card_Column__c> ([SELECT Id
                                                ,Name
                                                ,Order__c
                                                ,Residual__c
                                                ,(
                                                    SELECT Id, Rate__c, Rate_Card_Column__c, Rate_Card_Row__c
                                                    FROM Rate_Card_Rates__r
                                                    ORDER BY Rate_Card_Row__r.Order__c
                                                )
                                                FROM Rate_Card_Column__c
                                                WHERE Rate_Card__c = :rateCardId
                                                ORDER BY Order__c ASC]);
    }   
    
  @AuraEnabled
  public static String getConditionValue(String rateCardId, String value) {
    try {
      String conditionValue = null;
      List<TCRE__Rule_Condition__c> lstRuleCondition = [SELECT Id, TCRE__Value__c FROM TCRE__Rule_Condition__c 
                                                        WHERE TCRE__Value__c =:value AND TCRE__Rule_Config__c IN 
                                                          (SELECT Entry_Criteria__c FROM RateCard__c WHERE Id = :rateCardId)];
      if(lstRuleCondition.isEmpty()){
        return conditionValue;
      }

      conditionValue  = lstRuleCondition[0].TCRE__Value__c;
      return conditionValue;
    }catch (Exception ex) {
      System.debug ('Error : ' + ex.getMessage() + ' - ' + ex.getStacktraceString());
      throw new AuraHandledException ('Error : ' + ex.getMessage() + ' - ' + ex.getStacktraceString());
    }
  }
}