peac_dev/force-app/main/default/objects/Miscellaneous_Billable_Item__c/Miscellaneous_Billable_Item__c.object-meta.xml
<CustomObject>
    <label>Miscellaneous Billable Item</label>
    <nameField>
        <displayFormat>MB-{0}</displayFormat>
        <label>Miscellaneous Billable Item Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Miscellaneous Billable Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

peac_dev/force-app/main/default/objects/Miscellaneous_Billable_Item__c/fields/Billing_Cycle__c.field-meta.xml
<CustomField>
    <fullName>Billing_Cycle__c</fullName>
    <label>Billing Cycle</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Monthly</fullName>
                <default>true</default>
                <label>Monthly</label>
            </value>
            <value>
                <fullName>Variable</fullName>
            </value>
            <value>
                <fullName>Quarterly</fullName>
            </value>
            <value>
                <fullName>Annually</fullName>
            </value>
            <value>
                <fullName>Weekly</fullName>
            </value>
            <value>
                <fullName>Daily</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

peac_dev/force-app/main/default/objects/Miscellaneous_Billable_Item__c/fields/CB_Disp__c.field-meta.xml
<CustomField>
    <fullName>CB_Disp__c</fullName>
    <defaultValue>true</defaultValue>
    <label>CB/Disp</label>
    <type>Checkbox</type>
</CustomField>

peac_dev/force-app/main/default/objects/Miscellaneous_Billable_Item__c/fields/Final_Payment_Date__c.field-meta.xml
<CustomField>
    <fullName>Final_Payment_Date__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Final Payment Date</label>
    <type>Date</type>
</CustomField>

peac_dev/force-app/main/default/objects/Miscellaneous_Billable_Item__c/fields/First_Payment_Date__c.field-meta.xml
<CustomField>
    <fullName>First_Payment_Date__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>First Payment Date</label>
    <type>Date</type>
</CustomField>

peac_dev/force-app/main/default/objects/Miscellaneous_Billable_Item__c/fields/Future_Bill_Misc_Type__c.field-meta.xml
<CustomField>
    <fullName>Future_Bill_Misc_Type__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Future Bill Misc Type</label>
    <type>Checkbox</type>
</CustomField>

peac_dev/force-app/main/default/objects/Miscellaneous_Billable_Item__c/fields/Included_in_Rental__c.field-meta.xml
<CustomField>
    <fullName>Included_in_Rental__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Included in Rental?</label>
    <type>Checkbox</type>
</CustomField>

peac_dev/force-app/main/default/objects/Miscellaneous_Billable_Item__c/fields/Misc_GL_Code__c.field-meta.xml
<CustomField>
    <fullName>Misc_GL_Code__c</fullName>
    <label>Misc GL Code</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>0000 - NOT ON FILE</fullName>
            </value>
            <value>
                <fullName>0001 - Interim Rent</fullName>
            </value>
            <value>
                <fullName>0002 - Upfront Tax</fullName>
            </value>
            <value>
                <fullName>0003 - OneTime Documentation Fee</fullName>
            </value>
            <value>
                <fullName>0004 - Ending Deposit</fullName>
            </value>
            <value>
                <fullName>0005 - Security Deposit</fullName>
            </value>
            <value>
                <fullName>0006 - Rental on Disposed Accts</fullName>
            </value>
            <value>
                <fullName>0007 - 90-day same as cash disc.</fullName>
            </value>
            <value>
                <fullName>0008 - CLOSING FEE</fullName>
            </value>
            <value>
                <fullName>0009 - Returned Check Fee</fullName>
            </value>
            <value>
                <fullName>0010 - COLLECTION / REPO FEE</fullName>
            </value>
            <value>
                <fullName>0011 - Insurance Fee</fullName>
            </value>
            <value>
                <fullName>0012 - Legal Fee</fullName>
            </value>
            <value>
                <fullName>0013 - Loss Reserve</fullName>
            </value>
            <value>
                <fullName>0014 - Funding Difference</fullName>
            </value>
            <value>
                <fullName>0015 - Recovery</fullName>
            </value>
            <value>
                <fullName>0016 - Equipment Sale</fullName>
            </value>
            <value>
                <fullName>0017 - Service Contract</fullName>
            </value>
            <value>
                <fullName>0018 - Property Tax</fullName>
            </value>
            <value>
                <fullName>0019 - Fla Doc Stamp Tax</fullName>
            </value>
            <value>
                <fullName>0020 - Renewal Rentals</fullName>
            </value>
            <value>
                <fullName>0021 - Sec Deposit Refund</fullName>
            </value>
            <value>
                <fullName>0022 - Residual Due Vendor</fullName>
            </value>
            <value>
                <fullName>0023 - Insurance Misc</fullName>
            </value>
            <value>
                <fullName>0024 - Hasselblad</fullName>
            </value>
            <value>
                <fullName>0025 - Inventory Equipment Sale</fullName>
            </value>
            <value>
                <fullName>0026 - Payment after Disposition</fullName>
            </value>
            <value>
                <fullName>0027 - Damage/Return Fee</fullName>
            </value>
            <value>
                <fullName>0028 - End of Term Recovery</fullName>
            </value>
            <value>
                <fullName>0029 - Restructure Fee</fullName>
            </value>
            <value>
                <fullName>0090 - Convenience Fee</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

peac_dev/force-app/main/default/objects/Miscellaneous_Billable_Item__c/fields/Misc_Item_Description__c.field-meta.xml
<CustomField>
    <fullName>Misc_Item_Description__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Misc Item Description</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

peac_dev/force-app/main/default/objects/Miscellaneous_Billable_Item__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <inlineHelpText>Opportunity related to this Misc Billable</inlineHelpText>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Misc Billables</relationshipLabel>
    <relationshipName>Miscellaneous_Billable_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

peac_dev/force-app/main/default/objects/Miscellaneous_Billable_Item__c/fields/Pay_Code__c.field-meta.xml
<CustomField>
    <fullName>Pay_Code__c</fullName>
    <label>Pay Code</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>0</fullName>
                <default>true</default>
                <label>Don&apos;t Pay Dealer</label>
            </value>
            <value>
                <fullName>1</fullName>
                <label>Pay Dealer</label>
            </value>
            <value>
                <fullName>2</fullName>
                <label>Service Dealer</label>
            </value>
            <value>
                <fullName>3</fullName>
                <label>Pay Customer</label>
            </value>
            <value>
                <fullName>4</fullName>
                <label>Service Multiple Dealers</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

peac_dev/force-app/main/default/classes/SL_MiscBillableItemTriggerHandlerTest.cls
@isTest
public with sharing class SL_MiscBillableItemTriggerHandlerTest {
    @isTest
    static void miscInvoiceActionsFormerPB() {
        SL_SCTestData.createAccountAndContracts(1,1);
        SL_SCTestData.createOpportunitiesAndAssets(SL_SCTestData.testAccounts[0].Id, 1, 1);
        Opportunity opp = SL_SCTestData.testOpportunities[0];
        Date firstPaymentDate = Date.newInstance(Date.today().year(), Date.today().addMonths(1).month(), 1);
        String cycle = 'Monthly';
        opp.First_Payment_Date__c = firstPaymentDate;
        opp.Payment_Frequency__c = cycle;
        update opp;
        Test.startTest();
        Miscellaneous_Billable_Item__c miscBillableItem = new Miscellaneous_Billable_Item__c(Opportunity__c = opp.Id,
            Misc_GL_Code__c = '0000 - NOT ON FILE');
        insert miscBillableItem;
        miscBillableItem.Misc_GL_Code__c = '0001 - Interim Rent';
        update miscBillableItem;
        // SAL-5897 Misael Romero
        Miscellaneous_Billable_Item__c miscBillableItem2 = new Miscellaneous_Billable_Item__c(Opportunity__c = opp.Id,
            Misc_GL_Code__c = '0017 - Service Contract', Final_Payment_Date__c = Date.today(), Amount__c = -1);
        insert miscBillableItem2;
        List<Miscellaneous_Billable_Item__c> mbisAfter = [SELECT Id, Misc_Item_Description__c, CB_Disp__c, Future_Bill_Misc_Type__c,
            Included_in_Rental__c, Pay_Code__c, Due_Date__c, First_Payment_Date__c, Billing_Cycle__c, Final_Payment_Date__c
            FROM Miscellaneous_Billable_Item__c];
        System.Assert.areEqual('Service Contract', mbisAfter[1].Misc_Item_Description__c, 'In MiscBillableDefaultRulesFormerPB description is taken from GL code');
        System.Assert.areEqual(true, mbisAfter[1].Future_Bill_Misc_Type__c, 'In MiscBillableDefaultRulesFormerPB future, cb/disp and include in rental are set to true');
        System.Assert.areEqual(firstPaymentDate, mbisAfter[1].Due_Date__c, 'In MiscBillableDefaultRulesFormerPB due date is taken from opp first Payment Date');
        System.Assert.areEqual(firstPaymentDate, mbisAfter[1].First_Payment_Date__c, 'In MiscBillableDefaultRulesFormerPB first payment date is taken from opp');
        System.Assert.areEqual(cycle, mbisAfter[1].Billing_Cycle__c, 'In MiscBillableDefaultRulesFormerPB billing cycle is taken from opp payment frequency');
        System.Assert.areEqual(null, mbisAfter[1].Final_Payment_Date__c, 'In MiscBillableDefaultRulesFormerPB final payment date is nullified if amount is negative?');
        // SAL-5897 Misael Romero
        System.Assert.areEqual('1', mbisAfter[1].Pay_Code__c, 'In MiscBillableDefaultRulesFormerPB paycode is set to 1 for specific GL Codes');
        System.Assert.areEqual(true, mbisAfter[1].Included_in_Rental__c, 'In MiscBillableDefaultRulesFormerPB Include in Rental is set according to the Misc Coding Matrix');
        miscBillableItem2.Misc_GL_Code__c = '0090 - Convenience Fee';
        update miscBillableItem2;
        mbisAfter = [SELECT Id, Pay_Code__c, Included_in_Rental__c
            FROM Miscellaneous_Billable_Item__c];
        System.Assert.areEqual('0', mbisAfter[1].Pay_Code__c, 'In MiscBillableDefaultRulesFormerPB paycode is set to 0 for specific GL Codes');
        System.Assert.areEqual(false, mbisAfter[1].Included_in_Rental__c, 'In MiscBillableDefaultRulesFormerPB Include in Rental is set according to the Misc Coding Matrix');
        Test.stopTest();
        
    }
}