peac_dev/force-app/main/default/objects/Miscellaneous_Billable_Item__c/Miscellaneous_Billable_Item__c.object-meta.xml
<CustomObject>
    <label>Miscellaneous Billable Item</label>
    <nameField>
        <displayFormat>MB-{0}</displayFormat>
        <label>Miscellaneous Billable Item Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Miscellaneous Billable Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

peac_dev/force-app/main/default/objects/Miscellaneous_Billable_Item__c/fields/Billing_Cycle__c.field-meta.xml
<CustomField>
    <fullName>Billing_Cycle__c</fullName>
    <label>Billing Cycle</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Monthly</fullName>
                <default>true</default>
                <label>Monthly</label>
            </value>
            <value>
                <fullName>Variable</fullName>
            </value>
            <value>
                <fullName>Quarterly</fullName>
            </value>
            <value>
                <fullName>Annually</fullName>
            </value>
            <value>
                <fullName>Weekly</fullName>
            </value>
            <value>
                <fullName>Daily</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

peac_dev/force-app/main/default/objects/Miscellaneous_Billable_Item__c/fields/First_Payment_Date__c.field-meta.xml
<CustomField>
    <fullName>First_Payment_Date__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>First Payment Date</label>
    <type>Date</type>
</CustomField>

peac_dev/force-app/main/default/objects/Miscellaneous_Billable_Item__c/fields/Generated_Code__c.field-meta.xml
<CustomField>
    <fullName>Generated_Code__c</fullName>
    <description>SAL-5293</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Generated Code</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

peac_dev/force-app/main/default/objects/Miscellaneous_Billable_Item__c/fields/Misc_GL_Code__c.field-meta.xml
<CustomField>
    <fullName>Misc_GL_Code__c</fullName>
    <label>Misc GL Code</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>0000 - NOT ON FILE</fullName>
            </value>
            <value>
                <fullName>0001 - Interim Rent</fullName>
            </value>
            <value>
                <fullName>0002 - Upfront Tax</fullName>
            </value>
            <value>
                <fullName>0003 - OneTime Documentation Fee</fullName>
            </value>
            <value>
                <fullName>0004 - Ending Deposit</fullName>
            </value>
            <value>
                <fullName>0005 - Security Deposit</fullName>
            </value>
            <value>
                <fullName>0006 - Rental on Disposed Accts</fullName>
            </value>
            <value>
                <fullName>0007 - 90-day same as cash disc.</fullName>
            </value>
            <value>
                <fullName>0008 - CLOSING FEE</fullName>
            </value>
            <value>
                <fullName>0009 - Returned Check Fee</fullName>
            </value>
            <value>
                <fullName>0010 - COLLECTION / REPO FEE</fullName>
            </value>
            <value>
                <fullName>0011 - Insurance Fee</fullName>
            </value>
            <value>
                <fullName>0012 - Legal Fee</fullName>
            </value>
            <value>
                <fullName>0013 - Loss Reserve</fullName>
            </value>
            <value>
                <fullName>0014 - Funding Difference</fullName>
            </value>
            <value>
                <fullName>0015 - Recovery</fullName>
            </value>
            <value>
                <fullName>0016 - Equipment Sale</fullName>
            </value>
            <value>
                <fullName>0017 - Service Contract</fullName>
            </value>
            <value>
                <fullName>0018 - Property Tax</fullName>
            </value>
            <value>
                <fullName>0019 - Fla Doc Stamp Tax</fullName>
            </value>
            <value>
                <fullName>0020 - Renewal Rentals</fullName>
            </value>
            <value>
                <fullName>0021 - Sec Deposit Refund</fullName>
            </value>
            <value>
                <fullName>0022 - Residual Due Vendor</fullName>
            </value>
            <value>
                <fullName>0023 - Insurance Misc</fullName>
            </value>
            <value>
                <fullName>0024 - Hasselblad</fullName>
            </value>
            <value>
                <fullName>0025 - Inventory Equipment Sale</fullName>
            </value>
            <value>
                <fullName>0026 - Payment after Disposition</fullName>
            </value>
            <value>
                <fullName>0027 - Damage/Return Fee</fullName>
            </value>
            <value>
                <fullName>0028 - End of Term Recovery</fullName>
            </value>
            <value>
                <fullName>0029 - Restructure Fee</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

peac_dev/force-app/main/default/objects/Miscellaneous_Billable_Item__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <inlineHelpText>Opportunity related to this Misc Billable</inlineHelpText>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Misc Billables</relationshipLabel>
    <relationshipName>Miscellaneous_Billable_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

peac_dev/force-app/main/default/classes/TC_AutoCreateMiscBillableItems.cls
public class TC_AutoCreateMiscBillableItems {
    public static void autoCreateMiscBillableItems(Opportunity opp, Set<Id> oppsMovedToBooking, Map<Id, List<Miscellaneous_Billable_Item__c>> miscBillableItems,
    List<Miscellaneous_Billable_Item__c> miscBillablesToInsert) {
        // SAL-5293 Misael Romero
        String glCode = '0017';
        if(oppsMovedToBooking.contains(opp.Id)){
            Map<String, Miscellaneous_Billable_Item__c> mbisByGeneratedCode = new Map<String, Miscellaneous_Billable_Item__c>();
            for(Miscellaneous_Billable_Item__c mbi :miscBillableItems.get(opp.Id)){
                if(mbi.Generated_Code__c != null){
                    mbisByGeneratedCode.put(mbi.Generated_Code__c, mbi);
                }
            }       
            for(Integer i = 1; i <= 7; i++) {
                String APIName = 'Year_' + String.valueOf(i) + '_Pass_Thru_Fee__c';
                if(opp.get(APIName) != null) {
                    Decimal decimalAmount = Decimal.valueOf(String.valueOf(opp.get(APIName)));
                    if(decimalAmount > 0 && !mbisByGeneratedCode.containsKey(glCode + APIName)) {
                        Miscellaneous_Billable_Item__c newMiscBill = new Miscellaneous_Billable_Item__c(Opportunity__c = opp.Id);
                        newMiscBill.Misc_GL_Code__c = '0017 - Service Contract';
                        newMiscBill.Amount__c = decimalAmount;
                        //                        newMiscBill.Billing_Cycle__c = opp.Billing_Cycle__c; removed for SAL-868
                        newMiscBill.Generated_Code__c = glCode + APIName;
                        miscBillablesToInsert.add(newMiscBill);
                    }
                }
            }
            if(miscBillablesToInsert.size()  == 1 && mbisByGeneratedCode.keySet().size() == 0){
                miscBillablesToInsert[0].First_Payment_Date__c = opp.First_Payment_Date__c;
            }
       }
   }

//    public static void autoCreateMiscBillableItems(Map<Id, Opportunity> oldMap, Map<Id, Opportunity> newMap){

//    }
}