peac_dev/force-app/main/default/objects/County__c/County__c.object-meta.xml
<CustomObject>
    <label>County</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>County</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Counties</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

peac_dev/force-app/main/default/objects/County__c/fields/State__c.field-meta.xml
<CustomField>
    <fullName>State__c</fullName>
    <label>State</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>State_Code</valueSetName>
    </valueSet>
</CustomField>

peac_dev/force-app/main/default/objects/Rate__c/Rate__c.object-meta.xml
<CustomObject>
    <label>Rate</label>
    <nameField>
        <displayFormat>R-{0000}</displayFormat>
        <label>Rate Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Rates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

peac_dev/force-app/main/default/objects/Rate__c/fields/City__c.field-meta.xml
<CustomField>
    <fullName>City__c</fullName>
    <description>The city where the business is located.</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>The city where the business is located.</inlineHelpText>
    <label>City</label>
    <length>64</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

peac_dev/force-app/main/default/objects/Rate__c/fields/City_Tax_Rate__c.field-meta.xml
<CustomField>
    <fullName>City_Tax_Rate__c</fullName>
    <description>Field that stores city tax rate.</description>
    <inlineHelpText>Enter city tax rate.</inlineHelpText>
    <label>City Tax Rate</label>
    <precision>8</precision>
    <required>true</required>
    <scale>3</scale>
    <type>Percent</type>
</CustomField>

peac_dev/force-app/main/default/objects/Rate__c/fields/City_Transit_Tax_Rate__c.field-meta.xml
<CustomField>
    <fullName>City_Transit_Tax_Rate__c</fullName>
    <description>Field that stores city transit tax rate.</description>
    <inlineHelpText>Enter city transit tax rate.</inlineHelpText>
    <label>City Transit Tax Rate</label>
    <precision>8</precision>
    <required>true</required>
    <scale>3</scale>
    <type>Percent</type>
</CustomField>

peac_dev/force-app/main/default/objects/Rate__c/fields/County__c.field-meta.xml
<CustomField>
    <fullName>County__c</fullName>
    <description>The county the business is located in.</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>The county the business is located in.</inlineHelpText>
    <label>County</label>
    <length>64</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

peac_dev/force-app/main/default/objects/Rate__c/fields/County_Code__c.field-meta.xml
<CustomField>
    <fullName>County_Code__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>County Code</label>
    <length>16</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

peac_dev/force-app/main/default/objects/Rate__c/fields/County_Tax_Rate__c.field-meta.xml
<CustomField>
    <fullName>County_Tax_Rate__c</fullName>
    <description>Field that stores county tax rate.</description>
    <inlineHelpText>Enter county tax rate.</inlineHelpText>
    <label>County Tax Rate</label>
    <precision>8</precision>
    <required>true</required>
    <scale>3</scale>
    <type>Percent</type>
</CustomField>

peac_dev/force-app/main/default/objects/Rate__c/fields/County_Transit_Tax_Rate__c.field-meta.xml
<CustomField>
    <fullName>County_Transit_Tax_Rate__c</fullName>
    <description>Field that stores county transit tax rate</description>
    <inlineHelpText>Enter county transit tax rate.</inlineHelpText>
    <label>County Transit Tax Rate</label>
    <precision>8</precision>
    <required>true</required>
    <scale>3</scale>
    <type>Percent</type>
</CustomField>

peac_dev/force-app/main/default/objects/Rate__c/fields/Rate_Code__c.field-meta.xml
<CustomField>
    <fullName>Rate_Code__c</fullName>
    <description>Field that store the code of the tax type.</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Enter the tax type code.</inlineHelpText>
    <label>Rate Code</label>
    <length>16</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

peac_dev/force-app/main/default/objects/Rate__c/fields/State__c.field-meta.xml
<CustomField>
    <fullName>State__c</fullName>
    <description>State your business is located in.</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>State your business is located in.</inlineHelpText>
    <label>State</label>
    <length>64</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

peac_dev/force-app/main/default/objects/Rate__c/fields/State_Code__c.field-meta.xml
<CustomField>
    <fullName>State_Code__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>State Code</label>
    <length>16</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

peac_dev/force-app/main/default/objects/Rate__c/fields/State_Tax_Rate__c.field-meta.xml
<CustomField>
    <fullName>State_Tax_Rate__c</fullName>
    <description>Field that stores state tax rate.</description>
    <inlineHelpText>Enter state tax rate.</inlineHelpText>
    <label>State Tax Rate</label>
    <precision>8</precision>
    <required>true</required>
    <scale>3</scale>
    <type>Percent</type>
</CustomField>

peac_dev/force-app/main/default/objects/Tax_Rule__c/Tax_Rule__c.object-meta.xml
<CustomObject>
    <label>Tax Rule</label>
    <nameField>
        <displayFormat>TR-{0000}</displayFormat>
        <label>Tax Rule Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Tax Rules</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

peac_dev/force-app/main/default/objects/Tax_Rule__c/fields/City__c.field-meta.xml
<CustomField>
    <fullName>City__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>The city that the tax rule is applicable to (if any). This is not required and is informational only. If a rule is applicable to a certain city(s) that should be handled in the Rule Conditions associated with this Tax Rule.</inlineHelpText>
    <label>City</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

peac_dev/force-app/main/default/objects/Tax_Rule__c/fields/State__c.field-meta.xml
<CustomField>
    <fullName>State__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>The state that the tax rule is applicable to (if any). This is not required and is informational only. If a rule is applicable to a certain state(s) that should be handled in the Rule Conditions associated with this Tax Rule.</inlineHelpText>
    <label>State</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

peac_dev/force-app/main/default/objects/Tax_Rules_Settings__c/Tax_Rules_Settings__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Tax Rules Settings</label>
</CustomObject>

peac_dev/force-app/main/default/objects/Tax_Rules_Settings__c/fields/City_Tax_Rate_Field__c.field-meta.xml
<CustomField>
    <fullName>City_Tax_Rate_Field__c</fullName>
    <defaultValue>&quot;TC_TAX__City_Tax_Rate__c&quot;</defaultValue>
    <encryptionScheme>None</encryptionScheme>
    <label>City Tax Rate Field</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

peac_dev/force-app/main/default/objects/Tax_Rules_Settings__c/fields/County_Tax_Rate_Field__c.field-meta.xml
<CustomField>
    <fullName>County_Tax_Rate_Field__c</fullName>
    <defaultValue>&quot;TC_TAX__County_Tax_Rate__c&quot;</defaultValue>
    <encryptionScheme>None</encryptionScheme>
    <label>County Tax Rate Field</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

peac_dev/force-app/main/default/objects/Tax_Rules_Settings__c/fields/Parent_Generate_Tax_Matrix_Message_Field__c.field-meta.xml
<CustomField>
    <fullName>Parent_Generate_Tax_Matrix_Message_Field__c</fullName>
    <defaultValue>&quot;TC_TAX__Generate_Tax_Matrix_Message_Long__c&quot;</defaultValue>
    <encryptionScheme>None</encryptionScheme>
    <label>Parent Generate Tax Matrix Message Field</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

peac_dev/force-app/main/default/objects/Tax_Rules_Settings__c/fields/Parent_Object__c.field-meta.xml
<CustomField>
    <fullName>Parent_Object__c</fullName>
    <defaultValue>&quot;Opportunity&quot;</defaultValue>
    <encryptionScheme>None</encryptionScheme>
    <label>Parent Object</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

peac_dev/force-app/main/default/objects/Tax_Rules_Settings__c/fields/Parent_Tax_Calculation_Begin_Field__c.field-meta.xml
<CustomField>
    <fullName>Parent_Tax_Calculation_Begin_Field__c</fullName>
    <defaultValue>&quot;TC_TAX__Last_Tax_Calculation_Begin__c&quot;</defaultValue>
    <encryptionScheme>None</encryptionScheme>
    <label>Parent Tax Calculation Begin Field</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

peac_dev/force-app/main/default/objects/Tax_Rules_Settings__c/fields/Parent_Tax_Calculation_Complete_Field__c.field-meta.xml
<CustomField>
    <fullName>Parent_Tax_Calculation_Complete_Field__c</fullName>
    <defaultValue>&quot;TC_TAX__Last_Tax_Calculation_Complete__c&quot;</defaultValue>
    <encryptionScheme>None</encryptionScheme>
    <label>Parent Tax Calculation Complete Field</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

peac_dev/force-app/main/default/objects/Tax_Rules_Settings__c/fields/Parent_Tax_Calculation_Error_Field__c.field-meta.xml
<CustomField>
    <fullName>Parent_Tax_Calculation_Error_Field__c</fullName>
    <defaultValue>&quot;TC_TAX__Last_Tax_Calculation_Error_Details__c&quot;</defaultValue>
    <encryptionScheme>None</encryptionScheme>
    <label>Parent Tax Calculation Error Field</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

peac_dev/force-app/main/default/objects/Tax_Rules_Settings__c/fields/Parent_Tax_Calculation_In_Progress_Field__c.field-meta.xml
<CustomField>
    <fullName>Parent_Tax_Calculation_In_Progress_Field__c</fullName>
    <defaultValue>&quot;TC_TAX__Is_Tax_Calculation_In_Progress__c&quot;</defaultValue>
    <encryptionScheme>None</encryptionScheme>
    <label>Parent Tax Calculation In Progress Field</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

peac_dev/force-app/main/default/objects/Tax_Rules_Settings__c/fields/Parent_Tax_Calculation_Successful_Field__c.field-meta.xml
<CustomField>
    <fullName>Parent_Tax_Calculation_Successful_Field__c</fullName>
    <defaultValue>&quot;TC_TAX__Last_Tax_Calculation_Successful__c&quot;</defaultValue>
    <encryptionScheme>None</encryptionScheme>
    <label>Parent Tax Calculation Successful Field</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

peac_dev/force-app/main/default/objects/Tax_Rules_Settings__c/fields/Rate_City_Field__c.field-meta.xml
<CustomField>
    <fullName>Rate_City_Field__c</fullName>
    <defaultValue>&quot;TC_TAX__City__c&quot;</defaultValue>
    <encryptionScheme>None</encryptionScheme>
    <label>Rate City Field</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

peac_dev/force-app/main/default/objects/Tax_Rules_Settings__c/fields/Rate_Code_Field__c.field-meta.xml
<CustomField>
    <fullName>Rate_Code_Field__c</fullName>
    <defaultValue>&quot;TC_TAX__Rate_Code__c&quot;</defaultValue>
    <encryptionScheme>None</encryptionScheme>
    <label>Rate Code Field</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

peac_dev/force-app/main/default/objects/Tax_Rules_Settings__c/fields/Rate_County_Field__c.field-meta.xml
<CustomField>
    <fullName>Rate_County_Field__c</fullName>
    <defaultValue>&quot;TC_TAX__County__c&quot;</defaultValue>
    <encryptionScheme>None</encryptionScheme>
    <label>Rate County Field</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

peac_dev/force-app/main/default/objects/Tax_Rules_Settings__c/fields/Rate_Object__c.field-meta.xml
<CustomField>
    <fullName>Rate_Object__c</fullName>
    <defaultValue>&quot;TC_TAX__Rate__c&quot;</defaultValue>
    <encryptionScheme>None</encryptionScheme>
    <label>Rate Object</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

peac_dev/force-app/main/default/objects/Tax_Rules_Settings__c/fields/Rate_State_Field__c.field-meta.xml
<CustomField>
    <fullName>Rate_State_Field__c</fullName>
    <defaultValue>&quot;TC_TAX__State__c&quot;</defaultValue>
    <encryptionScheme>None</encryptionScheme>
    <label>Rate State Field</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

peac_dev/force-app/main/default/objects/Tax_Rules_Settings__c/fields/State_Tax_Rate_Field__c.field-meta.xml
<CustomField>
    <fullName>State_Tax_Rate_Field__c</fullName>
    <defaultValue>&quot;TC_TAX__State_Tax_Rate__c&quot;</defaultValue>
    <encryptionScheme>None</encryptionScheme>
    <label>State Tax Rate Field</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

peac_dev/force-app/main/default/objects/Tax_Rules_Settings__c/fields/Tax_Calculation_Completion_Alert_Seconds__c.field-meta.xml
<CustomField>
    <fullName>Tax_Calculation_Completion_Alert_Seconds__c</fullName>
    <defaultValue>90</defaultValue>
    <label>Tax Calculation Completion Alert Seconds</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

peac_dev/force-app/main/default/objects/Tax_Rules_Settings__c/fields/Tax_Parent_Object_Field__c.field-meta.xml
<CustomField>
    <fullName>Tax_Parent_Object_Field__c</fullName>
    <defaultValue>&quot;TC_TAX__Opportunity__c&quot;</defaultValue>
    <encryptionScheme>None</encryptionScheme>
    <label>Tax Parent Object Field</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

peac_dev/force-app/main/default/objects/Tax_Rules_Settings__c/fields/TCity_Tax_Rate_Field__c.field-meta.xml
<CustomField>
    <fullName>TCity_Tax_Rate_Field__c</fullName>
    <defaultValue>&quot;TC_TAX__City_Transit_Tax_Rate__c&quot;</defaultValue>
    <encryptionScheme>None</encryptionScheme>
    <label>TCity Tax Rate Field</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

peac_dev/force-app/main/default/objects/Tax_Rules_Settings__c/fields/TCounty_Tax_Rate_Field__c.field-meta.xml
<CustomField>
    <fullName>TCounty_Tax_Rate_Field__c</fullName>
    <defaultValue>&quot;TC_TAX__County_Transit_Tax_Rate__c&quot;</defaultValue>
    <encryptionScheme>None</encryptionScheme>
    <label>TCounty Tax Rate Field</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

peac_dev/force-app/main/default/classes/TaxRulesTest.cls
@isTest
public class TaxRulesTest {
    @isTest
    static void test() {
        Tax_Rules_Settings__c settings = new Tax_Rules_Settings__c();
        settings.Parent_Object__c = 'Opportunity';
        settings.Rate_Object__c = 'Rate__c';
        settings.Rate_State_Field__c = 'State__c';
        settings.Rate_County_Field__c = 'County__c';
        settings.Rate_City_Field__c = 'City__c';
        settings.Rate_Code_Field__c = 'Rate_Code__c';
        settings.State_Tax_Rate_Field__c = 'State_Tax_Rate__c';
        settings.County_Tax_Rate_Field__c = 'County_Tax_Rate__c';
        settings.TCounty_Tax_Rate_Field__c = 'County_Transit_Tax_Rate__c';
        settings.City_Tax_Rate_Field__c = 'City_Tax_Rate__c';
        settings.TCity_Tax_Rate_Field__c = 'City_Transit_Tax_Rate__c';
        settings.Tax_Parent_Object_Field__c = 'Opportunity__c';
        settings.Parent_Generate_Tax_Matrix_Message_Field__c = 'Description';
        settings.Parent_Tax_Calculation_Begin_Field__c = 'Last_Tax_Calculation_Begin__c';
        settings.Parent_Tax_Calculation_Complete_Field__c = 'Last_Tax_Calculation_Complete__c';
        settings.Parent_Tax_Calculation_Successful_Field__c = 'Last_Tax_Calculation_Successful__c';
        settings.Parent_Tax_Calculation_Error_Field__c = 'Last_Tax_Calculation_Error_Details__c';
        settings.Parent_Tax_Calculation_In_Progress_Field__c = 'Is_Tax_Calculation_In_Progress__c';
        settings.Tax_Calculation_Completion_Alert_Seconds__c = 90;
        insert settings;
        
        Rate__c rate = new Rate__c();
        rate.State__c = 'MN';
        rate.County__c = 'WASHINGTON';
        rate.City__c = 'WOODBURY';
        rate.State_Code__c = '24';
        rate.County_Code__c = '163';
        rate.City_Code__c = '1740';
        rate.Rate_Code__c = '001';
        rate.State_Tax_Rate__c = 0.01;
        rate.County_Tax_Rate__c = 0.01;
        rate.County_Transit_Tax_Rate__c = 0.01;
        rate.City_Tax_Rate__c = 0.01;
        rate.City_Transit_Tax_Rate__c = 0.01;
        insert rate;
        
        TCRE__Rule_Config__c conf = new TCRE__Rule_Config__c();
        conf.TCRE__SObject_Name__c = 'Opportunity';
        conf.TCRE__Priority__c = 1;
        insert conf;
        
        TCRE__Rule_Condition__c cond1 = new TCRE__Rule_Condition__c();
        cond1.TCRE__Field_Name__c = 'StageName';
        cond1.TCRE__Operator__c = '=';
        cond1.TCRE__Value__c = 'test';
        cond1.TCRE__Rule_Config__c = conf.Id;
        insert cond1;

        TCRE__Rule_Condition__c cond2 = new TCRE__Rule_Condition__c();
        cond2.TCRE__Field_Name__c = 'CreatedDate';
        cond2.TCRE__Operator__c = '>';
        cond2.TCRE__Value__c = '12/12/2010';
        cond2.TCRE__Rule_Config__c = conf.Id;
        insert cond2;
        
        TCRE__Rule_Condition__c cond3 = new TCRE__Rule_Condition__c();
        cond3.TCRE__Field_Name__c = 'Amount';
        cond3.TCRE__Operator__c = '<';
        cond3.TCRE__Value__c = '234.56';
        cond3.TCRE__Rule_Config__c = conf.Id;
        insert cond3;
        
        Tax_Rule__c tr = new Tax_Rule__c();
        tr.Rule_Config__c = conf.Id;
        tr.State__c = 'MN';
        tr.Tax_Basis_Field__c = 'Amount';
        tr.Rate_Code_to_Use__c = '001';
        tr.Description__c = 'Description';
        tr.Tax_type__c = 'Regular';
        tr.State_Rate_Code_to_Use__c = '001';
        tr.County_Rate_Code_to_Use__c = '001';
        tr.TCounty_Rate_Code_to_Use__c = '001';
        tr.City_Rate_Code_to_Use__c = '001';
        tr.TCity_Rate_Code_to_Use__c = '001';
        insert tr;
        
        Account acc = new Account();
        acc.Name = 'test';
        insert acc;
        
        Opportunity opp = new Opportunity();
        opp.StageName = 'test';
        opp.CloseDate = Date.today();
        opp.Amount = 123.45;
        opp.Name = 'test';
        opp.AccountId = acc.Id;
        opp.Tax_State__c = 'MN';
        opp.Tax_County__c = 'WASHINGTON';
        opp.Tax_City__c = 'WOODBURY';
        insert opp;

        GenerateTaxMatrixCtrl.generateTaxMatrix(opp.Id);
        GenerateTaxMatrixCtrl.getTaxCalculationStatus(opp.Id);

        TaxRules.runAutoGenerate(new List <Id>{opp.Id});
        GenerateTaxMatrixCtrl.getTaxCalculationStatus(opp.Id);
        
        settings = Tax_Rules_Settings__c.getOrgDefaults();
        settings.Use_Platform_Event_Instead_of_Future__c = true;
        update settings;
        TaxRules.generateTaxMatrixAsynchronous(opp.Id);
        
    }



    @isTest
    static void test2() {
        Tax_Rules_Settings__c settings = new Tax_Rules_Settings__c();
        settings.Parent_Object__c = 'Opportunity';
        settings.Rate_Object__c = 'Rate__c';
        settings.Rate_State_Field__c = 'State__c';
        settings.Rate_County_Field__c = 'County__c';
        settings.Rate_City_Field__c = 'City__c';
        settings.Rate_Code_Field__c = 'Rate_Code__c';
        settings.State_Tax_Rate_Field__c = 'State_Tax_Rate__c';
        settings.County_Tax_Rate_Field__c = 'County_Tax_Rate__c';
        settings.TCounty_Tax_Rate_Field__c = 'County_Transit_Tax_Rate__c';
        settings.City_Tax_Rate_Field__c = 'City_Tax_Rate__c';
        settings.TCity_Tax_Rate_Field__c = 'City_Transit_Tax_Rate__c';
        settings.Tax_Parent_Object_Field__c = 'Opportunity__c';
        settings.Parent_Generate_Tax_Matrix_Message_Field__c = 'Description';
        settings.Parent_Tax_Calculation_Begin_Field__c = 'Last_Tax_Calculation_Begin__c';
        settings.Parent_Tax_Calculation_Complete_Field__c = 'Last_Tax_Calculation_Complete__c';
        settings.Parent_Tax_Calculation_Successful_Field__c = 'Last_Tax_Calculation_Successful__c';
        settings.Parent_Tax_Calculation_Error_Field__c = 'Last_Tax_Calculation_Error_Details__c';
        settings.Parent_Tax_Calculation_In_Progress_Field__c = 'Is_Tax_Calculation_In_Progress__c';
        settings.Tax_Calculation_Completion_Alert_Seconds__c = 90;
        insert settings;
        
        Rate__c rate = new Rate__c();
        rate.State__c = 'MN';
        rate.County__c = 'WASHINGTON';
        rate.City__c = 'WOODBURY';
        rate.State_Code__c = '24';
        rate.County_Code__c = '163';
        rate.City_Code__c = '1740';
        rate.Rate_Code__c = '001';
        rate.State_Tax_Rate__c = 0.01;
        rate.County_Tax_Rate__c = 0.01;
        rate.County_Transit_Tax_Rate__c = 0.01;
        rate.City_Tax_Rate__c = 0.01;
        rate.City_Transit_Tax_Rate__c = 0.01;
        insert rate;
        
        TCRE__Rule_Config__c conf = new TCRE__Rule_Config__c();
        conf.TCRE__SObject_Name__c = 'Opportunity';
        conf.TCRE__Priority__c = 1;
        insert conf;
        
        TCRE__Rule_Condition__c cond1 = new TCRE__Rule_Condition__c();
        cond1.TCRE__Field_Name__c = 'StageName';
        cond1.TCRE__Operator__c = '=';
        cond1.TCRE__Value__c = 'test';
        cond1.TCRE__Rule_Config__c = conf.Id;
        insert cond1;

        TCRE__Rule_Condition__c cond2 = new TCRE__Rule_Condition__c();
        cond2.TCRE__Field_Name__c = 'CreatedDate';
        cond2.TCRE__Operator__c = '>';
        cond2.TCRE__Value__c = '12/12/2010';
        cond2.TCRE__Rule_Config__c = conf.Id;
        insert cond2;
        
        TCRE__Rule_Condition__c cond3 = new TCRE__Rule_Condition__c();
        cond3.TCRE__Field_Name__c = 'Amount';
        cond3.TCRE__Operator__c = '<';
        cond3.TCRE__Value__c = '234.56';
        cond3.TCRE__Rule_Config__c = conf.Id;
        insert cond3;
        
        Tax_Rule__c tr = new Tax_Rule__c();
        tr.Rule_Config__c = conf.Id;
        tr.State__c = 'MN';
        tr.Tax_Basis_Field__c = 'Amount';
        tr.Rate_Code_to_Use__c = '001';
        tr.Description__c = 'Description';
        tr.Tax_type__c = 'Regular';
        tr.State_Rate_Code_to_Use__c = '001';
        tr.County_Rate_Code_to_Use__c = '001';
        tr.TCounty_Rate_Code_to_Use__c = '001';
        tr.City_Rate_Code_to_Use__c = '001';
        tr.TCity_Rate_Code_to_Use__c = '001';
        insert tr;
        
        Account acc = new Account();
        acc.Name = 'test';
        insert acc;
        
        Opportunity opp = new Opportunity();
        opp.StageName = 'test';
        opp.CloseDate = Date.today();
        opp.Amount = 123.45;
        opp.Name = 'test';
        opp.AccountId = acc.Id;
        opp.Tax_State__c = 'MN';
        opp.Tax_County__c = 'WASHINGTON';
        opp.Tax_City__c = 'WOODBURY';
        insert opp;

        GenerateTaxMatrixCtrl.generateTaxMatrix(opp.Id);
        GenerateTaxMatrixCtrl.getTaxCalculationStatus(opp.Id);

        TaxRules.runAutoGenerate(new List <Id>{opp.Id});
        GenerateTaxMatrixCtrl.getTaxCalculationStatus(opp.Id);
        
        settings = Tax_Rules_Settings__c.getOrgDefaults();
        settings.Use_Platform_Event_Instead_of_Future__c = true;
        update settings;
        
        GenerateTaxMatrixInvocable.TaxMatrixParam param = new GenerateTaxMatrixInvocable.TaxMatrixParam();
        param.recordId = opp.Id;
        param.status = 'Submitted';
        GenerateTaxMatrixInvocable.execute(new List<GenerateTaxMatrixInvocable.TaxMatrixParam>{param});
        
    }


}