peac_dev/force-app/main/default/objects/Trust_Pilot_App__c/Trust_Pilot_App__c.object-meta.xml
<CustomObject>
    <label>Trust Pilot App</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Trust Pilot App Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Trust_Pilot_Apps</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

peac_dev/force-app/main/default/objects/Trust_Pilot_App__c/fields/API_Key__c.field-meta.xml
<CustomField>
    <fullName>API_Key__c</fullName>
    <label>API Key</label>
    <length>175</length>
    <maskChar>asterisk</maskChar>
    <maskType>all</maskType>
    <type>EncryptedText</type>
</CustomField>

peac_dev/force-app/main/default/objects/Trust_Pilot_App__c/fields/Business_Id__c.field-meta.xml
<CustomField>
    <fullName>Business_Id__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Business Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

peac_dev/force-app/main/default/objects/Trust_Pilot_App__c/fields/Invitation_URL__c.field-meta.xml
<CustomField>
    <fullName>Invitation_URL__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Invitation URL</label>
    <type>Url</type>
</CustomField>

peac_dev/force-app/main/default/objects/Trust_Pilot_App__c/fields/Secret__c.field-meta.xml
<CustomField>
    <fullName>Secret__c</fullName>
    <label>Secret</label>
    <length>175</length>
    <maskChar>asterisk</maskChar>
    <maskType>all</maskType>
    <type>EncryptedText</type>
</CustomField>

peac_dev/force-app/main/default/objects/Trust_Pilot_App__c/fields/Token_URL__c.field-meta.xml
<CustomField>
    <fullName>Token_URL__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Token URL</label>
    <type>Url</type>
</CustomField>

peac_dev/force-app/main/default/objects/Trust_Pilot_App__c/fields/Username__c.field-meta.xml
<CustomField>
    <fullName>Username__c</fullName>
    <label>Username</label>
    <length>175</length>
    <maskChar>asterisk</maskChar>
    <maskType>all</maskType>
    <type>EncryptedText</type>
</CustomField>

peac_dev/force-app/main/default/classes/TC_TrustPilotAPITest.cls
@isTest public class TC_TrustPilotAPITest {
    
    @testsetup
    public static void setupIntData () {
        insert new Trust_Pilot_App__c(API_Key__c = 'test', Secret__c = 'test', Business_Id__c = 'test', Invitation_URL__c = 'TrustPilot2Resp', Password__c = 'tes', Token_URL__c = 'TrustPilot1Resp', Username__c = 'test');
        Account acc = new Account (Name = 'test', Business_Phone__c = '1234567890');
        insert acc;
        Opportunity opp = new Opportunity (Name = 'trustpilot', StageName = 'Quote ', CloseDate = Date.today (), AccountId = acc.Id);
        insert opp;
        
        Contact con = new Contact (FirstName = 'test', LastName = 'tes', AccountId = acc.Id);
        insert con;
        
        insert new OpportunityContactRole (ContactId = con.Id, OpportunityId = opp.Id, IsPrimary = true);
    }
    
    @istest
    public static void syncTest () {
        Test.startTest();
        Opportunity opp = [SELECT Id FROM Opportunity WHERE Name = 'trustpilot'][0];
        Test.setMock(HttpCalloutMock.class, new TC_TrustPilotResponseGenerator());
        TC_TrustPilotAPI.generateInvitation (opp.Id);
        Test.stopTest();
        
    }
    @istest
    public static void asyncTest () {
        Test.startTest();
        Opportunity opp = [SELECT Id FROM Opportunity WHERE Name = 'trustpilot'][0];
        Test.setMock(HttpCalloutMock.class, new TC_TrustPilotResponseGenerator());
        System.enqueueJob (new TC_TrustPilotQueueable (new Set <Id> {opp.Id}));
        Test.stopTest();
        
    }

}