peac_dev/force-app/main/default/objects/Approved_Offer__c/Approved_Offer__c.object-meta.xml
<CustomObject>
    <description>Approved Offer from Case Center Loan system.</description>
    <label>Approved Offer</label>
    <nameField>
        <displayFormat>Offer-{0}</displayFormat>
        <label>Approved Offer ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Approved Offers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

peac_dev/force-app/main/default/objects/Approved_Offer__c/fields/Approved_Frequency__c.field-meta.xml
<CustomField>
    <fullName>Approved_Frequency__c</fullName>
    <inlineHelpText>Value from Case Center. If set to daily, weekly payments do not calculate and user cannot select weekly as selected frequency. If set to Daily/Weekly, both daily and weekly calculate and selected frequency can be either.</inlineHelpText>
    <label>Approved Frequency</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Daily</fullName>
            </value>
            <value>
                <fullName>Daily/Weekly</fullName>
                <default>true</default>
                <label>Daily/Weekly</label>
            </value>
            <value>
                <fullName>Daily/Weekly/Monthly</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

peac_dev/force-app/main/default/objects/Approved_Offer__c/fields/Offer_Amount__c.field-meta.xml
<CustomField>
    <fullName>Offer_Amount__c</fullName>
    <label>Offer (Amount)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

peac_dev/force-app/main/default/objects/Approved_Offer__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <inlineHelpText>Related Opportunity</inlineHelpText>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Approved Offers</relationshipLabel>
    <relationshipName>Approved_Offers</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

peac_dev/force-app/main/default/objects/Approved_Offer__c/fields/Select_for_approval__c.field-meta.xml
<CustomField>
    <fullName>Select_for_approval__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Created for gds</description>
    <label>Select for approval</label>
    <type>Checkbox</type>
</CustomField>

peac_dev/force-app/main/default/objects/Approved_Offer__c/fields/Term__c.field-meta.xml
<CustomField>
    <fullName>Term__c</fullName>
    <label>Term (in Months)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

peac_dev/force-app/main/default/classes/PEAC_OptyApprovalFSController.cls
/**************************************************************************************************************
@Author:D Balakrishna(LTIMindtree)
@Description:This class contains the business logic that ensures fulfillment of requirement of displaying Approval Section fields which fetches left side data from Approver and Right Side data from Opportunity
@User Story:SAL-5999
@Created Date:November-25-2025
**************************************************************************************************************/
public with sharing class PEAC_OptyApprovalFSController {
    @AuraEnabled(cacheable=true)
    public static Approved_Offer__c getTopApprovedOffer(Id opptyId) {
        if (opptyId == null) return null;
        List<Approved_Offer__c> rows = [SELECT Id,Approved_Frequency__c,Select_for_approval__c,Offer_Amount__c,Term__c FROM Approved_Offer__c
            WHERE Opportunity__c = :opptyId AND Select_for_approval__c = true AND Offer_Amount__c > 0
            ORDER BY Offer_Amount__c DESC LIMIT 1
        ];
        return rows.isEmpty() ? null : rows[0];
    }
    public PEAC_OptyApprovalFSController() {

    }
}