peac_dev/force-app/main/default/objects/OnBase_Credentials__c/OnBase_Credentials__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>OnBase Credentials</label>
</CustomObject>

peac_dev/force-app/main/default/objects/OnBase_Credentials__c/fields/Add_Document__c.field-meta.xml
<CustomField>
    <fullName>Add_Document__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Add Document</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

peac_dev/force-app/main/default/objects/OnBase_Credentials__c/fields/App_Server_Url__c.field-meta.xml
<CustomField>
    <fullName>App_Server_Url__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>App Server Url</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

peac_dev/force-app/main/default/objects/OnBase_Credentials__c/fields/Data_Source__c.field-meta.xml
<CustomField>
    <fullName>Data_Source__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Data Source</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

peac_dev/force-app/main/default/objects/OnBase_Credentials__c/fields/Gateway_Url__c.field-meta.xml
<CustomField>
    <fullName>Gateway_Url__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Gateway Url</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

peac_dev/force-app/main/default/objects/OnBase_Credentials__c/fields/Initialization_Vector__c.field-meta.xml
<CustomField>
    <fullName>Initialization_Vector__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Initialization Vector</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

peac_dev/force-app/main/default/objects/OnBase_Credentials__c/fields/Secret_Key__c.field-meta.xml
<CustomField>
    <fullName>Secret_Key__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Secret Key</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

peac_dev/force-app/main/default/classes/TC_OnBaseRequest.cls
public class TC_OnBaseRequest {
    
    private static OnBase_Credentials__c creds = OnBase_Credentials__c.getOrgDefaults ();
    
    public static String getAddDocumentUrl () {
        return creds.Gateway_Url__c + creds.Add_Document__c;
    }
    
    public static String getHeader () {
        
        String credString = '{0},{1},{2},{3}';
        
        credString = String.format (credString
                                    , new List <String> {
                                         creds.Username__c
                                        , creds.Password__c
                                        , creds.App_Server_Url__c
                                        , creds.Data_Source__c});

		Blob bval = Blob.valueOf (EncodingUtil.base64Encode (Blob.valueOf (credString)));
        
		Blob input  = Crypto.encrypt('AES256', Blob.valueOf(creds.Secret_Key__c), Blob.valueOf (creds.Initialization_Vector__c), bval);
        return EncodingUtil.base64Encode (input);
    }

}