peac_dev/force-app/main/default/objects/OnBase_Credentials__c/OnBase_Credentials__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>OnBase Credentials</label>
</CustomObject>

peac_dev/force-app/main/default/objects/OnBase_Credentials__c/fields/Add_Document__c.field-meta.xml
<CustomField>
    <fullName>Add_Document__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Add Document</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

peac_dev/force-app/main/default/objects/OnBase_Credentials__c/fields/App_Server_Url__c.field-meta.xml
<CustomField>
    <fullName>App_Server_Url__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>App Server Url</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

peac_dev/force-app/main/default/objects/OnBase_Credentials__c/fields/Data_Source__c.field-meta.xml
<CustomField>
    <fullName>Data_Source__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Data Source</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

peac_dev/force-app/main/default/objects/OnBase_Credentials__c/fields/Gateway_Url__c.field-meta.xml
<CustomField>
    <fullName>Gateway_Url__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Gateway Url</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

peac_dev/force-app/main/default/objects/OnBase_Credentials__c/fields/Initialization_Vector__c.field-meta.xml
<CustomField>
    <fullName>Initialization_Vector__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Initialization Vector</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

peac_dev/force-app/main/default/objects/OnBase_Credentials__c/fields/Secret_Key__c.field-meta.xml
<CustomField>
    <fullName>Secret_Key__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Secret Key</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

peac_dev/force-app/main/default/classes/TC_OnBaseRequestTest.cls
@isTest public class TC_OnBaseRequestTest {
    
    @isTest public static void testOnBaseHeader () {
        insert new OnBase_Credentials__c (Add_Document__c = 'test'
                                          , App_Server_Url__c = 'test'
                                          , Data_Source__c = 'tet'
                                          , Gateway_Url__c = 'test'
                                          , Initialization_Vector__c = 'Ki01di908lGdQ8ot'
                                          , Password__c = 'te'
                                          , Secret_Key__c = 'Ki0+di908lGdQ8otxkzyKHxqF3ciK411'
                                          , Username__c = 'test');
        TC_OnBaseRequest.getHeader();
        TC_OnBaseRequest.getAddDocumentUrl ();
    }

}