peac_dev/force-app/main/default/objects/Guarantor__c/Guarantor__c.object-meta.xml
<CustomObject>
    <label>Guarantor</label>
    <nameField>
        <displayFormat>G-{00000}</displayFormat>
        <label>Guarantor Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Guarantors</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

peac_dev/force-app/main/default/objects/Guarantor__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Guarantors</relationshipLabel>
    <relationshipName>GuarantorContact</relationshipName>
    <type>Lookup</type>
</CustomField>

peac_dev/force-app/main/default/objects/Guarantor__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <description>master detail relationship to Opportunity</description>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Guarantors</relationshipLabel>
    <relationshipName>Guarantor</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

peac_dev/force-app/main/default/objects/Guarantor__c/fields/Priority__c.field-meta.xml
<CustomField>
    <fullName>Priority__c</fullName>
    <inlineHelpText>Rank the priority of the related guarantors. Rankings must be unique per type. If priority is set to 1, formula field checks off that guarantor as a primary guarantor.</inlineHelpText>
    <label>Priority</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

peac_dev/force-app/main/default/objects/Guarantor__c/fields/SSN__c.field-meta.xml
<CustomField>
    <fullName>SSN__c</fullName>
    <formula>Contact__r.SSN__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>SSN</label>
    <type>Text</type>
</CustomField>

peac_dev/force-app/main/default/objects/Guarantor__c/fields/Tax_Id__c.field-meta.xml
<CustomField>
    <fullName>Tax_Id__c</fullName>
    <formula>Account__r.Tax_ID__c</formula>
    <label>Tax Id</label>
    <type>Text</type>
</CustomField>

peac_dev/force-app/main/default/objects/Webservice_Field__c/Webservice_Field__c.object-meta.xml
<CustomObject>
    <label>Webservice Field</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Webservice Field Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Webservice Fields</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

peac_dev/force-app/main/default/objects/Webservice_Field__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Webservice Fields</relationshipLabel>
    <relationshipName>Webservice_Fields</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

peac_dev/force-app/main/default/classes/SL_CaseCenterStoredProcedureTest.cls
@isTest
private class SL_CaseCenterStoredProcedureTest {

    class MockHttpResponseGenerator implements HttpCalloutMock {
        public HTTPResponse respond(HTTPRequest req) {
            HttpResponse res = new HttpResponse();
            res.setHeader('Content-Type', 'application/json');
            res.setBody('{"results": [{"CreditScore": "750", "FraudFlag": "No"}]}');
            res.setStatusCode(200);
            return res;
        }
    }

    @testSetup
    static void setup() {
        Account acct = new Account(Name = 'Test Acc', Tax_ID__c = '123789654');
        insert acct;

        Opportunity opp = new Opportunity(
            Name = 'Test Opp',
            StageName = 'Qualification',
            CloseDate = Date.today().addDays(10),
            AccountId = acct.Id
        );
        insert opp;

        Contact contact = new Contact(
            FirstName = 'John',
            LastName = 'Doe',
            SSN__c = '999887777',
            Phone = '7854785555'
        );
        insert contact;

        Guarantor__c g = new Guarantor__c(
            Opportunity__c = opp.Id,
            Priority__c = 1,
            Contact__c = contact.Id
            // Do NOT try to set SSN__c directly if it's a formula field
        );
        insert g;
    }


    @isTest
    static void testExecuteGetCreditExp() {
        Test.setMock(HttpCalloutMock.class, new MockHttpResponseGenerator());
        Opportunity opp = [SELECT Id FROM Opportunity LIMIT 1];

        Test.startTest();
        System.enqueueJob(new SL_CaseCenterStoredProcedureQueueable(new List<String>{'getGdsGetCustCreditExpLoan'},opp.Id, 'Label.PEAC_Initial_Submission'));         
          
        Test.stopTest();

        List<Webservice_Field__c> ws = [SELECT Id FROM Webservice_Field__c WHERE Opportunity__c = :opp.Id];
        System.assertEquals(1, ws.size());
    }

    @isTest
    static void testExecuteFraudFlags() {
        Test.setMock(HttpCalloutMock.class, new MockHttpResponseGenerator());
        Opportunity opp = [SELECT Id FROM Opportunity LIMIT 1];

        Test.startTest();
            SL_CaseCenterStoredProcedure.SL_CaseCenterStoredProcedure(new List<String>{'getGdsGetCustCreditExpLoan', 'getGDSFraudFlags'},opp.Id);
        Test.stopTest();

        List<Webservice_Field__c> ws = [SELECT Id FROM Webservice_Field__c WHERE Opportunity__c = :opp.Id];
        System.assertEquals(2, ws.size());
    }

    @isTest
    static void testBadJsonThrows() {
        try {
            SL_CaseCenterStoredProcedure.convertResponse('', 'key - Field__c', Id.valueOf(UserInfo.getUserId()));
            System.assert(false);
        } catch (Exception e) {
            System.assert(e.getMessage().contains('Invalid input'));
        }
    }

    @isTest
    static void testBadMappingLineThrows() {
        Opportunity opp = [SELECT Id FROM Opportunity LIMIT 1];

        try {
            SL_CaseCenterStoredProcedure.buildRequest(opp.Id, 'No-Dash-MappingLine-Here');
            System.assert(false);
        } catch (SL_CaseCenterStoredProcedure.MappingException e) {
            System.assert(e.getMessage().contains('Invalid mapping line'));
        }
    }
}