peac_dev/force-app/main/default/objects/Guarantor__c/Guarantor__c.object-meta.xml
<CustomObject>
    <label>Guarantor</label>
    <nameField>
        <displayFormat>G-{00000}</displayFormat>
        <label>Guarantor Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Guarantors</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

peac_dev/force-app/main/default/objects/Guarantor__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Guarantors</relationshipLabel>
    <relationshipName>GuarantorContact</relationshipName>
    <type>Lookup</type>
</CustomField>

peac_dev/force-app/main/default/objects/Guarantor__c/fields/SSN__c.field-meta.xml
<CustomField>
    <fullName>SSN__c</fullName>
    <formula>Contact__r.SSN__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>SSN</label>
    <type>Text</type>
</CustomField>

peac_dev/force-app/main/default/objects/Guarantor__c/recordTypes/Personal.recordType-meta.xml
<RecordType>
    <fullName>Personal</fullName>
    <active>true</active>
    <label>Personal</label>
</RecordType>

peac_dev/force-app/main/default/objects/Marlin_Configuration__c/Marlin_Configuration__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Marlin Configuration</label>
</CustomObject>

peac_dev/force-app/main/default/objects/Marlin_Configuration__c/fields/Apex_Validations_Active__c.field-meta.xml
<CustomField>
    <fullName>Apex_Validations_Active__c</fullName>
    <defaultValue>false</defaultValue>
    <description>If true apex validation rules will run</description>
    <inlineHelpText>If true apex validation rules will run</inlineHelpText>
    <label>Apex Validations Active</label>
    <type>Checkbox</type>
</CustomField>

peac_dev/force-app/main/default/classes/TC_CheckGuarantorSSNsWhenBookingStage.cls
public class TC_CheckGuarantorSSNsWhenBookingStage {
    public static Marlin_Configuration__c config = Marlin_Configuration__c.getOrgDefaults();
public static void checkGuarantorSSNsWhenBookingStage (Map <Id, Opportunity> oldMap, Map <Id, Opportunity> newMap, Map<Id, Guarantor__c> guarantors) {
        
        Set <Id> bookingOppIds = new Set <Id> ();
        // only on change to booking stage
        if(config != null && config.Apex_Validations_Active__c){
            for (Opportunity opp : newMap.values ()) {
                if (!opp.Loan_Record_Type__c && opp.StageName == 'Booking' && opp.StageName != oldMap.get (opp.Id).StageName) {
                    bookingOppIds.add (opp.Id);
                }
            }
        }        
        if (!bookingOppIds.isEmpty ()) {
            Id pgRecordTypeId = Schema.SObjectType.Guarantor__c.getRecordTypeInfosByName().get('Personal').getRecordTypeId();
            
            Map<Id, List<Guarantor__c>> guarantorsByOpp = TC_OpportunityFieldUpdates.getGuarantorMap(guarantors);
            for (Id oppId : bookingOppIds) {
                List<Guarantor__c> guarantorsThisOpp = guarantorsByOpp.get(oppId);
                if(guarantorsThisOpp != null){
                    List <String> errors = new List <String> ();
                    for(Guarantor__c guar : guarantorsThisOpp) {
                        if(guar.RecordTypeId == pgRecordTypeId && (String.isBlank(guar.Contact__r.SSN__c) || guar.Contact__r.SSN__c.length() != 9)) {
                            errors.add(guar.Contact__r.Name);
                        }
                    }
                    if(!errors.isEmpty())
                        newMap.get(oppId).addError('Personal Guarantor: ' + errors + ' SSN can\'t be less than 9 digits when stage is changed to Booking');
                }
                
            }
        }
        
    }
}