peac_dev/force-app/main/default/objects/Guarantor__c/Guarantor__c.object-meta.xml
<CustomObject>
    <label>Guarantor</label>
    <nameField>
        <displayFormat>G-{00000}</displayFormat>
        <label>Guarantor Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Guarantors</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

peac_dev/force-app/main/default/objects/Guarantor__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Guarantors</relationshipLabel>
    <relationshipName>GuarantorContact</relationshipName>
    <type>Lookup</type>
</CustomField>

peac_dev/force-app/main/default/objects/Guarantor__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <description>master detail relationship to Opportunity</description>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Guarantors</relationshipLabel>
    <relationshipName>Guarantor</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

peac_dev/force-app/main/default/objects/Guarantor__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Personal Guarantor</fullName>
            </value>
            <value>
                <fullName>Corporate Guarantor</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

peac_dev/force-app/main/default/objects/Guarantor__c/recordTypes/Personal.recordType-meta.xml
<RecordType>
    <fullName>Personal</fullName>
    <active>true</active>
    <label>Personal</label>
</RecordType>

peac_dev/force-app/main/default/classes/TC_GenerateDocsCtrlTest.cls
@IsTest
public with sharing class TC_GenerateDocsCtrlTest {
   @TestSetup
    static void makeData(){
        Account a = TC_SDR_TestUtility.constructAccount('Test Generate Docs Ctrl', null, null);
        insert a;
        Opportunity o = TC_SDR_TestUtility.constructOpportunity('Test GenDocs Opportunity', a.Id);
        insert o;
        Contact c1 = TC_SDR_TestUtility.constructContact('TestPerson', 'DOCGEN', 'test@test.com', a.Id);
        c1.Phone = '6121231234';
        Contact c2 = TC_SDR_TestUtility.constructContact('TestPerson2', '2DOC2GEN', 'person@testEmail.com', a.Id);
        c2.Phone = '1231231234';
        insert new List<Contact>{c1, c2};
    }

    @IsTest
    static void testWithGuarantors() {
        Test.startTest();
        Opportunity o = [SELECT Id FROM Opportunity][0];
        List<Contact> cons = new List<Contact>([SELECT Id FROM Contact]);
        Guarantor__c g = new Guarantor__c(
            Opportunity__c = o.Id,
            Contact__c = cons[0].Id,
            Type__c = 'Personal Guarantor',
            RecordTypeId = Schema.SObjectType.Guarantor__c.getRecordTypeInfosByName().get('Personal').getRecordTypeId()
        );
        Guarantor__c g2 = new Guarantor__c(
            Opportunity__c = o.Id,
            Contact__c = cons[1].Id,
            Type__c = 'Personal Guarantor',
            RecordTypeId = Schema.SObjectType.Guarantor__c.getRecordTypeInfosByName().get('Personal').getRecordTypeId()
        );
        insert new List<Guarantor__c>{g, g2};

        TC_GenerateDocsCtrl.generateDocuments(o.Id);
        Test.stopTest();
    }

    @IsTest
    static void testWithPrimaryContact() {
        Test.startTest();
        Opportunity o = [SELECT Id FROM Opportunity][0];
        Contact c = [SELECT Id FROM Contact][0];
        o.Primary_Contact__c = c.Id;
        update o;
        TC_GenerateDocsCtrl.generateDocuments(o.Id);
        Test.stopTest();
    }
}