peac_dev/force-app/main/default/objects/Guarantor__c/Guarantor__c.object-meta.xml
<CustomObject>
    <label>Guarantor</label>
    <nameField>
        <displayFormat>G-{00000}</displayFormat>
        <label>Guarantor Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Guarantors</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

peac_dev/force-app/main/default/objects/Guarantor__c/fields/Business_Phone__c.field-meta.xml
<CustomField>
    <fullName>Business_Phone__c</fullName>
    <formula>Account__r.Business_Phone__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Business Phone</label>
    <type>Text</type>
</CustomField>

peac_dev/force-app/main/default/objects/Guarantor__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Guarantors</relationshipLabel>
    <relationshipName>GuarantorContact</relationshipName>
    <type>Lookup</type>
</CustomField>

peac_dev/force-app/main/default/objects/Guarantor__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <description>master detail relationship to Opportunity</description>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Guarantors</relationshipLabel>
    <relationshipName>Guarantor</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

peac_dev/force-app/main/default/objects/Guarantor__c/fields/SSN__c.field-meta.xml
<CustomField>
    <fullName>SSN__c</fullName>
    <formula>Contact__r.SSN__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>SSN</label>
    <type>Text</type>
</CustomField>

peac_dev/force-app/main/default/classes/TC_TestSetApprovalMergeFields.cls
/** @author : Northteq Consulting, Inc.
 * @date : 11/11/20
 * @description: Created as a replacement for the testSetApprovalMergeFields test in TC_OpportunityTriggerHelperTest
 *
 */
@IsTest
public with sharing class TC_TestSetApprovalMergeFields {

    @TestSetup
    static void setup() {
        Account account = new Account(Name = 'test account', Business_Phone__c = '1234567890');
        insert account;

        Contact contact = new Contact(
                FirstName = 'Joe',
                LastName = 'Smith',
                AccountId = account.Id,
                MailingStreet = '701 N 3rd St',
                MailingCity = 'Minneapolis',
                MailingState = 'Minnesota',
                MailingPostalCode = '55401',
                SSN__c = '666000000',
                Email = 'sfdc@northteq.com'
        );
        insert contact;

        Opportunity opportunity = new Opportunity(
        AccountId = account.Id,
        Name = 'testSetApprovalMergeFields',
        StageName = 'Decision',
        CloseDate = Date.today(),
        Application__c = '12345'
        );
        Test.startTest();
        insert opportunity;
        Test.stopTest();
    }

    @IsTest
    static void test() {

        Contact contact = [SELECT Id FROM Contact WHERE FirstName = 'Joe'];
        Opportunity opportunity = [SELECT Id FROM Opportunity WHERE Name = 'testSetApprovalMergeFields'];

        Guarantor__c guarantor = new Guarantor__c(
        Opportunity__c = opportunity.Id,
        Contact__c = contact.Id
        );
        insert guarantor;

        opportunity.Application_Status__c = 'Automatically Approved';
        Test.startTest();
        update opportunity;
        Test.stopTest();
    }
}