peac_dev/force-app/main/default/objects/Variable_Payment__c/Variable_Payment__c.object-meta.xml
<CustomObject>
    <label>Variable Payment</label>
    <nameField>
        <displayFormat>VP-{0000}</displayFormat>
        <label>Variable Payments Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Variable Payments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

peac_dev/force-app/main/default/objects/Variable_Payment__c/fields/of_payments__c.field-meta.xml
<CustomField>
    <fullName>of_payments__c</fullName>
    <label># of payments</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

peac_dev/force-app/main/default/objects/Variable_Payment__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Variable Payments</relationshipLabel>
    <relationshipName>Variable_Payments</relationshipName>
    <type>Lookup</type>
</CustomField>

peac_dev/force-app/main/default/objects/Variable_Payment__c/fields/Payment_Amount__c.field-meta.xml
<CustomField>
    <fullName>Payment_Amount__c</fullName>
    <label>Payment Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

peac_dev/force-app/main/default/classes/VariablePaymentTriggerHandler_Test.cls
@isTest
public class VariablePaymentTriggerHandler_Test {
    
    @TestSetup
    static void setup(){
        
        //create dealer type account
        //Account record of type End USer
        RecordType rt = [select id,Name from RecordType where SobjectType='Account' and Name='End User Account' Limit 1];
        Account acct1 = new Account(Name='Test Account1' , recordTypeId=rt.id);        
        insert acct1;
        
        Account acct2 = new Account(Name='Test Account2' , recordTypeId=rt.id, Business_Phone__c = '0987654321');
        insert acct2;
        
        //create opportuntiy and associate it with the account.
        RecordType rt2 = [select id,Name from RecordType where SobjectType='Opportunity' and Name LIKE '%Express%' Limit 1];
        Opportunity op = new Opportunity();
        op.Name = 'Test Opp';
        op.Accountid = acct1.Id;
        op.Amount = 100;
        op.StageName = 'Quote';
        op.CloseDate = System.today() + 30;
        op.Primary_Source__c = 'Email';
        
        Test.startTest();
        insert op;
        Test.stopTest();
        
    }
    
    public static testmethod void testInsertVp() {
        Opportunity op = [SELECT Id FROM Opportunity WHERE Name = 'Test Opp'];
        
        Test.startTest();
        Variable_Payment__c vp = new Variable_Payment__c();
        vp.of_payments__c = 67;
        vp.Payment_Amount__c = 56;
        vp.Opportunity__c = op.id;
        insert vp;
        Test.stopTest();
    }
}