peac_dev/force-app/main/default/objects/Marlin_Configuration__c/Marlin_Configuration__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Marlin Configuration</label>
</CustomObject>

peac_dev/force-app/main/default/objects/Marlin_Configuration__c/fields/DNS_Marketo_Timer__c.field-meta.xml
<CustomField>
    <fullName>DNS_Marketo_Timer__c</fullName>
    <description>If an application is rejected for more than this number of days, set related Contacts on the Parent Account to Not Sync to Marketo.</description>
    <inlineHelpText>If an application is rejected for more than this number of days, set related Contacts on the Parent Account to Not Sync to Marketo.</inlineHelpText>
    <label>DNS Marketo Timer</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

peac_dev/force-app/main/default/classes/TC_DNSMarketoSchedulableTest.cls
/** @author : Northteq Consulting, Inc.
 * @date : 11/10/20
 * @description: Do Not Sync to Marketo Schedulable Test class
 *
 */

@IsTest
public with sharing class TC_DNSMarketoSchedulableTest {

    @IsTest
    static void test() {
        String CRON_EXP = '0 0 0 3 9 ? 2022';
        insert new Marlin_Configuration__c(DNS_Marketo_Timer__c = 30);
        Test.startTest();
        String jobId = System.schedule('TC_DNSMarketoSchedulableTest', CRON_EXP, new TC_DNSMarketoSchedulable());
        Test.stopTest();
    }
}