peac_dev/force-app/main/default/objects/Marlin_Configuration__c/Marlin_Configuration__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Marlin Configuration</label>
</CustomObject>

peac_dev/force-app/main/default/objects/Marlin_Configuration__c/fields/Enable_Auto_Move_to_Booking__c.field-meta.xml
<CustomField>
    <fullName>Enable_Auto_Move_to_Booking__c</fullName>
    <defaultValue>false</defaultValue>
    <description>If checked, deal will automatically move to booking once all payments move to Payment Confirmed status. If not checked, a user needs to move to Booking.</description>
    <inlineHelpText>If checked, deal will automatically move to booking once all payments move to Payment Confirmed status. If not checked, a user needs to move to Booking.</inlineHelpText>
    <label>Enable Auto Move to Booking</label>
    <type>Checkbox</type>
</CustomField>

peac_dev/force-app/main/default/objects/Payment__c/Payment__c.object-meta.xml
<CustomObject>
    <description>Payments to a Payee related to an opportunity</description>
    <label>Payment</label>
    <nameField>
        <displayFormat>PYMT-{0}</displayFormat>
        <label>Payment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

peac_dev/force-app/main/default/objects/Payment__c/fields/Date_Sent_to_External_System__c.field-meta.xml
<CustomField>
    <fullName>Date_Sent_to_External_System__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Date Sent to External System</label>
    <type>DateTime</type>
</CustomField>

peac_dev/force-app/main/default/objects/Payment__c/fields/Less_Delivery_Guarantee_Fee__c.field-meta.xml
<CustomField>
    <fullName>Less_Delivery_Guarantee_Fee__c</fullName>
    <label>Less Delivery Guarantee Fee</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

peac_dev/force-app/main/default/objects/Payment__c/fields/Less_Titling_Fee__c.field-meta.xml
<CustomField>
    <fullName>Less_Titling_Fee__c</fullName>
    <label>Less Titling Fee</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

peac_dev/force-app/main/default/objects/Payment__c/fields/Less_UPS_Charge__c.field-meta.xml
<CustomField>
    <fullName>Less_UPS_Charge__c</fullName>
    <label>Less UPS Charge</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

peac_dev/force-app/main/default/objects/Payment__c/fields/Less_Wire_Fee__c.field-meta.xml
<CustomField>
    <fullName>Less_Wire_Fee__c</fullName>
    <label>Less Wire Fee</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

peac_dev/force-app/main/default/objects/Payment__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <inlineHelpText>Opportunity related to this payment</inlineHelpText>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Payments</relationshipLabel>
    <relationshipName>Payments</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

peac_dev/force-app/main/default/objects/Payment__c/fields/Payment_Status__c.field-meta.xml
<CustomField>
    <fullName>Payment_Status__c</fullName>
    <label>Payment Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>Ready to Send</fullName>
            </value>
            <value>
                <fullName>Payment Sent</fullName>
            </value>
            <value>
                <fullName>Payment Confirmed</fullName>
                <label>Payment Acknowledged</label>
            </value>
            <value>
                <fullName>Payment Released</fullName>
            </value>
            <value>
                <fullName>Void/Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

peac_dev/force-app/main/default/objects/Payment__c/fields/Plus_Points__c.field-meta.xml
<CustomField>
    <fullName>Plus_Points__c</fullName>
    <label>Plus Points</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

peac_dev/force-app/main/default/classes/TC_PaymentTriggerHelper.cls
public class TC_PaymentTriggerHelper {
	
    public static void updateOpportunityStage (Map <Id, Payment__c> oldMap, Map <Id, Payment__c> newMap) {
        Marlin_Configuration__c config = Marlin_Configuration__c.getOrgDefaults ();
        
        if (config != null && config.Enable_Auto_Move_to_Booking__c) {
            Set <Id> oppIds = new Set <Id> ();
            String paymentAcknowledgedAPIName = 'Payment Confirmed';
            
            for (Payment__c payment : newMap.values ()) {
                if (payment.Payment_Status__c != oldMap.get (payment.Id).Payment_Status__c && payment.Payment_Status__c == paymentAcknowledgedAPIName) {
                    oppIds.add (payment.Opportunity__c);
                }
            }
            
            if (!oppIds.isEmpty ()) {
                List <Opportunity> updateList = new List <Opportunity> ();
                for (Opportunity opp : [SELECT Id, (SELECT ID FROM Payments__r WHERE Payment_Status__c != :paymentAcknowledgedAPIName) FROM Opportunity WHERE Id IN :oppIds AND StageName = 'Funding' AND Loan_Record_Type__c = false]) {
                    if (opp.Payments__r.isEmpty ()) updateList.add (new Opportunity (Id = opp.Id, StageName = 'Booking'));
                }
                
                if (!updateList.isEmpty ()) update updateList;
            }
        }
        
    }

    public static void updateOpportunityFields (List<Payment__c> oldList, List<Payment__c> newList){

        Set <Id> oppIds = new Set <Id> ();

        for (Integer i=0; i < newList.size(); i++){
            if (oldList == null ||
                    oldList[i].Plus_Points__c != newList[i].Plus_Points__c ||
                    oldList[i].Less_Delivery_Guarantee_Fee__c != newList[i].Less_Delivery_Guarantee_Fee__c ||
                    oldList[i].Less_Wire_Fee__c != newList[i].Less_Wire_Fee__c ||
                    oldList[i].Less_UPS_Charge__c != newList[i].Less_UPS_Charge__c ||
                    oldList[i].Less_Titling_Fee__c != newList[i].Less_Titling_Fee__c ||
                    oldList[i].Payment_Status__c != newList[i].Payment_Status__c
                    ){
                oppIds.add(newList[i].Opportunity__c);
            }
        }

        if (!oppIds.isEmpty()) {

            List <Opportunity> oppList = new List <Opportunity> ([SELECT Id, Broker_Fees__c, Delivery_Guarantee_Fee__c, Wire_Fee__c, UPS_Fee__c, Titling_Fee__c, (SELECT Id, Plus_Points__c, Less_Delivery_Guarantee_Fee__c, Less_Wire_Fee__c, Less_UPS_Charge__c, Less_Titling_Fee__c FROM Payments__r WHERE Payment_Status__c != 'Void/Cancelled') FROM Opportunity WHERE Id IN :oppIds]);
            for (Opportunity opp : oppList) {
                opp.Broker_Fees__c = 0;
                opp.Delivery_Guarantee_Fee__c = 0;
                opp.Wire_Fee__c = 0;
                opp.UPS_Fee__c = 0;
                opp.Titling_Fee__c = 0;
                if (opp.Payments__r.size() > 0) {
                    for (Payment__c payment : opp.Payments__r) {
                        opp.Broker_Fees__c += (payment.Plus_Points__c == null ? 0 : payment.Plus_Points__c);
                        opp.Delivery_Guarantee_Fee__c += (payment.Less_Delivery_Guarantee_Fee__c == null ? 0 : payment.Less_Delivery_Guarantee_Fee__c);
                        opp.Wire_Fee__c += (payment.Less_Wire_Fee__c == null ? 0 : payment.Less_Wire_Fee__c);
                        opp.UPS_Fee__c += (payment.Less_UPS_Charge__c == null ? 0 : payment.Less_UPS_Charge__c);
                        opp.Titling_Fee__c += (payment.Less_Titling_Fee__c == null ? 0 : payment.Less_Titling_Fee__c);
                    }
                }
            }
            update oppList;
        }
    }

    public static void validateDelete(List<Payment__c> triggerOld){

        System.debug('#$#$# Validate payment delete #$#$#');

        Profile cms = [SELECT Id FROM Profile WHERE Name = 'CMS' LIMIT 1];

        System.debug('User Profile: ' + UserInfo.getProfileId());
        if (UserInfo.getProfileId() == cms.Id){
            for(Payment__c payment : triggerOld){

                System.debug('Payee Sent_to_Solomon__c: : ' + payment.Date_Sent_to_External_System__c);
                if(payment.Date_Sent_to_External_System__c != null){
                    payment.addError('CMS should not be able to use the "Delete" function on the payment object after they have Sent to Solomon.');
                }
            }
        }
    }
}