peac_dev/force-app/main/default/objects/Marlin_Configuration__c/Marlin_Configuration__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Marlin Configuration</label>
</CustomObject>

peac_dev/force-app/main/default/objects/Marlin_Configuration__c/fields/Apex_Validations_Active__c.field-meta.xml
<CustomField>
    <fullName>Apex_Validations_Active__c</fullName>
    <defaultValue>false</defaultValue>
    <description>If true apex validation rules will run</description>
    <inlineHelpText>If true apex validation rules will run</inlineHelpText>
    <label>Apex Validations Active</label>
    <type>Checkbox</type>
</CustomField>

peac_dev/force-app/main/default/objects/ORE__c/ORE__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Settings to Bypass Org Rules</description>
    <label>OrgExceptions</label>
</CustomObject>

peac_dev/force-app/main/default/objects/ORE__c/fields/Bypass__c.field-meta.xml
<CustomField>
    <fullName>Bypass__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Bypass</label>
    <type>Checkbox</type>
</CustomField>

peac_dev/force-app/main/default/classes/TC_CheckForBillingContact.cls
public class TC_CheckForBillingContact {
    public static Marlin_Configuration__c config = Marlin_Configuration__c.getOrgDefaults ();
public static void checkForBillingContact (Map <Id, Opportunity> oldMap, Map <Id, Opportunity> newMap) {
        ORE__c ore = ORE__c.getOrgDefaults ();
        if (ore.Bypass__c) return;
        
        Set <Id> oppIds = new Set <Id> ();
        for (Opportunity opp : newMap.values ()) {
            if (!opp.Loan_Record_Type__c && oldMap.get (opp.Id).StageName != opp.StageName && opp.Probability >= 93) oppIds.add (opp.Id);
        }
        if (!oppIds.isEmpty ()) {
            List <OpportunityContactRole> roles = new List <OpportunityContactRole> ([SELECT OpportunityId, Role, IsPrimary  FROM OpportunityContactRole WHERE OpportunityId IN :oppIds]);
            Map <Id, Boolean> hasBilling = new Map <Id, Boolean> ();
            for (OpportunityContactRole role : roles) {
                if (role.Role == 'Billing Contact') hasBilling.put (role.OpportunityId, true);
            }
            
            for (Opportunity opp : newMap.values ()) {
                if (hasBilling.get (opp.Id) == null && opp.StageName != 'Funded/Booked' && config != null && config.Apex_Validations_Active__c) opp.StageName.addError (Label.TC_No_Billing_Contact);
            }
        }
    }
}