peac_dev/force-app/main/default/objects/Marlin_Configuration__c/Marlin_Configuration__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Marlin Configuration</label>
</CustomObject>

peac_dev/force-app/main/default/objects/Marlin_Configuration__c/fields/Apex_Validations_Active__c.field-meta.xml
<CustomField>
    <fullName>Apex_Validations_Active__c</fullName>
    <defaultValue>false</defaultValue>
    <description>If true apex validation rules will run</description>
    <inlineHelpText>If true apex validation rules will run</inlineHelpText>
    <label>Apex Validations Active</label>
    <type>Checkbox</type>
</CustomField>

peac_dev/force-app/main/default/objects/ORE__c/ORE__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Settings to Bypass Org Rules</description>
    <label>OrgExceptions</label>
</CustomObject>

peac_dev/force-app/main/default/objects/ORE__c/fields/Bypass__c.field-meta.xml
<CustomField>
    <fullName>Bypass__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Bypass</label>
    <type>Checkbox</type>
</CustomField>

peac_dev/force-app/main/default/objects/Variable_Payment__c/Variable_Payment__c.object-meta.xml
<CustomObject>
    <label>Variable Payment</label>
    <nameField>
        <displayFormat>VP-{0000}</displayFormat>
        <label>Variable Payments Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Variable Payments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

peac_dev/force-app/main/default/classes/TC_CheckVariablePayments.cls
public class TC_CheckVariablePayments {
    public static Marlin_Configuration__c config = Marlin_Configuration__c.getOrgDefaults ();
public static void checkVariablePayments (Map <Id, Opportunity> oldMap, Map <Id, Opportunity> newMap) {
        ORE__c ore = ORE__c.getOrgDefaults ();
        if (ore.Bypass__c) return;
        
        Set <Id> oppIds = new Set <Id> ();
        for (Opportunity opp : newMap.values ()) {
            if (!opp.Loan_Record_Type__c && oldMap.get (opp.Id).StageName != opp.StageName && opp.Probability >= 95 && !opp.Variable_Payment__c ) oppIds.add (opp.Id);
        }
        if (!oppIds.isEmpty ()) {
            for (Opportunity opp : [SELECT Id, (SELECT Id FROM Variable_Payments__r) FROM Opportunity WHERE Id IN :oppIds]) {
                if (!opp.Variable_Payments__r.isEmpty () && config != null && config.Apex_Validations_Active__c && newMap.get (opp.Id).StageName != 'Funded/Booked' ) {
                    newMap.get(opp.Id).Variable_Payment__c.addError ('Please check the Variable Payment checkbox if variable payments exist on the Opportunity.');
                }
            }
        }
    }
}