peac_dev/force-app/main/default/objects/IL10_Flag__c/IL10_Flag__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Setting to indicate whether or not the Infolease integration classes should process logic to dewtermine if records update IL9 or IL 10. Used primarily as a backout mechanism.</description>
    <label>IL10 Flag</label>
</CustomObject>

peac_dev/force-app/main/default/objects/IL10_Flag__c/fields/use_IL10__c.field-meta.xml
<CustomField>
    <fullName>use_IL10__c</fullName>
    <defaultValue>true</defaultValue>
    <description>to restrict the IL10 when needed</description>
    <label>use IL10</label>
    <type>Checkbox</type>
</CustomField>

peac_dev/force-app/main/default/objects/Integration_Log__c/Integration_Log__c.object-meta.xml
<CustomObject>
    <description>To collect all the custom integration exceptions</description>
    <label>Integration Log</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Interface Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Integration Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

peac_dev/force-app/main/default/objects/Integration_Log__c/fields/Error_Code__c.field-meta.xml
<CustomField>
    <fullName>Error_Code__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Error Code</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

peac_dev/force-app/main/default/objects/Integration_Log__c/fields/Error_Message__c.field-meta.xml
<CustomField>
    <fullName>Error_Message__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Error Message</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

peac_dev/force-app/main/default/objects/Integration_Log__c/fields/Record_Id__c.field-meta.xml
<CustomField>
    <fullName>Record_Id__c</fullName>
    <description>It holds the Id field of integration(Salesforce Id/ External Id)</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Object Id</label>
    <length>32</length>
    <type>Text</type>
</CustomField>

peac_dev/force-app/main/default/objects/Integration_Log__c/fields/Request_Message__c.field-meta.xml
<CustomField>
    <fullName>Request_Message__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Request Message</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

peac_dev/force-app/main/default/objects/Integration_Log__c/fields/Response_Message__c.field-meta.xml
<CustomField>
    <fullName>Response_Message__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Response Message</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

peac_dev/force-app/main/default/objects/Integration_Log__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Success</fullName>
            </value>
            <value>
                <fullName>Error</fullName>
            </value>
            <value>
                <fullName>Failure</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

peac_dev/force-app/main/default/classes/TC_BWcreateDealerCallout.cls
/**
 * Created by jhber on 3/12/2019.
 */

public with sharing class TC_BWcreateDealerCallout {

    public TC_BWDealerResponseBean createDealer(TC_BWDealerRequestBean request) {
        TC_BWDealerResponseBean respBean;

        TC_BWUtility util = TC_BWUtility.getInstance();

        String requestJSON = JSON.serialize(request, true);
        //Have to add extra "input" object layer
        String editrequestJSON = requestJSON;
        IL10_Flag__c il10Setting = IL10_Flag__c.getValues('GeneralSetting');
        Boolean isIL10 = il10Setting.use_IL10__c; // this is IL10 only regardless of the record
        if(isIL10){
            editrequestJSON = '{"inputs":' + editrequestJSON + '}';
        }
        system.debug('editrequestJSON: ' + editrequestJSON);
        util.logInfo(editrequestJSON);

        if (request != null) {
            try {
                Http h = new Http ();
                HttpRequest req = new HttpRequest ();

                if (util.getServiceSettings().Mock_Callout__c && !String.isEmpty(util.getServiceSettings().Mock_Callout_createCustomer__c)) {
                    Blob headerValue = Blob.valueOf('username' + ':' + 'password');
                    String authorizationHeader = 'Basic ' + EncodingUtil.base64Encode(headerValue);
                    req.setHeader('Authorization', authorizationHeader);
                    req.setEndpoint(util.getServiceSettings().Mock_Callout_createCustomer__c);

                } else {
                    if(isIL10){
                        TC_BWUtility.requestToIL10(req);
                    }else{
                        req.setEndpoint('callout:Bridgeware'+'/subroutine');
                    }
                }

                req.setMethod('POST');
                req.setHeader('CONFIG-NAME', util.getServiceSettings().Config_Name__c);
                req.setHeader('Content-Type','application/json');
                req.setBody(editrequestJSON);
                req.setTimeout(120000);

                HttpResponse resp = h.send(req);

                util.logInfo('createDealer response body\n' + resp.getBody());
                String responseJSON = TC_BWResponseBean.unWrap(resp.getBody());
                system.debug('responseJSON: ' + responseJSON);

                if (resp.getStatusCode() == 200) {
                    respBean = (TC_BWDealerResponseBean) JSON.deserialize(responseJSON, TC_BWDealerResponseBean.class);
                    util.logInfo('TC_BWDealerResponseBean ######\n' + respBean);


                } else {
                    util.logError(resp.getStatusCode() + ' - ' + resp.getStatus() + '\n' + resp.getBody());
                    respBean = (TC_BWDealerResponseBean) JSON.deserialize(responseJSON, TC_BWDealerResponseBean.class);
                }
                insert new Integration_Log__c(
                    Name = 'Infolease Create Dealer',
                    Record_Id__c = '',
                    Status__c = (resp.getStatusCode() == 200 ? 'Success' : 'Error'),
                    Error_Code__c = resp.getStatusCode() + '',
                    Error_Message__c = resp.getStatus(),
                    Request_Message__c = editrequestJSON,
                    Response_Message__c= resp.getBody()
                );
            } catch (Exception e) {
                System.debug(new TC_BWcreateDealerCalloutException (e.getMessage() + e.getStackTraceString()));
                throw new TC_BWcreateDealerCalloutException (e.getMessage());
            }
        } else {
            respBean = new TC_BWDealerResponseBean ();
        }
        return respBean;
    }

    public class TC_BWcreateDealerCalloutException extends Exception {}
}