peac_dev/force-app/main/default/objects/IL10_Flag__c/IL10_Flag__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Setting to indicate whether or not the Infolease integration classes should process logic to dewtermine if records update IL9 or IL 10. Used primarily as a backout mechanism.</description>
    <label>IL10 Flag</label>
</CustomObject>

peac_dev/force-app/main/default/objects/Insurance__c/Insurance__c.object-meta.xml
<CustomObject>
    <label>Insurance</label>
    <nameField>
        <displayFormat>INS-{0000}</displayFormat>
        <label>Insurance Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Insurance</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

peac_dev/force-app/main/default/objects/Insurance__c/fields/Cancel_Date__c.field-meta.xml
<CustomField>
    <fullName>Cancel_Date__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Cancel Date</label>
    <type>Date</type>
</CustomField>

peac_dev/force-app/main/default/objects/Insurance__c/fields/Carrier__c.field-meta.xml
<CustomField>
    <fullName>Carrier__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Carrier Name</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

peac_dev/force-app/main/default/objects/Insurance__c/fields/Effective_Date__c.field-meta.xml
<CustomField>
    <fullName>Effective_Date__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Effective Date</label>
    <type>Date</type>
</CustomField>

peac_dev/force-app/main/default/objects/Insurance__c/fields/Expiration_Date__c.field-meta.xml
<CustomField>
    <fullName>Expiration_Date__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Expiration Date</label>
    <type>Date</type>
</CustomField>

peac_dev/force-app/main/default/objects/Insurance__c/fields/Infolease_Environment__c.field-meta.xml
<CustomField>
    <fullName>Infolease_Environment__c</fullName>
    <label>Infolease Environment</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>9</fullName>
            </value>
            <value>
                <fullName>10</fullName>
            </value>
            <value>
                <fullName>C</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

peac_dev/force-app/main/default/objects/Insurance__c/fields/Insurance_Id__c.field-meta.xml
<CustomField>
    <fullName>Insurance_Id__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <externalId>true</externalId>
    <label>Insurance Id</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

peac_dev/force-app/main/default/objects/Insurance__c/fields/Policy_Status__c.field-meta.xml
<CustomField>
    <fullName>Policy_Status__c</fullName>
    <label>Policy Status</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Infolease_Environment__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>01</fullName>
                <label>Marlin Business Bank</label>
            </value>
            <value>
                <fullName>00</fullName>
                <label>Marlin Leasing Corp</label>
            </value>
            <value>
                <fullName>02</fullName>
                <label>PEAC</label>
            </value>
            <value>
                <fullName>05</fullName>
                <label>Outside Coverage</label>
            </value>
            <value>
                <fullName>06</fullName>
                <label>Marlin Program</label>
            </value>
            <value>
                <fullName>07</fullName>
                <label>Reinstated</label>
            </value>
            <value>
                <fullName>08</fullName>
                <label>Voided - No Coverage</label>
            </value>
            <value>
                <fullName>09</fullName>
                <label>Non-Solicitable</label>
            </value>
            <value>
                <fullName>10</fullName>
                <label>Cancel Non Payment</label>
            </value>
            <value>
                <fullName>11</fullName>
                <label>Disposed</label>
            </value>
            <value>
                <fullName>12</fullName>
                <label>Self Insured</label>
            </value>
            <value>
                <fullName>13</fullName>
                <label>Not Required</label>
            </value>
            <value>
                <fullName>14</fullName>
                <label>Pending Auto</label>
            </value>
            <value>
                <fullName>15</fullName>
                <label>Outside Ins Auto</label>
            </value>
            <value>
                <fullName>16</fullName>
                <label>TV In-House</label>
            </value>
            <value>
                <fullName>17</fullName>
                <label>TV Reinstated</label>
            </value>
            <value>
                <fullName>18</fullName>
                <label>Canceled - Delinquent</label>
            </value>
            <value>
                <fullName>19</fullName>
                <label>TV Disposed</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

peac_dev/force-app/main/default/classes/SL_InfoleaseInsuranceHelper.cls
public with sharing class SL_InfoleaseInsuranceHelper {
    private List<String> errorMessages;
    private Insurance__c thisInsurance;
    public Id recordId;
    Boolean isIL10;

    private SL_InfoleaseInsuranceRequestWrapper request;
    public SL_InfoleaseUtils util = SL_InfoleaseUtils.getInstance();

    public SL_InfoleaseInsuranceHelper(Id insuranceId) {
        recordId = insuranceId;
        thisInsurance = getFields(recordId);
        IL10_Flag__c il10Setting = IL10_Flag__c.getValues('GeneralSetting');
        isIL10 = false;
        if(thisInsurance != null){
            isIL10 = TC_BWUtility.isIL10Record(thisInsurance);
        }
    }

    public SL_InfoleaseInsuranceRequestWrapper createRequest () {
        mapFields();
        return request;
    }

    public Boolean validate() {
        errorMessages = new List<String>();

        if (thisInsurance == null) {
            errorMessages.add('Null object sent to updateInsurance!');
            return errorMessages.isEmpty();
        }
        return errorMessages.isEmpty();
    }

    public List<String> getErrorMessages() { return errorMessages; }


    public boolean isValid() {
        return errorMessages.isEmpty();
    }

    private SL_InfoleaseInsuranceRequestWrapper mapFields() {

        request = new SL_InfoleaseInsuranceRequestWrapper();

        request.Request.UserId = util.getServiceSettings().UserId__c == null ? 'servcloud' : util.getServiceSettings().UserId__c;

        request.Request.InsuranceId = thisInsurance.Insurance_Id__c;
        request.Request.INSUR_CARRIER = thisInsurance.Carrier__c;
        request.Request.INSUR_EFFECTIVE_DATE = thisInsurance.Effective_Date__c != null ? String.valueOf(thisInsurance.Effective_Date__c.format()) : null;
        request.Request.INSUR_EXPIRE_DATE = thisInsurance.Expiration_Date__c != null ? String.valueOf(thisInsurance.Expiration_Date__c.format()) : null;
        request.Request.INSUR_CANCEL_DATE = thisInsurance.Cancel_Date__c != null ? String.valueOf(thisInsurance.Cancel_Date__c.format()) : null;
        request.Request.INSUR_STATUS = isIL10? thisInsurance.Policy_Status__c: '';
        //End Mapping
        return request;

    }

    public String mapSpecificFields(String insuranceId, Set<String> changedFieldSet){

        List<String> fieldList = new List<String>(changedFieldSet);
        String effectiveDate = thisInsurance.Effective_Date__c != null ? String.valueOf(thisInsurance.Effective_Date__c.format()) : '';
        String expireDate = thisInsurance.Expiration_Date__c != null ? String.valueOf(thisInsurance.Expiration_Date__c.format()) : '';
        String cancelDate = thisInsurance.Cancel_Date__c != null ? String.valueOf(thisInsurance.Cancel_Date__c.format()) : '';

        Map<String,String> wrapVarFieldMap = new Map<String,String>{
            'Insurance_Id__c' => 'InsuranceId',
            'Carrier__c' => 'INSUR.CARRIER',
            'Effective_Date__c' => 'INSUR.EFFECTIVE.DATE' ,
            'Expiration_Date__c' => 'INSUR.EXPIRE.DATE' ,
            'Cancel_Date__c' => 'INSUR.CANCEL.DATE',
            'Policy_Status__c' => 'INSUR.STATUS'
        }; 

        JSONGenerator gen = JSON.createGenerator(true);

        gen.writeStartObject();
        for(String thisField : fieldList){
            if(thisField == 'Effective_Date__c'){
                gen.writeStringField(wrapVarFieldMap.get(thisField), effectiveDate);
            }
            else if(thisField == 'Expiration_Date__c'){
                gen.writeStringField(wrapVarFieldMap.get(thisField), expireDate);
            }
            else if(thisField == 'Cancel_Date__c'){
                gen.writeStringField(wrapVarFieldMap.get(thisField), cancelDate);
            }
            else if(thisField == 'Policy_Status__c'){
                gen.writeStringField(wrapVarFieldMap.get(thisField), isIL10? thisInsurance.Policy_Status__c: '');
            }
            else {
                gen.writeStringField(wrapVarFieldMap.get(thisField), String.valueOf(thisInsurance.get(thisField) != null ? thisInsurance.get(thisField) : ''));
            }
        }
        gen.writeStringField('UserId', util.getServiceSettings().UserId__c == null ? 'servcloud' : util.getServiceSettings().UserId__c);
        gen.writeEndObject();

        String pretty = gen.getAsString();

        pretty = '{'+
                '"Header" : {'+
                '"NitroApi" : "BW.UPDATE.INSURANCE"'+
                '},'+
                '"Request" : '+ pretty +
                '}';
        return pretty;
    }

    private Insurance__c getFields(Id insuranceId) {
        Insurance__c thisInsurance;
        try{
            thisInsurance = [SELECT Carrier__c, Effective_Date__c, Expiration_Date__c, Cancel_Date__c,
                            Insurance_Id__c, Policy_Status__c, Infolease_Environment__c
                            FROM Insurance__c  
                            WHERE Id = :insuranceId 
                            LIMIT 1];
            return thisInsurance;
        }catch(Exception e){
            return null;
        }
    }
}