peac_dev/force-app/main/default/objects/Dealer_Surveillance__c/Dealer_Surveillance__c.object-meta.xml
<CustomObject>
    <label>Dealer Surveillance</label>
    <nameField>
        <displayFormat>A-{00000}</displayFormat>
        <label>Dealer Surveillance Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Dealer Surveillances</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

peac_dev/force-app/main/default/objects/Dealer_Surveillance__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Dealer Surveillances</relationshipLabel>
    <relationshipName>Dealer_Surveillances</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

peac_dev/force-app/main/default/objects/Dealer_Surveillance__c/fields/Actual_Vs_Projected_Loss__c.field-meta.xml
<CustomField>
    <fullName>Actual_Vs_Projected_Loss__c</fullName>
    <label>Actual Vs Projected Loss</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

peac_dev/force-app/main/default/objects/Dealer_Surveillance__c/fields/Created_via_Batch__c.field-meta.xml
<CustomField>
    <fullName>Created_via_Batch__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Created via Batch</label>
    <type>Checkbox</type>
</CustomField>

peac_dev/force-app/main/default/objects/Dealer_Surveillance__c/fields/Dealer_Surveillance__c.field-meta.xml
<CustomField>
    <fullName>Dealer_Surveillance__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Dealer Surveillance</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

peac_dev/force-app/main/default/objects/Dealer_Surveillance__c/fields/Next_Scheduled_Review__c.field-meta.xml
<CustomField>
    <fullName>Next_Scheduled_Review__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Next Scheduled Review</label>
    <type>Date</type>
</CustomField>

peac_dev/force-app/main/default/objects/Dealer_Surveillance__c/fields/Review_Date__c.field-meta.xml
<CustomField>
    <fullName>Review_Date__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Review Date</label>
    <type>Date</type>
</CustomField>

peac_dev/force-app/main/default/objects/Dealer_Surveillance__c/fields/Review_Type__c.field-meta.xml
<CustomField>
    <fullName>Review_Type__c</fullName>
    <label>Review Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Review_Type</valueSetName>
    </valueSet>
</CustomField>

peac_dev/force-app/main/default/objects/Dealer_Surveillance__c/fields/Waiting_To_Be_Sent_To_Bridgeware__c.field-meta.xml
<CustomField>
    <fullName>Waiting_To_Be_Sent_To_Bridgeware__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Waiting To Be Sent To Bridgeware</label>
    <type>Checkbox</type>
</CustomField>

peac_dev/force-app/main/default/classes/TC_DealerSurveillancePortfolioBatch.cls
public class TC_DealerSurveillancePortfolioBatch implements Database.Batchable<SObject> {
    
    public static Date todayDate = Date.today();
    
	public Database.QueryLocator start(Database.BatchableContext bc) {
        String query = 'SELECT Id, Review_Date__c, Account__c, Account__r.X1_app_in_the_last_12_months__c, Account__r.Actual_Vs_Projected_Loss__c, Account__r.Account_Percentage31__c, Account__r.Account_Total_CBR__c, Account__r.X1_app_in_the_last_24_months__c, Account__r.Portfolio_Review_Threshold__c, Account__r.Last_Reviewed_Threshold__c, Account__r.Account_Dealer_LTD_Volume__c, Account__r.Surveillances_Incomplete__c from Dealer_Surveillance__c WHERE Next_Scheduled_Review__c = TODAY';
        return Database.getQueryLocator(query);
    }
    
    public void execute (Database.BatchableContext bc, List<Dealer_Surveillance__c> suvs) {
        List <Dealer_Surveillance__c> insertList = new List <Dealer_Surveillance__c> ();

        Set<Id> accIds = new Set<Id>();

        for(Dealer_Surveillance__c suv : suvs){
            accIds.add(suv.Account__c);
        }

        //Will use this map to find the date of the last portfolio review for the account
        Map<Id, Account> accounts = new Map<Id, Account> (
            [SELECT Id, Name, 
            (SELECT Id, Review_Date__c 
            FROM Dealer_Surveillances__r 
            WHERE Review_Type__c = 'Portfolio Threshold' 
            ORDER BY Review_Date__c DESC Limit 1) 
            FROM Account 
            WHERE Id IN :accIds]);
        
        for (Dealer_Surveillance__c suv : suvs) {
            if (suv.Account__r.Portfolio_Review_Threshold__c != null && 
                Decimal.valueOf (suv.Account__r.Portfolio_Review_Threshold__c.remove(',')) >= suv.Account__r.Account_Dealer_LTD_Volume__c) {

                    Boolean meetsLastThresholdCritera = false;
                    if(suv.Account__r.Last_Reviewed_Threshold__c == null){
                        meetsLastThresholdCritera = true;
                    }else if(Decimal.valueOf (suv.Account__r.Last_Reviewed_Threshold__c.remove(',')) <= Decimal.valueOf (suv.Account__r.Portfolio_Review_Threshold__c.remove(','))){
                        meetsLastThresholdCritera = true;
                    }
                    System.debug('Meets Last Threshold Criteria:' + meetsLastThresholdCritera);
                    System.debug('Is port reviews empty:' + accounts.get(suv.Account__c).Dealer_Surveillances__r.isEmpty());
                    System.debug('Portfolio reviews' + accounts.get(suv.Account__c).Dealer_Surveillances__r);

                    //Added criteria so a Surveillance object is only created if Last Review Threshold is <= new threshold and is the last review was at least 12 months ago for SAL-2923
                    if(meetsLastThresholdCritera &&
                    accounts.get(suv.Account__c).Dealer_Surveillances__r.isEmpty()){
                        insertList.add (new Dealer_Surveillance__c (Account__c = suv.Account__c
                                                          	, Review_Type__c = 'Portfolio Threshold'
                                                          	, Review_Date__c = todayDate
                                                          	, Status__c = 'In Queue'
                                                            , Waiting_To_Be_Sent_To_Bridgeware__c = true
                                                            , Created_via_Batch__c = true));
                    }else if (meetsLastThresholdCritera &&
                    accounts.get(suv.Account__c).Dealer_Surveillances__r[0].Review_Date__c <= todayDate.addMonths(-12)){
                        insertList.add (new Dealer_Surveillance__c (Account__c = suv.Account__c
                                                          	, Review_Type__c = 'Portfolio Threshold'
                                                          	, Review_Date__c = todayDate
                                                          	, Status__c = 'In Queue'
                                                            , Waiting_To_Be_Sent_To_Bridgeware__c = true
                                                            , Created_via_Batch__c = true));
                    }  
            }
        }
        
        if (!insertList.isEmpty()) insert insertList;
    }
    
    public void finish(Database.BatchableContext bc) {
        System.debug('>>> finish TC_DealerSurveillanceBatch');
    }

}