peac_dev/force-app/main/default/objects/Dealer_Surveillance__c/Dealer_Surveillance__c.object-meta.xml
<CustomObject>
    <label>Dealer Surveillance</label>
    <nameField>
        <displayFormat>A-{00000}</displayFormat>
        <label>Dealer Surveillance Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Dealer Surveillances</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

peac_dev/force-app/main/default/objects/Dealer_Surveillance__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Dealer Surveillances</relationshipLabel>
    <relationshipName>Dealer_Surveillances</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

peac_dev/force-app/main/default/objects/Dealer_Surveillance__c/fields/Actual_Vs_Projected_Loss__c.field-meta.xml
<CustomField>
    <fullName>Actual_Vs_Projected_Loss__c</fullName>
    <label>Actual Vs Projected Loss</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

peac_dev/force-app/main/default/objects/Dealer_Surveillance__c/fields/Dealer_Surveillance__c.field-meta.xml
<CustomField>
    <fullName>Dealer_Surveillance__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Dealer Surveillance</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

peac_dev/force-app/main/default/objects/Dealer_Surveillance__c/fields/Model_Hit__c.field-meta.xml
<CustomField>
    <fullName>Model_Hit__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Model Hit</label>
    <referenceTo>Dealer_Surveillance_Model__c</referenceTo>
    <relationshipLabel>Dealer Surveillances</relationshipLabel>
    <relationshipName>Dealer_Surveillances</relationshipName>
    <type>Lookup</type>
</CustomField>

peac_dev/force-app/main/default/objects/Dealer_Surveillance__c/fields/Net_Investment__c.field-meta.xml
<CustomField>
    <fullName>Net_Investment__c</fullName>
    <formula>Account__r.Net_Investment__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Net Investment</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

peac_dev/force-app/main/default/objects/Dealer_Surveillance__c/fields/Review_Type__c.field-meta.xml
<CustomField>
    <fullName>Review_Type__c</fullName>
    <label>Review Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Review_Type</valueSetName>
    </valueSet>
</CustomField>

peac_dev/force-app/main/default/objects/Dealer_Surveillance__c/fields/Total_Past_Due__c.field-meta.xml
<CustomField>
    <fullName>Total_Past_Due__c</fullName>
    <label>Total Past Due %</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

peac_dev/force-app/main/default/objects/Dealer_Surveillance_Model__c/Dealer_Surveillance_Model__c.object-meta.xml
<CustomObject>
    <label>Dealer Surveillance Model</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Model Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Dealer Surveillance Models</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

peac_dev/force-app/main/default/objects/Dealer_Surveillance_Model__c/fields/Actual_Vs_Project_Max__c.field-meta.xml
<CustomField>
    <fullName>Actual_Vs_Project_Max__c</fullName>
    <label>Actual Vs Project Max</label>
    <precision>18</precision>
    <scale>4</scale>
    <type>Percent</type>
</CustomField>

peac_dev/force-app/main/default/objects/Dealer_Surveillance_Model__c/fields/Delinquency_Max__c.field-meta.xml
<CustomField>
    <fullName>Delinquency_Max__c</fullName>
    <label>Delinquency Max</label>
    <precision>18</precision>
    <scale>4</scale>
    <type>Percent</type>
</CustomField>

peac_dev/force-app/main/default/objects/Dealer_Surveillance_Model__c/fields/Net_Investment_Maximum__c.field-meta.xml
<CustomField>
    <fullName>Net_Investment_Maximum__c</fullName>
    <label>Net Investment Maximum</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

peac_dev/force-app/main/default/objects/Dealer_Surveillance_Model__c/fields/Net_Investment_Minimum__c.field-meta.xml
<CustomField>
    <fullName>Net_Investment_Minimum__c</fullName>
    <label>Net Investment Minimum</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

peac_dev/force-app/main/default/classes/DealerReviewer.cls
// Andrew
// Responsible for reviewing dealers based on models
// https://marlinbusiness.atlassian.net/browse/SAL-1590

// models should always be exclusive

public class DealerReviewer {
    
    private List <Dealer_Surveillance_Model__c > models;
    private Map <String, Id> modelMap;
    
    public DealerReviewer () {
        this.models = new List < Dealer_Surveillance_Model__c > ([SELECT Actual_Vs_Project_Max__c 
                                                                    , Delinquency_Max__c
                                                                    , Net_Investment_Maximum__c 
                                                                    , Net_Investment_Minimum__c 
                                                                    , Name
                                                                  	, Id
                                                                  FROM Dealer_Surveillance_Model__c
                                                                  ORDER BY Name ASC]);
        this.modelMap = new Map <String, Id> ();
        
        for (Dealer_Surveillance_Model__c model : this.models) {
            this.modelMap.put (model.Name, model.Id);
        }
    }
    
    public Map <Id, String> review (List <Account> dealers) {
        
        Map <Id, String> reviewResults = new Map <Id, String> ();
        if (dealers == null || dealers.isEmpty ()) return reviewResults;

        for (Account dealer : dealers) {
            for (Dealer_Surveillance_Model__c model : this.models) {
                if (modelCompare(dealer, model)) {
                    System.debug ('!!!!! hit');
                    System.debug ('!!!!! hit dealer.Id ' + dealer.Id);
                    System.debug ('!!!!! hit model.Name ' + model.Name);


                    reviewResults.put (dealer.Id, model.Name);
                    break;
                }
            }
        }
        System.debug ('!!!!! hit reviewResults ' + reviewResults);

        return reviewResults;
    }
    
    public Id getModelIdByName (String name) {
        return this.modelMap.get (name);
    }
    
    public Boolean modelCompare (Account dealer, Dealer_Surveillance_Model__c model) {
        return dealer.Net_Investment__c >= model.Net_Investment_Minimum__c
           && dealer.Net_Investment__c <= model.Net_Investment_Maximum__c
           && dealer.Actual_Vs_Projected_Loss__c  < model.Actual_Vs_Project_Max__c
           && dealer.Account_Total_Past_Due_Percentage__c < model.Delinquency_Max__c
           && dealer.X1_app_in_the_last_12_months__c >= 1;// ask jeff about this one. model says number of months with an app which is only tracked at 12 and 24
    }



    public void reviewSurveillances (List<Dealer_Surveillance__c> surveillances) {
                        System.debug ('!!!!! reviewSurveillances');

        Set <Id> accIds = new Set <Id> ();        
        
        for (Dealer_Surveillance__c suv : surveillances) {
            accIds.add (suv.Account__c);
        }

        Map <Id, Account> accs = new Map <Id, Account> ([SELECT Id, Actual_Vs_Projected_Loss__c, Account_Total_Past_Due_Percentage__c, X1_app_in_the_last_12_months__c   FROM Account WHERE Id IN :accIds]);

        for (Dealer_Surveillance__c suv : surveillances) {
            if(suv.Review_Type__c == 'Portfolio Threshold' && suv.Status__c !='Completed'){
                for (Dealer_Surveillance_Model__c model : this.models) {
                    if (modelCompareSurveillances(suv, model, accs.get(suv.Account__c))) {
                        System.debug ('!!!!! hit reviewSurveillances');
                        suv.Model_Hit__c = model.Id;
                        break;
                    }
                }
            }
        }
    }

        public Boolean modelCompareSurveillances (Dealer_Surveillance__c suv, Dealer_Surveillance_Model__c model, Account dealer) {
            return suv.Net_Investment__c >= model.Net_Investment_Minimum__c
            && suv.Net_Investment__c <= model.Net_Investment_Maximum__c
            && suv.Actual_Vs_Projected_Loss__c  < model.Actual_Vs_Project_Max__c
            && suv.Total_Past_Due__c  < model.Delinquency_Max__c
            && dealer.X1_app_in_the_last_12_months__c >= 1;// ask jeff about this one. model says number of months with an app which is only tracked at 12 and 24
        }



}