peac_dev/force-app/main/default/objects/Dealer_Surveillance__c/Dealer_Surveillance__c.object-meta.xml
<CustomObject>
    <label>Dealer Surveillance</label>
    <nameField>
        <displayFormat>A-{00000}</displayFormat>
        <label>Dealer Surveillance Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Dealer Surveillances</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

peac_dev/force-app/main/default/objects/Dealer_Surveillance__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Dealer Surveillances</relationshipLabel>
    <relationshipName>Dealer_Surveillances</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

peac_dev/force-app/main/default/objects/Dealer_Surveillance__c/fields/Dealer_Surveillance__c.field-meta.xml
<CustomField>
    <fullName>Dealer_Surveillance__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Dealer Surveillance</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

peac_dev/force-app/main/default/objects/Dealer_Surveillance__c/fields/Recommended_Action__c.field-meta.xml
<CustomField>
    <fullName>Recommended_Action__c</fullName>
    <label>Recommended Action</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Action</valueSetName>
    </valueSet>
</CustomField>

peac_dev/force-app/main/default/objects/Dealer_Surveillance__c/fields/Recommended_Next_Review__c.field-meta.xml
<CustomField>
    <fullName>Recommended_Next_Review__c</fullName>
    <label>Recommended Next Review</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Next_Review</valueSetName>
    </valueSet>
</CustomField>

peac_dev/force-app/main/default/objects/Dealer_Surveillance__c/fields/Review_Date__c.field-meta.xml
<CustomField>
    <fullName>Review_Date__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Review Date</label>
    <type>Date</type>
</CustomField>

peac_dev/force-app/main/default/classes/TC_CreateSurveillanceOnWatchList.cls
public class TC_CreateSurveillanceOnWatchList {
    public static void createSurveillanceOnWatchList (Map <Id, Account> oldMap, Map <Id, Account> newMap) {
        Set <Id> accIds = new Set <Id> ();
        for (Account acc : newMap.values ()) {
            if ((acc.Account_Dealer_Status__c == 'Watch List') && (oldMap == null || oldMap.get (acc.Id).Account_Dealer_Status__c != 'Watch List')) {
                accIds.add (acc.Id);
            }
        }
        if (!accIds.isEmpty()) {
            Map <Id, Dealer_Surveillance__c> cantCreateSUVRecord = new Map <Id, Dealer_Surveillance__c> ();

            for (Dealer_Surveillance__c suv : [SELECT Id, Account__c  FROM Dealer_Surveillance__c WHERE Status__c != 'Completed']) {
                cantCreateSUVRecord.put (suv.Account__c, suv);
            }

            List <Dealer_Surveillance__c> suvs = new List <Dealer_Surveillance__c> ();

            Date todayDate = Date.today ();

            for (Id accId : accIds) {
                if (cantCreateSUVRecord.get (accId) == null) {
                    suvs.add (new Dealer_Surveillance__c (Account__c = accId
                            , Recommended_Action__c = 'Approved'
                            , Recommended_Next_Review__c = '12 mos'
                            , Review_Date__c = todayDate));
                }
            }

            if (!suvs.isEmpty ()) insert suvs;
        }
    }

}