peac_dev/force-app/main/default/objects/Dealer_Surveillance__c/Dealer_Surveillance__c.object-meta.xml
<CustomObject>
    <label>Dealer Surveillance</label>
    <nameField>
        <displayFormat>A-{00000}</displayFormat>
        <label>Dealer Surveillance Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Dealer Surveillances</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

peac_dev/force-app/main/default/objects/Dealer_Surveillance__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Dealer Surveillances</relationshipLabel>
    <relationshipName>Dealer_Surveillances</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

peac_dev/force-app/main/default/objects/Dealer_Surveillance__c/fields/Dealer_Surveillance__c.field-meta.xml
<CustomField>
    <fullName>Dealer_Surveillance__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Dealer Surveillance</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

peac_dev/force-app/main/default/objects/Dealer_Surveillance__c/fields/Net_Investment__c.field-meta.xml
<CustomField>
    <fullName>Net_Investment__c</fullName>
    <formula>Account__r.Net_Investment__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Net Investment</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

peac_dev/force-app/main/default/objects/Dealer_Surveillance__c/fields/Review_Type__c.field-meta.xml
<CustomField>
    <fullName>Review_Type__c</fullName>
    <label>Review Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Review_Type</valueSetName>
    </valueSet>
</CustomField>

peac_dev/force-app/main/default/classes/TC_ThresholdReachedCreateSurv.cls
public class TC_ThresholdReachedCreateSurv {
public static void thresholdReachedCreateSurv (Map <Id, Account> oldMap, Map <Id, Account> newMap) {
        
        // throw values in maps so we don't have to loop inside of a loop
        Map <String, String> thresholdMap = new Map <String, String> ();
        Map <String, Id> accIdRefMap = new Map <String, Id> ();
        
        for (Account acc : newMap.values ()) {
            if (acc.Net_Investment__c!= null && (oldMap == null || acc.Net_Investment__c != oldMap.get (acc.Id).Net_Investment__c)) {
                String thresh = TC_ValueToThreshold.valueToThreshold (acc.Net_Investment__c);
                if (thresh != null) {
                    String key = TC_CreateThresholdKey.createThresholdKey (acc.Id, thresh);
                    thresholdMap.put (key, thresh);
                    accIdRefMap.put (key, acc.Id);
                } 
            }
                
        }
        
        if (accIdRefMap.isEmpty() || thresholdMap.isEmpty()) return;
        
        for (Dealer_Surveillance__c surv : [SELECT Id, Account__c, Dealer_Surveillance__c FROM Dealer_Surveillance__c WHERE Account__c IN :accIdRefMap.values() AND Review_Type__c = 'Portfolio Threshold' AND Dealer_Surveillance__c Like 'Portfolio Threshold %']) {
            List <String> splitName = surv.Dealer_Surveillance__c.split (' ');
            if (splitName.size() == 3) {
                String thresh = splitName[2];
                String key = TC_CreateThresholdKey.createThresholdKey (surv.Account__c, thresh);
                if (thresholdMap.get (key) != null) {
                    thresholdMap.remove (key);
                }
            }
        }
        
        if (thresholdMap.isEmpty ()) return;
        
        List <Dealer_Surveillance__c> insertList = new List <Dealer_Surveillance__c> ();
        
        for (String key : thresholdMap.keySet ()) {
            insertList.add (new Dealer_Surveillance__c (Account__c = accIdRefMap.get (key)
                                                       , Dealer_Surveillance__c = 'Portfolio Threshold ' + thresholdMap.get (key)
                                                       , Review_Type__c = 'Portfolio Threshold'
                                                       , Status__c = 'In Queue'));
        }
        
        insert insertList;
        

    }
}