peac_dev/force-app/main/default/objects/Dealer_Surveillance__c/Dealer_Surveillance__c.object-meta.xml
<CustomObject>
    <label>Dealer Surveillance</label>
    <nameField>
        <displayFormat>A-{00000}</displayFormat>
        <label>Dealer Surveillance Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Dealer Surveillances</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

peac_dev/force-app/main/default/objects/Dealer_Surveillance__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Dealer Surveillances</relationshipLabel>
    <relationshipName>Dealer_Surveillances</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

peac_dev/force-app/main/default/objects/Dealer_Surveillance__c/fields/Actual_Vs_Projected_Loss__c.field-meta.xml
<CustomField>
    <fullName>Actual_Vs_Projected_Loss__c</fullName>
    <label>Actual Vs Projected Loss</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

peac_dev/force-app/main/default/objects/Dealer_Surveillance__c/fields/Dealer_Surveillance__c.field-meta.xml
<CustomField>
    <fullName>Dealer_Surveillance__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Dealer Surveillance</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

peac_dev/force-app/main/default/objects/Dealer_Surveillance__c/fields/Net_Investment__c.field-meta.xml
<CustomField>
    <fullName>Net_Investment__c</fullName>
    <formula>Account__r.Net_Investment__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Net Investment</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

peac_dev/force-app/main/default/objects/Dealer_Surveillance_Model__c/Dealer_Surveillance_Model__c.object-meta.xml
<CustomObject>
    <label>Dealer Surveillance Model</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Model Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Dealer Surveillance Models</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

peac_dev/force-app/main/default/objects/Dealer_Surveillance_Model__c/fields/Actual_Vs_Project_Max__c.field-meta.xml
<CustomField>
    <fullName>Actual_Vs_Project_Max__c</fullName>
    <label>Actual Vs Project Max</label>
    <precision>18</precision>
    <scale>4</scale>
    <type>Percent</type>
</CustomField>

peac_dev/force-app/main/default/objects/Dealer_Surveillance_Model__c/fields/Delinquency_Max__c.field-meta.xml
<CustomField>
    <fullName>Delinquency_Max__c</fullName>
    <label>Delinquency Max</label>
    <precision>18</precision>
    <scale>4</scale>
    <type>Percent</type>
</CustomField>

peac_dev/force-app/main/default/objects/Dealer_Surveillance_Model__c/fields/Net_Investment_Maximum__c.field-meta.xml
<CustomField>
    <fullName>Net_Investment_Maximum__c</fullName>
    <label>Net Investment Maximum</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

peac_dev/force-app/main/default/objects/Dealer_Surveillance_Model__c/fields/Net_Investment_Minimum__c.field-meta.xml
<CustomField>
    <fullName>Net_Investment_Minimum__c</fullName>
    <label>Net Investment Minimum</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

peac_dev/force-app/main/default/classes/TC_DealerSurvModelBackfillBatchTest.cls
@isTest public class TC_DealerSurvModelBackfillBatchTest {
    @isTest public static void test () {
        Account acc = new Account (X1_app_in_the_last_12_months__c = 1
                                   , Net_Investment__c = 2
                                   , Actual_Vs_Projected_Loss__c = 1
                                   , Account_Total_Past_Due_Percentage__c = 1
                                   , Name = 'test');
        insert acc;
        
        insert new Dealer_Surveillance__c (Status__c = 'In Process', Account__c = acc.Id);
        insert new Dealer_Surveillance_Model__c (Actual_Vs_Project_Max__c = 3
                                                , Delinquency_Max__c = 3
                                                , Net_Investment_Maximum__c = 999999999
                                                , Net_Investment_Minimum__c = 0
                                                , Name = 'test');
		Test.startTest();
        Database.executeBatch(new TC_DealerSurveillanceModelBackfillBatch(), 1);
        Test.stopTest();
    }
}