peac_dev/force-app/main/default/objects/Remarketer_Matrix_Obj__c/Remarketer_Matrix_Obj__c.object-meta.xml
<CustomObject>
    <label>Remarketer Matrix</label>
    <nameField>
        <displayFormat>RM-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Remarketer Matrix</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

peac_dev/force-app/main/default/objects/Remarketer_Matrix_Obj__c/fields/Equipment_Subtype__c.field-meta.xml
<CustomField>
    <fullName>Equipment_Subtype__c</fullName>
    <label>Equipment Subtype</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Equipment_Sub_Category</valueSetName>
    </valueSet>
</CustomField>

peac_dev/force-app/main/default/objects/Remarketer_Matrix_Obj__c/fields/Equipment_Type__c.field-meta.xml
<CustomField>
    <fullName>Equipment_Type__c</fullName>
    <label>Equipment Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Equipment_Type</valueSetName>
    </valueSet>
</CustomField>

peac_dev/force-app/main/default/objects/Remarketer_Matrix_Obj__c/fields/Return_Warehouse_Code__c.field-meta.xml
<CustomField>
    <fullName>Return_Warehouse_Code__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Return Warehouse Code</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

peac_dev/force-app/main/default/objects/Remarketer_Matrix_Obj__c/fields/Synced__c.field-meta.xml
<CustomField>
    <fullName>Synced__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Synced</label>
    <type>Checkbox</type>
</CustomField>

peac_dev/force-app/main/default/classes/RemarketerMatrixSyncClient.cls
public with sharing class RemarketerMatrixSyncClient {
    public static void syncRemarketersToSandbox() {
          // Obtener registros modificados recientemente
          List<Remarketer_Matrix_Obj__c> recent = [
              SELECT Equipment_Type__c, Equipment_Subtype__c, State__c, Return_Warehouse_Code__c 
              FROM Remarketer_Matrix_Obj__c 
              WHERE Synced__c = false
          ];
  
          // Mapear a formato JSON
          List<RemarketerMatrixSyncService.RemarketerMatrixWrapper> payload = new List<RemarketerMatrixSyncService.RemarketerMatrixWrapper>();
          for (Remarketer_Matrix_Obj__c r : recent) {
              RemarketerMatrixSyncService.RemarketerMatrixWrapper record = new RemarketerMatrixSyncService.RemarketerMatrixWrapper();
              record.EquipmentType = r.Equipment_Type__c ;
              record.EquipmentSubType = r.Equipment_Subtype__c ;
              record.State = r.State__c ;
              record.WarehouseCode = r.Return_Warehouse_Code__c;
              r.Synced__c=true;
              payload.add(record);
          }
  
          // Enviar callout
          HttpRequest req = new HttpRequest();
          req.setEndpoint('callout:Lower_Sandbox/services/apexrest/RemarketerMatrixSync');
          req.setMethod('POST');
          req.setHeader('Content-Type', 'application/json');
          req.setBody(JSON.serialize(payload));
  
          Http http = new Http();
          try {
              HttpResponse res = http.send(req);
              System.debug('Req: ' + req.getBody());
              if(res.getBody().contains('Success')){
                  update recent;
              }
              System.debug('Respuesta: ' + res.getBody());
          } catch (Exception ex) {
              System.debug('Error en callout REST: ' + ex.getMessage());
          }
      }
  }