peac_dev/force-app/main/default/objects/Remarketer_Matrix_Obj__c/Remarketer_Matrix_Obj__c.object-meta.xml
<CustomObject>
    <label>Remarketer Matrix</label>
    <nameField>
        <displayFormat>RM-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Remarketer Matrix</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

peac_dev/force-app/main/default/objects/Remarketer_Matrix_Obj__c/fields/Equipment_Subtype__c.field-meta.xml
<CustomField>
    <fullName>Equipment_Subtype__c</fullName>
    <label>Equipment Subtype</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Equipment_Sub_Category</valueSetName>
    </valueSet>
</CustomField>

peac_dev/force-app/main/default/objects/Remarketer_Matrix_Obj__c/fields/Equipment_Type__c.field-meta.xml
<CustomField>
    <fullName>Equipment_Type__c</fullName>
    <label>Equipment Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Equipment_Type</valueSetName>
    </valueSet>
</CustomField>

peac_dev/force-app/main/default/objects/Remarketer_Matrix_Obj__c/fields/Return_Warehouse_Code__c.field-meta.xml
<CustomField>
    <fullName>Return_Warehouse_Code__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Return Warehouse Code</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

peac_dev/force-app/main/default/classes/RemarketerMatrixSyncService.cls
@RestResource(urlMapping='/RemarketerMatrixSync')
global with sharing class RemarketerMatrixSyncService {

    @HttpPost
    global static String upsertRemarketers() {
        String requestBody = RestContext.request.requestBody.toString();
        System.debug('requestBody  ' + requestBody);

        List<RemarketerMatrixWrapper> remarketers = (List<RemarketerMatrixWrapper>) JSON.deserializeStrict(requestBody, List<RemarketerMatrixWrapper>.class);
        System.debug('upsertRemarketers ' + remarketers);
        List<Remarketer_Matrix_Obj__c> toUpsert = new List<Remarketer_Matrix_Obj__c>();

        for (RemarketerMatrixSyncService.RemarketerMatrixWrapper wrapper : remarketers) {
            toUpsert.add(new Remarketer_Matrix_Obj__c(
                Equipment_Type__c = wrapper.EquipmentType,
                Equipment_Subtype__c = wrapper.EquipmentSubType,
                Return_Warehouse_Code__c = wrapper.WarehouseCode,
                State__c = wrapper.State
            ));
        }

        upsert toUpsert;
        return 'Success: ' + toUpsert.size() + ' records upserted';
    }

    global class RemarketerMatrixWrapper {
        public String EquipmentType;
        public String EquipmentSubType;
        public String State;
        public String WarehouseCode;
    }
}