peac_dev/force-app/main/default/objects/Remarketer_Matrix_Obj__c/Remarketer_Matrix_Obj__c.object-meta.xml
<CustomObject>
    <label>Remarketer Matrix</label>
    <nameField>
        <displayFormat>RM-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Remarketer Matrix</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

peac_dev/force-app/main/default/objects/Remarketer_Matrix_Obj__c/fields/Equipment_Subtype__c.field-meta.xml
<CustomField>
    <fullName>Equipment_Subtype__c</fullName>
    <label>Equipment Subtype</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Equipment_Sub_Category</valueSetName>
    </valueSet>
</CustomField>

peac_dev/force-app/main/default/objects/Remarketer_Matrix_Obj__c/fields/Equipment_Type__c.field-meta.xml
<CustomField>
    <fullName>Equipment_Type__c</fullName>
    <label>Equipment Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Equipment_Type</valueSetName>
    </valueSet>
</CustomField>

peac_dev/force-app/main/default/objects/Remarketer_Matrix_Obj__c/fields/Return_Warehouse_Code__c.field-meta.xml
<CustomField>
    <fullName>Return_Warehouse_Code__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Return Warehouse Code</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

peac_dev/force-app/main/default/classes/SL_RemarketerMatrixTriggerHandlerTest.cls
@isTest
public with sharing class SL_RemarketerMatrixTriggerHandlerTest {
    @isTest
    static void InsertRemarketerMatrix() {

        Schema.Location testLocation = new Schema.Location(Name='ALS');
        insert testLocation;

        Remarketer_Matrix_Obj__c newRM = new Remarketer_Matrix_Obj__c(
                Equipment_Type__c = 'Office Equipment(General)',
                Equipment_Subtype__c = 'Copiers',
                Return_Warehouse_Code__c = 'ALS',
                State__c = 'AK'
            );

        Test.startTest();
        insert newRM;
        Test.stopTest();
    }
    
	@isTest
    static void updateRemarketerMatrix() {

        Schema.Location testLocation = new Schema.Location(Name='ALS');
        insert testLocation;

        Remarketer_Matrix_Obj__c newRM = new Remarketer_Matrix_Obj__c(
                Equipment_Type__c = 'Office Equipment(General)',
                Equipment_Subtype__c = 'Copiers',
                Return_Warehouse_Code__c = 'ALS',
                State__c = 'AK'
            );
		insert newRM;


        Test.startTest();
        newRM.Equipment_Subtype__c = 'ATM';
        update newRM;
        Test.stopTest();
    }
}