peac_dev/force-app/main/default/objects/Escalation_Adjustments__c/Escalation_Adjustments__c.object-meta.xml
<CustomObject>
    <description>Escalation Adjustments captures information of Pool with rates. Data comes from Infolease via data warehouse. Jira ticket DP-1090</description>
    <label>Escalation Adjustments</label>
    <nameField>
        <displayFormat>EP-{0000000}</displayFormat>
        <label>Escalation Adjustments Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Escalation Adjustments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

peac_dev/force-app/main/default/objects/Escalation_Adjustments__c/fields/Adjustment_Method__c.field-meta.xml
<CustomField>
    <fullName>Adjustment_Method__c</fullName>
    <description>Adjustment Method could be Percentage, Fixed or Other</description>
    <label>Adjustment Method</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Percentage</fullName>
                <default>true</default>
                <label>Percentage</label>
            </value>
            <value>
                <fullName>Fixed</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

peac_dev/force-app/main/default/objects/Escalation_Adjustments__c/fields/Adjustment_Value__c.field-meta.xml
<CustomField>
    <fullName>Adjustment_Value__c</fullName>
    <description>Value of the field will be considered as in percentage or specific value like 5% or 10</description>
    <label>Adjustment Value</label>
    <precision>18</precision>
    <scale>5</scale>
    <type>Number</type>
</CustomField>

peac_dev/force-app/main/default/objects/Escalation_Adjustments__c/fields/Audit_Pool__c.field-meta.xml
<CustomField>
    <fullName>Audit_Pool__c</fullName>
    <description>Pool is tagged with every Escalation Adjustment record</description>
    <label>Audit Pool</label>
    <referenceTo>Pool__c</referenceTo>
    <relationshipLabel>Escalation Adjustments</relationshipLabel>
    <relationshipName>Pool_Escalation_Adjustments</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

peac_dev/force-app/main/default/objects/Escalation_Adjustments__c/fields/Change_Value__c.field-meta.xml
<CustomField>
    <fullName>Change_Value__c</fullName>
    <description>In case of Method = percentage, Change = Percentage of Current Rate
In case of Method = Fixed, Change = Adjustment Value
Refer to the use case attached for calculation
Number field with 5 decimals</description>
    <label>Change Value</label>
    <precision>18</precision>
    <scale>5</scale>
    <type>Number</type>
</CustomField>

peac_dev/force-app/main/default/objects/Escalation_Adjustments__c/fields/Effective_Date__c.field-meta.xml
<CustomField>
    <fullName>Effective_Date__c</fullName>
    <description>Denotes the Date from when the Adjustment Current rate is active from.</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Effective Date</label>
    <type>Date</type>
</CustomField>

peac_dev/force-app/main/default/objects/Escalation_Adjustments__c/fields/Escalated_Rate__c.field-meta.xml
<CustomField>
    <fullName>Escalated_Rate__c</fullName>
    <description>New Rate = Current Rate + Adjustment Value
Number field with 5 decimals</description>
    <label>Escalated Rate</label>
    <precision>18</precision>
    <scale>5</scale>
    <type>Number</type>
</CustomField>

peac_dev/force-app/main/default/objects/Pool__c/Pool__c.object-meta.xml
<CustomObject>
    <label>Pool</label>
    <nameField>
        <displayFormat>P-{0000}</displayFormat>
        <label>Pool Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Pools</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

peac_dev/force-app/main/default/objects/Pool__c/fields/Current_Rate__c.field-meta.xml
<CustomField>
    <fullName>Current_Rate__c</fullName>
    <label>Current Rate</label>
    <precision>15</precision>
    <scale>5</scale>
    <type>Number</type>
</CustomField>

peac_dev/force-app/main/default/classes/PEAC_PoolTriggerHelper.cls
/**************************************************************************************************************
@Author:Rajesh Kumar(LTIMindtree)
@Description: This is a PEAC_PoolTriggerHelper class to support 
            PEAC_PoolTriggerHandler
@User Story:DP-1090	 
@Created Date:July-22-2024   
**************************************************************************************************************/
public with sharing class PEAC_PoolTriggerHelper {

     
    /**************************************************************************************************************
    @Author:Rajesh Kumar(LTIMindtree)
    @Description: This method will be called from pool handler class to recalculate the escalation rate
    @User Story:DP-1090	 
    @Created Date:July-22-2024   
    @Param: Set of Pool Ids
    **************************************************************************************************************/
   
    public static void escalationRate(Set<Id> poolsIDSet){
        //list of Escalation records to be updated
        List<Escalation_Adjustments__c> toBeUpdatedEscList = New List<Escalation_Adjustments__c>();
        list<Pool__C> poolEscalationList = getPoolData(poolsIDSet);// get the pool details
                
        for(Pool__c pool:poolEscalationList){
            if(!pool.Pool_Escalation_Adjustments__r.isEmpty()){
                Decimal escalationRate = 0.00000;
                escalationRate = pool.Current_Rate__c;//Assign the current rate to escalation rate
                Integer index = 0;// Initialise index for the Pool's escalation records
                Integer sizeOfAdj = pool.Pool_Escalation_Adjustments__r.size();//get the size of escalation records
                index = getRecordIndex(pool.Pool_Escalation_Adjustments__r);//get the index number of the records from where to be updated
                //loop through the pool's escalation records with latest index
                for(Integer k = index;  k<sizeOfAdj;k++){
                    Escalation_Adjustments__c esc = pool.Pool_Escalation_Adjustments__r[k];//get the escalation record based on index
                    Escalation_Adjustments__c escAdj = calculatEscalation(esc,escalationRate);// call the method to calculate escalation rate
                    escalationRate = escAdj.Escalated_Rate__c;
                    toBeUpdatedEscList.add(escAdj);//Add the escalation record to the list to be updated
                }
            }
        }
        
        if(!toBeUpdatedEscList.isEmpty())
        {
            update toBeUpdatedEscList;//Update the list of escalation records.
        }
    }
    /**************************************************************************************************************
    @Author:Rajesh Kumar(LTIMindtree)
    @Description: Get List of Pool's Records
    @User Story:DP-1090	 
    @Created Date:July-22-2024   
    @Param:Set of Pool ids
    @Return: List of Pool's records
    **************************************************************************************************************/
   
    public static List<Pool__c> getPoolData(Set<Id> poolsIDSet)
    {
        List<Pool__c> poolEscalationList = New List<Pool__c>();
        poolEscalationList = [SELECT Id,Current_Rate__c, (SELECT Id,Adjustment_Method__c,Adjustment_Value__c,Change_Value__c,
                            Effective_Date__c,Escalated_Rate__c FROM Pool_Escalation_Adjustments__r 
                            ORDER BY Effective_Date__c ASC) FROM Pool__c WHERE Id IN:poolsIDSet];
        return poolEscalationList;
    }
    /**************************************************************************************************************
    @Author:Rajesh Kumar(LTIMindtree)
    @Description: Get escalation record index number to start the update from.
    @User Story:DP-1090	 
    @Created Date:July-22-2024   
    @Param:List of Escalation records
    @Return: Integer
    **************************************************************************************************************/
   
    public static Integer getRecordIndex(List<Escalation_Adjustments__c> escalationList)
    {
        Integer index = 0;
        Integer sizeOfAdj = escalationList.size();
        for(Escalation_Adjustments__c escIndex:escalationList){
            index = index + 1;
            Date currentRecDate = escIndex.Effective_Date__c;//Get the current escalation record's date
            Date nextRecDate = escalationList[index].Effective_Date__c;// Get the next escalation records' date
            Integer daysBetween = nextRecDate.daysBetween(System.today());// find the days between next record and today
            //next record's date is in future and today is within the next record's date
            if(nextRecDate > currentRecDate && daysBetween < = 0 ){
                index = index - 1;
                break;
            } 
        }
        return index;
    }
    /**************************************************************************************************************
    @Author:Rajesh Kumar(LTIMindtree)
    @Description: Calculate the escalation rate
    @User Story:DP-1090	 
    @Created Date:July-22-2024   
    @Param: Escalation_Adjustments__c record
    **************************************************************************************************************/
  
    public static Escalation_Adjustments__c calculatEscalation(Escalation_Adjustments__c esc, Decimal escalationRate){
        Escalation_Adjustments__c escAdj = New Escalation_Adjustments__c();
        escAdj.id = esc.id;
        if(esc.Adjustment_Value__c == Null)
        {
           esc.Adjustment_Value__c = 0; 
        }
        //Check for method as Fixed= Escalation Rate + Adjustment Value
        if(esc.Adjustment_Method__c == PEAC_ConstantClass.FIXED){
            escAdj.Change_Value__c  = esc.Adjustment_Value__c + escalationRate;
            escAdj.Escalated_Rate__c = escalationRate + esc.Adjustment_Value__c;
        }
        else {
            //Method as Percentage
            escAdj.Change_Value__c = (esc.Adjustment_Value__c*escalationRate)/100;
            escAdj.Escalated_Rate__c = escalationRate + escAdj.Change_Value__c;
        }
        return escAdj;
    }
}